In [1]:
import csv
import pandas as pd
import talib
import numpy as np

In [2]:
data = pd.read_csv("全數據手動整理.csv")

In [3]:
data

,Date,BTC,trend,ADA,ALGO,ATOM,BAT,BCH,BNB,ZIL,...,LINK,LTC,NEO,QTUM,TRX,VET,XLM,XRP,ZEC,ZRX
0,2019/7/31,"10,080.50",1,0.06009,0.5680,3.649,0.2469,317.42,27.73,0.01094,...,2.21,45.40,11.724,3.058,0.02240,0.005600,0.08385,0.31962,68.10,0.2243
1,2019/8/1,"10,374.10",1,0.05854,0.5620,3.538,0.2364,305.28,28.71,0.01031,...,2.16,44.75,11.862,3.024,0.02212,0.005410,0.08273,0.31550,67.61,0.2195
2,2019/8/2,"10,521.00",1,0.05731,0.8080,3.647,0.2361,310.48,28.09,0.01025,...,2.43,45.12,11.660,3.003,0.02172,0.005481,0.08192,0.31168,66.41,0.2157
3,2019/8/3,"10,814.10",1,0.05774,0.7440,3.690,0.2348,305.8,27.74,0.01018,...,2.41,45.61,12.117,3.043,0.02183,0.005480,0.08236,0.31592,65.15,0.2152
4,2019/8/4,"10,926.50",1,0.05605,0.7050,3.592,0.2359,318.14,27.38,0.01005,...,2.51,47.05,11.880,3.017,0.02229,0.005317,0.08183,0.31817,65.73,0.2115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,2021/7/20,"29,793.50",0,1.05510,0.6962,9.480,0.4665,398.75,264.61,0.05342,...,13.75,107.27,25.836,4.986,0.05052,0.057790,0.21200,0.52860,85.64,0.5476
721,2021/7/21,"32,130.90",0,1.16980,0.7700,10.458,0.5033,430.5,293.09,0.05854,...,15.29,117.64,27.895,5.381,0.05384,0.065960,0.22804,0.57130,95.10,0.6355
722,2021/7/22,"32,297.40",0,1.18590,0.7961,11.382,0.5131,442.04,293.54,0.06209,...,16.08,120.69,28.925,5.598,0.05526,0.067690,0.26342,0.59190,97.47,0.6418
723,2021/7/23,"33,600.00",0,1.20750,0.8079,11.447,0.5248,454.56,298.91,0.06305,...,16.49,124.18,29.553,5.872,0.05597,0.070970,0.26931,0.60910,97.66,0.6495
724,2021/7/24,"33,818.50",0,1.21520,0.8442,11.667,0.5461,455.36,303.14,0.06413,...,16.75,125.56,30.398,6.241,0.05664,0.071900,0.26230,0.60670,98.39,0.6650

In [4]:
data.iloc[4,0]

'2019/8/4'

In [5]:
data2 = pd.read_csv("全數據手動整理.csv")

In [6]:
data = data.dropna()

In [7]:
data['BTC'] = data['BTC'].str.replace(",","")
data['BTC'] = data['BTC'].astype(float)
data['ETH'] = data['ETH'].str.replace(",","") 
data['ETH'] = data['ETH'].astype(float)
data['BCH'] = data['BCH'].str.replace(",","") 
data['BCH'] = data['BCH'].astype(float)

In [8]:
data['BTC']
seven = data.shift(6)

In [9]:
today = data.drop(['Date','BTC','trend'], axis=1)

In [10]:
sevenago = seven.drop(['Date','BTC','trend'], axis=1)

In [11]:
sevenago.head(10)

,ADA,ALGO,ATOM,BAT,BCH,BNB,ZIL,ETH,ICX,IOTA,LINK,LTC,NEO,QTUM,TRX,VET,XLM,XRP,ZEC,ZRX
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.06009,0.568,3.649,0.2469,317.42,27.73,0.01094,218.42,0.2663,0.2900,2.21,45.40,11.724,3.058,0.02240,0.005600,0.08385,0.31962,68.10,0.2243
7,0.05854,0.562,3.538,0.2364,305.28,28.71,0.01031,216.80,0.2503,0.2874,2.16,44.75,11.862,3.024,0.02212,0.005410,0.08273,0.31550,67.61,0.2195
8,0.05731,0.808,3.647,0.2361,310.48,28.09,0.01025,217.69,0.2486,0.2875,2.43,45.12,11.660,3.003,0.02172,0.005481,0.08192,0.31168,66.41,0.2157
9,0.05774,0.744,3.690,0.2348,305.80,27.74,0.01018,222.06,0.2401,0.2832,2.41,45.61,12.117,3.043,0.02183,0.005480,0.08236,0.31592,65.15,0.2152

In [12]:
today = today.astype('float64')

In [13]:
today

,ADA,ALGO,ATOM,BAT,BCH,BNB,ZIL,ETH,ICX,IOTA,LINK,LTC,NEO,QTUM,TRX,VET,XLM,XRP,ZEC,ZRX
0,0.06009,0.5680,3.649,0.2469,317.42,27.73,0.01094,218.42,0.2663,0.2900,2.21,45.40,11.724,3.058,0.02240,0.005600,0.08385,0.31962,68.10,0.2243
1,0.05854,0.5620,3.538,0.2364,305.28,28.71,0.01031,216.80,0.2503,0.2874,2.16,44.75,11.862,3.024,0.02212,0.005410,0.08273,0.31550,67.61,0.2195
2,0.05731,0.8080,3.647,0.2361,310.48,28.09,0.01025,217.69,0.2486,0.2875,2.43,45.12,11.660,3.003,0.02172,0.005481,0.08192,0.31168,66.41,0.2157
3,0.05774,0.7440,3.690,0.2348,305.80,27.74,0.01018,222.06,0.2401,0.2832,2.41,45.61,12.117,3.043,0.02183,0.005480,0.08236,0.31592,65.15,0.2152
4,0.05605,0.7050,3.592,0.2359,318.14,27.38,0.01005,221.81,0.2379,0.2837,2.51,47.05,11.880,3.017,0.02229,0.005317,0.08183,0.31817,65.73,0.2115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,1.05510,0.6962,9.480,0.4665,398.75,264.61,0.05342,1786.03,0.6807,0.5899,13.75,107.27,25.836,4.986,0.05052,0.057790,0.21200,0.52860,85.64,0.5476
721,1.16980,0.7700,10.458,0.5033,430.50,293.09,0.05854,1994.43,0.7456,0.6469,15.29,117.64,27.895,5.381,0.05384,0.065960,0.22804,0.57130,95.10,0.6355
722,1.18590,0.7961,11.382,0.5131,442.04,293.54,0.06209,2024.57,0.7708,0.6513,16.08,120.69,28.925,5.598,0.05526,0.067690,0.26342,0.59190,97.47,0.6418
723,1.20750,0.8079,11.447,0.5248,454.56,298.91,0.06305,2123.93,0.7968,0.6858,16.49,124.18,29.553,5.872,0.05597,0.070970,0.26931,0.60910,97.66,0.6495
724,1.21520,0.8442,11.667,0.5461,455.36,303.14,0.06413,2151.60,0.7959,0.6920,16.75,125.56,30.398,6.241,0.05664,0.071900,0.26230,0.60670,98.39,0.6650

In [14]:
today = today.astype(float, errors = 'raise')

In [15]:
reward = today/sevenago-1  #計算觀察期

In [16]:
reward["BBI"]= data2['trend'] #將牛式與熊式用BBI判斷寫入BBI

In [17]:
reward.head(8)

,ADA,ALGO,ATOM,BAT,BCH,BNB,ZIL,ETH,ICX,IOTA,...,LTC,NEO,QTUM,TRX,VET,XLM,XRP,ZEC,ZRX,BBI
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
6,-0.109336,0.234155,-0.025212,-0.120697,0.035978,-0.002164,-0.154479,0.035986,-0.131806,-0.038966,...,0.054405,-0.031218,-0.041203,-0.029911,-0.129821,-0.064997,-0.025092,-0.082673,-0.114133,1
7,-0.112402,0.229537,-0.012719,-0.062183,0.073932,0.033090,-0.141610,0.042159,-0.126648,-0.040014,...,0.023911,-0.047041,-0.036706,-0.022152,-0.073198,-0.050042,-0.014422,-0.080314,-0.101139,1

In [18]:
# reward.isnull().any()

In [19]:
reward = reward.dropna(axis=0,how='any')   #將NA值拿掉

In [20]:
reward

,ADA,ALGO,ATOM,BAT,BCH,BNB,ZIL,ETH,ICX,IOTA,...,LTC,NEO,QTUM,TRX,VET,XLM,XRP,ZEC,ZRX,BBI
6,-0.109336,0.234155,-0.025212,-0.120697,0.035978,-0.002164,-0.154479,0.035986,-0.131806,-0.038966,...,0.054405,-0.031218,-0.041203,-0.029911,-0.129821,-0.064997,-0.025092,-0.082673,-0.114133,1
7,-0.112402,0.229537,-0.012719,-0.062183,0.073932,0.033090,-0.141610,0.042159,-0.126648,-0.040014,...,0.023911,-0.047041,-0.036706,-0.022152,-0.073198,-0.050042,-0.014422,-0.080314,-0.101139,1
8,-0.091956,-0.100248,-0.100905,-0.111393,0.080810,0.111784,-0.177561,0.017594,-0.129525,-0.041391,...,0.164450,-0.066038,-0.065268,0.013352,-0.089217,-0.059937,-0.010620,-0.057973,-0.126565,1
9,-0.174056,0.090054,-0.147425,-0.151618,0.096109,0.074621,-0.218075,-0.051698,-0.189921,-0.101342,...,0.213330,-0.143600,-0.135393,-0.092075,-0.104745,-0.127853,-0.061598,-0.097928,-0.125000,1
10,-0.073149,0.147518,-0.067650,-0.142009,0.091846,0.082907,-0.169154,-0.069068,-0.149643,-0.081072,...,0.205739,-0.107323,-0.119324,-0.081651,-0.076547,-0.098741,-0.059654,-0.137228,-0.092199,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720,-0.164674,-0.189334,-0.193740,-0.121469,-0.146676,-0.144985,-0.250246,-0.104617,-0.182539,-0.201975,...,-0.181582,-0.213253,-0.195157,-0.156172,-0.203556,-0.116004,-0.147144,-0.180792,-0.235623,0
721,-0.045217,-0.076849,-0.087992,-0.007102,-0.055735,-0.071207,-0.131325,0.040277,-0.053567,-0.065308,...,-0.063898,-0.110434,-0.092121,-0.068995,-0.045303,-0.055031,-0.044009,-0.049095,-0.053611,0
722,0.012119,0.015304,0.020441,-0.066242,0.009132,-0.030773,0.005669,0.077931,0.045720,-0.008223,...,0.000000,-0.025897,0.011199,-0.006115,0.037077,0.120602,0.004412,0.046152,0.038848,0
723,0.030642,0.030091,0.039031,-0.017412,0.043047,-0.004794,0.014318,0.119213,0.006315,-0.002037,...,0.035956,0.000000,0.056305,0.000357,0.084671,0.158522,0.047283,0.048529,0.036216,0
724,0.028175,0.057365,0.062762,0.051608,0.039326,0.003144,0.014394,0.136705,0.038627,0.012881,...,0.053002,0.023226,0.100317,0.012332,0.065501,0.141427,0.033913,0.046925,0.067759,0

In [21]:
reward.reset_index(drop=True, inplace=True)
reward
reward.to_csv('reward.csv', mode='a', header=True)

In [38]:

for i in range(6,len(reward),1):
    num = i
    rd = reward.iloc[i,20]
    if reward.iloc[i,20] == 0:
        print("熊式-----------------------------------")
        print("執行第",i) 
        q = reward.iloc[i:i+1,:20]  #取BBI值
#         print(q)
        a = q.T               #將資料行轉列                 
#         print(a)
#         print("執行第",i)    
        c = a.sort_values(by=[i]) #將資料排序
        print(c)
        d = c.T            #將資料行轉列

        e = d.iloc[:,0:5]    #取後五筆資料
#         print(e)
        f= list(e.columns)    #將資料存進串列
#         print(f)
        g = data.reindex(columns=f)   #更改資料欄未名稱
        print("g================================================================", g.shift(-13)  )
        h = g / g.shift(7) - 1  #計算報酬
        
        i = h.iloc[i-6,:]
        print(i)
        p = i.sum()/5
        print("報酬",p,"%")
        result3 = pd.DataFrame(np.array([i]),
                   columns=f)
        result3.to_csv('all.csv', mode='a', header=True)
        print("i=",i)
        date = data.iloc[num,0]
#         date = str(date)
        datee = pd.Series(date)
        datee.to_csv('date.csv', mode='a', header=True)
    else :
        print("牛式===============================")
        print("執行第",i)     
        q = reward.iloc[i:i+1,:20] 
        a = q.T 
        c = a.sort_values(by=[i]) 
        print(c)
        d = c.T 
        e = d.iloc[:,15:20] 
        f= list(e.columns)
#         print(f)
        g = data.reindex(columns=f)
        print("g================================================================", g.shift(13)  )
        h = g.shift(-13)  / g.shift(-7) - 1 

#         print(h.head(25))
        i = h.iloc[i-6,:]
        print(i)
        p = i.sum()/5
        print("報酬",p,"%")
        result2 = pd.DataFrame(np.array([i]),
                   columns=f)
        result2.to_csv('all.csv', mode='a', header=True)
        print("i=",i)

        date = data.iloc[num,0]
#         date = str(date)
        datee = pd.Series(date)
        datee.to_csv('date.csv', mode='a', header=True)

牛式===============================
執行第 0
             0
ZIL  -0.154479
ICX  -0.131806
VET  -0.129821
BAT  -0.120697
ZRX  -0.114133
ADA  -0.109336
ZEC  -0.082673
XLM  -0.064997
QTUM -0.041203
IOTA -0.038966
NEO  -0.031218
TRX  -0.029911
ATOM -0.025212
XRP  -0.025092
BNB  -0.002164
BCH   0.035978
ETH   0.035986
LTC   0.054405
LINK  0.117647
ALGO  0.234155
g================================================================         BCH      ETH     LTC   LINK    ALGO
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  509.55  2316.15  137.39  19.79  0.9062
721  490.60  2121.52  132.25  18.44  0.8683
722  504.08  2146.27  134.42  18.66  0.9059
723  497.02  2111.19  134.00  18.20  0.8918
724  498.00  2138.86  134.19  18.38  0.8952

[725 rows x 5 columns]
BCH    NaN
ETH    NaN
LTC    NaN
LINK   NaN
ALGO   NaN
Name: 719, dtype: float64
報酬 0.0 %
i= BCH    NaN
ETH    NaN
LTC    NaN
LINK   NaN
ALGO   NaN
Name: 719, dtype: float64
牛式===============================
執行第 1
             1
ZIL  -0.141610
ICX  -0.126648
ADA  -0.112402
ZRX  -0.101139
ZEC  -0.080314
VET  -0.073198
BAT  -0.062183
XLM  -0.050042
NEO  -0.047041
IOTA -0.040014
QTUM -0.036706
TRX  -0.022152
XRP  -0.014422
ATOM -0.012719
LTC   0.023911
BNB   0.033090
ETH   0.042159
BCH   0.073932
LINK  0.101852
ALGO  0.229537
g================================================================         BNB      ETH     BCH   LINK    ALGO
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  327.67  2316.15  509.55  19.79  0.9062
721  310.59  2121.52  490.60  18.44  0.8683
722  316.72  2146.27  504.08  18.66  0.9059
723  316.09  2111.19  497.02  18.20  0.8918
724  321.87  2138.86  498.00  18.38  0.8952

[725 rows x 5 columns]
BNB    NaN
ETH    NaN
BCH    NaN
LINK   NaN
ALGO   NaN
Name: 720, dtype: float64
報酬 0.0 %
i= BNB    NaN
ETH    NaN
BCH    NaN
LINK   NaN
ALGO   NaN
Name: 720, dtype: float64
牛式===============================
執行第 2
             2
ZIL  -0.177561
ICX  -0.129525
ZRX  -0.126565
BAT  -0.111393
ATOM -0.100905
ALGO -0.100248
ADA  -0.091956
VET  -0.089217
NEO  -0.066038
QTUM -0.065268
LINK -0.061728
XLM  -0.059937
ZEC  -0.057973
IOTA -0.041391
XRP  -0.010620
TRX   0.013352
ETH   0.017594
BCH   0.080810
BNB   0.111784
LTC   0.164450
g================================================================          TRX      ETH     BCH     BNB     LTC
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.06432  2316.15  509.55  327.67  137.39
721  0.06111  2121.52  490.60  310.59  132.25
722  0.06219  2146.27  504.08  316.72  134.42
723  0.06139  2111.19  497.02  316.09  134.00
724  0.06184  2138.86  498.00  321.87  134.19

[725 rows x 5 columns]
TRX   NaN
ETH   NaN
BCH   NaN
BNB   NaN
LTC   NaN
Name: 721, dtype: float64
報酬 0.0 %
i= TRX   NaN
ETH   NaN
BCH   NaN
BNB   NaN
LTC   NaN
Name: 721, dtype: float64
牛式===============================
執行第 3
             3
ZIL  -0.218075
ICX  -0.189921
ADA  -0.174056
BAT  -0.151618
ATOM -0.147425
NEO  -0.143600
QTUM -0.135393
XLM  -0.127853
ZRX  -0.125000
VET  -0.104745
IOTA -0.101342
LINK -0.099585
ZEC  -0.097928
TRX  -0.092075
XRP  -0.061598
ETH  -0.051698
BNB   0.074621
ALGO  0.090054
BCH   0.096109
LTC   0.213330
g================================================================          ETH     BNB    ALGO     BCH     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  327.67  0.9062  509.55  137.39
721  2121.52  310.59  0.8683  490.60  132.25
722  2146.27  316.72  0.9059  504.08  134.42
723  2111.19  316.09  0.8918  497.02  134.00
724  2138.86  321.87  0.8952  498.00  134.19

[725 rows x 5 columns]
ETH    NaN
BNB    NaN
ALGO   NaN
BCH    NaN
LTC    NaN
Name: 722, dtype: float64
報酬 0.0 %
i= ETH    NaN
BNB    NaN
ALGO   NaN
BCH    NaN
LTC    NaN
Name: 722, dtype: float64
牛式===============================
執行第 4
             4
ZIL  -0.169154
ICX  -0.149643
BAT  -0.142009
ZEC  -0.137228
QTUM -0.119324
NEO  -0.107323
XLM  -0.098741
ZRX  -0.092199
TRX  -0.081651
IOTA -0.081072
VET  -0.076547
ADA  -0.073149
LINK -0.071713
ETH  -0.069068
ATOM -0.067650
XRP  -0.059654
BNB   0.082907
BCH   0.091846
ALGO  0.147518
LTC   0.205739
g================================================================         XRP     BNB     BCH    ALGO     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6521  327.67  509.55  0.9062  137.39
721  0.6236  310.59  490.60  0.8683  132.25
722  0.6372  316.72  504.08  0.9059  134.42
723  0.6251  316.09  497.02  0.8918  134.00
724  0.6362  321.87  498.00  0.8952  134.19

[725 rows x 5 columns]
XRP    NaN
BNB    NaN
BCH    NaN
ALGO   NaN
LTC    NaN
Name: 723, dtype: float64
報酬 0.0 %
i= XRP    NaN
BNB    NaN
BCH    NaN
ALGO   NaN
LTC    NaN
Name: 723, dtype: float64
牛式===============================
執行第 5
             5
ICX  -0.142977
BAT  -0.112302
QTUM -0.103426
ZEC  -0.101934
TRX  -0.094323
ZIL  -0.093117
ZRX  -0.088041
IOTA -0.074545
NEO  -0.073081
ETH  -0.071897
ATOM -0.058402
XRP  -0.058011
XLM  -0.050638
ADA  -0.025700
VET  -0.021415
LINK -0.016260
BCH   0.022736
ALGO  0.034091
BNB   0.083304
LTC   0.147988
g================================================================       LINK     BCH    ALGO     BNB     LTC
0      NaN     NaN     NaN     NaN     NaN
1      NaN     NaN     NaN     NaN     NaN
2      NaN     NaN     NaN     NaN     NaN
3      NaN     NaN     NaN     NaN     NaN
4      NaN     NaN     NaN     NaN     NaN
..     ...     ...     ...     ...     ...
720  19.79  509.55  0.9062  327.67  137.39
721  18.44  490.60  0.8683  310.59  132.25
722  18.66  504.08  0.9059  316.72  134.42
723  18.20  497.02  0.8918  316.09  134.00
724  18.38  498.00  0.8952  321.87  134.19

[725 rows x 5 columns]
LINK   NaN
BCH    NaN
ALGO   NaN
BNB    NaN
LTC    NaN
Name: 724, dtype: float64
報酬 0.0 %
i= LINK   NaN
BCH    NaN
ALGO   NaN
BNB    NaN
LTC    NaN
Name: 724, dtype: float64
牛式===============================
執行第 6
             6
ICX  -0.130623
ZEC  -0.089963
QTUM -0.077080
IOTA -0.069609
ETH  -0.065450
BAT  -0.061262
ATOM -0.060725
NEO  -0.058725
ZRX  -0.054353
TRX  -0.047860
ZIL  -0.047568
XLM  -0.038520
XRP  -0.035751
LINK -0.032389
ADA  -0.008969
BCH   0.029163
VET   0.046788
BNB   0.090351
ALGO  0.145506
LTC   0.208899
g================================================================         BCH      VET     BNB    ALGO     LTC
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  509.55  0.08348  327.67  0.9062  137.39
721  490.60  0.07614  310.59  0.8683  132.25
722  504.08  0.07704  316.72  0.9059  134.42
723  497.02  0.07591  316.09  0.8918  134.00
724  498.00  0.07768  321.87  0.8952  134.19

[725 rows x 5 columns]
BCH     0.019033
VET    -0.019545
BNB    -0.008092
ALGO    0.170767
LTC     0.235050
Name: 0, dtype: float64
報酬 0.07944266318578967 %
i= BCH     0.019033
VET    -0.019545
BNB    -0.008092
ALGO    0.170767
LTC     0.235050
Name: 0, dtype: float64
牛式===============================
執行第 7
             7
BAT  -0.110510
ZEC  -0.108234
QTUM -0.093031
ICX  -0.084172
ZRX  -0.080588
ETH  -0.074002
NEO  -0.071656
IOTA -0.070678
ATOM -0.067277
XLM  -0.053060
TRX  -0.052705
XRP  -0.042065
VET  -0.019545
BNB  -0.008092
ZIL  -0.006780
ADA   0.012702
LINK  0.016807
BCH   0.019033
ALGO  0.170767
LTC   0.235050
g================================================================         ADA   LINK     BCH    ALGO     LTC
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  1.4039  19.79  509.55  0.9062  137.39
721  1.3327  18.44  490.60  0.8683  132.25
722  1.3497  18.66  504.08  0.9059  134.42
723  1.3356  18.20  497.02  0.8918  134.00
724  1.3478  18.38  498.00  0.8952  134.19

[725 rows x 5 columns]
ADA    -0.093966
LINK    0.000000
BCH    -0.061030
ALGO   -0.013755
LTC     0.043396
Name: 1, dtype: float64
報酬 -0.025071263060880655 %
i= ADA    -0.093966
LINK    0.000000
BCH    -0.061030
ALGO   -0.013755
LTC     0.043396
Name: 1, dtype: float64
牛式===============================
執行第 8
             8
BAT  -0.198284
TRX  -0.192185
ZEC  -0.191816
QTUM -0.163876
IOTA -0.157475
ETH  -0.155336
XRP  -0.145896
ICX  -0.139556
ZRX  -0.138004
BNB  -0.135126
NEO  -0.134343
ATOM -0.128698
XLM  -0.101156
ZIL  -0.096085
ADA  -0.093966
VET  -0.072917
BCH  -0.061030
ALGO -0.013755
LINK  0.000000
LTC   0.043396
g================================================================          VET     BCH    ALGO   LINK     LTC
0        NaN     NaN     NaN    NaN     NaN
1        NaN     NaN     NaN    NaN     NaN
2        NaN     NaN     NaN    NaN     NaN
3        NaN     NaN     NaN    NaN     NaN
4        NaN     NaN     NaN    NaN     NaN
..       ...     ...     ...    ...     ...
720  0.08348  509.55  0.9062  19.79  137.39
721  0.07614  490.60  0.8683  18.44  132.25
722  0.07704  504.08  0.9059  18.66  134.42
723  0.07591  497.02  0.8918  18.20  134.00
724  0.07768  498.00  0.8952  18.38  134.19

[725 rows x 5 columns]
VET    -0.066449
BCH    -0.056953
ALGO   -0.124538
LINK    0.115207
LTC     0.022768
Name: 2, dtype: float64
報酬 -0.021992782466283823 %

i= VET    -0.066449
BCH    -0.056953
ALGO   -0.124538
LINK    0.115207
LTC     0.022768
Name: 2, dtype: float64
牛式===============================
執行第 9
             9
ZEC  -0.139527
ALGO -0.124538
TRX  -0.116044
XRP  -0.109222
ETH  -0.106468
QTUM -0.096921
ATOM -0.078830
ZRX  -0.078067
VET  -0.066449
BAT  -0.061245
ZIL  -0.059045
BNB  -0.057028
BCH  -0.056953
NEO  -0.046256
IOTA -0.045972
XLM  -0.022832
ADA  -0.007549
LTC   0.022768
ICX   0.033933
LINK  0.115207
g================================================================          XLM     ADA     LTC     ICX   LINK
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  0.25677  1.4039  137.39  0.9279  19.79
721  0.24383  1.3327  132.25  1.0350  18.44
722  0.24550  1.3497  134.42  0.9786  18.66
723  0.24484  1.3356  134.00  0.9198  18.20
724  0.24587  1.3478  134.19  0.9519  18.38

[725 rows x 5 columns]
XLM    -0.071051
ADA    -0.101444
LTC    -0.025560
ICX    -0.048443
LINK   -0.012876
Name: 3, dtype: float64
報酬 -0.05187453099595789 %
i= XLM    -0.071051
ADA    -0.101444
LTC    -0.025560
ICX    -0.048443
LINK   -0.012876
Name: 3, dtype: float64
牛式===============================
執行第 10
            10
TRX  -0.175379
ALGO -0.163164
ATOM -0.138847
ZEC  -0.138600
QTUM -0.137749
XRP  -0.129149
ZIL  -0.123353
BAT  -0.116601
ETH  -0.103928
ADA  -0.101444
ZRX  -0.088021
VET  -0.084929
IOTA -0.074415
NEO  -0.074210
BNB  -0.071501
XLM  -0.071051
ICX  -0.048443
LTC  -0.025560
BCH  -0.024038
LINK -0.012876
g================================================================          XLM     ICX     LTC     BCH   LINK
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  0.25677  0.9279  137.39  509.55  19.79
721  0.24383  1.0350  132.25  490.60  18.44
722  0.24550  0.9786  134.42  504.08  18.66
723  0.24484  0.9198  134.00  497.02  18.20
724  0.24587  0.9519  134.19  498.00  18.38

[725 rows x 5 columns]
XLM    -0.134050
ICX    -0.036585
LTC     0.004675
BCH    -0.017558
LINK   -0.008264
Name: 4, dtype: float64
報酬 -0.03835667177931792 %
i= XLM    -0.134050
ICX    -0.036585
LTC     0.004675
BCH    -0.017558
LINK   -0.008264
Name: 4, dtype: float64
牛式===============================
執行第 11
            11
TRX  -0.184185
ATOM -0.179588
ALGO -0.166056
ZEC  -0.165248
BAT  -0.148238
ETH  -0.143628
ADA  -0.137711
ZIL  -0.137277
XLM  -0.134050
NEO  -0.132274
VET  -0.129738
XRP  -0.125408
ZRX  -0.116675
QTUM -0.114996
IOTA -0.100965
BNB  -0.092409
ICX  -0.036585
BCH  -0.017558
LINK -0.008264
LTC   0.004675
g================================================================         BNB     ICX     BCH   LINK     LTC
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  327.67  0.9279  509.55  19.79  137.39
721  310.59  1.0350  490.60  18.44  132.25
722  316.72  0.9786  504.08  18.66  134.42
723  316.09  0.9198  497.02  18.20  134.00
724  321.87  0.9519  498.00  18.38  134.19

[725 rows x 5 columns]
BNB    -0.074577
ICX    -0.007463
BCH     0.025766
LINK    0.046025
LTC     0.011232
Name: 5, dtype: float64
報酬 0.00019662648948699514 %
i= BNB    -0.074577
ICX    -0.007463
BCH     0.025766
LINK    0.046025
LTC     0.011232
Name: 5, dtype: float64
牛式===============================
執行第 12
            12
ALGO -0.158157
TRX  -0.140648
VET  -0.118800
ATOM -0.110745
ZIL  -0.106697
BAT  -0.094701
ETH  -0.080910
NEO  -0.079319
BNB  -0.074577
ZEC  -0.074406
ZRX  -0.067589
XLM  -0.061820
QTUM -0.058758
XRP  -0.057312
IOTA -0.046664
ADA  -0.045626
ICX  -0.007463
LTC   0.011232
BCH   0.025766
LINK  0.046025
g================================================================         ADA     ICX     LTC     BCH   LINK
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  1.4039  0.9279  137.39  509.55  19.79
721  1.3327  1.0350  132.25  490.60  18.44
722  1.3497  0.9786  134.42  504.08  18.66
723  1.3356  0.9198  134.00  497.02  18.20
724  1.3478  0.9519  134.19  498.00  18.38

[725 rows x 5 columns]
ADA    -0.049411
ICX    -0.026973
LTC     0.081286
BCH    -0.067018
LINK    0.028926
Name: 6, dtype: float64
報酬 -0.006637940119513064 %
i= ADA    -0.049411
ICX    -0.026973
LTC     0.081286
BCH    -0.067018
LINK    0.028926
Name: 6, dtype: float64
牛式===============================
執行第 13
            13
ALGO -0.190358
TRX  -0.123963
ZIL  -0.121729
ATOM -0.112339
BCH  -0.067018
BAT  -0.063895
XRP  -0.053815
VET  -0.052075
ADA  -0.049411
ZRX  -0.038037
XLM  -0.036415
NEO  -0.035163
ETH  -0.033697
ICX  -0.026973
BNB  -0.021754
ZEC  -0.020739
IOTA -0.020671
QTUM  0.017790
LINK  0.028926
LTC   0.081286
g================================================================         ZEC    IOTA   QTUM   LINK     LTC
0       NaN     NaN    NaN    NaN     NaN
1       NaN     NaN    NaN    NaN     NaN
2       NaN     NaN    NaN    NaN     NaN
3       NaN     NaN    NaN    NaN     NaN
4       NaN     NaN    NaN    NaN     NaN
..      ...     ...    ...    ...     ...
720  118.51  0.8896  7.079  19.79  137.39
721  109.38  0.8165  6.504  18.44  132.25
722  110.99  0.8180  6.776  18.66  134.42
723  108.15  0.7913  6.639  18.20  134.00
724  110.82  0.8404  6.694  18.38  134.19

[725 rows x 5 columns]
ZEC     0.028481
IOTA    0.072351
QTUM    0.111632
LINK    0.035088
LTC     0.103612
Name: 7, dtype: float64
報酬 0.07023276882430282 %
i= ZEC     0.028481
IOTA    0.072351
QTUM    0.111632
LINK    0.035088
LTC     0.103612
Name: 7, dtype: float64
牛式===============================
執行第 14
            14
ALGO -0.126918
ZIL  -0.017060
VET  -0.016854
TRX  -0.014623
XLM  -0.008090
BCH  -0.002602
ATOM  0.003150
ZEC   0.028481
LINK  0.035088
ZRX   0.035099
BNB   0.036283
XRP   0.040208
ADA   0.042842
NEO   0.048690
ETH   0.048902
ICX   0.049946
BAT   0.064804
IOTA  0.072351
LTC   0.103612
QTUM  0.111632
g================================================================         ICX     BAT    IOTA     LTC   QTUM
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  0.9279  0.6135  0.8896  137.39  7.079
721  1.0350  0.5691  0.8165  132.25  6.504
722  0.9786  0.5695  0.8180  134.42  6.776
723  0.9198  0.5575  0.7913  134.00  6.639
724  0.9519  0.5623  0.8404  134.19  6.694

[725 rows x 5 columns]
ICX    -0.057683
BAT    -0.021390
IOTA   -0.011944
LTC     0.045406
QTUM    0.047559
Name: 8, dtype: float64
報酬 0.0003896353855876944 %
i= ICX    -0.057683
BAT    -0.021390
IOTA   -0.011944
LTC     0.045406
QTUM    0.047559
Name: 8, dtype: float64
牛式===============================
執行第 15
            15
ALGO -0.201408
LINK -0.086777
ATOM -0.079710
ICX  -0.057683
ZIL  -0.048064
XLM  -0.046730
VET  -0.046070
NEO  -0.044054
BNB  -0.041622
TRX  -0.041096
BCH  -0.022714
BAT  -0.021390
ZEC  -0.015424
IOTA -0.011944
ZRX  -0.006912
ETH  -0.003189
ADA  -0.000211
XRP   0.007536
LTC   0.045406
QTUM  0.047559
g================================================================          ETH     ADA     XRP     LTC   QTUM
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  2316.15  1.4039  0.6521  137.39  7.079
721  2121.52  1.3327  0.6236  132.25  6.504
722  2146.27  1.3497  0.6372  134.42  6.776
723  2111.19  1.3356  0.6251  134.00  6.639
724  2138.86  1.3478  0.6362  134.19  6.694

[725 rows x 5 columns]
ETH     0.029455
ADA     0.054627
XRP     0.037843
LTC     0.076881
QTUM    0.108686
Name: 9, dtype: float64
報酬 0.06149849028089509 %
i= ETH     0.029455
ADA     0.054627
XRP     0.037843
LTC     0.076881
QTUM    0.108686
Name: 9, dtype: float64
牛式===============================
執行第 16
            16
ALGO -0.153619
BCH  -0.095749
ATOM -0.058599
LINK -0.034783
BNB  -0.020341
VET  -0.006454
XLM  -0.004671
NEO  -0.002444
ZRX   0.003998
ZIL   0.021858
ETH   0.029455
TRX   0.029621
XRP   0.037843
ZEC   0.039304
ADA   0.054627
LTC   0.076881
IOTA  0.082056
QTUM  0.108686
BAT   0.116331
ICX   0.170390
g================================================================         LTC    IOTA   QTUM     BAT     ICX
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  137.39  0.8896  7.079  0.6135  0.9279
721  132.25  0.8165  6.504  0.5691  1.0350
722  134.42  0.8180  6.776  0.5695  0.9786
723  134.00  0.7913  6.639  0.5575  0.9198
724  134.19  0.8404  6.694  0.5623  0.9519

[725 rows x 5 columns]
LTC     0.078561
IOTA    0.070190
QTUM    0.060285
BAT     0.145125
ICX     0.226329
Name: 10, dtype: float64
報酬 0.1160980182236873 %
i= LTC     0.078561
IOTA    0.070190
QTUM    0.060285
BAT     0.145125
ICX     0.226329
Name: 10, dtype: float64
牛式===============================
執行第 17
            17
ALGO -0.159590
ATOM -0.066667
LINK -0.066667
BCH  -0.038925
ZIL  -0.024580
BNB  -0.019636
ZEC   0.016797
XLM   0.022157
NEO   0.022457
VET   0.031432
XRP   0.042685
ETH   0.045310
ADA   0.047046
QTUM  0.060285
TRX   0.063830
IOTA  0.070190
LTC   0.078561
ZRX   0.080655
BAT   0.145125
ICX   0.226329
g================================================================        IOTA     LTC     ZRX     BAT     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.8896  137.39  0.7889  0.6135  0.9279
721  0.8165  132.25  0.8190  0.5691  1.0350
722  0.8180  134.42  0.8384  0.5695  0.9786
723  0.7913  134.00  0.7890  0.5575  0.9198
724  0.8404  134.19  0.7950  0.5623  0.9519

[725 rows x 5 columns]
IOTA    0.044094
LTC     0.000342
ZRX     0.055936
BAT     0.100271
ICX     0.213033
Name: 11, dtype: float64
報酬 0.0827350543710732 %
i= IOTA    0.044094
LTC     0.000342
ZRX     0.055936
BAT     0.100271
ICX     0.213033
Name: 11, dtype: float64
牛式===============================
執行第 18
            18
ALGO -0.146450
LINK -0.132000
ATOM -0.093235
BCH  -0.064756
BNB  -0.058739
ZEC  -0.047891
XRP  -0.042261
ETH  -0.019346
ADA  -0.009680
XLM  -0.005232
TRX  -0.002812
LTC   0.000342
QTUM  0.001178
NEO   0.026313
IOTA  0.044094
ZRX   0.055936
VET   0.091212
ZIL   0.091487
BAT   0.100271
ICX   0.213033
g================================================================         ZRX      VET      ZIL     BAT     ICX
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.7889  0.08348  0.08133  0.6135  0.9279
721  0.8190  0.07614  0.07509  0.5691  1.0350
722  0.8384  0.07704  0.07496  0.5695  0.9786
723  0.7890  0.07591  0.07299  0.5575  0.9198
724  0.7950  0.07768  0.07377  0.5623  0.9519

[725 rows x 5 columns]
ZRX    0.027507
VET   -0.038412
ZIL    0.018135
BAT    0.038462
ICX    0.147331
Name: 12, dtype: float64
報酬 0.038604399025278326 %
i= ZRX    0.027507
VET   -0.038412
ZIL    0.018135
BAT    0.038462
ICX    0.147331
Name: 12, dtype: float64
牛式===============================
執行第 19
            19
ALGO -0.178626
LINK -0.164659
ATOM -0.095090
BNB  -0.093120
ETH  -0.077558
ZEC  -0.075506
QTUM -0.056155
NEO  -0.045728
XRP  -0.043535
VET  -0.038412
XLM  -0.033747
LTC  -0.031051
TRX  -0.027298
ADA  -0.010796
BCH   0.010587
ZIL   0.018135
ZRX   0.027507
BAT   0.038462
IOTA  0.061728
ICX   0.147331
g================================================================          ZIL     ZRX     BAT    IOTA     ICX
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08133  0.7889  0.6135  0.8896  0.9279
721  0.07509  0.8190  0.5691  0.8165  1.0350
722  0.07496  0.8384  0.5695  0.8180  0.9786
723  0.07299  0.7890  0.5575  0.7913  0.9198
724  0.07377  0.7950  0.5623  0.8404  0.9519

[725 rows x 5 columns]
ZIL     0.118825
ZRX     0.056514
BAT     0.046901
IOTA    0.079518
ICX     0.228645
Name: 13, dtype: float64
報酬 0.10608056520093956 %
i= ZIL     0.118825
ZRX     0.056514
BAT     0.046901
IOTA    0.079518
ICX     0.228645
Name: 13, dtype: float64
牛式===============================
執行第 20
            20
ALGO -0.166134
LINK -0.122881
ATOM -0.087230
BNB  -0.066810
ETH  -0.038826
QTUM -0.028747
BCH  -0.026347
XRP  -0.012629
ZEC  -0.010192
NEO  -0.006069
VET   0.001319
LTC   0.005950
TRX   0.009132
ADA   0.009559
XLM   0.014565
BAT   0.046901
ZRX   0.056514
IOTA  0.079518
ZIL   0.118825
ICX   0.228645
g================================================================         BAT     ZRX    IOTA      ZIL     ICX
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6135  0.7889  0.8896  0.08133  0.9279
721  0.5691  0.8190  0.8165  0.07509  1.0350
722  0.5695  0.8384  0.8180  0.07496  0.9786
723  0.5575  0.7890  0.7913  0.07299  0.9198
724  0.5623  0.7950  0.8404  0.07377  0.9519

[725 rows x 5 columns]
BAT     0.033333
ZRX    -0.000580
IOTA    0.084619
ZIL     0.120617
ICX     0.172032
Name: 14, dtype: float64
報酬 0.08200413021556115 %
i= BAT     0.033333
ZRX    -0.000580
IOTA    0.084619
ZIL     0.120617
ICX     0.172032
Name: 14, dtype: float64
牛式===============================
執行第 21
            21
ALGO -0.075838
BNB  -0.049740
LINK -0.045249
ATOM -0.036745
QTUM -0.006830
ETH  -0.001653
ZRX  -0.000580
BCH   0.009873
LTC   0.011323
XRP   0.013380
NEO   0.014058
ZEC   0.014260
XLM   0.023763
BAT   0.033333
VET   0.039139
TRX   0.048810
ADA   0.054100
IOTA  0.084619
ZIL   0.120617
ICX   0.172032
g================================================================          TRX     ADA    IOTA      ZIL     ICX
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.06432  1.4039  0.8896  0.08133  0.9279
721  0.06111  1.3327  0.8165  0.07509  1.0350
722  0.06219  1.3497  0.8180  0.07496  0.9786
723  0.06139  1.3356  0.7913  0.07299  0.9198
724  0.06184  1.3478  0.8404  0.07377  0.9519

[725 rows x 5 columns]
TRX    -0.079977
ADA    -0.068251
IOTA   -0.071620
ZIL    -0.037433
ICX    -0.091877
Name: 15, dtype: float64
報酬 -0.0698317544307224 %
i= TRX    -0.079977
ADA    -0.068251
IOTA   -0.071620
ZIL    -0.037433
ICX    -0.091877
Name: 15, dtype: float64
牛式===============================
執行第 22
            22
ALGO -0.240838
LINK -0.148649
ATOM -0.144751
BNB  -0.133852
QTUM -0.124409
ZRX  -0.097838
ICX  -0.091877
ETH  -0.091453
BAT  -0.086172
ZEC  -0.085681
TRX  -0.079977
IOTA -0.071620
ADA  -0.068251
NEO  -0.066265
XLM  -0.061153
XRP  -0.051884
VET  -0.050627
ZIL  -0.037433
LTC  -0.008903
BCH   0.029653
g================================================================         XRP      VET      ZIL     LTC     BCH
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.6521  0.08348  0.08133  137.39  509.55
721  0.6236  0.07614  0.07509  132.25  490.60
722  0.6372  0.07704  0.07496  134.42  504.08
723  0.6251  0.07591  0.07299  134.00  497.02
724  0.6362  0.07768  0.07377  134.19  498.00

[725 rows x 5 columns]
XRP   -0.071434
VET   -0.117980
ZIL   -0.068966
LTC   -0.024722
BCH   -0.037886
Name: 16, dtype: float64
報酬 -0.06419740415179176 %
i= XRP   -0.071434
VET   -0.117980
ZIL   -0.068966
LTC   -0.024722
BCH   -0.037886
Name: 16, dtype: float64
牛式===============================
執行第 23
            23
ALGO -0.301394
LINK -0.205357
ATOM -0.204713
BNB  -0.192136
QTUM -0.192086
ZRX  -0.164413
BAT  -0.157921
TRX  -0.140556
ETH  -0.129471
ICX  -0.126755
VET  -0.117980
ZEC  -0.115438
NEO  -0.113563
XLM  -0.109538
ADA  -0.103365
XRP  -0.071434
ZIL  -0.068966
BCH  -0.037886
IOTA -0.034336
LTC  -0.024722
g================================================================         XRP      ZIL     BCH    IOTA     LTC
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.6521  0.08133  509.55  0.8896  137.39
721  0.6236  0.07509  490.60  0.8165  132.25
722  0.6372  0.07496  504.08  0.8180  134.42
723  0.6251  0.07299  497.02  0.7913  134.00
724  0.6362  0.07377  498.00  0.8404  134.19

[725 rows x 5 columns]
XRP    -0.058503
ZIL    -0.183935
BCH    -0.058521
IOTA   -0.022859
LTC     0.050905
Name: 17, dtype: float64
報酬 -0.0545824719062598 %
i= XRP    -0.058503
ZIL    -0.183935
BCH    -0.058521
IOTA   -0.022859
LTC     0.050905
Name: 17, dtype: float64
牛式===============================
執行第 24
            24
ALGO -0.275563
ATOM -0.200817
ZIL  -0.183935
LINK -0.170507
VET  -0.169215
QTUM -0.169020
BNB  -0.158295
NEO  -0.136112
BAT  -0.123153
TRX  -0.122955
ICX  -0.121074
XLM  -0.119972
ETH  -0.116422
ZRX  -0.112973
ZEC  -0.110978
ADA  -0.107520
BCH  -0.058521
XRP  -0.058503
IOTA -0.022859
LTC   0.050905
g================================================================         ADA     BCH     XRP    IOTA     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  1.4039  509.55  0.6521  0.8896  137.39
721  1.3327  490.60  0.6236  0.8165  132.25
722  1.3497  504.08  0.6372  0.8180  134.42
723  1.3356  497.02  0.6251  0.7913  134.00
724  1.3478  498.00  0.6362  0.8404  134.19

[725 rows x 5 columns]
ADA    -0.096403
BCH    -0.012635
XRP    -0.044664
IOTA   -0.075394
LTC     0.020408
Name: 18, dtype: float64
報酬 -0.041737383288731465 %
i= ADA    -0.096403
BCH    -0.012635
XRP    -0.044664
IOTA   -0.075394
LTC     0.020408
Name: 18, dtype: float64
牛式===============================
執行第 25
            25
ALGO -0.237918
ATOM -0.229270
BNB  -0.193103
QTUM -0.174153
LINK -0.144231
ZIL  -0.118321
TRX  -0.113975
ZEC  -0.111554
XLM  -0.106076
ADA  -0.096403
ZRX  -0.095371
NEO  -0.090147
VET  -0.087257
ICX  -0.080984
ETH  -0.080272
BAT  -0.076682
IOTA -0.075394
XRP  -0.044664
BCH  -0.012635
LTC   0.020408
g================================================================         BAT    IOTA     XRP     BCH     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6135  0.8896  0.6521  509.55  137.39
721  0.5691  0.8165  0.6236  490.60  132.25
722  0.5695  0.8180  0.6372  504.08  134.42
723  0.5575  0.7913  0.6251  497.02  134.00
724  0.5623  0.8404  0.6362  498.00  134.19

[725 rows x 5 columns]
BAT    -0.036800
IOTA   -0.106399
XRP    -0.054009
BCH     0.007843
LTC     0.008709
Name: 19, dtype: float64
報酬 -0.0361311997090082 %
i= BAT    -0.036800
IOTA   -0.106399
XRP    -0.054009
BCH     0.007843
LTC     0.008709
Name: 19, dtype: float64
牛式===============================
執行第 26
            26
ALGO -0.256705
ATOM -0.188073
BNB  -0.179556
QTUM -0.173244
ZIL  -0.159905
LINK -0.144928
ICX  -0.129475
TRX  -0.123303
ZEC  -0.121624
ADA  -0.108582
XLM  -0.108240
NEO  -0.108182
IOTA -0.106399
VET  -0.101185
ZRX  -0.094595
ETH  -0.094572
XRP  -0.054009
BAT  -0.036800
BCH   0.007843
LTC   0.008709
g================================================================          ETH     XRP     BAT     BCH     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  0.6521  0.6135  509.55  137.39
721  2121.52  0.6236  0.5691  490.60  132.25
722  2146.27  0.6372  0.5695  504.08  134.42
723  2111.19  0.6251  0.5575  497.02  134.00
724  2138.86  0.6362  0.5623  498.00  134.19

[725 rows x 5 columns]
ETH   -0.048758
XRP   -0.032934
BAT   -0.030672
BCH   -0.064333
LTC    0.010194
Name: 20, dtype: float64
報酬 -0.03330064523330423 %

i= ETH   -0.048758
XRP   -0.032934
BAT   -0.030672
BCH   -0.064333
LTC    0.010194
Name: 20, dtype: float64
牛式===============================
執行第 27
            27
ALGO -0.250000
ATOM -0.174776
LINK -0.132701
QTUM -0.131472
BNB  -0.112109
ZIL  -0.105131
TRX  -0.098751
ADA  -0.091620
XLM  -0.080146
ZEC  -0.072871
BCH  -0.064333
ICX  -0.050878
NEO  -0.049197
ETH  -0.048758
IOTA -0.044965
VET  -0.039648
XRP  -0.032934
BAT  -0.030672
ZRX   0.005223
LTC   0.010194
g================================================================          VET     XRP     BAT     ZRX     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08348  0.6521  0.6135  0.7889  137.39
721  0.07614  0.6236  0.5691  0.8190  132.25
722  0.07704  0.6372  0.5695  0.8384  134.42
723  0.07591  0.6251  0.5575  0.7890  134.00
724  0.07768  0.6362  0.5623  0.7950  134.19

[725 rows x 5 columns]
VET    0.007551
XRP    0.023325
BAT   -0.023026
ZRX    0.080706
LTC    0.025254
Name: 21, dtype: float64
報酬 0.0227619168726765 %
i= VET    0.007551
XRP    0.023325
BAT   -0.023026
ZRX    0.080706
LTC    0.025254
Name: 21, dtype: float64
牛式===============================
執行第 28
            28
ALGO -0.154023
BCH  -0.113579
ATOM -0.071490
BNB  -0.043236
QTUM -0.033273
BAT  -0.023026
LINK -0.015873
ZEC  -0.015511
XLM  -0.014683
ZIL  -0.008333
TRX  -0.007505
VET   0.007551
ICX   0.011241
NEO   0.012028
ADA   0.017441
XRP   0.023325
LTC   0.025254
IOTA  0.027640
ETH   0.033110
ZRX   0.080706
g================================================================         XRP     LTC    IOTA      ETH     ZRX
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6521  137.39  0.8896  2316.15  0.7889
721  0.6236  132.25  0.8165  2121.52  0.8190
722  0.6372  134.42  0.8180  2146.27  0.8384
723  0.6251  134.00  0.7913  2111.19  0.7890
724  0.6362  134.19  0.8404  2138.86  0.7950

[725 rows x 5 columns]
XRP     0.005603
LTC     0.028411
IOTA   -0.016380
ETH     0.034577
ZRX     0.062783
Name: 22, dtype: float64
報酬 0.022998771109490557 %
i= XRP     0.005603
LTC     0.028411
IOTA   -0.016380
ETH     0.034577
ZRX     0.062783
Name: 22, dtype: float64
牛式===============================
執行第 29
            29
ALGO -0.137157
BCH  -0.086716
ATOM -0.056944
ICX  -0.039716
IOTA -0.016380
QTUM -0.009035
ZEC  -0.005113
BNB  -0.004591
ZIL  -0.001425
LINK  0.000000
XLM   0.000974
TRX   0.003232
XRP   0.005603
ADA   0.020225
VET   0.021471
LTC   0.028411
BAT   0.033510
NEO   0.033683
ETH   0.034577
ZRX   0.062783
g================================================================         LTC     BAT     NEO      ETH     ZRX
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  137.39  0.6135  37.005  2316.15  0.7889
721  132.25  0.5691  34.083  2121.52  0.8190
722  134.42  0.5695  34.637  2146.27  0.8384
723  134.00  0.5575  34.057  2111.19  0.7890
724  134.19  0.5623  34.191  2138.86  0.7950

[725 rows x 5 columns]
LTC    0.246424
BAT   -0.028652
NEO    0.031168
ETH    0.031590
ZRX   -0.030469
Name: 23, dtype: float64
報酬 0.050012045884881375 %
i= LTC    0.246424
BAT   -0.028652
NEO    0.031168
ETH    0.031590
ZRX   -0.030469
Name: 23, dtype: float64
牛式===============================
執行第 30
            30
ATOM -0.094752
BCH  -0.086924
ICX  -0.074283
ALGO -0.066986
QTUM -0.048608
IOTA -0.041237
VET  -0.039509
TRX  -0.036656
ZIL  -0.034237
ZRX  -0.030469
BAT  -0.028652
XLM  -0.026652
ADA  -0.007599
LINK -0.005556
XRP   0.003093
ZEC   0.009879
BNB   0.023508
NEO   0.031168
ETH   0.031590
LTC   0.246424
g================================================================         ZEC     BNB     NEO      ETH     LTC
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  118.51  327.67  37.005  2316.15  137.39
721  109.38  310.59  34.083  2121.52  132.25
722  110.99  316.72  34.637  2146.27  134.42
723  108.15  316.09  34.057  2111.19  134.00
724  110.82  321.87  34.191  2138.86  134.19

[725 rows x 5 columns]
ZEC    0.028251
BNB    0.045109
NEO   -0.013195
ETH   -0.014167
LTC    0.404793
Name: 24, dtype: float64
報酬 0.09015819277266397 %
i= ZEC    0.028251
BNB    0.045109
NEO   -0.013195
ETH   -0.014167
LTC    0.404793
Name: 24, dtype: float64
牛式===============================
執行第 31
            31
ALGO -0.153659
BCH  -0.097486
VET  -0.085575
TRX  -0.084034
QTUM -0.069656
ICX  -0.068647
IOTA -0.064503
XLM  -0.063126
BAT  -0.059887
ZIL  -0.059163
LINK -0.033708
ZRX  -0.033292
XRP  -0.024347
ETH  -0.014167
NEO  -0.013195
ADA  -0.010512
ATOM  0.008924
ZEC   0.028251
BNB   0.045109
LTC   0.404793
g================================================================         ADA    ATOM     ZEC     BNB     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  1.4039  12.946  118.51  327.67  137.39
721  1.3327  11.958  109.38  310.59  132.25
722  1.3497  13.182  110.99  316.72  134.42
723  1.3356  14.395  108.15  316.09  134.00
724  1.3478  14.064  110.82  321.87  134.19

[725 rows x 5 columns]
ADA     0.038870
ATOM    0.016949
ZEC     0.039151
BNB     0.045730
LTC     0.379704
Name: 25, dtype: float64
報酬 0.10408073177127908 %
i= ADA     0.038870
ATOM    0.016949
ZEC     0.039151
BNB     0.045730
LTC     0.379704
Name: 25, dtype: float64
牛式===============================
執行第 32
            32
VET  -0.062759
BCH  -0.049548
ALGO -0.048969
BAT  -0.035991
QTUM -0.034368
ZIL  -0.032670
ICX  -0.027260
XLM  -0.025596
TRX  -0.009032
IOTA  0.000000
LINK  0.000000
XRP   0.015670
ATOM  0.016949
ZRX   0.018657
NEO   0.034349
ADA   0.038870
ZEC   0.039151
ETH   0.039637
BNB   0.045730
LTC   0.379704
g================================================================         ADA     ZEC      ETH     BNB     LTC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  1.4039  118.51  2316.15  327.67  137.39
721  1.3327  109.38  2121.52  310.59  132.25
722  1.3497  110.99  2146.27  316.72  134.42
723  1.3356  108.15  2111.19  316.09  134.00
724  1.3478  110.82  2138.86  321.87  134.19

[725 rows x 5 columns]
ADA    0.028250
ZEC    0.031183
ETH    0.018808
BNB   -0.014078
LTC    0.459388
Name: 26, dtype: float64
報酬 0.10471004965382688 %
i= ADA    0.028250
ZEC    0.031183
ETH    0.018808
BNB   -0.014078
LTC    0.459388
Name: 26, dtype: float64
牛式===============================
執行第 33
            33
VET  -0.083486
ZRX  -0.066397
ICX  -0.048861
BAT  -0.041462
ZIL  -0.040559
XLM  -0.031106
IOTA -0.022938
ALGO -0.020356
BNB  -0.014078
QTUM -0.011644
TRX  -0.006927
LINK  0.000000
XRP   0.005791
NEO   0.015348
ETH   0.018808
BCH   0.028160
ADA   0.028250
ZEC   0.031183
ATOM  0.286792
LTC   0.459388
g================================================================         BCH     ADA     ZEC    ATOM     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  1.4039  118.51  12.946  137.39
721  490.60  1.3327  109.38  11.958  132.25
722  504.08  1.3497  110.99  13.182  134.42
723  497.02  1.3356  108.15  14.395  134.00
724  498.00  1.3478  110.82  14.064  134.19

[725 rows x 5 columns]
BCH     0.050609
ADA     0.002786
ZEC     0.030635
ATOM    0.269017
LTC     0.524219
Name: 27, dtype: float64
報酬 0.1754530101953667 %
i= BCH     0.050609
ADA     0.002786
ZEC     0.030635
ATOM    0.269017
LTC     0.524219
Name: 27, dtype: float64
牛式===============================
執行第 34
            34
VET  -0.071194
XLM  -0.045498
ZRX  -0.040840
IOTA -0.039342
LINK -0.037634
BAT  -0.031987
QTUM -0.031163
NEO  -0.017936
ZIL  -0.015406
TRX  -0.014493
XRP  -0.014293
BNB  -0.011186
ALGO  0.000000
ADA   0.002786
ICX   0.007733
ETH   0.009956
ZEC   0.030635
BCH   0.050609
ATOM  0.269017
LTC   0.524219
g================================================================          ETH     ZEC     BCH    ATOM     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  118.51  509.55  12.946  137.39
721  2121.52  109.38  490.60  11.958  132.25
722  2146.27  110.99  504.08  13.182  134.42
723  2111.19  108.15  497.02  14.395  134.00
724  2138.86  110.82  498.00  14.064  134.19

[725 rows x 5 columns]
ETH     0.029472
ZEC     0.004022
BCH     0.049358
ATOM    0.268532
LTC     0.514640
Name: 28, dtype: float64
報酬 0.17320499511600432 %
i= ETH     0.029472
ZEC     0.004022
BCH     0.049358
ATOM    0.268532
LTC     0.514640
Name: 28, dtype: float64
牛式===============================
執行第 35
            35
VET  -0.054844
XLM  -0.033236
IOTA -0.031682
ZIL  -0.029957
QTUM -0.027831
NEO  -0.024191
BAT  -0.021047
ZRX  -0.019488
XRP   0.000542
ZEC   0.004022
BNB   0.004151
TRX   0.005799
ICX   0.005908
LINK  0.011236
ADA   0.023348
ETH   0.029472
BCH   0.049358
ALGO  0.054913
ATOM  0.268532
LTC   0.514640
g================================================================          ETH     BCH    ALGO    ATOM     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  509.55  0.9062  12.946  137.39
721  2121.52  490.60  0.8683  11.958  132.25
722  2146.27  504.08  0.9059  13.182  134.42
723  2111.19  497.02  0.8918  14.395  134.00
724  2138.86  498.00  0.8952  14.064  134.19

[725 rows x 5 columns]
ETH     0.026190
BCH     0.026442
ALGO   -0.107692
ATOM    0.316060
LTC     0.155060
Name: 29, dtype: float64
報酬 0.08321188001097908 %
i= ETH     0.026190
BCH     0.026442
ALGO   -0.107692
ATOM    0.316060
LTC     0.155060
Name: 29, dtype: float64
牛式===============================
執行第 36
            36
ALGO -0.107692
BNB  -0.083922
VET  -0.046755
LINK -0.033520
XLM  -0.026884
NEO  -0.022336
ICX  -0.021838
ZRX  -0.015713
ZEC  -0.014673
BAT  -0.014459
IOTA -0.013234
QTUM -0.009425
TRX  -0.004673
XRP  -0.003903
ZIL   0.002954
ADA   0.010586
ETH   0.026190
BCH   0.026442
LTC   0.155060
ATOM  0.316060
g================================================================         ADA      ETH     BCH     LTC    ATOM
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  1.4039  2316.15  509.55  137.39  12.946
721  1.3327  2121.52  490.60  132.25  11.958
722  1.3497  2146.27  504.08  134.42  13.182
723  1.3356  2111.19  497.02  134.00  14.395
724  1.3478  2138.86  498.00  134.19  14.064

[725 rows x 5 columns]
ADA     0.026447
ETH     0.068662
BCH     0.067937
LTC     0.013060
ATOM    0.507617
Name: 30, dtype: float64
報酬 0.13674453626993738 %
i= ADA     0.026447
ETH     0.068662
BCH     0.067937
LTC     0.013060
ATOM    0.507617
Name: 30, dtype: float64
牛式===============================
執行第 37
            37
ALGO -0.080692
BNB  -0.054066
ZEC  -0.027475
LINK -0.005814
VET   0.000535
XLM   0.004480
XRP   0.011223
LTC   0.013060
IOTA  0.022116
ZRX   0.023597
ADA   0.026447
QTUM  0.027692
BAT   0.029447
ZIL   0.035276
NEO   0.039193
TRX   0.045872
ICX   0.056979
BCH   0.067937
ETH   0.068662
ATOM  0.507617
g================================================================          TRX     ICX     BCH      ETH    ATOM
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.06432  0.9279  509.55  2316.15  12.946
721  0.06111  1.0350  490.60  2121.52  11.958
722  0.06219  0.9786  504.08  2146.27  13.182
723  0.06139  0.9198  497.02  2111.19  14.395
724  0.06184  0.9519  498.00  2138.86  14.064

[725 rows x 5 columns]
TRX     0.009115
ICX    -0.026549
BCH     0.047047
ETH     0.019147
ATOM    0.470370
Name: 31, dtype: float64
報酬 0.10382616865742819 %
i= TRX     0.009115
ICX    -0.026549
BCH     0.047047
ETH     0.019147
ATOM    0.470370
Name: 31, dtype: float64
牛式===============================
執行第 38
            38
ALGO -0.138211
LINK -0.107345
BNB  -0.072289
ZEC  -0.049596
XLM  -0.045597
VET  -0.027619
ICX  -0.026549
XRP  -0.018353
ZRX  -0.015873
BAT  -0.013785
NEO  -0.013460
ZIL  -0.010279
ADA  -0.005438
QTUM -0.003955
IOTA  0.003747
TRX   0.009115
ETH   0.019147
LTC   0.040142
BCH   0.047047
ATOM  0.470370
g================================================================          TRX      ETH     LTC     BCH    ATOM
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.06432  2316.15  137.39  509.55  12.946
721  0.06111  2121.52  132.25  490.60  11.958
722  0.06219  2146.27  134.42  504.08  13.182
723  0.06139  2111.19  134.00  497.02  14.395
724  0.06184  2138.86  134.19  498.00  14.064

[725 rows x 5 columns]
TRX    -0.000634
ETH     0.036535
LTC    -0.105872
BCH     0.013728
ATOM    0.137463
Name: 32, dtype: float64
報酬 0.016244069985517907 %
i= TRX    -0.000634
ETH     0.036535
LTC    -0.105872
BCH     0.013728
ATOM    0.137463
Name: 32, dtype: float64
牛式===============================
執行第 39
            39
ALGO -0.166234
LINK -0.147541
LTC  -0.105872
VET  -0.084084
BNB  -0.065149
ZEC  -0.043289
XLM  -0.038821
QTUM -0.031103
NEO  -0.017059
ICX  -0.014464
BAT  -0.009676
XRP  -0.003966
ADA  -0.003863
TRX  -0.000634
ZIL   0.004373
BCH   0.013728
IOTA  0.019769
ZRX   0.022882
ETH   0.036535
ATOM  0.137463
g================================================================         BCH    IOTA     ZRX      ETH    ATOM
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  509.55  0.8896  0.7889  2316.15  12.946
721  490.60  0.8165  0.8190  2121.52  11.958
722  504.08  0.8180  0.8384  2146.27  13.182
723  497.02  0.7913  0.7890  2111.19  14.395
724  498.00  0.8404  0.7950  2138.86  14.064

[725 rows x 5 columns]
BCH     0.034530
IOTA    0.038863
ZRX     0.003041
ETH     0.046962
ATOM    0.254751
Name: 33, dtype: float64
報酬 0.07562965094670435 %
i= BCH     0.034530
IOTA    0.038863
ZRX     0.003041
ETH     0.046962
ATOM    0.254751
Name: 33, dtype: float64
牛式===============================
執行第 40
            40
LTC  -0.148915
ALGO -0.108696
LINK -0.100559
BNB  -0.081900
VET  -0.063036
ICX  -0.036930
XLM  -0.032387
ZIL  -0.019915
ZEC  -0.008493
TRX  -0.007673
QTUM -0.006721
ADA  -0.003632
NEO  -0.002971
ZRX   0.003041
XRP   0.006226
BAT   0.008696
BCH   0.034530
IOTA  0.038863
ETH   0.046962
ATOM  0.254751
g================================================================         BAT     BCH    IOTA      ETH    ATOM
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6135  509.55  0.8896  2316.15  12.946
721  0.5691  490.60  0.8165  2121.52  11.958
722  0.5695  504.08  0.8180  2146.27  13.182
723  0.5575  497.02  0.7913  2111.19  14.395
724  0.5623  498.00  0.8404  2138.86  14.064

[725 rows x 5 columns]
BAT     0.036607
BCH     0.022288
IOTA    0.041527
ETH     0.097726
ATOM    0.288313
Name: 34, dtype: float64
報酬 0.09729202039214155 %
i= BAT     0.036607
BCH     0.022288
IOTA    0.041527
ETH     0.097726
ATOM    0.288313
Name: 34, dtype: float64
牛式===============================
執行第 41
            41
LTC  -0.152250
LINK -0.122222
ALGO -0.117808
BNB  -0.070280
ICX  -0.018600
XLM  -0.016099
TRX   0.003203
QTUM  0.009378
XRP   0.009630
ADA   0.012053
ZIL   0.016176
ZRX   0.019255
BCH   0.022288
NEO   0.028073
VET   0.031186
BAT   0.036607
IOTA  0.041527
ZEC   0.080792
ETH   0.097726
ATOM  0.288313
g================================================================         BAT    IOTA     ZEC      ETH    ATOM
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6135  0.8896  118.51  2316.15  12.946
721  0.5691  0.8165  109.38  2121.52  11.958
722  0.5695  0.8180  110.99  2146.27  13.182
723  0.5575  0.7913  108.15  2111.19  14.395
724  0.5623  0.8404  110.82  2138.86  14.064

[725 rows x 5 columns]
BAT     0.083920
IOTA    0.096815
ZEC     0.143051
ETH     0.167433
ATOM    0.284211
Name: 35, dtype: float64
報酬 0.15508585188308516 %
i= BAT     0.083920
IOTA    0.096815
ZEC     0.143051
ETH     0.167433
ATOM    0.284211
Name: 35, dtype: float64
牛式===============================
執行第 42
            42
ALGO -0.083333
LINK -0.063584
LTC  -0.060065
BNB   0.012054
BCH   0.047228
ZIL   0.051546
QTUM  0.052579
NEO   0.079564
XLM   0.082538
ICX   0.083593
BAT   0.083920
ADA   0.089146
IOTA  0.096815
XRP   0.118382
TRX   0.118712
ZRX   0.118774
VET   0.120879
ZEC   0.143051
ETH   0.167433
ATOM  0.284211
g================================================================         ZRX      VET     ZEC      ETH    ATOM
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.7889  0.08348  118.51  2316.15  12.946
721  0.8190  0.07614  109.38  2121.52  11.958
722  0.8384  0.07704  110.99  2146.27  13.182
723  0.7890  0.07591  108.15  2111.19  14.395
724  0.7950  0.07768  110.82  2138.86  14.064

[725 rows x 5 columns]
ZRX     0.197508
VET     0.143773
ZEC     0.182511
ETH     0.162867
ATOM    0.072034
Name: 36, dtype: float64
報酬 0.1517385820440092 %
i= ZRX     0.197508
VET     0.143773
ZEC     0.182511
ETH     0.162867
ATOM    0.072034
Name: 36, dtype: float64
牛式===============================
執行第 43
            43
LTC  -0.091521
BCH  -0.006805
LINK  0.052632
BNB   0.065322
ALGO  0.065831
ATOM  0.072034
ICX   0.076162
ZIL   0.115556
NEO   0.121131
QTUM  0.131238
VET   0.143773
BAT   0.150613
ETH   0.162867
ADA   0.169346
ZEC   0.182511
ZRX   0.197508
TRX   0.207827
XRP   0.234218
IOTA  0.261349
XLM   0.416538
g================================================================         ZRX      TRX     XRP    IOTA      XLM
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.7889  0.06432  0.6521  0.8896  0.25677
721  0.8190  0.06111  0.6236  0.8165  0.24383
722  0.8384  0.06219  0.6372  0.8180  0.24550
723  0.7890  0.06139  0.6251  0.7913  0.24484
724  0.7950  0.06184  0.6362  0.8404  0.24587

[725 rows x 5 columns]
ZRX     0.410670
TRX     0.133548
XRP     0.177001
IOTA    0.233098
XLM     0.397265
Name: 37, dtype: float64
報酬 0.27031650809197966 %
i= ZRX     0.410670
TRX     0.133548
XRP     0.177001
IOTA    0.233098
XLM     0.397265
Name: 37, dtype: float64
牛式===============================
執行第 44
            44
LTC  -0.088195
ATOM -0.015113
BCH  -0.008700
ALGO  0.012579
BNB   0.036556
ICX   0.066667
ZIL   0.074184
NEO   0.086446
QTUM  0.097767
VET   0.125402
TRX   0.133548
BAT   0.136867
ADA   0.143701
ZEC   0.144681
XRP   0.177001
LINK  0.183544
ETH   0.216942
IOTA  0.233098
XLM   0.397265
ZRX   0.410670
g================================================================       LINK      ETH    IOTA      XLM     ZRX
0      NaN      NaN     NaN      NaN     NaN
1      NaN      NaN     NaN      NaN     NaN
2      NaN      NaN     NaN      NaN     NaN
3      NaN      NaN     NaN      NaN     NaN
4      NaN      NaN     NaN      NaN     NaN
..     ...      ...     ...      ...     ...
720  19.79  2316.15  0.8896  0.25677  0.7889
721  18.44  2121.52  0.8165  0.24383  0.8190
722  18.66  2146.27  0.8180  0.24550  0.8384
723  18.20  2111.19  0.7913  0.24484  0.7890
724  18.38  2138.86  0.8404  0.24587  0.7950

[725 rows x 5 columns]
LINK    0.166667
ETH     0.159011
IOTA    0.266963
XLM     0.227846
ZRX     0.408706
Name: 38, dtype: float64
報酬 0.2458385570416876 %
i= LINK    0.166667
ETH     0.159011
IOTA    0.266963
XLM     0.227846
ZRX     0.408706
Name: 38, dtype: float64
牛式===============================
執行第 45
            45
BCH  -0.003648
LTC  -0.001395
ALGO  0.000000
BNB   0.015274
ATOM  0.028360
ZIL   0.030479
NEO   0.048880
ICX   0.054656
ZEC   0.058021
QTUM  0.068093
TRX   0.104061
XRP   0.124722
ADA   0.129067
VET   0.141803
ETH   0.159011
LINK  0.166667
BAT   0.215517
XLM   0.227846
IOTA  0.266963
ZRX   0.408706
g================================================================       LINK     BAT      XLM    IOTA     ZRX
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  19.79  0.6135  0.25677  0.8896  0.7889
721  18.44  0.5691  0.24383  0.8165  0.8190
722  18.66  0.5695  0.24550  0.8180  0.8384
723  18.20  0.5575  0.24484  0.7913  0.7890
724  18.38  0.5623  0.24587  0.8404  0.7950

[725 rows x 5 columns]
LINK    0.173913
BAT     0.178161
XLM     0.195846
IOTA    0.182623
ZRX     0.496058
Name: 39, dtype: float64
報酬 0.24532021476540616 %
i= LINK    0.173913
BAT     0.178161
XLM     0.195846
IOTA    0.182623
ZRX     0.496058
Name: 39, dtype: float64
牛式===============================
執行第 46
            46
ATOM -0.107195
ALGO -0.039634
ZIL   0.000000
BCH   0.011181
ZEC   0.021413
ICX   0.030876
BNB   0.033514
QTUM  0.038666
NEO   0.039395
LTC   0.040525
ADA   0.110658
VET   0.112756
XRP   0.113558
ETH   0.137530
TRX   0.168170
LINK  0.173913
BAT   0.178161
IOTA  0.182623
XLM   0.195846
ZRX   0.496058
g================================================================       LINK     BAT    IOTA      XLM     ZRX
0      NaN     NaN     NaN      NaN     NaN
1      NaN     NaN     NaN      NaN     NaN
2      NaN     NaN     NaN      NaN     NaN
3      NaN     NaN     NaN      NaN     NaN
4      NaN     NaN     NaN      NaN     NaN
..     ...     ...     ...      ...     ...
720  19.79  0.6135  0.8896  0.25677  0.7889
721  18.44  0.5691  0.8165  0.24383  0.8190
722  18.66  0.5695  0.8180  0.24550  0.8384
723  18.20  0.5575  0.7913  0.24484  0.7890
724  18.38  0.5623  0.8404  0.24587  0.7950

[725 rows x 5 columns]
LINK    0.151899
BAT     0.073430
IOTA    0.121627
XLM     0.164138
ZRX     0.438757
Name: 40, dtype: float64
報酬 0.18997030965785405 %
i= LINK    0.151899
BAT     0.073430
IOTA    0.121627
XLM     0.164138
ZRX     0.438757
Name: 40, dtype: float64
牛式===============================
執行第 47
            47
ATOM -0.125563
ALGO -0.068323
ZEC  -0.050041
ZIL  -0.040521
NEO  -0.000771
ICX   0.000998
VET   0.001735
BNB   0.006423
QTUM  0.024939
ADA   0.039345
LTC   0.057202
XRP   0.058684
BCH   0.064201
ETH   0.069479
BAT   0.073430
TRX   0.073436
IOTA  0.121627
LINK  0.151899
XLM   0.164138
ZRX   0.438757
g================================================================          TRX    IOTA   LINK      XLM     ZRX
0        NaN     NaN    NaN      NaN     NaN
1        NaN     NaN    NaN      NaN     NaN
2        NaN     NaN    NaN      NaN     NaN
3        NaN     NaN    NaN      NaN     NaN
4        NaN     NaN    NaN      NaN     NaN
..       ...     ...    ...      ...     ...
720  0.06432  0.8896  19.79  0.25677  0.7889
721  0.06111  0.8165  18.44  0.24383  0.8190
722  0.06219  0.8180  18.66  0.24550  0.8384
723  0.06139  0.7913  18.20  0.24484  0.7890
724  0.06184  0.8404  18.38  0.24587  0.7950

[725 rows x 5 columns]
TRX    -0.044365
IOTA    0.061139
LINK    0.111111
XLM     0.000000
ZRX     0.194064
Name: 41, dtype: float64
報酬 0.06438984762064981 %
i= TRX    -0.044365
IOTA    0.061139
LINK    0.111111
XLM     0.000000
ZRX     0.194064
Name: 41, dtype: float64
牛式===============================
執行第 48
            48
ATOM -0.219794
ALGO -0.156740
ZEC  -0.129688
ZIL  -0.112045
NEO  -0.092756
BNB  -0.080991
ICX  -0.078103
QTUM -0.067555
VET  -0.065997
XRP  -0.064331
ADA  -0.051565
TRX  -0.044365
ETH  -0.035459
LTC  -0.025345
XLM   0.000000
BAT   0.009746
IOTA  0.061139
BCH   0.078297
LINK  0.111111
ZRX   0.194064
g================================================================         BAT    IOTA     BCH   LINK     ZRX
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.6135  0.8896  509.55  19.79  0.7889
721  0.5691  0.8165  490.60  18.44  0.8190
722  0.5695  0.8180  504.08  18.66  0.8384
723  0.5575  0.7913  497.02  18.20  0.7890
724  0.5623  0.8404  498.00  18.38  0.7950

[725 rows x 5 columns]
BAT    -0.208524
IOTA   -0.146317
BCH     0.083431
LINK   -0.050000
ZRX    -0.016129
Name: 42, dtype: float64
報酬 -0.06750763583914746 %
i= BAT    -0.208524
IOTA   -0.146317
BCH     0.083431
LINK   -0.050000
ZRX    -0.016129
Name: 42, dtype: float64
牛式===============================
執行第 49
            49
ALGO -0.432353
XLM  -0.361511
ZIL  -0.342629
ATOM -0.325023
ZEC  -0.322905
QTUM -0.312748
ADA  -0.299435
TRX  -0.297765
BNB  -0.286294
NEO  -0.283665
XRP  -0.257980
ICX  -0.254136
VET  -0.220093
ETH  -0.209822
BAT  -0.208524
IOTA -0.146317
LINK -0.050000
LTC  -0.021094
ZRX  -0.016129
BCH   0.083431
g================================================================        IOTA   LINK     LTC     ZRX     BCH
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  0.8896  19.79  137.39  0.7889  509.55
721  0.8165  18.44  132.25  0.8190  490.60
722  0.8180  18.66  134.42  0.8384  504.08
723  0.7913  18.20  134.00  0.7890  497.02
724  0.8404  18.38  134.19  0.7950  498.00

[725 rows x 5 columns]
IOTA   -0.123781
LINK   -0.064171
LTC    -0.048674
ZRX    -0.066403
BCH     0.038721
Name: 43, dtype: float64
報酬 -0.052861628887729564 %
i= IOTA   -0.123781
LINK   -0.064171
LTC    -0.048674
ZRX    -0.066403
BCH     0.038721
Name: 43, dtype: float64
牛式===============================
執行第 50
            50
ALGO -0.363354
ZIL  -0.309392
XLM  -0.291749
ATOM -0.269182
ZEC  -0.258266
QTUM -0.257685
BNB  -0.256148
ADA  -0.251865
TRX  -0.250996
NEO  -0.233350
ETH  -0.228398
ICX  -0.204072
VET  -0.190000
XRP  -0.182018
BAT  -0.176742
IOTA -0.123781
ZRX  -0.066403
LINK -0.064171
LTC  -0.048674
BCH   0.038721
g================================================================        IOTA     ZRX   LINK     LTC     BCH
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  0.8896  0.7889  19.79  137.39  509.55
721  0.8165  0.8190  18.44  132.25  490.60
722  0.8180  0.8384  18.66  134.42  504.08
723  0.7913  0.7890  18.20  134.00  497.02
724  0.8404  0.7950  18.38  134.19  498.00

[725 rows x 5 columns]
IOTA   -0.148231
ZRX    -0.061803
LINK   -0.093407
LTC    -0.066904
BCH     0.028668
Name: 44, dtype: float64
報酬 -0.06833520748299642 %
i= IOTA   -0.148231
ZRX    -0.061803
LINK   -0.093407
LTC    -0.066904
BCH     0.028668
Name: 44, dtype: float64
熊式-----------------------------------
執行第 51
            51
ALGO -0.411215
ZIL  -0.322535
ATOM -0.305233
ZEC  -0.285451
BNB  -0.284438
BAT  -0.280378
QTUM -0.271403
ADA  -0.270992
TRX  -0.267241
NEO  -0.251545
ETH  -0.239347
ICX  -0.237044
VET  -0.208184
XLM  -0.188758
XRP  -0.175766
IOTA -0.148231
LINK -0.093407
LTC  -0.066904
ZRX  -0.061803
BCH   0.028668
g================================================================       ALGO      ZIL   ATOM    ZEC    BNB
0    0.809  0.00879  3.258  55.45  29.42
1    0.717  0.00762  2.857  50.56  27.01
2    0.710  0.00749  2.898  50.57  28.11
3    0.677  0.00732  2.884  48.85  27.53
4    0.683  0.00773  2.910  50.01  27.50
..     ...      ...    ...    ...    ...
720    NaN      NaN    NaN    NaN    NaN
721    NaN      NaN    NaN    NaN    NaN
722    NaN      NaN    NaN    NaN    NaN
723    NaN      NaN    NaN    NaN    NaN
724    NaN      NaN    NaN    NaN    NaN

[725 rows x 5 columns]
ALGO   -0.130081
ZIL     0.011747
ATOM    0.436574
ZEC    -0.016816
BNB    -0.065149
Name: 45, dtype: float64
報酬 0.0472550100867023 %
i= ALGO   -0.130081
ZIL     0.011747
ATOM    0.436574
ZEC    -0.016816
BNB    -0.065149
Name: 45, dtype: float64
熊式-----------------------------------
執行第 52
            52
ALGO -0.400000
ZIL  -0.278665
ATOM -0.258401
BNB  -0.253696
TRX  -0.249862
ADA  -0.244835
QTUM -0.243834
NEO  -0.220193
ZEC  -0.214465
ICX  -0.204831
ETH  -0.192002
BAT  -0.184390
VET  -0.180169
XRP  -0.164544
XLM  -0.155160
ZRX  -0.134982
LINK -0.121693
LTC  -0.107410
IOTA -0.104422
BCH  -0.003512
g================================================================       ALGO      ZIL   ATOM    BNB      TRX
0    0.809  0.00879  3.258  29.42  0.02049
1    0.717  0.00762  2.857  27.01  0.01778
2    0.710  0.00749  2.898  28.11  0.01752
3    0.677  0.00732  2.884  27.53  0.01688
4    0.683  0.00773  2.910  27.50  0.01692
..     ...      ...    ...    ...      ...
720    NaN      NaN    NaN    NaN      NaN
721    NaN      NaN    NaN    NaN      NaN
722    NaN      NaN    NaN    NaN      NaN
723    NaN      NaN    NaN    NaN      NaN
724    NaN      NaN    NaN    NaN      NaN

[725 rows x 5 columns]
ALGO   -0.148052
ZIL     0.004373
ATOM    0.258431
BNB    -0.094601
TRX    -0.015853
Name: 46, dtype: float64
報酬 0.0008597609776776815 %
i= ALGO   -0.148052
ZIL     0.004373
ATOM    0.258431
BNB    -0.094601
TRX    -0.015853
Name: 46, dtype: float64
熊式-----------------------------------
執行第 53
            53
ALGO -0.320000
BNB  -0.227786
ZIL  -0.223228
ATOM -0.218138
ADA  -0.210149
QTUM -0.209924
NEO  -0.194380
TRX  -0.192742
ETH  -0.178133
ICX  -0.176881
VET  -0.150210
XLM  -0.146559
BAT  -0.141514
ZEC  -0.126165
LTC  -0.125152
XRP  -0.125081
ZRX  -0.107582
BCH  -0.082637
LINK -0.076923
IOTA -0.057810
g================================================================       ALGO    BNB      ZIL   ATOM      ADA
0    0.809  29.42  0.00879  3.258  0.05262
1    0.717  27.01  0.00762  2.857  0.04715
2    0.710  28.11  0.00749  2.898  0.04733
3    0.677  27.53  0.00732  2.884  0.04668
4    0.683  27.50  0.00773  2.910  0.04740
..     ...    ...      ...    ...      ...
720    NaN    NaN      NaN    NaN      NaN
721    NaN    NaN      NaN    NaN      NaN
722    NaN    NaN      NaN    NaN      NaN
723    NaN    NaN      NaN    NaN      NaN
724    NaN    NaN      NaN    NaN      NaN

[725 rows x 5 columns]
ALGO   -0.125000
BNB    -0.084163
ZIL    -0.017070
ATOM    0.216740
ADA     0.004701
Name: 47, dtype: float64
報酬 -0.0009583952850207078 %
i= ALGO   -0.125000
BNB    -0.084163
ZIL    -0.017070
ATOM    0.216740
ADA     0.004701
Name: 47, dtype: float64
熊式-----------------------------------
執行第 54
            54
BCH  -0.327357
BNB  -0.212027
ZIL  -0.211356
ADA  -0.198058
NEO  -0.173030
QTUM -0.168878
ALGO -0.167286
TRX  -0.166876
ETH  -0.157011
ICX  -0.154886
BAT  -0.149598
ATOM -0.145914
VET  -0.145161
ZEC  -0.144024
XRP  -0.100584
LTC  -0.090214
XLM  -0.087744
IOTA -0.067699
LINK -0.055556
ZRX  -0.038241
g================================================================         BCH    BNB      ZIL      ADA     NEO
0    334.09  29.42  0.00879  0.05262  10.494
1    315.09  27.01  0.00762  0.04715   9.427
2    316.10  28.11  0.00749  0.04733   9.897
3    339.01  27.53  0.00732  0.04668   9.818
4    330.12  27.50  0.00773  0.04740   9.663
..      ...    ...      ...      ...     ...
720     NaN    NaN      NaN      NaN     NaN
721     NaN    NaN      NaN      NaN     NaN
722     NaN    NaN      NaN      NaN     NaN
723     NaN    NaN      NaN      NaN     NaN
724     NaN    NaN      NaN      NaN     NaN

[725 rows x 5 columns]
BCH    0.025535
BNB   -0.035829
ZIL    0.050000
ADA    0.051873
NEO    0.075164
Name: 48, dtype: float64
報酬 0.033348512809750284 %
i= BCH    0.025535
BNB   -0.035829
ZIL    0.050000
ADA    0.051873
NEO    0.075164
Name: 48, dtype: float64
熊式-----------------------------------
執行第 55
            55
BCH  -0.295564
LTC  -0.057203
BNB   0.000632
ZIL   0.030303
ICX   0.031423
LINK  0.035088
VET   0.041043
ADA   0.044892
IOTA  0.045705
NEO   0.049448
ZRX   0.078794
ZEC   0.082890
ETH   0.087389
QTUM  0.096277
XRP   0.102067
BAT   0.107051
TRX   0.155131
XLM   0.171851
ATOM  0.195045
ALGO  0.295337
g================================================================         BCH    LTC    BNB      ZIL     ICX
0    334.09  56.59  29.42  0.00879  0.2002
1    315.09  54.82  27.01  0.00762  0.1862
2    316.10  56.60  28.11  0.00749  0.2011
3    339.01  55.28  27.53  0.00732  0.1925
4    330.12  55.88  27.50  0.00773  0.1975
..      ...    ...    ...      ...     ...
720     NaN    NaN    NaN      NaN     NaN
721     NaN    NaN    NaN      NaN     NaN
722     NaN    NaN    NaN      NaN     NaN
723     NaN    NaN    NaN      NaN     NaN
724     NaN    NaN    NaN      NaN     NaN

[725 rows x 5 columns]
BCH    0.039270
LTC   -0.116857
BNB    0.069431
ZIL    0.108984
ICX    0.129803
Name: 49, dtype: float64
報酬 0.04612611685322765 %
i= BCH    0.039270
LTC   -0.116857
BNB    0.069431
ZIL    0.108984
ICX    0.129803
Name: 49, dtype: float64
熊式-----------------------------------
執行第 56
            56
BCH  -0.322775
LTC  -0.085187
ADA  -0.022495
ICX  -0.019036
BNB  -0.013100
ZRX  -0.005181
NEO   0.001611
VET   0.005291
ZEC   0.006067
XRP   0.009404
ZIL   0.018000
BAT   0.022402
QTUM  0.025579
XLM   0.026412
IOTA  0.031094
ETH   0.033720
LINK  0.045714
TRX   0.060030
ATOM  0.108049
ALGO  0.131707
g================================================================         BCH    LTC      ADA     ICX    BNB
0    334.09  56.59  0.05262  0.2002  29.42
1    315.09  54.82  0.04715  0.1862  27.01
2    316.10  56.60  0.04733  0.2011  28.11
3    339.01  55.28  0.04668  0.1925  27.53
4    330.12  55.88  0.04740  0.1975  27.50
..      ...    ...      ...     ...    ...
720     NaN    NaN      NaN     NaN    NaN
721     NaN    NaN      NaN     NaN    NaN
722     NaN    NaN      NaN     NaN    NaN
723     NaN    NaN      NaN     NaN    NaN
724     NaN    NaN      NaN     NaN    NaN

[725 rows x 5 columns]
BCH    0.014878
LTC   -0.067015
ADA    0.151508
ICX    0.044510
BNB    0.035062
Name: 50, dtype: float64
報酬 0.035788855698804835 %
i= BCH    0.014878
LTC   -0.067015
ADA    0.151508
ICX    0.044510
BNB    0.035062
Name: 50, dtype: float64
熊式-----------------------------------
執行第 57
            57
BCH  -0.293952
LTC  -0.077143
ZRX  -0.048490
XLM   0.022754
ADA   0.025654
BNB   0.042707
XRP   0.043277
ICX   0.049057
IOTA  0.049775
VET   0.049864
ZIL   0.056133
NEO   0.065762
QTUM  0.068125
ETH   0.087379
ZEC   0.091924
BAT   0.108410
TRX   0.127843
ATOM  0.173207
LINK  0.218182
ALGO  0.227513
g================================================================         BCH    LTC     ZRX      XLM      ADA
0    334.09  56.59  0.1814  0.07442  0.05262
1    315.09  54.82  0.1624  0.06922  0.04715
2    316.10  56.60  0.1736  0.07019  0.04733
3    339.01  55.28  0.1751  0.06851  0.04668
4    330.12  55.88  0.1711  0.06770  0.04740
..      ...    ...     ...      ...      ...
720     NaN    NaN     NaN      NaN      NaN
721     NaN    NaN     NaN      NaN      NaN
722     NaN    NaN     NaN      NaN      NaN
723     NaN    NaN     NaN      NaN      NaN
724     NaN    NaN     NaN      NaN      NaN

[725 rows x 5 columns]
BCH   -0.012284
LTC   -0.105902
ZRX    0.445409
XLM    0.247187
ADA    0.146107
Name: 51, dtype: float64
報酬 0.14410335439753294 %
i= BCH   -0.012284
LTC   -0.105902
ZRX    0.445409
XLM    0.247187
ADA    0.146107
Name: 51, dtype: float64
熊式-----------------------------------
執行第 58
            58
BCH  -0.258893
ADA  -0.024035
ZRX  -0.009841
ZEC  -0.006405
XLM  -0.006116
NEO  -0.002042
BNB  -0.000639
ICX   0.000000
ETH   0.004374
VET   0.008850
LTC   0.017975
XRP   0.019703
IOTA  0.025066
QTUM  0.035692
TRX   0.050000
ZIL   0.058350
BAT   0.083134
ATOM  0.137264
LINK  0.168675
ALGO  0.216931
g================================================================         BCH      ADA     ZRX    ZEC      XLM
0    334.09  0.05262  0.1814  55.45  0.07442
1    315.09  0.04715  0.1624  50.56  0.06922
2    316.10  0.04733  0.1736  50.57  0.07019
3    339.01  0.04668  0.1751  48.85  0.06851
4    330.12  0.04740  0.1711  50.01  0.06770
..      ...      ...     ...    ...      ...
720     NaN      NaN     NaN    NaN      NaN
721     NaN      NaN     NaN    NaN      NaN
722     NaN      NaN     NaN    NaN      NaN
723     NaN      NaN     NaN    NaN      NaN
724     NaN      NaN     NaN    NaN      NaN

[725 rows x 5 columns]
BCH    0.010715
ADA    0.115923
ZRX    0.491536
ZEC    0.032691
XLM    0.187287
Name: 52, dtype: float64
報酬 0.1676304454438451 %
i= BCH    0.010715
ADA    0.115923
ZRX    0.491536
ZEC    0.032691
XLM    0.187287
Name: 52, dtype: float64
熊式-----------------------------------
執行第 59
            59
BCH  -0.253665
ZEC  -0.080625
BNB  -0.007629
VET   0.000874
NEO   0.004787
XLM   0.005318
ETH   0.011638
ADA   0.017358
QTUM  0.021739
LTC   0.021869
ICX   0.022397
IOTA  0.025915
ZIL   0.031068
XRP   0.044084
ZRX   0.045562
TRX   0.072218
ALGO  0.122549
ATOM  0.128295
BAT   0.128345
LINK  0.172619
g================================================================         BCH    ZEC    BNB       VET     NEO
0    334.09  55.45  29.42  0.004916  10.494
1    315.09  50.56  27.01  0.004628   9.427
2    316.10  50.57  28.11  0.004580   9.897
3    339.01  48.85  27.53  0.004493   9.818
4    330.12  50.01  27.50  0.004454   9.663
..      ...    ...    ...       ...     ...
720     NaN    NaN    NaN       NaN     NaN
721     NaN    NaN    NaN       NaN     NaN
722     NaN    NaN    NaN       NaN     NaN
723     NaN    NaN    NaN       NaN     NaN
724     NaN    NaN    NaN       NaN     NaN

[725 rows x 5 columns]
BCH    0.046564
ZEC   -0.012206
BNB    0.003943
VET    0.087460
NEO    0.001435
Name: 53, dtype: float64
報酬 0.0254390175669297 %
i= BCH    0.046564
ZEC   -0.012206
BNB    0.003943
VET    0.087460
NEO    0.001435
Name: 53, dtype: float64
熊式-----------------------------------
執行第 60
            60
ZEC  -0.023582
LTC  -0.001355
ALGO  0.000000
XLM   0.017959
VET   0.021863
NEO   0.029189
BNB   0.032237
ETH   0.041187
BCH   0.043061
ICX   0.050431
XRP   0.054584
QTUM  0.054635
ADA   0.067259
IOTA  0.068752
ZIL   0.070000
ZRX   0.098410
TRX   0.134036
LINK  0.152941
BAT   0.240227
ATOM  0.263326
g================================================================        ZEC    LTC   ALGO      XLM       VET
0    55.45  56.59  0.809  0.07442  0.004916
1    50.56  54.82  0.717  0.06922  0.004628
2    50.57  56.60  0.710  0.07019  0.004580
3    48.85  55.28  0.677  0.06851  0.004493
4    50.01  55.88  0.683  0.06770  0.004454
..     ...    ...    ...      ...       ...
720    NaN    NaN    NaN      NaN       NaN
721    NaN    NaN    NaN      NaN       NaN
722    NaN    NaN    NaN      NaN       NaN
723    NaN    NaN    NaN      NaN       NaN
724    NaN    NaN    NaN      NaN       NaN

[725 rows x 5 columns]
ZEC    -0.092051
LTC     0.045349
ALGO   -0.164596
XLM     0.081984
VET    -0.031730
Name: 54, dtype: float64
報酬 -0.03220890432845851 %
i= ZEC    -0.092051
LTC     0.045349
ALGO   -0.164596
XLM     0.081984
VET    -0.031730
Name: 54, dtype: float64
熊式-----------------------------------
執行第 61
            61
ALGO -0.148000
ZEC  -0.079648
NEO  -0.060279
ETH  -0.057879
XLM  -0.054710
BNB  -0.048611
VET  -0.035683
BCH  -0.019936
ICX  -0.012545
QTUM -0.008197
ATOM -0.004146
XRP  -0.004056
ADA  -0.000515
TRX   0.000000
IOTA  0.007913
ZRX   0.035784
BAT   0.074117
LTC   0.097797
ZIL   0.131373
LINK  0.225989
g================================================================       ALGO    ZEC     NEO     ETH      XLM
0    0.809  55.45  10.494  209.22  0.07442
1    0.717  50.56   9.427  187.11  0.06922
2    0.710  50.57   9.897  188.16  0.07019
3    0.677  48.85   9.818  185.03  0.06851
4    0.683  50.01   9.663  185.61  0.06770
..     ...    ...     ...     ...      ...
720    NaN    NaN     NaN     NaN      NaN
721    NaN    NaN     NaN     NaN      NaN
722    NaN    NaN     NaN     NaN      NaN
723    NaN    NaN     NaN     NaN      NaN
724    NaN    NaN     NaN     NaN      NaN

[725 rows x 5 columns]
ALGO   -0.394984
ZEC    -0.295105
NEO    -0.237734
ETH    -0.202229
XLM    -0.169502
Name: 55, dtype: float64
報酬 -0.25991095723633706 %
i= ALGO   -0.394984
ZEC    -0.295105
NEO    -0.237734
ETH    -0.202229
XLM    -0.169502
Name: 55, dtype: float64
熊式-----------------------------------
執行第 62
            62
ALGO -0.056034
ZEC  -0.019402
NEO  -0.002011
BNB   0.012642
VET   0.016667
ETH   0.023853
ZRX   0.042614
ICX   0.043056
IOTA  0.048399
BCH   0.050558
XLM   0.058282
QTUM  0.061758
ADA   0.081590
XRP   0.112240
LTC   0.112430
ZIL   0.139489
ATOM  0.142124
TRX   0.164158
BAT   0.178941
LINK  0.311475
g================================================================       ALGO    ZEC     NEO    BNB       VET
0    0.809  55.45  10.494  29.42  0.004916
1    0.717  50.56   9.427  27.01  0.004628
2    0.710  50.57   9.897  28.11  0.004580
3    0.677  48.85   9.818  27.53  0.004493
4    0.683  50.01   9.663  27.50  0.004454
..     ...    ...     ...    ...       ...
720    NaN    NaN     NaN    NaN       NaN
721    NaN    NaN     NaN    NaN       NaN
722    NaN    NaN     NaN    NaN       NaN
723    NaN    NaN     NaN    NaN       NaN
724    NaN    NaN     NaN    NaN       NaN

[725 rows x 5 columns]
ALGO   -0.397059
ZEC    -0.281191
NEO    -0.263085
BNB    -0.277277
VET    -0.205140
Name: 56, dtype: float64
報酬 -0.28475031481525387 %
i= ALGO   -0.397059
ZEC    -0.281191
NEO    -0.263085
BNB    -0.277277
VET    -0.205140
Name: 56, dtype: float64
熊式-----------------------------------
執行第 63
            63
ZEC  -0.041437
ALGO -0.025862
IOTA -0.017825
NEO  -0.015623
ETH   0.001442
BNB   0.008822
BCH   0.009084
VET   0.031952
XLM   0.033958
ADA   0.052578
QTUM  0.053833
ICX   0.071942
XRP   0.098243
ATOM  0.114571
LTC   0.115141
TRX   0.180807
ZIL   0.206693
ZRX   0.248077
BAT   0.249555
LINK  0.283582
g================================================================        ZEC   ALGO    IOTA     NEO     ETH
0    55.45  0.809  0.2564  10.494  209.22
1    50.56  0.717  0.2322   9.427  187.11
2    50.57  0.710  0.2428   9.897  188.16
3    48.85  0.677  0.2413   9.818  185.03
4    50.01  0.683  0.2422   9.663  185.61
..     ...    ...     ...     ...     ...
720    NaN    NaN     NaN     NaN     NaN
721    NaN    NaN     NaN     NaN     NaN
722    NaN    NaN     NaN     NaN     NaN
723    NaN    NaN     NaN     NaN     NaN
724    NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
ZEC    -0.316768
ALGO   -0.413043
IOTA   -0.101245
NEO    -0.264334
ETH    -0.247014
Name: 57, dtype: float64
報酬 -0.2684807515936668 %
i= ZEC    -0.316768
ALGO   -0.413043
IOTA   -0.101245
NEO    -0.264334
ETH    -0.247014
Name: 57, dtype: float64
熊式-----------------------------------
執行第 64
            64
BCH  -0.025452
LTC   0.009300
ZEC   0.020414
IOTA  0.033346
ALGO  0.039130
NEO   0.057299
ICX   0.070474
XLM   0.078291
ETH   0.104573
QTUM  0.105169
ADA   0.110296
VET   0.115205
ATOM  0.123017
BNB   0.133632
XRP   0.137568
BAT   0.138045
ZIL   0.163498
TRX   0.183473
ZRX   0.211074
LINK  0.443299
g================================================================         BCH    LTC    ZEC    IOTA   ALGO
0    334.09  56.59  55.45  0.2564  0.809
1    315.09  54.82  50.56  0.2322  0.717
2    316.10  56.60  50.57  0.2428  0.710
3    339.01  55.28  48.85  0.2413  0.677
4    330.12  55.88  50.01  0.2422  0.683
..      ...    ...    ...     ...    ...
720     NaN    NaN    NaN     NaN    NaN
721     NaN    NaN    NaN     NaN    NaN
722     NaN    NaN    NaN     NaN    NaN
723     NaN    NaN    NaN     NaN    NaN
724     NaN    NaN    NaN     NaN    NaN

[725 rows x 5 columns]
BCH     0.010853
LTC    -0.074775
ZEC    -0.233272
IOTA   -0.160663
ALGO   -0.411215
Name: 58, dtype: float64
報酬 -0.1738142368610409 %
i= BCH     0.010853
LTC    -0.074775
ZEC    -0.233272
IOTA   -0.160663
ALGO   -0.411215
Name: 58, dtype: float64
熊式-----------------------------------
執行第 65
            65
ZEC   0.009984
NEO   0.016608
LTC   0.017721
BCH   0.022212
IOTA  0.025260
ICX   0.029011
XLM   0.048976
BAT   0.049057
ADA   0.059587
QTUM  0.065012
XRP   0.070187
VET   0.086413
ETH   0.088729
ZIL   0.094162
ALGO  0.104803
TRX   0.115464
BNB   0.122998
ATOM  0.125000
ZRX   0.233318
LINK  0.335025
g================================================================        ZEC     NEO    LTC     BCH    IOTA
0    55.45  10.494  56.59  334.09  0.2564
1    50.56   9.427  54.82  315.09  0.2322
2    50.57   9.897  56.60  316.10  0.2428
3    48.85   9.818  55.28  339.01  0.2413
4    50.01   9.663  55.88  330.12  0.2422
..     ...     ...    ...     ...     ...
720    NaN     NaN    NaN     NaN     NaN
721    NaN     NaN    NaN     NaN     NaN
722    NaN     NaN    NaN     NaN     NaN
723    NaN     NaN    NaN     NaN     NaN
724    NaN     NaN    NaN     NaN     NaN

[725 rows x 5 columns]
ZEC    -0.154927
NEO    -0.223803
LTC    -0.120759
BCH    -0.050537
IOTA   -0.107483
Name: 59, dtype: float64
報酬 -0.13150169868453318 %
i= ZEC    -0.154927
NEO    -0.223803
LTC    -0.120759
BCH    -0.050537
IOTA   -0.107483
Name: 59, dtype: float64
熊式-----------------------------------
執行第 66
            66
ICX  -0.039813
BAT  -0.037621
BCH  -0.028770
IOTA -0.026021
ZEC  -0.021167
NEO  -0.015680
LTC   0.009224
ADA   0.009831
ATOM  0.012982
XLM   0.013062
ETH   0.024801
QTUM  0.036671
TRX   0.051129
XRP   0.055865
BNB   0.056087
VET   0.065358
ZIL   0.119626
ALGO  0.125000
ZRX   0.161538

LINK  0.403061
g================================================================         ICX     BAT     BCH    IOTA    ZEC
0    0.2002  0.1972  334.09  0.2564  55.45
1    0.1862  0.1682  315.09  0.2322  50.56
2    0.2011  0.1870  316.10  0.2428  50.57
3    0.1925  0.1788  339.01  0.2413  48.85
4    0.1975  0.1764  330.12  0.2422  50.01
..      ...     ...     ...     ...    ...
720     NaN     NaN     NaN     NaN    NaN
721     NaN     NaN     NaN     NaN    NaN
722     NaN     NaN     NaN     NaN    NaN
723     NaN     NaN     NaN     NaN    NaN
724     NaN     NaN     NaN     NaN    NaN

[725 rows x 5 columns]
ICX    -0.189836
BAT    -0.171802
BCH    -0.316282
IOTA   -0.070377
ZEC    -0.181877
Name: 60, dtype: float64
報酬 -0.1860347500023443 %
i= ICX    -0.189836
BAT    -0.171802
BCH    -0.316282
IOTA   -0.070377
ZEC    -0.181877
Name: 60, dtype: float64
熊式-----------------------------------
執行第 67
            67
LTC  -0.063975
ICX  -0.001815
ZIL   0.001733
IOTA  0.004860
NEO   0.013866
ZEC   0.028098
ADA   0.039897
XLM   0.041610
BCH   0.045218
QTUM  0.046045
ETH   0.056790
BAT   0.058221
XRP   0.066445
ATOM  0.068130
TRX   0.079201
VET   0.097881
BNB   0.140677
LINK  0.198157
ALGO  0.206573
ZRX   0.216280
g================================================================        LTC     ICX      ZIL    IOTA     NEO
0    56.59  0.2002  0.00879  0.2564  10.494
1    54.82  0.1862  0.00762  0.2322   9.427
2    56.60  0.2011  0.00749  0.2428   9.897
3    55.28  0.1925  0.00732  0.2413   9.818
4    55.88  0.1975  0.00773  0.2422   9.663
..     ...     ...      ...     ...     ...
720    NaN     NaN      NaN     NaN     NaN
721    NaN     NaN      NaN     NaN     NaN
722    NaN     NaN      NaN     NaN     NaN
723    NaN     NaN      NaN     NaN     NaN
724    NaN     NaN      NaN     NaN     NaN

[725 rows x 5 columns]
LTC    -0.110303
ICX    -0.129938
ZIL    -0.195584
IOTA   -0.044292
NEO    -0.118255
Name: 61, dtype: float64
報酬 -0.11967428413768881 %
i= LTC    -0.110303
ICX    -0.129938
ZIL    -0.195584
IOTA   -0.044292
NEO    -0.118255
Name: 61, dtype: float64
熊式-----------------------------------
執行第 68
            68
ICX  -0.035465
NEO  -0.020013
ZIL  -0.015517
ZEC  -0.013369
IOTA -0.012784
XLM  -0.011111
TRX  -0.011084
ATOM -0.009679
LTC  -0.008487
ADA  -0.002176
QTUM  0.002796
XRP   0.005983
ETH   0.006895
BCH   0.030601
VET   0.030774
LINK  0.037500
BAT   0.050077
BNB   0.139825
ALGO  0.146119
ZRX   0.337421
g================================================================         ICX     NEO      ZIL    ZEC    IOTA
0    0.2002  10.494  0.00879  55.45  0.2564
1    0.1862   9.427  0.00762  50.56  0.2322
2    0.2011   9.897  0.00749  50.57  0.2428
3    0.1925   9.818  0.00732  48.85  0.2413
4    0.1975   9.663  0.00773  50.01  0.2422
..      ...     ...      ...    ...     ...
720     NaN     NaN      NaN    NaN     NaN
721     NaN     NaN      NaN    NaN     NaN
722     NaN     NaN      NaN    NaN     NaN
723     NaN     NaN      NaN    NaN     NaN
724     NaN     NaN      NaN    NaN     NaN

[725 rows x 5 columns]
ICX     0.016020
NEO     0.030387
ZIL     0.028283
ZEC     0.068048
IOTA    0.058314
Name: 62, dtype: float64
報酬 0.04021021675003529 %
i= ICX     0.016020
NEO     0.030387
ZIL     0.028283
ZEC     0.068048
IOTA    0.058314
Name: 62, dtype: float64
熊式-----------------------------------
執行第 69
            69
ICX  -0.071029
ZIL  -0.065253
LINK -0.019380
TRX  -0.018257
NEO   0.001334
ADA   0.010912
VET   0.013110
ZEC   0.013406
QTUM  0.014436
BAT   0.018975
IOTA  0.032305
ETH   0.033503
ATOM  0.065885
XLM   0.069892
XRP   0.071398
BCH   0.072695
LTC   0.146087
BNB   0.153029
ALGO  0.176991
ZRX   0.280046
g================================================================         ICX      ZIL  LINK      TRX     NEO
0    0.2002  0.00879  2.42  0.02049  10.494
1    0.1862  0.00762  2.28  0.01778   9.427
2    0.2011  0.00749  2.42  0.01752   9.897
3    0.1925  0.00732  2.30  0.01688   9.818
4    0.1975  0.00773  2.40  0.01692   9.663
..      ...      ...   ...      ...     ...
720     NaN      NaN   NaN      NaN     NaN
721     NaN      NaN   NaN      NaN     NaN
722     NaN      NaN   NaN      NaN     NaN
723     NaN      NaN   NaN      NaN     NaN
724     NaN      NaN   NaN      NaN     NaN

[725 rows x 5 columns]
ICX    -0.007733
ZIL     0.016000
LINK    0.148571
TRX     0.092705
NEO     0.022691
Name: 63, dtype: float64
報酬 0.054446751797013374 %
i= ICX    -0.007733
ZIL     0.016000
LINK    0.148571
TRX     0.092705
NEO     0.022691
Name: 63, dtype: float64
熊式-----------------------------------
執行第 70
            70
LINK -0.146429
VET  -0.097011
ZIL  -0.091503
ICX  -0.091373
TRX  -0.073373
ADA  -0.066069
QTUM -0.063978
ETH  -0.063807
NEO  -0.049419
ZEC  -0.030798
IOTA  0.002510
ATOM  0.012056
XLM   0.012999
XRP   0.027135
BCH   0.036374
ALGO  0.037657
BNB   0.047377
BAT   0.078117
LTC   0.130609
ZRX   0.231340
g================================================================      LINK       VET      ZIL     ICX      TRX
0    2.42  0.004916  0.00879  0.2002  0.02049
1    2.28  0.004628  0.00762  0.1862  0.01778
2    2.42  0.004580  0.00749  0.2011  0.01752
3    2.30  0.004493  0.00732  0.1925  0.01688
4    2.40  0.004454  0.00773  0.1975  0.01692
..    ...       ...      ...     ...      ...
720   NaN       NaN      NaN     NaN      NaN
721   NaN       NaN      NaN     NaN      NaN
722   NaN       NaN      NaN     NaN      NaN
723   NaN       NaN      NaN     NaN      NaN
724   NaN       NaN      NaN     NaN      NaN

[725 rows x 5 columns]
LINK    0.175758
VET     0.033545
ZIL     0.093555
ICX     0.035220
TRX     0.120000
Name: 64, dtype: float64
報酬 0.09161553454107212 %
i= LINK    0.175758
VET     0.033545
ZIL     0.093555
ICX     0.035220
TRX     0.120000
Name: 64, dtype: float64
熊式-----------------------------------
執行第 71
            71
VET  -0.113016
ZIL  -0.111876
ICX  -0.104143
LINK -0.095057
ALGO -0.094862
ETH  -0.086729
ADA  -0.077385
QTUM -0.072142
TRX  -0.064079
NEO  -0.063337
ZEC  -0.043281
IOTA -0.016667
ATOM -0.016269
BCH  -0.009518
XLM   0.003742
BNB   0.012550
XRP   0.048743
BAT   0.122302
ZRX   0.135444
LTC   0.171176
g================================================================           VET      ZIL     ICX  LINK   ALGO
0    0.004916  0.00879  0.2002  2.42  0.809
1    0.004628  0.00762  0.1862  2.28  0.717
2    0.004580  0.00749  0.2011  2.42  0.710
3    0.004493  0.00732  0.1925  2.30  0.677
4    0.004454  0.00773  0.1975  2.40  0.683
..        ...      ...     ...   ...    ...
720       NaN      NaN     NaN   NaN    NaN
721       NaN      NaN     NaN   NaN    NaN
722       NaN      NaN     NaN   NaN    NaN
723       NaN      NaN     NaN   NaN    NaN
724       NaN      NaN     NaN   NaN    NaN

[725 rows x 5 columns]
VET     0.013864
ZIL     0.068410
ICX     0.026124
LINK    0.186747
ALGO    0.211640
Name: 65, dtype: float64
報酬 0.10135718119397294 %
i= VET     0.013864
ZIL     0.068410
ICX     0.026124
LINK    0.186747
ALGO    0.211640
Name: 65, dtype: float64
熊式-----------------------------------
執行第 72
            72
LINK -0.123636
ZIL  -0.105175
ALGO -0.059524
VET  -0.055021
TRX  -0.029690
QTUM -0.023021
ICX  -0.020732
ETH  -0.018885
ADA  -0.018472
ZEC   0.001663
NEO   0.004571
BCH   0.016966
IOTA  0.025232
ATOM  0.034532
XLM   0.089082
BNB   0.117683
XRP   0.128851
BAT   0.166403
ZRX   0.220101
LTC   0.225134
g================================================================      LINK      ZIL   ALGO       VET      TRX
0    2.42  0.00879  0.809  0.004916  0.02049
1    2.28  0.00762  0.717  0.004628  0.01778
2    2.42  0.00749  0.710  0.004580  0.01752
3    2.30  0.00732  0.677  0.004493  0.01688
4    2.40  0.00773  0.683  0.004454  0.01692
..    ...      ...    ...       ...      ...
720   NaN      NaN    NaN       NaN      NaN
721   NaN      NaN    NaN       NaN      NaN
722   NaN      NaN    NaN       NaN      NaN
723   NaN      NaN    NaN       NaN      NaN
724   NaN      NaN    NaN       NaN      NaN

[725 rows x 5 columns]
LINK    0.166667
ZIL     0.038835
ALGO    0.098039
VET    -0.006407
TRX     0.109801
Name: 66, dtype: float64
報酬 0.08138706849831126 %
i= LINK    0.166667
ZIL     0.038835
ALGO    0.098039
VET    -0.006407
TRX     0.109801
Name: 66, dtype: float64
熊式-----------------------------------
執行第 73
            73
ALGO -0.120623
ZIL  -0.105536
LINK -0.096154
VET  -0.083718
ICX  -0.060606
ADA  -0.060396
QTUM -0.043454
BCH  -0.041758
ETH  -0.039219
ATOM -0.027994
ZEC  -0.020771
NEO  -0.017682
TRX  -0.017230
IOTA  0.008185
XLM   0.034851
BNB   0.059337
XRP   0.078570
BAT   0.113092
ZRX   0.167704
LTC   0.376112
g================================================================       ALGO      ZIL  LINK       VET     ICX
0    0.809  0.00879  2.42  0.004916  0.2002
1    0.717  0.00762  2.28  0.004628  0.1862
2    0.710  0.00749  2.42  0.004580  0.2011
3    0.677  0.00732  2.30  0.004493  0.1925
4    0.683  0.00773  2.40  0.004454  0.1975
..     ...      ...   ...       ...     ...
720    NaN      NaN   NaN       NaN     NaN
721    NaN      NaN   NaN       NaN     NaN
722    NaN      NaN   NaN       NaN     NaN
723    NaN      NaN   NaN       NaN     NaN
724    NaN      NaN   NaN       NaN     NaN

[725 rows x 5 columns]
ALGO   -0.049107
ZIL     0.154000
LINK    0.276471
VET     0.003594
ICX     0.016605
Name: 67, dtype: float64
報酬 0.08031250036323098 %
i= ALGO   -0.049107
ZIL     0.154000
LINK    0.276471
VET     0.003594
ICX     0.016605
Name: 67, dtype: float64
熊式-----------------------------------
執行第 74
            74
ALGO -0.111554
ZIL  -0.099825
ICX  -0.072936
VET  -0.069196
QTUM -0.061350
LINK -0.056225
ADA  -0.054761
ETH  -0.051080
ATOM -0.045375
TRX  -0.036737
IOTA -0.034173
ZEC  -0.027371
NEO  -0.026179
BCH  -0.016443
BNB  -0.004381
XLM   0.017261
BAT   0.029990
XRP   0.050139
ZRX   0.080136
LTC   0.237064
g================================================================       ALGO      ZIL     ICX       VET   QTUM
0    0.809  0.00879  0.2002  0.004916  2.642
1    0.717  0.00762  0.1862  0.004628  2.347
2    0.710  0.00749  0.2011  0.004580  2.376
3    0.677  0.00732  0.1925  0.004493  2.291
4    0.683  0.00773  0.1975  0.004454  2.455
..     ...      ...     ...       ...    ...
720    NaN      NaN     NaN       NaN    NaN
721    NaN      NaN     NaN       NaN    NaN
722    NaN      NaN     NaN       NaN    NaN
723    NaN      NaN     NaN       NaN    NaN
724    NaN      NaN     NaN       NaN    NaN

[725 rows x 5 columns]
ALGO   -0.124000
ZIL     0.137255
ICX     0.027479
VET     0.000576
QTUM    0.046838
Name: 68, dtype: float64
報酬 0.017629588203699132 %
i= ALGO   -0.124000
ZIL     0.137255
ICX     0.027479
VET     0.000576
QTUM    0.046838
Name: 68, dtype: float64
熊式-----------------------------------
執行第 75
            75
ALGO -0.157895
ZIL  -0.092496
VET  -0.073789
TRX  -0.070186
BCH  -0.068105
ETH  -0.061459
ATOM -0.060841
QTUM -0.059113
ICX  -0.054786
ADA  -0.053490
IOTA -0.050633
XLM  -0.045063
LINK -0.035573
NEO  -0.027304
ZEC  -0.019438
XRP  -0.011135
ZRX  -0.003912
BNB   0.002167
LTC   0.033568
BAT   0.054469
g================================================================       ALGO      ZIL       VET      TRX     BCH
0    0.809  0.00879  0.004916  0.02049  334.09
1    0.717  0.00762  0.004628  0.01778  315.09
2    0.710  0.00749  0.004580  0.01752  316.10
3    0.677  0.00732  0.004493  0.01688  339.01
4    0.683  0.00773  0.004454  0.01692  330.12
..     ...      ...       ...      ...     ...
720    NaN      NaN       NaN      NaN     NaN
721    NaN      NaN       NaN      NaN     NaN
722    NaN      NaN       NaN      NaN     NaN
723    NaN      NaN       NaN      NaN     NaN
724    NaN      NaN       NaN      NaN     NaN

[725 rows x 5 columns]

ALGO   -0.025862
ZIL     0.204322
VET     0.048246
TRX     0.217204
BCH     0.038082
Name: 69, dtype: float64
報酬 0.09639847582780933 %
i= ALGO   -0.025862
ZIL     0.204322
VET     0.048246
TRX     0.217204
BCH     0.038082
Name: 69, dtype: float64
熊式-----------------------------------
執行第 76
            76
ALGO -0.087903
BCH  -0.054325
IOTA -0.039342
ETH  -0.035463
VET  -0.034262
ZIL  -0.034173
BAT  -0.028803
ICX  -0.028107
QTUM -0.021827
BNB  -0.015617
ADA  -0.013643
TRX  -0.008940
ZEC  -0.001630
XLM   0.001721
NEO   0.004479
XRP   0.013001
ATOM  0.013615
LTC   0.022325
ZRX   0.023485
LINK  0.096234
g================================================================       ALGO     BCH    IOTA     ETH       VET
0    0.809  334.09  0.2564  209.22  0.004916
1    0.717  315.09  0.2322  187.11  0.004628
2    0.710  316.10  0.2428  188.16  0.004580
3    0.677  339.01  0.2413  185.03  0.004493
4    0.683  330.12  0.2422  185.61  0.004454
..     ...     ...     ...     ...       ...
720    NaN     NaN     NaN     NaN       NaN
721    NaN     NaN     NaN     NaN       NaN
722    NaN     NaN     NaN     NaN       NaN
723    NaN     NaN     NaN     NaN       NaN
724    NaN     NaN     NaN     NaN       NaN

[725 rows x 5 columns]
ALGO    0.030172
BCH     0.005223
IOTA   -0.005704
ETH     0.069044
VET     0.097870
Name: 70, dtype: float64
報酬 0.03932112006823263 %
i= ALGO    0.030172
BCH     0.005223
IOTA   -0.005704
ETH     0.069044
VET     0.097870
Name: 70, dtype: float64
熊式-----------------------------------
執行第 77
            77
ALGO -0.046725
ETH  -0.019245
VET  -0.016304
ICX  -0.013487
IOTA -0.008106
TRX  -0.004608
BCH  -0.003218
QTUM -0.001196
ZEC   0.000838
ADA   0.004689
ATOM  0.007741
ZRX   0.008428
ZIL   0.009690
XLM   0.024473
XRP   0.024668
BNB   0.027042
NEO   0.038313
LTC   0.081999
LINK  0.096639
BAT   0.100275
g================================================================       ALGO     ETH       VET     ICX    IOTA
0    0.809  209.22  0.004916  0.2002  0.2564
1    0.717  187.11  0.004628  0.1862  0.2322
2    0.710  188.16  0.004580  0.2011  0.2428
3    0.677  185.03  0.004493  0.1925  0.2413
4    0.683  185.61  0.004454  0.1975  0.2422
..     ...     ...       ...     ...     ...
720    NaN     NaN       NaN     NaN     NaN
721    NaN     NaN       NaN     NaN     NaN
722    NaN     NaN       NaN     NaN     NaN
723    NaN     NaN       NaN     NaN     NaN
724    NaN     NaN       NaN     NaN     NaN

[725 rows x 5 columns]
ALGO    0.100000
ETH     0.095405
VET     0.091813
ICX     0.055893
IOTA    0.022601
Name: 71, dtype: float64
報酬 0.07314228821954316 %
i= ALGO    0.100000
ETH     0.095405
VET     0.091813
ICX     0.055893
IOTA    0.022601
Name: 71, dtype: float64
熊式-----------------------------------
執行第 78
            78
ALGO -0.154852
VET  -0.128093
ICX  -0.121420
ZIL  -0.111940
QTUM -0.105747
BNB  -0.098812
XRP  -0.095164
ZEC  -0.089399
ETH  -0.083935
IOTA -0.082519
XLM  -0.079490
ATOM -0.077426
ADA  -0.075534
TRX  -0.066406
ZRX  -0.065453
BCH  -0.054956
NEO  -0.047573
LTC  -0.000768
LINK  0.082988
BAT   0.088315
g================================================================       ALGO       VET     ICX      ZIL   QTUM
0    0.809  0.004916  0.2002  0.00879  2.642
1    0.717  0.004628  0.1862  0.00762  2.347
2    0.710  0.004580  0.2011  0.00749  2.376
3    0.677  0.004493  0.1925  0.00732  2.291
4    0.683  0.004454  0.1975  0.00773  2.455
..     ...       ...     ...      ...    ...
720    NaN       NaN     NaN      NaN    NaN
721    NaN       NaN     NaN      NaN    NaN
722    NaN       NaN     NaN      NaN    NaN
723    NaN       NaN     NaN      NaN    NaN
724    NaN       NaN     NaN      NaN    NaN

[725 rows x 5 columns]
ALGO    0.100437
VET     0.057608
ICX    -0.029011
ZIL     0.128060
QTUM    0.052600
Name: 72, dtype: float64
報酬 0.06193890956603063 %
i= ALGO    0.100437
VET     0.057608
ICX    -0.029011
ZIL     0.128060
QTUM    0.052600
Name: 72, dtype: float64
熊式-----------------------------------
執行第 79
            79
VET  -0.110650
ALGO -0.110619
LTC  -0.110600
ICX  -0.091613
ZEC  -0.075356
ETH  -0.071218
BNB  -0.070291
QTUM -0.064897
ZIL  -0.063830
IOTA -0.063100
XRP  -0.060013
BCH  -0.045236
XLM  -0.044162
NEO  -0.020391
ADA  -0.016860
TRX  -0.015584
ZRX  -0.009330
ATOM  0.027707
BAT   0.076888
LINK  0.157447
g================================================================           VET   ALGO    LTC     ICX    ZEC
0    0.004916  0.809  56.59  0.2002  55.45
1    0.004628  0.717  54.82  0.1862  50.56
2    0.004580  0.710  56.60  0.2011  50.57
3    0.004493  0.677  55.28  0.1925  48.85
4    0.004454  0.683  55.88  0.1975  50.01
..        ...    ...    ...     ...    ...
720       NaN    NaN    NaN     NaN    NaN
721       NaN    NaN    NaN     NaN    NaN
722       NaN    NaN    NaN     NaN    NaN
723       NaN    NaN    NaN     NaN    NaN
724       NaN    NaN    NaN     NaN    NaN

[725 rows x 5 columns]
VET     0.078253
ALGO    0.147321
LTC     0.006240
ICX    -0.033958
ZEC    -0.007056
Name: 73, dtype: float64
報酬 0.03816020049751727 %
i= VET     0.078253
ALGO    0.147321
LTC     0.006240
ICX    -0.033958
ZEC    -0.007056
Name: 73, dtype: float64
熊式-----------------------------------
執行第 80
            80
LTC  -0.080302
ALGO -0.044395
ZRX  -0.038981
ICX  -0.017555
BCH  -0.014436
IOTA  0.011546
VET   0.011990
ZIL   0.019455
BNB   0.023652
XRP   0.023855
XLM   0.028494
ZEC   0.034271
QTUM  0.054070
ADA   0.054858
ETH   0.055808
NEO   0.095707
ATOM  0.114077
TRX   0.138979
BAT   0.201432
LINK  0.208511
g================================================================        LTC   ALGO     ZRX     ICX     BCH
0    56.59  0.809  0.1814  0.2002  334.09
1    54.82  0.717  0.1624  0.1862  315.09
2    56.60  0.710  0.1736  0.2011  316.10
3    55.28  0.677  0.1751  0.1925  339.01
4    55.88  0.683  0.1711  0.1975  330.12
..     ...    ...     ...     ...     ...
720    NaN    NaN     NaN     NaN     NaN
721    NaN    NaN     NaN     NaN     NaN
722    NaN    NaN     NaN     NaN     NaN
723    NaN    NaN     NaN     NaN     NaN
724    NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
LTC    -0.027003
ALGO    0.178404
ZRX     0.393753
ICX     0.003630
BCH     0.040458
Name: 74, dtype: float64
報酬 0.11784826770134309 %
i= LTC    -0.027003
ALGO    0.178404
ZRX     0.393753
ICX     0.003630
BCH     0.040458
Name: 74, dtype: float64
牛式===============================
執行第 81
            81
ZRX  -0.116314
ICX  -0.071975
ALGO -0.037500
LTC  -0.011161
ZEC  -0.009086
XLM  -0.007918
ZIL  -0.007692
IOTA -0.004815
XRP  -0.000714
VET   0.000595
BNB   0.023243
ETH   0.025063
ADA   0.025849
BAT   0.041501
BCH   0.046695
ATOM  0.060648
QTUM  0.062245
TRX   0.070323
LINK  0.122951
NEO   0.246200
g================================================================        ATOM   QTUM      TRX   LINK     NEO
0       NaN    NaN      NaN    NaN     NaN
1       NaN    NaN      NaN    NaN     NaN
2       NaN    NaN      NaN    NaN     NaN
3       NaN    NaN      NaN    NaN     NaN
4       NaN    NaN      NaN    NaN     NaN
..      ...    ...      ...    ...     ...
720  12.946  7.079  0.06432  19.79  37.005
721  11.958  6.504  0.06111  18.44  34.083
722  13.182  6.776  0.06219  18.66  34.637
723  14.395  6.639  0.06139  18.20  34.057
724  14.064  6.694  0.06184  18.38  34.191

[725 rows x 5 columns]
ATOM    0.073203
QTUM    0.355843
TRX     0.230670
LINK    0.015267
NEO     0.554054
Name: 75, dtype: float64
報酬 0.24580749112956862 %
i= ATOM    0.073203
QTUM    0.355843
TRX     0.230670
LINK    0.015267
NEO     0.554054
Name: 75, dtype: float64
牛式===============================
執行第 82
            82
ZRX  -0.107287
ALGO -0.035809
IOTA  0.013775
ZEC   0.015234
LINK  0.015267
XLM   0.017653
XRP   0.020398
BCH   0.046657
BNB   0.055799
ETH   0.056931
ZIL   0.057728
ICX   0.059769
ATOM  0.073203
ADA   0.079918
BAT   0.112141
LTC   0.161179
TRX   0.230670
VET   0.239627
QTUM  0.355843
NEO   0.554054
g================================================================         LTC      TRX      VET   QTUM     NEO
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  137.39  0.06432  0.08348  7.079  37.005
721  132.25  0.06111  0.07614  6.504  34.083
722  134.42  0.06219  0.07704  6.776  34.637
723  134.00  0.06139  0.07591  6.639  34.057
724  134.19  0.06184  0.07768  6.694  34.191

[725 rows x 5 columns]
LTC     0.085403
TRX     0.320106
VET     0.166360
QTUM    0.380838
NEO     0.475423
Name: 76, dtype: float64
報酬 0.2856260972908535 %
i= LTC     0.085403
TRX     0.320106
VET     0.166360
QTUM    0.380838
NEO     0.475423
Name: 76, dtype: float64
牛式===============================

執行第 83
            83
ZRX  -0.081324
BCH  -0.044973
BAT  -0.014981
XRP   0.013570
LINK  0.019157
XLM   0.019617
ZEC   0.054408
ALGO  0.056803
IOTA  0.056835
ETH   0.061146
ZIL   0.078695
ATOM  0.082402
LTC   0.085403
ICX   0.085938
BNB   0.091607
ADA   0.091781
VET   0.166360
TRX   0.320106
QTUM  0.380838
NEO   0.475423
g================================================================         ADA      VET      TRX   QTUM     NEO
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  1.4039  0.08348  0.06432  7.079  37.005
721  1.3327  0.07614  0.06111  6.504  34.083
722  1.3497  0.07704  0.06219  6.776  34.637
723  1.3356  0.07591  0.06139  6.639  34.057
724  1.3478  0.07768  0.06184  6.694  34.191

[725 rows x 5 columns]
ADA     0.194223
VET     0.409015
TRX     0.530683
QTUM    0.477506
NEO     0.560735
Name: 77, dtype: float64
報酬 0.4344326348293972 %
i= ADA     0.194223
VET     0.409015
TRX     0.530683
QTUM    0.477506
NEO     0.560735
Name: 77, dtype: float64
牛式===============================
執行第 84
            84
ZRX  -0.045781
BAT  -0.024553
BCH   0.000991
LINK  0.019157
XRP   0.105246
IOTA  0.105325
XLM   0.112744
ALGO  0.132302
ICX   0.172927
ETH   0.173393
ATOM  0.175308
ZIL   0.182773
ZEC   0.188754
ADA   0.194223
LTC   0.220246
BNB   0.239664
VET   0.409015
QTUM  0.477506
TRX   0.530683
NEO   0.560735
g================================================================         BNB      VET   QTUM      TRX     NEO
0       NaN      NaN    NaN      NaN     NaN
1       NaN      NaN    NaN      NaN     NaN
2       NaN      NaN    NaN      NaN     NaN
3       NaN      NaN    NaN      NaN     NaN
4       NaN      NaN    NaN      NaN     NaN
..      ...      ...    ...      ...     ...
720  327.67  0.08348  7.079  0.06432  37.005
721  310.59  0.07614  6.504  0.06111  34.083
722  316.72  0.07704  6.776  0.06219  34.637
723  316.09  0.07591  6.639  0.06139  34.057
724  321.87  0.07768  6.694  0.06184  34.191

[725 rows x 5 columns]
BNB     0.184288
VET     0.380921
QTUM    0.382965
TRX     0.315963
NEO     0.611255
Name: 78, dtype: float64
報酬 0.3750783770697892 %
i= BNB     0.184288
VET     0.380921
QTUM    0.382965
TRX     0.315963
NEO     0.611255
Name: 78, dtype: float64
牛式===============================
執行第 85
            85
ZRX  -0.088463
LINK -0.040441
BAT  -0.004250
ALGO  0.049751
XLM   0.061492
XRP   0.066705
ATOM  0.069883
IOTA  0.109098
ADA   0.117095
ETH   0.141762
ZIL   0.148760
ZEC   0.158165
BNB   0.184288
ICX   0.199574
BCH   0.216426
LTC   0.284833
TRX   0.315963
VET   0.380921
QTUM  0.382965
NEO   0.611255
g================================================================         LTC      TRX      VET   QTUM     NEO
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  137.39  0.06432  0.08348  7.079  37.005
721  132.25  0.06111  0.07614  6.504  34.083
722  134.42  0.06219  0.07704  6.776  34.637
723  134.00  0.06139  0.07591  6.639  34.057
724  134.19  0.06184  0.07768  6.694  34.191

[725 rows x 5 columns]
LTC     0.307876
TRX     0.120318
VET     0.213566
QTUM    0.207441
NEO     0.353372
Name: 79, dtype: float64
報酬 0.24051465822947934 %
i= LTC     0.307876
TRX     0.120318
VET     0.213566
QTUM    0.207441
NEO     0.353372
Name: 79, dtype: float64
牛式===============================
執行第 86
            86
ZRX  -0.111547
BAT  -0.078268
LINK -0.042254
XRP  -0.012974
IOTA  0.001105
ADA   0.002187
ETH   0.004134
ZEC   0.011045
XLM   0.013385
ALGO  0.041295
BNB   0.069318
ZIL   0.070611
ICX   0.070814
ATOM  0.070889
TRX   0.120318
BCH   0.125061
QTUM  0.207441
VET   0.213566
LTC   0.307876
NEO   0.353372
g================================================================         BCH   QTUM      VET     LTC     NEO
0       NaN    NaN      NaN     NaN     NaN
1       NaN    NaN      NaN     NaN     NaN
2       NaN    NaN      NaN     NaN     NaN
3       NaN    NaN      NaN     NaN     NaN
4       NaN    NaN      NaN     NaN     NaN
..      ...    ...      ...     ...     ...
720  509.55  7.079  0.08348  137.39  37.005
721  490.60  6.504  0.07614  132.25  34.083
722  504.08  6.776  0.07704  134.42  34.637
723  497.02  6.639  0.07591  134.00  34.057
724  498.00  6.694  0.07768  134.19  34.191

[725 rows x 5 columns]
BCH     0.120757
QTUM    0.180723
VET     0.182709
LTC     0.294470
NEO     0.166136
Name: 80, dtype: float64
報酬 0.18895892130246753 %
i= BCH     0.120757
QTUM    0.180723
VET     0.182709
LTC     0.294470
NEO     0.166136
Name: 80, dtype: float64
牛式===============================
執行第 87
            87
LINK -0.010949
XRP  -0.008034
BAT  -0.005935
IOTA  0.015631
ETH   0.018157
ZRX   0.018462
ADA   0.040267
ZEC   0.046402
BNB   0.056524
ATOM  0.058155
XLM   0.101357
ICX   0.117364
BCH   0.120757
NEO   0.166136
QTUM  0.180723
TRX   0.182640
VET   0.182709
ALGO  0.205937
ZIL   0.224806
LTC   0.294470
g================================================================          TRX      VET    ALGO      ZIL     LTC
0        NaN      NaN     NaN      NaN     NaN
1        NaN      NaN     NaN      NaN     NaN
2        NaN      NaN     NaN      NaN     NaN
3        NaN      NaN     NaN      NaN     NaN
4        NaN      NaN     NaN      NaN     NaN
..       ...      ...     ...      ...     ...
720  0.06432  0.08348  0.9062  0.08133  137.39
721  0.06111  0.07614  0.8683  0.07509  132.25
722  0.06219  0.07704  0.9059  0.07496  134.42
723  0.06139  0.07591  0.8918  0.07299  134.00
724  0.06184  0.07768  0.8952  0.07377  134.19

[725 rows x 5 columns]
TRX     0.040314
VET     0.019888
ALGO    0.184319
ZIL     0.068662
LTC     0.072338
Name: 81, dtype: float64
報酬 0.07710439336770661 %
i= TRX     0.040314
VET     0.019888
ALGO    0.184319
ZIL     0.068662
LTC     0.072338
Name: 81, dtype: float64
牛式===============================
執行第 88
            88
QTUM -0.054569
NEO  -0.046870
BAT  -0.028333
XRP  -0.012041
ETH  -0.005544
ICX  -0.001819
IOTA  0.000367
ADA   0.004981
ZEC   0.008039
LINK  0.015038
ZRX   0.018757
VET   0.019888
TRX   0.040314
BNB   0.045078
ZIL   0.068662
ATOM  0.069775
LTC   0.072338
XLM   0.093951
BCH   0.162012
ALGO  0.184319
g================================================================        ATOM     LTC      XLM     BCH    ALGO
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  12.946  137.39  0.25677  509.55  0.9062
721  11.958  132.25  0.24383  490.60  0.8683
722  13.182  134.42  0.24550  504.08  0.9059
723  14.395  134.00  0.24484  497.02  0.8918
724  14.064  134.19  0.24587  498.00  0.8952

[725 rows x 5 columns]
ATOM    0.091290
LTC     0.115688
XLM     0.063150
BCH     0.377059
ALGO    0.143910
Name: 82, dtype: float64
報酬 0.15821944226851303 %
i= ATOM    0.091290
LTC     0.115688
XLM     0.063150
BCH     0.377059
ALGO    0.143910
Name: 82, dtype: float64
牛式===============================
執行第 89
            89
QTUM -0.075889
IOTA -0.056942
BAT  -0.024504
ZEC  -0.020111
TRX  -0.015531
XRP  -0.013456
ADA  -0.010449
ICX  -0.002398
ETH  -0.000991
LINK  0.000000
BNB   0.012563
ZRX   0.028691
NEO   0.031728
ZIL   0.062278
XLM   0.063150
ATOM  0.091290
VET   0.114211
LTC   0.115688
ALGO  0.143910
BCH   0.377059
g================================================================        ATOM      VET     LTC    ALGO     BCH
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  12.946  0.08348  137.39  0.9062  509.55
721  11.958  0.07614  132.25  0.8683  490.60
722  13.182  0.07704  134.42  0.9059  504.08
723  14.395  0.07591  134.00  0.8918  497.02
724  14.064  0.07768  134.19  0.8952  498.00

[725 rows x 5 columns]
ATOM    0.146620
VET     0.040284
LTC     0.011607
ALGO    0.136243
BCH     0.360494
Name: 83, dtype: float64
報酬 0.1390498051330799 %
i= ATOM    0.146620
VET     0.040284
LTC     0.011607
ALGO    0.136243
BCH     0.360494
Name: 83, dtype: float64
牛式===============================
執行第 90
            90
TRX  -0.098405
ZEC  -0.034518
ETH  -0.024313
IOTA -0.022127
QTUM -0.014789
XRP  -0.010135
ADA  -0.005298
BNB  -0.003383
LINK  0.003759
LTC   0.011607
BAT   0.032850
VET   0.040284
NEO   0.058256
ZRX   0.058360
ICX   0.071903
ZIL   0.078153
ALGO  0.136243
ATOM  0.146620
XLM   0.177274
BCH   0.360494
g================================================================          ZIL    ALGO    ATOM      XLM     BCH
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.08133  0.9062  12.946  0.25677  509.55
721  0.07509  0.8683  11.958  0.24383  490.60
722  0.07496  0.9059  13.182  0.24550  504.08
723  0.07299  0.8918  14.395  0.24484  497.02
724  0.07377  0.8952  14.064  0.24587  498.00

[725 rows x 5 columns]
ZIL     0.120504
ALGO    0.343602
ATOM    0.245358
XLM     0.284954
BCH     0.090407
Name: 84, dtype: float64
報酬 0.21696493055206306 %
i= ZIL     0.120504
ALGO    0.343602
ATOM    0.245358
XLM     0.284954
BCH     0.090407
Name: 84, dtype: float64
牛式===============================
執行第 91
            91
IOTA -0.024858
LTC  -0.019374
NEO  -0.008820
TRX  -0.008521
ZEC   0.006516
XRP   0.020539
LINK  0.022989
QTUM  0.026460
ETH   0.029429
BNB   0.029925
ADA   0.058047
BAT   0.065301
ZRX   0.074539
ICX   0.078153
BCH   0.090407
ZIL   0.120504
VET   0.181401
ATOM  0.245358
XLM   0.284954
ALGO  0.343602
g================================================================          ZIL      VET    ATOM      XLM    ALGO
0        NaN      NaN     NaN      NaN     NaN
1        NaN      NaN     NaN      NaN     NaN
2        NaN      NaN     NaN      NaN     NaN
3        NaN      NaN     NaN      NaN     NaN
4        NaN      NaN     NaN      NaN     NaN
..       ...      ...     ...      ...     ...
720  0.08133  0.08348  12.946  0.25677  0.9062
721  0.07509  0.07614  11.958  0.24383  0.8683
722  0.07496  0.07704  13.182  0.24550  0.9059
723  0.07299  0.07591  14.395  0.24484  0.8918
724  0.07377  0.07768  14.064  0.24587  0.8952

[725 rows x 5 columns]
ZIL     0.140820
VET     0.278496
ATOM    0.175299
XLM     0.180617
ALGO    0.279405
Name: 85, dtype: float64
報酬 0.21092755681680267 %
i= ZIL     0.140820
VET     0.278496
ATOM    0.175299
XLM     0.180617
ALGO    0.279405
Name: 85, dtype: float64
牛式===============================
執行第 92
            92
LTC  -0.075736
LINK  0.007353
TRX   0.019757
IOTA  0.027584
ZEC   0.034373
BNB   0.038693
ETH   0.048688
NEO   0.052107
XRP   0.054106
QTUM  0.065826
ADA   0.085112
BCH   0.101741
ICX   0.123609
BAT   0.133621
ZRX   0.137703
ZIL   0.140820
ATOM  0.175299
XLM   0.180617
VET   0.278496
ALGO  0.279405
g================================================================          ZIL    ATOM      XLM      VET    ALGO
0        NaN     NaN      NaN      NaN     NaN
1        NaN     NaN      NaN      NaN     NaN
2        NaN     NaN      NaN      NaN     NaN
3        NaN     NaN      NaN      NaN     NaN
4        NaN     NaN      NaN      NaN     NaN
..       ...     ...      ...      ...     ...
720  0.08133  12.946  0.25677  0.08348  0.9062
721  0.07509  11.958  0.24383  0.07614  0.8683
722  0.07496  13.182  0.24550  0.07704  0.9059
723  0.07299  14.395  0.24484  0.07591  0.8918
724  0.07377  14.064  0.24587  0.07768  0.8952

[725 rows x 5 columns]
ZIL     0.039557
ATOM    0.191280
XLM     0.075797
VET     0.406431
ALGO    0.041923
Name: 86, dtype: float64
報酬 0.15099760095981848 %
i= ZIL     0.039557
ATOM    0.191280
XLM     0.075797
VET     0.406431
ALGO    0.041923
Name: 86, dtype: float64
牛式===============================
執行第 93
            93
LTC  -0.108379
LINK -0.011070
IOTA -0.009894
TRX  -0.005607
XRP  -0.002917
ZRX   0.019470
BNB   0.020500
ETH   0.020841
QTUM  0.022727
ZEC   0.024960
ADA   0.030872
ZIL   0.039557
ALGO  0.041923
NEO   0.048243
BAT   0.071215
XLM   0.075797
ICX   0.105037
BCH   0.112045
ATOM  0.191280
VET   0.406431
g================================================================          XLM     ICX     BCH    ATOM      VET
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  0.25677  0.9279  509.55  12.946  0.08348
721  0.24383  1.0350  490.60  11.958  0.07614
722  0.24550  0.9786  504.08  13.182  0.07704
723  0.24484  0.9198  497.02  14.395  0.07591
724  0.24587  0.9519  498.00  14.064  0.07768

[725 rows x 5 columns]
XLM    -0.001403
ICX     0.000608
BCH     0.104246
ATOM    0.113191
VET     0.262782
Name: 87, dtype: float64
報酬 0.0958846511311566 %
i= XLM    -0.001403
ICX     0.000608
BCH     0.104246
ATOM    0.113191
VET     0.262782
Name: 87, dtype: float64
熊式-----------------------------------
執行第 94
            94
XRP  -0.064809
TRX  -0.055360
LTC  -0.038137
ZEC  -0.031632
NEO  -0.029559
IOTA -0.026799
BNB  -0.025781
QTUM -0.013743
ZIL  -0.011532
ALGO -0.010453
ADA  -0.004484
XLM  -0.001403
ZRX  -0.001364
ICX   0.000608
LINK  0.003704
ETH   0.004427
BAT   0.018439
BCH   0.104246
ATOM  0.113191
VET   0.262782
g================================================================          XRP      TRX    LTC    ZEC     NEO
0    0.29787  0.02049  56.59  55.45  10.494
1    0.26338  0.01778  54.82  50.56   9.427
2    0.26408  0.01752  56.60  50.57   9.897
3    0.26055  0.01688  55.28  48.85   9.818
4    0.26543  0.01692  55.88  50.01   9.663
..       ...      ...    ...    ...     ...
720      NaN      NaN    NaN    NaN     NaN
721      NaN      NaN    NaN    NaN     NaN
722      NaN      NaN    NaN    NaN     NaN
723      NaN      NaN    NaN    NaN     NaN
724      NaN      NaN    NaN    NaN     NaN

[725 rows x 5 columns]
XRP    0.014254
TRX    0.232258
LTC    0.121652
ZEC    0.027533
NEO    0.574695
Name: 88, dtype: float64
報酬 0.194078372103005 %
i= XRP    0.014254
TRX    0.232258
LTC    0.121652
ZEC    0.027533
NEO    0.574695
Name: 88, dtype: float64
熊式-----------------------------------
執行第 95
            95
XRP  -0.035925
TRX  -0.035623
NEO  -0.034009
LTC  -0.029676
BNB  -0.021836
ICX  -0.015024
IOTA -0.008200
ZEC  -0.007561
ALGO -0.006063
QTUM  0.002346
BCH   0.003873
ZIL   0.008375
ADA   0.017759
ETH   0.018510
ZRX   0.033673
LINK  0.052632
XLM   0.067426
BAT   0.075790
ATOM  0.172037
VET   0.209731
g================================================================          XRP      TRX     NEO    LTC    BNB
0    0.29787  0.02049  10.494  56.59  29.42
1    0.26338  0.01778   9.427  54.82  27.01
2    0.26408  0.01752   9.897  56.60  28.11
3    0.26055  0.01688   9.818  55.28  27.53
4    0.26543  0.01692   9.663  55.88  27.50
..       ...      ...     ...    ...    ...
720      NaN      NaN     NaN    NaN    NaN
721      NaN      NaN     NaN    NaN    NaN
722      NaN      NaN     NaN    NaN    NaN
723      NaN      NaN     NaN    NaN    NaN
724      NaN      NaN     NaN    NaN    NaN

[725 rows x 5 columns]
XRP    0.007187
TRX    0.286082
NEO    0.448108
LTC    0.186482
BNB    0.088621
Name: 89, dtype: float64
報酬 0.20329618664880572 %
i= XRP    0.007187
TRX    0.286082
NEO    0.448108
LTC    0.186482
BNB    0.088621
Name: 89, dtype: float64
熊式-----------------------------------
執行第 96
            96
XRP  -0.066486
ICX  -0.055806
QTUM -0.035320
NEO  -0.034362
IOTA -0.025912
TRX  -0.022739
BNB  -0.009699
ZEC  -0.004767
ZIL  -0.003295
XLM   0.006503
BAT   0.009500
BCH   0.014280
ADA   0.015285
ETH   0.016954
ZRX   0.036874
ALGO  0.037641
LTC   0.039047
LINK  0.041199
ATOM  0.160255
VET   0.307517
g================================================================          XRP     ICX   QTUM     NEO    IOTA
0    0.29787  0.2002  2.642  10.494  0.2564
1    0.26338  0.1862  2.347   9.427  0.2322
2    0.26408  0.2011  2.376   9.897  0.2428
3    0.26055  0.1925  2.291   9.818  0.2413
4    0.26543  0.1975  2.455   9.663  0.2422
..       ...     ...    ...     ...     ...
720      NaN     NaN    NaN     NaN     NaN
721      NaN     NaN    NaN     NaN     NaN
722      NaN     NaN    NaN     NaN     NaN
723      NaN     NaN    NaN     NaN     NaN
724      NaN     NaN    NaN     NaN     NaN

[725 rows x 5 columns]
XRP     0.039848
ICX     0.077474
QTUM    0.376647
NEO     0.484235
IOTA    0.040862
Name: 90, dtype: float64
報酬 0.20381322019759968 %
i= XRP     0.039848
ICX     0.077474
QTUM    0.376647
NEO     0.484235
IOTA    0.040862
Name: 90, dtype: float64
熊式-----------------------------------
執行第 97
            97
ICX  -0.114772
XRP  -0.087755
ZIL  -0.078652
QTUM -0.064000
IOTA -0.061544
ZEC  -0.051528
BAT  -0.040865
TRX  -0.034378
BNB  -0.027119
XLM  -0.025222
ADA  -0.021764
ETH  -0.018670
ALGO -0.003175
NEO   0.001978
LINK  0.029963
LTC   0.031908
ZRX   0.037775
BCH   0.081354
ATOM  0.158946
VET   0.237988
g================================================================         ICX      XRP      ZIL   QTUM    IOTA
0    0.2002  0.29787  0.00879  2.642  0.2564
1    0.1862  0.26338  0.00762  2.347  0.2322
2    0.2011  0.26408  0.00749  2.376  0.2428
3    0.1925  0.26055  0.00732  2.291  0.2413
4    0.1975  0.26543  0.00773  2.455  0.2422
..      ...      ...      ...    ...     ...
720     NaN      NaN      NaN    NaN     NaN
721     NaN      NaN      NaN    NaN     NaN
722     NaN      NaN      NaN    NaN     NaN
723     NaN      NaN      NaN    NaN     NaN
724     NaN      NaN      NaN    NaN     NaN

[725 rows x 5 columns]
ICX     0.197023
XRP     0.078303
ZIL     0.168067
QTUM    0.408740
IOTA    0.110848
Name: 91, dtype: float64
報酬 0.1925963978000597 %
i= ICX     0.197023
XRP     0.078303
ZIL     0.168067
QTUM    0.408740
IOTA    0.110848
Name: 91, dtype: float64
熊式-----------------------------------
執行第 98
            98
XRP  -0.123216
ICX  -0.114411
ZIL  -0.087500
BAT  -0.080989
IOTA -0.067645
ZEC  -0.051005
ALGO -0.039803
ZRX  -0.026537
ADA  -0.023464
TRX  -0.022355
ETH  -0.020832
QTUM -0.015331
XLM  -0.000260
BNB   0.013546
LINK  0.029197
BCH   0.048597
LTC   0.081471
NEO   0.092918
ATOM  0.102477
VET   0.247614
g================================================================          XRP     ICX      ZIL     BAT    IOTA
0    0.29787  0.2002  0.00879  0.1972  0.2564
1    0.26338  0.1862  0.00762  0.1682  0.2322
2    0.26408  0.2011  0.00749  0.1870  0.2428
3    0.26055  0.1925  0.00732  0.1788  0.2413
4    0.26543  0.1975  0.00773  0.1764  0.2422
..       ...     ...      ...     ...     ...
720      NaN     NaN      NaN     NaN     NaN
721      NaN     NaN      NaN     NaN     NaN
722      NaN     NaN      NaN     NaN     NaN
723      NaN     NaN      NaN     NaN     NaN
724      NaN     NaN      NaN     NaN     NaN

[725 rows x 5 columns]
XRP     0.066198
ICX     0.149148
ZIL     0.159091
BAT    -0.014025
IOTA    0.070894
Name: 92, dtype: float64
報酬 0.08626126899281161 %
i= XRP     0.066198
ICX     0.149148
ZIL     0.159091
BAT    -0.014025
IOTA    0.070894
Name: 92, dtype: float64
熊式-----------------------------------
執行第 99
            99
ZIL  -0.111111
ICX  -0.092273
XRP  -0.063606
IOTA -0.045892
ZEC  -0.045596
BCH  -0.043699
ZRX  -0.010207
ADA  -0.003455
ETH   0.007984
BAT   0.012341
XLM   0.026000
ATOM  0.026031
QTUM  0.027664
TRX   0.031266
BNB   0.048506
ALGO  0.060908
VET   0.121450
LINK  0.126866
NEO   0.183281
LTC   0.263348
g================================================================          ZIL     ICX      XRP    IOTA    ZEC
0    0.00879  0.2002  0.29787  0.2564  55.45
1    0.00762  0.1862  0.26338  0.2322  50.56
2    0.00749  0.2011  0.26408  0.2428  50.57
3    0.00732  0.1925  0.26055  0.2413  48.85
4    0.00773  0.1975  0.26543  0.2422  50.01
..       ...     ...      ...     ...    ...
720      NaN     NaN      NaN     NaN    NaN
721      NaN     NaN      NaN     NaN    NaN
722      NaN     NaN      NaN     NaN    NaN
723      NaN     NaN      NaN     NaN    NaN
724      NaN     NaN      NaN     NaN    NaN

[725 rows x 5 columns]
ZIL     0.206107
ICX     0.077432
XRP    -0.023132
IOTA    0.004786
ZEC     0.014547
Name: 93, dtype: float64
報酬 0.05594820945214174 %
i= ZIL     0.206107
ICX     0.077432
XRP    -0.023132
IOTA    0.004786
ZEC     0.014547
Name: 93, dtype: float64
熊式-----------------------------------
執行第 100
           100
BCH  -0.029969
XRP  -0.026282
ICX  -0.025501
ZRX  -0.007853
IOTA -0.005658
ZEC  -0.000823
ETH   0.006367
ZIL   0.011667
ADA   0.014462
TRX   0.034097
XLM   0.042159
ATOM  0.052811
QTUM  0.071993
BAT   0.080000
ALGO  0.083725
BNB   0.084987
LINK  0.121771
NEO   0.192253
LTC   0.308894
VET   0.374953
g================================================================         BCH      XRP     ICX     ZRX    IOTA
0    334.09  0.29787  0.2002  0.1814  0.2564
1    315.09  0.26338  0.1862  0.1624  0.2322
2    316.10  0.26408  0.2011  0.1736  0.2428
3    339.01  0.26055  0.1925  0.1751  0.2413
4    330.12  0.26543  0.1975  0.1711  0.2422
..      ...      ...     ...     ...     ...
720     NaN      NaN     NaN     NaN     NaN
721     NaN      NaN     NaN     NaN     NaN
722     NaN      NaN     NaN     NaN     NaN
723     NaN      NaN     NaN     NaN     NaN
724     NaN      NaN     NaN     NaN     NaN

[725 rows x 5 columns]
BCH     0.134868
XRP     0.002757
ICX     0.129719
ZRX     0.002735
IOTA    0.013770
Name: 94, dtype: float64
報酬 0.05676976132293583 %
i= BCH     0.134868
XRP     0.002757
ICX     0.129719
ZRX     0.002735
IOTA    0.013770
Name: 94, dtype: float64
熊式-----------------------------------
執行第 101
           101
ZRX  -0.087200
XRP  -0.068632
ICX  -0.042099
IOTA -0.028561
ETH  -0.026179
TRX  -0.019525
ZEC  -0.016871
XLM  -0.013672
ATOM -0.009836
ALGO  0.008387
BCH   0.009334
BAT   0.010467
QTUM  0.016386
BNB   0.028919
ADA   0.035841
LINK  0.085714
ZIL   0.112957
NEO   0.123689
LTC   0.217145
VET   0.525185
g================================================================         ZRX      XRP     ICX    IOTA     ETH
0    0.1814  0.29787  0.2002  0.2564  209.22
1    0.1624  0.26338  0.1862  0.2322  187.11
2    0.1736  0.26408  0.2011  0.2428  188.16
3    0.1751  0.26055  0.1925  0.2413  185.03
4    0.1711  0.26543  0.1975  0.2422  185.61
..      ...      ...     ...     ...     ...
720     NaN      NaN     NaN     NaN     NaN
721     NaN      NaN     NaN     NaN     NaN
722     NaN      NaN     NaN     NaN     NaN
723     NaN      NaN     NaN     NaN     NaN
724     NaN      NaN     NaN     NaN     NaN

[725 rows x 5 columns]
ZRX     0.021188
XRP    -0.026228
ICX     0.009096
IOTA   -0.014690
ETH    -0.013371
Name: 95, dtype: float64
報酬 -0.004800954612807273 %
i= ZRX     0.021188
XRP    -0.026228
ICX     0.009096
IOTA   -0.014690
ETH    -0.013371
Name: 95, dtype: float64
熊式-----------------------------------
執行第 102
           102
XLM  -0.097036
ZRX  -0.079935
XRP  -0.060181
ATOM -0.054389
ZEC  -0.045769
ICX  -0.041194
IOTA -0.039341
TRX  -0.035160
ETH  -0.034824
BCH  -0.020742
QTUM -0.018307
BNB  -0.013222
ADA   0.000456
ALGO  0.017577
LINK  0.075540
BAT   0.095336
ZIL   0.099174
LTC   0.118130
NEO   0.125091
VET   0.265157
g================================================================          XLM     ZRX      XRP   ATOM    ZEC
0    0.07442  0.1814  0.29787  3.258  55.45
1    0.06922  0.1624  0.26338  2.857  50.56
2    0.07019  0.1736  0.26408  2.898  50.57
3    0.06851  0.1751  0.26055  2.884  48.85
4    0.06770  0.1711  0.26543  2.910  50.01
..       ...     ...      ...    ...    ...
720      NaN     NaN      NaN    NaN    NaN
721      NaN     NaN      NaN    NaN    NaN
722      NaN     NaN      NaN    NaN    NaN
723      NaN     NaN      NaN    NaN    NaN
724      NaN     NaN      NaN    NaN    NaN

[725 rows x 5 columns]
XLM     0.216912
ZRX     0.034290
XRP     0.015529
ATOM    0.165484
ZEC    -0.000794
Name: 96, dtype: float64
報酬 0.08628419169043251 %

i= XLM     0.216912
ZRX     0.034290
XRP     0.015529
ATOM    0.165484
ZEC    -0.000794
Name: 96, dtype: float64
熊式-----------------------------------
執行第 103
           103
XLM  -0.105375
ATOM -0.104985
ZRX  -0.086367
ALGO -0.053786
BCH  -0.053397
XRP  -0.040842
ZEC  -0.023205
TRX  -0.018848
ETH  -0.006648
IOTA -0.004269
BNB   0.002489
QTUM  0.011396
ICX   0.021092
ADA   0.042642
LINK  0.058182
NEO   0.081457
LTC   0.118434
ZIL   0.146341
BAT   0.148287
VET   0.264575
g================================================================          XLM   ATOM     ZRX   ALGO     BCH
0    0.07442  3.258  0.1814  0.809  334.09
1    0.06922  2.857  0.1624  0.717  315.09
2    0.07019  2.898  0.1736  0.710  316.10
3    0.06851  2.884  0.1751  0.677  339.01
4    0.06770  2.910  0.1711  0.683  330.12
..       ...    ...     ...    ...     ...
720      NaN    NaN     NaN    NaN     NaN
721      NaN    NaN     NaN    NaN     NaN
722      NaN    NaN     NaN    NaN     NaN
723      NaN    NaN     NaN    NaN     NaN
724      NaN    NaN     NaN    NaN     NaN

[725 rows x 5 columns]
XLM     0.231912
ATOM    0.192003
ZRX     0.042607
ALGO    0.250000
BCH     0.331966
Name: 97, dtype: float64
報酬 0.2096974508266914 %
i= XLM     0.231912
ATOM    0.192003
ZRX     0.042607
ALGO    0.250000
BCH     0.331966
Name: 97, dtype: float64
熊式-----------------------------------
執行第 104
           104
ATOM -0.146168
ZRX  -0.129654
XLM  -0.128822
TRX  -0.128049
QTUM -0.126779
ALGO -0.086941
BNB  -0.086874
XRP  -0.074676
NEO  -0.065704
ZEC  -0.059175
ETH  -0.047255
IOTA -0.041459
ICX  -0.030435
BCH  -0.022333
ADA  -0.012586
LINK -0.010638
ZIL   0.044521
BAT   0.086057
VET   0.133435
LTC   0.199146
g================================================================       ATOM     ZRX      XLM      TRX   QTUM
0    3.258  0.1814  0.07442  0.02049  2.642
1    2.857  0.1624  0.06922  0.01778  2.347
2    2.898  0.1736  0.07019  0.01752  2.376
3    2.884  0.1751  0.06851  0.01688  2.291
4    2.910  0.1711  0.06770  0.01692  2.455
..     ...     ...      ...      ...    ...
720    NaN     NaN      NaN      NaN    NaN
721    NaN     NaN      NaN      NaN    NaN
722    NaN     NaN      NaN      NaN    NaN
723    NaN     NaN      NaN      NaN    NaN
724    NaN     NaN      NaN      NaN    NaN

[725 rows x 5 columns]
ATOM    0.271552
ZRX     0.140221
XLM     0.203538
TRX     0.009023
QTUM    0.041515
Name: 98, dtype: float64
報酬 0.13316974374682977 %
i= ATOM    0.271552
ZRX     0.140221
XLM     0.203538
TRX     0.009023
QTUM    0.041515
Name: 98, dtype: float64
熊式-----------------------------------
執行第 105
           105
TRX  -0.157555
ALGO -0.151009
QTUM -0.150044
XLM  -0.138393
BNB  -0.135514
ZRX  -0.135063
ATOM -0.116051
NEO  -0.109693
LINK -0.099338
ZEC  -0.077362
XRP  -0.067118
ETH  -0.064803
IOTA -0.049651
ADA  -0.025659
BAT  -0.014550
ICX  -0.001225
BCH   0.002491
ZIL   0.011986
LTC   0.056506
VET   0.095238
g================================================================          TRX   ALGO   QTUM      XLM    BNB
0    0.02049  0.809  2.642  0.07442  29.42
1    0.01778  0.717  2.347  0.06922  27.01
2    0.01752  0.710  2.376  0.07019  28.11
3    0.01688  0.677  2.291  0.06851  27.53
4    0.01692  0.683  2.455  0.06770  27.50
..       ...    ...    ...      ...    ...
720      NaN    NaN    NaN      NaN    NaN
721      NaN    NaN    NaN      NaN    NaN
722      NaN    NaN    NaN      NaN    NaN
723      NaN    NaN    NaN      NaN    NaN
724      NaN    NaN    NaN      NaN    NaN

[725 rows x 5 columns]
TRX    -0.011651
ALGO    0.220820
QTUM    0.029412
XLM     0.140071
BNB     0.025628
Name: 99, dtype: float64
報酬 0.08085585505107203 %
i= TRX    -0.011651
ALGO    0.220820
QTUM    0.029412
XLM     0.140071
BNB     0.025628
Name: 99, dtype: float64
熊式-----------------------------------
執行第 106
           106
QTUM -0.176343
ATOM -0.168705
VET  -0.161759
BNB  -0.151501
TRX  -0.147347
XLM  -0.137136
LINK -0.111842
ZRX  -0.097385
NEO  -0.093361
BAT  -0.091618
IOTA -0.086495
ALGO -0.086282
ZEC  -0.072802
BCH  -0.068302
XRP  -0.067293
ETH  -0.055477
ZIL  -0.051071
ADA  -0.044169
ICX  -0.028037
LTC  -0.014151
g================================================================       QTUM   ATOM       VET    BNB      TRX
0    2.642  3.258  0.004916  29.42  0.02049
1    2.347  2.857  0.004628  27.01  0.01778
2    2.376  2.898  0.004580  28.11  0.01752
3    2.291  2.884  0.004493  27.53  0.01688
4    2.455  2.910  0.004454  27.50  0.01692
..     ...    ...       ...    ...      ...
720    NaN    NaN       NaN    NaN      NaN
721    NaN    NaN       NaN    NaN      NaN
722    NaN    NaN       NaN    NaN      NaN
723    NaN    NaN       NaN    NaN      NaN
724    NaN    NaN       NaN    NaN      NaN

[725 rows x 5 columns]
QTUM   -0.001391
ATOM    0.168560
VET     0.333836
BNB    -0.017500
TRX    -0.043323
Name: 100, dtype: float64
報酬 0.08803622778006212 %
i= QTUM   -0.001391
ATOM    0.168560
VET     0.333836
BNB    -0.017500
TRX    -0.043323
Name: 100, dtype: float64
熊式-----------------------------------
執行第 107
           107
VET  -0.267153
ZIL  -0.213433
ATOM -0.187723
QTUM -0.177338
BNB  -0.172091
TRX  -0.171690
LINK -0.164474
XLM  -0.158719
ZEC  -0.132577
ADA  -0.126565
IOTA -0.121857
BAT  -0.117530
ETH  -0.105754
BCH  -0.094765
ICX  -0.081529
NEO  -0.079660
ALGO -0.067297
XRP  -0.066094
ZRX  -0.055876
LTC  -0.001256
g================================================================           VET      ZIL   ATOM   QTUM    BNB
0    0.004916  0.00879  3.258  2.642  29.42
1    0.004628  0.00762  2.857  2.347  27.01
2    0.004580  0.00749  2.898  2.376  28.11
3    0.004493  0.00732  2.884  2.291  27.53
4    0.004454  0.00773  2.910  2.455  27.50
..        ...      ...    ...    ...    ...
720       NaN      NaN    NaN    NaN    NaN
721       NaN      NaN    NaN    NaN    NaN
722       NaN      NaN    NaN    NaN    NaN
723       NaN      NaN    NaN    NaN    NaN
724       NaN      NaN    NaN    NaN    NaN

[725 rows x 5 columns]
VET     0.218074
ZIL    -0.008237
ATOM    0.159696
QTUM   -0.021530
BNB    -0.022806
Name: 101, dtype: float64
報酬 0.0650392309270654 %
i= VET     0.218074
ZIL    -0.008237
ATOM    0.159696
QTUM   -0.021530
BNB    -0.022806
Name: 101, dtype: float64
熊式-----------------------------------
執行第 108
           108
VET  -0.287800
ZIL  -0.281203
ATOM -0.258073
BNB  -0.231762
TRX  -0.229368
QTUM -0.226107
NEO  -0.219703
LINK -0.214047
ZEC  -0.191299
IOTA -0.187207
ALGO -0.182653
BAT  -0.180799
ETH  -0.179799
ICX  -0.173724
XLM  -0.170455
ADA  -0.156407
ZRX  -0.139007
XRP  -0.122273
BCH  -0.072164
LTC   0.043332
g================================================================           VET      ZIL   ATOM    BNB      TRX
0    0.004916  0.00879  3.258  29.42  0.02049
1    0.004628  0.00762  2.857  27.01  0.01778
2    0.004580  0.00749  2.898  28.11  0.01752
3    0.004493  0.00732  2.884  27.53  0.01688
4    0.004454  0.00773  2.910  27.50  0.01692
..        ...      ...    ...    ...      ...
720       NaN      NaN    NaN    NaN      NaN
721       NaN      NaN    NaN    NaN      NaN
722       NaN      NaN    NaN    NaN      NaN
723       NaN      NaN    NaN    NaN      NaN
724       NaN      NaN    NaN    NaN      NaN

[725 rows x 5 columns]
VET     0.355692
ZIL     0.013400
ATOM    0.239137
BNB     0.013400
TRX    -0.015776
Name: 102, dtype: float64
報酬 0.12117052701703598 %
i= VET     0.355692
ZIL     0.013400
ATOM    0.239137
BNB     0.013400
TRX    -0.015776
Name: 102, dtype: float64
熊式-----------------------------------
執行第 109
           109
ZIL  -0.252280
VET  -0.248531
TRX  -0.199039
BAT  -0.196799
BNB  -0.195134
QTUM -0.182160
ZEC  -0.174679
ETH  -0.174547
ATOM -0.173768
NEO  -0.171215
ICX  -0.170109
LINK -0.168385
IOTA -0.163289
ADA  -0.156924
BCH  -0.147057
ALGO -0.145101
XLM  -0.141959
XRP  -0.111090
ZRX  -0.103223
LTC   0.025905
g================================================================          ZIL       VET      TRX     BAT    BNB
0    0.00879  0.004916  0.02049  0.1972  29.42
1    0.00762  0.004628  0.01778  0.1682  27.01
2    0.00749  0.004580  0.01752  0.1870  28.11
3    0.00732  0.004493  0.01688  0.1788  27.53
4    0.00773  0.004454  0.01692  0.1764  27.50
..       ...       ...      ...     ...    ...
720      NaN       NaN      NaN     NaN    NaN
721      NaN       NaN      NaN     NaN    NaN
722      NaN       NaN      NaN     NaN    NaN
723      NaN       NaN      NaN     NaN    NaN
724      NaN       NaN      NaN     NaN    NaN

[725 rows x 5 columns]
ZIL   -0.054366
VET    0.379271
TRX   -0.034866
BAT   -0.011152
BNB   -0.025703
Name: 103, dtype: float64
報酬 0.050636725276335046 %
i= ZIL   -0.054366
VET    0.379271
TRX   -0.034866
BAT   -0.011152
BNB   -0.025703
Name: 103, dtype: float64
熊式-----------------------------------
執行第 110
           110
VET  -0.294586
ZIL  -0.252459
BAT  -0.228190
BNB  -0.214846
ETH  -0.214442
ZEC  -0.212637
NEO  -0.206820
LINK -0.204301
ICX  -0.202434
TRX  -0.200466
IOTA -0.193032
ADA  -0.188644
ALGO -0.186822
QTUM -0.181355
XLM  -0.170724
BCH  -0.152267
ATOM -0.143767
XRP  -0.126256
ZRX  -0.101986
LTC   0.005671
g================================================================           VET      ZIL     BAT    BNB     ETH
0    0.004916  0.00879  0.1972  29.42  209.22
1    0.004628  0.00762  0.1682  27.01  187.11
2    0.004580  0.00749  0.1870  28.11  188.16
3    0.004493  0.00732  0.1788  27.53  185.03
4    0.004454  0.00773  0.1764  27.50  185.61
..        ...      ...     ...    ...     ...
720       NaN      NaN     NaN    NaN     NaN
721       NaN      NaN     NaN    NaN     NaN
722       NaN      NaN     NaN    NaN     NaN
723       NaN      NaN     NaN    NaN     NaN
724       NaN      NaN     NaN    NaN     NaN

[725 rows x 5 columns]
VET    0.336128
ZIL   -0.062600
BAT   -0.031651
BNB    0.014528
ETH   -0.007797
Name: 104, dtype: float64
報酬 0.049721542050131885 %
i= VET    0.336128
ZIL   -0.062600
BAT   -0.031651
BNB    0.014528
ETH   -0.007797
Name: 104, dtype: float64
熊式-----------------------------------
執行第 111
           111
NEO  -0.226962
ICX  -0.219497
ZEC  -0.199176
ZIL  -0.187817
BAT  -0.186353
BNB  -0.179459
ETH  -0.172181
LINK -0.169118
TRX  -0.162832
QTUM -0.159917
VET  -0.154864
ALGO -0.152049
ADA  -0.149229
IOTA -0.147755
XRP  -0.142317
XLM  -0.127400
BCH  -0.123929
ZRX  -0.088462
ATOM -0.038647
LTC   0.042787
g================================================================         NEO     ICX    ZEC      ZIL     BAT
0    10.494  0.2002  55.45  0.00879  0.1972
1     9.427  0.1862  50.56  0.00762  0.1682
2     9.897  0.2011  50.57  0.00749  0.1870
3     9.818  0.1925  48.85  0.00732  0.1788
4     9.663  0.1975  50.01  0.00773  0.1764
..      ...     ...    ...      ...     ...
720     NaN     NaN    NaN      NaN     NaN
721     NaN     NaN    NaN      NaN     NaN
722     NaN     NaN    NaN      NaN     NaN
723     NaN     NaN    NaN      NaN     NaN
724     NaN     NaN    NaN      NaN     NaN

[725 rows x 5 columns]
NEO    0.187551
ICX   -0.101760
ZEC   -0.051005
ZIL   -0.087500
BAT   -0.033080
Name: 105, dtype: float64
報酬 -0.017158783292504844 %
i= NEO    0.187551
ICX   -0.101760
ZEC   -0.051005
ZIL   -0.087500
BAT   -0.033080
Name: 105, dtype: float64
熊式-----------------------------------
執行第 112
           112
NEO  -0.193860
LINK -0.170370
ICX  -0.169231
ZEC  -0.163852
ETH  -0.155828
BNB  -0.154782
BCH  -0.139970
ALGO -0.131964
BAT  -0.128326
QTUM -0.124145
IOTA -0.120432
XRP  -0.118275
ZIL  -0.114583
ADA  -0.103667
XLM  -0.101735
TRX  -0.077341
ZRX  -0.059855
LTC   0.028035
VET   0.034804
ATOM  0.042930
g================================================================         NEO  LINK     ICX    ZEC     ETH
0    10.494  2.42  0.2002  55.45  209.22
1     9.427  2.28  0.1862  50.56  187.11
2     9.897  2.42  0.2011  50.57  188.16
3     9.818  2.30  0.1925  48.85  185.03
4     9.663  2.40  0.1975  50.01  185.61
..      ...   ...     ...    ...     ...
720     NaN   NaN     NaN    NaN     NaN
721     NaN   NaN     NaN    NaN     NaN
722     NaN   NaN     NaN    NaN     NaN
723     NaN   NaN     NaN    NaN     NaN
724     NaN   NaN     NaN    NaN     NaN

[725 rows x 5 columns]
NEO     0.139955
LINK    0.134328
ICX    -0.107838
ZEC    -0.056995
ETH    -0.009002
Name: 106, dtype: float64
報酬 0.02008973151380309 %
i= NEO     0.139955
LINK    0.134328
ICX    -0.107838
ZEC    -0.056995
ETH    -0.009002
Name: 106, dtype: float64
熊式-----------------------------------
執行第 113
           113
BCH  -0.217967
NEO  -0.144228
LINK -0.125984
ZEC  -0.091576
ALGO -0.088366
BAT  -0.085779
XRP  -0.079397
IOTA -0.067841
ETH  -0.052609
ICX  -0.043689
BNB  -0.043478
QTUM -0.039754
XLM  -0.033449
ZIL  -0.028463
ZRX  -0.005727
LTC   0.003996
ADA   0.017983
TRX   0.044834
ATOM  0.119473
VET   0.136070

g================================================================         BCH     NEO  LINK    ZEC   ALGO
0    334.09  10.494  2.42  55.45  0.809
1    315.09   9.427  2.28  50.56  0.717
2    316.10   9.897  2.42  50.57  0.710
3    339.01   9.818  2.30  48.85  0.677
4    330.12   9.663  2.40  50.01  0.683
..      ...     ...   ...    ...    ...
720     NaN     NaN   NaN    NaN    NaN
721     NaN     NaN   NaN    NaN    NaN
722     NaN     NaN   NaN    NaN    NaN
723     NaN     NaN   NaN    NaN    NaN
724     NaN     NaN   NaN    NaN    NaN

[725 rows x 5 columns]
BCH     0.005973
NEO     0.128232
LINK    0.121771
ZEC    -0.008235
ALGO    0.034820
Name: 107, dtype: float64
報酬 0.05651222911500568 %
i= BCH     0.005973
NEO     0.128232
LINK    0.121771
ZEC    -0.008235
ALGO    0.034820
Name: 107, dtype: float64
熊式-----------------------------------
執行第 114
           114
BCH  -0.191921
BAT  -0.066575
NEO  -0.042085
LINK -0.034043
XRP  -0.030460
XLM  -0.021478
ZEC  -0.013793
LTC   0.000073
BNB   0.003876
IOTA  0.006238
ETH   0.007889
ICX   0.018086
ADA   0.055135
QTUM  0.085542
ZRX   0.092257
ZIL   0.096234
TRX   0.098748
VET   0.228152
ATOM  0.250935
ALGO  0.288219
g================================================================         BCH     BAT     NEO  LINK      XRP
0    334.09  0.1972  10.494  2.42  0.29787
1    315.09  0.1682   9.427  2.28  0.26338
2    316.10  0.1870   9.897  2.42  0.26408
3    339.01  0.1788   9.818  2.30  0.26055
4    330.12  0.1764   9.663  2.40  0.26543
..      ...     ...     ...   ...      ...
720     NaN     NaN     NaN   NaN      NaN
721     NaN     NaN     NaN   NaN      NaN
722     NaN     NaN     NaN   NaN      NaN
723     NaN     NaN     NaN   NaN      NaN
724     NaN     NaN     NaN   NaN      NaN

[725 rows x 5 columns]
BCH    -0.012951
BAT     0.077697
NEO     0.160487
LINK    0.067857
XRP    -0.063237
Name: 108, dtype: float64
報酬 0.04597072925304542 %
i= BCH    -0.012951
BAT     0.077697
NEO     0.160487
LINK    0.067857
XRP    -0.063237
Name: 108, dtype: float64
熊式-----------------------------------
執行第 115
           115
BCH  -0.179142
XLM  -0.038756
LINK -0.033058
NEO  -0.028626
BAT  -0.025362
LTC  -0.023996
XRP  -0.016338
ZEC  -0.006773
BNB   0.000000
ICX   0.010249
IOTA  0.013507
ETH   0.018390
TRX   0.075283
QTUM  0.079793
ADA   0.088057
ZRX   0.095315
ZIL   0.101626
VET   0.123740
ALGO  0.207787
ATOM  0.246350
g================================================================         BCH      XLM  LINK     NEO     BAT
0    334.09  0.07442  2.42  10.494  0.1972
1    315.09  0.06922  2.28   9.427  0.1682
2    316.10  0.07019  2.42   9.897  0.1870
3    339.01  0.06851  2.30   9.818  0.1788
4    330.12  0.06770  2.40   9.663  0.1764
..      ...      ...   ...     ...     ...
720     NaN      NaN   NaN     NaN     NaN
721     NaN      NaN   NaN     NaN     NaN
722     NaN      NaN   NaN     NaN     NaN
723     NaN      NaN   NaN     NaN     NaN
724     NaN      NaN   NaN     NaN     NaN

[725 rows x 5 columns]
BCH    -0.011960
XLM    -0.093362
LINK    0.046763
NEO     0.094317
BAT     0.124795
Name: 109, dtype: float64
報酬 0.032110645849005956 %
i= BCH    -0.011960
XLM    -0.093362
LINK    0.046763
NEO     0.094317
BAT     0.124795
Name: 109, dtype: float64
熊式-----------------------------------
執行第 116
           116
LTC  -0.161377
BCH  -0.145107
BAT   0.004936
LINK  0.009009
XRP   0.025000
XLM   0.032241
NEO   0.039430
IOTA  0.040199
BNB   0.046605
ZEC   0.063027
ETH   0.082280
ZRX   0.095704
ICX   0.097189
QTUM  0.114499
TRX   0.129009
ADA   0.151957
ZIL   0.162281
VET   0.164976
ATOM  0.269816
ALGO  0.308300
g================================================================        LTC     BCH     BAT  LINK      XRP
0    56.59  334.09  0.1972  2.42  0.29787
1    54.82  315.09  0.1682  2.28  0.26338
2    56.60  316.10  0.1870  2.42  0.26408
3    55.28  339.01  0.1788  2.30  0.26055
4    55.88  330.12  0.1764  2.40  0.26543
..     ...     ...     ...   ...      ...
720    NaN     NaN     NaN   NaN      NaN
721    NaN     NaN     NaN   NaN      NaN
722    NaN     NaN     NaN   NaN      NaN
723    NaN     NaN     NaN   NaN      NaN
724    NaN     NaN     NaN   NaN      NaN

[725 rows x 5 columns]
LTC     0.165114
BCH    -0.065575
BAT     0.096491
LINK    0.014545
XRP    -0.081829
Name: 110, dtype: float64
報酬 0.025749140265937998 %
i= LTC     0.165114
BCH    -0.065575
BAT     0.096491
LINK    0.014545
XRP    -0.081829
Name: 110, dtype: float64
熊式-----------------------------------
執行第 117
           117
LTC  -0.156819
BCH  -0.133610
LINK -0.044248
BAT  -0.043649
IOTA -0.018678
XLM  -0.001048
BNB   0.017787
NEO   0.020530
ZEC   0.026084
XRP   0.032203
ETH   0.035432
ICX   0.051060
ZIL   0.075000
ZRX   0.094515
QTUM  0.101360
ADA   0.103458
TRX   0.121212
ATOM  0.127106
VET   0.221783
ALGO  0.283229
g================================================================        LTC     BCH  LINK     BAT    IOTA
0    56.59  334.09  2.42  0.1972  0.2564
1    54.82  315.09  2.28  0.1682  0.2322
2    56.60  316.10  2.42  0.1870  0.2428
3    55.28  339.01  2.30  0.1788  0.2413
4    55.88  330.12  2.40  0.1764  0.2422
..     ...     ...   ...     ...     ...
720    NaN     NaN   NaN     NaN     NaN
721    NaN     NaN   NaN     NaN     NaN
722    NaN     NaN   NaN     NaN     NaN
723    NaN     NaN   NaN     NaN     NaN
724    NaN     NaN   NaN     NaN     NaN

[725 rows x 5 columns]
LTC     0.190078
BCH    -0.048640
LINK   -0.035461
BAT     0.036823
IOTA   -0.059501
Name: 111, dtype: float64
報酬 0.0166596047188154 %
i= LTC     0.190078
BCH    -0.048640
LINK   -0.035461
BAT     0.036823
IOTA   -0.059501
Name: 111, dtype: float64
熊式-----------------------------------
執行第 118
           118
BAT  -0.070901
LINK -0.066964
NEO  -0.035818
XLM  -0.031837
BCH  -0.031578
LTC  -0.026325
ZEC  -0.019844
IOTA -0.018886
BNB  -0.010464
XRP  -0.006483
TRX  -0.003274
ZIL   0.000000
ZRX   0.002028
ETH   0.008138
ICX   0.014660
ADA   0.035188
QTUM  0.052252
ATOM  0.054980
VET   0.171799
ALGO  0.248066
g================================================================         BAT  LINK     NEO      XLM     BCH
0    0.1972  2.42  10.494  0.07442  334.09
1    0.1682  2.28   9.427  0.06922  315.09
2    0.1870  2.42   9.897  0.07019  316.10
3    0.1788  2.30   9.818  0.06851  339.01
4    0.1764  2.40   9.663  0.06770  330.12
..      ...   ...     ...      ...     ...
720     NaN   NaN     NaN      NaN     NaN
721     NaN   NaN     NaN      NaN     NaN
722     NaN   NaN     NaN      NaN     NaN
723     NaN   NaN     NaN      NaN     NaN
724     NaN   NaN     NaN      NaN     NaN

[725 rows x 5 columns]
BAT    -0.083759
LINK   -0.105960
NEO    -0.126557
XLM    -0.159795
BCH    -0.049738
Name: 112, dtype: float64
報酬 -0.10516207282756147 %
i= BAT    -0.083759
LINK   -0.105960
NEO    -0.126557
XLM    -0.159795
BCH    -0.049738
Name: 112, dtype: float64
熊式-----------------------------------
執行第 119
           119
LTC  -0.093308
ZRX  -0.066436
TRX  -0.055970
NEO  -0.054486
BNB  -0.050436
XLM  -0.049267
LINK -0.045045
IOTA -0.042533
ZEC  -0.041447
ETH  -0.035141
ICX  -0.034808
ADA  -0.034562
BAT  -0.030123
XRP  -0.020881
ATOM  0.016807
QTUM  0.022741
BCH   0.060882
VET   0.070879
ZIL   0.111328
ALGO  0.280569
g================================================================        LTC     ZRX      TRX     NEO    BNB
0    56.59  0.1814  0.02049  10.494  29.42
1    54.82  0.1624  0.01778   9.427  27.01
2    56.60  0.1736  0.01752   9.897  28.11
3    55.28  0.1751  0.01688   9.818  27.53
4    55.88  0.1711  0.01692   9.663  27.50
..     ...     ...      ...     ...    ...
720    NaN     NaN      NaN     NaN    NaN
721    NaN     NaN      NaN     NaN    NaN
722    NaN     NaN      NaN     NaN    NaN
723    NaN     NaN      NaN     NaN    NaN
724    NaN     NaN      NaN     NaN    NaN

[725 rows x 5 columns]
LTC   -0.003980
ZRX   -0.098761
TRX   -0.207110
NEO   -0.129081
BNB   -0.212477
Name: 113, dtype: float64
報酬 -0.13028160166748592 %
i= LTC   -0.003980
ZRX   -0.098761
TRX   -0.207110
NEO   -0.129081
BNB   -0.212477
Name: 113, dtype: float64
熊式-----------------------------------
執行第 120
           120
ZRX  -0.134615
BAT  -0.112848
LINK -0.105727
TRX  -0.096835
LTC  -0.096339
ALGO -0.083770
NEO  -0.071675
ZEC  -0.067832
IOTA -0.062470
XLM  -0.055133
QTUM -0.054939
ADA  -0.049180
ICX  -0.042931
XRP  -0.041321
ETH  -0.036018
ATOM -0.035064
BNB  -0.027671
BCH   0.024295
ZIL   0.030534
VET   0.086115
g================================================================         ZRX     BAT  LINK      TRX    LTC
0    0.1814  0.1972  2.42  0.02049  56.59
1    0.1624  0.1682  2.28  0.01778  54.82
2    0.1736  0.1870  2.42  0.01752  56.60
3    0.1751  0.1788  2.30  0.01688  55.28
4    0.1711  0.1764  2.40  0.01692  55.88
..      ...     ...   ...      ...    ...
720     NaN     NaN   NaN      NaN    NaN
721     NaN     NaN   NaN      NaN    NaN
722     NaN     NaN   NaN      NaN    NaN
723     NaN     NaN   NaN      NaN    NaN
724     NaN     NaN   NaN      NaN    NaN

[725 rows x 5 columns]
ZRX    -0.124730
BAT    -0.126295
LINK   -0.226974
TRX    -0.226050
LTC     0.007169
Name: 114, dtype: float64
報酬 -0.1393757858328395 %
i= ZRX    -0.124730
BAT    -0.126295
LINK   -0.226974
TRX    -0.226050
LTC     0.007169
Name: 114, dtype: float64
熊式-----------------------------------
執行第 121
           121
ZRX  -0.147861
LINK -0.141026
BAT  -0.135223
ATOM -0.130110
TRX  -0.102230
LTC  -0.101974
NEO  -0.100361
ADA  -0.088684
QTUM -0.079745
IOTA -0.064338
XLM  -0.062002
ALGO -0.041652
ETH  -0.041489
XRP  -0.038263
ICX  -0.037681
BNB  -0.033930
ZEC   0.028640
BCH   0.044754
ZIL   0.057196
VET   0.062945
g================================================================         ZRX  LINK     BAT   ATOM      TRX
0    0.1814  2.42  0.1972  3.258  0.02049
1    0.1624  2.28  0.1682  2.857  0.01778
2    0.1736  2.42  0.1870  2.898  0.01752
3    0.1751  2.30  0.1788  2.884  0.01688
4    0.1711  2.40  0.1764  2.910  0.01692
..      ...   ...     ...    ...      ...
720     NaN   NaN     NaN    NaN      NaN
721     NaN   NaN     NaN    NaN      NaN
722     NaN   NaN     NaN    NaN      NaN
723     NaN   NaN     NaN    NaN      NaN
724     NaN   NaN     NaN    NaN      NaN

[725 rows x 5 columns]
ZRX    -0.121986
LINK   -0.190635
BAT    -0.175196
ATOM   -0.187941
TRX    -0.195606
Name: 115, dtype: float64
報酬 -0.1742728857680862 %
i= ZRX    -0.121986
LINK   -0.190635
BAT    -0.175196
ATOM   -0.187941
TRX    -0.195606
Name: 115, dtype: float64
熊式-----------------------------------
執行第 122
           122
ATOM -0.067516
LINK -0.066964
NEO  -0.062795
ZRX  -0.057065
TRX  -0.051646
ADA  -0.051575
BAT  -0.047151
XLM  -0.033676
QTUM -0.023451
IOTA -0.022901
ETH  -0.020194
ICX  -0.011713
BNB  -0.003181
XRP   0.000089
ZEC   0.003792
ALGO  0.011707
BCH   0.028716
LTC   0.048366
VET   0.141778
ZIL   0.162264
g================================================================       ATOM  LINK     NEO     ZRX      TRX
0    3.258  2.42  10.494  0.1814  0.02049
1    2.857  2.28   9.427  0.1624  0.01778
2    2.898  2.42   9.897  0.1736  0.01752
3    2.884  2.30   9.818  0.1751  0.01688
4    2.910  2.40   9.663  0.1711  0.01692
..     ...   ...     ...     ...      ...
720    NaN   NaN     NaN     NaN      NaN
721    NaN   NaN     NaN     NaN      NaN
722    NaN   NaN     NaN     NaN      NaN
723    NaN   NaN     NaN     NaN      NaN
724    NaN   NaN     NaN     NaN      NaN

[725 rows x 5 columns]
ATOM   -0.206622
LINK   -0.237113
NEO    -0.255247
ZRX    -0.148497
TRX    -0.267876
Name: 116, dtype: float64
報酬 -0.22307109725300317 %
i= ATOM   -0.206622
LINK   -0.237113
NEO    -0.255247
ZRX    -0.148497
TRX    -0.267876
Name: 116, dtype: float64

熊式-----------------------------------
執行第 123
           123
TRX  -0.089881
ZRX  -0.089052
LINK -0.055556
VET  -0.041684
BAT  -0.038974
NEO  -0.036232
XLM  -0.031294
ADA  -0.029062
ETH  -0.024140
QTUM -0.022447
ATOM -0.012851
LTC  -0.002583
IOTA -0.001464
BCH   0.000901
BNB   0.008414
XRP   0.010236
ICX   0.018685
ALGO  0.036911
ZEC   0.056212
ZIL   0.244186
g================================================================          TRX     ZRX  LINK       VET     BAT
0    0.02049  0.1814  2.42  0.004916  0.1972
1    0.01778  0.1624  2.28  0.004628  0.1682
2    0.01752  0.1736  2.42  0.004580  0.1870
3    0.01688  0.1751  2.30  0.004493  0.1788
4    0.01692  0.1711  2.40  0.004454  0.1764
..       ...     ...   ...       ...     ...
720      NaN     NaN   NaN       NaN     NaN
721      NaN     NaN   NaN       NaN     NaN
722      NaN     NaN   NaN       NaN     NaN
723      NaN     NaN   NaN       NaN     NaN
724      NaN     NaN   NaN       NaN     NaN

[725 rows x 5 columns]
TRX    -0.173077
ZRX    -0.094729
LINK   -0.189964
VET    -0.215337
BAT    -0.223238
Name: 117, dtype: float64
報酬 -0.17926896403173184 %
i= TRX    -0.173077
ZRX    -0.094729
LINK   -0.189964
VET    -0.215337
BAT    -0.223238
Name: 117, dtype: float64
熊式-----------------------------------
執行第 124
           124
LTC  -0.116065
ZRX  -0.042088
TRX  -0.040079
VET  -0.039617
BCH  -0.030556
LINK -0.019139
IOTA -0.006737
QTUM -0.005137
BAT  -0.000530
XLM   0.002695
NEO   0.010518
ETH   0.011839
ADA   0.020290
BNB   0.030403
ICX   0.030418
XRP   0.045309
ZEC   0.057845
ALGO  0.067104
ATOM  0.067940
ZIL   0.268627
g================================================================        LTC     ZRX      TRX       VET     BCH
0    56.59  0.1814  0.02049  0.004916  334.09
1    54.82  0.1624  0.01778  0.004628  315.09
2    56.60  0.1736  0.01752  0.004580  316.10
3    55.28  0.1751  0.01688  0.004493  339.01
4    55.88  0.1711  0.01692  0.004454  330.12
..     ...     ...      ...       ...     ...
720    NaN     NaN      NaN       NaN     NaN
721    NaN     NaN      NaN       NaN     NaN
722    NaN     NaN      NaN       NaN     NaN
723    NaN     NaN      NaN       NaN     NaN
724    NaN     NaN      NaN       NaN     NaN

[725 rows x 5 columns]
LTC    0.007473
ZRX   -0.051538
TRX   -0.099115
VET   -0.079104
BCH   -0.184777
Name: 118, dtype: float64
報酬 -0.08141236422081644 %
i= LTC    0.007473
ZRX   -0.051538
TRX   -0.099115
VET   -0.079104
BCH   -0.184777
Name: 118, dtype: float64
熊式-----------------------------------
執行第 125
           125
BAT  -0.058045
BCH  -0.053708
TRX  -0.052701
ZRX  -0.051419
LTC  -0.038124
NEO  -0.024169
XLM  -0.020620
VET  -0.019383
LINK -0.014151
ADA  -0.012729
QTUM -0.010262
IOTA -0.003455
ETH   0.001563
ICX   0.003757
BNB   0.005246
ATOM  0.007713
ALGO  0.019097
XRP   0.022784
ZIL   0.063269
ZEC   0.133382
g================================================================         BAT     BCH      TRX     ZRX    LTC
0    0.1972  334.09  0.02049  0.1814  56.59
1    0.1682  315.09  0.01778  0.1624  54.82
2    0.1870  316.10  0.01752  0.1736  56.60
3    0.1788  339.01  0.01688  0.1751  55.28
4    0.1764  330.12  0.01692  0.1711  55.88
..      ...     ...      ...     ...    ...
720     NaN     NaN      NaN     NaN    NaN
721     NaN     NaN      NaN     NaN    NaN
722     NaN     NaN      NaN     NaN    NaN
723     NaN     NaN      NaN     NaN    NaN
724     NaN     NaN      NaN     NaN    NaN

[725 rows x 5 columns]
BAT   -0.130901
BCH   -0.212026
TRX   -0.028399
ZRX   -0.007244
LTC    0.014354
Name: 119, dtype: float64
報酬 -0.0728430606705186 %
i= BAT   -0.130901
BCH   -0.212026
TRX   -0.028399
ZRX   -0.007244
LTC    0.014354
Name: 119, dtype: float64
熊式-----------------------------------
執行第 126
           126
VET  -0.099000
BCH  -0.061523
BAT  -0.039097
ICX  -0.036350
LTC  -0.029880
XLM  -0.027803
ADA  -0.021013
BNB  -0.019854
ZRX  -0.013943
TRX  -0.010512
NEO  -0.007558
ETH   0.001583
IOTA  0.003561
ATOM  0.008451
QTUM  0.021726
ZIL   0.033333
XRP   0.040438
ALGO  0.046476
LINK  0.118227
ZEC   0.126407
g================================================================           VET     BCH     BAT     ICX    LTC
0    0.004916  334.09  0.1972  0.2002  56.59
1    0.004628  315.09  0.1682  0.1862  54.82
2    0.004580  316.10  0.1870  0.2011  56.60
3    0.004493  339.01  0.1788  0.1925  55.28
4    0.004454  330.12  0.1764  0.1975  55.88
..        ...     ...     ...     ...    ...
720       NaN     NaN     NaN     NaN    NaN
721       NaN     NaN     NaN     NaN    NaN
722       NaN     NaN     NaN     NaN    NaN
723       NaN     NaN     NaN     NaN    NaN
724       NaN     NaN     NaN     NaN    NaN

[725 rows x 5 columns]
VET    0.109520
BCH   -0.190033
BAT   -0.075847
ICX   -0.063107
LTC    0.008510
Name: 120, dtype: float64
報酬 -0.04219134994244431 %
i= VET    0.109520
BCH   -0.190033
BAT   -0.075847
ICX   -0.063107
LTC    0.008510
Name: 120, dtype: float64
熊式-----------------------------------
執行第 127
           127
VET  -0.116979
BNB  -0.056194
BAT  -0.049973
XLM  -0.046415
ZRX  -0.037646
ICX  -0.036898
ETH  -0.031602
ADA  -0.026323
TRX  -0.023464
IOTA -0.023084
NEO  -0.022220
BCH  -0.020804
ZIL  -0.015707
XRP  -0.000814
QTUM  0.010976
LTC   0.037065
ZEC   0.039775
ALGO  0.083522
LINK  0.084577
ATOM  0.095415
g================================================================           VET    BNB     BAT      XLM     ZRX
0    0.004916  29.42  0.1972  0.07442  0.1814
1    0.004628  27.01  0.1682  0.06922  0.1624
2    0.004580  28.11  0.1870  0.07019  0.1736
3    0.004493  27.53  0.1788  0.06851  0.1751
4    0.004454  27.50  0.1764  0.06770  0.1711
..        ...    ...     ...      ...     ...
720       NaN    NaN     NaN      NaN     NaN
721       NaN    NaN     NaN      NaN     NaN
722       NaN    NaN     NaN      NaN     NaN
723       NaN    NaN     NaN      NaN     NaN
724       NaN    NaN     NaN      NaN     NaN

[725 rows x 5 columns]
VET    0.250193
BNB    0.047158
BAT   -0.018696
XLM   -0.001691
ZRX    0.116969
Name: 121, dtype: float64
報酬 0.07878652614371125 %
i= VET    0.250193
BNB    0.047158
BAT   -0.018696
XLM   -0.001691
ZRX    0.116969
Name: 121, dtype: float64
熊式-----------------------------------
執行第 128
           128
ZIL  -0.146104
ZRX  -0.108275
VET  -0.105899
BAT  -0.105155
TRX  -0.062628
XLM  -0.060852
BNB  -0.059987
IOTA -0.052734
ADA  -0.045752
XRP  -0.031616
BCH  -0.028197
ETH  -0.024180
LTC  -0.019737
ICX  -0.019259
NEO  -0.011662
LINK  0.009569
ALGO  0.033595
QTUM  0.038879
ZEC   0.093063
ATOM  0.122404
g================================================================          ZIL     ZRX       VET     BAT      TRX
0    0.00879  0.1814  0.004916  0.1972  0.02049
1    0.00762  0.1624  0.004628  0.1682  0.01778
2    0.00749  0.1736  0.004580  0.1870  0.01752
3    0.00732  0.1751  0.004493  0.1788  0.01688
4    0.00773  0.1711  0.004454  0.1764  0.01692
..       ...     ...       ...     ...      ...
720      NaN     NaN       NaN     NaN      NaN
721      NaN     NaN       NaN     NaN      NaN
722      NaN     NaN       NaN     NaN      NaN
723      NaN     NaN       NaN     NaN      NaN
724      NaN     NaN       NaN     NaN      NaN

[725 rows x 5 columns]
ZIL    0.077236
ZRX    0.040388
VET    0.057873
BAT   -0.077899
TRX    0.031979
Name: 122, dtype: float64
報酬 0.025915281759025577 %
i= ZIL    0.077236
ZRX    0.040388
VET    0.057873
BAT   -0.077899
TRX    0.031979
Name: 122, dtype: float64
熊式-----------------------------------
執行第 129
           129
ZIL  -0.133956
VET  -0.133872
LTC  -0.095322
ZRX  -0.066441
IOTA -0.055230
XLM  -0.048908
BNB  -0.047497
ICX  -0.033749
ADA  -0.032275
TRX  -0.028315
XRP  -0.028151
ETH  -0.016174
ALGO -0.012350
NEO  -0.001908
BAT   0.000534
BCH   0.001517
LINK  0.014706
ATOM  0.053932
QTUM  0.070608
ZEC   0.128475
g================================================================          ZIL       VET    LTC     ZRX    IOTA
0    0.00879  0.004916  56.59  0.1814  0.2564
1    0.00762  0.004628  54.82  0.1624  0.2322
2    0.00749  0.004580  56.60  0.1736  0.2428
3    0.00732  0.004493  55.28  0.1751  0.2413
4    0.00773  0.004454  55.88  0.1711  0.2422
..       ...       ...    ...     ...     ...
720      NaN       NaN    NaN     NaN     NaN
721      NaN       NaN    NaN     NaN     NaN
722      NaN       NaN    NaN     NaN     NaN
723      NaN       NaN    NaN     NaN     NaN
724      NaN       NaN    NaN     NaN     NaN

[725 rows x 5 columns]
ZIL     0.131579
VET     0.359043
LTC    -0.132311
ZRX     0.103360
IOTA    0.016873
Name: 123, dtype: float64
報酬 0.09570885134018184 %
i= ZIL     0.131579
VET     0.359043
LTC    -0.132311
ZRX     0.103360
IOTA    0.016873
Name: 123, dtype: float64
熊式-----------------------------------
執行第 130
           130
VET  -0.235162
ZIL  -0.207110
ALGO -0.137731
LTC  -0.129531
ZRX  -0.107731
XLM  -0.087814
IOTA -0.082849
BNB  -0.076972
ADA  -0.064824
ICX  -0.059041
ETH  -0.057107
XRP  -0.056921
TRX  -0.054073
BAT  -0.050901
BCH  -0.031002
LINK -0.029268
NEO  -0.025357
QTUM  0.003442
ATOM  0.088145
ZEC   0.097403
g================================================================           VET      ZIL   ALGO    LTC     ZRX
0    0.004916  0.00879  0.809  56.59  0.1814
1    0.004628  0.00762  0.717  54.82  0.1624
2    0.004580  0.00749  0.710  56.60  0.1736
3    0.004493  0.00732  0.677  55.28  0.1751
4    0.004454  0.00773  0.683  55.88  0.1711
..        ...      ...    ...    ...     ...
720       NaN      NaN    NaN    NaN     NaN
721       NaN      NaN    NaN    NaN     NaN
722       NaN      NaN    NaN    NaN     NaN
723       NaN      NaN    NaN    NaN     NaN
724       NaN      NaN    NaN    NaN     NaN

[725 rows x 5 columns]
VET     0.276841
ZIL     0.062500
ALGO    0.325278
LTC    -0.059299
ZRX     0.042616
Name: 124, dtype: float64
報酬 0.12958723035075098 %
i= VET     0.276841
ZIL     0.062500
ALGO    0.325278
LTC    -0.059299
ZRX     0.042616
Name: 124, dtype: float64
熊式-----------------------------------
執行第 131
           131
VET  -0.184627
ZIL  -0.150413
LTC  -0.114848
ZRX  -0.101474
ALGO -0.092675
IOTA -0.072808
XLM  -0.066825
BNB  -0.061318
ICX  -0.056886
ETH  -0.033582
XRP  -0.031633
TRX  -0.030598
ADA  -0.020682
LINK -0.009569
BAT  -0.009189
BCH  -0.006626
QTUM  0.012097
NEO   0.022360
ZEC   0.063369
ATOM  0.226627
g================================================================           VET      ZIL    LTC     ZRX   ALGO
0    0.004916  0.00879  56.59  0.1814  0.809
1    0.004628  0.00762  54.82  0.1624  0.717
2    0.004580  0.00749  56.60  0.1736  0.710
3    0.004493  0.00732  55.28  0.1751  0.677
4    0.004454  0.00773  55.88  0.1711  0.683
..        ...      ...    ...     ...    ...
720       NaN      NaN    NaN     NaN    NaN
721       NaN      NaN    NaN     NaN    NaN
722       NaN      NaN    NaN     NaN    NaN
723       NaN      NaN    NaN     NaN    NaN
724       NaN      NaN    NaN     NaN    NaN

[725 rows x 5 columns]
VET     0.099795
ZIL     0.115686
LTC    -0.105374
ZRX    -0.014193
ALGO    0.310878
Name: 125, dtype: float64
報酬 0.08135845828818652 %
i= VET     0.099795
ZIL     0.115686
LTC    -0.105374
ZRX    -0.014193
ALGO    0.310878
Name: 125, dtype: float64
熊式-----------------------------------
執行第 132
           132
VET  -0.188546
LTC  -0.153498
ZRX  -0.148034
ZIL  -0.139785
LINK -0.127753
IOTA -0.119615
XLM  -0.116275
ALGO -0.112850
BNB  -0.091830
ETH  -0.088142
XRP  -0.076384
ADA  -0.061090
TRX  -0.050992
BCH  -0.049482
QTUM -0.049425
ICX  -0.040931
NEO  -0.020269
ZEC  -0.016983
BAT   0.001719
ATOM  0.132961
g================================================================           VET    LTC     ZRX      ZIL  LINK
0    0.004916  56.59  0.1814  0.00879  2.42
1    0.004628  54.82  0.1624  0.00762  2.28
2    0.004580  56.60  0.1736  0.00749  2.42
3    0.004493  55.28  0.1751  0.00732  2.30
4    0.004454  55.88  0.1711  0.00773  2.40
..        ...    ...     ...      ...   ...
720       NaN    NaN     NaN      NaN   NaN
721       NaN    NaN     NaN      NaN   NaN
722       NaN    NaN     NaN      NaN   NaN
723       NaN    NaN     NaN      NaN   NaN
724       NaN    NaN     NaN      NaN   NaN

[725 rows x 5 columns]
VET     0.060732
LTC    -0.092276
ZRX    -0.118664
ZIL     0.054688
LINK   -0.085586
Name: 126, dtype: float64
報酬 -0.036221153226657046 %
i= VET     0.060732
LTC    -0.092276
ZRX    -0.118664
ZIL     0.054688
LINK   -0.085586
Name: 126, dtype: float64
熊式-----------------------------------
執行第 133
           133
LTC  -0.270815
VET  -0.237766
ALGO -0.237182
IOTA -0.223228
ZIL  -0.218085
ZRX  -0.198741
LINK -0.192661
XLM  -0.180682
XRP  -0.171531
BNB  -0.163058
ETH  -0.149711
BCH  -0.148238
ICX  -0.143081
ADA  -0.134899
QTUM -0.125714
BAT  -0.123303
TRX  -0.120848
ZEC  -0.116672
NEO  -0.077311
ATOM -0.048130
g================================================================        LTC       VET   ALGO    IOTA      ZIL
0    56.59  0.004916  0.809  0.2564  0.00879
1    54.82  0.004628  0.717  0.2322  0.00762
2    56.60  0.004580  0.710  0.2428  0.00749
3    55.28  0.004493  0.677  0.2413  0.00732
4    55.88  0.004454  0.683  0.2422  0.00773
..     ...       ...    ...     ...      ...
720    NaN       NaN    NaN     NaN      NaN
721    NaN       NaN    NaN     NaN      NaN
722    NaN       NaN    NaN     NaN      NaN
723    NaN       NaN    NaN     NaN      NaN
724    NaN       NaN    NaN     NaN      NaN

[725 rows x 5 columns]
LTC    -0.128990
VET     0.082021
ALGO   -0.076440
IOTA   -0.029089
ZIL     0.093511
Name: 127, dtype: float64
報酬 -0.011797151808039308 %
i= LTC    -0.128990
VET     0.082021
ALGO   -0.076440
IOTA   -0.029089
ZIL     0.093511
Name: 127, dtype: float64
熊式-----------------------------------
執行第 134
           134
LTC  -0.241695
IOTA -0.183505
VET  -0.145478
ALGO -0.116287
LINK -0.113744
XLM  -0.106518
XRP  -0.103759
ICX  -0.092145
BCH  -0.086319
ETH  -0.084553
ZEC  -0.080741
BNB  -0.078751
QTUM -0.077050
ZRX  -0.071560
ADA  -0.058356
BAT  -0.030530
TRX  -0.029775
ZIL  -0.024715
NEO   0.015733
ATOM  0.042113
g================================================================        LTC    IOTA       VET   ALGO  LINK
0    56.59  0.2564  0.004916  0.809  2.42
1    54.82  0.2322  0.004628  0.717  2.28
2    56.60  0.2428  0.004580  0.710  2.42
3    55.28  0.2413  0.004493  0.677  2.30
4    55.88  0.2422  0.004454  0.683  2.40
..     ...     ...       ...    ...   ...
720    NaN     NaN       NaN    NaN   NaN
721    NaN     NaN       NaN    NaN   NaN
722    NaN     NaN       NaN    NaN   NaN
723    NaN     NaN       NaN    NaN   NaN
724    NaN     NaN       NaN    NaN   NaN

[725 rows x 5 columns]
LTC    -0.080112
IOTA   -0.058824
VET     0.074853
ALGO   -0.029699
LINK   -0.106838

Name: 128, dtype: float64
報酬 -0.04012388059021046 %
i= LTC    -0.080112
IOTA   -0.058824
VET     0.074853
ALGO   -0.029699
LINK   -0.106838
Name: 128, dtype: float64
熊式-----------------------------------
執行第 135
           135
LTC  -0.266784
IOTA -0.156751
ALGO -0.155204
ZRX  -0.150952
XRP  -0.148051
ZEC  -0.143286
VET  -0.143196
XLM  -0.142315
LINK -0.130435
BCH  -0.119582
ZIL  -0.115108
ETH  -0.115079
ADA  -0.111350
ICX  -0.110099
QTUM -0.109920
BAT  -0.109333
BNB  -0.101752
TRX  -0.078181
NEO  -0.034743
ATOM  0.076380
g================================================================        LTC    IOTA   ALGO     ZRX      XRP
0    56.59  0.2564  0.809  0.1814  0.29787
1    54.82  0.2322  0.717  0.1624  0.26338
2    56.60  0.2428  0.710  0.1736  0.26408
3    55.28  0.2413  0.677  0.1751  0.26055
4    55.88  0.2422  0.683  0.1711  0.26543
..     ...     ...    ...     ...      ...
720    NaN     NaN    NaN     NaN      NaN
721    NaN     NaN    NaN     NaN      NaN
722    NaN     NaN    NaN     NaN      NaN
723    NaN     NaN    NaN     NaN      NaN
724    NaN     NaN    NaN     NaN      NaN

[725 rows x 5 columns]
LTC     0.031986
IOTA   -0.023855
ALGO    0.039653
ZRX    -0.082686
XRP     0.006608
Name: 129, dtype: float64
報酬 -0.005659134892907614 %
i= LTC     0.031986
IOTA   -0.023855
ALGO    0.039653
ZRX    -0.082686
XRP     0.006608
Name: 129, dtype: float64
熊式-----------------------------------
執行第 136
           136
IOTA -0.136292
LTC  -0.127160
ZEC  -0.116786
XRP  -0.096598
ETH  -0.096171
XLM  -0.092141
ZRX  -0.090909
BCH  -0.090251
ICX  -0.069804
ADA  -0.063795
BNB  -0.061849
BAT  -0.052514
QTUM -0.052030
ALGO -0.049544
LINK -0.035176
TRX  -0.032562
NEO  -0.021586
ZIL  -0.015595
VET  -0.010273
ATOM  0.011975
g================================================================        IOTA    LTC    ZEC      XRP     ETH
0    0.2564  56.59  55.45  0.29787  209.22
1    0.2322  54.82  50.56  0.26338  187.11
2    0.2428  56.60  50.57  0.26408  188.16
3    0.2413  55.28  48.85  0.26055  185.03
4    0.2422  55.88  50.01  0.26543  185.61
..      ...    ...    ...      ...     ...
720     NaN    NaN    NaN      NaN     NaN
721     NaN    NaN    NaN      NaN     NaN
722     NaN    NaN    NaN      NaN     NaN
723     NaN    NaN    NaN      NaN     NaN
724     NaN    NaN    NaN      NaN     NaN

[725 rows x 5 columns]
IOTA    0.007321
LTC    -0.013832
ZEC     0.047619
XRP     0.019583
ETH    -0.002454
Name: 130, dtype: float64
報酬 0.011647260701115903 %
i= IOTA    0.007321
LTC    -0.013832
ZEC     0.047619
XRP     0.019583
ETH    -0.002454
Name: 130, dtype: float64
熊式-----------------------------------
執行第 137
           137
ZEC  -0.138948
IOTA -0.137821
XRP  -0.119255
XLM  -0.109476
ETH  -0.108459
LINK -0.101449
BCH  -0.099816
ALGO -0.098761
BAT  -0.096017
ATOM -0.095832
ADA  -0.094076
QTUM -0.078543
BNB  -0.076442
ZRX  -0.074807
ZIL  -0.060311
ICX  -0.048413
NEO  -0.046321
VET  -0.045430
LTC  -0.034180
TRX  -0.030129
g================================================================        ZEC    IOTA      XRP      XLM     ETH
0    55.45  0.2564  0.29787  0.07442  209.22
1    50.56  0.2322  0.26338  0.06922  187.11
2    50.57  0.2428  0.26408  0.07019  188.16
3    48.85  0.2413  0.26055  0.06851  185.03
4    50.01  0.2422  0.26543  0.06770  185.61
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
ZEC     0.118221
IOTA   -0.028393
XRP     0.024138
XLM    -0.018509
ETH    -0.008476
Name: 131, dtype: float64
報酬 0.017396387464806252 %
i= ZEC     0.118221
IOTA   -0.028393
XRP     0.024138
XLM    -0.018509
ETH    -0.008476
Name: 131, dtype: float64
熊式-----------------------------------
執行第 138
           138
XRP  -0.044172
IOTA -0.043754
LINK -0.030303
LTC  -0.028772
ZEC  -0.014228
BAT  -0.009725
ZRX  -0.006743
ETH  -0.004520
BCH   0.000611
XLM   0.005535
ADA   0.007034
ALGO  0.015183
QTUM  0.016324
BNB   0.024535
ZIL   0.027083
ICX   0.043515
ATOM  0.049556
NEO   0.064339
VET   0.093180
TRX   0.111194
g================================================================          XRP    IOTA  LINK    LTC    ZEC
0    0.29787  0.2564  2.42  56.59  55.45
1    0.26338  0.2322  2.28  54.82  50.56
2    0.26408  0.2428  2.42  56.60  50.57
3    0.26055  0.2413  2.30  55.28  48.85
4    0.26543  0.2422  2.40  55.88  50.01
..       ...     ...   ...    ...    ...
720      NaN     NaN   NaN    NaN    NaN
721      NaN     NaN   NaN    NaN    NaN
722      NaN     NaN   NaN    NaN    NaN
723      NaN     NaN   NaN    NaN    NaN
724      NaN     NaN   NaN    NaN    NaN

[725 rows x 5 columns]
XRP     0.014172
IOTA   -0.026160
LINK    0.070755
LTC    -0.028776
ZEC     0.100403
Name: 132, dtype: float64
報酬 0.02607877166252657 %
i= XRP     0.014172
IOTA   -0.026160
LINK    0.070755
LTC    -0.028776
ZEC     0.100403
Name: 132, dtype: float64
熊式-----------------------------------
執行第 139
           139
ZEC   0.020931
ZRX   0.028620
XRP   0.036374
XLM   0.039297
IOTA  0.045307
ADA   0.045455
ETH   0.047974
BAT   0.049677
QTUM  0.053595
LINK  0.056818
ZIL   0.068027
BCH   0.076020
BNB   0.076799
ICX   0.083942
NEO   0.086454
ALGO  0.098765
TRX   0.108521
LTC   0.116631
ATOM  0.182468
VET   0.280156
g================================================================        ZEC     ZRX      XRP      XLM    IOTA
0    55.45  0.1814  0.29787  0.07442  0.2564
1    50.56  0.1624  0.26338  0.06922  0.2322
2    50.57  0.1736  0.26408  0.07019  0.2428
3    48.85  0.1751  0.26055  0.06851  0.2413
4    50.01  0.1711  0.26543  0.06770  0.2422
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
ZEC     0.176669
ZRX    -0.030937
XRP     0.033192
XLM    -0.034205
IOTA    0.011699
Name: 133, dtype: float64
報酬 0.031283505371150856 %
i= ZEC     0.176669
ZRX    -0.030937
XRP     0.033192
XLM    -0.034205
IOTA    0.011699
Name: 133, dtype: float64
熊式-----------------------------------
執行第 140
           140
ZRX  -0.088016
ZIL  -0.081871
ALGO -0.057622
QTUM -0.044126
ZEC  -0.041012
ETH  -0.037020
XLM  -0.031418
XRP  -0.025188
BAT  -0.019014
IOTA -0.017677
BNB  -0.016949
LINK -0.016043
ADA  -0.013966
ICX  -0.009983
NEO  -0.009681
BCH  -0.003334
TRX   0.013473
ATOM  0.025228
LTC   0.101892
VET   0.125047
g================================================================         ZRX      ZIL   ALGO   QTUM    ZEC
0    0.1814  0.00879  0.809  2.642  55.45
1    0.1624  0.00762  0.717  2.347  50.56
2    0.1736  0.00749  0.710  2.376  50.57
3    0.1751  0.00732  0.677  2.291  48.85
4    0.1711  0.00773  0.683  2.455  50.01
..      ...      ...    ...    ...    ...
720     NaN      NaN    NaN    NaN    NaN
721     NaN      NaN    NaN    NaN    NaN
722     NaN      NaN    NaN    NaN    NaN
723     NaN      NaN    NaN    NaN    NaN
724     NaN      NaN    NaN    NaN    NaN

[725 rows x 5 columns]
ZRX    -0.062743
ZIL    -0.082024
ALGO    0.046485
QTUM    0.049682
ZEC     0.055022
Name: 134, dtype: float64
報酬 0.0012842472007601469 %
i= ZRX    -0.062743
ZIL    -0.082024
ALGO    0.046485
QTUM    0.049682
ZEC     0.055022
Name: 134, dtype: float64
熊式-----------------------------------
執行第 141
           141
ZIL  -0.060976
QTUM -0.043976
IOTA -0.043558
ZEC  -0.040323
BAT  -0.040120
ZRX  -0.038441
ETH  -0.023573
BNB  -0.019505
XLM  -0.018584
LINK -0.011111
ALGO -0.009578
BCH  -0.004622
ATOM -0.003279
NEO   0.000466
XRP   0.003512
ADA   0.009080
TRX   0.018504
ICX   0.029863
VET   0.158020
LTC   0.200378
g================================================================          ZIL   QTUM    IOTA    ZEC     BAT
0    0.00879  2.642  0.2564  55.45  0.1972
1    0.00762  2.347  0.2322  50.56  0.1682
2    0.00749  2.376  0.2428  50.57  0.1870
3    0.00732  2.291  0.2413  48.85  0.1788
4    0.00773  2.455  0.2422  50.01  0.1764
..       ...    ...     ...    ...     ...
720      NaN    NaN     NaN    NaN     NaN
721      NaN    NaN     NaN    NaN     NaN
722      NaN    NaN     NaN    NaN     NaN
723      NaN    NaN     NaN    NaN     NaN
724      NaN    NaN     NaN    NaN     NaN

[725 rows x 5 columns]
ZIL    -0.097403
QTUM    0.066324
IOTA   -0.056152
ZEC     0.143201
BAT    -0.033505
Name: 135, dtype: float64
報酬 0.004492813430440256 %
i= ZIL    -0.097403
QTUM    0.066324
IOTA   -0.056152
ZEC     0.143201
BAT    -0.033505
Name: 135, dtype: float64
熊式-----------------------------------
執行第 142
           142
ZIL  -0.091089
ZRX  -0.056250
QTUM -0.041616
LINK -0.036458
IOTA -0.034862
XLM  -0.033110
XRP  -0.030485
BAT  -0.027123
BNB  -0.026667
ZEC  -0.026446
ETH  -0.020282
NEO  -0.010102
TRX  -0.001496
ALGO -0.000834
BCH   0.001654
LTC   0.003781
ICX   0.007589
ADA   0.007670
VET   0.016682
ATOM  0.056613
g================================================================          ZIL     ZRX   QTUM  LINK    IOTA
0    0.00879  0.1814  2.642  2.42  0.2564
1    0.00762  0.1624  2.347  2.28  0.2322
2    0.00749  0.1736  2.376  2.42  0.2428
3    0.00732  0.1751  2.291  2.30  0.2413
4    0.00773  0.1711  2.455  2.40  0.2422
..       ...     ...    ...   ...     ...
720      NaN     NaN    NaN   NaN     NaN
721      NaN     NaN    NaN   NaN     NaN
722      NaN     NaN    NaN   NaN     NaN
723      NaN     NaN    NaN   NaN     NaN
724      NaN     NaN    NaN   NaN     NaN

[725 rows x 5 columns]
ZIL    -0.200935
ZRX    -0.106221
QTUM    0.004018
LINK   -0.024510
IOTA   -0.074780
Name: 136, dtype: float64
報酬 -0.08048539559005488 %
i= ZIL    -0.200935
ZRX    -0.106221
QTUM    0.004018
LINK   -0.024510
IOTA   -0.074780
Name: 136, dtype: float64
熊式-----------------------------------
執行第 143
           143
LTC  -0.067121
ALGO -0.043750
ZRX  -0.032864
ZIL  -0.024845
ZEC  -0.024718
TRX  -0.021450
XRP  -0.007313
QTUM -0.006177
ETH  -0.005591
ADA  -0.003936
ICX  -0.002502
BNB   0.000000
IOTA  0.001859
XLM   0.009914
LINK  0.010753
BAT   0.025347
NEO   0.025873
VET   0.065651
BCH   0.091124
ATOM  0.110673
g================================================================        LTC   ALGO     ZRX      ZIL    ZEC
0    56.59  0.809  0.1814  0.00879  55.45
1    54.82  0.717  0.1624  0.00762  50.56
2    56.60  0.710  0.1736  0.00749  50.57
3    55.28  0.677  0.1751  0.00732  48.85
4    55.88  0.683  0.1711  0.00773  50.01
..     ...    ...     ...      ...    ...
720    NaN    NaN     NaN      NaN    NaN
721    NaN    NaN     NaN      NaN    NaN
722    NaN    NaN     NaN      NaN    NaN
723    NaN    NaN     NaN      NaN    NaN
724    NaN    NaN     NaN      NaN    NaN

[725 rows x 5 columns]
LTC    -0.114998
ALGO   -0.089884
ZRX    -0.124630
ZIL    -0.205564
ZEC     0.124060
Name: 137, dtype: float64
報酬 -0.08220320272123849 %
i= LTC    -0.114998
ALGO   -0.089884
ZRX    -0.124630
ZIL    -0.205564
ZEC     0.124060
Name: 137, dtype: float64
熊式-----------------------------------
執行第 144
           144
TRX  -0.094694
ALGO -0.059418
ICX  -0.053729
LTC  -0.051410
ZIL  -0.048682
ZRX  -0.038120
ZEC  -0.032302
QTUM -0.032124
ETH  -0.030576
XLM  -0.029007
LINK -0.026042
ADA  -0.020664
XRP  -0.016439
NEO  -0.015056
IOTA -0.014449
BNB  -0.007257
VET   0.027566
ATOM  0.033122
BCH   0.049074
BAT   0.072790
g================================================================          TRX   ALGO     ICX    LTC      ZIL
0    0.02049  0.809  0.2002  56.59  0.00879
1    0.01778  0.717  0.1862  54.82  0.00762
2    0.01752  0.710  0.2011  56.60  0.00749
3    0.01688  0.677  0.1925  55.28  0.00732
4    0.01692  0.683  0.1975  55.88  0.00773
..       ...    ...     ...    ...      ...
720      NaN    NaN     NaN    NaN      NaN
721      NaN    NaN     NaN    NaN      NaN
722      NaN    NaN     NaN    NaN      NaN
723      NaN    NaN     NaN    NaN      NaN
724      NaN    NaN     NaN    NaN      NaN

[725 rows x 5 columns]
TRX    -0.068150
ALGO   -0.169676
ICX    -0.105539
LTC    -0.145272
ZIL    -0.206612
Name: 138, dtype: float64
報酬 -0.13904974381871732 %
i= TRX    -0.068150
ALGO   -0.169676
ICX    -0.105539
LTC    -0.145272
ZIL    -0.206612
Name: 138, dtype: float64
熊式-----------------------------------
執行第 145
           145
LTC  -0.062450
VET  -0.059102
ALGO -0.035789
ATOM -0.011620
TRX  -0.006526
ICX  -0.005051
ZIL   0.000000
LINK  0.021505
XLM   0.028470
ZEC   0.030046
ADA   0.030193
QTUM  0.033499
XRP   0.036151
IOTA  0.040248
ETH   0.051334
BNB   0.059309
ZRX   0.074741
NEO   0.075134
BCH   0.118645
BAT   0.178857
g================================================================        LTC       VET   ALGO   ATOM      TRX
0    56.59  0.004916  0.809  3.258  0.02049
1    54.82  0.004628  0.717  2.857  0.01778
2    56.60  0.004580  0.710  2.898  0.01752
3    55.28  0.004493  0.677  2.884  0.01688
4    55.88  0.004454  0.683  2.910  0.01692
..     ...       ...    ...    ...      ...
720    NaN       NaN    NaN    NaN      NaN
721    NaN       NaN    NaN    NaN      NaN
722    NaN       NaN    NaN    NaN      NaN
723    NaN       NaN    NaN    NaN      NaN
724    NaN       NaN    NaN    NaN      NaN

[725 rows x 5 columns]
LTC    -0.248661
VET    -0.255792
ALGO   -0.203859
ATOM    0.016480
TRX    -0.118980
Name: 139, dtype: float64
報酬 -0.16216216951682988 %
i= LTC    -0.248661
VET    -0.255792
ALGO   -0.203859
ATOM    0.016480
TRX    -0.118980
Name: 139, dtype: float64
熊式-----------------------------------
執行第 146
           146
LTC  -0.107831
VET  -0.091898
ATOM -0.050809
ZIL  -0.031847
ICX  -0.028571
ALGO -0.022984
TRX  -0.017725
ADA  -0.013278
LINK -0.010870
ZEC   0.010335
XLM   0.011331
XRP   0.012945
QTUM  0.016843
IOTA  0.025064
ZRX   0.026718
NEO   0.028522
ETH   0.030301
BNB   0.038231
BCH   0.107854
BAT   0.142944
g================================================================        LTC       VET   ATOM      ZIL     ICX
0    56.59  0.004916  3.258  0.00879  0.2002
1    54.82  0.004628  2.857  0.00762  0.1862
2    56.60  0.004580  2.898  0.00749  0.2011
3    55.28  0.004493  2.884  0.00732  0.1925
4    55.88  0.004454  2.910  0.00773  0.1975
..     ...       ...    ...      ...     ...
720    NaN       NaN    NaN      NaN     NaN
721    NaN       NaN    NaN      NaN     NaN
722    NaN       NaN    NaN      NaN     NaN
723    NaN       NaN    NaN      NaN     NaN
724    NaN       NaN    NaN      NaN     NaN

[725 rows x 5 columns]
LTC    -0.265779
VET    -0.125062
ATOM    0.119801
ZIL    -0.090426
ICX    -0.060203
Name: 140, dtype: float64
報酬 -0.08433359478345444 %
i= LTC    -0.265779
VET    -0.125062
ATOM    0.119801
ZIL    -0.090426
ICX    -0.060203
Name: 140, dtype: float64
熊式-----------------------------------
執行第 147
           147
VET  -0.103625
LTC  -0.058126
ICX  -0.056338
ALGO -0.047033
ZIL  -0.032468
ADA  -0.015597
ATOM -0.006814
LINK -0.005618
ZEC   0.006211
TRX   0.006813
ZRX   0.007773
NEO   0.010362
XLM   0.012173
QTUM  0.015753
XRP   0.023118
IOTA  0.024375
ETH   0.032617
BNB   0.049732
BCH   0.105459
BAT   0.124766
g================================================================           VET    LTC     ICX   ALGO      ZIL
0    0.004916  56.59  0.2002  0.809  0.00879
1    0.004628  54.82  0.1862  0.717  0.00762
2    0.004580  56.60  0.2011  0.710  0.00749
3    0.004493  55.28  0.1925  0.677  0.00732
4    0.004454  55.88  0.1975  0.683  0.00773
..        ...    ...     ...    ...      ...
720       NaN    NaN     NaN    NaN      NaN
721       NaN    NaN     NaN    NaN      NaN
722       NaN    NaN     NaN    NaN      NaN
723       NaN    NaN     NaN    NaN      NaN
724       NaN    NaN     NaN    NaN      NaN

[725 rows x 5 columns]
VET    -0.187319
LTC    -0.333893
ICX    -0.114804
ALGO   -0.170459
ZIL    -0.064639
Name: 141, dtype: float64
報酬 -0.17422252652451853 %
i= VET    -0.187319
LTC    -0.333893
ICX    -0.114804
ALGO   -0.170459
ZIL    -0.064639
Name: 141, dtype: float64

熊式-----------------------------------
執行第 148
           148
ALGO -0.081386
ICX  -0.041004
ATOM -0.038208
VET  -0.023154
LINK -0.021622
ADA  -0.019906
ZIL  -0.010893
TRX  -0.009738
LTC   0.002105
ZRX   0.007174
QTUM  0.008811
XLM   0.013653
ZEC   0.016661
IOTA  0.017744
XRP   0.020081
NEO   0.037537
ETH   0.040529
BNB   0.042618
BCH   0.089185
BAT   0.189091
g================================================================       ALGO     ICX   ATOM       VET  LINK
0    0.809  0.2002  3.258  0.004916  2.42
1    0.717  0.1862  2.857  0.004628  2.28
2    0.710  0.2011  2.898  0.004580  2.42
3    0.677  0.1925  2.884  0.004493  2.30
4    0.683  0.1975  2.910  0.004454  2.40
..     ...     ...    ...       ...   ...
720    NaN     NaN    NaN       NaN   NaN
721    NaN     NaN    NaN       NaN   NaN
722    NaN     NaN    NaN       NaN   NaN
723    NaN     NaN    NaN       NaN   NaN
724    NaN     NaN    NaN       NaN   NaN

[725 rows x 5 columns]
ALGO   -0.118058
ICX    -0.099468
ATOM    0.086463
VET    -0.084662
LINK   -0.072464
Name: 142, dtype: float64
報酬 -0.057637882561131316 %
i= ALGO   -0.118058
ICX    -0.099468
ATOM    0.086463
VET    -0.084662
LINK   -0.072464
Name: 142, dtype: float64
熊式-----------------------------------
執行第 149
           149
VET  -0.100794
ATOM -0.090990
ICX  -0.083612
LINK -0.074468
ZIL  -0.070064
ALGO -0.067974
ZRX  -0.055016
XLM  -0.048429
QTUM -0.047234
LTC  -0.044506
BCH  -0.038386
NEO  -0.029921
TRX  -0.029478
ZEC  -0.021723
IOTA -0.021645
BNB  -0.021068
XRP  -0.013629
ADA  -0.006383
ETH   0.006335
BAT   0.075338
g================================================================           VET   ATOM     ICX  LINK      ZIL
0    0.004916  3.258  0.2002  2.42  0.00879
1    0.004628  2.857  0.1862  2.28  0.00762
2    0.004580  2.898  0.2011  2.42  0.00749
3    0.004493  2.884  0.1925  2.30  0.00732
4    0.004454  2.910  0.1975  2.40  0.00773
..        ...    ...     ...   ...      ...
720       NaN    NaN     NaN   NaN      NaN
721       NaN    NaN     NaN   NaN      NaN
722       NaN    NaN     NaN   NaN      NaN
723       NaN    NaN     NaN   NaN      NaN
724       NaN    NaN     NaN   NaN      NaN

[725 rows x 5 columns]
VET    -0.024766
ATOM   -0.047429
ICX    -0.059608
LINK   -0.065327
ZIL    -0.058480
Name: 143, dtype: float64
報酬 -0.0511218160736094 %
i= VET    -0.024766
ATOM   -0.047429
ICX    -0.059608
LINK   -0.065327
ZIL    -0.058480
Name: 143, dtype: float64
熊式-----------------------------------
執行第 150
           150
VET  -0.061419
LINK -0.037433
ATOM -0.036608
ZIL  -0.031983
ICX  -0.031356
ALGO -0.023636
ZRX  -0.011401
XLM  -0.004361
TRX  -0.002967
BNB  -0.002193
QTUM  0.000000
XRP   0.000414
BAT   0.003231
ZEC   0.008878
NEO   0.012891
ADA   0.015453
IOTA  0.017104
ETH   0.048247
LTC   0.059884
BCH   0.079193
g================================================================           VET  LINK   ATOM      ZIL     ICX
0    0.004916  2.42  3.258  0.00879  0.2002
1    0.004628  2.28  2.857  0.00762  0.1862
2    0.004580  2.42  2.898  0.00749  0.2011
3    0.004493  2.30  2.884  0.00732  0.1925
4    0.004454  2.40  2.910  0.00773  0.1975
..        ...   ...    ...      ...     ...
720       NaN   NaN    NaN      NaN     NaN
721       NaN   NaN    NaN      NaN     NaN
722       NaN   NaN    NaN      NaN     NaN
723       NaN   NaN    NaN      NaN     NaN
724       NaN   NaN    NaN      NaN     NaN

[725 rows x 5 columns]
VET    -0.009876
LINK   -0.072464
ATOM   -0.051259
ZIL    -0.040856
ICX    -0.010317
Name: 144, dtype: float64
報酬 -0.03695451052501397 %
i= VET    -0.009876
LINK   -0.072464
ATOM   -0.051259
ZIL    -0.040856
ICX    -0.010317
Name: 144, dtype: float64
熊式-----------------------------------
執行第 151
           151
ZRX  -0.053807
LINK -0.042105
ICX  -0.036379
BNB  -0.021262
ZIL  -0.021231
TRX  -0.018978
BAT  -0.018248
XRP  -0.017241
QTUM -0.014406
NEO  -0.013694
XLM  -0.012543
ETH  -0.001340
ATOM -0.000705
ADA   0.006448
VET   0.010409
ALGO  0.015106
ZEC   0.026424
IOTA  0.032143
LTC   0.049266
BCH   0.057787
g================================================================         ZRX  LINK     ICX    BNB      ZIL
0    0.1814  2.42  0.2002  29.42  0.00879
1    0.1624  2.28  0.1862  27.01  0.00762
2    0.1736  2.42  0.2011  28.11  0.00749
3    0.1751  2.30  0.1925  27.53  0.00732
4    0.1711  2.40  0.1975  27.50  0.00773
..      ...   ...     ...    ...      ...
720     NaN   NaN     NaN    NaN      NaN
721     NaN   NaN     NaN    NaN      NaN
722     NaN   NaN     NaN    NaN      NaN
723     NaN   NaN     NaN    NaN      NaN
724     NaN   NaN     NaN    NaN      NaN

[725 rows x 5 columns]
ZRX    -0.049274
LINK   -0.060606
ICX    -0.005858
BNB    -0.009665
ZIL    -0.018750
Name: 145, dtype: float64
報酬 -0.02883061752445799 %
i= ZRX    -0.049274
LINK   -0.060606
ICX    -0.005858
BNB    -0.009665
ZIL    -0.018750
Name: 145, dtype: float64
熊式-----------------------------------
執行第 152
           152
ICX  -0.018166
ZRX  -0.011683
LINK -0.010989
BAT  -0.006889
XLM  -0.001757
QTUM  0.000613
XRP   0.006675
VET   0.007373
ATOM  0.008161
NEO   0.008610
BNB   0.012996
ZIL   0.015351
TRX   0.018045
ALGO  0.018198
ETH   0.028726
ADA   0.034988
LTC   0.066284
BCH   0.068689
IOTA  0.077743
ZEC   0.086772
g================================================================         ICX     ZRX  LINK     BAT      XLM
0    0.2002  0.1814  2.42  0.1972  0.07442
1    0.1862  0.1624  2.28  0.1682  0.06922
2    0.2011  0.1736  2.42  0.1870  0.07019
3    0.1925  0.1751  2.30  0.1788  0.06851
4    0.1975  0.1711  2.40  0.1764  0.06770
..      ...     ...   ...     ...      ...
720     NaN     NaN   NaN     NaN      NaN
721     NaN     NaN   NaN     NaN      NaN
722     NaN     NaN   NaN     NaN      NaN
723     NaN     NaN   NaN     NaN      NaN
724     NaN     NaN   NaN     NaN      NaN

[725 rows x 5 columns]
ICX     0.085766
ZRX     0.029181
LINK    0.045455
BAT     0.065161
XLM     0.040453
Name: 146, dtype: float64
報酬 0.053203205883161964 %
i= ICX     0.085766
ZRX     0.029181
LINK    0.045455
BAT     0.065161
XLM     0.040453
Name: 146, dtype: float64
熊式-----------------------------------
執行第 153
           153
ATOM -0.027916
LTC   0.049014
BAT   0.062119
ZRX   0.078788
QTUM  0.083127
BNB   0.089650
VET   0.093857
ZIL   0.093960
ICX   0.095698
LINK  0.096045
TRX   0.103759
ETH   0.115429
ALGO  0.119004
XLM   0.124053
NEO   0.124337
ADA   0.137112
IOTA  0.143394
XRP   0.156509
BCH   0.192946
ZEC   0.193174
g================================================================       ATOM    LTC     BAT     ZRX   QTUM
0    3.258  56.59  0.1972  0.1814  2.642
1    2.857  54.82  0.1682  0.1624  2.347
2    2.898  56.60  0.1870  0.1736  2.376
3    2.884  55.28  0.1788  0.1751  2.291
4    2.910  55.88  0.1764  0.1711  2.455
..     ...    ...     ...     ...    ...
720    NaN    NaN     NaN     NaN    NaN
721    NaN    NaN     NaN     NaN    NaN
722    NaN    NaN     NaN     NaN    NaN
723    NaN    NaN     NaN     NaN    NaN
724    NaN    NaN     NaN     NaN    NaN

[725 rows x 5 columns]
ATOM   -0.005840
LTC     0.054431
BAT    -0.047534
ZRX    -0.104426
QTUM   -0.053667
Name: 147, dtype: float64
報酬 -0.031407208845171494 %
i= ATOM   -0.005840
LTC     0.054431
BAT    -0.047534
ZRX    -0.104426
QTUM   -0.053667
Name: 147, dtype: float64
熊式-----------------------------------
執行第 154
           154
ATOM -0.069635
BAT  -0.020387
LTC   0.023881
ZRX   0.029041
VET   0.041247
ICX   0.046248
ALGO  0.046343
ZIL   0.061674
XLM   0.069110
QTUM  0.084217
TRX   0.085477
ETH   0.093817
BNB   0.096350
ADA   0.105735
XRP   0.105735
NEO   0.108084
ZEC   0.148913
IOTA  0.156289
LINK  0.160221
BCH   0.187781
g================================================================       ATOM     BAT    LTC     ZRX       VET
0    3.258  0.1972  56.59  0.1814  0.004916
1    2.857  0.1682  54.82  0.1624  0.004628
2    2.898  0.1870  56.60  0.1736  0.004580
3    2.884  0.1788  55.28  0.1751  0.004493
4    2.910  0.1764  55.88  0.1711  0.004454
..     ...     ...    ...     ...       ...
720    NaN     NaN    NaN     NaN       NaN
721    NaN     NaN    NaN     NaN       NaN
722    NaN     NaN    NaN     NaN       NaN
723    NaN     NaN    NaN     NaN       NaN
724    NaN     NaN    NaN     NaN       NaN

[725 rows x 5 columns]
ATOM    0.066511
BAT    -0.011976
LTC     0.136776
ZRX    -0.032568
VET     0.086139
Name: 148, dtype: float64
報酬 0.048976170125578956 %
i= ATOM    0.066511
BAT    -0.011976
LTC     0.136776
ZRX    -0.032568
VET     0.086139
Name: 148, dtype: float64
熊式-----------------------------------
執行第 155
           155
ATOM -0.025635
BAT  -0.003284
ALGO  0.067789
ICX   0.068431
LTC   0.070533
ZIL   0.070776
VET   0.077150
XLM   0.091930
TRX   0.092679
QTUM  0.097847
ETH   0.106539
XRP   0.107554
ADA   0.110737
NEO   0.116521
BNB   0.116833
IOTA  0.142225
ZEC   0.142857
ZRX   0.214041
BCH   0.227994
LINK  0.258621
g================================================================       ATOM     BAT   ALGO     ICX    LTC
0    3.258  0.1972  0.809  0.2002  56.59
1    2.857  0.1682  0.717  0.1862  54.82
2    2.898  0.1870  0.710  0.2011  56.60
3    2.884  0.1788  0.677  0.1925  55.28
4    2.910  0.1764  0.683  0.1975  55.88
..     ...     ...    ...     ...    ...
720    NaN     NaN    NaN     NaN    NaN
721    NaN     NaN    NaN     NaN    NaN
722    NaN     NaN    NaN     NaN    NaN
723    NaN     NaN    NaN     NaN    NaN
724    NaN     NaN    NaN     NaN    NaN

[725 rows x 5 columns]
ATOM    0.045476
BAT     0.001769
ALGO   -0.042952
ICX     0.008432
LTC     0.049488
Name: 149, dtype: float64
報酬 0.012442436591933559 %
i= ATOM    0.045476
BAT     0.001769
ALGO   -0.042952
ICX     0.008432
LTC     0.049488
Name: 149, dtype: float64
熊式-----------------------------------
執行第 156
           156
LTC  -0.058222
ALGO -0.022007
BAT  -0.006441
VET   0.001128
ATOM  0.001888
QTUM  0.004302
ZIL   0.011013
ICX   0.020997
ETH   0.025918
XLM   0.033290
TRX   0.040923
BNB   0.052015
XRP   0.053484
NEO   0.057214
ADA   0.057653
IOTA  0.063063
BCH   0.070189
ZEC   0.085181
ZRX   0.130148
LINK  0.216667
g================================================================        LTC   ALGO     BAT       VET   ATOM
0    56.59  0.809  0.1972  0.004916  3.258
1    54.82  0.717  0.1682  0.004628  2.857
2    56.60  0.710  0.1870  0.004580  2.898
3    55.28  0.677  0.1788  0.004493  2.884
4    55.88  0.683  0.1764  0.004454  2.910
..     ...    ...     ...       ...    ...
720    NaN    NaN     NaN       NaN    NaN
721    NaN    NaN     NaN       NaN    NaN
722    NaN    NaN     NaN       NaN    NaN
723    NaN    NaN     NaN       NaN    NaN
724    NaN    NaN     NaN       NaN    NaN

[725 rows x 5 columns]
LTC    -0.078885
ALGO   -0.030417
BAT     0.120700
VET     0.065839
ATOM    0.084052
Name: 150, dtype: float64
報酬 0.03225793819236762 %
i= LTC    -0.078885
ALGO   -0.030417
BAT     0.120700
VET     0.065839
ATOM    0.084052
Name: 150, dtype: float64
熊式-----------------------------------
執行第 157
           157
LTC  -0.082142
ALGO -0.039541
VET  -0.031083
BAT  -0.003717
ATOM  0.004706
ZIL   0.017354
ICX   0.043020
XLM   0.051686
QTUM  0.055420
ADA   0.074549
ETH   0.079824
ZRX   0.086910
NEO   0.089587
BNB   0.091238
TRX   0.093006
IOTA  0.096886
XRP   0.101589
ZEC   0.124707
BCH   0.209929
LINK  0.225275
g================================================================        LTC   ALGO       VET     BAT   ATOM
0    56.59  0.809  0.004916  0.1972  3.258
1    54.82  0.717  0.004628  0.1682  2.857
2    56.60  0.710  0.004580  0.1870  2.898
3    55.28  0.677  0.004493  0.1788  2.884
4    55.88  0.683  0.004454  0.1764  2.910
..     ...    ...       ...     ...    ...
720    NaN    NaN       NaN     NaN    NaN
721    NaN    NaN       NaN     NaN    NaN
722    NaN    NaN       NaN     NaN    NaN
723    NaN    NaN       NaN     NaN    NaN
724    NaN    NaN       NaN     NaN    NaN

[725 rows x 5 columns]
LTC    -0.043266
ALGO   -0.063460
VET     0.010519
BAT     0.108030
ATOM   -0.000940
Name: 151, dtype: float64
報酬 0.002176660548193099 %
i= LTC    -0.043266
ALGO   -0.063460
VET     0.010519
BAT     0.108030
ATOM   -0.000940
Name: 151, dtype: float64

熊式-----------------------------------
執行第 158
           158
LTC  -0.048127
ALGO -0.013078
ZIL   0.004320
BAT   0.006403
VET   0.013175
ATOM  0.015238
ETH   0.051784
ICX   0.059031
XLM   0.062720
ADA   0.063565
BNB   0.064861
QTUM  0.066830
NEO   0.076718
TRX   0.079025
XRP   0.086811
ZRX   0.109081
IOTA  0.115765
ZEC   0.132749
BCH   0.171115
LINK  0.266667
g================================================================        LTC   ALGO      ZIL     BAT       VET
0    56.59  0.809  0.00879  0.1972  0.004916
1    54.82  0.717  0.00762  0.1682  0.004628
2    56.60  0.710  0.00749  0.1870  0.004580
3    55.28  0.677  0.00732  0.1788  0.004493
4    55.88  0.683  0.00773  0.1764  0.004454
..     ...    ...      ...     ...       ...
720    NaN    NaN      NaN     NaN       NaN
721    NaN    NaN      NaN     NaN       NaN
722    NaN    NaN      NaN     NaN       NaN
723    NaN    NaN      NaN     NaN       NaN
724    NaN    NaN      NaN     NaN       NaN

[725 rows x 5 columns]
LTC    -0.113528
ALGO   -0.062422
ZIL    -0.031847
BAT     0.159803
VET    -0.083924
Name: 152, dtype: float64
報酬 -0.02638353422013522 %
i= LTC    -0.113528
ALGO   -0.062422
ZIL    -0.031847
BAT     0.159803
VET    -0.083924
Name: 152, dtype: float64
熊式-----------------------------------
執行第 159
           159
LTC  -0.105235
ALGO -0.059357
VET  -0.036449
XRP  -0.034773
XLM  -0.028136
ICX  -0.026442
ZIL  -0.022495
BAT  -0.006789
QTUM  0.005155
ADA   0.015273
ETH   0.016796
TRX   0.024523
BNB   0.025418
ATOM  0.035045
IOTA  0.047645
NEO   0.052475
ZEC   0.080949
BCH   0.106912
ZRX   0.114402
LINK  0.154639
g================================================================        LTC   ALGO       VET      XRP      XLM
0    56.59  0.809  0.004916  0.29787  0.07442
1    54.82  0.717  0.004628  0.26338  0.06922
2    56.60  0.710  0.004580  0.26408  0.07019
3    55.28  0.677  0.004493  0.26055  0.06851
4    55.88  0.683  0.004454  0.26543  0.06770
..     ...    ...       ...      ...      ...
720    NaN    NaN       NaN      NaN      NaN
721    NaN    NaN       NaN      NaN      NaN
722    NaN    NaN       NaN      NaN      NaN
723    NaN    NaN       NaN      NaN      NaN
724    NaN    NaN       NaN      NaN      NaN

[725 rows x 5 columns]
LTC    -0.098695
ALGO   -0.059844
VET    -0.122531
XRP     0.011321
XLM    -0.002444
Name: 153, dtype: float64
報酬 -0.054438555759345995 %
i= LTC    -0.098695
ALGO   -0.059844
VET    -0.122531
XRP     0.011321
XLM    -0.002444
Name: 153, dtype: float64
熊式-----------------------------------
執行第 160
           160
LTC  -0.077205
ZIL  -0.031120
VET  -0.030830
BAT  -0.028616
QTUM -0.021289
ALGO -0.014329
XRP  -0.009839
XLM  -0.005576
ADA  -0.005402
ETH   0.003988
BNB   0.009987
IOTA  0.014540
TRX   0.020209
NEO   0.020304
ICX   0.025021
ATOM  0.040736
LINK  0.042857
BCH   0.099535
ZRX   0.119276
ZEC   0.187597
g================================================================        LTC      ZIL       VET     BAT   QTUM
0    56.59  0.00879  0.004916  0.1972  2.642
1    54.82  0.00762  0.004628  0.1682  2.347
2    56.60  0.00749  0.004580  0.1870  2.376
3    55.28  0.00732  0.004493  0.1788  2.291
4    55.88  0.00773  0.004454  0.1764  2.455
..     ...      ...       ...     ...    ...
720    NaN      NaN       NaN     NaN    NaN
721    NaN      NaN       NaN     NaN    NaN
722    NaN      NaN       NaN     NaN    NaN
723    NaN      NaN       NaN     NaN    NaN
724    NaN      NaN       NaN     NaN    NaN

[725 rows x 5 columns]
LTC    -0.050992
ZIL    -0.017316
VET    -0.083789
BAT     0.223955
QTUM    0.010082
Name: 154, dtype: float64
報酬 0.016388030272647902 %
i= LTC    -0.050992
ZIL    -0.017316
VET    -0.083789
BAT     0.223955
QTUM    0.010082
Name: 154, dtype: float64
熊式-----------------------------------
執行第 161
           161
LTC  -0.065057
ALGO  0.007881
ZIL   0.081023
LINK  0.086758
VET   0.090942
XLM   0.109595
ZRX   0.118947
XRP   0.132707
ATOM  0.136808
QTUM  0.140820
BNB   0.145905
ADA   0.148169
IOTA  0.164914
BAT   0.175728
ETH   0.181469
ICX   0.190436
NEO   0.191046
TRX   0.196721
ZEC   0.424223
BCH   0.458512
g================================================================        LTC   ALGO      ZIL  LINK       VET
0    56.59  0.809  0.00879  2.42  0.004916
1    54.82  0.717  0.00762  2.28  0.004628
2    56.60  0.710  0.00749  2.42  0.004580
3    55.28  0.677  0.00732  2.30  0.004493
4    55.88  0.683  0.00773  2.40  0.004454
..     ...    ...      ...   ...       ...
720    NaN    NaN      NaN   NaN       NaN
721    NaN    NaN      NaN   NaN       NaN
722    NaN    NaN      NaN   NaN       NaN
723    NaN    NaN      NaN   NaN       NaN
724    NaN    NaN      NaN   NaN       NaN

[725 rows x 5 columns]
LTC    -0.000997
ALGO   -0.107262
ZIL    -0.045752
LINK   -0.059459
VET    -0.071285
Name: 155, dtype: float64
報酬 -0.05695112799896516 %
i= LTC    -0.000997
ALGO   -0.107262
ZIL    -0.045752
LINK   -0.059459
VET    -0.071285
Name: 155, dtype: float64
熊式-----------------------------------
執行第 162
           162
LTC  -0.077626
ATOM  0.078210
LINK  0.095890
ALGO  0.112961
VET   0.127536
ZIL   0.139434
XRP   0.147346
XLM   0.161509
ADA   0.183730
BAT   0.188547
ZRX   0.196793
QTUM  0.208078
ETH   0.208566
NEO   0.217002
ICX   0.220223
BNB   0.229109
TRX   0.236598
IOTA  0.318644
BCH   0.428343
ZEC   0.784301
g================================================================        LTC   ATOM  LINK   ALGO       VET
0    56.59  3.258  2.42  0.809  0.004916
1    54.82  2.857  2.28  0.717  0.004628
2    56.60  2.898  2.42  0.710  0.004580
3    55.28  2.884  2.30  0.677  0.004493
4    55.88  2.910  2.40  0.683  0.004454
..     ...    ...   ...    ...       ...
720    NaN    NaN   NaN    NaN       NaN
721    NaN    NaN   NaN    NaN       NaN
722    NaN    NaN   NaN    NaN       NaN
723    NaN    NaN   NaN    NaN       NaN
724    NaN    NaN   NaN    NaN       NaN

[725 rows x 5 columns]
LTC     0.046519
ATOM   -0.059698
LINK   -0.042553
ALGO   -0.010022
VET    -0.061253
Name: 156, dtype: float64
報酬 -0.025401489421525935 %
i= LTC     0.046519
ATOM   -0.059698
LINK   -0.042553
ALGO   -0.010022
VET    -0.061253
Name: 156, dtype: float64
熊式-----------------------------------
執行第 163
           163
LTC  -0.061872
ALGO  0.068614
XRP   0.076623
VET   0.078827
ZIL   0.095949
QTUM  0.116561
LINK  0.116592
XLM   0.118284
ADA   0.129268
BNB   0.132050
ETH   0.135699
NEO   0.141586
BAT   0.160448
TRX   0.175630
ATOM  0.190632
IOTA  0.198212
BCH   0.202649
ZRX   0.222606
ICX   0.223906
ZEC   0.509512
g================================================================        LTC   ALGO      XRP       VET      ZIL
0    56.59  0.809  0.29787  0.004916  0.00879
1    54.82  0.717  0.26338  0.004628  0.00762
2    56.60  0.710  0.26408  0.004580  0.00749
3    55.28  0.677  0.26055  0.004493  0.00732
4    55.88  0.683  0.26543  0.004454  0.00773
..     ...    ...      ...       ...      ...
720    NaN    NaN      NaN       NaN      NaN
721    NaN    NaN      NaN       NaN      NaN
722    NaN    NaN      NaN       NaN      NaN
723    NaN    NaN      NaN       NaN      NaN
724    NaN    NaN      NaN       NaN      NaN

[725 rows x 5 columns]
LTC     0.058274
ALGO    0.010743
XRP    -0.000103
VET    -0.006354
ZIL    -0.017058
Name: 157, dtype: float64
報酬 0.009100600687702664 %
i= LTC     0.058274
ALGO    0.010743
XRP    -0.000103
VET    -0.006354
ZIL    -0.017058
Name: 157, dtype: float64
熊式-----------------------------------
執行第 164
           164
LTC  -0.159663
XRP   0.131520
VET   0.154958
ALGO  0.157244
ZIL   0.169892
ATOM  0.174719
LINK  0.184211
ETH   0.195393
QTUM  0.201149
TRX   0.203970
BNB   0.210174
BAT   0.211029
NEO   0.220243
ADA   0.222222
ZRX   0.234012
IOTA  0.242440
XLM   0.259681
ICX   0.271215
BCH   0.410341
ZEC   0.767049
g================================================================        LTC      XRP       VET   ALGO      ZIL
0    56.59  0.29787  0.004916  0.809  0.00879
1    54.82  0.26338  0.004628  0.717  0.00762
2    56.60  0.26408  0.004580  0.710  0.00749
3    55.28  0.26055  0.004493  0.677  0.00732
4    55.88  0.26543  0.004454  0.683  0.00773
..     ...      ...       ...    ...      ...
720    NaN      NaN       NaN    NaN      NaN
721    NaN      NaN       NaN    NaN      NaN
722    NaN      NaN       NaN    NaN      NaN
723    NaN      NaN       NaN    NaN      NaN
724    NaN      NaN       NaN    NaN      NaN

[725 rows x 5 columns]
LTC     0.008193
XRP    -0.010477
VET    -0.019203
ALGO   -0.009927
ZIL    -0.016985
Name: 158, dtype: float64
報酬 -0.009679751133542979 %
i= LTC     0.008193
XRP    -0.010477
VET    -0.019203
ALGO   -0.009927
ZIL    -0.016985
Name: 158, dtype: float64
熊式-----------------------------------
執行第 165
           165
LTC  -0.094588
ATOM  0.088408
ZIL   0.104603
ZRX   0.125115
VET   0.129231
XRP   0.130548
ALGO  0.132778
NEO   0.156490
QTUM  0.160114
BNB   0.161122
BAT   0.172976
TRX   0.174202
ADA   0.184745
ETH   0.188874
LINK  0.236607
BCH   0.252284
XLM   0.253619
ICX   0.262551
IOTA  0.283325
ZEC   0.439752
g================================================================        LTC   ATOM      ZIL     ZRX       VET
0    56.59  3.258  0.00879  0.1814  0.004916
1    54.82  2.857  0.00762  0.1624  0.004628
2    56.60  2.898  0.00749  0.1736  0.004580
3    55.28  2.884  0.00732  0.1751  0.004493
4    55.88  2.910  0.00773  0.1711  0.004454
..     ...    ...      ...     ...       ...
720    NaN    NaN      NaN     NaN       NaN
721    NaN    NaN      NaN     NaN       NaN
722    NaN    NaN      NaN     NaN       NaN
723    NaN    NaN      NaN     NaN       NaN
724    NaN    NaN      NaN     NaN       NaN

[725 rows x 5 columns]
LTC     0.059757
ATOM   -0.013682
ZIL     0.072368
ZRX     0.039830
VET     0.056959
Name: 159, dtype: float64
報酬 0.043046347332946724 %
i= LTC     0.059757
ATOM   -0.013682
ZIL     0.072368
ZRX     0.039830
VET     0.056959
Name: 159, dtype: float64
熊式-----------------------------------
執行第 166
           166
LTC  -0.126258
ALGO  0.057269
ATOM  0.064843
VET   0.084150
ZIL   0.094218
ZRX   0.099905
XRP   0.115548
NEO   0.123100
QTUM  0.134627
TRX   0.137978
ADA   0.140413
BNB   0.144364
BAT   0.145688
ETH   0.162567
ICX   0.189585
LINK  0.196347
XLM   0.247144
BCH   0.271498
IOTA  0.308386
ZEC   0.347520
g================================================================        LTC   ALGO   ATOM       VET      ZIL
0    56.59  0.809  3.258  0.004916  0.00879
1    54.82  0.717  2.857  0.004628  0.00762
2    56.60  0.710  2.898  0.004580  0.00749
3    55.28  0.677  2.884  0.004493  0.00732
4    55.88  0.683  2.910  0.004454  0.00773
..     ...    ...    ...       ...      ...
720    NaN    NaN    NaN       NaN      NaN
721    NaN    NaN    NaN       NaN      NaN
722    NaN    NaN    NaN       NaN      NaN
723    NaN    NaN    NaN       NaN      NaN
724    NaN    NaN    NaN       NaN      NaN

[725 rows x 5 columns]
LTC     0.031636
ALGO    0.062269
ATOM   -0.035959
VET     0.064288
ZIL     0.078300
Name: 160, dtype: float64
報酬 0.0401069366896315 %
i= LTC     0.031636
ALGO    0.062269
ATOM   -0.035959
VET     0.064288
ZIL     0.078300
Name: 160, dtype: float64

熊式-----------------------------------
執行第 167
           167
LTC  -0.194681
VET  -0.028734
ZRX  -0.026891
BCH  -0.018802
NEO  -0.012352
TRX  -0.010125
XRP  -0.008718
ATOM -0.006833
QTUM  0.001563
ETH   0.003972
ZIL   0.005917
ALGO  0.029540
BAT   0.039701
BNB   0.040240
ADA   0.049652
ICX   0.083931
LINK  0.130252
XLM   0.185430
IOTA  0.198575
ZEC   0.216917
g================================================================        LTC       VET     ZRX     BCH     NEO
0    56.59  0.004916  0.1814  334.09  10.494
1    54.82  0.004628  0.1624  315.09   9.427
2    56.60  0.004580  0.1736  316.10   9.897
3    55.28  0.004493  0.1751  339.01   9.818
4    55.88  0.004454  0.1711  330.12   9.663
..     ...       ...     ...     ...     ...
720    NaN       NaN     NaN     NaN     NaN
721    NaN       NaN     NaN     NaN     NaN
722    NaN       NaN     NaN     NaN     NaN
723    NaN       NaN     NaN     NaN     NaN
724    NaN       NaN     NaN     NaN     NaN

[725 rows x 5 columns]
LTC    0.067219
VET    0.024076
ZRX    0.165479
BCH    0.173694
NEO    0.068174
Name: 161, dtype: float64
報酬 0.09972863222990758 %
i= LTC    0.067219
VET    0.024076
ZRX    0.165479
BCH    0.173694
NEO    0.068174
Name: 161, dtype: float64
熊式-----------------------------------
執行第 168
           168
LTC  -0.110502
ZEC  -0.031812
ZIL  -0.021033
ZRX  -0.019488
NEO  -0.017332
QTUM -0.012665
VET  -0.006497
TRX   0.001156
BAT   0.002273
ALGO  0.003639
BCH   0.010413
ATOM  0.014201
XRP   0.015320
ETH   0.017840
BNB   0.026062
IOTA  0.072408
ADA   0.076905
ICX   0.102528
LINK  0.112500
XLM   0.145985
g================================================================        LTC    ZEC      ZIL     ZRX     NEO
0    56.59  55.45  0.00879  0.1814  10.494
1    54.82  50.56  0.00762  0.1624   9.427
2    56.60  50.57  0.00749  0.1736   9.897
3    55.28  48.85  0.00732  0.1751   9.818
4    55.88  50.01  0.00773  0.1711   9.663
..     ...    ...      ...     ...     ...
720    NaN    NaN      NaN     NaN     NaN
721    NaN    NaN      NaN     NaN     NaN
722    NaN    NaN      NaN     NaN     NaN
723    NaN    NaN      NaN     NaN     NaN
724    NaN    NaN      NaN     NaN     NaN

[725 rows x 5 columns]
LTC    0.031496
ZEC    0.141007
ZIL    0.047945
ZRX    0.174658
NEO    0.109312
Name: 162, dtype: float64
報酬 0.10088353675673893 %
i= LTC    0.031496
ZEC    0.141007
ZIL    0.047945
ZRX    0.174658
NEO    0.109312
Name: 162, dtype: float64
熊式-----------------------------------
執行第 169
           169
LTC  -0.092098
ATOM -0.083989
ZRX  -0.023012
VET  -0.003738
NEO  -0.003632
BAT   0.004134
TRX   0.009265
ZIL   0.009728
ETH   0.021332
ALGO  0.023198
ZEC   0.028555
QTUM  0.031008
XRP   0.035781
BNB   0.045135
LINK  0.064257
BCH   0.067346
ICX   0.075653
IOTA  0.090829
ADA   0.097912
XLM   0.142272
g================================================================        LTC   ATOM     ZRX       VET     NEO
0    56.59  3.258  0.1814  0.004916  10.494
1    54.82  2.857  0.1624  0.004628   9.427
2    56.60  2.898  0.1736  0.004580   9.897
3    55.28  2.884  0.1751  0.004493   9.818
4    55.88  2.910  0.1711  0.004454   9.663
..     ...    ...     ...       ...     ...
720    NaN    NaN     NaN       NaN     NaN
721    NaN    NaN     NaN       NaN     NaN
722    NaN    NaN     NaN       NaN     NaN
723    NaN    NaN     NaN       NaN     NaN
724    NaN    NaN     NaN       NaN     NaN

[725 rows x 5 columns]
LTC    -0.083536
ATOM    0.007789
ZRX     0.112576
VET     0.025762
NEO     0.113639
Name: 163, dtype: float64
報酬 0.03524573618226625 %
i= LTC    -0.083536
ATOM    0.007789
ZRX     0.112576
VET     0.025762
NEO     0.113639
Name: 163, dtype: float64
熊式-----------------------------------
執行第 170
           170
ZEC  -0.195719
VET  -0.123221
BCH  -0.117342
ATOM -0.109004
ZRX  -0.103651
NEO  -0.103620
ALGO -0.100763
QTUM -0.095694
BAT  -0.091506
ZIL  -0.088235
LINK -0.085185
TRX  -0.074474
BNB  -0.055863
XRP  -0.055839
ETH  -0.043420
XLM  -0.041098
ADA  -0.040009
ICX  -0.021597
LTC  -0.009896
IOTA -0.005875
g================================================================        ZEC       VET     BCH   ATOM     ZRX
0    55.45  0.004916  334.09  3.258  0.1814
1    50.56  0.004628  315.09  2.857  0.1624
2    50.57  0.004580  316.10  2.898  0.1736
3    48.85  0.004493  339.01  2.884  0.1751
4    50.01  0.004454  330.12  2.910  0.1711
..     ...       ...     ...    ...     ...
720    NaN       NaN     NaN    NaN     NaN
721    NaN       NaN     NaN    NaN     NaN
722    NaN       NaN     NaN    NaN     NaN
723    NaN       NaN     NaN    NaN     NaN
724    NaN       NaN     NaN    NaN     NaN

[725 rows x 5 columns]
ZEC     0.166834
VET    -0.016519
BCH     0.162511
ATOM    0.003294
ZRX     0.107296
Name: 164, dtype: float64
報酬 0.08468331412690569 %
i= ZEC     0.166834
VET    -0.016519
BCH     0.162511
ATOM    0.003294
ZRX     0.107296
Name: 164, dtype: float64
熊式-----------------------------------
執行第 171
           171
NEO  -0.114938
VET  -0.105626
ALGO -0.104062
LINK -0.097473
XRP  -0.087467
ZRX  -0.073320
TRX  -0.071914
QTUM -0.071709
XLM  -0.070743
BAT  -0.069027
ETH  -0.066774
ZIL  -0.064394
BCH  -0.058311
ZEC  -0.045366
BNB  -0.043258
LTC  -0.041552
IOTA -0.034623
ATOM -0.030460
ICX  -0.017601
ADA   0.001337
g================================================================         NEO       VET   ALGO  LINK      XRP
0    10.494  0.004916  0.809  2.42  0.29787
1     9.427  0.004628  0.717  2.28  0.26338
2     9.897  0.004580  0.710  2.42  0.26408
3     9.818  0.004493  0.677  2.30  0.26055
4     9.663  0.004454  0.683  2.40  0.26543
..      ...       ...    ...   ...      ...
720     NaN       NaN    NaN   NaN      NaN
721     NaN       NaN    NaN   NaN      NaN
722     NaN       NaN    NaN   NaN      NaN
723     NaN       NaN    NaN   NaN      NaN
724     NaN       NaN    NaN   NaN      NaN

[725 rows x 5 columns]
NEO     0.138470
VET     0.010979
ALGO   -0.005231
LINK    0.244444
XRP     0.107113
Name: 165, dtype: float64
報酬 0.09915518346307595 %
i= NEO     0.138470
VET     0.010979
ALGO   -0.005231
LINK    0.244444
XRP     0.107113
Name: 165, dtype: float64
熊式-----------------------------------
執行第 172
           172
BCH  -0.086276
NEO  -0.078444
XRP  -0.069223
LINK -0.068702
XLM  -0.066112
ZEC  -0.055609
IOTA -0.049087
BAT  -0.046751
VET  -0.041624
ETH  -0.038060
QTUM -0.034197
ZIL  -0.033268
TRX  -0.031813
ZRX  -0.030277
ATOM -0.027901
ALGO -0.025000
BNB  -0.023041
LTC  -0.017142
ADA   0.027387
ICX   0.060192
g================================================================         BCH     NEO      XRP  LINK      XLM
0    334.09  10.494  0.29787  2.42  0.07442
1    315.09   9.427  0.26338  2.28  0.06922
2    316.10   9.897  0.26408  2.42  0.07019
3    339.01   9.818  0.26055  2.30  0.06851
4    330.12   9.663  0.26543  2.40  0.06770
..      ...     ...      ...   ...      ...
720     NaN     NaN      NaN   NaN      NaN
721     NaN     NaN      NaN   NaN      NaN
722     NaN     NaN      NaN   NaN      NaN
723     NaN     NaN      NaN   NaN      NaN
724     NaN     NaN      NaN   NaN      NaN

[725 rows x 5 columns]
BCH     0.093277
NEO     0.024905
XRP    -0.052966
LINK    0.128866
XLM    -0.045968
Name: 166, dtype: float64
報酬 0.029622669281098225 %
i= BCH     0.093277
NEO     0.024905
XRP    -0.052966
LINK    0.128866
XLM    -0.045968
Name: 166, dtype: float64
熊式-----------------------------------
執行第 173
           173
XLM  -0.068156
BAT  -0.048967
LINK -0.044610
NEO  -0.028253
IOTA -0.026159
VET  -0.014448
XRP  -0.008022
ATOM -0.005770
ZRX  -0.004750
ALGO  0.001688
ZEC   0.002055
ZIL   0.003922
ETH   0.006115
QTUM  0.006240
BNB   0.009238
TRX   0.013237
BCH   0.013571
ADA   0.020795
LTC   0.037149
ICX   0.150232
g================================================================          XLM     BAT  LINK     NEO    IOTA
0    0.07442  0.1972  2.42  10.494  0.2564
1    0.06922  0.1682  2.28   9.427  0.2322
2    0.07019  0.1870  2.42   9.897  0.2428
3    0.06851  0.1788  2.30   9.818  0.2413
4    0.06770  0.1764  2.40   9.663  0.2422
..       ...     ...   ...     ...     ...
720      NaN     NaN   NaN     NaN     NaN
721      NaN     NaN   NaN     NaN     NaN
722      NaN     NaN   NaN     NaN     NaN
723      NaN     NaN   NaN     NaN     NaN
724      NaN     NaN   NaN     NaN     NaN

[725 rows x 5 columns]
XLM     0.091491
BAT     0.113944
LINK    0.133333
NEO     0.148148
IOTA    0.133549
Name: 167, dtype: float64
報酬 0.12409302878089198 %
i= XLM     0.091491
BAT     0.113944
LINK    0.133333
NEO     0.148148
IOTA    0.133549
Name: 167, dtype: float64
熊式-----------------------------------
執行第 174
           174
XLM  -0.049204
ZRX  -0.040994
LTC  -0.039706
VET  -0.036385
ALGO -0.033038
ATOM -0.027359
XRP  -0.027101
BNB  -0.024296
LINK -0.022472
NEO  -0.012827
TRX  -0.010970
ZIL  -0.001953
ETH   0.003718
IOTA  0.005194
BAT   0.024490
QTUM  0.024628
ZEC   0.036050
ADA   0.038854
BCH   0.055837
ICX   0.129936
g================================================================          XLM     ZRX    LTC       VET   ALGO
0    0.07442  0.1814  56.59  0.004916  0.809
1    0.06922  0.1624  54.82  0.004628  0.717
2    0.07019  0.1736  56.60  0.004580  0.710
3    0.06851  0.1751  55.28  0.004493  0.677
4    0.06770  0.1711  55.88  0.004454  0.683
..       ...     ...    ...       ...    ...
720      NaN     NaN    NaN       NaN    NaN
721      NaN     NaN    NaN       NaN    NaN
722      NaN     NaN    NaN       NaN    NaN
723      NaN     NaN    NaN       NaN    NaN
724      NaN     NaN    NaN       NaN    NaN

[725 rows x 5 columns]
XLM     0.150535
ZRX     0.157969
LTC    -0.111261
VET     0.094040
ALGO    0.082750
Name: 168, dtype: float64
報酬 0.07480672414582472 %
i= XLM     0.150535
ZRX     0.157969
LTC    -0.111261
VET     0.094040
ALGO    0.082750
Name: 168, dtype: float64
牛式===============================
執行第 175
           175
LTC  -0.063951
ZRX  -0.042975
ALGO -0.014170
ATOM -0.012025
VET  -0.009381
XLM  -0.009292
LINK  0.000000
XRP   0.008047
NEO   0.009247
BNB   0.011217
BAT   0.015554
ZIL   0.023121
QTUM  0.030075
ETH   0.044689
TRX   0.069994
BCH   0.085428
ZEC   0.087306
IOTA  0.148833
ADA   0.158033
ICX   0.187980
g================================================================         BCH     ZEC    IOTA     ADA     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  118.51  0.8896  1.4039  0.9279
721  490.60  109.38  0.8165  1.3327  1.0350
722  504.08  110.99  0.8180  1.3497  0.9786
723  497.02  108.15  0.7913  1.3356  0.9198
724  498.00  110.82  0.8404  1.3478  0.9519

[725 rows x 5 columns]
BCH     0.171123
ZEC     0.244758
IOTA    0.283242
ADA     0.235703
ICX     0.412709
Name: 169, dtype: float64
報酬 0.2695068686770993 %
i= BCH     0.171123
ZEC     0.244758
IOTA    0.283242
ADA     0.235703
ICX     0.412709
Name: 169, dtype: float64
牛式===============================
執行第 176
           176
LTC  -0.019856
ATOM -0.013892
ZRX  -0.012265
ALGO  0.021222
VET   0.022472
XRP   0.042585
XLM   0.043545
BNB   0.049209
BAT   0.051566
NEO   0.054504
ETH   0.067871
QTUM  0.093122
ZIL   0.112903
LINK  0.125506
TRX   0.146192
BCH   0.171123
ADA   0.235703
ZEC   0.244758
IOTA  0.283242
ICX   0.412709
g================================================================         BCH     ADA     ZEC    IOTA     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  1.4039  118.51  0.8896  0.9279
721  490.60  1.3327  109.38  0.8165  1.0350
722  504.08  1.3497  110.99  0.8180  0.9786
723  497.02  1.3356  108.15  0.7913  0.9198
724  498.00  1.3478  110.82  0.8404  0.9519

[725 rows x 5 columns]
BCH     0.230559
ADA     0.249833
ZEC     0.360713
IOTA    0.240506
ICX     0.579297
Name: 170, dtype: float64
報酬 0.3321816435649575 %
i= BCH     0.230559
ADA     0.249833
ZEC     0.360713
IOTA    0.240506
ICX     0.579297
Name: 170, dtype: float64
牛式===============================
執行第 177
           177
ATOM -0.017380
LTC  -0.003146
VET   0.018459
ZRX   0.024615
ALGO  0.043178
BAT   0.076553
BNB   0.089841
XRP   0.096166
XLM   0.099405
NEO   0.116449
ZIL   0.121457
ETH   0.136643
QTUM  0.150265
LINK  0.164000
TRX   0.188530
BCH   0.230559
IOTA  0.240506
ADA   0.249833
ZEC   0.360713
ICX   0.579297
g================================================================         BCH    IOTA     ADA     ZEC     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  0.8896  1.4039  118.51  0.9279
721  490.60  0.8165  1.3327  109.38  1.0350
722  504.08  0.8180  1.3497  110.99  0.9786
723  497.02  0.7913  1.3356  108.15  0.9198
724  498.00  0.8404  1.3478  110.82  0.9519

[725 rows x 5 columns]
BCH     0.208672
IOTA    0.255119
ADA     0.248261
ZEC     0.363972
ICX     0.666452
Name: 171, dtype: float64
報酬 0.34849529251352174 %
i= BCH     0.208672
IOTA    0.255119
ADA     0.248261
ZEC     0.363972
ICX     0.666452
Name: 171, dtype: float64
牛式===============================
執行第 178
           178
LTC  -0.090203
ATOM  0.001595
ZRX   0.018733
VET   0.026344
ALGO  0.056410
BNB   0.074882
BAT   0.076508
XLM   0.079886
XRP   0.091096
NEO   0.106570
ETH   0.121565
QTUM  0.140021
TRX   0.156851
LINK  0.159836
ZIL   0.200405
BCH   0.208672
ADA   0.248261
IOTA  0.255119
ZEC   0.363972
ICX   0.666452
g================================================================         BCH     ADA    IOTA     ZEC     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  1.4039  0.8896  118.51  0.9279
721  490.60  1.3327  0.8165  109.38  1.0350
722  504.08  1.3497  0.8180  110.99  0.9786
723  497.02  1.3356  0.7913  108.15  0.9198
724  498.00  1.3478  0.8404  110.82  0.9519

[725 rows x 5 columns]
BCH     0.091768
ADA     0.255429
IOTA    0.243793
ZEC     0.231027
ICX     0.581703
Name: 172, dtype: float64
報酬 0.28074417685445996 %
i= BCH     0.091768
ADA     0.255429
IOTA    0.243793
ZEC     0.231027
ICX     0.581703
Name: 172, dtype: float64
牛式===============================
執行第 179
           179
LTC  -0.157601
ATOM -0.020536
ZRX   0.006941
ALGO  0.042544
XRP   0.043982
BNB   0.045195
VET   0.046248
NEO   0.057593
BAT   0.058573
XLM   0.065605
BCH   0.091768
ETH   0.094500
LINK  0.105058
TRX   0.132423
QTUM  0.133333
ZIL   0.173828
ZEC   0.231027
IOTA  0.243793
ADA   0.255429
ICX   0.581703
g================================================================          ZIL     ZEC    IOTA     ADA     ICX
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08133  118.51  0.8896  1.4039  0.9279
721  0.07509  109.38  0.8165  1.3327  1.0350
722  0.07496  110.99  0.8180  1.3497  0.9786
723  0.07299  108.15  0.7913  1.3356  0.9198
724  0.07377  110.82  0.8404  1.3478  0.9519

[725 rows x 5 columns]
ZIL     0.213307
ZEC     0.204603
IOTA    0.224165
ADA     0.164647
ICX     0.786359
Name: 173, dtype: float64
報酬 0.31861621963579784 %
i= ZIL     0.213307
ZEC     0.204603
IOTA    0.224165
ADA     0.164647
ICX     0.786359
Name: 173, dtype: float64
牛式===============================
執行第 180
           180
LTC  -0.124318
ATOM -0.024142
BAT  -0.009739
ZRX   0.034111
BCH   0.039567
BNB   0.042445
ALGO  0.052917
XLM   0.062469
LINK  0.080460
VET   0.085958
NEO   0.085995
XRP   0.086124
ETH   0.107126
TRX   0.114419
QTUM  0.132699
ADA   0.164647
ZEC   0.204603
ZIL   0.213307
IOTA  0.224165
ICX   0.786359
g================================================================         ADA     ZEC      ZIL    IOTA     ICX
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  1.4039  118.51  0.08133  0.8896  0.9279
721  1.3327  109.38  0.07509  0.8165  1.0350
722  1.3497  110.99  0.07496  0.8180  0.9786
723  1.3356  108.15  0.07299  0.7913  0.9198
724  1.3478  110.82  0.07377  0.8404  0.9519

[725 rows x 5 columns]
ADA     0.075123
ZEC     0.154429
ZIL     0.175141
IOTA    0.175420
ICX     0.994080
Name: 174, dtype: float64
報酬 0.31483847018786004 %
i= ADA     0.075123
ZEC     0.154429
ZIL     0.175141
IOTA    0.175420
ICX     0.994080
Name: 174, dtype: float64
牛式===============================
執行第 181
           181
LTC  -0.109756
ATOM -0.073245
BCH   0.016084
ZRX   0.018998
BNB   0.023849
TRX   0.028954
NEO   0.046604
LINK  0.049057
XLM   0.058088
BAT   0.059459
XRP   0.064360
ADA   0.075123
ALGO  0.080082
ETH   0.081169
VET   0.085916
QTUM  0.112895
ZEC   0.154429
ZIL   0.175141
IOTA  0.175420
ICX   0.994080
g================================================================       QTUM     ZEC      ZIL    IOTA     ICX
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  7.079  118.51  0.08133  0.8896  0.9279
721  6.504  109.38  0.07509  0.8165  1.0350
722  6.776  110.99  0.07496  0.8180  0.9786
723  6.639  108.15  0.07299  0.7913  0.9198
724  6.694  110.82  0.07377  0.8404  0.9519

[725 rows x 5 columns]
QTUM    0.114714
ZEC     0.041302
ZIL     0.244565
IOTA    0.091447
ICX     1.434659
Name: 175, dtype: float64
報酬 0.38533766718179574 %
i= QTUM    0.114714
ZEC     0.041302
ZIL     0.244565
IOTA    0.091447
ICX     1.434659
Name: 175, dtype: float64
牛式===============================
執行第 182
           182
LTC  -0.103603
ATOM -0.041127
LINK -0.014388
BCH   0.000736
BNB   0.015075
TRX   0.031618
ZEC   0.041302
ADA   0.048717
ETH   0.086909
NEO   0.087217
XLM   0.089699
IOTA  0.091447
QTUM  0.114714
BAT   0.115490
ZRX   0.125499
XRP   0.135275
VET   0.139369
ALGO  0.166667
ZIL   0.244565
ICX   1.434659
g================================================================         XRP      VET    ALGO      ZIL     ICX
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.6521  0.08348  0.9062  0.08133  0.9279
721  0.6236  0.07614  0.8683  0.07509  1.0350
722  0.6372  0.07704  0.9059  0.07496  0.9786
723  0.6251  0.07591  0.8918  0.07299  0.9198
724  0.6362  0.07768  0.8952  0.07377  0.9519

[725 rows x 5 columns]
XRP     0.140277
VET     0.138835
ALGO    0.139487
ZIL     0.238267
ICX     0.835294
Name: 176, dtype: float64
報酬 0.29843196747370687 %
i= XRP     0.140277
VET     0.138835
ALGO    0.139487
ZIL     0.238267
ICX     0.835294
Name: 176, dtype: float64
牛式===============================
執行第 183
           183
LTC  -0.081630
LINK -0.024055
ATOM -0.018141
BNB   0.037716
ADA   0.056070
TRX   0.065708
ZEC   0.071504
NEO   0.088539
XLM   0.099650
ZRX   0.102531
ETH   0.103112
IOTA  0.110544
BAT   0.124776
QTUM  0.125115
BCH   0.134747
VET   0.138835
ALGO  0.139487
XRP   0.140277
ZIL   0.238267
ICX   0.835294
g================================================================          VET    ALGO     XRP      ZIL     ICX
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.08348  0.9062  0.6521  0.08133  0.9279
721  0.07614  0.8683  0.6236  0.07509  1.0350
722  0.07704  0.9059  0.6372  0.07496  0.9786
723  0.07591  0.8918  0.6251  0.07299  0.9198
724  0.07768  0.8952  0.6362  0.07377  0.9519

[725 rows x 5 columns]
VET     0.179327
ALGO    0.165049
XRP     0.184062
ZIL     0.256324
ICX     0.772358
Name: 177, dtype: float64
報酬 0.3114238564214236 %
i= VET     0.179327
ALGO    0.165049
XRP     0.184062
ZIL     0.256324
ICX     0.772358
Name: 177, dtype: float64
牛式===============================
執行第 184
           184
LINK  0.021201
LTC   0.032949
ATOM  0.042756
ZEC   0.055054
ADA   0.116063
IOTA  0.124745
NEO   0.131145
BNB   0.133845
ALGO  0.165049
XLM   0.174703
VET   0.179327
XRP   0.184062
ETH   0.184500
BCH   0.188915
QTUM  0.197176
BAT   0.206378
TRX   0.215970
ZRX   0.218476
ZIL   0.256324
ICX   0.772358
g================================================================         BAT      TRX     ZRX      ZIL     ICX
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.6135  0.06432  0.7889  0.08133  0.9279
721  0.5691  0.06111  0.8190  0.07509  1.0350
722  0.5695  0.06219  0.8384  0.07496  0.9786
723  0.5575  0.06139  0.7890  0.07299  0.9198
724  0.5623  0.06184  0.7950  0.07377  0.9519

[725 rows x 5 columns]
BAT    0.176261
TRX    0.156266
ZRX    0.196467
ZIL    0.372712
ICX    0.500182
Name: 178, dtype: float64
報酬 0.2803776111511524 %
i= BAT    0.176261
TRX    0.156266
ZRX    0.196467
ZIL    0.372712
ICX    0.500182
Name: 178, dtype: float64
牛式===============================
執行第 185
           185
ZEC   0.036504
IOTA  0.050065
LTC   0.055276
ADA   0.067582
ATOM  0.099590
NEO   0.119944
VET   0.137615
XLM   0.155923
TRX   0.156266
BCH   0.157109
XRP   0.158368
LINK  0.161972
QTUM  0.173735
BAT   0.176261
ZRX   0.196467
BNB   0.207444
ETH   0.217758
ALGO  0.262222
ZIL   0.372712
ICX   0.500182
g================================================================         BNB      ETH    ALGO      ZIL     ICX
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  327.67  2316.15  0.9062  0.08133  0.9279
721  310.59  2121.52  0.8683  0.07509  1.0350
722  316.72  2146.27  0.9059  0.07496  0.9786
723  316.09  2111.19  0.8918  0.07299  0.9198
724  321.87  2138.86  0.8952  0.07377  0.9519

[725 rows x 5 columns]
BNB     0.182953
ETH     0.185236
ALGO    0.216462
ZIL     0.211290
ICX     0.278321
Name: 179, dtype: float64
報酬 0.2148526808693926 %
i= BNB     0.182953
ETH     0.185236
ALGO    0.216462
ZIL     0.211290
ICX     0.278321
Name: 179, dtype: float64
牛式===============================
執行第 186
           186
IOTA -0.002922
LTC   0.016363
ATOM  0.050613
NEO   0.053344
ZEC   0.053708
VET   0.068579
ADA   0.077682
XRP   0.107375
XLM   0.117591
ZRX   0.139875
TRX   0.140911
BAT   0.143943
QTUM  0.149867
BCH   0.178500
BNB   0.182953
ETH   0.185236
ZIL   0.211290
LINK  0.212766
ALGO  0.216462
ICX   0.278321
g================================================================          ETH      ZIL   LINK    ALGO     ICX
0        NaN      NaN    NaN     NaN     NaN
1        NaN      NaN    NaN     NaN     NaN
2        NaN      NaN    NaN     NaN     NaN
3        NaN      NaN    NaN     NaN     NaN
4        NaN      NaN    NaN     NaN     NaN
..       ...      ...    ...     ...     ...
720  2316.15  0.08133  19.79  0.9062  0.9279
721  2121.52  0.07509  18.44  0.8683  1.0350
722  2146.27  0.07496  18.66  0.9059  0.9786
723  2111.19  0.07299  18.20  0.8918  0.9198
724  2138.86  0.07377  18.38  0.8952  0.9519

[725 rows x 5 columns]
ETH     0.204468
ZIL     0.270833
LINK    0.255396
ALGO    0.297338
ICX     0.182996
Name: 180, dtype: float64
報酬 0.24220619935313142 %
i= ETH     0.204468
ZIL     0.270833
LINK    0.255396
ALGO    0.297338
ICX     0.182996
Name: 180, dtype: float64
牛式===============================
執行第 187
           187
IOTA -0.039321
LTC   0.010430
VET   0.081814
ZEC   0.085113
ADA   0.086728
XRP   0.108764
ATOM  0.114212
XLM   0.139036
TRX   0.149557
BAT   0.161139
BCH   0.168928
QTUM  0.179711
ICX   0.182996
NEO   0.196044
ETH   0.204468
LINK  0.255396
ZRX   0.257627
ZIL   0.270833
ALGO  0.297338
BNB   0.319068
g================================================================       LINK     ZRX      ZIL    ALGO     BNB
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  19.79  0.7889  0.08133  0.9062  327.67
721  18.44  0.8190  0.07509  0.8683  310.59
722  18.66  0.8384  0.07496  0.9059  316.72
723  18.20  0.7890  0.07299  0.8918  316.09
724  18.38  0.7950  0.07377  0.8952  321.87

[725 rows x 5 columns]
LINK    0.237226
ZRX     0.117021
ZIL     0.100437
ALGO    0.278589
BNB     0.380638
Name: 181, dtype: float64
報酬 0.2227823080359705 %
i= LINK    0.237226
ZRX     0.117021
ZIL     0.100437
ALGO    0.278589
BNB     0.380638
Name: 181, dtype: float64
牛式===============================
執行第 188
           188
ICX  -0.206729
IOTA -0.044605
VET  -0.003368
XRP   0.022590
LTC   0.043379
XLM   0.063320
ADA   0.076470
ZEC   0.085705
BAT   0.087510
ZIL   0.100437
NEO   0.112899
ZRX   0.117021
QTUM  0.126791
ATOM  0.130569
TRX   0.151169
ETH   0.180134
BCH   0.187620
LINK  0.237226
ALGO  0.278589
BNB   0.380638
g================================================================          ETH     BCH   LINK    ALGO     BNB
0        NaN     NaN    NaN     NaN     NaN
1        NaN     NaN    NaN     NaN     NaN
2        NaN     NaN    NaN     NaN     NaN
3        NaN     NaN    NaN     NaN     NaN
4        NaN     NaN    NaN     NaN     NaN
..       ...     ...    ...     ...     ...
720  2316.15  509.55  19.79  0.9062  327.67
721  2121.52  490.60  18.44  0.8683  310.59
722  2146.27  504.08  18.66  0.9059  316.72
723  2111.19  497.02  18.20  0.8918  316.09
724  2138.86  498.00  18.38  0.8952  321.87

[725 rows x 5 columns]
ETH     0.162512
BCH     0.037291
LINK    0.404930
ALGO    0.342172
BNB     0.333333
Name: 182, dtype: float64
報酬 0.25604763087766746 %
i= ETH     0.162512
BCH     0.037291
LINK    0.404930
ALGO    0.342172
BNB     0.333333
Name: 182, dtype: float64
牛式===============================
執行第 189
           189
ICX  -0.046474
XRP   0.011557
IOTA  0.017152
ZEC   0.022057
BCH   0.037291
LTC   0.052286
ADA   0.068262
XLM   0.069485
NEO   0.079145
TRX   0.095376
QTUM  0.107522
VET   0.156520
BAT   0.161431
ETH   0.162512
ZRX   0.177043
ATOM  0.178984
ZIL   0.193878
BNB   0.333333
ALGO  0.342172
LINK  0.404930
g================================================================        ATOM      ZIL     BNB    ALGO   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  12.946  0.08133  327.67  0.9062  19.79
721  11.958  0.07509  310.59  0.8683  18.44
722  13.182  0.07496  316.72  0.9059  18.66
723  14.395  0.07299  316.09  0.8918  18.20
724  14.064  0.07377  321.87  0.8952  18.38

[725 rows x 5 columns]
ATOM    0.113850
ZIL     0.112752
BNB     0.278181
ALGO    0.346875
LINK    0.384083
Name: 183, dtype: float64
報酬 0.24714803413254033 %
i= ATOM    0.113850
ZIL     0.112752
BNB     0.278181
ALGO    0.346875
LINK    0.384083
Name: 183, dtype: float64
牛式===============================
執行第 190
           190
ICX  -0.077326
IOTA  0.005742
LTC   0.013339
ZEC   0.042486
TRX   0.054650
BCH   0.062971
XRP   0.073616
VET   0.098529
QTUM  0.102987
ZIL   0.112752
ATOM  0.113850
ZRX   0.117140
XLM   0.125387
ADA   0.135108
NEO   0.143420
BAT   0.143505
ETH   0.244735
BNB   0.278181
ALGO  0.346875
LINK  0.384083
g================================================================         BAT      ETH     BNB    ALGO   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  0.6135  2316.15  327.67  0.9062  19.79
721  0.5691  2121.52  310.59  0.8683  18.44
722  0.5695  2146.27  316.72  0.9059  18.66
723  0.5575  2111.19  316.09  0.8918  18.20
724  0.5623  2138.86  321.87  0.8952  18.38

[725 rows x 5 columns]
BAT     0.120637
ETH     0.202334
BNB     0.154125
ALGO    0.118758
LINK    0.175758
Name: 184, dtype: float64
報酬 0.1543223215185185 %
i= BAT     0.120637
ETH     0.202334
BNB     0.154125
ALGO    0.118758
LINK    0.175758
Name: 184, dtype: float64
牛式===============================
執行第 191
           191
ICX  -0.068138
ZIL  -0.018182
IOTA  0.003739
ATOM  0.018446
ZEC   0.054216
LTC   0.057305
BCH   0.085356
TRX   0.086168
QTUM  0.106838
ALGO  0.118758
BAT   0.120637
ADA   0.146985
ZRX   0.149082
BNB   0.154125
XLM   0.157697
XRP   0.170189
LINK  0.175758
VET   0.181818
NEO   0.183240
ETH   0.202334
g================================================================         XRP   LINK      VET     NEO      ETH
0       NaN    NaN      NaN     NaN      NaN
1       NaN    NaN      NaN     NaN      NaN
2       NaN    NaN      NaN     NaN      NaN
3       NaN    NaN      NaN     NaN      NaN
4       NaN    NaN      NaN     NaN      NaN
..      ...    ...      ...     ...      ...
720  0.6521  19.79  0.08348  37.005  2316.15
721  0.6236  18.44  0.07614  34.083  2121.52
722  0.6372  18.66  0.07704  34.637  2146.27
723  0.6251  18.20  0.07591  34.057  2111.19
724  0.6362  18.38  0.07768  34.191  2138.86

[725 rows x 5 columns]
XRP     0.209596
LINK    0.295322
VET     0.245014
NEO     0.315453
ETH     0.279595
Name: 185, dtype: float64
報酬 0.26899590319261824 %
i= XRP     0.209596
LINK    0.295322
VET     0.245014
NEO     0.315453
ETH     0.279595
Name: 185, dtype: float64
牛式===============================
執行第 192
           192
ICX  -0.003950
ZEC   0.041405
IOTA  0.052100
LTC   0.070224
ATOM  0.104126
BCH   0.110684
QTUM  0.165705
ADA   0.177460
ALGO  0.191932
ZIL   0.194407
XRP   0.209596
BNB   0.210188
TRX   0.211203
BAT   0.216100
XLM   0.222708
VET   0.245014
ZRX   0.267766
ETH   0.279595
LINK  0.295322
NEO   0.315453
g================================================================          VET     ZRX      ETH   LINK     NEO
0        NaN     NaN      NaN    NaN     NaN
1        NaN     NaN      NaN    NaN     NaN
2        NaN     NaN      NaN    NaN     NaN
3        NaN     NaN      NaN    NaN     NaN
4        NaN     NaN      NaN    NaN     NaN
..       ...     ...      ...    ...     ...
720  0.08348  0.7889  2316.15  19.79  37.005
721  0.07614  0.8190  2121.52  18.44  34.083
722  0.07704  0.8384  2146.27  18.66  34.637
723  0.07591  0.7890  2111.19  18.20  34.057
724  0.07768  0.7950  2138.86  18.38  34.191

[725 rows x 5 columns]
VET     0.093947
ZRX     0.076819
ETH     0.159129
LINK    0.232092
NEO     0.060455
Name: 186, dtype: float64
報酬 0.12448827365816273 %
i= VET     0.093947
ZRX     0.076819
ETH     0.159129
LINK    0.232092
NEO     0.060455
Name: 186, dtype: float64
牛式===============================
執行第 193
           193
ICX  -0.172485
IOTA -0.107597
ZEC  -0.093899
ATOM -0.026942
BCH  -0.023371
ALGO -0.016999
BNB  -0.004517
QTUM -0.004077
BAT   0.020505
ZIL   0.021438
ADA   0.038288
NEO   0.060455
LTC   0.065321
TRX   0.070716
ZRX   0.076819
XLM   0.077826
XRP   0.088923
VET   0.093947
ETH   0.159129
LINK  0.232092
g================================================================          XLM     XRP      VET      ETH   LINK
0        NaN     NaN      NaN      NaN    NaN
1        NaN     NaN      NaN      NaN    NaN
2        NaN     NaN      NaN      NaN    NaN
3        NaN     NaN      NaN      NaN    NaN
4        NaN     NaN      NaN      NaN    NaN
..       ...     ...      ...      ...    ...
720  0.25677  0.6521  0.08348  2316.15  19.79
721  0.24383  0.6236  0.07614  2121.52  18.44
722  0.24550  0.6372  0.07704  2146.27  18.66
723  0.24484  0.6251  0.07591  2111.19  18.20
724  0.24587  0.6362  0.07768  2138.86  18.38

[725 rows x 5 columns]
XLM     0.054728
XRP     0.071136
VET     0.090015
ETH     0.166271
LINK    0.312684
Name: 187, dtype: float64
報酬 0.13896695263967448 %
i= XLM     0.054728
XRP     0.071136
VET     0.090015
ETH     0.166271
LINK    0.312684
Name: 187, dtype: float64
牛式===============================
執行第 194
           194
ICX  -0.143663
ZEC  -0.139542
IOTA -0.123344
BCH  -0.086052
ATOM -0.078809
BNB  -0.068127
QTUM -0.036994
ALGO -0.036500
BAT  -0.003022
LTC   0.001163
TRX   0.005866
ZIL   0.026455
ADA   0.029046
XLM   0.054728
ZRX   0.058554
XRP   0.071136
NEO   0.080862
VET   0.090015
ETH   0.166271
LINK  0.312684
g================================================================         XRP     NEO      VET      ETH   LINK
0       NaN     NaN      NaN      NaN    NaN
1       NaN     NaN      NaN      NaN    NaN
2       NaN     NaN      NaN      NaN    NaN
3       NaN     NaN      NaN      NaN    NaN
4       NaN     NaN      NaN      NaN    NaN
..      ...     ...      ...      ...    ...
720  0.6521  37.005  0.08348  2316.15  19.79
721  0.6236  34.083  0.07614  2121.52  18.44
722  0.6372  34.637  0.07704  2146.27  18.66
723  0.6251  34.057  0.07591  2111.19  18.20
724  0.6362  34.191  0.07768  2138.86  18.38

[725 rows x 5 columns]
XRP     0.021995
NEO     0.088139
VET    -0.098597
ETH     0.128989
LINK    0.080201
Name: 188, dtype: float64
報酬 0.044145301532954 %
i= XRP     0.021995
NEO     0.088139
VET    -0.098597
ETH     0.128989
LINK    0.080201
Name: 188, dtype: float64
牛式===============================
執行第 195
           195
ICX  -0.170468
ATOM -0.163565
IOTA -0.146643
ZEC  -0.117526
ALGO -0.107172
BCH  -0.106096
VET  -0.098597
ZIL  -0.091575
BAT  -0.087984
BNB  -0.087617
QTUM -0.074935
ADA  -0.051120
TRX  -0.042656
ZRX  -0.035372
XLM  -0.015701
LTC   0.000852
XRP   0.021995
LINK  0.080201
NEO   0.088139
ETH   0.128989
g================================================================         LTC     XRP   LINK     NEO      ETH
0       NaN     NaN    NaN     NaN      NaN
1       NaN     NaN    NaN     NaN      NaN
2       NaN     NaN    NaN     NaN      NaN
3       NaN     NaN    NaN     NaN      NaN
4       NaN     NaN    NaN     NaN      NaN
..      ...     ...    ...     ...      ...
720  137.39  0.6521  19.79  37.005  2316.15
721  132.25  0.6236  18.44  34.083  2121.52
722  134.42  0.6372  18.66  34.637  2146.27
723  134.00  0.6251  18.20  34.057  2111.19
724  134.19  0.6362  18.38  34.191  2138.86

[725 rows x 5 columns]
LTC     0.001860
XRP    -0.021421
LINK    0.135000
NEO     0.044825
ETH     0.063567
Name: 189, dtype: float64
報酬 0.04476621733446255 %
i= LTC     0.001860
XRP    -0.021421
LINK    0.135000
NEO     0.044825
ETH     0.063567
Name: 189, dtype: float64
牛式===============================
執行第 196
           196
ATOM -0.130605
IOTA -0.126502
BCH  -0.114092
ZEC  -0.101340
ALGO -0.098995
ICX  -0.096591
BNB  -0.088569
ADA  -0.080328
BAT  -0.069022
QTUM -0.061297
ZIL  -0.056695
TRX  -0.056415
VET  -0.055556
XLM  -0.052710
XRP  -0.021421
ZRX  -0.012866
LTC   0.001860
NEO   0.044825
ETH   0.063567
LINK  0.135000
g================================================================         ZRX     LTC     NEO      ETH   LINK
0       NaN     NaN     NaN      NaN    NaN
1       NaN     NaN     NaN      NaN    NaN
2       NaN     NaN     NaN      NaN    NaN
3       NaN     NaN     NaN      NaN    NaN
4       NaN     NaN     NaN      NaN    NaN
..      ...     ...     ...      ...    ...
720  0.7889  137.39  37.005  2316.15  19.79
721  0.8190  132.25  34.083  2121.52  18.44
722  0.8384  134.42  34.637  2146.27  18.66
723  0.7890  134.00  34.057  2111.19  18.20
724  0.7950  134.19  34.191  2138.86  18.38

[725 rows x 5 columns]
ZRX    -0.122846
LTC     0.026112
NEO    -0.070957
ETH    -0.038446
LINK    0.131443
Name: 190, dtype: float64
報酬 -0.014938633644547773 %
i= ZRX    -0.122846
LTC     0.026112
NEO    -0.070957
ETH    -0.038446
LINK    0.131443
Name: 190, dtype: float64
牛式===============================
執行第 197
           197
BCH  -0.206446
VET  -0.195409
IOTA -0.170444
ADA  -0.163536
XRP  -0.159892
XLM  -0.157598
TRX  -0.157411
ATOM -0.156288
ZIL  -0.146914
QTUM -0.142155
ZEC  -0.138065
BAT  -0.124915
BNB  -0.123331
ZRX  -0.122846
NEO  -0.070957
ICX  -0.047619
ETH  -0.038446
ALGO -0.005436
LTC   0.026112
LINK  0.131443
g================================================================         ICX      ETH    ALGO     LTC   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  0.9279  2316.15  0.9062  137.39  19.79
721  1.0350  2121.52  0.8683  132.25  18.44
722  0.9786  2146.27  0.9059  134.42  18.66
723  0.9198  2111.19  0.8918  134.00  18.20
724  0.9519  2138.86  0.8952  134.19  18.38

[725 rows x 5 columns]
ICX    -0.036927
ETH    -0.097171
ALGO    0.188319
LTC     0.061318
LINK   -0.036117
Name: 191, dtype: float64
報酬 0.015884377489734168 %
i= ICX    -0.036927
ETH    -0.097171
ALGO    0.188319
LTC     0.061318
LINK   -0.036117
Name: 191, dtype: float64
牛式===============================
執行第 198
           198
TRX  -0.248294
BCH  -0.245264
VET  -0.218837
QTUM -0.212071
ZRX  -0.197920
ZIL  -0.193980
XRP  -0.193586
XLM  -0.188603
IOTA -0.183535
ADA  -0.177859
BAT  -0.176093
ZEC  -0.167672
BNB  -0.159651
NEO  -0.159031
ATOM -0.126394
ETH  -0.097171
ICX  -0.036927
LINK -0.036117
LTC   0.061318
ALGO  0.188319
g================================================================          ETH     ICX   LINK     LTC    ALGO
0        NaN     NaN    NaN     NaN     NaN
1        NaN     NaN    NaN     NaN     NaN
2        NaN     NaN    NaN     NaN     NaN
3        NaN     NaN    NaN     NaN     NaN
4        NaN     NaN    NaN     NaN     NaN
..       ...     ...    ...     ...     ...
720  2316.15  0.9279  19.79  137.39  0.9062
721  2121.52  1.0350  18.44  132.25  0.8683
722  2146.27  0.9786  18.66  134.42  0.9059
723  2111.19  0.9198  18.20  134.00  0.8918
724  2138.86  0.9519  18.38  134.19  0.8952

[725 rows x 5 columns]
ETH     0.000189
ICX     0.164047
LINK   -0.006977
LTC     0.124367
ALGO    0.246273
Name: 192, dtype: float64
報酬 0.10557995626705667 %
i= ETH     0.000189
ICX     0.164047
LINK   -0.006977
LTC     0.124367
ALGO    0.246273
Name: 192, dtype: float64
牛式===============================
執行第 199
           199
TRX  -0.146486
BCH  -0.140301
VET  -0.111200
XRP  -0.108719
XLM  -0.101343
QTUM -0.099739
ZRX  -0.098248
ADA  -0.089000
ZIL  -0.087654
BNB  -0.084571
NEO  -0.070215
IOTA -0.068450
BAT  -0.048080
ZEC  -0.043593
LINK -0.006977
ETH   0.000189
ATOM  0.071166
LTC   0.124367
ICX   0.164047
ALGO  0.246273
g================================================================          ETH    ATOM     LTC     ICX    ALGO
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  12.946  137.39  0.9279  0.9062
721  2121.52  11.958  132.25  1.0350  0.8683
722  2146.27  13.182  134.42  0.9786  0.9059
723  2111.19  14.395  134.00  0.9198  0.8918
724  2138.86  14.064  134.19  0.9519  0.8952

[725 rows x 5 columns]
ETH     0.005959
ATOM    0.140159
LTC     0.112821
ICX     0.164329
ALGO    0.301909
Name: 193, dtype: float64
報酬 0.14503545598406276 %
i= ETH     0.005959
ATOM    0.140159
LTC     0.112821
ICX     0.164329
ALGO    0.301909
Name: 193, dtype: float64
牛式===============================
執行第 200
           200
TRX  -0.101839
BCH  -0.097274
LINK -0.076404
VET  -0.070180
NEO  -0.063823
ZRX  -0.063312
ADA  -0.061452
XRP  -0.061324
BNB  -0.061137
XLM  -0.054981
ZIL  -0.048969
QTUM -0.044418
IOTA -0.026988
ETH   0.005959
ZEC   0.011156
BAT   0.029178
LTC   0.112821
ATOM  0.140159
ICX   0.164329
ALGO  0.301909
g================================================================         BAT     LTC    ATOM     ICX    ALGO
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6135  137.39  12.946  0.9279  0.9062
721  0.5691  132.25  11.958  1.0350  0.8683
722  0.5695  134.42  13.182  0.9786  0.9059
723  0.5575  134.00  14.395  0.9198  0.8918
724  0.5623  134.19  14.064  0.9519  0.8952

[725 rows x 5 columns]
BAT     0.037162
LTC     0.065248
ATOM    0.123888
ICX     0.167294
ALGO    0.392543
Name: 194, dtype: float64
報酬 0.1572269897953332 %
i= BAT     0.037162
LTC     0.065248
ATOM    0.123888
ICX     0.167294
ALGO    0.392543
Name: 194, dtype: float64
牛式===============================
執行第 201
           201
NEO  -0.047067
BNB  -0.024328
BCH  -0.023840
IOTA -0.018349
TRX  -0.017915
LINK -0.013921
XRP  -0.012955
ZEC  -0.012305
ZRX  -0.011652
QTUM -0.003990
XLM   0.006738
ADA   0.024776
ETH   0.027404
VET   0.034386
BAT   0.037162
ZIL   0.048387
LTC   0.065248
ATOM  0.123888
ICX   0.167294
ALGO  0.392543
g================================================================          ZIL     LTC    ATOM     ICX    ALGO
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08133  137.39  12.946  0.9279  0.9062
721  0.07509  132.25  11.958  1.0350  0.8683
722  0.07496  134.42  13.182  0.9786  0.9059
723  0.07299  134.00  14.395  0.9198  0.8918
724  0.07377  134.19  14.064  0.9519  0.8952

[725 rows x 5 columns]
ZIL    -0.079284
LTC     0.045130
ATOM   -0.010135
ICX    -0.044025
ALGO    0.414878
Name: 195, dtype: float64
報酬 0.06531283614857948 %
i= ZIL    -0.079284
LTC     0.045130
ATOM   -0.010135
ICX    -0.044025
ALGO    0.414878
Name: 195, dtype: float64
牛式===============================
執行第 202
           202
LINK -0.136564
NEO  -0.136461
ZRX  -0.126426
TRX  -0.118689
QTUM -0.104024
IOTA -0.098383
BCH  -0.097935
XRP  -0.092160
XLM  -0.088344
BAT  -0.087620
BNB  -0.083472
ZIL  -0.079284
ZEC  -0.076244
ETH  -0.059342
ADA  -0.058655
VET  -0.048476
ICX  -0.044025
ATOM -0.010135
LTC   0.045130
ALGO  0.414878
g================================================================          VET     ICX    ATOM     LTC    ALGO
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08348  0.9279  12.946  137.39  0.9062
721  0.07614  1.0350  11.958  132.25  0.8683
722  0.07704  0.9786  13.182  134.42  0.9059
723  0.07591  0.9198  14.395  134.00  0.8918
724  0.07768  0.9519  14.064  134.19  0.8952

[725 rows x 5 columns]
VET    -0.042714
ICX    -0.106557
ATOM   -0.022190
LTC    -0.006052
ALGO    0.131473
Name: 196, dtype: float64
報酬 -0.00920814144408435 %
i= VET    -0.042714
ICX    -0.106557
ATOM   -0.022190
LTC    -0.006052
ALGO    0.131473
Name: 196, dtype: float64
牛式===============================
執行第 203
           203
LINK -0.205011
NEO  -0.118689
ICX  -0.106557
ZRX  -0.097892
BAT  -0.094391
BNB  -0.089158
XLM  -0.086126
ZEC  -0.082663
XRP  -0.082321
IOTA -0.073728
BCH  -0.068181
ZIL  -0.066570
TRX  -0.061447
ETH  -0.045203
VET  -0.042714
ADA  -0.024547
QTUM -0.024141
ATOM -0.022190
LTC  -0.006052
ALGO  0.131473
g================================================================         ADA   QTUM    ATOM     LTC    ALGO
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  1.4039  7.079  12.946  137.39  0.9062
721  1.3327  6.504  11.958  132.25  0.8683
722  1.3497  6.776  13.182  134.42  0.9059
723  1.3356  6.639  14.395  134.00  0.8918
724  1.3478  6.694  14.064  134.19  0.8952

[725 rows x 5 columns]
ADA    -0.154256
QTUM   -0.121390
ATOM   -0.184546
LTC    -0.103672
ALGO   -0.166284
Name: 197, dtype: float64
報酬 -0.1460295984810241 %
i= ADA    -0.154256
QTUM   -0.121390
ATOM   -0.184546
LTC    -0.103672
ALGO   -0.166284
Name: 197, dtype: float64
熊式-----------------------------------
執行第 204
           204
ICX  -0.220793
NEO  -0.215131
ZIL  -0.211618
ATOM -0.184546
IOTA -0.181956
TRX  -0.174987
ALGO -0.166284
LINK -0.166276
XLM  -0.164202
BNB  -0.155235
ADA  -0.154256
XRP  -0.153909
ZRX  -0.153098
ZEC  -0.152693
BCH  -0.148898
BAT  -0.147036
VET  -0.143077
ETH  -0.131172
QTUM -0.121390
LTC  -0.103672
g================================================================         ICX     NEO      ZIL   ATOM    IOTA
0    0.2002  10.494  0.00879  3.258  0.2564
1    0.1862   9.427  0.00762  2.857  0.2322
2    0.2011   9.897  0.00749  2.898  0.2428
3    0.1925   9.818  0.00732  2.884  0.2413
4    0.1975   9.663  0.00773  2.910  0.2422
..      ...     ...      ...    ...     ...
720     NaN     NaN      NaN    NaN     NaN
721     NaN     NaN      NaN    NaN     NaN
722     NaN     NaN      NaN    NaN     NaN
723     NaN     NaN      NaN    NaN     NaN
724     NaN     NaN      NaN    NaN     NaN

[725 rows x 5 columns]
ICX    -0.021581
NEO     0.303627
ZIL     0.087273
ATOM    0.059275
IOTA    0.006856
Name: 198, dtype: float64
報酬 0.08708986693502965 %
i= ICX    -0.021581
NEO     0.303627
ZIL     0.087273
ATOM    0.059275
IOTA    0.006856
Name: 198, dtype: float64
牛式===============================
執行第 205
           205
LTC  -0.298392
ICX  -0.268356
ATOM -0.253231
IOTA -0.197687
ZIL  -0.189445
NEO  -0.180514
BAT  -0.167358
TRX  -0.156250
ZRX  -0.154060
ADA  -0.149103
XLM  -0.147871
ETH  -0.142577
ZEC  -0.140957
BCH  -0.140421
BNB  -0.135647
XRP  -0.130738
VET  -0.125113
QTUM -0.122365
ALGO -0.100957
LINK -0.077283
g================================================================         XRP      VET   QTUM    ALGO   LINK
0       NaN      NaN    NaN     NaN    NaN
1       NaN      NaN    NaN     NaN    NaN
2       NaN      NaN    NaN     NaN    NaN
3       NaN      NaN    NaN     NaN    NaN
4       NaN      NaN    NaN     NaN    NaN
..      ...      ...    ...     ...    ...
720  0.6521  0.08348  7.079  0.9062  19.79
721  0.6236  0.07614  6.504  0.8683  18.44
722  0.6372  0.07704  6.776  0.9059  18.66
723  0.6251  0.07591  6.639  0.8918  18.20
724  0.6362  0.07768  6.694  0.8952  18.38

[725 rows x 5 columns]
XRP    -0.138809
VET    -0.127918
QTUM   -0.130235
ALGO   -0.224789
LINK    0.012165
Name: 199, dtype: float64
報酬 -0.12191693079463187 %
i= XRP    -0.138809
VET    -0.127918
QTUM   -0.130235
ALGO   -0.224789
LINK    0.012165
Name: 199, dtype: float64
熊式-----------------------------------
執行第 206
           206
ATOM -0.292556
LTC  -0.250913
ICX  -0.246127
ALGO -0.224789
BAT  -0.207290
IOTA -0.202663
ZIL  -0.191057
NEO  -0.175137
XLM  -0.169132
ZEC  -0.162358
ADA  -0.159478
ZRX  -0.154749
BCH  -0.154293
TRX  -0.145355
XRP  -0.138809
BNB  -0.134335
ETH  -0.132472
QTUM -0.130235
VET  -0.127918
LINK  0.012165
g================================================================       ATOM    LTC     ICX   ALGO     BAT
0    3.258  56.59  0.2002  0.809  0.1972
1    2.857  54.82  0.1862  0.717  0.1682
2    2.898  56.60  0.2011  0.710  0.1870
3    2.884  55.28  0.1925  0.677  0.1788
4    2.910  55.88  0.1975  0.683  0.1764
..     ...    ...     ...    ...     ...
720    NaN    NaN     NaN    NaN     NaN
721    NaN    NaN     NaN    NaN     NaN
722    NaN    NaN     NaN    NaN     NaN
723    NaN    NaN     NaN    NaN     NaN
724    NaN    NaN     NaN    NaN     NaN

[725 rows x 5 columns]
ATOM   -0.074932
LTC     0.061008
ICX    -0.203057
ALGO    0.013482
BAT    -0.033687
Name: 200, dtype: float64
報酬 -0.047437355267857105 %
i= ATOM   -0.074932
LTC     0.061008
ICX    -0.203057
ALGO    0.013482
BAT    -0.033687
Name: 200, dtype: float64
熊式-----------------------------------
執行第 207
           207
ALGO -0.295821
ATOM -0.282559
ICX  -0.271758
LTC  -0.265779
ZIL  -0.244872
BCH  -0.240718
IOTA -0.237239
BAT  -0.237061
ADA  -0.235437
TRX  -0.229186
ZEC  -0.228513
NEO  -0.223800
XLM  -0.222237
ETH  -0.209163
ZRX  -0.206657
VET  -0.195157
XRP  -0.193099
QTUM -0.188702
BNB  -0.157918
LINK -0.044706
g================================================================       ALGO   ATOM     ICX    LTC      ZIL
0    0.809  3.258  0.2002  56.59  0.00879
1    0.717  2.857  0.1862  54.82  0.00762
2    0.710  2.898  0.2011  56.60  0.00749
3    0.677  2.884  0.1925  55.28  0.00732
4    0.683  2.910  0.1975  55.88  0.00773
..     ...    ...     ...    ...      ...
720    NaN    NaN     NaN    NaN      NaN
721    NaN    NaN     NaN    NaN      NaN
722    NaN    NaN     NaN    NaN      NaN
723    NaN    NaN     NaN    NaN      NaN
724    NaN    NaN     NaN    NaN      NaN

[725 rows x 5 columns]
ALGO   -0.080802
ATOM   -0.105009
ICX    -0.152979
LTC     0.024858
ZIL    -0.015873
Name: 201, dtype: float64
報酬 -0.06596106135094995 %
i= ALGO   -0.080802
ATOM   -0.105009
ICX    -0.152979
LTC     0.024858
ZIL    -0.015873
Name: 201, dtype: float64
熊式-----------------------------------
執行第 208
           208
ALGO -0.351466
ATOM -0.238453
LTC  -0.236267
ADA  -0.226380
ICX  -0.212719
IOTA -0.196490
XLM  -0.192653
VET  -0.191271
ZEC  -0.190445
BAT  -0.186625
ZIL  -0.186111
ETH  -0.178148
BCH  -0.175118
TRX  -0.173367
XRP  -0.159800
NEO  -0.153610
ZRX  -0.142111
BNB  -0.141821
QTUM -0.138983
LINK -0.015306
g================================================================       ALGO   ATOM    LTC      ADA     ICX
0    0.809  3.258  56.59  0.05262  0.2002
1    0.717  2.857  54.82  0.04715  0.1862
2    0.710  2.898  56.60  0.04733  0.2011
3    0.677  2.884  55.28  0.04668  0.1925
4    0.683  2.910  55.88  0.04740  0.1975
..     ...    ...    ...      ...     ...
720    NaN    NaN    NaN      NaN     NaN
721    NaN    NaN    NaN      NaN     NaN
722    NaN    NaN    NaN      NaN     NaN
723    NaN    NaN    NaN      NaN     NaN
724    NaN    NaN    NaN      NaN     NaN

[725 rows x 5 columns]
ALGO   -0.054127
ATOM   -0.130264
LTC    -0.005963
ADA    -0.010098
ICX    -0.083794
Name: 202, dtype: float64
報酬 -0.056849101379417455 %
i= ALGO   -0.054127
ATOM   -0.130264
LTC    -0.005963
ADA    -0.010098
ICX    -0.083794
Name: 202, dtype: float64
牛式===============================
執行第 209
           209
LTC  -0.234154
ADA  -0.122256
IOTA -0.094949
QTUM -0.085954
ATOM -0.085841
ZEC  -0.082924
TRX  -0.071278
XLM  -0.069434
VET  -0.061050
ETH  -0.060708
XRP  -0.050937
ALGO -0.049835
BCH  -0.040637
ZIL  -0.037209
ICX  -0.034862
BAT  -0.027339
NEO  -0.024611
BNB  -0.020167
ZRX  -0.007921
LINK  0.214900
g================================================================         BAT     NEO     BNB     ZRX   LINK
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  0.6135  37.005  327.67  0.7889  19.79
721  0.5691  34.083  310.59  0.8190  18.44
722  0.5695  34.637  316.72  0.8384  18.66
723  0.5575  34.057  316.09  0.7890  18.20
724  0.5623  34.191  321.87  0.7950  18.38

[725 rows x 5 columns]

BAT     0.022862
NEO     0.049877
BNB     0.051816
ZRX     0.081667
LINK    0.286517
Name: 203, dtype: float64
報酬 0.0985480376303681 %
i= BAT     0.022862
NEO     0.049877
BNB     0.051816
ZRX     0.081667
LINK    0.286517
Name: 203, dtype: float64
牛式===============================
執行第 210
           210
LTC  -0.189157
ZEC  -0.012830
XLM  -0.010716
ADA  -0.010370
ATOM -0.005218
ETH  -0.000536
ALGO  0.015152
QTUM  0.021915
XRP   0.022258
BAT   0.022862
IOTA  0.036145
VET   0.039403
BCH   0.040188
NEO   0.049877
BNB   0.051816
TRX   0.053178
ZIL   0.057895
ZRX   0.081667
ICX   0.120872
LINK  0.286517
g================================================================          TRX      ZIL     ZRX     ICX   LINK
0        NaN      NaN     NaN     NaN    NaN
1        NaN      NaN     NaN     NaN    NaN
2        NaN      NaN     NaN     NaN    NaN
3        NaN      NaN     NaN     NaN    NaN
4        NaN      NaN     NaN     NaN    NaN
..       ...      ...     ...     ...    ...
720  0.06432  0.08133  0.7889  0.9279  19.79
721  0.06111  0.07509  0.8190  1.0350  18.44
722  0.06219  0.07496  0.8384  0.9786  18.66
723  0.06139  0.07299  0.7890  0.9198  18.20
724  0.06184  0.07377  0.7950  0.9519  18.38

[725 rows x 5 columns]
TRX     0.045855
ZIL     0.020033
ZRX     0.079984
ICX     0.054387
LINK    0.177665
Name: 204, dtype: float64
報酬 0.07558477375145478 %
i= TRX     0.045855
ZIL     0.020033
ZRX     0.079984
ICX     0.054387
LINK    0.177665
Name: 204, dtype: float64
牛式===============================
執行第 211
           211
ZEC  -0.050982
XLM  -0.030438
ADA  -0.016259
XRP  -0.014608
BCH  -0.014327
ETH  -0.012233
ATOM  0.012980
QTUM  0.014602
ZIL   0.020033
NEO   0.023866
LTC   0.026398
IOTA  0.033008
BNB   0.040146
VET   0.040489
ALGO  0.044705
TRX   0.045855
BAT   0.048891
ICX   0.054387
ZRX   0.079984
LINK  0.177665
g================================================================          TRX     BAT     ICX     ZRX   LINK
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  0.06432  0.6135  0.9279  0.7889  19.79
721  0.06111  0.5691  1.0350  0.8190  18.44
722  0.06219  0.5695  0.9786  0.8384  18.66
723  0.06139  0.5575  0.9198  0.7890  18.20
724  0.06184  0.5623  0.9519  0.7950  18.38

[725 rows x 5 columns]
TRX     0.045587
BAT     0.088249
ICX     0.289954
ZRX     0.160774
LINK    0.132212
Name: 205, dtype: float64
報酬 0.14335532357714045 %
i= TRX     0.045587
BAT     0.088249
ICX     0.289954
ZRX     0.160774
LINK    0.132212
Name: 205, dtype: float64
牛式===============================
執行第 212
           212
LTC  -0.031528
ETH   0.006212
XRP   0.009673
ZEC   0.018675
XLM   0.021229
ADA   0.041914
ZIL   0.045226
TRX   0.045587
IOTA  0.055195
QTUM  0.056331
ATOM  0.060367
VET   0.064998
NEO   0.067179
BCH   0.068143
ALGO  0.085960
BAT   0.088249
BNB   0.092583
LINK  0.132212
ZRX   0.160774
ICX   0.289954
g================================================================         BAT     BNB   LINK     ZRX     ICX
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  0.6135  327.67  19.79  0.7889  0.9279
721  0.5691  310.59  18.44  0.8190  1.0350
722  0.5695  316.72  18.66  0.8384  0.9786
723  0.5575  316.09  18.20  0.7890  0.9198
724  0.5623  321.87  18.38  0.7950  0.9519

[725 rows x 5 columns]
BAT     0.149905
BNB     0.109091
LINK    0.152709
ZRX     0.240385
ICX     0.297923
Name: 206, dtype: float64
報酬 0.19000261163062676 %
i= BAT     0.149905
BNB     0.109091
LINK    0.152709
ZRX     0.240385
ICX     0.297923
Name: 206, dtype: float64
牛式===============================
執行第 213
           213
LTC   0.019768
XRP   0.069961
XLM   0.077801
ZEC   0.089534
VET   0.093466
IOTA  0.095193
ADA   0.098048
BNB   0.109091
TRX   0.112864
NEO   0.115818
ATOM  0.119373
ETH   0.127824
QTUM  0.143210
BCH   0.146014
BAT   0.149905
LINK  0.152709
ALGO  0.153632
ZIL   0.190153
ZRX   0.240385
ICX   0.297923
g================================================================       LINK    ALGO      ZIL     ZRX     ICX
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  19.79  0.9062  0.08133  0.7889  0.9279
721  18.44  0.8683  0.07509  0.8190  1.0350
722  18.66  0.9059  0.07496  0.8384  0.9786
723  18.20  0.8918  0.07299  0.7890  0.9198
724  18.38  0.8952  0.07377  0.7950  0.9519

[725 rows x 5 columns]
LINK    0.126943
ALGO    0.053944
ZIL     0.175768
ZRX     0.142609
ICX     0.223886
Name: 207, dtype: float64
報酬 0.14462998184164372 %
i= LINK    0.126943
ALGO    0.053944
ZIL     0.175768
ZRX     0.142609
ICX     0.223886
Name: 207, dtype: float64
牛式===============================
執行第 214
           214
LTC   0.008946
NEO   0.024487
ZEC   0.029711
TRX   0.032827
XRP   0.039746
XLM   0.044429
ALGO  0.053944
IOTA  0.057930
BCH   0.059453
VET   0.066863
ADA   0.067849
BNB   0.068638
ATOM  0.080968
BAT   0.086998
ETH   0.087576
QTUM  0.088583
LINK  0.126943
ZRX   0.142609
ZIL   0.175768
ICX   0.223886
g================================================================       QTUM   LINK     ZRX      ZIL     ICX
0      NaN    NaN     NaN      NaN     NaN
1      NaN    NaN     NaN      NaN     NaN
2      NaN    NaN     NaN      NaN     NaN
3      NaN    NaN     NaN      NaN     NaN
4      NaN    NaN     NaN      NaN     NaN
..     ...    ...     ...      ...     ...
720  7.079  19.79  0.7889  0.08133  0.9279
721  6.504  18.44  0.8190  0.07509  1.0350
722  6.776  18.66  0.8384  0.07496  0.9786
723  6.639  18.20  0.7890  0.07299  0.9198
724  6.694  18.38  0.7950  0.07377  0.9519

[725 rows x 5 columns]
QTUM   -0.133028
LINK   -0.044811
ZRX    -0.102196
ZIL    -0.078905
ICX    -0.080165
Name: 208, dtype: float64
報酬 -0.0878208419894769 %
i= QTUM   -0.133028
LINK   -0.044811
ZRX    -0.102196
ZIL    -0.078905
ICX    -0.080165
Name: 208, dtype: float64
熊式-----------------------------------
執行第 215
           215
ALGO -0.222906
BCH  -0.194984
VET  -0.193858
ZEC  -0.181610
NEO  -0.169341
ATOM -0.169185
TRX  -0.168846
XLM  -0.167505
BAT  -0.156785
BNB  -0.151104
XRP  -0.148233
IOTA -0.146875
ETH  -0.140473
QTUM -0.133028
ADA  -0.130134
ZRX  -0.102196
ICX  -0.080165
ZIL  -0.078905
LINK -0.044811
LTC   0.017167
g================================================================       ALGO     BCH       VET    ZEC     NEO
0    0.809  334.09  0.004916  55.45  10.494
1    0.717  315.09  0.004628  50.56   9.427
2    0.710  316.10  0.004580  50.57   9.897
3    0.677  339.01  0.004493  48.85   9.818
4    0.683  330.12  0.004454  50.01   9.663
..     ...     ...       ...    ...     ...
720    NaN     NaN       NaN    NaN     NaN
721    NaN     NaN       NaN    NaN     NaN
722    NaN     NaN       NaN    NaN     NaN
723    NaN     NaN       NaN    NaN     NaN
724    NaN     NaN       NaN    NaN     NaN

[725 rows x 5 columns]
ALGO    0.125322
BCH    -0.159349
VET    -0.120057
ZEC    -0.131943
NEO    -0.199263
Name: 209, dtype: float64
報酬 -0.09705815742463611 %
i= ALGO    0.125322
BCH    -0.159349
VET    -0.120057
ZEC    -0.131943
NEO    -0.199263
Name: 209, dtype: float64
熊式-----------------------------------
執行第 216
           216
ALGO -0.243691
VET  -0.190756
BCH  -0.172100
ZEC  -0.169358
ATOM -0.163722
BNB  -0.156932
ADA  -0.146086
NEO  -0.141918
IOTA -0.141771
ZRX  -0.128588
TRX  -0.127104
BAT  -0.126062
XRP  -0.105367
XLM  -0.100069
LINK -0.098253
QTUM -0.093706
ETH  -0.092009
ICX  -0.040955
ZIL  -0.016584
LTC   0.052749
g================================================================       ALGO       VET     BCH    ZEC   ATOM
0    0.809  0.004916  334.09  55.45  3.258
1    0.717  0.004628  315.09  50.56  2.857
2    0.710  0.004580  316.10  50.57  2.898
3    0.677  0.004493  339.01  48.85  2.884
4    0.683  0.004454  330.12  50.01  2.910
..     ...       ...     ...    ...    ...
720    NaN       NaN     NaN    NaN    NaN
721    NaN       NaN     NaN    NaN    NaN
722    NaN       NaN     NaN    NaN    NaN
723    NaN       NaN     NaN    NaN    NaN
724    NaN       NaN     NaN    NaN    NaN

[725 rows x 5 columns]
ALGO    0.044304
VET    -0.142945
BCH    -0.162899
ZEC    -0.172724
ATOM   -0.121804
Name: 210, dtype: float64
報酬 -0.11121387014424153 %
i= ALGO    0.044304
VET    -0.142945
BCH    -0.162899
ZEC    -0.172724
ATOM   -0.121804
Name: 210, dtype: float64
熊式-----------------------------------
執行第 217
           217
ALGO -0.283749
VET  -0.223878
ATOM -0.183396
ZEC  -0.176880
NEO  -0.161378
BNB  -0.155890
ADA  -0.155070
TRX  -0.152333
BCH  -0.151355
BAT  -0.123004
LINK -0.120690
XLM  -0.113121
IOTA -0.111611
ETH  -0.107359
XRP  -0.098360
ZRX  -0.095329
QTUM -0.094243
ICX  -0.032545
LTC  -0.028219
ZIL  -0.026187
g================================================================       ALGO       VET   ATOM    ZEC     NEO
0    0.809  0.004916  3.258  55.45  10.494
1    0.717  0.004628  2.857  50.56   9.427
2    0.710  0.004580  2.898  50.57   9.897
3    0.677  0.004493  2.884  48.85   9.818
4    0.683  0.004454  2.910  50.01   9.663
..     ...       ...    ...    ...     ...
720    NaN       NaN    NaN    NaN     NaN
721    NaN       NaN    NaN    NaN     NaN
722    NaN       NaN    NaN    NaN     NaN
723    NaN       NaN    NaN    NaN     NaN
724    NaN       NaN    NaN    NaN     NaN

[725 rows x 5 columns]
ALGO   -0.136886
VET    -0.105150
ATOM   -0.171781
ZEC    -0.127656
NEO    -0.181332
Name: 211, dtype: float64
報酬 -0.14456075250778191 %
i= ALGO   -0.136886
VET    -0.105150
ATOM   -0.171781
ZEC    -0.127656
NEO    -0.181332
Name: 211, dtype: float64
熊式-----------------------------------
執行第 218
           218
ALGO -0.284960
VET  -0.272356
ICX  -0.236915
ZEC  -0.224045
ADA  -0.221154
NEO  -0.219747
BCH  -0.208322
ATOM -0.203778
BNB  -0.202696
LINK -0.188960
ZRX  -0.178390
TRX  -0.168250
XLM  -0.154568
BAT  -0.147674
ETH  -0.147642
IOTA -0.141978
XRP  -0.129016
QTUM -0.114403
ZIL  -0.078526
LTC   0.033813
g================================================================       ALGO       VET     ICX    ZEC      ADA
0    0.809  0.004916  0.2002  55.45  0.05262
1    0.717  0.004628  0.1862  50.56  0.04715
2    0.710  0.004580  0.2011  50.57  0.04733
3    0.677  0.004493  0.1925  48.85  0.04668
4    0.683  0.004454  0.1975  50.01  0.04740
..     ...       ...     ...    ...      ...
720    NaN       NaN     NaN    NaN      NaN
721    NaN       NaN     NaN    NaN      NaN
722    NaN       NaN     NaN    NaN      NaN
723    NaN       NaN     NaN    NaN      NaN
724    NaN       NaN     NaN    NaN      NaN

[725 rows x 5 columns]
ALGO   -0.165072
VET    -0.132650
ICX    -0.273804
ZEC    -0.174858
ADA    -0.164646
Name: 212, dtype: float64
報酬 -0.18220586229482932 %
i= ALGO   -0.165072
VET    -0.132650
ICX    -0.273804
ZEC    -0.174858
ADA    -0.164646
Name: 212, dtype: float64
熊式-----------------------------------
執行第 219
           219
ALGO -0.633976
VET  -0.627971
BCH  -0.587193
ATOM -0.578101
LINK -0.568376
ICX  -0.566369
BNB  -0.565340
ETH  -0.558239
ZIL  -0.554922
ADA  -0.552957
QTUM -0.552052
NEO  -0.542165
TRX  -0.540349
BAT  -0.536304
IOTA -0.528830
ZEC  -0.516323
ZRX  -0.483439
XLM  -0.477595
XRP  -0.445607
LTC   0.013694
g================================================================       ALGO       VET     BCH   ATOM  LINK
0    0.809  0.004916  334.09  3.258  2.42
1    0.717  0.004628  315.09  2.857  2.28
2    0.710  0.004580  316.10  2.898  2.42
3    0.677  0.004493  339.01  2.884  2.30
4    0.683  0.004454  330.12  2.910  2.40
..     ...       ...     ...    ...   ...
720    NaN       NaN     NaN    NaN   NaN
721    NaN       NaN     NaN    NaN   NaN
722    NaN       NaN     NaN    NaN   NaN
723    NaN       NaN     NaN    NaN   NaN
724    NaN       NaN     NaN    NaN   NaN

[725 rows x 5 columns]
ALGO   -0.281430
VET    -0.148681
BCH    -0.180362
ATOM   -0.312912
LINK   -0.012165
Name: 213, dtype: float64
報酬 -0.18711012528930446 %
i= ALGO   -0.281430
VET    -0.148681
BCH    -0.180362
ATOM   -0.312912
LINK   -0.012165
Name: 213, dtype: float64
熊式-----------------------------------
執行第 220
           220
ALGO -0.548521
VET  -0.512949
ATOM -0.501382
ZIL  -0.484761
BCH  -0.465732
NEO  -0.463629
ZEC  -0.460474
BNB  -0.459980
ICX  -0.456330
LINK -0.443678
ETH  -0.433971
QTUM -0.432188
ADA  -0.418733
BAT  -0.417766
IOTA -0.416966
TRX  -0.396115
ZRX  -0.361872
XRP  -0.329608
XLM  -0.322642
LTC   0.048768
g================================================================       ALGO       VET   ATOM      ZIL     BCH
0    0.809  0.004916  3.258  0.00879  334.09
1    0.717  0.004628  2.857  0.00762  315.09
2    0.710  0.004580  2.898  0.00749  316.10
3    0.677  0.004493  2.884  0.00732  339.01
4    0.683  0.004454  2.910  0.00773  330.12
..     ...       ...    ...      ...     ...
720    NaN       NaN    NaN      NaN     NaN
721    NaN       NaN    NaN      NaN     NaN
722    NaN       NaN    NaN      NaN     NaN
723    NaN       NaN    NaN      NaN     NaN
724    NaN       NaN    NaN      NaN     NaN

[725 rows x 5 columns]
ALGO   -0.301916
VET    -0.222095
ATOM   -0.302563
ZIL    -0.248718
BCH    -0.224784
Name: 214, dtype: float64
報酬 -0.2600150913869323 %
i= ALGO   -0.301916
VET    -0.222095
ATOM   -0.302563
ZIL    -0.248718
BCH    -0.224784
Name: 214, dtype: float64
熊式-----------------------------------
執行第 221
           221
ALGO -0.492424
LINK -0.471605
VET  -0.458395
NEO  -0.426950
ZEC  -0.416959
ATOM -0.402403
BNB  -0.400946
ADA  -0.397382
ZIL  -0.395105
BCH  -0.385719
ETH  -0.384600
QTUM -0.378836
ICX  -0.373751
BAT  -0.357812
IOTA -0.349032
TRX  -0.334473
ZRX  -0.302357
XRP  -0.284362
XLM  -0.259416
LTC   0.021141
g================================================================       ALGO  LINK       VET     NEO    ZEC
0    0.809  2.42  0.004916  10.494  55.45
1    0.717  2.28  0.004628   9.427  50.56
2    0.710  2.42  0.004580   9.897  50.57
3    0.677  2.30  0.004493   9.818  48.85
4    0.683  2.40  0.004454   9.663  50.01
..     ...   ...       ...     ...    ...
720    NaN   NaN       NaN     NaN    NaN
721    NaN   NaN       NaN     NaN    NaN
722    NaN   NaN       NaN     NaN    NaN
723    NaN   NaN       NaN     NaN    NaN
724    NaN   NaN       NaN     NaN    NaN

[725 rows x 5 columns]
ALGO   -0.244287
LINK    0.081633
VET    -0.131685
NEO    -0.095548
ZEC    -0.138221
Name: 215, dtype: float64
報酬 -0.10562162550816172 %
i= ALGO   -0.244287
LINK    0.081633
VET    -0.131685
NEO    -0.095548
ZEC    -0.138221
Name: 215, dtype: float64
熊式-----------------------------------
執行第 222
           222
LINK -0.493947
ALGO -0.472192
VET  -0.460107
ICX  -0.420891
NEO  -0.396531
ZEC  -0.391181
ETH  -0.391165
ZIL  -0.379427
QTUM -0.378601
BNB  -0.374699
BAT  -0.368798
IOTA -0.366858
ATOM -0.365797
ADA  -0.351059
BCH  -0.347729
TRX  -0.317154
ZRX  -0.285199
XLM  -0.275697
XRP  -0.269673
LTC  -0.014644
g================================================================      LINK   ALGO       VET     ICX     NEO
0    2.42  0.809  0.004916  0.2002  10.494
1    2.28  0.717  0.004628  0.1862   9.427
2    2.42  0.710  0.004580  0.2011   9.897
3    2.30  0.677  0.004493  0.1925   9.818
4    2.40  0.683  0.004454  0.1975   9.663
..    ...    ...       ...     ...     ...
720   NaN    NaN       NaN     NaN     NaN
721   NaN    NaN       NaN     NaN     NaN
722   NaN    NaN       NaN     NaN     NaN
723   NaN    NaN       NaN     NaN     NaN
724   NaN    NaN       NaN     NaN     NaN

[725 rows x 5 columns]
LINK    0.312321
ALGO   -0.063056
VET    -0.069427
ICX     0.037920
NEO    -0.067538
Name: 216, dtype: float64
報酬 0.030044108449205485 %
i= LINK    0.312321
ALGO   -0.063056
VET    -0.069427
ICX     0.037920
NEO    -0.067538
Name: 216, dtype: float64
熊式-----------------------------------
執行第 223
           223
LINK -0.563725
ALGO -0.549787
VET  -0.517815
ICX  -0.466201
QTUM -0.464890
NEO  -0.453642
ATOM -0.453089
BAT  -0.449803
IOTA -0.447822
ETH  -0.446801
BNB  -0.441211
ZIL  -0.438655
ZRX  -0.420235
ADA  -0.414876
ZEC  -0.406091
BCH  -0.367785
TRX  -0.363395
XRP  -0.335916
XLM  -0.323009
LTC   0.024076
g================================================================      LINK   ALGO       VET     ICX   QTUM
0    2.42  0.809  0.004916  0.2002  2.642
1    2.28  0.717  0.004628  0.1862  2.347
2    2.42  0.710  0.004580  0.2011  2.376
3    2.30  0.677  0.004493  0.1925  2.291
4    2.40  0.683  0.004454  0.1975  2.455
..    ...    ...       ...     ...    ...
720   NaN    NaN       NaN     NaN    NaN
721   NaN    NaN       NaN     NaN    NaN
722   NaN    NaN       NaN     NaN    NaN
723   NaN    NaN       NaN     NaN    NaN
724   NaN    NaN       NaN     NaN    NaN

[725 rows x 5 columns]
LINK    0.303371
ALGO    0.081543
VET     0.086542
ICX     0.075627
QTUM    0.026203
Name: 217, dtype: float64
報酬 0.11465716769316718 %
i= LINK    0.303371
ALGO    0.081543
VET     0.086542
ICX     0.075627
QTUM    0.026203
Name: 217, dtype: float64
熊式-----------------------------------
執行第 224
           224
LINK -0.510471
ALGO -0.489299
VET  -0.445167
QTUM -0.434380
ATOM -0.410959
BAT  -0.410616
ETH  -0.402938
NEO  -0.400531
ICX  -0.399934
ZIL  -0.386087
IOTA -0.379611
BNB  -0.378019
ZEC  -0.376772
ZRX  -0.370697
ADA  -0.349710
TRX  -0.325941
BCH  -0.315701
XRP  -0.293372
XLM  -0.260956
LTC  -0.017571
g================================================================      LINK   ALGO       VET   QTUM   ATOM
0    2.42  0.809  0.004916  2.642  3.258
1    2.28  0.717  0.004628  2.347  2.857
2    2.42  0.710  0.004580  2.376  2.898
3    2.30  0.677  0.004493  2.291  2.884
4    2.40  0.683  0.004454  2.455  2.910
..    ...    ...       ...    ...    ...
720   NaN    NaN       NaN    NaN    NaN
721   NaN    NaN       NaN    NaN    NaN
722   NaN    NaN       NaN    NaN    NaN
723   NaN    NaN       NaN    NaN    NaN
724   NaN    NaN       NaN    NaN    NaN

[725 rows x 5 columns]
LINK    0.195431
ALGO    0.008515
VET     0.055824
QTUM    0.033443
ATOM    0.016495
Name: 218, dtype: float64
報酬 0.06194177065859252 %
i= LINK    0.195431
ALGO    0.008515
VET     0.055824
QTUM    0.033443
ATOM    0.016495
Name: 218, dtype: float64
熊式-----------------------------------
執行第 225
           225
LINK -0.034653
ZRX  -0.006821
LTC  -0.003158
NEO   0.010233
ALGO  0.031479
BAT   0.065836
QTUM  0.070395
XRP   0.086245
ETH   0.092076
ICX   0.102238
VET   0.110722
ATOM  0.114391
BNB   0.119612
ADA   0.127108
ZIL   0.128205
XLM   0.150967
ZEC   0.151280
IOTA  0.153425
TRX   0.213523
BCH   0.276100
g================================================================      LINK     ZRX    LTC     NEO   ALGO
0    2.42  0.1814  56.59  10.494  0.809
1    2.28  0.1624  54.82   9.427  0.717
2    2.42  0.1736  56.60   9.897  0.710
3    2.30  0.1751  55.28   9.818  0.677
4    2.40  0.1711  55.88   9.663  0.683
..    ...     ...    ...     ...    ...
720   NaN     NaN    NaN     NaN    NaN
721   NaN     NaN    NaN     NaN    NaN
722   NaN     NaN    NaN     NaN    NaN
723   NaN     NaN    NaN     NaN    NaN
724   NaN     NaN    NaN     NaN    NaN

[725 rows x 5 columns]
LINK    0.125000
ZRX     0.194444
LTC    -0.020554
NEO     0.094316
ALGO    0.069341
Name: 219, dtype: float64
報酬 0.0925095563003612 %
i= LINK    0.125000
ZRX     0.194444
LTC    -0.020554
NEO     0.094316
ALGO    0.069341
Name: 219, dtype: float64
熊式-----------------------------------
執行第 226
           226
LTC  -0.077105
LINK -0.070248
ZRX  -0.030411
QTUM  0.000000
ETH   0.016750
ALGO  0.030144
VET   0.030486
BAT   0.030967
XRP   0.039467
NEO   0.043597
XLM   0.046847
ADA   0.068054
ICX   0.091052
BNB   0.121683
TRX   0.133528
ZIL   0.143662
IOTA  0.147806
ATOM  0.149113
ZEC   0.171429
BCH   0.249943
g================================================================        LTC  LINK     ZRX   QTUM     ETH
0    56.59  2.42  0.1814  2.642  209.22
1    54.82  2.28  0.1624  2.347  187.11
2    56.60  2.42  0.1736  2.376  188.16
3    55.28  2.30  0.1751  2.291  185.03
4    55.88  2.40  0.1711  2.455  185.61
..     ...   ...     ...    ...     ...
720    NaN   NaN     NaN    NaN     NaN
721    NaN   NaN     NaN    NaN     NaN
722    NaN   NaN     NaN    NaN     NaN
723    NaN   NaN     NaN    NaN     NaN
724    NaN   NaN     NaN    NaN     NaN

[725 rows x 5 columns]
LTC     0.022670
LINK    0.071429
ZRX     0.148601
QTUM    0.092346
ETH     0.091980
Name: 220, dtype: float64
報酬 0.0854050311512693 %

i= LTC     0.022670
LINK    0.071429
ZRX     0.148601
QTUM    0.092346
ETH     0.091980
Name: 220, dtype: float64
熊式-----------------------------------
執行第 227
           227
LTC  -0.087161
ZRX  -0.030593
QTUM  0.051107
LINK  0.056075
ALGO  0.072592
XRP   0.075579
XLM   0.085940
ETH   0.087952
NEO   0.090719
BAT   0.091646
ICX   0.114961
VET   0.119450
ZIL   0.132948
IOTA  0.140675
ADA   0.144298
TRX   0.159301
BNB   0.175716
ATOM  0.179348
BCH   0.285228
ZEC   0.324519
g================================================================        LTC     ZRX   QTUM  LINK   ALGO
0    56.59  0.1814  2.642  2.42  0.809
1    54.82  0.1624  2.347  2.28  0.717
2    56.60  0.1736  2.376  2.42  0.710
3    55.28  0.1751  2.291  2.30  0.677
4    55.88  0.1711  2.455  2.40  0.683
..     ...     ...    ...   ...    ...
720    NaN     NaN    NaN   NaN    NaN
721    NaN     NaN    NaN   NaN    NaN
722    NaN     NaN    NaN   NaN    NaN
723    NaN     NaN    NaN   NaN    NaN
724    NaN     NaN    NaN   NaN    NaN

[725 rows x 5 columns]
LTC     0.007157
ZRX    -0.022174
QTUM   -0.069882
LINK    0.049223
ALGO   -0.094481
Name: 221, dtype: float64
報酬 -0.02603138254191457 %
i= LTC     0.007157
ZRX    -0.022174
QTUM   -0.069882
LINK    0.049223
ALGO   -0.094481
Name: 221, dtype: float64
熊式-----------------------------------
執行第 228
           228
ZRX  -0.020202
LTC  -0.016473
QTUM  0.019868
XRP   0.032018
ALGO  0.040109
NEO   0.040608
XLM   0.043524
ZIL   0.062500
ICX   0.067374
ETH   0.071908
LINK  0.086124
ADA   0.091583
TRX   0.093476
BAT   0.102917
ATOM  0.129099
IOTA  0.139918
VET   0.147781
BNB   0.165703
BCH   0.236480
ZEC   0.285826
g================================================================         ZRX    LTC   QTUM      XRP   ALGO
0    0.1814  56.59  2.642  0.29787  0.809
1    0.1624  54.82  2.347  0.26338  0.717
2    0.1736  56.60  2.376  0.26408  0.710
3    0.1751  55.28  2.291  0.26055  0.677
4    0.1711  55.88  2.455  0.26543  0.683
..      ...    ...    ...      ...    ...
720     NaN    NaN    NaN      NaN    NaN
721     NaN    NaN    NaN      NaN    NaN
722     NaN    NaN    NaN      NaN    NaN
723     NaN    NaN    NaN      NaN    NaN
724     NaN    NaN    NaN      NaN    NaN

[725 rows x 5 columns]
ZRX    -0.115369
LTC     0.024214
QTUM   -0.108257
XRP    -0.124760
ALGO   -0.254215
Name: 222, dtype: float64
報酬 -0.11567732780114856 %
i= ZRX    -0.115369
LTC     0.024214
QTUM   -0.108257
XRP    -0.124760
ALGO   -0.254215
Name: 222, dtype: float64
熊式-----------------------------------
執行第 229
           229
LTC  -0.045406
ZRX   0.018827
XLM   0.045467
XRP   0.051224
TRX   0.070833
ZIL   0.074850
ICX   0.092152
QTUM  0.098659
ETH   0.102571
NEO   0.103045
BAT   0.107335
ADA   0.115559
LINK  0.117978
ATOM  0.147041
ALGO  0.151659
VET   0.154867
IOTA  0.155963
BCH   0.181077
BNB   0.188098
ZEC   0.200651
g================================================================        LTC     ZRX      XLM      XRP      TRX
0    56.59  0.1814  0.07442  0.29787  0.02049
1    54.82  0.1624  0.06922  0.26338  0.01778
2    56.60  0.1736  0.07019  0.26408  0.01752
3    55.28  0.1751  0.06851  0.26055  0.01688
4    55.88  0.1711  0.06770  0.26543  0.01692
..     ...     ...      ...      ...      ...
720    NaN     NaN      NaN      NaN      NaN
721    NaN     NaN      NaN      NaN      NaN
722    NaN     NaN      NaN      NaN      NaN
723    NaN     NaN      NaN      NaN      NaN
724    NaN     NaN      NaN      NaN      NaN

[725 rows x 5 columns]
LTC    0.010587
ZRX   -0.063311
XLM   -0.106259
XRP   -0.096358
TRX   -0.124782
Name: 223, dtype: float64
報酬 -0.07602467187458466 %
i= LTC    0.010587
ZRX   -0.063311
XLM   -0.106259
XRP   -0.096358
TRX   -0.124782
Name: 223, dtype: float64
熊式-----------------------------------
執行第 230
           230
LTC  -0.048344
XLM   0.056882
ZRX   0.062412
XRP   0.077828
ZIL   0.099150
ICX   0.099393
QTUM  0.121929
TRX   0.132602
ADA   0.133282
BAT   0.144435
ALGO  0.152457
VET   0.152789
ETH   0.171384
IOTA  0.182494
BNB   0.183495
NEO   0.184523
ATOM  0.197391
LINK  0.203209
BCH   0.211322
ZEC   0.278532
g================================================================        LTC      XLM     ZRX      XRP      ZIL
0    56.59  0.07442  0.1814  0.29787  0.00879
1    54.82  0.06922  0.1624  0.26338  0.00762
2    56.60  0.07019  0.1736  0.26408  0.00749
3    55.28  0.06851  0.1751  0.26055  0.00732
4    55.88  0.06770  0.1711  0.26543  0.00773
..     ...      ...     ...      ...      ...
720    NaN      NaN     NaN      NaN      NaN
721    NaN      NaN     NaN      NaN      NaN
722    NaN      NaN     NaN      NaN      NaN
723    NaN      NaN     NaN      NaN      NaN
724    NaN      NaN     NaN      NaN      NaN

[725 rows x 5 columns]
LTC    0.026612
XLM   -0.139567
ZRX   -0.139385
XRP   -0.113099
ZIL   -0.058920
Name: 224, dtype: float64
報酬 -0.08487166185060553 %
i= LTC    0.026612
XLM   -0.139567
ZRX   -0.139385
XRP   -0.113099
ZIL   -0.058920
Name: 224, dtype: float64
熊式-----------------------------------
執行第 231
           231
LTC  -0.034847
ZRX   0.041896
XLM   0.092412
XRP   0.101045
ZEC   0.105121
ZIL   0.116477
TRX   0.125122
ALGO  0.134138
IOTA  0.144893
QTUM  0.145946
ICX   0.146542
ADA   0.159570
ETH   0.171078
ATOM  0.182671
LINK  0.184615
BNB   0.195380
NEO   0.204855
VET   0.205674
BCH   0.231144
BAT   0.281302
g================================================================        LTC     ZRX      XLM      XRP    ZEC
0    56.59  0.1814  0.07442  0.29787  55.45
1    54.82  0.1624  0.06922  0.26338  50.56
2    56.60  0.1736  0.07019  0.26408  50.57
3    55.28  0.1751  0.06851  0.26055  48.85
4    55.88  0.1711  0.06770  0.26543  50.01
..     ...     ...      ...      ...    ...
720    NaN     NaN      NaN      NaN    NaN
721    NaN     NaN      NaN      NaN    NaN
722    NaN     NaN      NaN      NaN    NaN
723    NaN     NaN      NaN      NaN    NaN
724    NaN     NaN      NaN      NaN    NaN

[725 rows x 5 columns]
LTC    0.025180
ZRX   -0.468455
XLM   -0.462531
XRP   -0.432480
ZEC   -0.502509
Name: 225, dtype: float64
報酬 -0.3681591166592527 %
i= LTC    0.025180
ZRX   -0.468455
XLM   -0.462531
XRP   -0.432480
ZEC   -0.502509
Name: 225, dtype: float64
熊式-----------------------------------
執行第 232
           232
IOTA -0.054997
ZIL  -0.044335
ZRX  -0.033210
ADA  -0.027732
ALGO -0.021628
TRX  -0.021496
XLM  -0.019110
XRP  -0.017860
ICX  -0.013909
ETH  -0.004247
BCH  -0.001810
LTC   0.001466
ATOM  0.002412
QTUM  0.003981
LINK  0.004444
BNB   0.005710
ZEC   0.006879
VET   0.051256
NEO   0.068907
BAT   0.087179
g================================================================        IOTA      ZIL     ZRX      ADA   ALGO
0    0.2564  0.00879  0.1814  0.05262  0.809
1    0.2322  0.00762  0.1624  0.04715  0.717
2    0.2428  0.00749  0.1736  0.04733  0.710
3    0.2413  0.00732  0.1751  0.04668  0.677
4    0.2422  0.00773  0.1711  0.04740  0.683
..      ...      ...     ...      ...    ...
720     NaN      NaN     NaN      NaN    NaN
721     NaN      NaN     NaN      NaN    NaN
722     NaN      NaN     NaN      NaN    NaN
723     NaN      NaN     NaN      NaN    NaN
724     NaN      NaN     NaN      NaN    NaN

[725 rows x 5 columns]
IOTA   -0.441050
ZIL    -0.493581
ZRX    -0.409091
ADA    -0.451875
ALGO   -0.591104
Name: 226, dtype: float64
報酬 -0.47734002925718555 %
i= IOTA   -0.441050
ZIL    -0.493581
ZRX    -0.409091
ADA    -0.451875
ALGO   -0.591104
Name: 226, dtype: float64
熊式-----------------------------------
執行第 233
           233
ZEC  -0.018149
ATOM  0.000922
ZIL   0.005102
ALGO  0.005693
LTC   0.016771
LINK  0.022124
IOTA  0.022551
ICX   0.033547
QTUM  0.035656
ETH   0.037237
ADA   0.045424
ZRX   0.047995
TRX   0.059397
BCH   0.059677
XLM   0.073378
VET   0.081783
BNB   0.109152
NEO   0.120937
XRP   0.122125
BAT   0.128529
g================================================================        ZEC   ATOM      ZIL   ALGO    LTC
0    55.45  3.258  0.00879  0.809  56.59
1    50.56  2.857  0.00762  0.717  54.82
2    50.57  2.898  0.00749  0.710  56.60
3    48.85  2.884  0.00732  0.677  55.28
4    50.01  2.910  0.00773  0.683  55.88
..     ...    ...      ...    ...    ...
720    NaN    NaN      NaN    NaN    NaN
721    NaN    NaN      NaN    NaN    NaN
722    NaN    NaN      NaN    NaN    NaN
723    NaN    NaN      NaN    NaN    NaN
724    NaN    NaN      NaN    NaN    NaN

[725 rows x 5 columns]
ZEC    -0.506719
ATOM   -0.491432
ZIL    -0.497823
ALGO   -0.563905
LTC     0.019330
Name: 227, dtype: float64
報酬 -0.4081099373349395 %
i= ZEC    -0.506719
ATOM   -0.491432
ZIL    -0.497823
ALGO   -0.563905
LTC     0.019330
Name: 227, dtype: float64
熊式-----------------------------------
執行第 234
           234
LTC  -0.098125
ATOM -0.081604
ZEC  -0.061478
LINK -0.057269
ZIL  -0.051151
ZRX  -0.036082
ICX  -0.033300
BCH  -0.031065
QTUM -0.022727
ADA  -0.021739
IOTA -0.018051
ETH  -0.009723
TRX  -0.001781
ALGO  0.005229
BNB   0.019008
XLM   0.021234
BAT   0.025716
VET   0.035554
NEO   0.045287
XRP   0.093770
g================================================================        LTC   ATOM    ZEC  LINK      ZIL
0    56.59  3.258  55.45  2.42  0.00879
1    54.82  2.857  50.56  2.28  0.00762
2    56.60  2.898  50.57  2.42  0.00749
3    55.28  2.884  48.85  2.30  0.00732
4    55.88  2.910  50.01  2.40  0.00773
..     ...    ...    ...   ...      ...
720    NaN    NaN    NaN   NaN      NaN
721    NaN    NaN    NaN   NaN      NaN
722    NaN    NaN    NaN   NaN      NaN
723    NaN    NaN    NaN   NaN      NaN
724    NaN    NaN    NaN   NaN      NaN

[725 rows x 5 columns]
LTC    -0.007817
ATOM   -0.376096
ZEC    -0.400140
LINK   -0.483951
ZIL    -0.356643
Name: 228, dtype: float64
報酬 -0.32492938538230093 %
i= LTC    -0.007817
ATOM   -0.376096
ZEC    -0.400140
LINK   -0.483951
ZIL    -0.356643
Name: 228, dtype: float64
熊式-----------------------------------
執行第 235
           235
LTC  -0.068434
ATOM  0.027097
ALGO  0.028121
ZEC   0.029153
ICX   0.041372
ZIL   0.052925
BCH   0.054657
QTUM  0.057541
ZRX   0.063255
ETH   0.072983
LINK  0.075377
XLM   0.085893
BNB   0.090340
ADA   0.100629
IOTA  0.106349
TRX   0.107977
NEO   0.115637
BAT   0.121971
VET   0.137548
XRP   0.187060
g================================================================        LTC   ATOM   ALGO    ZEC     ICX
0    56.59  3.258  0.809  55.45  0.2002
1    54.82  2.857  0.717  50.56  0.1862
2    56.60  2.898  0.710  50.57  0.2011
3    55.28  2.884  0.677  48.85  0.1925
4    55.88  2.910  0.683  50.01  0.1975
..     ...    ...    ...    ...     ...
720    NaN    NaN    NaN    NaN     NaN
721    NaN    NaN    NaN    NaN     NaN
722    NaN    NaN    NaN    NaN     NaN
723    NaN    NaN    NaN    NaN     NaN
724    NaN    NaN    NaN    NaN     NaN

[725 rows x 5 columns]
LTC    -0.016937
ATOM   -0.447672
ALGO   -0.545748
ZEC    -0.417496
ICX    -0.483257
Name: 229, dtype: float64
報酬 -0.3822221557815703 %

i= LTC    -0.016937
ATOM   -0.447672
ALGO   -0.545748
ZEC    -0.417496
ICX    -0.483257
Name: 229, dtype: float64
熊式-----------------------------------
執行第 236
           236
ATOM -0.123638
ZEC  -0.119538
LINK -0.106667
ICX  -0.101457
ALGO -0.096552
ZIL  -0.090206
ETH  -0.085788
IOTA -0.081704
NEO  -0.076245
QTUM -0.075426
BNB  -0.073011
BCH  -0.072042
TRX  -0.061620
ZRX  -0.048185
VET  -0.043128
XLM  -0.041635
ADA  -0.040000
BAT  -0.032665
XRP   0.027748
LTC   0.060104
g================================================================       ATOM    ZEC  LINK     ICX   ALGO
0    3.258  55.45  2.42  0.2002  0.809
1    2.857  50.56  2.28  0.1862  0.717
2    2.898  50.57  2.42  0.2011  0.710
3    2.884  48.85  2.30  0.1925  0.677
4    2.910  50.01  2.40  0.1975  0.683
..     ...    ...   ...     ...    ...
720    NaN    NaN   NaN     NaN    NaN
721    NaN    NaN   NaN     NaN    NaN
722    NaN    NaN   NaN     NaN    NaN
723    NaN    NaN   NaN     NaN    NaN
724    NaN    NaN   NaN     NaN    NaN

[725 rows x 5 columns]
ATOM   -0.423668
ZEC    -0.394247
LINK   -0.541667
ICX    -0.425262
ALGO   -0.507824
Name: 230, dtype: float64
報酬 -0.45853340112598245 %
i= ATOM   -0.423668
ZEC    -0.394247
LINK   -0.541667
ICX    -0.425262
ALGO   -0.507824
Name: 230, dtype: float64
熊式-----------------------------------
執行第 237
           237
BAT  -0.091857
ATOM -0.087727
LINK -0.077922
ZEC  -0.069207
QTUM -0.058962
NEO  -0.047978
ETH  -0.046649
VET  -0.041176
ZIL  -0.035623
BCH  -0.032017
ALGO -0.031915
BNB  -0.022544
IOTA -0.022130
ADA  -0.019517
ICX  -0.016276
ZRX  -0.008570
XLM  -0.006946
TRX  -0.004344
LTC   0.034099
XRP   0.054237
g================================================================         BAT   ATOM  LINK    ZEC   QTUM
0    0.1972  3.258  2.42  55.45  2.642
1    0.1682  2.857  2.28  50.56  2.347
2    0.1870  2.898  2.42  50.57  2.376
3    0.1788  2.884  2.30  48.85  2.291
4    0.1764  2.910  2.40  50.01  2.455
..      ...    ...   ...    ...    ...
720     NaN    NaN   NaN    NaN    NaN
721     NaN    NaN   NaN    NaN    NaN
722     NaN    NaN   NaN    NaN    NaN
723     NaN    NaN   NaN    NaN    NaN
724     NaN    NaN   NaN    NaN    NaN

[725 rows x 5 columns]
BAT    -0.400100
ATOM   -0.394587
LINK   -0.489529
ZEC    -0.261875
QTUM   -0.428718
Name: 231, dtype: float64
報酬 -0.3949619897169343 %
i= BAT    -0.400100
ATOM   -0.394587
LINK   -0.489529
ZEC    -0.261875
QTUM   -0.428718
Name: 231, dtype: float64
熊式-----------------------------------
執行第 238
           238
ATOM -0.061598
BAT  -0.046496
ZEC  -0.040373
QTUM -0.039651
ZRX  -0.028626
ETH  -0.023456
NEO  -0.023363
ZIL  -0.015464
BCH  -0.010699
LINK  0.000000
ALGO  0.001300
XLM   0.003946
TRX   0.016696
VET   0.017016
BNB   0.017843
IOTA  0.019163
ICX   0.030156
ADA   0.033956
XRP   0.072988
LTC   0.093121
g================================================================       ATOM     BAT    ZEC   QTUM     ZRX
0    3.258  0.1972  55.45  2.642  0.1814
1    2.857  0.1682  50.56  2.347  0.1624
2    2.898  0.1870  50.57  2.376  0.1736
3    2.884  0.1788  48.85  2.291  0.1751
4    2.910  0.1764  50.01  2.455  0.1711
..     ...     ...    ...    ...     ...
720    NaN     NaN    NaN    NaN     NaN
721    NaN     NaN    NaN    NaN     NaN
722    NaN     NaN    NaN    NaN     NaN
723    NaN     NaN    NaN    NaN     NaN
724    NaN     NaN    NaN    NaN     NaN

[725 rows x 5 columns]
ATOM    0.274908
BAT     0.214413
ZEC     0.240497
QTUM    0.211186
ZRX     0.109141
Name: 232, dtype: float64
報酬 0.21002874031885535 %
i= ATOM    0.274908
BAT     0.214413
ZEC     0.240497
QTUM    0.211186
ZRX     0.109141
Name: 232, dtype: float64
熊式-----------------------------------
執行第 239
           239
ATOM -0.093923
BAT  -0.061224
XLM  -0.048997
ZRX  -0.047679
QTUM -0.043818
BNB  -0.038607
ZEC  -0.036044
NEO  -0.032267
ALGO -0.031447
TRX  -0.030962
ETH  -0.020009
BCH  -0.019474
ZIL  -0.017766
LINK -0.012987
XRP  -0.006699
ADA   0.002918
IOTA  0.011027
VET   0.023037
LTC   0.082287
ICX   0.167542
g================================================================       ATOM     BAT      XLM     ZRX   QTUM
0    3.258  0.1972  0.07442  0.1814  2.642
1    2.857  0.1682  0.06922  0.1624  2.347
2    2.898  0.1870  0.07019  0.1736  2.376
3    2.884  0.1788  0.06851  0.1751  2.291
4    2.910  0.1764  0.06770  0.1711  2.455
..     ...     ...      ...     ...    ...
720    NaN     NaN      NaN     NaN    NaN
721    NaN     NaN      NaN     NaN    NaN
722    NaN     NaN      NaN     NaN    NaN
723    NaN     NaN      NaN     NaN    NaN
724    NaN     NaN      NaN     NaN    NaN

[725 rows x 5 columns]
ATOM    0.202882
BAT     0.016616
XLM     0.011142
ZRX    -0.093023
QTUM   -0.017516
Name: 233, dtype: float64
報酬 0.024020335894037757 %
i= ATOM    0.202882
BAT     0.016616
XLM     0.011142
ZRX    -0.093023
QTUM   -0.017516
Name: 233, dtype: float64
熊式-----------------------------------
執行第 240
           240
ATOM -0.005020
XLM   0.021535
ALGO  0.027308
BAT   0.030086
ZRX   0.031417
XRP   0.032475
ZEC   0.040013
QTUM  0.053156
BNB   0.057583
TRX   0.066905
ZIL   0.067385
NEO   0.073130
LINK  0.074766
VET   0.076000
ETH   0.077866
IOTA  0.085294
BCH   0.086107
ADA   0.107986
LTC   0.205894
ICX   0.288432
g================================================================       ATOM      XLM   ALGO     BAT     ZRX
0    3.258  0.07442  0.809  0.1972  0.1814
1    2.857  0.06922  0.717  0.1682  0.1624
2    2.898  0.07019  0.710  0.1870  0.1736
3    2.884  0.06851  0.677  0.1788  0.1751
4    2.910  0.06770  0.683  0.1764  0.1711
..     ...      ...    ...     ...     ...
720    NaN      NaN    NaN     NaN     NaN
721    NaN      NaN    NaN     NaN     NaN
722    NaN      NaN    NaN     NaN     NaN
723    NaN      NaN    NaN     NaN     NaN
724    NaN      NaN    NaN     NaN     NaN

[725 rows x 5 columns]
ATOM    0.178804
XLM     0.075877
ALGO    0.037992
BAT     0.103812
ZRX    -0.010835
Name: 234, dtype: float64
報酬 0.0771300389496132 %
i= ATOM    0.178804
XLM     0.075877
ALGO    0.037992
BAT     0.103812
ZRX    -0.010835
Name: 234, dtype: float64
熊式-----------------------------------
執行第 241
           241
ATOM  0.003551
XRP   0.023489
XLM   0.036045
ZRX   0.038770
BAT   0.040317
ZIL   0.044974
QTUM  0.046167
TRX   0.047410
ALGO  0.058039
NEO   0.059143
IOTA  0.070301
LINK  0.074766
ZEC   0.076087
ETH   0.077017
ADA   0.084706
BNB   0.097621
VET   0.098013
BCH   0.104210
LTC   0.167911
ICX   0.265551
g================================================================       ATOM      XRP      XLM     ZRX     BAT
0    3.258  0.29787  0.07442  0.1814  0.1972
1    2.857  0.26338  0.06922  0.1624  0.1682
2    2.898  0.26408  0.07019  0.1736  0.1870
3    2.884  0.26055  0.06851  0.1751  0.1788
4    2.910  0.26543  0.06770  0.1711  0.1764
..     ...      ...      ...     ...     ...
720    NaN      NaN      NaN     NaN     NaN
721    NaN      NaN      NaN     NaN     NaN
722    NaN      NaN      NaN     NaN     NaN
723    NaN      NaN      NaN     NaN     NaN
724    NaN      NaN      NaN     NaN     NaN

[725 rows x 5 columns]
ATOM   -0.001041
XRP    -0.034501
XLM    -0.029544
ZRX    -0.111742
BAT     0.003241
Name: 235, dtype: float64
報酬 -0.0347172995414111 %
i= ATOM   -0.001041
XRP    -0.034501
XLM    -0.029544
ZRX    -0.111742
BAT     0.003241
Name: 235, dtype: float64
熊式-----------------------------------
執行第 242
           242
LTC   0.022643
ZRX   0.083911
ATOM  0.092973
XLM   0.107815
XRP   0.111861
TRX   0.122889
BAT   0.124328
QTUM  0.131579
IOTA  0.139924
LINK  0.154229
ZIL   0.155807
ADA   0.155983
ETH   0.157387
BCH   0.159751
NEO   0.163295
ZEC   0.170861
VET   0.189080
BNB   0.217699
ALGO  0.235253
ICX   0.337060
g================================================================        LTC     ZRX   ATOM      XLM      XRP
0    56.59  0.1814  3.258  0.07442  0.29787
1    54.82  0.1624  2.857  0.06922  0.26338
2    56.60  0.1736  2.898  0.07019  0.26408
3    55.28  0.1751  2.884  0.06851  0.26055
4    55.88  0.1711  2.910  0.06770  0.26543
..     ...     ...    ...      ...      ...
720    NaN     NaN    NaN      NaN      NaN
721    NaN     NaN    NaN      NaN      NaN
722    NaN     NaN    NaN      NaN      NaN
723    NaN     NaN    NaN      NaN      NaN
724    NaN     NaN    NaN      NaN      NaN

[725 rows x 5 columns]
LTC    -0.035535
ZRX     0.097031
ATOM    0.261805
XLM     0.119352
XRP     0.128130
Name: 236, dtype: float64
報酬 0.11415677696858728 %
i= LTC    -0.035535
ZRX     0.097031
ATOM    0.261805
XLM     0.119352
XRP     0.128130
Name: 236, dtype: float64
熊式-----------------------------------
執行第 243
           243
ZRX   0.021277
LTC   0.026803
BAT   0.047346
XRP   0.048115
BCH   0.049841
IOTA  0.050919
QTUM  0.050961
ATOM  0.055754
LINK  0.061033
ZEC   0.064854
NEO   0.068362
ADA   0.075911
ETH   0.080594
XLM   0.087684
TRX   0.096859
VET   0.101909
ALGO  0.110537
ICX   0.124088
BNB   0.127677

ZIL   0.142480
g================================================================         ZRX    LTC     BAT      XRP     BCH
0    0.1814  56.59  0.1972  0.29787  334.09
1    0.1624  54.82  0.1682  0.26338  315.09
2    0.1736  56.60  0.1870  0.26408  316.10
3    0.1751  55.28  0.1788  0.26055  339.01
4    0.1711  55.88  0.1764  0.26543  330.12
..      ...    ...     ...      ...     ...
720     NaN    NaN     NaN      NaN     NaN
721     NaN    NaN     NaN      NaN     NaN
722     NaN    NaN     NaN      NaN     NaN
723     NaN    NaN     NaN      NaN     NaN
724     NaN    NaN     NaN      NaN     NaN

[725 rows x 5 columns]
ZRX    0.063815
LTC   -0.028865
BAT    0.304163
XRP    0.102841
BCH    0.244826
Name: 237, dtype: float64
報酬 0.13735615618349686 %
i= ZRX    0.063815
LTC   -0.028865
BAT    0.304163
XRP    0.102841
BCH    0.244826
Name: 237, dtype: float64
熊式-----------------------------------
執行第 244
           244
LTC  -0.025105
ZRX   0.108055
LINK  0.132743
XRP   0.141984
BAT   0.142756
NEO   0.154312
IOTA  0.156685
QTUM  0.171759
VET   0.172458
ADA   0.182266
BCH   0.183339
ICX   0.189330
TRX   0.191011
BNB   0.209562
ZEC   0.217152
ALGO  0.219481
XLM   0.226234
ZIL   0.232984
ATOM  0.233846
ETH   0.290114
g================================================================        LTC     ZRX  LINK      XRP     BAT
0    56.59  0.1814  2.42  0.29787  0.1972
1    54.82  0.1624  2.28  0.26338  0.1682
2    56.60  0.1736  2.42  0.26408  0.1870
3    55.28  0.1751  2.30  0.26055  0.1788
4    55.88  0.1711  2.40  0.26543  0.1764
..     ...     ...   ...      ...     ...
720    NaN     NaN   NaN      NaN     NaN
721    NaN     NaN   NaN      NaN     NaN
722    NaN     NaN   NaN      NaN     NaN
723    NaN     NaN   NaN      NaN     NaN
724    NaN     NaN   NaN      NaN     NaN

[725 rows x 5 columns]
LTC    -0.038015
ZRX     0.079670
LINK    0.158974
XRP     0.097109
BAT     0.238731
Name: 238, dtype: float64
報酬 0.10729404886735272 %
i= LTC    -0.038015
ZRX     0.079670
LINK    0.158974
XRP     0.097109
BAT     0.238731
Name: 238, dtype: float64
熊式-----------------------------------
執行第 245
           245
LTC   0.009352
ICX   0.013491
XRP   0.102252
ZRX   0.117260
IOTA  0.117928
QTUM  0.125205
BAT   0.128331
BCH   0.129495
NEO   0.134988
ADA   0.139994
TRX   0.148532
BNB   0.159843
ZEC   0.164909
ZIL   0.173127
XLM   0.188665
ATOM  0.192073
LINK  0.192982
ALGO  0.205195
ETH   0.213607
VET   0.227402
g================================================================        LTC     ICX      XRP     ZRX    IOTA
0    56.59  0.2002  0.29787  0.1814  0.2564
1    54.82  0.1862  0.26338  0.1624  0.2322
2    56.60  0.2011  0.26408  0.1736  0.2428
3    55.28  0.1925  0.26055  0.1751  0.2413
4    55.88  0.1975  0.26543  0.1711  0.2422
..     ...     ...      ...     ...     ...
720    NaN     NaN      NaN     NaN     NaN
721    NaN     NaN      NaN     NaN     NaN
722    NaN     NaN      NaN     NaN     NaN
723    NaN     NaN      NaN     NaN     NaN
724    NaN     NaN      NaN     NaN     NaN

[725 rows x 5 columns]
LTC    -0.022536
ICX     0.004796
XRP     0.070044
ZRX    -0.019680
IOTA   -0.026828
Name: 239, dtype: float64
報酬 0.001159390735696042 %
i= LTC    -0.022536
ICX     0.004796
XRP     0.070044
ZRX    -0.019680
IOTA   -0.026828
Name: 239, dtype: float64
熊式-----------------------------------
執行第 246
           246
ICX   0.009577
LTC   0.025444
XRP   0.132148
ADA   0.141022
NEO   0.144596
ZRX   0.149060
TRX   0.149666
BCH   0.153942
BAT   0.155772
BNB   0.157975
IOTA  0.165312
ZIL   0.169192
ZEC   0.173751
QTUM  0.182965
ETH   0.222513
VET   0.232032
XLM   0.241580
ATOM  0.256307
ALGO  0.290506
LINK  0.378261
g================================================================         ICX    LTC      XRP      ADA     NEO
0    0.2002  56.59  0.29787  0.05262  10.494
1    0.1862  54.82  0.26338  0.04715   9.427
2    0.2011  56.60  0.26408  0.04733   9.897
3    0.1925  55.28  0.26055  0.04668   9.818
4    0.1975  55.88  0.26543  0.04740   9.663
..      ...    ...      ...      ...     ...
720     NaN    NaN      NaN      NaN     NaN
721     NaN    NaN      NaN      NaN     NaN
722     NaN    NaN      NaN      NaN     NaN
723     NaN    NaN      NaN      NaN     NaN
724     NaN    NaN      NaN      NaN     NaN

[725 rows x 5 columns]
ICX   -0.040454
LTC   -0.055841
XRP    0.100529
ADA   -0.023729
NEO    0.037126
Name: 240, dtype: float64
報酬 0.003526040332097602 %
i= ICX   -0.040454
LTC   -0.055841
XRP    0.100529
ADA   -0.023729
NEO    0.037126
Name: 240, dtype: float64
熊式-----------------------------------
執行第 247
           247
ICX   0.048327
BCH   0.084802
LTC   0.091239
XRP   0.104445
ADA   0.118376
BNB   0.121824
TRX   0.127410
NEO   0.142450
IOTA  0.156166
QTUM  0.163121
ZIL   0.177215
VET   0.185890
BAT   0.190311
ETH   0.200651
ZRX   0.220721
ZEC   0.247016
XLM   0.256101
ALGO  0.261034
ATOM  0.300809
LINK  0.439130
g================================================================         ICX     BCH    LTC      XRP      ADA
0    0.2002  334.09  56.59  0.29787  0.05262
1    0.1862  315.09  54.82  0.26338  0.04715
2    0.2011  316.10  56.60  0.26408  0.04733
3    0.1925  339.01  55.28  0.26055  0.04668
4    0.1975  330.12  55.88  0.26543  0.04740
..      ...     ...    ...      ...      ...
720     NaN     NaN    NaN      NaN      NaN
721     NaN     NaN    NaN      NaN      NaN
722     NaN     NaN    NaN      NaN      NaN
723     NaN     NaN    NaN      NaN      NaN
724     NaN     NaN    NaN      NaN      NaN

[725 rows x 5 columns]
ICX   -0.049205
BCH   -0.028976
LTC   -0.097943
XRP    0.110548
ADA    0.010530
Name: 241, dtype: float64
報酬 -0.011009139808917778 %
i= ICX   -0.049205
BCH   -0.028976
LTC   -0.097943
XRP    0.110548
ADA    0.010530
Name: 241, dtype: float64
熊式-----------------------------------
執行第 248
           248
ICX  -0.043478
BCH  -0.022342
BNB  -0.002907
ALGO  0.005618
NEO   0.015442
ADA   0.023413
ZIL   0.029412
XRP   0.035541
QTUM  0.040310
TRX   0.042607
IOTA  0.074716
ZRX   0.081254
ETH   0.096210
LTC   0.100412
BAT   0.106485
ZEC   0.111414
VET   0.112173
XLM   0.141081
ATOM  0.141939
LINK  0.387931
g================================================================         ICX     BCH    BNB   ALGO     NEO
0    0.2002  334.09  29.42  0.809  10.494
1    0.1862  315.09  27.01  0.717   9.427
2    0.2011  316.10  28.11  0.710   9.897
3    0.1925  339.01  27.53  0.677   9.818
4    0.1975  330.12  27.50  0.683   9.663
..      ...     ...    ...    ...     ...
720     NaN     NaN    NaN    NaN     NaN
721     NaN     NaN    NaN    NaN     NaN
722     NaN     NaN    NaN    NaN     NaN
723     NaN     NaN    NaN    NaN     NaN
724     NaN     NaN    NaN    NaN     NaN

[725 rows x 5 columns]
ICX    -0.026130
BCH     0.012826
BNB     0.010733
ALGO   -0.011660
NEO     0.040061
Name: 242, dtype: float64
報酬 0.005166050730248628 %
i= ICX    -0.026130
BCH     0.012826
BNB     0.010733
ALGO   -0.011660
NEO     0.040061
Name: 242, dtype: float64
熊式-----------------------------------
執行第 249
           249
ZIL  -0.013857
TRX  -0.005569
ICX  -0.002165
BNB   0.008766
BCH   0.009694
NEO   0.041186
ALGO  0.044820
ADA   0.048918
XRP   0.052153
LTC   0.054439
QTUM  0.072337
IOTA  0.078735
BAT   0.106164
ETH   0.109701
ZEC   0.113504
ZRX   0.116536
ATOM  0.118217
VET   0.138262
XLM   0.143087
LINK  0.455752
g================================================================          ZIL      TRX     ICX    BNB     BCH
0    0.00879  0.02049  0.2002  29.42  334.09
1    0.00762  0.01778  0.1862  27.01  315.09
2    0.00749  0.01752  0.2011  28.11  316.10
3    0.00732  0.01688  0.1925  27.53  339.01
4    0.00773  0.01692  0.1975  27.50  330.12
..       ...      ...     ...    ...     ...
720      NaN      NaN     NaN    NaN     NaN
721      NaN      NaN     NaN    NaN     NaN
722      NaN      NaN     NaN    NaN     NaN
723      NaN      NaN     NaN    NaN     NaN
724      NaN      NaN     NaN    NaN     NaN

[725 rows x 5 columns]
ZIL   -0.023196
TRX    0.008803
ICX    0.032145
BNB   -0.004102
BCH   -0.005243
Name: 243, dtype: float64
報酬 0.001681433584702252 %
i= ZIL   -0.023196
TRX    0.008803
ICX    0.032145
BNB   -0.004102
BCH   -0.005243
Name: 243, dtype: float64
熊式-----------------------------------
執行第 250
           250
ZIL  -0.106157
BCH  -0.097661
TRX  -0.079826
ICX  -0.077809
ETH  -0.075464
ADA  -0.071111
BNB  -0.059289
NEO  -0.058462
ALGO -0.053781
ATOM -0.045719
XRP  -0.045583
QTUM -0.041579
ZEC  -0.037224
IOTA -0.030704
XLM  -0.022035
BAT  -0.011750
ZRX  -0.008865
VET   0.011251
LTC   0.037597
LINK  0.332031
g================================================================          ZIL     BCH      TRX     ICX     ETH
0    0.00879  334.09  0.02049  0.2002  209.22
1    0.00762  315.09  0.01778  0.1862  187.11
2    0.00749  316.10  0.01752  0.2011  188.16
3    0.00732  339.01  0.01688  0.1925  185.03
4    0.00773  330.12  0.01692  0.1975  185.61
..       ...     ...      ...     ...     ...
720      NaN     NaN      NaN     NaN     NaN
721      NaN     NaN      NaN     NaN     NaN
722      NaN     NaN      NaN     NaN     NaN
723      NaN     NaN      NaN     NaN     NaN
724      NaN     NaN      NaN     NaN     NaN

[725 rows x 5 columns]
ZIL   -0.027990
BCH   -0.040241
TRX    0.005213
ICX    0.013882
ETH   -0.040945
Name: 244, dtype: float64
報酬 -0.018016054033105265 %
i= ZIL   -0.027990
BCH   -0.040241
TRX    0.005213
ICX    0.013882
ETH   -0.040945
Name: 244, dtype: float64
熊式-----------------------------------
執行第 251
           251
BCH  -0.114887
ZIL  -0.094714
ICX  -0.080678
VET  -0.067442
ADA  -0.060976
NEO  -0.057720
TRX  -0.054887
ALGO -0.054418
ETH  -0.050471
ATOM -0.037084
IOTA -0.030488
XRP  -0.026808
QTUM -0.024727
ZEC  -0.019204
BAT  -0.016781
ZRX  -0.013561
XLM  -0.005986
BNB   0.019688
LTC   0.064516
LINK  0.238971
g================================================================         BCH      ZIL     ICX       VET      ADA
0    334.09  0.00879  0.2002  0.004916  0.05262
1    315.09  0.00762  0.1862  0.004628  0.04715
2    316.10  0.00749  0.2011  0.004580  0.04733
3    339.01  0.00732  0.1925  0.004493  0.04668
4    330.12  0.00773  0.1975  0.004454  0.04740
..      ...      ...     ...       ...      ...
720     NaN      NaN     NaN       NaN      NaN
721     NaN      NaN     NaN       NaN      NaN
722     NaN      NaN     NaN       NaN      NaN
723     NaN      NaN     NaN       NaN      NaN
724     NaN      NaN     NaN       NaN      NaN

[725 rows x 5 columns]
BCH    0.013464
ZIL   -0.002577
ICX    0.189689
VET    0.031741
ADA    0.050255
Name: 245, dtype: float64

報酬 0.05651415905625314 %
i= BCH    0.013464
ZIL   -0.002577
ICX    0.189689
VET    0.031741
ADA    0.050255
Name: 245, dtype: float64
熊式-----------------------------------
執行第 252
           252
BCH  -0.165981
ALGO -0.125552
QTUM -0.114000
ZIL  -0.105832
ICX  -0.098814
TRX  -0.094545
NEO  -0.092308
ADA  -0.090909
ETH  -0.085085
IOTA -0.081977
XRP  -0.078691
VET  -0.078200
XLM  -0.062256
ZEC  -0.061327
ATOM -0.053012
ZRX  -0.037225
BAT  -0.005415
LINK  0.025237
BNB   0.033775
LTC   0.039504
g================================================================         BCH   ALGO   QTUM      ZIL     ICX
0    334.09  0.809  2.642  0.00879  0.2002
1    315.09  0.717  2.347  0.00762  0.1862
2    316.10  0.710  2.376  0.00749  0.2011
3    339.01  0.677  2.291  0.00732  0.1925
4    330.12  0.683  2.455  0.00773  0.1975
..      ...    ...    ...      ...     ...
720     NaN    NaN    NaN      NaN     NaN
721     NaN    NaN    NaN      NaN     NaN
722     NaN    NaN    NaN      NaN     NaN
723     NaN    NaN    NaN      NaN     NaN
724     NaN    NaN    NaN      NaN     NaN

[725 rows x 5 columns]
BCH     0.016272
ALGO   -0.006289
QTUM   -0.007825
ZIL     0.005076
ICX     0.196181
Name: 246, dtype: float64
報酬 0.04068308437881305 %
i= BCH     0.016272
ALGO   -0.006289
QTUM   -0.007825
ZIL     0.005076
ICX     0.196181
Name: 246, dtype: float64
熊式-----------------------------------
執行第 253
           253
BCH  -0.160250
ALGO -0.156500
IOTA -0.141449
ZIL  -0.139785
ZEC  -0.138930
ZRX  -0.137059
ICX  -0.132782
NEO  -0.128055
QTUM -0.122629
ATOM -0.117761
ADA  -0.117484
XLM  -0.113868
ETH  -0.098950
BAT  -0.097674
TRX  -0.093680
XRP  -0.089474
LINK -0.057402
VET  -0.053802
BNB  -0.029314
LTC  -0.021378
g================================================================         BCH   ALGO    IOTA      ZIL    ZEC
0    334.09  0.809  0.2564  0.00879  55.45
1    315.09  0.717  0.2322  0.00762  50.56
2    316.10  0.710  0.2428  0.00749  50.57
3    339.01  0.677  0.2413  0.00732  48.85
4    330.12  0.683  0.2422  0.00773  50.01
..      ...    ...     ...      ...    ...
720     NaN    NaN     NaN      NaN    NaN
721     NaN    NaN     NaN      NaN    NaN
722     NaN    NaN     NaN      NaN    NaN
723     NaN    NaN     NaN      NaN    NaN
724     NaN    NaN     NaN      NaN    NaN

[725 rows x 5 columns]
BCH     0.106590
ALGO    0.031209
IOTA    0.097059
ZIL     0.064690
ZEC     0.054211
Name: 247, dtype: float64
報酬 0.07075193363196855 %
i= BCH     0.106590
ALGO    0.031209
IOTA    0.097059
ZIL     0.064690
ZEC     0.054211
Name: 247, dtype: float64
熊式-----------------------------------
執行第 254
           254
LTC  -0.042427
IOTA -0.024209
BCH   0.009407
XRP   0.015828
ZIL   0.019048
BAT   0.019741
ZRX   0.024852
ICX   0.028409
XLM   0.030176
ALGO  0.036872
ADA   0.037327
TRX   0.043269
NEO   0.043431
QTUM  0.045455
ATOM  0.045474
ZEC   0.055571
VET   0.060682
LINK  0.080745
ETH   0.091692
BNB   0.145773
g================================================================        LTC    IOTA     BCH      XRP      ZIL
0    56.59  0.2564  334.09  0.29787  0.00879
1    54.82  0.2322  315.09  0.26338  0.00762
2    56.60  0.2428  316.10  0.26408  0.00749
3    55.28  0.2413  339.01  0.26055  0.00732
4    55.88  0.2422  330.12  0.26543  0.00773
..     ...     ...     ...      ...      ...
720    NaN     NaN     NaN      NaN      NaN
721    NaN     NaN     NaN      NaN      NaN
722    NaN     NaN     NaN      NaN      NaN
723    NaN     NaN     NaN      NaN      NaN
724    NaN     NaN     NaN      NaN      NaN

[725 rows x 5 columns]
LTC     0.175782
IOTA    0.075323
BCH     0.113751
XRP     0.033067
ZIL     0.079365
Name: 248, dtype: float64
報酬 0.0954576747758821 %
i= LTC     0.175782
IOTA    0.075323
BCH     0.113751
XRP     0.033067
ZIL     0.079365
Name: 248, dtype: float64
熊式-----------------------------------
執行第 255
           255
IOTA -0.026201
XLM  -0.024312
ZIL  -0.016393
LTC  -0.007655
BCH  -0.005786
XRP   0.000053
ZRX   0.004082
ICX   0.006941
BAT   0.021672
NEO   0.022037
QTUM  0.025204
ATOM  0.025563
ADA   0.026308
VET   0.027989
TRX   0.030400
ALGO  0.045682
LINK  0.048632
ETH   0.077317
ZEC   0.114088
BNB   0.131789
g================================================================        IOTA      XLM      ZIL    LTC     BCH
0    0.2564  0.07442  0.00879  56.59  334.09
1    0.2322  0.06922  0.00762  54.82  315.09
2    0.2428  0.07019  0.00749  56.60  316.10
3    0.2413  0.06851  0.00732  55.28  339.01
4    0.2422  0.06770  0.00773  55.88  330.12
..      ...      ...      ...    ...     ...
720     NaN      NaN      NaN    NaN     NaN
721     NaN      NaN      NaN    NaN     NaN
722     NaN      NaN      NaN    NaN     NaN
723     NaN      NaN      NaN    NaN     NaN
724     NaN      NaN      NaN    NaN     NaN

[725 rows x 5 columns]
IOTA    0.130038
XLM     0.153377
ZIL     0.226629
LTC     0.022117
BCH     0.125414
Name: 249, dtype: float64
報酬 0.1315150585992635 %
i= IOTA    0.130038
XLM     0.153377
ZIL     0.226629
LTC     0.022117
BCH     0.125414
Name: 249, dtype: float64
熊式-----------------------------------
執行第 256
           256
LTC  -0.023329
IOTA  0.010559
XRP   0.033585
XLM   0.035846
BCH   0.045618
ZIL   0.047506
QTUM  0.056618
TRX   0.056782
ICX   0.065002
ZRX   0.067979
NEO   0.070788
BAT   0.071965
VET   0.076798
ADA   0.092703
ATOM  0.092770
LINK  0.108504
ALGO  0.118739
ZEC   0.163491
BNB   0.163866
ETH   0.183701
g================================================================        LTC    IOTA      XRP      XLM     BCH
0    56.59  0.2564  0.29787  0.07442  334.09
1    54.82  0.2322  0.26338  0.06922  315.09
2    56.60  0.2428  0.26408  0.07019  316.10
3    55.28  0.2413  0.26055  0.06851  339.01
4    55.88  0.2422  0.26543  0.06770  330.12
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
LTC     0.027156
IOTA    0.174682
XRP     0.158141
XLM     0.247065
BCH     0.173285
Name: 250, dtype: float64
報酬 0.15606558496271322 %
i= LTC     0.027156
IOTA    0.174682
XRP     0.158141
XLM     0.247065
BCH     0.173285
Name: 250, dtype: float64
熊式-----------------------------------
執行第 257
           257
LTC  -0.071567
IOTA -0.020126
XRP   0.006287
XLM   0.013289
ZRX   0.023311
TRX   0.026253
ZIL   0.031630
BCH   0.034183
QTUM  0.037286
BAT   0.041087
ICX   0.041685
NEO   0.046285
ATOM  0.054006
LINK  0.068249
ALGO  0.068376
BNB   0.069241
ADA   0.072184
VET   0.081740
ETH   0.152040
ZEC   0.299021
g================================================================        LTC    IOTA      XRP      XLM     ZRX
0    56.59  0.2564  0.29787  0.07442  0.1814
1    54.82  0.2322  0.26338  0.06922  0.1624
2    56.60  0.2428  0.26408  0.07019  0.1736
3    55.28  0.2413  0.26055  0.06851  0.1751
4    55.88  0.2422  0.26543  0.06770  0.1711
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
LTC    -0.024603
IOTA    0.142061
XRP     0.111720
XLM     0.190125
ZRX     0.110675
Name: 251, dtype: float64
報酬 0.10599563562600392 %
i= LTC    -0.024603
IOTA    0.142061
XRP     0.111720
XLM     0.190125
ZRX     0.110675
Name: 251, dtype: float64
熊式-----------------------------------
執行第 258
           258
LTC  -0.084956
IOTA -0.061431
BAT  -0.053842
BNB  -0.041640
ATOM -0.036047
ZIL  -0.026570
ICX  -0.025439
XRP  -0.024296
ZRX  -0.017575
BCH  -0.017085
QTUM -0.013544
ALGO -0.010095
NEO  -0.007854
VET  -0.005728
TRX  -0.004016
ADA   0.025378
XLM   0.029344
LINK  0.055385
ETH   0.075447
ZEC   0.180231
g================================================================        LTC    IOTA     BAT    BNB   ATOM
0    56.59  0.2564  0.1972  29.42  3.258
1    54.82  0.2322  0.1682  27.01  2.857
2    56.60  0.2428  0.1870  28.11  2.898
3    55.28  0.2413  0.1788  27.53  2.884
4    55.88  0.2422  0.1764  27.50  2.910
..     ...     ...     ...    ...    ...
720    NaN     NaN     NaN    NaN    NaN
721    NaN     NaN     NaN    NaN    NaN
722    NaN     NaN     NaN    NaN    NaN
723    NaN     NaN     NaN    NaN    NaN
724    NaN     NaN     NaN    NaN    NaN

[725 rows x 5 columns]
LTC     0.060963
IOTA    0.172461
BAT     0.165498
BNB     0.188976
ATOM    0.265244
Name: 252, dtype: float64
報酬 0.170628383654554 %
i= LTC     0.060963
IOTA    0.172461
BAT     0.165498
BNB     0.188976
ATOM    0.265244
Name: 252, dtype: float64
熊式-----------------------------------
執行第 259
           259
LTC  -0.042557
ATOM  0.000881
VET   0.005194
QTUM  0.015444
XRP   0.015953
BAT   0.017397
ICX   0.019991
BCH   0.020273
TRX   0.024610
IOTA  0.024983
ZRX   0.028100
ZIL   0.030000
NEO   0.033891
BNB   0.037062
ALGO  0.052756
ADA   0.084458
XLM   0.103755
LINK  0.108974
ETH   0.117147
ZEC   0.199544
g================================================================        LTC   ATOM       VET   QTUM      XRP
0    56.59  3.258  0.004916  2.642  0.29787
1    54.82  2.857  0.004628  2.347  0.26338
2    56.60  2.898  0.004580  2.376  0.26408
3    55.28  2.884  0.004493  2.291  0.26055
4    55.88  2.910  0.004454  2.455  0.26543
..     ...    ...       ...    ...      ...
720    NaN    NaN       NaN    NaN      NaN
721    NaN    NaN       NaN    NaN      NaN
722    NaN    NaN       NaN    NaN      NaN
723    NaN    NaN       NaN    NaN      NaN
724    NaN    NaN       NaN    NaN      NaN

[725 rows x 5 columns]
LTC     0.057081
ATOM    0.298184
VET     0.197646
QTUM    0.164038
XRP     0.111628
Name: 253, dtype: float64
報酬 0.1657151918933813 %
i= LTC     0.057081
ATOM    0.298184
VET     0.197646
QTUM    0.164038
XRP     0.111628
Name: 253, dtype: float64
熊式-----------------------------------
執行第 260
           260
LTC  -0.090568
QTUM -0.025659
ZIL  -0.014019
XRP  -0.013588
ZRX  -0.012125
ATOM -0.010771
NEO  -0.010767
BCH  -0.008639
IOTA -0.006997
TRX  -0.004608
BNB  -0.000636
BAT   0.000000
ICX   0.008075
ALGO  0.008621
VET   0.017241
LINK  0.057471
ETH   0.060151
ADA   0.063262
XLM   0.117372
ZEC   0.174710
g================================================================        LTC   QTUM      ZIL      XRP     ZRX
0    56.59  2.642  0.00879  0.29787  0.1814
1    54.82  2.347  0.00762  0.26338  0.1624
2    56.60  2.376  0.00749  0.26408  0.1736
3    55.28  2.291  0.00732  0.26055  0.1751
4    55.88  2.455  0.00773  0.26543  0.1711
..     ...    ...      ...      ...     ...
720    NaN    NaN      NaN      NaN     NaN
721    NaN    NaN      NaN      NaN     NaN
722    NaN    NaN      NaN      NaN     NaN
723    NaN    NaN      NaN      NaN     NaN
724    NaN    NaN      NaN      NaN     NaN

[725 rows x 5 columns]
LTC     0.107828
QTUM    0.057526
ZIL     0.063291
XRP     0.045232
ZRX     0.087516
Name: 254, dtype: float64
報酬 0.07227849132548977 %
i= LTC     0.107828
QTUM    0.057526
ZIL     0.063291
XRP     0.045232
ZRX     0.087516
Name: 254, dtype: float64
熊式-----------------------------------
執行第 261
           261
LTC  -0.095191
QTUM  0.005061
BAT   0.014545
ZRX   0.018002
IOTA  0.018578
XRP   0.020515
BCH   0.023539
ATOM  0.025349
BNB   0.026871
ZIL   0.030952
ALGO  0.039425
VET   0.044674
NEO   0.051025
TRX   0.056677
ICX   0.070659
LINK  0.086957
ETH   0.087716
ZEC   0.102901
ADA   0.189339
XLM   0.278418
g================================================================        LTC   QTUM     BAT     ZRX    IOTA
0    56.59  2.642  0.1972  0.1814  0.2564
1    54.82  2.347  0.1682  0.1624  0.2322
2    56.60  2.376  0.1870  0.1736  0.2428
3    55.28  2.291  0.1788  0.1751  0.2413
4    55.88  2.455  0.1764  0.1711  0.2422
..     ...    ...     ...     ...     ...
720    NaN    NaN     NaN     NaN     NaN
721    NaN    NaN     NaN     NaN     NaN
722    NaN    NaN     NaN     NaN     NaN
723    NaN    NaN     NaN     NaN     NaN
724    NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
LTC     0.053896
QTUM    0.045736
BAT     0.102389
ZRX     0.097249
IOTA    0.069380
Name: 255, dtype: float64
報酬 0.07373006123337626 %
i= LTC     0.053896
QTUM    0.045736
BAT     0.102389
ZRX     0.097249
IOTA    0.069380
Name: 255, dtype: float64
熊式-----------------------------------
執行第 262
           262
LTC  -0.068609
BNB  -0.042720
BCH  -0.024831
XRP  -0.011770
QTUM -0.007655
LINK -0.002646
ETH   0.000427
NEO   0.023982
VET   0.028730
IOTA  0.030731
BAT   0.032107
ZRX   0.035734
TRX   0.038060
ZEC   0.046048
ALGO  0.051308
ZIL   0.054422
ICX   0.071140
ATOM  0.095257
ADA   0.139847
XLM   0.209808
g================================================================        LTC    BNB     BCH      XRP   QTUM
0    56.59  29.42  334.09  0.29787  2.642
1    54.82  27.01  315.09  0.26338  2.347
2    56.60  28.11  316.10  0.26408  2.376
3    55.28  27.53  339.01  0.26055  2.291
4    55.88  27.50  330.12  0.26543  2.455
..     ...    ...     ...      ...    ...
720    NaN    NaN     NaN      NaN    NaN
721    NaN    NaN     NaN      NaN    NaN
722    NaN    NaN     NaN      NaN    NaN
723    NaN    NaN     NaN      NaN    NaN
724    NaN    NaN     NaN      NaN    NaN

[725 rows x 5 columns]
LTC     0.037953
BNB     0.043097
BCH     0.008439
XRP     0.054607
QTUM    0.081081
Name: 256, dtype: float64
報酬 0.04503549936671893 %
i= LTC     0.037953
BNB     0.043097
BCH     0.008439
XRP     0.054607
QTUM    0.081081
Name: 256, dtype: float64
熊式-----------------------------------
執行第 263
           263
LTC  -0.121007
ZEC  -0.037468
BNB   0.010585
XRP   0.028169
BCH   0.030068
LINK  0.052778
QTUM  0.065421
ZRX   0.078271
ETH   0.078285
VET   0.079918
TRX   0.081395
IOTA  0.091142
NEO   0.106327
BAT   0.108682
ALGO  0.124267
ZIL   0.129717
ICX   0.146588
ADA   0.189577
ATOM  0.205796
XLM   0.265779
g================================================================        LTC    ZEC    BNB      XRP     BCH
0    56.59  55.45  29.42  0.29787  334.09
1    54.82  50.56  27.01  0.26338  315.09
2    56.60  50.57  28.11  0.26408  316.10
3    55.28  48.85  27.53  0.26055  339.01
4    55.88  50.01  27.50  0.26543  330.12
..     ...    ...    ...      ...     ...
720    NaN    NaN    NaN      NaN     NaN
721    NaN    NaN    NaN      NaN     NaN
722    NaN    NaN    NaN      NaN     NaN
723    NaN    NaN    NaN      NaN     NaN
724    NaN    NaN    NaN      NaN     NaN

[725 rows x 5 columns]
LTC    0.065064
ZEC   -0.049455
BNB   -0.010540
XRP   -0.052600
BCH   -0.134526
Name: 257, dtype: float64
報酬 -0.03641129167944117 %
i= LTC    0.065064
ZEC   -0.049455
BNB   -0.010540
XRP   -0.052600
BCH   -0.134526
Name: 257, dtype: float64
熊式-----------------------------------
執行第 264
           264
LTC  -0.187232
ZEC   0.063708
XRP   0.080707
LINK  0.084548
BNB   0.093583
BCH   0.123409
TRX   0.149194
ETH   0.157978
QTUM  0.169336
BAT   0.177749
ZRX   0.184258
IOTA  0.190283
NEO   0.198194
VET   0.226612
ATOM  0.235812
XLM   0.252729
ZIL   0.258065
ALGO  0.277620
ICX   0.343384
ADA   0.353270
g================================================================        LTC    ZEC      XRP  LINK    BNB
0    56.59  55.45  0.29787  2.42  29.42
1    54.82  50.56  0.26338  2.28  27.01
2    56.60  50.57  0.26408  2.42  28.11
3    55.28  48.85  0.26055  2.30  27.53
4    55.88  50.01  0.26543  2.40  27.50
..     ...    ...      ...   ...    ...
720    NaN    NaN      NaN   NaN    NaN
721    NaN    NaN      NaN   NaN    NaN
722    NaN    NaN      NaN   NaN    NaN
723    NaN    NaN      NaN   NaN    NaN
724    NaN    NaN      NaN   NaN    NaN

[725 rows x 5 columns]
LTC     0.092656
ZEC    -0.025789
XRP    -0.035312
LINK    0.194853
BNB     0.059742
Name: 258, dtype: float64
報酬 0.057229987264910284 %
i= LTC     0.092656
ZEC    -0.025789
XRP    -0.035312
LINK    0.194853
BNB     0.059742
Name: 258, dtype: float64
熊式-----------------------------------
執行第 265
           265
LTC  -0.187426
LINK  0.052023
ZEC   0.056559
XRP   0.076768
BNB   0.086698
BCH   0.105414
QTUM  0.144487
IOTA  0.146245
BAT   0.146928
ETH   0.150908
TRX   0.162530
NEO   0.165422
VET   0.184661
ATOM  0.217870
ALGO  0.220721
ZIL   0.220874
ZRX   0.227570
ICX   0.294878
XLM   0.323894
ADA   0.346265
g================================================================        LTC  LINK    ZEC      XRP    BNB
0    56.59  2.42  55.45  0.29787  29.42
1    54.82  2.28  50.56  0.26338  27.01
2    56.60  2.42  50.57  0.26408  28.11
3    55.28  2.30  48.85  0.26055  27.53
4    55.88  2.40  50.01  0.26543  27.50
..     ...   ...    ...      ...    ...
720    NaN   NaN    NaN      NaN    NaN
721    NaN   NaN    NaN      NaN    NaN
722    NaN   NaN    NaN      NaN    NaN
723    NaN   NaN    NaN      NaN    NaN
724    NaN   NaN    NaN      NaN    NaN

[725 rows x 5 columns]
LTC     0.008815
LINK   -0.015773
ZEC    -0.072694
XRP    -0.105977
BNB    -0.035099
Name: 259, dtype: float64
報酬 -0.04414565386260272 %
i= LTC     0.008815
LINK   -0.015773
ZEC    -0.072694
XRP    -0.105977
BNB    -0.035099
Name: 259, dtype: float64
熊式-----------------------------------
執行第 266
           266
LTC  -0.214759
ZEC  -0.018893
LINK -0.008152
BCH   0.036659
BNB   0.040102
ETH   0.076161
VET   0.104263
BAT   0.111313
IOTA  0.114670
QTUM  0.118508
NEO   0.124768
XRP   0.141421
ALGO  0.153312
ATOM  0.169598
ZIL   0.180095
TRX   0.180556
ZRX   0.189363
ICX   0.193929
XLM   0.247952
ADA   0.277020
g================================================================        LTC    ZEC  LINK     BCH    BNB
0    56.59  55.45  2.42  334.09  29.42
1    54.82  50.56  2.28  315.09  27.01
2    56.60  50.57  2.42  316.10  28.11
3    55.28  48.85  2.30  339.01  27.53
4    55.88  50.01  2.40  330.12  27.50
..     ...    ...   ...     ...    ...
720    NaN    NaN   NaN     NaN    NaN
721    NaN    NaN   NaN     NaN    NaN
722    NaN    NaN   NaN     NaN    NaN
723    NaN    NaN   NaN     NaN    NaN
724    NaN    NaN   NaN     NaN    NaN

[725 rows x 5 columns]
LTC    -0.027870
ZEC    -0.048846
LINK    0.051360
BCH    -0.082429
BNB     0.047302
Name: 260, dtype: float64
報酬 -0.012096783290609902 %
i= LTC    -0.027870
ZEC    -0.048846
LINK    0.051360
BCH    -0.082429
BNB     0.047302
Name: 260, dtype: float64
牛式===============================
執行第 267
           267
LTC  -0.173408
LINK  0.034667
ZEC   0.055306
BNB   0.083489
BCH   0.084955
BAT   0.158303
ETH   0.161555
XLM   0.161888
IOTA  0.168553
NEO   0.174057
QTUM  0.174820
XRP   0.175160
ALGO  0.179908
TRX   0.191036
ICX   0.202817
VET   0.204706
ATOM  0.206840
ZRX   0.217912
ZIL   0.240185
ADA   0.260103
g================================================================          VET    ATOM     ZRX      ZIL     ADA
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.08348  12.946  0.7889  0.08133  1.4039
721  0.07614  11.958  0.8190  0.07509  1.3327
722  0.07704  13.182  0.8384  0.07496  1.3497
723  0.07591  14.395  0.7890  0.07299  1.3356
724  0.07768  14.064  0.7950  0.07377  1.3478

[725 rows x 5 columns]
VET     0.066879
ATOM   -0.005095
ZRX     0.068464
ZIL     0.189247
ADA     0.142137
Name: 261, dtype: float64
報酬 0.09232642901129844 %
i= VET     0.066879
ATOM   -0.005095
ZRX     0.068464
ZIL     0.189247
ADA     0.142137
Name: 261, dtype: float64
牛式===============================
執行第 268
           268
LTC  -0.146781
LINK -0.018568
ATOM -0.005095
ALGO  0.001435
ZEC   0.015657
BAT   0.038462
ICX   0.051321
BCH   0.052399
IOTA  0.052475
VET   0.066879
ZRX   0.068464
BNB   0.069767
QTUM  0.077139
TRX   0.092739
XRP   0.094604
ETH   0.101764
NEO   0.102478
XLM   0.103138
ADA   0.142137
ZIL   0.189247
g================================================================          ETH     NEO      XLM     ADA      ZIL
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  2316.15  37.005  0.25677  1.4039  0.08133
721  2121.52  34.083  0.24383  1.3327  0.07509
722  2146.27  34.637  0.24550  1.3497  0.07496
723  2111.19  34.057  0.24484  1.3356  0.07299
724  2138.86  34.191  0.24587  1.3478  0.07377

[725 rows x 5 columns]
ETH    0.091808
NEO    0.069174
XLM    0.177271
ADA    0.205778
ZIL    0.242171
Name: 262, dtype: float64
報酬 0.15724032216968964 %
i= ETH    0.091808
NEO    0.069174
XLM    0.177271
ADA    0.205778
ZIL    0.242171
Name: 262, dtype: float64
牛式===============================
執行第 269
           269
LTC  -0.058266
ATOM -0.014977
LINK -0.007916
ALGO  0.014706
ZEC   0.021924
BAT   0.027382
ICX   0.042248
VET   0.052182
IOTA  0.068235
NEO   0.069174
BCH   0.069218
QTUM  0.069501
BNB   0.075786
ETH   0.091808
XRP   0.121022
TRX   0.133333
ZRX   0.156555
XLM   0.177271
ADA   0.205778
ZIL   0.242171
g================================================================          TRX     ZRX      XLM     ADA      ZIL
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  0.06432  0.7889  0.25677  1.4039  0.08133
721  0.06111  0.8190  0.24383  1.3327  0.07509
722  0.06219  0.8384  0.24550  1.3497  0.07496
723  0.06139  0.7890  0.24484  1.3356  0.07299
724  0.06184  0.7950  0.24587  1.3478  0.07377

[725 rows x 5 columns]
TRX    0.147368
ZRX    0.078550
XLM    0.218528
ADA    0.108208
ZIL    0.224852
Name: 263, dtype: float64
報酬 0.1555013132922288 %

i= TRX    0.147368
ZRX    0.078550
XLM    0.218528
ADA    0.108208
ZIL    0.224852
Name: 263, dtype: float64
牛式===============================
執行第 270
           270
ALGO -0.029712
ICX  -0.026466
LTC  -0.012035
VET   0.009618
ATOM  0.023140
LINK  0.026882
BAT   0.036374
ZEC   0.043069
BCH   0.059454
NEO   0.069317
QTUM  0.071102
BNB   0.071516
ZRX   0.078550
ETH   0.084309
IOTA  0.084467
ADA   0.108208
XRP   0.140898
TRX   0.147368
XLM   0.218528
ZIL   0.224852
g================================================================         ADA     XRP      TRX      XLM      ZIL
0       NaN     NaN      NaN      NaN      NaN
1       NaN     NaN      NaN      NaN      NaN
2       NaN     NaN      NaN      NaN      NaN
3       NaN     NaN      NaN      NaN      NaN
4       NaN     NaN      NaN      NaN      NaN
..      ...     ...      ...      ...      ...
720  1.4039  0.6521  0.06432  0.25677  0.08133
721  1.3327  0.6236  0.06111  0.24383  0.07509
722  1.3497  0.6372  0.06219  0.24550  0.07496
723  1.3356  0.6251  0.06139  0.24484  0.07299
724  1.3478  0.6362  0.06184  0.24587  0.07377

[725 rows x 5 columns]
ADA    0.054409
XRP    0.110588
TRX    0.101240
XLM    0.084373
ZIL    0.204771
Name: 264, dtype: float64
報酬 0.11107613288106308 %
i= ADA    0.054409
XRP    0.110588
TRX    0.101240
XLM    0.084373
ZIL    0.204771
Name: 264, dtype: float64
牛式===============================
執行第 271
           271
ICX  -0.058136
ALGO -0.052122
VET  -0.005280
ZRX  -0.001452
ATOM  0.002530
ZEC   0.007422
LTC   0.009983
LINK  0.019231
BAT   0.019879
BCH   0.037765
BNB   0.042022
IOTA  0.050000
QTUM  0.052492
ADA   0.054409
ETH   0.067698
NEO   0.076311
XLM   0.084373
TRX   0.101240
XRP   0.110588
ZIL   0.204771
g================================================================         NEO      XLM      TRX     XRP      ZIL
0       NaN      NaN      NaN     NaN      NaN
1       NaN      NaN      NaN     NaN      NaN
2       NaN      NaN      NaN     NaN      NaN
3       NaN      NaN      NaN     NaN      NaN
4       NaN      NaN      NaN     NaN      NaN
..      ...      ...      ...     ...      ...
720  37.005  0.25677  0.06432  0.6521  0.08133
721  34.083  0.24383  0.06111  0.6236  0.07509
722  34.637  0.24550  0.06219  0.6372  0.07496
723  34.057  0.24484  0.06139  0.6251  0.07299
724  34.191  0.24587  0.06184  0.6362  0.07377

[725 rows x 5 columns]
NEO    0.062662
XLM    0.069584
TRX    0.061438
XRP    0.016122
ZIL    0.425703
Name: 265, dtype: float64
報酬 0.12710189883053746 %
i= NEO    0.062662
XLM    0.069584
TRX    0.061438
XRP    0.016122
ZIL    0.425703
Name: 265, dtype: float64
牛式===============================
執行第 272
           272
ALGO -0.047707
ICX  -0.026836
ZEC  -0.014330
ATOM -0.011457
ZRX   0.002457
BAT   0.015242
XRP   0.016122
BCH   0.018385
QTUM  0.018967
LINK  0.027397
VET   0.034186
BNB   0.041616
ETH   0.050689
IOTA  0.051724
ADA   0.056636
TRX   0.061438
NEO   0.062662
XLM   0.069584
LTC   0.076870
ZIL   0.425703
g================================================================          TRX     NEO      XLM     LTC      ZIL
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  0.06432  37.005  0.25677  137.39  0.08133
721  0.06111  34.083  0.24383  132.25  0.07509
722  0.06219  34.637  0.24550  134.42  0.07496
723  0.06139  34.057  0.24484  134.00  0.07299
724  0.06184  34.191  0.24587  134.19  0.07377

[725 rows x 5 columns]
TRX   -0.019124
NEO   -0.012264
XLM    0.000555
LTC    0.041036
ZIL    0.541899
Name: 266, dtype: float64
報酬 0.11042036421257787 %
i= TRX   -0.019124
NEO   -0.012264
XLM    0.000555
LTC    0.041036
ZIL    0.541899
Name: 266, dtype: float64
牛式===============================
執行第 273
           273
ALGO -0.094266
ICX  -0.082302
ATOM -0.075794
VET  -0.071624
ZEC  -0.065403
LINK -0.051546
QTUM -0.050827
ETH  -0.047290
BAT  -0.041258
BCH  -0.040762
XRP  -0.040755
ADA  -0.038484
ZRX  -0.032787
BNB  -0.028752
TRX  -0.019124
NEO  -0.012264
XLM   0.000555
IOTA  0.009688
LTC   0.041036
ZIL   0.541899
g================================================================         NEO      XLM    IOTA     LTC      ZIL
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  37.005  0.25677  0.8896  137.39  0.08133
721  34.083  0.24383  0.8165  132.25  0.07509
722  34.637  0.24550  0.8180  134.42  0.07496
723  34.057  0.24484  0.7913  134.00  0.07299
724  34.191  0.24587  0.8404  134.19  0.07377

[725 rows x 5 columns]
NEO     0.028661
XLM     0.031116
IOTA    0.006799
LTC    -0.031123
ZIL     0.276673
Name: 267, dtype: float64
報酬 0.06242504015560486 %
i= NEO     0.028661
XLM     0.031116
IOTA    0.006799
LTC    -0.031123
ZIL     0.276673
Name: 267, dtype: float64
牛式===============================
執行第 274
           274
ICX  -0.062455
ALGO -0.060678
ZEC  -0.057194
ATOM -0.040600
ETH  -0.038030
BNB  -0.037603
BCH  -0.035193
LTC  -0.031123
LINK -0.029730
BAT  -0.029412
VET  -0.025718
QTUM -0.020833
XRP   0.000189
IOTA  0.006799
TRX   0.022368
NEO   0.028661
ADA   0.029010
XLM   0.031116
ZRX   0.060545
ZIL   0.276673
g================================================================         NEO     ADA      XLM     ZRX      ZIL
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  37.005  1.4039  0.25677  0.7889  0.08133
721  34.083  1.3327  0.24383  0.8190  0.07509
722  34.637  1.3497  0.24550  0.8384  0.07496
723  34.057  1.3356  0.24484  0.7890  0.07299
724  34.191  1.3478  0.24587  0.7950  0.07377

[725 rows x 5 columns]
NEO    0.097658
ADA    0.005499
XLM   -0.009076
ZRX    0.398126
ZIL    0.191597
Name: 268, dtype: float64
報酬 0.13676088678714807 %
i= NEO    0.097658
ADA    0.005499
XLM   -0.009076
ZRX    0.398126
ZIL    0.191597
Name: 268, dtype: float64
牛式===============================
執行第 275
           275
LTC  -0.061451
ALGO -0.046283
ATOM -0.036068
ZEC  -0.033056
BNB  -0.026919
BAT  -0.015458
ICX  -0.012689
BCH  -0.010410
XLM  -0.009076
ETH  -0.000660
LINK  0.000000
QTUM  0.001893
XRP   0.003721
ADA   0.005499
TRX   0.013915
IOTA  0.015969
VET   0.016231
NEO   0.097658
ZIL   0.191597
ZRX   0.398126
g================================================================        IOTA      VET     NEO      ZIL     ZRX
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.8896  0.08348  37.005  0.08133  0.7889
721  0.8165  0.07614  34.083  0.07509  0.8190
722  0.8180  0.07704  34.637  0.07496  0.8384
723  0.7913  0.07591  34.057  0.07299  0.7890
724  0.8404  0.07768  34.191  0.07377  0.7950

[725 rows x 5 columns]
IOTA    0.055933
VET     0.058706
NEO     0.228726
ZIL     0.130435
ZRX     0.840803
Name: 269, dtype: float64
報酬 0.2629206788705225 %
i= IOTA    0.055933
VET     0.058706
NEO     0.228726
ZIL     0.130435
ZRX     0.840803
Name: 269, dtype: float64
牛式===============================
執行第 276
           276
LTC  -0.045095
XLM  -0.038940
XRP  -0.022877
ATOM -0.022617
BNB  -0.022248
ETH  -0.011595
TRX  -0.005505
LINK -0.005236
ALGO -0.003199
BCH  -0.002607
ZEC   0.005591
QTUM  0.009744
ADA   0.021807
ICX   0.038541
IOTA  0.055933
VET   0.058706
ZIL   0.130435
BAT   0.192771
NEO   0.228726
ZRX   0.840803
g================================================================          VET      ZIL     BAT     NEO     ZRX
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.08348  0.08133  0.6135  37.005  0.7889
721  0.07614  0.07509  0.5691  34.083  0.8190
722  0.07704  0.07496  0.5695  34.637  0.8384
723  0.07591  0.07299  0.5575  34.057  0.7890
724  0.07768  0.07377  0.5623  34.191  0.7950

[725 rows x 5 columns]
VET    0.049158
ZIL    0.183168
BAT    0.178668
NEO    0.213695
ZRX    1.060107
Name: 270, dtype: float64
報酬 0.33695914011343503 %
i= VET    0.049158
ZIL    0.183168
BAT    0.178668
NEO    0.213695
ZRX    1.060107
Name: 270, dtype: float64
牛式===============================
執行第 277
           277
LTC  -0.077224
XLM  -0.021781
BNB  -0.016949
XRP  -0.013176
ATOM -0.008652
ETH   0.002288
ZEC   0.004689
QTUM  0.006313
TRX   0.007505
ALGO  0.039903
VET   0.049158
ADA   0.050173
BCH   0.054507
ICX   0.079255
IOTA  0.081007
LINK  0.083558
BAT   0.178668
ZIL   0.183168
NEO   0.213695
ZRX   1.060107
g================================================================       LINK     BAT      ZIL     NEO     ZRX
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  19.79  0.6135  0.08133  37.005  0.7889
721  18.44  0.5691  0.07509  34.083  0.8190
722  18.66  0.5695  0.07496  34.637  0.8384
723  18.20  0.5575  0.07299  34.057  0.7890
724  18.38  0.5623  0.07377  34.191  0.7950

[725 rows x 5 columns]
LINK    0.002667
BAT     0.052011
ZIL    -0.035211
NEO     0.080511
ZRX     0.947059
Name: 271, dtype: float64
報酬 0.20940715475383823 %
i= LINK    0.002667
BAT     0.052011
ZIL    -0.035211
NEO     0.080511
ZRX     0.947059
Name: 271, dtype: float64
牛式===============================
執行第 278
           278
XLM  -0.124386
TRX  -0.120690
BNB  -0.096945
XRP  -0.094557
ETH  -0.091019
ATOM -0.089460
QTUM -0.069961
ZEC  -0.068832
ALGO -0.066148
VET  -0.060715
BCH  -0.052736
ICX  -0.041727
LTC  -0.041093
ADA  -0.035801
ZIL  -0.035211
LINK  0.002667
IOTA  0.007104
BAT   0.052011
NEO   0.080511
ZRX   0.947059
g================================================================       LINK    IOTA     BAT     NEO     ZRX
0      NaN     NaN     NaN     NaN     NaN
1      NaN     NaN     NaN     NaN     NaN
2      NaN     NaN     NaN     NaN     NaN
3      NaN     NaN     NaN     NaN     NaN
4      NaN     NaN     NaN     NaN     NaN
..     ...     ...     ...     ...     ...
720  19.79  0.8896  0.6135  37.005  0.7889
721  18.44  0.8165  0.5691  34.083  0.8190
722  18.66  0.8180  0.5695  34.637  0.8384
723  18.20  0.7913  0.5575  34.057  0.7890
724  18.38  0.8404  0.5623  34.191  0.7950

[725 rows x 5 columns]
LINK   -0.021739
IOTA   -0.057569
BAT    -0.006993
NEO     0.057906
ZRX     0.681840
Name: 272, dtype: float64
報酬 0.13068889690943752 %
i= LINK   -0.021739
IOTA   -0.057569
BAT    -0.006993
NEO     0.057906
ZRX     0.681840
Name: 272, dtype: float64
牛式===============================
執行第 279
           279
ZIL  -0.150966
XLM  -0.129555
TRX  -0.120126
XRP  -0.112944
ATOM -0.111932
ALGO -0.103118
BNB  -0.103020
QTUM -0.096129
ETH  -0.092503
ZEC  -0.091406
VET  -0.070814
ICX  -0.070725
IOTA -0.057569
LTC  -0.048272
BCH  -0.047837
ADA  -0.034566
LINK -0.021739
BAT  -0.006993
NEO   0.057906
ZRX   0.681840

g================================================================         ADA   LINK     BAT     NEO     ZRX
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  1.4039  19.79  0.6135  37.005  0.7889
721  1.3327  18.44  0.5691  34.083  0.8190
722  1.3497  18.66  0.5695  34.637  0.8384
723  1.3356  18.20  0.5575  34.057  0.7890
724  1.3478  18.38  0.5623  34.191  0.7950

[725 rows x 5 columns]
ADA     0.029826
LINK    0.027855
BAT     0.163861
NEO     0.092767
ZRX     0.696955
Name: 273, dtype: float64
報酬 0.20225284524587378 %
i= ADA     0.029826
LINK    0.027855
BAT     0.163861
NEO     0.092767
ZRX     0.696955
Name: 273, dtype: float64
牛式===============================
執行第 280
           280
XRP  -0.067635
TRX  -0.062420
ATOM -0.052612
ETH  -0.045317
BNB  -0.037241
BCH  -0.033078
QTUM -0.023936
ALGO -0.016785
ZEC  -0.000237
VET   0.000236
LTC   0.001980
XLM   0.008766
ICX   0.009571
LINK  0.027855
ADA   0.029826
IOTA  0.046145
ZIL   0.079320
NEO   0.092767
BAT   0.163861
ZRX   0.696955
g================================================================        IOTA      ZIL     NEO     BAT     ZRX
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  0.08133  37.005  0.6135  0.7889
721  0.8165  0.07509  34.083  0.5691  0.8190
722  0.8180  0.07496  34.637  0.5695  0.8384
723  0.7913  0.07299  34.057  0.5575  0.7890
724  0.8404  0.07377  34.191  0.5623  0.7950

[725 rows x 5 columns]
IOTA    0.042818
ZIL     0.330042
NEO     0.038621
BAT     0.095831
ZRX     0.164154
Name: 274, dtype: float64
報酬 0.13429337822681328 %
i= IOTA    0.042818
ZIL     0.330042
NEO     0.038621
BAT     0.095831
ZRX     0.164154
Name: 274, dtype: float64
牛式===============================
執行第 281
           281
XRP  -0.076617
ATOM -0.069332
TRX  -0.064255
QTUM -0.061713
ETH  -0.057952
BCH  -0.049659
BNB  -0.045321
ALGO -0.042157
XLM  -0.032612
ICX  -0.031774
ZEC  -0.027394
VET  -0.010870
LTC  -0.006480
LINK  0.000000
ADA   0.006055
NEO   0.038621
IOTA  0.042818
BAT   0.095831
ZRX   0.164154
ZIL   0.330042
g================================================================         NEO    IOTA     BAT     ZRX      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  37.005  0.8896  0.6135  0.7889  0.08133
721  34.083  0.8165  0.5691  0.8190  0.07509
722  34.637  0.8180  0.5695  0.8384  0.07496
723  34.057  0.7913  0.5575  0.7890  0.07299
724  34.191  0.8404  0.5623  0.7950  0.07377

[725 rows x 5 columns]
NEO    -0.101544
IOTA    0.035644
BAT    -0.120334
ZRX    -0.131626
ZIL     0.490028
Name: 275, dtype: float64
報酬 0.03443374510723365 %
i= NEO    -0.101544
IOTA    0.035644
BAT    -0.120334
ZRX    -0.131626
ZIL     0.490028
Name: 275, dtype: float64
牛式===============================
執行第 282
           282
ZRX  -0.131626
BAT  -0.120334
ICX  -0.110338
NEO  -0.101544
ATOM -0.100036
ALGO -0.096745
ZEC  -0.076133
QTUM -0.073583
XRP  -0.067813
BCH  -0.067602
TRX  -0.060886
VET  -0.059636
XLM  -0.045480
BNB  -0.044341
ETH  -0.039499
ADA  -0.019612
LTC  -0.013205
LINK  0.002632
IOTA  0.035644
ZIL   0.490028
g================================================================         ADA     LTC   LINK    IOTA      ZIL
0       NaN     NaN    NaN     NaN      NaN
1       NaN     NaN    NaN     NaN      NaN
2       NaN     NaN    NaN     NaN      NaN
3       NaN     NaN    NaN     NaN      NaN
4       NaN     NaN    NaN     NaN      NaN
..      ...     ...    ...     ...      ...
720  1.4039  137.39  19.79  0.8896  0.08133
721  1.3327  132.25  18.44  0.8165  0.07509
722  1.3497  134.42  18.66  0.8180  0.07496
723  1.3356  134.00  18.20  0.7913  0.07299
724  1.3478  134.19  18.38  0.8404  0.07377

[725 rows x 5 columns]
ADA    -0.023500
LTC    -0.024771
LINK   -0.089552
IOTA    0.004051
ZIL     0.400279
Name: 276, dtype: float64
報酬 0.0533012738072081 %
i= ADA    -0.023500
LTC    -0.024771
LINK   -0.089552
IOTA    0.004051
ZIL     0.400279
Name: 276, dtype: float64
牛式===============================
執行第 283
           283
BCH  -0.114267
ATOM -0.102909
ZRX  -0.101176
ALGO -0.101076
LINK -0.089552
ICX  -0.089340
NEO  -0.088853
XRP  -0.084504
BAT  -0.083142
TRX  -0.076350
ETH  -0.073583
ZEC  -0.069556
BNB  -0.066587
QTUM -0.058344
XLM  -0.057975
VET  -0.037176
LTC  -0.024771
ADA  -0.023500
IOTA  0.004051
ZIL   0.400279
g================================================================          VET     LTC     ADA    IOTA      ZIL
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  0.08348  137.39  1.4039  0.8896  0.08133
721  0.07614  132.25  1.3327  0.8165  0.07509
722  0.07704  134.42  1.3497  0.8180  0.07496
723  0.07591  134.00  1.3356  0.7913  0.07299
724  0.07768  134.19  1.3478  0.8404  0.07377

[725 rows x 5 columns]
VET     0.065837
LTC    -0.035785
ADA     0.070065
IOTA    0.069452
ZIL     0.589781
Name: 277, dtype: float64
報酬 0.15186989388674182 %
i= VET     0.065837
LTC    -0.035785
ADA     0.070065
IOTA    0.069452
ZIL     0.589781
Name: 277, dtype: float64
牛式===============================
執行第 284
           284
ZRX  -0.036002
LTC  -0.035785
LINK  0.000000
XRP   0.011395
BCH   0.014938
ATOM  0.016309
NEO   0.028571
ALGO  0.031250
ICX   0.031806
BAT   0.036697
ZEC   0.037570
BNB   0.044893
TRX   0.048319
XLM   0.060125
QTUM  0.062802
VET   0.065837
ETH   0.067234
IOTA  0.069452
ADA   0.070065
ZIL   0.589781
g================================================================          VET      ETH    IOTA     ADA      ZIL
0        NaN      NaN     NaN     NaN      NaN
1        NaN      NaN     NaN     NaN      NaN
2        NaN      NaN     NaN     NaN      NaN
3        NaN      NaN     NaN     NaN      NaN
4        NaN      NaN     NaN     NaN      NaN
..       ...      ...     ...     ...      ...
720  0.08348  2316.15  0.8896  1.4039  0.08133
721  0.07614  2121.52  0.8165  1.3327  0.07509
722  0.07704  2146.27  0.8180  1.3497  0.07496
723  0.07591  2111.19  0.7913  1.3356  0.07299
724  0.07768  2138.86  0.8404  1.3478  0.07377

[725 rows x 5 columns]
VET     0.077672
ETH     0.111272
IOTA    0.127828
ADA     0.073702
ZIL     0.504979
Name: 278, dtype: float64
報酬 0.17909059365729724 %
i= VET     0.077672
ETH     0.111272
IOTA    0.127828
ADA     0.073702
ZIL     0.504979
Name: 278, dtype: float64
牛式===============================
執行第 285
           285
LTC  -0.016168
BCH   0.023505
XRP   0.045506
LINK  0.050000
NEO   0.053905
ATOM  0.058236
ALGO  0.058289
TRX   0.072194
ADA   0.073702
ZRX   0.073711
BNB   0.075908
VET   0.077672
ICX   0.086701
XLM   0.094397
QTUM  0.104211
BAT   0.111051
ETH   0.111272
IOTA  0.127828
ZEC   0.160311
ZIL   0.504979
g================================================================         BAT      ETH    IOTA     ZEC      ZIL
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.6135  2316.15  0.8896  118.51  0.08133
721  0.5691  2121.52  0.8165  109.38  0.07509
722  0.5695  2146.27  0.8180  110.99  0.07496
723  0.5575  2111.19  0.7913  108.15  0.07299
724  0.5623  2138.86  0.8404  110.82  0.07377

[725 rows x 5 columns]
BAT     0.011572
ETH     0.132185
IOTA    0.098440
ZEC     0.139607
ZIL     0.305774
Name: 279, dtype: float64
報酬 0.13751549996271262 %
i= BAT     0.011572
ETH     0.132185
IOTA    0.098440
ZEC     0.139607
ZIL     0.305774
Name: 279, dtype: float64
牛式===============================
執行第 286
           286
LTC  -0.050066
XLM   0.000712
BAT   0.011572
NEO   0.024398
ZRX   0.040370
ALGO  0.041904
XRP   0.041952
ATOM  0.046278
LINK  0.054201
BNB   0.054534
TRX   0.054907
VET   0.057257
BCH   0.065161
QTUM  0.075613
ADA   0.077366
ICX   0.086462
IOTA  0.098440
ETH   0.132185
ZEC   0.139607
ZIL   0.305774
g================================================================         ICX    IOTA      ETH     ZEC      ZIL
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  0.9279  0.8896  2316.15  118.51  0.08133
721  1.0350  0.8165  2121.52  109.38  0.07509
722  0.9786  0.8180  2146.27  110.99  0.07496
723  0.9198  0.7913  2111.19  108.15  0.07299
724  0.9519  0.8404  2138.86  110.82  0.07377

[725 rows x 5 columns]
ICX     0.094395
IOTA    0.050936
ETH     0.074592
ZEC     0.139665
ZIL     0.039236
Name: 280, dtype: float64
報酬 0.07976476784765044 %
i= ICX     0.094395
IOTA    0.050936
ETH     0.074592
ZEC     0.139665
ZIL     0.039236
Name: 280, dtype: float64
牛式===============================
執行第 287
           287
LTC  -0.022942
XLM   0.001291
NEO   0.005354
XRP   0.015812
VET   0.016820
BAT   0.021245
ALGO  0.027636
BCH   0.030408
ATOM  0.031533
ZRX   0.032230
TRX   0.036000
ZIL   0.039236
LINK  0.050532
IOTA  0.050936
BNB   0.060419
QTUM  0.061745
ETH   0.074592
ICX   0.094395
ADA   0.102116
ZEC   0.139665
g================================================================       QTUM      ETH     ICX     ADA     ZEC
0      NaN      NaN     NaN     NaN     NaN
1      NaN      NaN     NaN     NaN     NaN
2      NaN      NaN     NaN     NaN     NaN
3      NaN      NaN     NaN     NaN     NaN
4      NaN      NaN     NaN     NaN     NaN
..     ...      ...     ...     ...     ...
720  7.079  2316.15  0.9279  1.4039  118.51
721  6.504  2121.52  1.0350  1.3327  109.38
722  6.776  2146.27  0.9786  1.3497  110.99
723  6.639  2111.19  0.9198  1.3356  108.15
724  6.694  2138.86  0.9519  1.3478  110.82

[725 rows x 5 columns]
QTUM    0.025391
ETH     0.034524
ICX     0.270019
ADA     0.115317
ZEC     0.120139
Name: 281, dtype: float64
報酬 0.11307767620168847 %
i= QTUM    0.025391
ETH     0.034524
ICX     0.270019
ADA     0.115317
ZEC     0.120139
Name: 281, dtype: float64
牛式===============================
執行第 288
           288
LTC  -0.092992
ZIL  -0.080306
IOTA -0.048757
TRX  -0.017682
BCH  -0.011747
XRP  -0.010546
NEO  -0.004321
VET   0.006898
BAT   0.017474
XLM   0.023968
QTUM  0.025391
BNB   0.031746
ETH   0.034524
ZRX   0.051694
ALGO  0.061421
ATOM  0.070016
LINK  0.073491
ADA   0.115317
ZEC   0.120139
ICX   0.270019
g================================================================        ATOM   LINK     ADA     ZEC     ICX
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  12.946  19.79  1.4039  118.51  0.9279
721  11.958  18.44  1.3327  109.38  1.0350
722  13.182  18.66  1.3497  110.99  0.9786
723  14.395  18.20  1.3356  108.15  0.9198
724  14.064  18.38  1.3478  110.82  0.9519

[725 rows x 5 columns]
ATOM    0.018646
LINK    0.043716
ADA     0.035601
ZEC     0.098639
ICX     0.143441
Name: 282, dtype: float64
報酬 0.06800847114298851 %
i= ATOM    0.018646
LINK    0.043716
ADA     0.035601
ZEC     0.098639
ICX     0.143441
Name: 282, dtype: float64
牛式===============================
執行第 289
           289
ZRX  -0.155759
LTC  -0.154233
IOTA -0.050933
NEO  -0.049656
TRX  -0.044355
VET  -0.031985
BCH  -0.029477
ZIL  -0.027888
BAT  -0.021042
XRP  -0.019480
XLM  -0.012338
ALGO -0.005726
QTUM -0.002665
ETH   0.018483
ATOM  0.018646
BNB   0.024841
ADA   0.035601
LINK  0.043716
ZEC   0.098639
ICX   0.143441
g================================================================         BNB     ADA   LINK     ZEC     ICX
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  327.67  1.4039  19.79  118.51  0.9279
721  310.59  1.3327  18.44  109.38  1.0350
722  316.72  1.3497  18.66  110.99  0.9786
723  316.09  1.3356  18.20  108.15  0.9198
724  321.87  1.3478  18.38  110.82  0.9519

[725 rows x 5 columns]
BNB     0.033624
ADA     0.092923
LINK    0.079787
ZEC     0.121326
ICX     0.194128
Name: 283, dtype: float64
報酬 0.10435773275314766 %
i= BNB     0.033624
ADA     0.092923
LINK    0.079787
ZEC     0.121326
ICX     0.194128
Name: 283, dtype: float64
牛式===============================
執行第 290
           290
ZRX  -0.128232
ZIL  -0.078972
LTC  -0.065292
TRX  -0.008684
BCH  -0.007570
XLM   0.000882
XRP   0.003305
BAT   0.011799
IOTA  0.024860
ALGO  0.032323
BNB   0.033624
ETH   0.034368
ATOM  0.037182
NEO   0.037970
VET   0.042453
LINK  0.079787
ADA   0.092923
ZEC   0.121326
QTUM  0.142208
ICX   0.194128
g================================================================       LINK     ADA     ZEC   QTUM     ICX
0      NaN     NaN     NaN    NaN     NaN
1      NaN     NaN     NaN    NaN     NaN
2      NaN     NaN     NaN    NaN     NaN
3      NaN     NaN     NaN    NaN     NaN
4      NaN     NaN     NaN    NaN     NaN
..     ...     ...     ...    ...     ...
720  19.79  1.4039  118.51  7.079  0.9279
721  18.44  1.3327  109.38  6.504  1.0350
722  18.66  1.3497  110.99  6.776  0.9786
723  18.20  1.3356  108.15  6.639  0.9198
724  18.38  1.3478  110.82  6.694  0.9519

[725 rows x 5 columns]
LINK    0.039683
ADA     0.070788
ZEC     0.014270
QTUM    0.079509
ICX     0.151986
Name: 284, dtype: float64
報酬 0.0712469855200815 %
i= LINK    0.039683
ADA     0.070788
ZEC     0.014270
QTUM    0.079509
ICX     0.151986
Name: 284, dtype: float64
牛式===============================
執行第 291
           291
ZRX  -0.123626
LTC  -0.107159
ZIL  -0.068998
BCH  -0.027658
XLM  -0.023564
XRP  -0.012372
BAT  -0.009751
ETH  -0.002319
TRX  -0.002000
IOTA -0.001003
NEO   0.005519
BNB   0.010429
ZEC   0.014270
ALGO  0.017686
ATOM  0.018868
LINK  0.039683
VET   0.041347
ADA   0.070788
QTUM  0.079509
ICX   0.151986
g================================================================       LINK      VET     ADA   QTUM     ICX
0      NaN      NaN     NaN    NaN     NaN
1      NaN      NaN     NaN    NaN     NaN
2      NaN      NaN     NaN    NaN     NaN
3      NaN      NaN     NaN    NaN     NaN
4      NaN      NaN     NaN    NaN     NaN
..     ...      ...     ...    ...     ...
720  19.79  0.08348  1.4039  7.079  0.9279
721  18.44  0.07614  1.3327  6.504  1.0350
722  18.66  0.07704  1.3497  6.776  0.9786
723  18.20  0.07591  1.3356  6.639  0.9198
724  18.38  0.07768  1.3478  6.694  0.9519

[725 rows x 5 columns]
LINK   -0.025707
VET    -0.003566
ADA    -0.053397
QTUM   -0.010133
ICX     0.060384
Name: 285, dtype: float64
報酬 -0.006483802726740895 %
i= LINK   -0.025707
VET    -0.003566
ADA    -0.053397
QTUM   -0.010133
ICX     0.060384
Name: 285, dtype: float64
牛式===============================
執行第 292
           292
ZRX  -0.187551
BCH  -0.100857
XLM  -0.088399
BAT  -0.079600
TRX  -0.074821
LTC  -0.071429
ETH  -0.070684
IOTA -0.067581
ZEC  -0.064684
XRP  -0.060759
NEO  -0.054856
ADA  -0.053397
BNB  -0.037282
ATOM -0.036538
LINK -0.025707
ALGO -0.018868
QTUM -0.010133
ZIL  -0.007035
VET  -0.003566
ICX   0.060384
g================================================================        ALGO   QTUM      ZIL      VET     ICX
0       NaN    NaN      NaN      NaN     NaN
1       NaN    NaN      NaN      NaN     NaN
2       NaN    NaN      NaN      NaN     NaN
3       NaN    NaN      NaN      NaN     NaN
4       NaN    NaN      NaN      NaN     NaN
..      ...    ...      ...      ...     ...
720  0.9062  7.079  0.08133  0.08348  0.9279
721  0.8683  6.504  0.07509  0.07614  1.0350
722  0.9059  6.776  0.07496  0.07704  0.9786
723  0.8918  6.639  0.07299  0.07591  0.9198
724  0.8952  6.694  0.07377  0.07768  0.9519

[725 rows x 5 columns]
ALGO    0.053785
QTUM    0.046144
ZIL     0.269388
VET     0.116895
ICX     0.120283
Name: 286, dtype: float64
報酬 0.12129886604407983 %
i= ALGO    0.053785
QTUM    0.046144
ZIL     0.269388
VET     0.116895
ICX     0.120283
Name: 286, dtype: float64
牛式===============================
執行第 293
           293
ZRX  -0.107053
LTC  -0.086326
BCH  -0.065629
ZEC  -0.060253
TRX  -0.052767
XLM  -0.051433
ADA  -0.050555
ETH  -0.048576
BNB  -0.047674
XRP  -0.043379
NEO  -0.039214
LINK -0.022785
IOTA -0.022750
BAT  -0.008708
ATOM -0.001911
QTUM  0.046144
ALGO  0.053785
VET   0.116895
ICX   0.120283
ZIL   0.269388
g================================================================       QTUM    ALGO      VET     ICX      ZIL
0      NaN     NaN      NaN     NaN      NaN
1      NaN     NaN      NaN     NaN      NaN
2      NaN     NaN      NaN     NaN      NaN
3      NaN     NaN      NaN     NaN      NaN
4      NaN     NaN      NaN     NaN      NaN
..     ...     ...      ...     ...      ...
720  7.079  0.9062  0.08348  0.9279  0.08133
721  6.504  0.8683  0.07614  1.0350  0.07509
722  6.776  0.9059  0.07704  0.9786  0.07496
723  6.639  0.8918  0.07591  0.9198  0.07299
724  6.694  0.8952  0.07768  0.9519  0.07377

[725 rows x 5 columns]
QTUM    0.053333
ALGO    0.045433
VET     0.076685
ICX    -0.000587
ZIL     0.285863
Name: 287, dtype: float64
報酬 0.09214549981487337 %
i= QTUM    0.053333
ALGO    0.045433
VET     0.076685
ICX    -0.000587
ZIL     0.285863
Name: 287, dtype: float64
牛式===============================
執行第 294
           294
XLM  -0.083333
ZEC  -0.073362
LINK -0.058680
ADA  -0.058379
BCH  -0.048882
ATOM -0.046580
ETH  -0.043654
BNB  -0.040237
XRP  -0.039314
ZRX  -0.035268
TRX  -0.028667
IOTA -0.023618
NEO  -0.020217
BAT  -0.001472
ICX  -0.000587
LTC   0.045011
ALGO  0.045433
QTUM  0.053333
VET   0.076685
ZIL   0.285863
g================================================================         LTC    ALGO   QTUM      VET      ZIL
0       NaN     NaN    NaN      NaN      NaN
1       NaN     NaN    NaN      NaN      NaN
2       NaN     NaN    NaN      NaN      NaN
3       NaN     NaN    NaN      NaN      NaN
4       NaN     NaN    NaN      NaN      NaN
..      ...     ...    ...      ...      ...
720  137.39  0.9062  7.079  0.08348  0.08133
721  132.25  0.8683  6.504  0.07614  0.07509
722  134.42  0.9059  6.776  0.07704  0.07496
723  134.00  0.8918  6.639  0.07591  0.07299
724  134.19  0.8952  6.694  0.07768  0.07377

[725 rows x 5 columns]
LTC     0.099297
ALGO    0.151832
QTUM    0.091516
VET     0.155535
ZIL     0.258197
Name: 288, dtype: float64
報酬 0.15127533225153048 %

i= LTC     0.099297
ALGO    0.151832
QTUM    0.091516
VET     0.155535
ZIL     0.258197
Name: 288, dtype: float64
牛式===============================
執行第 295
           295
XLM  -0.007074
ZEC   0.004565
LINK  0.007853
XRP   0.018941
BCH   0.020511
BNB   0.022996
TRX   0.033755
ATOM  0.035018
ZRX   0.037209
IOTA  0.045165
ETH   0.049756
NEO   0.049837
BAT   0.058342
ADA   0.058575
QTUM  0.091516
ICX   0.097498
LTC   0.099297
ALGO  0.151832
VET   0.155535
ZIL   0.258197
g================================================================         ICX     LTC    ALGO      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.9279  137.39  0.9062  0.08348  0.08133
721  1.0350  132.25  0.8683  0.07614  0.07509
722  0.9786  134.42  0.9059  0.07704  0.07496
723  0.9198  134.00  0.8918  0.07591  0.07299
724  0.9519  134.19  0.8952  0.07768  0.07377

[725 rows x 5 columns]
ICX     0.085126
LTC    -0.011275
ALGO    0.110568
VET     0.187029
ZIL     0.235294
Name: 289, dtype: float64
報酬 0.12134835578157552 %
i= ICX     0.085126
LTC    -0.011275
ALGO    0.110568
VET     0.187029
ZIL     0.235294
Name: 289, dtype: float64
牛式===============================
執行第 296
           296
QTUM -0.042069
LTC  -0.011275
LINK -0.004926
ZRX  -0.002996
ZEC  -0.000629
XRP   0.000948
NEO   0.002888
IOTA  0.003465
ATOM  0.007170
XLM   0.012918
TRX   0.018868
BCH   0.021393
BNB   0.028313
BAT   0.032556
ETH   0.060472
ICX   0.085126
ALGO  0.110568
ADA   0.165919
VET   0.187029
ZIL   0.235294
g================================================================         ICX    ALGO     ADA      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.9279  0.9062  1.4039  0.08348  0.08133
721  1.0350  0.8683  1.3327  0.07614  0.07509
722  0.9786  0.9059  1.3497  0.07704  0.07496
723  0.9198  0.8918  1.3356  0.07591  0.07299
724  0.9519  0.8952  1.3478  0.07768  0.07377

[725 rows x 5 columns]
ICX     0.094328
ALGO    0.132572
ADA     0.178656
VET     0.203515
ZIL     0.267005
Name: 290, dtype: float64
報酬 0.175215142768345 %
i= ICX     0.094328
ALGO    0.132572
ADA     0.178656
VET     0.203515
ZIL     0.267005
Name: 290, dtype: float64
牛式===============================
執行第 297
           297
ZEC  -0.006608
XRP  -0.006138
TRX   0.002004
NEO   0.003822
XLM   0.009534
IOTA  0.010040
LTC   0.011094
QTUM  0.011377
LINK  0.012723
BCH   0.017853
ZRX   0.018054
BAT   0.030034
BNB   0.032180
ATOM  0.032793
ETH   0.068361
ICX   0.094328
ALGO  0.132572
ADA   0.178656
VET   0.203515
ZIL   0.267005
g================================================================         ICX    ALGO     ADA      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.9279  0.9062  1.4039  0.08348  0.08133
721  1.0350  0.8683  1.3327  0.07614  0.07509
722  0.9786  0.9059  1.3497  0.07704  0.07496
723  0.9198  0.8918  1.3356  0.07591  0.07299
724  0.9519  0.8952  1.3478  0.07768  0.07377

[725 rows x 5 columns]
ICX     0.176761
ALGO    0.230769
ADA     0.495234
VET     0.392530
ZIL     0.357287
Name: 291, dtype: float64
報酬 0.3305163465556321 %
i= ICX     0.176761
ALGO    0.230769
ADA     0.495234
VET     0.392530
ZIL     0.357287
Name: 291, dtype: float64
牛式===============================
執行第 298
           298
LTC  -0.003983
XRP   0.072984
LINK  0.100264
BNB   0.107433
ZRX   0.118740
ATOM  0.124551
BCH   0.129627
XLM   0.132417
NEO   0.139523
BAT   0.140860
IOTA  0.149160
QTUM  0.152271
TRX   0.152602
ICX   0.176761
ZEC   0.213031
ETH   0.219418
ALGO  0.230769
ZIL   0.357287
VET   0.392530
ADA   0.495234
g================================================================          ETH    ALGO      ZIL      VET     ADA
0        NaN     NaN      NaN      NaN     NaN
1        NaN     NaN      NaN      NaN     NaN
2        NaN     NaN      NaN      NaN     NaN
3        NaN     NaN      NaN      NaN     NaN
4        NaN     NaN      NaN      NaN     NaN
..       ...     ...      ...      ...     ...
720  2316.15  0.9062  0.08133  0.08348  1.4039
721  2121.52  0.8683  0.07509  0.07614  1.3327
722  2146.27  0.9059  0.07496  0.07704  1.3497
723  2111.19  0.8918  0.07299  0.07591  1.3356
724  2138.86  0.8952  0.07377  0.07768  1.3478

[725 rows x 5 columns]
ETH     0.136410
ALGO    0.102079
ZIL     0.182476
VET     0.232227
ADA     0.375139
Name: 292, dtype: float64
報酬 0.20566646424442436 %
i= ETH     0.136410
ALGO    0.102079
ZIL     0.182476
VET     0.232227
ADA     0.375139
Name: 292, dtype: float64
牛式===============================
執行第 299
           299
ICX  -0.012632
ZRX  -0.012176
BAT   0.031235
LTC   0.031746
XRP   0.032849
BCH   0.035922
ATOM  0.044410
BNB   0.045177
QTUM  0.058006
XLM   0.066002
LINK  0.069948
TRX   0.074728
ALGO  0.102079
NEO   0.102993
IOTA  0.112348
ZEC   0.119539
ETH   0.136410
ZIL   0.182476
VET   0.232227
ADA   0.375139
g================================================================         ZEC      ETH      ZIL      VET     ADA
0       NaN      NaN      NaN      NaN     NaN
1       NaN      NaN      NaN      NaN     NaN
2       NaN      NaN      NaN      NaN     NaN
3       NaN      NaN      NaN      NaN     NaN
4       NaN      NaN      NaN      NaN     NaN
..      ...      ...      ...      ...     ...
720  118.51  2316.15  0.08133  0.08348  1.4039
721  109.38  2121.52  0.07509  0.07614  1.3327
722  110.99  2146.27  0.07496  0.07704  1.3497
723  108.15  2111.19  0.07299  0.07591  1.3356
724  110.82  2138.86  0.07377  0.07768  1.3478

[725 rows x 5 columns]
ZEC    0.219224
ETH    0.234357
ZIL    0.318513
VET    0.366379
ADA    0.511111
Name: 293, dtype: float64
報酬 0.3299167939707194 %
i= ZEC    0.219224
ETH    0.234357
ZIL    0.318513
VET    0.366379
ADA    0.511111
Name: 293, dtype: float64
牛式===============================
執行第 300
           300
ZRX  -0.041163
ICX   0.004401
LTC   0.024647
XRP   0.087883
BAT   0.098771
BNB   0.105425
ATOM  0.108569
BCH   0.109542
LINK  0.137662
QTUM  0.141049
ALGO  0.142726
XLM   0.163513
TRX   0.169526
IOTA  0.214617
ZEC   0.219224
ETH   0.234357
NEO   0.249522
ZIL   0.318513
VET   0.366379
ADA   0.511111
g================================================================          ETH     NEO      ZIL      VET     ADA
0        NaN     NaN      NaN      NaN     NaN
1        NaN     NaN      NaN      NaN     NaN
2        NaN     NaN      NaN      NaN     NaN
3        NaN     NaN      NaN      NaN     NaN
4        NaN     NaN      NaN      NaN     NaN
..       ...     ...      ...      ...     ...
720  2316.15  37.005  0.08133  0.08348  1.4039
721  2121.52  34.083  0.07509  0.07614  1.3327
722  2146.27  34.637  0.07496  0.07704  1.3497
723  2111.19  34.057  0.07299  0.07591  1.3356
724  2138.86  34.191  0.07377  0.07768  1.3478

[725 rows x 5 columns]
ETH    0.142240
NEO    0.212772
ZIL    0.484528
VET    0.480596
ADA    0.429971
Name: 294, dtype: float64
報酬 0.3500214249886201 %
i= ETH    0.142240
NEO    0.212772
ZIL    0.484528
VET    0.480596
ADA    0.429971
Name: 294, dtype: float64
牛式===============================
執行第 301
           301
ZRX  -0.026308
ICX   0.000000
XRP   0.026014
BAT   0.041103
BNB   0.049818
LTC   0.061039
ATOM  0.061515
BCH   0.078548
QTUM  0.101591
TRX   0.114286
ZEC   0.115559
ALGO  0.118182
ETH   0.142240
LINK  0.142857
IOTA  0.188612
XLM   0.206306
NEO   0.212772
ADA   0.429971
VET   0.480596
ZIL   0.484528
g================================================================          XLM     NEO     ADA      VET      ZIL
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  0.25677  37.005  1.4039  0.08348  0.08133
721  0.24383  34.083  1.3327  0.07614  0.07509
722  0.24550  34.637  1.3497  0.07704  0.07496
723  0.24484  34.057  1.3356  0.07591  0.07299
724  0.24587  34.191  1.3478  0.07768  0.07377

[725 rows x 5 columns]
XLM    0.199130
NEO    0.188328
ADA    0.316308
VET    0.288619
ZIL    0.453592
Name: 295, dtype: float64
報酬 0.28919525026470966 %
i= XLM    0.199130
NEO    0.188328
ADA    0.316308
VET    0.288619
ZIL    0.453592
Name: 295, dtype: float64
牛式===============================
執行第 302
           302
ICX  -0.039932
ZRX  -0.009014
XRP   0.017851
BNB   0.028120
LTC   0.050570
BCH   0.056450
BAT   0.056941
ALGO  0.066960
QTUM  0.086053
ATOM  0.088423
ZEC   0.108477
LINK  0.108911
ETH   0.111273
TRX   0.118386
NEO   0.188328
XLM   0.199130
IOTA  0.240750
VET   0.288619
ADA   0.316308
ZIL   0.453592
g================================================================          XLM    IOTA      VET     ADA      ZIL
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  0.25677  0.8896  0.08348  1.4039  0.08133
721  0.24383  0.8165  0.07614  1.3327  0.07509
722  0.24550  0.8180  0.07704  1.3497  0.07496
723  0.24484  0.7913  0.07591  1.3356  0.07299
724  0.24587  0.8404  0.07768  1.3478  0.07377

[725 rows x 5 columns]
XLM     0.210860
IOTA    0.238569
VET     0.213629
ADA     0.372373
ZIL     0.314904
Name: 296, dtype: float64
報酬 0.27006699725789207 %
i= XLM     0.210860
IOTA    0.238569
VET     0.213629
ADA     0.372373
ZIL     0.314904
Name: 296, dtype: float64
牛式===============================
執行第 303
           303
ICX  -0.041523
ZRX  -0.018936
LTC   0.029925
BNB   0.030588
XRP   0.034624
ALGO  0.061377
BCH   0.074983
QTUM  0.088218
ETH   0.102642
LINK  0.113065
ZEC   0.119313
TRX   0.124000
BAT   0.155354
ATOM  0.161375
NEO   0.188440
XLM   0.210860
VET   0.213629
IOTA  0.238569
ZIL   0.314904
ADA   0.372373
g================================================================          XLM      VET    IOTA      ZIL     ADA
0        NaN      NaN     NaN      NaN     NaN
1        NaN      NaN     NaN      NaN     NaN
2        NaN      NaN     NaN      NaN     NaN
3        NaN      NaN     NaN      NaN     NaN
4        NaN      NaN     NaN      NaN     NaN
..       ...      ...     ...      ...     ...
720  0.25677  0.08348  0.8896  0.08133  1.4039
721  0.24383  0.07614  0.8165  0.07509  1.3327
722  0.24550  0.07704  0.8180  0.07496  1.3497
723  0.24484  0.07591  0.7913  0.07299  1.3356
724  0.24587  0.07768  0.8404  0.07377  1.3478

[725 rows x 5 columns]
XLM     0.088665
VET     0.076775
IOTA    0.101920
ZIL     0.338553
ADA     0.107975
Name: 297, dtype: float64
報酬 0.14277747863353302 %
i= XLM     0.088665
VET     0.076775
IOTA    0.101920
ZIL     0.338553
ADA     0.107975
Name: 297, dtype: float64
牛式===============================
執行第 304
           304
ICX  -0.057902
ZRX  -0.048918
ALGO -0.045230
ZEC  -0.035747
XRP  -0.020193
ETH  -0.014043
BNB  -0.002256
QTUM -0.001666
BCH   0.014820
TRX   0.028066
LTC   0.040240
LINK  0.045564
NEO   0.070691
VET   0.076775
XLM   0.088665
ATOM  0.098687
IOTA  0.101920
ADA   0.107975
BAT   0.109850
ZIL   0.338553
g================================================================        ATOM    IOTA     ADA     BAT      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  12.946  0.8896  1.4039  0.6135  0.08133
721  11.958  0.8165  1.3327  0.5691  0.07509
722  13.182  0.8180  1.3497  0.5695  0.07496
723  14.395  0.7913  1.3356  0.5575  0.07299
724  14.064  0.8404  1.3478  0.5623  0.07377

[725 rows x 5 columns]
ATOM    0.120235
IOTA    0.107825
ADA     0.162304
BAT     0.120681
ZIL     0.438477
Name: 298, dtype: float64
報酬 0.18990459859987885 %
i= ATOM    0.120235
IOTA    0.107825
ADA     0.162304
BAT     0.120681
ZIL     0.438477
Name: 298, dtype: float64
牛式===============================
執行第 305
           305
LTC  -0.037118
XRP   0.005482
ALGO  0.017581
BNB   0.025117
ZEC   0.025626
ICX   0.025891
ZRX   0.025917
ETH   0.043634
LINK  0.053269
QTUM  0.055968
BCH   0.060683
TRX   0.077118
NEO   0.079306
IOTA  0.107825
ATOM  0.120235
BAT   0.120681
XLM   0.128932
ADA   0.162304
VET   0.171955
ZIL   0.438477
g================================================================         BAT      XLM     ADA      VET      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  0.6135  0.25677  1.4039  0.08348  0.08133
721  0.5691  0.24383  1.3327  0.07614  0.07509
722  0.5695  0.24550  1.3497  0.07704  0.07496
723  0.5575  0.24484  1.3356  0.07591  0.07299
724  0.5623  0.24587  1.3478  0.07768  0.07377

[725 rows x 5 columns]
BAT    0.049195
XLM    0.041777
ADA    0.069328
VET    0.087577
ZIL    0.367872
Name: 299, dtype: float64
報酬 0.12314980346146127 %
i= BAT    0.049195
XLM    0.041777
ADA    0.069328
VET    0.087577
ZIL    0.367872
Name: 299, dtype: float64
牛式===============================
執行第 306
           306
ALGO -0.071257
NEO  -0.051313
QTUM -0.045431
ZEC  -0.044997
XRP  -0.035530
ZRX  -0.033323
BNB  -0.028444
ICX  -0.024248
LTC  -0.014713
ETH  -0.013792
LINK -0.006849
BCH   0.001897
IOTA  0.022034
XLM   0.041777
BAT   0.049195
ATOM  0.056313
TRX   0.067488
ADA   0.069328
VET   0.087577
ZIL   0.367872
g================================================================        ATOM      TRX     ADA      VET      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  12.946  0.06432  1.4039  0.08348  0.08133
721  11.958  0.06111  1.3327  0.07614  0.07509
722  13.182  0.06219  1.3497  0.07704  0.07496
723  14.395  0.06139  1.3356  0.07591  0.07299
724  14.064  0.06184  1.3478  0.07768  0.07377

[725 rows x 5 columns]
ATOM    0.141253
TRX     0.095849
ADA     0.096676
VET     0.073803
ZIL     0.170598
Name: 300, dtype: float64
報酬 0.11563578685827935 %
i= ATOM    0.141253
TRX     0.095849
ADA     0.096676
VET     0.073803
ZIL     0.170598
Name: 300, dtype: float64
牛式===============================
執行第 307
           307
ALGO -0.049187
NEO  -0.040297
ZRX  -0.019650
ICX  -0.007995
LTC  -0.007655
XRP   0.004628
XLM   0.006283
BNB   0.008102
QTUM  0.013889
LINK  0.015909
BCH   0.016684
ZEC   0.018429
IOTA  0.032934
ETH   0.034852
VET   0.073803
TRX   0.095849
ADA   0.096676
ATOM  0.141253
ZIL   0.170598
BAT   0.194612
g================================================================          TRX     ADA    ATOM      ZIL     BAT
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.06432  1.4039  12.946  0.08133  0.6135
721  0.06111  1.3327  11.958  0.07509  0.5691
722  0.06219  1.3497  13.182  0.07496  0.5695
723  0.06139  1.3356  14.395  0.07299  0.5575
724  0.06184  1.3478  14.064  0.07377  0.5623

[725 rows x 5 columns]
TRX     0.036665
ADA    -0.031440
ATOM    0.072978
ZIL     0.357024
BAT     0.118433
Name: 301, dtype: float64
報酬 0.11073180800501237 %
i= TRX     0.036665
ADA    -0.031440
ATOM    0.072978
ZIL     0.357024
BAT     0.118433
Name: 301, dtype: float64
牛式===============================
執行第 308
           308
XLM  -0.055112
ADA  -0.031440
NEO  -0.028595
IOTA -0.018290
ICX  -0.016814
ZEC  -0.016089
XRP  -0.014305
QTUM -0.013661
BNB  -0.010256
LINK -0.008929
ETH  -0.002619
ALGO  0.000413
BCH   0.002725
LTC   0.022652
TRX   0.036665
ZRX   0.057307
ATOM  0.072978
BAT   0.118433
VET   0.152416
ZIL   0.357024
g================================================================         ZRX    ATOM     BAT      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.7889  12.946  0.6135  0.08348  0.08133
721  0.8190  11.958  0.5691  0.07614  0.07509
722  0.8384  13.182  0.5695  0.07704  0.07496
723  0.7890  14.395  0.5575  0.07591  0.07299
724  0.7950  14.064  0.5623  0.07768  0.07377

[725 rows x 5 columns]
ZRX     0.187806
ATOM    0.001608
BAT     0.035581
VET     0.338235
ZIL     0.664839
Name: 302, dtype: float64
報酬 0.24561394261169628 %
i= ZRX     0.187806
ATOM    0.001608
BAT     0.035581
VET     0.338235
ZIL     0.664839
Name: 302, dtype: float64
牛式===============================
執行第 309
           309
ADA  -0.058883
XLM  -0.039118
NEO  -0.019471
XRP  -0.008660
BNB  -0.006279
LINK -0.002257
ATOM  0.001608
BCH   0.002928
IOTA  0.006822
QTUM  0.013058
ETH   0.018124
ALGO  0.020240
BAT   0.035581
TRX   0.043891
ZEC   0.058474
ICX   0.082462
LTC   0.108717
ZRX   0.187806
VET   0.338235
ZIL   0.664839
g================================================================         ICX     LTC     ZRX      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.9279  137.39  0.7889  0.08348  0.08133
721  1.0350  132.25  0.8190  0.07614  0.07509
722  0.9786  134.42  0.8384  0.07704  0.07496
723  0.9198  134.00  0.7890  0.07591  0.07299
724  0.9519  134.19  0.7950  0.07768  0.07377

[725 rows x 5 columns]
ICX   -0.046021
LTC    0.113647
ZRX    0.044576
VET    0.306981
ZIL    0.397772
Name: 303, dtype: float64
報酬 0.16339089236045867 %
i= ICX   -0.046021
LTC    0.113647
ZRX    0.044576
VET    0.306981
ZIL    0.397772
Name: 303, dtype: float64
牛式===============================
執行第 310
           310
ADA  -0.116708
ATOM -0.104685
XLM  -0.099557
NEO  -0.095311
BAT  -0.090389
LINK -0.089450
BNB  -0.083098
BCH  -0.082074
IOTA -0.076732
XRP  -0.069914
TRX  -0.065875
QTUM -0.058954
ZEC  -0.051521
ICX  -0.046021
ETH  -0.040523
ALGO -0.004307
ZRX   0.044576
LTC   0.113647
VET   0.306981
ZIL   0.397772
g================================================================        ALGO     ZRX     LTC      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.9062  0.7889  137.39  0.08348  0.08133
721  0.8683  0.8190  132.25  0.07614  0.07509
722  0.9059  0.8384  134.42  0.07704  0.07496
723  0.8918  0.7890  134.00  0.07591  0.07299
724  0.8952  0.7950  134.19  0.07768  0.07377

[725 rows x 5 columns]
ALGO   -0.023599
ZRX     0.095810
LTC     0.150139
VET     0.327772
ZIL     0.226371
Name: 304, dtype: float64
報酬 0.15529877320266477 %
i= ALGO   -0.023599
ZRX     0.095810
LTC     0.150139
VET     0.327772
ZIL     0.226371
Name: 304, dtype: float64
牛式===============================
執行第 311
           311
XLM  -0.086220
ADA  -0.077423
IOTA -0.075565
NEO  -0.075510
ATOM -0.063482
LINK -0.062069
QTUM -0.056247
XRP  -0.052161
BNB  -0.051852
BCH  -0.048802
TRX  -0.035211
BAT  -0.030828
ALGO -0.023599
ZEC  -0.023093
ICX  -0.020190
ETH  -0.018550
ZRX   0.095810
LTC   0.150139
ZIL   0.226371
VET   0.327772
g================================================================          ETH     ZRX     LTC      ZIL      VET
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  2316.15  0.7889  137.39  0.08133  0.08348
721  2121.52  0.8190  132.25  0.07509  0.07614
722  2146.27  0.8384  134.42  0.07496  0.07704
723  2111.19  0.7890  134.00  0.07299  0.07591
724  2138.86  0.7950  134.19  0.07377  0.07768

[725 rows x 5 columns]
ETH   -0.026375
ZRX    0.118012
LTC    0.061152
ZIL    0.017481
VET    0.325552
Name: 305, dtype: float64
報酬 0.09916456321782889 %
i= ETH   -0.026375
ZRX    0.118012
LTC    0.061152
ZIL    0.017481
VET    0.325552
Name: 305, dtype: float64
牛式===============================
執行第 312
           312
ADA  -0.086328
TRX  -0.083013
XLM  -0.059772
NEO  -0.058674
LINK -0.055172
XRP  -0.054053
IOTA -0.051824
BCH  -0.050533
ATOM -0.049338
BNB  -0.035017
ETH  -0.026375
QTUM -0.016049
BAT  -0.008951
ALGO  0.011207
ZEC   0.011492
ICX   0.014072
ZIL   0.017481
LTC   0.061152
ZRX   0.118012
VET   0.325552
g================================================================         ICX      ZIL     LTC     ZRX      VET
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.9279  0.08133  137.39  0.7889  0.08348
721  1.0350  0.07509  132.25  0.8190  0.07614
722  0.9786  0.07496  134.42  0.8384  0.07704
723  0.9198  0.07299  134.00  0.7890  0.07591
724  0.9519  0.07377  134.19  0.7950  0.07768

[725 rows x 5 columns]
ICX   -0.038507
ZIL    0.073102
LTC    0.146564
ZRX    0.116505
VET    0.109969
Name: 306, dtype: float64
報酬 0.08152650592972625 %
i= ICX   -0.038507
ZIL    0.073102
LTC    0.146564
ZRX    0.116505
VET    0.109969
Name: 306, dtype: float64
牛式===============================
執行第 313
           313
BAT  -0.129860
ATOM -0.126309
LINK -0.118568
XLM  -0.116259
ADA  -0.115456
TRX  -0.099164
NEO  -0.088528
IOTA -0.082816
BCH  -0.069792
XRP  -0.067823
ETH  -0.058663
QTUM -0.057534
BNB  -0.049369
ICX  -0.038507
ZEC  -0.026667
ALGO -0.003420
ZIL   0.073102
VET   0.109969
ZRX   0.116505
LTC   0.146564

g================================================================        ALGO      ZIL      VET     ZRX     LTC
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.9062  0.08133  0.08348  0.7889  137.39
721  0.8683  0.07509  0.07614  0.8190  132.25
722  0.9059  0.07496  0.07704  0.8384  134.42
723  0.8918  0.07299  0.07591  0.7890  134.00
724  0.8952  0.07377  0.07768  0.7950  134.19

[725 rows x 5 columns]
ALGO   -0.063145
ZIL     0.026187
VET     0.104633
ZRX    -0.013192
LTC     0.141209
Name: 307, dtype: float64
報酬 0.03913831848527858 %
i= ALGO   -0.063145
ZIL     0.026187
VET     0.104633
ZRX    -0.013192
LTC     0.141209
Name: 307, dtype: float64
牛式===============================
執行第 314
           314
NEO  -0.132712
ATOM -0.132178
IOTA -0.117051
LINK -0.114865
BAT  -0.114650
XLM  -0.092095
TRX  -0.082715
QTUM -0.072576
BCH  -0.072036
ALGO -0.063145
BNB  -0.056995
ADA  -0.056112
ICX  -0.054605
ETH  -0.052966
XRP  -0.043934
ZRX  -0.013192
ZEC   0.004232
ZIL   0.026187
VET   0.104633
LTC   0.141209
g================================================================         ZRX     ZEC      ZIL      VET     LTC
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  0.7889  118.51  0.08133  0.08348  137.39
721  0.8190  109.38  0.07509  0.07614  132.25
722  0.8384  110.99  0.07496  0.07704  134.42
723  0.7890  108.15  0.07299  0.07591  134.00
724  0.7950  110.82  0.07377  0.07768  134.19

[725 rows x 5 columns]
ZRX   -0.116327
ZEC   -0.040935
ZIL   -0.079429
VET    0.006327
LTC    0.120769
Name: 308, dtype: float64
報酬 -0.02191898538507564 %
i= ZRX   -0.116327
ZEC   -0.040935
ZIL   -0.079429
VET    0.006327
LTC    0.120769
Name: 308, dtype: float64
牛式===============================
執行第 315
           315
ICX  -0.127795
IOTA -0.125947
ATOM -0.123635
ZRX  -0.116327
NEO  -0.115207
BAT  -0.101079
XLM  -0.095117
TRX  -0.084091
LINK -0.083710
ZIL  -0.079429
BCH  -0.075815
QTUM -0.068206
BNB  -0.056289
ADA  -0.053475
XRP  -0.050686
ETH  -0.050135
ALGO -0.045749
ZEC  -0.040935
VET   0.006327
LTC   0.120769
g================================================================          ETH    ALGO     ZEC      VET     LTC
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  2316.15  0.9062  118.51  0.08348  137.39
721  2121.52  0.8683  109.38  0.07614  132.25
722  2146.27  0.9059  110.99  0.07704  134.42
723  2111.19  0.8918  108.15  0.07591  134.00
724  2138.86  0.8952  110.82  0.07768  134.19

[725 rows x 5 columns]
ETH     0.014758
ALGO    0.057958
ZEC     0.060333
VET     0.028532
LTC     0.069903
Name: 309, dtype: float64
報酬 0.04629692924856328 %
i= ETH     0.014758
ALGO    0.057958
ZEC     0.060333
VET     0.028532
LTC     0.069903
Name: 309, dtype: float64
牛式===============================
執行第 316
           316
ZIL  -0.071343
ATOM -0.024179
NEO  -0.009263
BAT   0.005845
ICX   0.008403
IOTA  0.009883
XLM   0.009987
QTUM  0.010638
BNB   0.011097
ETH   0.014758
ZRX   0.022381
BCH   0.022502
XRP   0.023908
VET   0.028532
TRX   0.028590
LINK  0.047859
ALGO  0.057958
ZEC   0.060333
LTC   0.069903
ADA   0.109398
g================================================================       LINK    ALGO     ZEC     LTC     ADA
0      NaN     NaN     NaN     NaN     NaN
1      NaN     NaN     NaN     NaN     NaN
2      NaN     NaN     NaN     NaN     NaN
3      NaN     NaN     NaN     NaN     NaN
4      NaN     NaN     NaN     NaN     NaN
..     ...     ...     ...     ...     ...
720  19.79  0.9062  118.51  137.39  1.4039
721  18.44  0.8683  109.38  132.25  1.3327
722  18.66  0.9059  110.99  134.42  1.3497
723  18.20  0.8918  108.15  134.00  1.3356
724  18.38  0.8952  110.82  134.19  1.3478

[725 rows x 5 columns]
LINK    0.014706
ALGO    0.037117
ZEC     0.007557
LTC     0.290187
ADA     0.028686
Name: 310, dtype: float64
報酬 0.07565068241974085 %
i= LINK    0.014706
ALGO    0.037117
ZEC     0.007557
LTC     0.290187
ADA     0.028686
Name: 310, dtype: float64
牛式===============================
執行第 317
           317
ZIL  -0.197303
VET  -0.107415
ATOM -0.076520
ZRX  -0.069159
BAT  -0.048366
NEO  -0.046516
QTUM -0.037249
XLM  -0.030078
BNB  -0.028846
ETH  -0.026520
TRX  -0.025547
BCH  -0.019592
XRP  -0.016582
ICX  -0.013636
IOTA -0.006219
ZEC   0.007557
LINK  0.014706
ADA   0.028686
ALGO  0.037117
LTC   0.290187
g================================================================         ZEC   LINK     ADA    ALGO     LTC
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  118.51  19.79  1.4039  0.9062  137.39
721  109.38  18.44  1.3327  0.8683  132.25
722  110.99  18.66  1.3497  0.9059  134.42
723  108.15  18.20  1.3356  0.8918  134.00
724  110.82  18.38  1.3478  0.8952  134.19

[725 rows x 5 columns]
ZEC    -0.026510
LINK   -0.002433
ADA     0.011131
ALGO   -0.012361
LTC     0.299978
Name: 311, dtype: float64
報酬 0.053960752670241495 %
i= ZEC    -0.026510
LINK   -0.002433
ADA     0.011131
ALGO   -0.012361
LTC     0.299978
Name: 311, dtype: float64
牛式===============================
執行第 318
           318
ZIL  -0.173568
VET  -0.126810
ATOM -0.095437
ZRX  -0.081667
NEO  -0.075320
BAT  -0.063656
XLM  -0.062087
QTUM -0.057368
ICX  -0.054916
BNB  -0.050565
TRX  -0.048561
IOTA -0.041102
ETH  -0.038093
BCH  -0.030205
XRP  -0.026673
ZEC  -0.026510
ALGO -0.012361
LINK -0.002433
ADA   0.011131
LTC   0.299978
g================================================================         ZEC    ALGO   LINK     ADA     LTC
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  118.51  0.9062  19.79  1.4039  137.39
721  109.38  0.8683  18.44  1.3327  132.25
722  110.99  0.9059  18.66  1.3497  134.42
723  108.15  0.8918  18.20  1.3356  134.00
724  110.82  0.8952  18.38  1.3478  134.19

[725 rows x 5 columns]
ZEC     0.005871
ALGO   -0.011154
LINK    0.060914
ADA     0.040544
LTC     0.175943
Name: 312, dtype: float64
報酬 0.054423505328597924 %
i= ZEC     0.005871
ALGO   -0.011154
LINK    0.060914
ADA     0.040544
LTC     0.175943
Name: 312, dtype: float64
牛式===============================
執行第 319
           319
ZIL  -0.164192
ATOM -0.048311
VET  -0.039005
NEO  -0.033066
BNB  -0.030193
QTUM -0.023256
BCH  -0.020252
ZRX  -0.019635
IOTA -0.016704
XLM  -0.014413
ETH  -0.012386
TRX  -0.012369
XRP  -0.012354
ALGO -0.011154
ICX  -0.007451
ZEC   0.005871
BAT   0.031278
ADA   0.040544
LINK  0.060914
LTC   0.175943
g================================================================         ZEC     BAT     ADA   LINK     LTC
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  118.51  0.6135  1.4039  19.79  137.39
721  109.38  0.5691  1.3327  18.44  132.25
722  110.99  0.5695  1.3497  18.66  134.42
723  108.15  0.5575  1.3356  18.20  134.00
724  110.82  0.5623  1.3478  18.38  134.19

[725 rows x 5 columns]
ZEC    -0.032375
BAT     0.089478
ADA     0.002301
LINK    0.063613
LTC     0.235342
Name: 313, dtype: float64
報酬 0.07167181237691674 %
i= ZEC    -0.032375
BAT     0.089478
ADA     0.002301
LINK    0.063613
LTC     0.235342
Name: 313, dtype: float64
牛式===============================
執行第 320
           320
ZIL  -0.210128
VET  -0.045480
ATOM -0.039187
XLM  -0.034658
XRP  -0.033113
ZEC  -0.032375
BNB  -0.025031
BCH  -0.022452
TRX  -0.016169
NEO  -0.014669
ETH  -0.012087
IOTA -0.001376
ADA   0.002301
ZRX   0.007556
ICX   0.009203
ALGO  0.022467
QTUM  0.032855
LINK  0.063613
BAT   0.089478
LTC   0.235342
g================================================================        ALGO   QTUM   LINK     BAT     LTC
0       NaN    NaN    NaN     NaN     NaN
1       NaN    NaN    NaN     NaN     NaN
2       NaN    NaN    NaN     NaN     NaN
3       NaN    NaN    NaN     NaN     NaN
4       NaN    NaN    NaN     NaN     NaN
..      ...    ...    ...     ...     ...
720  0.9062  7.079  19.79  0.6135  137.39
721  0.8683  6.504  18.44  0.5691  132.25
722  0.9059  6.776  18.66  0.5695  134.42
723  0.8918  6.639  18.20  0.5575  134.00
724  0.8952  6.694  18.38  0.5623  134.19

[725 rows x 5 columns]
ALGO    0.024608
QTUM    0.059366
LINK    0.108642
BAT     0.086222
LTC     0.155885
Name: 314, dtype: float64
報酬 0.08694447782049082 %
i= ALGO    0.024608
QTUM    0.059366
LINK    0.108642
BAT     0.086222
LTC     0.155885
Name: 314, dtype: float64
牛式===============================
執行第 321
           321
ZIL  -0.202783
XRP  -0.016012
ATOM -0.014291
BNB   0.004260
XLM   0.007428
ZEC   0.010954
BCH   0.015034
TRX   0.016129
NEO   0.022727
VET   0.023715
ALGO  0.024608
ICX   0.032278
ETH   0.033148
ZRX   0.034151
ADA   0.056876
IOTA  0.059280
QTUM  0.059366
BAT   0.086222
LINK  0.108642
LTC   0.155885
g================================================================        IOTA   QTUM     BAT   LINK     LTC
0       NaN    NaN     NaN    NaN     NaN
1       NaN    NaN     NaN    NaN     NaN
2       NaN    NaN     NaN    NaN     NaN
3       NaN    NaN     NaN    NaN     NaN
4       NaN    NaN     NaN    NaN     NaN
..      ...    ...     ...    ...     ...
720  0.8896  7.079  0.6135  19.79  137.39
721  0.8165  6.504  0.5691  18.44  132.25
722  0.8180  6.776  0.5695  18.66  134.42
723  0.7913  6.639  0.5575  18.20  134.00
724  0.8404  6.694  0.5623  18.38  134.19

[725 rows x 5 columns]
IOTA    0.017349
QTUM    0.050292
BAT     0.154224
LINK    0.153846
LTC     0.163541
Name: 315, dtype: float64
報酬 0.1078505500287068 %
i= IOTA    0.017349
QTUM    0.050292
BAT     0.154224
LINK    0.153846
LTC     0.163541
Name: 315, dtype: float64
牛式===============================
執行第 322
           322
ZIL  -0.164807
XRP  -0.022159
VET  -0.012095
XLM  -0.010724
ADA  -0.008148
ICX  -0.003395
BNB  -0.000610
BCH   0.001373
IOTA  0.017349
ALGO  0.018397
TRX   0.019148
ATOM  0.025888
NEO   0.032109
ETH   0.040123
QTUM  0.050292
ZRX   0.065382
ZEC   0.100945
LINK  0.153846
BAT   0.154224
LTC   0.163541
g================================================================         ZRX     ZEC   LINK     BAT     LTC
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  0.7889  118.51  19.79  0.6135  137.39
721  0.8190  109.38  18.44  0.5691  132.25
722  0.8384  110.99  18.66  0.5695  134.42
723  0.7890  108.15  18.20  0.5575  134.00
724  0.7950  110.82  18.38  0.5623  134.19

[725 rows x 5 columns]
ZRX     0.038055
ZEC     0.060000
LINK    0.137681
BAT     0.138736
LTC    -0.022560
Name: 316, dtype: float64
報酬 0.07038242906646089 %
i= ZRX     0.038055
ZEC     0.060000
LINK    0.137681
BAT     0.138736
LTC    -0.022560
Name: 316, dtype: float64
牛式===============================
執行第 323
           323
ZIL  -0.065771
XRP  -0.033249
ICX  -0.024885
XLM  -0.024356
LTC  -0.022560
IOTA -0.016093
BCH  -0.015284
BNB  -0.009901
ALGO -0.007491
TRX  -0.006242
NEO   0.006050
ADA   0.010029
ATOM  0.013243
ETH   0.014745
QTUM  0.032738
VET   0.036922
ZRX   0.038055
ZEC   0.060000
LINK  0.137681
BAT   0.138736
g================================================================          VET     ZRX     ZEC   LINK     BAT
0        NaN     NaN     NaN    NaN     NaN
1        NaN     NaN     NaN    NaN     NaN
2        NaN     NaN     NaN    NaN     NaN
3        NaN     NaN     NaN    NaN     NaN
4        NaN     NaN     NaN    NaN     NaN
..       ...     ...     ...    ...     ...
720  0.08348  0.7889  118.51  19.79  0.6135
721  0.07614  0.8190  109.38  18.44  0.5691
722  0.07704  0.8384  110.99  18.66  0.5695
723  0.07591  0.7890  108.15  18.20  0.5575
724  0.07768  0.7950  110.82  18.38  0.5623

[725 rows x 5 columns]
VET     0.059905
ZRX     0.013914
ZEC     0.087921
LINK    0.173171
BAT     0.242995
Name: 317, dtype: float64
報酬 0.11558098941609804 %
i= VET     0.059905
ZRX     0.013914
ZEC     0.087921
LINK    0.173171
BAT     0.242995
Name: 317, dtype: float64
牛式===============================
執行第 324
           324
XRP  -0.030128
ICX  -0.029366
XLM  -0.027918
LTC  -0.010825
BCH  -0.004070
BNB  -0.003133
TRX   0.001890
ZIL   0.003731
IOTA  0.004560
NEO   0.008194
ATOM  0.010397
ALGO  0.012516
ZRX   0.013914
ETH   0.015282
ADA   0.020891
QTUM  0.025060
VET   0.059905
ZEC   0.087921
LINK  0.173171
BAT   0.242995
g================================================================       QTUM      VET     ZEC   LINK     BAT
0      NaN      NaN     NaN    NaN     NaN
1      NaN      NaN     NaN    NaN     NaN
2      NaN      NaN     NaN    NaN     NaN
3      NaN      NaN     NaN    NaN     NaN
4      NaN      NaN     NaN    NaN     NaN
..     ...      ...     ...    ...     ...
720  7.079  0.08348  118.51  19.79  0.6135
721  6.504  0.07614  109.38  18.44  0.5691
722  6.776  0.07704  110.99  18.66  0.5695
723  6.639  0.07591  108.15  18.20  0.5575
724  6.694  0.07768  110.82  18.38  0.5623

[725 rows x 5 columns]
QTUM   -0.001190
VET     0.077442
ZEC     0.083658
LINK    0.122010
BAT     0.178076
Name: 318, dtype: float64
報酬 0.09199896514186637 %
i= QTUM   -0.001190
VET     0.077442
ZEC     0.083658
LINK    0.122010
BAT     0.178076
Name: 318, dtype: float64
牛式===============================
執行第 325
           325
ZIL  -0.068966
ICX  -0.062246
XLM  -0.040143
ALGO -0.033839
XRP  -0.028530
BNB  -0.018057
IOTA -0.012856
BCH  -0.008509
TRX  -0.008140
NEO  -0.006625
QTUM -0.001190
ATOM  0.000763
ETH   0.003059
ZRX   0.008584
LTC   0.011442
ADA   0.013323
VET   0.077442
ZEC   0.083658
LINK  0.122010
BAT   0.178076
g================================================================         ADA      VET     ZEC   LINK     BAT
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  1.4039  0.08348  118.51  19.79  0.6135
721  1.3327  0.07614  109.38  18.44  0.5691
722  1.3497  0.07704  110.99  18.66  0.5695
723  1.3356  0.07591  108.15  18.20  0.5575
724  1.3478  0.07768  110.82  18.38  0.5623

[725 rows x 5 columns]
ADA    -0.013010
VET    -0.000927
ZEC     0.034251
LINK    0.055024
BAT     0.118035
Name: 319, dtype: float64
報酬 0.03867448545732566 %
i= ADA    -0.013010
VET    -0.000927
ZEC     0.034251
LINK    0.055024
BAT     0.118035
Name: 319, dtype: float64
牛式===============================
執行第 326
           326
ZIL  -0.199899
ALGO -0.115898
ICX  -0.113836
LTC  -0.109002
QTUM -0.087334
XLM  -0.083917
IOTA -0.067065
ATOM -0.065410
BCH  -0.060481
XRP  -0.058495
NEO  -0.055756
BNB  -0.052599
ZRX  -0.040958
ETH  -0.031135
TRX  -0.024020
ADA  -0.013010
VET  -0.000927
ZEC   0.034251
LINK  0.055024
BAT   0.118035
g================================================================         ADA      VET     ZEC   LINK     BAT
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  1.4039  0.08348  118.51  19.79  0.6135
721  1.3327  0.07614  109.38  18.44  0.5691
722  1.3497  0.07704  110.99  18.66  0.5695
723  1.3356  0.07591  108.15  18.20  0.5575
724  1.3478  0.07768  110.82  18.38  0.5623

[725 rows x 5 columns]
ADA    -0.039464
VET    -0.063355
ZEC    -0.029329
LINK    0.020045
BAT     0.081424
Name: 320, dtype: float64
報酬 -0.006136078848343951 %
i= ADA    -0.039464
VET    -0.063355
ZEC    -0.029329
LINK    0.020045
BAT     0.081424
Name: 320, dtype: float64
牛式===============================
執行第 327
           327
ALGO -0.138716
QTUM -0.119695
ICX  -0.118332
ZIL  -0.105736
XLM  -0.105454
IOTA -0.100732
LTC  -0.083277
BCH  -0.075883
ETH  -0.075192
NEO  -0.069352
ATOM -0.066914
BNB  -0.066667
XRP  -0.064511
ZRX  -0.064352
VET  -0.063355
ADA  -0.039464
TRX  -0.036020
ZEC  -0.029329
LINK  0.020045
BAT   0.081424
g================================================================         ADA      TRX     ZEC   LINK     BAT
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  1.4039  0.06432  118.51  19.79  0.6135
721  1.3327  0.06111  109.38  18.44  0.5691
722  1.3497  0.06219  110.99  18.66  0.5695
723  1.3356  0.06139  108.15  18.20  0.5575
724  1.3478  0.06184  110.82  18.38  0.5623

[725 rows x 5 columns]
ADA     0.013530
TRX    -0.018788
ZEC    -0.100103
LINK   -0.037500
BAT     0.013555
Name: 321, dtype: float64
報酬 -0.0258611358434095 %
i= ADA     0.013530
TRX    -0.018788
ZEC    -0.100103
LINK   -0.037500
BAT     0.013555
Name: 321, dtype: float64
牛式===============================
執行第 328
           328
ALGO -0.140907
ZEC  -0.100103
XLM  -0.084049
ICX  -0.080211
LTC  -0.077123
ZIL  -0.073484
QTUM -0.069599
NEO  -0.065514
BCH  -0.065016
ETH  -0.062963
XRP  -0.061789
IOTA -0.060778
BNB  -0.056742
ZRX  -0.052055
ATOM -0.047224
LINK -0.037500
VET  -0.024037
TRX  -0.018788
ADA   0.013530
BAT   0.013555
g================================================================       LINK      VET      TRX     ADA     BAT
0      NaN      NaN      NaN     NaN     NaN
1      NaN      NaN      NaN     NaN     NaN
2      NaN      NaN      NaN     NaN     NaN
3      NaN      NaN      NaN     NaN     NaN
4      NaN      NaN      NaN     NaN     NaN
..     ...      ...      ...     ...     ...
720  19.79  0.08348  0.06432  1.4039  0.6135
721  18.44  0.07614  0.06111  1.3327  0.5691
722  18.66  0.07704  0.06219  1.3497  0.5695
723  18.20  0.07591  0.06139  1.3356  0.5575
724  18.38  0.07768  0.06184  1.3478  0.5623

[725 rows x 5 columns]
LINK   -0.031847
VET    -0.017025
TRX     0.028266
ADA     0.006781
BAT     0.010052
Name: 322, dtype: float64
報酬 -0.0007543636766619733 %
i= LINK   -0.031847
VET    -0.017025
TRX     0.028266
ADA     0.006781
BAT     0.010052
Name: 322, dtype: float64
牛式===============================
執行第 329
           329
ALGO -0.127044
ZIL  -0.106886
ICX  -0.086641
ZEC  -0.066763
QTUM -0.053026
BCH  -0.045705
XRP  -0.044803
NEO  -0.042192
ETH  -0.038693
BNB  -0.036875
LINK -0.031847
ATOM -0.030993
XLM  -0.029898
ZRX  -0.025604
VET  -0.017025
LTC  -0.016611
ADA   0.006781
BAT   0.010052
IOTA  0.026352
TRX   0.028266
g================================================================         LTC     ADA     BAT    IOTA      TRX
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  137.39  1.4039  0.6135  0.8896  0.06432
721  132.25  1.3327  0.5691  0.8165  0.06111
722  134.42  1.3497  0.5695  0.8180  0.06219
723  134.00  1.3356  0.5575  0.7913  0.06139
724  134.19  1.3478  0.5623  0.8404  0.06184

[725 rows x 5 columns]
LTC     0.017196
ADA     0.187967
BAT    -0.052476
IOTA    0.046300
TRX     0.060377
Name: 323, dtype: float64
報酬 0.05187309917586576 %
i= LTC     0.017196
ADA     0.187967
BAT    -0.052476
IOTA    0.046300
TRX     0.060377
Name: 323, dtype: float64
牛式===============================
執行第 330
           330
ALGO -0.086957
ZIL  -0.074349
ZEC  -0.073127
BAT  -0.052476
ICX  -0.037979
BCH  -0.037940
QTUM -0.035506
XRP  -0.028090
LINK -0.020790
NEO  -0.019061
ETH  -0.007268
BNB  -0.006285
ZRX   0.002685
XLM   0.011547
ATOM  0.013338
LTC   0.017196
IOTA  0.046300
TRX   0.060377
VET   0.062148
ADA   0.187967
g================================================================         LTC    IOTA      TRX      VET     ADA
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  137.39  0.8896  0.06432  0.08348  1.4039
721  132.25  0.8165  0.06111  0.07614  1.3327
722  134.42  0.8180  0.06219  0.07704  1.3497
723  134.00  0.7913  0.06139  0.07591  1.3356
724  134.19  0.8404  0.06184  0.07768  1.3478

[725 rows x 5 columns]
LTC     0.037539
IOTA    0.066047
TRX     0.046086
VET     0.068187
ADA     0.153188
Name: 324, dtype: float64
報酬 0.07420912619988096 %
i= LTC     0.037539
IOTA    0.066047
TRX     0.046086
VET     0.068187
ADA     0.153188
Name: 324, dtype: float64
牛式===============================
執行第 331
           331
BAT  -0.109599
ALGO -0.081275
ZEC  -0.081149
BCH  -0.048197
XRP  -0.042354
ZIL  -0.028620
NEO  -0.026677
BNB  -0.025999
ZRX  -0.022979
QTUM -0.018474
ETH  -0.013680
XLM   0.009858
ATOM  0.014111
LINK  0.023454
LTC   0.037539
TRX   0.046086
ICX   0.062041
IOTA  0.066047
VET   0.068187
ADA   0.153188
g================================================================          TRX     ICX    IOTA      VET     ADA
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.06432  0.9279  0.8896  0.08348  1.4039
721  0.06111  1.0350  0.8165  0.07614  1.3327
722  0.06219  0.9786  0.8180  0.07704  1.3497
723  0.06139  0.9198  0.7913  0.07591  1.3356
724  0.06184  0.9519  0.8404  0.07768  1.3478

[725 rows x 5 columns]
TRX     0.075777
ICX     0.203336
IOTA    0.110290
VET     0.187631
ADA     0.247868
Name: 325, dtype: float64
報酬 0.16498032104683252 %
i= TRX     0.075777
ICX     0.203336
IOTA    0.110290
VET     0.187631
ADA     0.247868
Name: 325, dtype: float64
牛式===============================
執行第 332
           332
BAT  -0.107051
ZEC  -0.020482
ALGO -0.007310
XRP   0.007138
NEO   0.007832
BNB   0.009914
ETH   0.017969
BCH   0.021119
QTUM  0.036755
XLM   0.067867
LINK  0.072562
ZIL   0.074448
TRX   0.075777
LTC   0.098090
ATOM  0.107452
IOTA  0.110290
ZRX   0.146165
VET   0.187631
ICX   0.203336
ADA   0.247868
g================================================================        IOTA     ZRX      VET     ICX     ADA
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  0.8896  0.7889  0.08348  0.9279  1.4039
721  0.8165  0.8190  0.07614  1.0350  1.3327
722  0.8180  0.8384  0.07704  0.9786  1.3497
723  0.7913  0.7890  0.07591  0.9198  1.3356
724  0.8404  0.7950  0.07768  0.9519  1.3478

[725 rows x 5 columns]
IOTA    0.152226
ZRX     0.168929
VET     0.441390
ICX     0.167594
ADA     0.244397
Name: 326, dtype: float64
報酬 0.2349071940234561 %
i= IOTA    0.152226
ZRX     0.168929
VET     0.441390
ICX     0.167594
ADA     0.244397
Name: 326, dtype: float64
牛式===============================
執行第 333
           333
BAT  -0.054484
ZEC  -0.009815
NEO  -0.007760
XRP   0.006213
BNB   0.010390
BCH   0.011673
ETH   0.019526
ALGO  0.046635
QTUM  0.047590
LINK  0.052402
XLM   0.057698
TRX   0.065231
ZIL   0.066369
ATOM  0.109960
IOTA  0.152226
ICX   0.167594
ZRX   0.168929
ADA   0.244397
LTC   0.250644
VET   0.441390
g================================================================         ICX     ZRX     ADA     LTC      VET
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.9279  0.7889  1.4039  137.39  0.08348
721  1.0350  0.8190  1.3327  132.25  0.07614
722  0.9786  0.8384  1.3497  134.42  0.07704
723  0.9198  0.7890  1.3356  134.00  0.07591
724  0.9519  0.7950  1.3478  134.19  0.07768

[725 rows x 5 columns]
ICX    0.166667
ZRX    0.211561
ADA    0.171037
LTC    0.277934
VET    0.649212
Name: 327, dtype: float64
報酬 0.2952820456534302 %
i= ICX    0.166667
ZRX    0.211561
ADA    0.171037
LTC    0.277934
VET    0.649212
Name: 327, dtype: float64
牛式===============================
執行第 334
           334
BAT  -0.055407
ZEC  -0.020798
BCH  -0.010708
NEO  -0.010575
XRP  -0.001411
ETH   0.000395
BNB   0.003234
ALGO  0.008411
LINK  0.030303
ZIL   0.034387
XLM   0.034430
TRX   0.050031
QTUM  0.067026
IOTA  0.101490
ATOM  0.113507
ICX   0.166667
ADA   0.171037
ZRX   0.211561
LTC   0.277934
VET   0.649212
g================================================================         ICX     ADA     ZRX     LTC      VET
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.9279  1.4039  0.7889  137.39  0.08348
721  1.0350  1.3327  0.8190  132.25  0.07614
722  0.9786  1.3497  0.8384  134.42  0.07704
723  0.9198  1.3356  0.7890  134.00  0.07591
724  0.9519  1.3478  0.7950  134.19  0.07768

[725 rows x 5 columns]
ICX    0.216281
ADA    0.264253
ZRX    0.194386
LTC    0.257468
VET    0.633122
Name: 328, dtype: float64
報酬 0.31310219006366846 %
i= ICX    0.216281
ADA    0.264253
ZRX    0.194386
LTC    0.257468
VET    0.633122
Name: 328, dtype: float64
牛式===============================
執行第 335
           335
BAT   0.038217
NEO   0.054016
BNB   0.057755
ETH   0.070703
XLM   0.073309
XRP   0.076690
ZEC   0.080288
BCH   0.091282
IOTA  0.091633
ZIL   0.093786
ALGO  0.099904
TRX   0.100794
QTUM  0.108947
ATOM  0.164162
LINK  0.175439
ZRX   0.194386
ICX   0.216281
LTC   0.257468
ADA   0.264253
VET   0.633122
g================================================================         ZRX     ICX     LTC     ADA      VET
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.7889  0.9279  137.39  1.4039  0.08348
721  0.8190  1.0350  132.25  1.3327  0.07614
722  0.8384  0.9786  134.42  1.3497  0.07704
723  0.7890  0.9198  134.00  1.3356  0.07591
724  0.7950  0.9519  134.19  1.3478  0.07768

[725 rows x 5 columns]
ZRX    0.214222
ICX    0.317497
LTC    0.196038
ADA    0.213615
VET    0.836973
Name: 329, dtype: float64
報酬 0.35566912352532104 %
i= ZRX    0.214222
ICX    0.317497
LTC    0.196038
ADA    0.213615
VET    0.836973
Name: 329, dtype: float64
牛式===============================
執行第 336
           336
BAT  -0.007410
TRX   0.020759
ETH   0.036995
NEO   0.041626
XRP   0.048906
IOTA  0.060738
ZEC   0.062500
BNB   0.062619
BCH   0.063358
XLM   0.075223
ALGO  0.087302
QTUM  0.090525
ZIL   0.167527
LTC   0.196038
ADA   0.213615
ZRX   0.214222
LINK  0.214437
ATOM  0.221888
ICX   0.317497
VET   0.836973
g================================================================         ZRX   LINK    ATOM     ICX      VET
0       NaN    NaN     NaN     NaN      NaN
1       NaN    NaN     NaN     NaN      NaN
2       NaN    NaN     NaN     NaN      NaN
3       NaN    NaN     NaN     NaN      NaN
4       NaN    NaN     NaN     NaN      NaN
..      ...    ...     ...     ...      ...
720  0.7889  19.79  12.946  0.9279  0.08348
721  0.8190  18.44  11.958  1.0350  0.07614
722  0.8384  18.66  13.182  0.9786  0.07704
723  0.7890  18.20  14.395  0.9198  0.07591
724  0.7950  18.38  14.064  0.9519  0.07768

[725 rows x 5 columns]
ZRX     0.299361
LINK    0.354167
ATOM    0.336593
ICX     0.243090
VET     1.090310
Name: 330, dtype: float64
報酬 0.4647041567769157 %
i= ZRX     0.299361
LINK    0.354167
ATOM    0.336593
ICX     0.243090
VET     1.090310
Name: 330, dtype: float64

牛式===============================
執行第 337
           337
TRX   0.080869
BAT   0.090458
ETH   0.091034
BCH   0.108106
NEO   0.115478
IOTA  0.119110
BNB   0.123698
ZEC   0.131887
LTC   0.151165
XRP   0.175535
ZIL   0.204506
ALGO  0.206256
QTUM  0.225865
ICX   0.243090
XLM   0.262831
ZRX   0.299361
ATOM  0.336593
LINK  0.354167
ADA   0.397763
VET   1.090310
g================================================================         ZRX    ATOM   LINK     ADA      VET
0       NaN     NaN    NaN     NaN      NaN
1       NaN     NaN    NaN     NaN      NaN
2       NaN     NaN    NaN     NaN      NaN
3       NaN     NaN    NaN     NaN      NaN
4       NaN     NaN    NaN     NaN      NaN
..      ...     ...    ...     ...      ...
720  0.7889  12.946  19.79  1.4039  0.08348
721  0.8190  11.958  18.44  1.3327  0.07614
722  0.8384  13.182  18.66  1.3497  0.07704
723  0.7890  14.395  18.20  1.3356  0.07591
724  0.7950  14.064  18.38  1.3478  0.07768

[725 rows x 5 columns]
ZRX     0.115980
ATOM    0.408178
LINK    0.285412
ADA     0.284279
VET     0.781729
Name: 331, dtype: float64
報酬 0.3751158646448945 %
i= ZRX     0.115980
ATOM    0.408178
LINK    0.285412
ADA     0.284279
VET     0.781729
Name: 331, dtype: float64
牛式===============================
執行第 338
           338
ETH   0.076253
BCH   0.077933
BAT   0.080198
NEO   0.100920
BNB   0.102094
ZEC   0.111198
ZRX   0.115980
TRX   0.116797
IOTA  0.129933
LTC   0.139010
ICX   0.147449
XRP   0.148835
ZIL   0.162654
ALGO  0.184585
ADA   0.284279
LINK  0.285412
QTUM  0.301956
XLM   0.347904
ATOM  0.408178
VET   0.781729
g================================================================       LINK   QTUM      XLM    ATOM      VET
0      NaN    NaN      NaN     NaN      NaN
1      NaN    NaN      NaN     NaN      NaN
2      NaN    NaN      NaN     NaN      NaN
3      NaN    NaN      NaN     NaN      NaN
4      NaN    NaN      NaN     NaN      NaN
..     ...    ...      ...     ...      ...
720  19.79  7.079  0.25677  12.946  0.08348
721  18.44  6.504  0.24383  11.958  0.07614
722  18.66  6.776  0.24550  13.182  0.07704
723  18.20  6.639  0.24484  14.395  0.07591
724  18.38  6.694  0.24587  14.064  0.07768

[725 rows x 5 columns]
LINK    0.273859
QTUM    0.201180
XLM     0.307749
ATOM    0.458004
VET     0.367119
Name: 332, dtype: float64
報酬 0.3215821888963918 %
i= LINK    0.273859
QTUM    0.201180
XLM     0.307749
ATOM    0.458004
VET     0.367119
Name: 332, dtype: float64
牛式===============================
執行第 339
           339
BAT   0.018407
ZIL   0.028766
IOTA  0.041545
ETH   0.052046
NEO   0.052742
BCH   0.057646
ZRX   0.061935
LTC   0.067196
TRX   0.076694
ZEC   0.089796
BNB   0.111825
XRP   0.117030
ALGO  0.148829
ADA   0.185193
ICX   0.197141
QTUM  0.201180
LINK  0.273859
XLM   0.307749
VET   0.367119
ATOM  0.458004
g================================================================       QTUM   LINK      XLM      VET    ATOM
0      NaN    NaN      NaN      NaN     NaN
1      NaN    NaN      NaN      NaN     NaN
2      NaN    NaN      NaN      NaN     NaN
3      NaN    NaN      NaN      NaN     NaN
4      NaN    NaN      NaN      NaN     NaN
..     ...    ...      ...      ...     ...
720  7.079  19.79  0.25677  0.08348  12.946
721  6.504  18.44  0.24383  0.07614  11.958
722  6.776  18.66  0.24550  0.07704  13.182
723  6.639  18.20  0.24484  0.07591  14.395
724  6.694  18.38  0.24587  0.07768  14.064

[725 rows x 5 columns]
QTUM    0.166012
LINK    0.281513
XLM     0.400000
VET     0.293371
ATOM    0.332654
Name: 333, dtype: float64
報酬 0.294709849952005 %
i= QTUM    0.166012
LINK    0.281513
XLM     0.400000
VET     0.293371
ATOM    0.332654
Name: 333, dtype: float64
牛式===============================
執行第 340
           340
ZRX   0.040553
BAT   0.042880
ETH   0.049311
IOTA  0.056213
BCH   0.062609
NEO   0.062939
ZIL   0.071850
TRX   0.080588
LTC   0.081117
ZEC   0.087101
BNB   0.136041
XRP   0.136592
ICX   0.165657
QTUM  0.166012
ADA   0.274606
LINK  0.281513
VET   0.293371
ALGO  0.294717
ATOM  0.332654
XLM   0.400000
g================================================================       LINK      VET    ALGO    ATOM      XLM
0      NaN      NaN     NaN     NaN      NaN
1      NaN      NaN     NaN     NaN      NaN
2      NaN      NaN     NaN     NaN      NaN
3      NaN      NaN     NaN     NaN      NaN
4      NaN      NaN     NaN     NaN      NaN
..     ...      ...     ...     ...      ...
720  19.79  0.08348  0.9062  12.946  0.25677
721  18.44  0.07614  0.8683  11.958  0.24383
722  18.66  0.07704  0.9059  13.182  0.24550
723  18.20  0.07591  0.8918  14.395  0.24484
724  18.38  0.07768  0.8952  14.064  0.24587

[725 rows x 5 columns]
LINK    0.371269
VET     0.258404
ALGO    0.220087
ATOM    0.331016
XLM     0.331196
Name: 334, dtype: float64
報酬 0.30239451578681165 %
i= LINK    0.371269
VET     0.258404
ALGO    0.220087
ATOM    0.331016
XLM     0.331196
Name: 334, dtype: float64
牛式===============================
執行第 341
           341
BCH  -0.019776
BAT  -0.003067
ETH   0.005382
TRX   0.008324
IOTA  0.018248
NEO   0.020234
ZIL   0.023146
LTC   0.050481
ZEC   0.056325
XRP   0.066299
ZRX   0.070250
QTUM  0.122393
BNB   0.122699
ICX   0.128191
ADA   0.207211
ALGO  0.220087
VET   0.258404
ATOM  0.331016
XLM   0.331196
LINK  0.371269
g================================================================        ALGO      VET    ATOM      XLM   LINK
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  0.9062  0.08348  12.946  0.25677  19.79
721  0.8683  0.07614  11.958  0.24383  18.44
722  0.9059  0.07704  13.182  0.24550  18.66
723  0.8918  0.07591  14.395  0.24484  18.20
724  0.8952  0.07768  14.064  0.24587  18.38

[725 rows x 5 columns]
ALGO    0.139545
VET     0.065147
ATOM    0.191136
XLM     0.227168
LINK    0.253497
Name: 335, dtype: float64
報酬 0.17529836033480534 %
i= ALGO    0.139545
VET     0.065147
ATOM    0.191136
XLM     0.227168
LINK    0.253497
Name: 335, dtype: float64
牛式===============================
執行第 342
           342
BCH  -0.023631
ZRX  -0.018378
ZIL  -0.015725
ETH   0.001337
NEO   0.010038
IOTA  0.018405
TRX   0.020337
BAT   0.034971
ICX   0.050279
ADA   0.056689
VET   0.065147
XRP   0.073748
LTC   0.094375
BNB   0.096429
ZEC   0.111837
ALGO  0.139545
ATOM  0.191136
QTUM  0.224682
XLM   0.227168
LINK  0.253497
g================================================================        ALGO    ATOM   QTUM      XLM   LINK
0       NaN     NaN    NaN      NaN    NaN
1       NaN     NaN    NaN      NaN    NaN
2       NaN     NaN    NaN      NaN    NaN
3       NaN     NaN    NaN      NaN    NaN
4       NaN     NaN    NaN      NaN    NaN
..      ...     ...    ...      ...    ...
720  0.9062  12.946  7.079  0.25677  19.79
721  0.8683  11.958  6.504  0.24383  18.44
722  0.9059  13.182  6.776  0.24550  18.66
723  0.8918  14.395  6.639  0.24484  18.20
724  0.8952  14.064  6.694  0.24587  18.38

[725 rows x 5 columns]
ALGO    0.102917
ATOM    0.113956
QTUM    0.162457
XLM     0.078707
LINK    0.250769
Name: 336, dtype: float64
報酬 0.14176125947787277 %
i= ALGO    0.102917
ATOM    0.113956
QTUM    0.162457
XLM     0.078707
LINK    0.250769
Name: 336, dtype: float64
牛式===============================
執行第 343
           343
ZRX  -0.117542
VET  -0.076746
BCH  -0.054204
ZIL  -0.051319
XRP  -0.030566
IOTA -0.030019
ETH  -0.026882
NEO  -0.021771
TRX  -0.014517
BAT  -0.006061
ADA   0.019546
ICX   0.034108
BNB   0.048667
ZEC   0.070775
XLM   0.078707
ALGO  0.102917
LTC   0.105195
ATOM  0.113956
QTUM  0.162457
LINK  0.250769
g================================================================        ALGO     LTC    ATOM   QTUM   LINK
0       NaN     NaN     NaN    NaN    NaN
1       NaN     NaN     NaN    NaN    NaN
2       NaN     NaN     NaN    NaN    NaN
3       NaN     NaN     NaN    NaN    NaN
4       NaN     NaN     NaN    NaN    NaN
..      ...     ...     ...    ...    ...
720  0.9062  137.39  12.946  7.079  19.79
721  0.8683  132.25  11.958  6.504  18.44
722  0.9059  134.42  13.182  6.776  18.66
723  0.8918  134.00  14.395  6.639  18.20
724  0.8952  134.19  14.064  6.694  18.38

[725 rows x 5 columns]
ALGO    0.193535
LTC     0.086797
ATOM    0.069166
QTUM    0.075587
LINK    0.421053
Name: 337, dtype: float64
報酬 0.1692274355713273 %
i= ALGO    0.193535
LTC     0.086797
ATOM    0.069166
QTUM    0.075587
LINK    0.421053
Name: 337, dtype: float64
牛式===============================
執行第 344
           344
ZRX  -0.083941
TRX  -0.052830
BCH  -0.045218
IOTA -0.037284
ZIL  -0.033333
XRP  -0.026700
ETH  -0.014211
BAT  -0.005358
NEO   0.020619
ICX   0.030840
VET   0.041292
XLM   0.044383
BNB   0.046912
ADA   0.053867
ATOM  0.069166
ZEC   0.075273
QTUM  0.075587
LTC   0.086797
ALGO  0.193535
LINK  0.421053
g================================================================         ZEC   QTUM     LTC    ALGO   LINK
0       NaN    NaN     NaN     NaN    NaN
1       NaN    NaN     NaN     NaN    NaN
2       NaN    NaN     NaN     NaN    NaN
3       NaN    NaN     NaN     NaN    NaN
4       NaN    NaN     NaN     NaN    NaN
..      ...    ...     ...     ...    ...
720  118.51  7.079  137.39  0.9062  19.79
721  109.38  6.504  132.25  0.8683  18.44
722  110.99  6.776  134.42  0.9059  18.66
723  108.15  6.639  134.00  0.8918  18.20
724  110.82  6.694  134.19  0.8952  18.38

[725 rows x 5 columns]
ZEC     0.054575
QTUM    0.134086
LTC     0.053734
ALGO    0.414634
LINK    0.363192
Name: 338, dtype: float64
報酬 0.20404424451425124 %
i= ZEC     0.054575
QTUM    0.134086
LTC     0.053734
ALGO    0.414634
LINK    0.363192
Name: 338, dtype: float64
牛式===============================
執行第 345
           345
ZIL  -0.084392
BCH  -0.059246
TRX  -0.051905
ICX  -0.044527
IOTA -0.037495
ETH  -0.031225
ZRX  -0.028190
XRP  -0.022913
BNB  -0.008671
ATOM  0.004185
NEO   0.018573
BAT   0.022397
VET   0.053590
LTC   0.053734
ZEC   0.054575
ADA   0.063819
QTUM  0.134086
XLM   0.146054
LINK  0.363192
ALGO  0.414634
g================================================================         ADA   QTUM      XLM   LINK    ALGO
0       NaN    NaN      NaN    NaN     NaN
1       NaN    NaN      NaN    NaN     NaN
2       NaN    NaN      NaN    NaN     NaN
3       NaN    NaN      NaN    NaN     NaN
4       NaN    NaN      NaN    NaN     NaN
..      ...    ...      ...    ...     ...
720  1.4039  7.079  0.25677  19.79  0.9062
721  1.3327  6.504  0.24383  18.44  0.8683
722  1.3497  6.776  0.24550  18.66  0.9059
723  1.3356  6.639  0.24484  18.20  0.8918
724  1.3478  6.694  0.24587  18.38  0.8952

[725 rows x 5 columns]
ADA    -0.023876
QTUM    0.152477
XLM     0.103481
LINK    0.354098
ALGO    0.239800
Name: 339, dtype: float64
報酬 0.16519604595717716 %
i= ADA    -0.023876
QTUM    0.152477
XLM     0.103481
LINK    0.354098
ALGO    0.239800
Name: 339, dtype: float64
牛式===============================
執行第 346
           346
ZIL  -0.093547
ZRX  -0.089409
TRX  -0.065324
BCH  -0.059090
IOTA -0.035214
XRP  -0.033115
ICX  -0.032186
BNB  -0.030647
ETH  -0.027176
ADA  -0.023876
VET  -0.017212
NEO  -0.013965
BAT   0.029480
ATOM  0.056604
ZEC   0.066320
LTC   0.102759
XLM   0.103481
QTUM  0.152477
ALGO  0.239800
LINK  0.354098
g================================================================         LTC      XLM   QTUM    ALGO   LINK
0       NaN      NaN    NaN     NaN    NaN
1       NaN      NaN    NaN     NaN    NaN
2       NaN      NaN    NaN     NaN    NaN
3       NaN      NaN    NaN     NaN    NaN
4       NaN      NaN    NaN     NaN    NaN
..      ...      ...    ...     ...    ...
720  137.39  0.25677  7.079  0.9062  19.79
721  132.25  0.24383  6.504  0.8683  18.44
722  134.42  0.24550  6.776  0.9059  18.66
723  134.00  0.24484  6.639  0.8918  18.20
724  134.19  0.24587  6.694  0.8952  18.38

[725 rows x 5 columns]
LTC     0.085341
XLM     0.055602
QTUM    0.155990
ALGO    0.273443
LINK    0.084354
Name: 340, dtype: float64
報酬 0.13094607568814043 %
i= LTC     0.085341
XLM     0.055602
QTUM    0.155990
ALGO    0.273443
LINK    0.084354
Name: 340, dtype: float64
牛式===============================
執行第 347
           347
ZIL  -0.079692
BNB  -0.063934
BCH  -0.055092
IOTA -0.049781
TRX  -0.041277
ADA  -0.033178
ETH  -0.029608
ICX  -0.024635
ZRX  -0.023593
NEO  -0.022706
XRP  -0.006312
VET   0.001487
ZEC   0.006133
BAT   0.036538
XLM   0.055602
ATOM  0.084307
LINK  0.084354
LTC   0.085341
QTUM  0.155990
ALGO  0.273443
g================================================================        ATOM   LINK     LTC   QTUM    ALGO
0       NaN    NaN     NaN    NaN     NaN
1       NaN    NaN     NaN    NaN     NaN
2       NaN    NaN     NaN    NaN     NaN
3       NaN    NaN     NaN    NaN     NaN
4       NaN    NaN     NaN    NaN     NaN
..      ...    ...     ...    ...     ...
720  12.946  19.79  137.39  7.079  0.9062
721  11.958  18.44  132.25  6.504  0.8683
722  13.182  18.66  134.42  6.776  0.9059
723  14.395  18.20  134.00  6.639  0.8918
724  14.064  18.38  134.19  6.694  0.8952

[725 rows x 5 columns]
ATOM    0.085013
LINK    0.128312
LTC     0.084671
QTUM    0.061003
ALGO    0.465335
Name: 341, dtype: float64
報酬 0.16486688385890483 %
i= ATOM    0.085013
LINK    0.128312
LTC     0.084671
QTUM    0.061003
ALGO    0.465335
Name: 341, dtype: float64

牛式===============================
執行第 348
           348
ZIL  -0.104843
ZEC  -0.046538
VET  -0.023728
BNB  -0.022258
BCH  -0.019811
IOTA -0.004016
ADA  -0.003217
ETH  -0.003087
NEO  -0.002063
TRX  -0.001708
XRP   0.003321
ICX   0.019342
BAT   0.041382
ZRX   0.048178
QTUM  0.061003
LTC   0.084671
ATOM  0.085013
XLM   0.110027
LINK  0.128312
ALGO  0.465335
g================================================================         LTC    ATOM      XLM   LINK    ALGO
0       NaN     NaN      NaN    NaN     NaN
1       NaN     NaN      NaN    NaN     NaN
2       NaN     NaN      NaN    NaN     NaN
3       NaN     NaN      NaN    NaN     NaN
4       NaN     NaN      NaN    NaN     NaN
..      ...     ...      ...    ...     ...
720  137.39  12.946  0.25677  19.79  0.9062
721  132.25  11.958  0.24383  18.44  0.8683
722  134.42  13.182  0.24550  18.66  0.9059
723  134.00  14.395  0.24484  18.20  0.8918
724  134.19  14.064  0.24587  18.38  0.8952

[725 rows x 5 columns]
LTC    -0.003506
ATOM   -0.019702
XLM     0.024321
LINK   -0.108241
ALGO    0.317046
Name: 342, dtype: float64
報酬 0.04198372275268958 %
i= LTC    -0.003506
ATOM   -0.019702
XLM     0.024321
LINK   -0.108241
ALGO    0.317046
Name: 342, dtype: float64
牛式===============================
執行第 349
           349
ZIL  -0.127907
VET  -0.127806
ADA  -0.111556
LINK -0.108241
ZEC  -0.080123
QTUM -0.052407
NEO  -0.041186
BNB  -0.034807
BCH  -0.032066
TRX  -0.027195
ICX  -0.026387
XRP  -0.022492
ATOM -0.019702
ETH  -0.018180
BAT  -0.014863
LTC  -0.003506
ZRX   0.000760
IOTA  0.005225
XLM   0.024321
ALGO  0.317046
g================================================================         LTC     ZRX    IOTA      XLM    ALGO
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  137.39  0.7889  0.8896  0.25677  0.9062
721  132.25  0.8190  0.8165  0.24383  0.8683
722  134.42  0.8384  0.8180  0.24550  0.9059
723  134.00  0.7890  0.7913  0.24484  0.8918
724  134.19  0.7950  0.8404  0.24587  0.8952

[725 rows x 5 columns]
LTC     0.010676
ZRX     0.027977
IOTA    0.081533
XLM     0.019712
ALGO    0.202431
Name: 343, dtype: float64
報酬 0.0684656406369469 %
i= LTC     0.010676
ZRX     0.027977
IOTA    0.081533
XLM     0.019712
ALGO    0.202431
Name: 343, dtype: float64
牛式===============================
執行第 350
           350
LINK -0.153935
VET  -0.079046
ZIL  -0.060084
ADA  -0.057847
ATOM -0.010864
TRX   0.002277
BAT   0.003078
BNB   0.005105
LTC   0.010676
XRP   0.010953
BCH   0.012357
NEO   0.017745
XLM   0.019712
ZEC   0.020445
QTUM  0.025316
ICX   0.026178
ZRX   0.027977
ETH   0.028958
IOTA  0.081533
ALGO  0.202431
g================================================================         ICX     ZRX      ETH    IOTA    ALGO
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  0.9279  0.7889  2316.15  0.8896  0.9062
721  1.0350  0.8190  2121.52  0.8165  0.8683
722  0.9786  0.8384  2146.27  0.8180  0.9059
723  0.9198  0.7890  2111.19  0.7913  0.8918
724  0.9519  0.7950  2138.86  0.8404  0.8952

[725 rows x 5 columns]
ICX     0.074720
ZRX    -0.001250
ETH     0.130211
IOTA    0.154994
ALGO   -0.022046
Name: 344, dtype: float64
報酬 0.06732573933752084 %
i= ICX     0.074720
ZRX    -0.001250
ETH     0.130211
IOTA    0.154994
ALGO   -0.022046
Name: 344, dtype: float64
牛式===============================
執行第 351
           351
LINK -0.107527
XLM  -0.044246
LTC  -0.041579
VET  -0.032137
ALGO -0.022046
ADA  -0.017061
ATOM -0.016426
ZRX  -0.001250
BAT   0.007302
QTUM  0.029017
ZIL   0.043309
TRX   0.044846
XRP   0.046696
BNB   0.055394
BCH   0.069355
ICX   0.074720
NEO   0.081915
ZEC   0.086758
ETH   0.130211
IOTA  0.154994
g================================================================         ICX     NEO     ZEC      ETH    IOTA
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.9279  37.005  118.51  2316.15  0.8896
721  1.0350  34.083  109.38  2121.52  0.8165
722  0.9786  34.637  110.99  2146.27  0.8180
723  0.9198  34.057  108.15  2111.19  0.7913
724  0.9519  34.191  110.82  2138.86  0.8404

[725 rows x 5 columns]
ICX     0.044257
NEO     0.079313
ZEC     0.067406
ETH     0.183299
IOTA    0.159685
Name: 345, dtype: float64
報酬 0.10679189666582527 %
i= ICX     0.044257
NEO     0.079313
ZEC     0.067406
ETH     0.183299
IOTA    0.159685
Name: 345, dtype: float64
牛式===============================
執行第 352
           352
XLM  -0.056459
LTC  -0.048934
ALGO -0.048788
VET  -0.045183
ATOM -0.044643
LINK -0.043584
QTUM -0.015860
ZRX  -0.011329
BAT  -0.003391
ADA   0.015952
TRX   0.043098
ICX   0.044257
ZEC   0.067406
BCH   0.071156
XRP   0.071634
NEO   0.079313
ZIL   0.084437
BNB   0.098361
IOTA  0.159685
ETH   0.183299
g================================================================         NEO      ZIL     BNB    IOTA      ETH
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  37.005  0.08133  327.67  0.8896  2316.15
721  34.083  0.07509  310.59  0.8165  2121.52
722  34.637  0.07496  316.72  0.8180  2146.27
723  34.057  0.07299  316.09  0.7913  2111.19
724  34.191  0.07377  321.87  0.8404  2138.86

[725 rows x 5 columns]
NEO     0.051494
ZIL     0.029609
BNB     0.119673
IOTA    0.119028
ETH     0.184723
Name: 346, dtype: float64
報酬 0.10090527864371826 %
i= NEO     0.051494
ZIL     0.029609
BNB     0.119673
IOTA    0.119028
ETH     0.184723
Name: 346, dtype: float64
牛式===============================
執行第 353
           353
ATOM -0.124312
LTC  -0.123031
ALGO -0.122822
ZRX  -0.074880
LINK -0.066499
VET  -0.065284
XLM  -0.050987
BAT  -0.043785
QTUM -0.032572
ADA  -0.005950
ICX   0.016495
XRP   0.020107
ZIL   0.029609
TRX   0.029851
BCH   0.047651
NEO   0.051494
ZEC   0.066881
IOTA  0.119028
BNB   0.119673
ETH   0.184723
g================================================================         NEO     ZEC    IOTA     BNB      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  37.005  118.51  0.8896  327.67  2316.15
721  34.083  109.38  0.8165  310.59  2121.52
722  34.637  110.99  0.8180  316.72  2146.27
723  34.057  108.15  0.7913  316.09  2111.19
724  34.191  110.82  0.8404  321.87  2138.86

[725 rows x 5 columns]
NEO     0.090661
ZEC     0.124679
IOTA    0.110887
BNB     0.099389
ETH     0.278331
Name: 347, dtype: float64
報酬 0.1407895430554833 %
i= NEO     0.090661
ZEC     0.124679
IOTA    0.110887
BNB     0.099389
ETH     0.278331
Name: 347, dtype: float64
牛式===============================
執行第 354
           354
ALGO -0.179223
LTC  -0.165023
ATOM -0.067635
ZRX  -0.063110
ICX  -0.054080
LINK -0.051916
BAT  -0.038644
XLM   0.005196
VET   0.010932
QTUM  0.025554
ZIL   0.037368
TRX   0.070736
XRP   0.075928
NEO   0.090661
BNB   0.099389
BCH   0.102153
IOTA  0.110887
ZEC   0.124679
ADA   0.158557
ETH   0.278331
g================================================================         BCH    IOTA     ZEC     ADA      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  509.55  0.8896  118.51  1.4039  2316.15
721  490.60  0.8165  109.38  1.3327  2121.52
722  504.08  0.8180  110.99  1.3497  2146.27
723  497.02  0.7913  108.15  1.3356  2111.19
724  498.00  0.8404  110.82  1.3478  2138.86

[725 rows x 5 columns]
BCH     0.110922
IOTA    0.075170
ZEC     0.160007
ADA     0.258347
ETH     0.318178
Name: 348, dtype: float64
報酬 0.18452465421467962 %
i= BCH     0.110922
IOTA    0.075170
ZEC     0.160007
ADA     0.258347
ETH     0.318178
Name: 348, dtype: float64
牛式===============================
執行第 355
           355
ALGO -0.104045
LTC  -0.045348
ICX  -0.030615
ZRX  -0.025810
ATOM -0.018294
BAT  -0.016634
LINK  0.033103
ZIL   0.042319
XLM   0.047700
QTUM  0.060252
IOTA  0.075170
TRX   0.078626
VET   0.091887
XRP   0.105701
BCH   0.110922
NEO   0.119137
BNB   0.119634
ZEC   0.160007
ADA   0.258347
ETH   0.318178
g================================================================         NEO     BNB     ZEC     ADA      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  37.005  327.67  118.51  1.4039  2316.15
721  34.083  310.59  109.38  1.3327  2121.52
722  34.637  316.72  110.99  1.3497  2146.27
723  34.057  316.09  108.15  1.3356  2111.19
724  34.191  321.87  110.82  1.3478  2138.86

[725 rows x 5 columns]
NEO    0.038895
BNB    0.117381
ZEC    0.134316
ADA    0.127101
ETH    0.309820
Name: 349, dtype: float64
報酬 0.14550274959475074 %
i= NEO    0.038895
BNB    0.117381
ZEC    0.134316
ADA    0.127101
ETH    0.309820
Name: 349, dtype: float64
牛式===============================
執行第 356
           356
ALGO -0.170373
VET  -0.106016
ATOM -0.104094
ICX  -0.102527
ZRX  -0.084395
ZIL  -0.059477
BAT  -0.047948
LINK -0.030096
XLM  -0.016525
QTUM -0.012771
LTC   0.000000
IOTA  0.024124
NEO   0.038895
TRX   0.063032
BNB   0.117381
XRP   0.124643
ADA   0.127101
ZEC   0.134316
BCH   0.165798
ETH   0.309820
g================================================================         XRP     ADA     ZEC     BCH      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.6521  1.4039  118.51  509.55  2316.15
721  0.6236  1.3327  109.38  490.60  2121.52
722  0.6372  1.3497  110.99  504.08  2146.27
723  0.6251  1.3356  108.15  497.02  2111.19
724  0.6362  1.3478  110.82  498.00  2138.86

[725 rows x 5 columns]
XRP    0.131479
ADA    0.203116
ZEC    0.099440
BCH    0.205914
ETH    0.199970
Name: 350, dtype: float64
報酬 0.1679838568035909 %
i= XRP    0.131479
ADA    0.203116
ZEC    0.099440
BCH    0.205914
ETH    0.199970
Name: 350, dtype: float64
牛式===============================
執行第 357
           357
ALGO -0.092486
VET  -0.084841
ICX  -0.078973
ATOM -0.065055
ZRX  -0.043065
ZIL  -0.042044
BAT  -0.041587
LINK -0.032129
IOTA -0.025834
XLM  -0.003593
QTUM -0.000842
NEO   0.015039
TRX   0.065775
LTC   0.087722
ZEC   0.099440
BNB   0.114365
XRP   0.131479
ETH   0.199970
ADA   0.203116
BCH   0.205914
g================================================================         BNB     XRP      ETH     ADA     BCH
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  327.67  0.6521  2316.15  1.4039  509.55
721  310.59  0.6236  2121.52  1.3327  490.60
722  316.72  0.6372  2146.27  1.3497  504.08
723  316.09  0.6251  2111.19  1.3356  497.02
724  321.87  0.6362  2138.86  1.3478  498.00

[725 rows x 5 columns]
BNB    0.056503
XRP    0.167474
ETH    0.151745
ADA    0.118931
BCH    0.205452
Name: 351, dtype: float64
報酬 0.14002107424157564 %
i= BNB    0.056503
XRP    0.167474
ETH    0.151745
ADA    0.118931
BCH    0.205452
Name: 351, dtype: float64
牛式===============================
執行第 358
           358
LINK -0.106329
VET  -0.103323
ZIL  -0.102799
ATOM -0.082597
ICX  -0.079128
ALGO -0.069196
BAT  -0.064650
XLM  -0.031804
LTC  -0.020347
ZRX  -0.019353
QTUM -0.001696
IOTA  0.021102
NEO   0.021258
BNB   0.056503
TRX   0.077052
ADA   0.118931
ZEC   0.131654
ETH   0.151745
XRP   0.167474
BCH   0.205452
g================================================================         ADA     ZEC      ETH     XRP     BCH
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  1.4039  118.51  2316.15  0.6521  509.55
721  1.3327  109.38  2121.52  0.6236  490.60
722  1.3497  110.99  2146.27  0.6372  504.08
723  1.3356  108.15  2111.19  0.6251  497.02
724  1.3478  110.82  2138.86  0.6362  498.00

[725 rows x 5 columns]
ADA    0.151866
ZEC    0.118076
ETH    0.199298
XRP    0.196960
BCH    0.240778
Name: 352, dtype: float64
報酬 0.18139555414076985 %
i= ADA    0.151866
ZEC    0.118076
ETH    0.199298
XRP    0.196960
BCH    0.240778
Name: 352, dtype: float64
牛式===============================
執行第 359
           359
ICX  -0.058063
BAT  -0.041133
ATOM -0.030120
ZIL  -0.015193
LINK -0.004032
ZRX   0.003103
LTC   0.004808
XLM   0.006481
VET   0.018829
QTUM  0.037604
BNB   0.042231
NEO   0.061869
TRX   0.068562
ALGO  0.071772
ZEC   0.118076
IOTA  0.123970
ADA   0.151866
XRP   0.196960
ETH   0.199298
BCH   0.240778
g================================================================        IOTA     ADA     XRP      ETH     BCH
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.8896  1.4039  0.6521  2316.15  509.55
721  0.8165  1.3327  0.6236  2121.52  490.60
722  0.8180  1.3497  0.6372  2146.27  504.08
723  0.7913  1.3356  0.6251  2111.19  497.02
724  0.8404  1.3478  0.6362  2138.86  498.00

[725 rows x 5 columns]
IOTA    0.086388
ADA    -0.033083
XRP     0.209052
ETH     0.134088
BCH     0.198206
Name: 353, dtype: float64
報酬 0.11893045217814399 %
i= IOTA    0.086388
ADA    -0.033083
XRP     0.209052
ETH     0.134088
BCH     0.198206
Name: 353, dtype: float64
牛式===============================
執行第 360
           360
LTC  -0.129213
ICX  -0.062688
VET  -0.055659
BAT  -0.040197
XLM  -0.036183
ADA  -0.033083
ZIL  -0.032258
ZRX  -0.032028
ATOM -0.031162
QTUM  0.004983
LINK  0.016949
ALGO  0.024123
BNB   0.043939
TRX   0.047949
NEO   0.055216
IOTA  0.086388
ETH   0.134088
ZEC   0.140399
BCH   0.198206
XRP   0.209052
g================================================================        IOTA      ETH     ZEC     BCH     XRP
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  2316.15  118.51  509.55  0.6521
721  0.8165  2121.52  109.38  490.60  0.6236
722  0.8180  2146.27  110.99  504.08  0.6372
723  0.7913  2111.19  108.15  497.02  0.6251
724  0.8404  2138.86  110.82  498.00  0.6362

[725 rows x 5 columns]
IOTA    0.168464
ETH     0.244045
ZEC     0.347333
BCH     0.291417
XRP     0.351589
Name: 354, dtype: float64
報酬 0.28056975915700355 %

i= IOTA    0.168464
ETH     0.244045
ZEC     0.347333
BCH     0.291417
XRP     0.351589
Name: 354, dtype: float64
牛式===============================
執行第 361
           361
LTC  -0.157794
ADA  -0.025520
VET  -0.013779
ICX  -0.012684
BAT   0.017309
ALGO  0.020859
ZRX   0.035065
ZIL   0.038376
ATOM  0.071916
XLM   0.088426
TRX   0.105292
BNB   0.105317
LINK  0.110814
QTUM  0.125530
NEO   0.152926
IOTA  0.168464
ETH   0.244045
BCH   0.291417
ZEC   0.347333
XRP   0.351589
g================================================================        IOTA      ETH     BCH     ZEC     XRP
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  2316.15  509.55  118.51  0.6521
721  0.8165  2121.52  490.60  109.38  0.6236
722  0.8180  2146.27  504.08  110.99  0.6372
723  0.7913  2111.19  497.02  108.15  0.6251
724  0.8404  2138.86  498.00  110.82  0.6362

[725 rows x 5 columns]
IOTA    0.061465
ETH     0.157929
BCH     0.057044
ZEC     0.191041
XRP     0.284319
Name: 355, dtype: float64
報酬 0.15035963673415007 %
i= IOTA    0.061465
ETH     0.157929
BCH     0.057044
ZEC     0.191041
XRP     0.284319
Name: 355, dtype: float64
牛式===============================
執行第 362
           362
LTC  -0.199358
ADA  -0.036461
BAT  -0.021354
ICX   0.012994
TRX   0.018162
ZRX   0.034906
VET   0.036139
QTUM  0.036223
NEO   0.049402
ALGO  0.050470
ZIL   0.053191
BCH   0.057044
BNB   0.061111
IOTA  0.061465
XLM   0.084223
ATOM  0.090276
ETH   0.157929
LINK  0.167842
ZEC   0.191041
XRP   0.284319
g================================================================        ATOM      ETH   LINK     ZEC     XRP
0       NaN      NaN    NaN     NaN     NaN
1       NaN      NaN    NaN     NaN     NaN
2       NaN      NaN    NaN     NaN     NaN
3       NaN      NaN    NaN     NaN     NaN
4       NaN      NaN    NaN     NaN     NaN
..      ...      ...    ...     ...     ...
720  12.946  2316.15  19.79  118.51  0.6521
721  11.958  2121.52  18.44  109.38  0.6236
722  13.182  2146.27  18.66  110.99  0.6372
723  14.395  2111.19  18.20  108.15  0.6251
724  14.064  2138.86  18.38  110.82  0.6362

[725 rows x 5 columns]
ATOM    0.026926
ETH     0.217523
LINK    0.269710
ZEC     0.164190
XRP     0.344696
Name: 356, dtype: float64
報酬 0.20460884446098815 %
i= ATOM    0.026926
ETH     0.217523
LINK    0.269710
ZEC     0.164190
XRP     0.344696
Name: 356, dtype: float64
牛式===============================
執行第 363
           363
LTC  -0.271416
ADA  -0.079112
ZIL  -0.026667
ALGO -0.014331
ICX  -0.012625
BAT  -0.001592
ZRX  -0.001308
BCH   0.026078
ATOM  0.026926
TRX   0.039226
VET   0.043663
NEO   0.055858
XLM   0.083239
BNB   0.093704
QTUM  0.103623
IOTA  0.106446
ZEC   0.164190
ETH   0.217523
LINK  0.269710
XRP   0.344696
g================================================================        IOTA     ZEC      ETH   LINK     XRP
0       NaN     NaN      NaN    NaN     NaN
1       NaN     NaN      NaN    NaN     NaN
2       NaN     NaN      NaN    NaN     NaN
3       NaN     NaN      NaN    NaN     NaN
4       NaN     NaN      NaN    NaN     NaN
..      ...     ...      ...    ...     ...
720  0.8896  118.51  2316.15  19.79  0.6521
721  0.8165  109.38  2121.52  18.44  0.6236
722  0.8180  110.99  2146.27  18.66  0.6372
723  0.7913  108.15  2111.19  18.20  0.6251
724  0.8404  110.82  2138.86  18.38  0.6362

[725 rows x 5 columns]
IOTA    0.075306
ZEC     0.181325
ETH     0.227997
LINK    0.396601
XRP     0.238769
Name: 357, dtype: float64
報酬 0.22399939734324445 %
i= IOTA    0.075306
ZEC     0.181325
ETH     0.227997
LINK    0.396601
XRP     0.238769
Name: 357, dtype: float64
牛式===============================
執行第 364
           364
LTC  -0.236010
BCH   0.002122
ADA   0.031592
ZRX   0.032459
ZIL   0.044810
ICX   0.056132
TRX   0.057024
BAT   0.059014
ALGO  0.064884
IOTA  0.075306
NEO   0.075981
ATOM  0.103800
BNB   0.125126
XLM   0.159297
ZEC   0.181325
VET   0.200192
QTUM  0.210280
ETH   0.227997
XRP   0.238769
LINK  0.396601
g================================================================          VET   QTUM      ETH     XRP   LINK
0        NaN    NaN      NaN     NaN    NaN
1        NaN    NaN      NaN     NaN    NaN
2        NaN    NaN      NaN     NaN    NaN
3        NaN    NaN      NaN     NaN    NaN
4        NaN    NaN      NaN     NaN    NaN
..       ...    ...      ...     ...    ...
720  0.08348  7.079  2316.15  0.6521  19.79
721  0.07614  6.504  2121.52  0.6236  18.44
722  0.07704  6.776  2146.27  0.6372  18.66
723  0.07591  6.639  2111.19  0.6251  18.20
724  0.07768  6.694  2138.86  0.6362  18.38

[725 rows x 5 columns]
VET     0.085360
QTUM    0.168984
ETH     0.196703
XRP     0.239309
LINK    0.286100
Name: 358, dtype: float64
報酬 0.19529100611158517 %
i= VET     0.085360
QTUM    0.168984
ETH     0.196703
XRP     0.239309
LINK    0.286100
Name: 358, dtype: float64
牛式===============================
執行第 365
           365
LTC  -0.135538
ALGO  0.002990
BCH   0.006652
ADA   0.012601
IOTA  0.016661
ZRX   0.024491
BAT   0.042493
ICX   0.049529
TRX   0.060511
ZIL   0.080441
VET   0.085360
NEO   0.092917
XLM   0.115588
ATOM  0.119093
BNB   0.164582
QTUM  0.168984
ETH   0.196703
XRP   0.239309
LINK  0.286100
ZEC   0.383392
g================================================================       QTUM      ETH     XRP   LINK     ZEC
0      NaN      NaN     NaN    NaN     NaN
1      NaN      NaN     NaN    NaN     NaN
2      NaN      NaN     NaN    NaN     NaN
3      NaN      NaN     NaN    NaN     NaN
4      NaN      NaN     NaN    NaN     NaN
..     ...      ...     ...    ...     ...
720  7.079  2316.15  0.6521  19.79  118.51
721  6.504  2121.52  0.6236  18.44  109.38
722  6.776  2146.27  0.6372  18.66  110.99
723  6.639  2111.19  0.6251  18.20  108.15
724  6.694  2138.86  0.6362  18.38  110.82

[725 rows x 5 columns]
QTUM    0.140496
ETH     0.139566
XRP     0.168472
LINK    0.307692
ZEC     0.291361
Name: 359, dtype: float64
報酬 0.20951749145686566 %
i= QTUM    0.140496
ETH     0.139566
XRP     0.168472
LINK    0.307692
ZEC     0.291361
Name: 359, dtype: float64
牛式===============================
執行第 366
           366
LTC   0.009264
BAT   0.022521
BCH   0.027747
TRX   0.027961
ADA   0.039545
ICX   0.042804
IOTA  0.053792
NEO   0.057388
ZRX   0.085872
XLM   0.095606
ATOM  0.099921
BNB   0.100629
ALGO  0.112879
ZIL   0.117222
ETH   0.139566
QTUM  0.140496
VET   0.146361
XRP   0.168472
ZEC   0.291361
LINK  0.307692
g================================================================       QTUM      VET     XRP     ZEC   LINK
0      NaN      NaN     NaN     NaN    NaN
1      NaN      NaN     NaN     NaN    NaN
2      NaN      NaN     NaN     NaN    NaN
3      NaN      NaN     NaN     NaN    NaN
4      NaN      NaN     NaN     NaN    NaN
..     ...      ...     ...     ...    ...
720  7.079  0.08348  0.6521  118.51  19.79
721  6.504  0.07614  0.6236  109.38  18.44
722  6.776  0.07704  0.6372  110.99  18.66
723  6.639  0.07591  0.6251  108.15  18.20
724  6.694  0.07768  0.6362  110.82  18.38

[725 rows x 5 columns]
QTUM   -0.004521
VET     0.077940
XRP     0.011891
ZEC     0.058758
LINK    0.216346
Name: 360, dtype: float64
報酬 0.07208271576068574 %
i= QTUM   -0.004521
VET     0.077940
XRP     0.011891
ZEC     0.058758
LINK    0.216346
Name: 360, dtype: float64
牛式===============================
執行第 367
           367
BCH  -0.054380
XLM  -0.042294
NEO  -0.040382
ADA  -0.038520
TRX  -0.028334
LTC  -0.021718
BAT  -0.021655
ETH  -0.019767
ATOM -0.016895
ZRX  -0.014304
ICX  -0.008128
QTUM -0.004521
XRP   0.011891
IOTA  0.015277
BNB   0.033765
ZEC   0.058758
VET   0.077940
ALGO  0.125648
ZIL   0.170327
LINK  0.216346
g================================================================         ZEC      VET    ALGO      ZIL   LINK
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  118.51  0.08348  0.9062  0.08133  19.79
721  109.38  0.07614  0.8683  0.07509  18.44
722  110.99  0.07704  0.9059  0.07496  18.66
723  108.15  0.07591  0.8918  0.07299  18.20
724  110.82  0.07768  0.8952  0.07377  18.38

[725 rows x 5 columns]
ZEC     0.150314
VET     0.285141
ALGO    0.496687
ZIL     0.470819
LINK    0.536232
Name: 361, dtype: float64
報酬 0.38783863689533493 %
i= ZEC     0.150314
VET     0.285141
ALGO    0.496687
ZIL     0.470819
LINK    0.536232
Name: 361, dtype: float64
牛式===============================
執行第 368
           368
XLM   0.006530
XRP   0.025385
LTC   0.036406
ICX   0.056654
ETH   0.065791
TRX   0.073452
BAT   0.074928
BCH   0.075749
NEO   0.077503
BNB   0.090909
ADA   0.097368
ZRX   0.109354
ATOM  0.132635
QTUM  0.147316
IOTA  0.147365
ZEC   0.150314
VET   0.285141
ZIL   0.470819
ALGO  0.496687
LINK  0.536232
g================================================================         ZEC      VET      ZIL    ALGO   LINK
0       NaN      NaN      NaN     NaN    NaN
1       NaN      NaN      NaN     NaN    NaN
2       NaN      NaN      NaN     NaN    NaN
3       NaN      NaN      NaN     NaN    NaN
4       NaN      NaN      NaN     NaN    NaN
..      ...      ...      ...     ...    ...
720  118.51  0.08348  0.08133  0.9062  19.79
721  109.38  0.07614  0.07509  0.8683  18.44
722  110.99  0.07704  0.07496  0.9059  18.66
723  108.15  0.07591  0.07299  0.8918  18.20
724  110.82  0.07768  0.07377  0.8952  18.38

[725 rows x 5 columns]
ZEC     0.118663
VET     0.313834
ZIL     0.434361
ALGO    0.372213
LINK    0.506536
Name: 362, dtype: float64
報酬 0.3491212305006168 %
i= ZEC     0.118663
VET     0.313834
ZIL     0.434361
ALGO    0.372213
LINK    0.506536
Name: 362, dtype: float64
牛式===============================
執行第 369
           369
XRP  -0.070139
XLM  -0.000190
BCH   0.010989
ETH   0.011639
BNB   0.017679
TRX   0.029190
QTUM  0.037023
NEO   0.048790
ADA   0.057418
BAT   0.064195
LTC   0.088139
ZEC   0.118663
ICX   0.136121
ZRX   0.147760
IOTA  0.158788
VET   0.313834
ATOM  0.369678
ALGO  0.372213
ZIL   0.434361
LINK  0.506536
g================================================================          VET    ATOM    ALGO      ZIL   LINK
0        NaN     NaN     NaN      NaN    NaN
1        NaN     NaN     NaN      NaN    NaN
2        NaN     NaN     NaN      NaN    NaN
3        NaN     NaN     NaN      NaN    NaN
4        NaN     NaN     NaN      NaN    NaN
..       ...     ...     ...      ...    ...
720  0.08348  12.946  0.9062  0.08133  19.79
721  0.07614  11.958  0.8683  0.07509  18.44
722  0.07704  13.182  0.9059  0.07496  18.66
723  0.07591  14.395  0.8918  0.07299  18.20
724  0.07768  14.064  0.8952  0.07377  18.38

[725 rows x 5 columns]
VET     0.144895
ATOM    0.364181
ALGO    0.434783
ZIL     0.355049
LINK    0.366126
Name: 363, dtype: float64
報酬 0.33300656763412956 %
i= VET     0.144895
ATOM    0.364181
ALGO    0.434783
ZIL     0.355049
LINK    0.366126
Name: 363, dtype: float64
牛式===============================
執行第 370
           370
XLM  -0.033966
XRP  -0.022563
ADA   0.003837
BNB   0.014798
ETH   0.015665
QTUM  0.028782
LTC   0.047273
ZEC   0.047709
BCH   0.049575
TRX   0.054438
BAT   0.093893
VET   0.144895
ICX   0.145340
NEO   0.157073
ZRX   0.207495
IOTA  0.248534
ZIL   0.355049
ATOM  0.364181
LINK  0.366126
ALGO  0.434783
g================================================================        IOTA      ZIL    ATOM   LINK    ALGO
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  0.8896  0.08133  12.946  19.79  0.9062
721  0.8165  0.07509  11.958  18.44  0.8683
722  0.8180  0.07496  13.182  18.66  0.9059
723  0.7913  0.07299  14.395  18.20  0.8918
724  0.8404  0.07377  14.064  18.38  0.8952

[725 rows x 5 columns]
IOTA    0.206490
ZIL     0.327894
ATOM    0.185811
LINK    0.360965
ALGO    0.301043
Name: 364, dtype: float64
報酬 0.27644060191568554 %

i= IOTA    0.206490
ZIL     0.327894
ATOM    0.185811
LINK    0.360965
ALGO    0.301043
Name: 364, dtype: float64
牛式===============================
執行第 371
           371
ZEC  -0.170326
LTC  -0.169814
BNB  -0.087199
XLM  -0.068051
XRP  -0.065016
ETH  -0.054432
BCH  -0.040775
ADA  -0.037964
QTUM -0.018745
TRX  -0.011805
BAT   0.015140
VET   0.062683
NEO   0.064579
ICX   0.081559
ZRX   0.114243
ATOM  0.185811
IOTA  0.206490
ALGO  0.301043
ZIL   0.327894
LINK  0.360965
g================================================================        ATOM    IOTA    ALGO      ZIL   LINK
0       NaN     NaN     NaN      NaN    NaN
1       NaN     NaN     NaN      NaN    NaN
2       NaN     NaN     NaN      NaN    NaN
3       NaN     NaN     NaN      NaN    NaN
4       NaN     NaN     NaN      NaN    NaN
..      ...     ...     ...      ...    ...
720  12.946  0.8896  0.9062  0.08133  19.79
721  11.958  0.8165  0.8683  0.07509  18.44
722  13.182  0.8180  0.9059  0.07496  18.66
723  14.395  0.7913  0.8918  0.07299  18.20
724  14.064  0.8404  0.8952  0.07377  18.38

[725 rows x 5 columns]
ATOM    0.417785
IOTA    0.220038
ALGO    0.437878
ZIL     0.270512
LINK    0.618627
Name: 365, dtype: float64
報酬 0.39296817414361657 %
i= ATOM    0.417785
IOTA    0.220038
ALGO    0.437878
ZIL     0.270512
LINK    0.618627
Name: 365, dtype: float64
牛式===============================
執行第 372
           372
LTC  -0.172267
ZEC  -0.135767
BCH  -0.079246
XRP  -0.068593
BNB  -0.055385
ADA  -0.053076
XLM  -0.045750
ETH  -0.019581
TRX  -0.001484
QTUM  0.013406
VET   0.035747
BAT   0.047913
NEO   0.107388
ZRX   0.116808
ICX   0.160082
IOTA  0.220038
ZIL   0.270512
ATOM  0.417785
ALGO  0.437878
LINK  0.618627
g================================================================        IOTA      ZIL    ATOM    ALGO   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  0.8896  0.08133  12.946  0.9062  19.79
721  0.8165  0.07509  11.958  0.8683  18.44
722  0.8180  0.07496  13.182  0.9059  18.66
723  0.7913  0.07299  14.395  0.8918  18.20
724  0.8404  0.07377  14.064  0.8952  18.38

[725 rows x 5 columns]
IOTA    0.182132
ZIL     0.161098
ATOM    0.513325
ALGO    0.802493
LINK    0.695652
Name: 366, dtype: float64
報酬 0.47093996282044637 %
i= IOTA    0.182132
ZIL     0.161098
ATOM    0.513325
ALGO    0.802493
LINK    0.695652
Name: 366, dtype: float64
牛式===============================
執行第 373
           373
LTC  -0.168489
ZEC  -0.075725
BNB  -0.025503
BCH  -0.021309
XLM  -0.018732
XRP  -0.000306
ADA   0.004828
VET   0.049649
BAT   0.062055
QTUM  0.082513
ETH   0.119148
TRX   0.124183
NEO   0.130989
ZRX   0.145112
ZIL   0.161098
IOTA  0.182132
ICX   0.288660
ATOM  0.513325
LINK  0.695652
ALGO  0.802493
g================================================================        IOTA     ICX    ATOM   LINK    ALGO
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.8896  0.9279  12.946  19.79  0.9062
721  0.8165  1.0350  11.958  18.44  0.8683
722  0.8180  0.9786  13.182  18.66  0.9059
723  0.7913  0.9198  14.395  18.20  0.8918
724  0.8404  0.9519  14.064  18.38  0.8952

[725 rows x 5 columns]
IOTA    0.230281
ICX     0.393778
ATOM    0.375451
LINK    0.331761
ALGO    0.409564
Name: 367, dtype: float64
報酬 0.3481671287059734 %
i= IOTA    0.230281
ICX     0.393778
ATOM    0.375451
LINK    0.331761
ALGO    0.409564
Name: 367, dtype: float64
牛式===============================
執行第 374
           374
LTC  -0.218176
ZEC  -0.122731
ADA  -0.057994
ZIL  -0.045403
BCH  -0.039189
VET  -0.014939
BNB   0.008290
XRP   0.015951
XLM   0.016462
BAT   0.067407
ETH   0.103555
QTUM  0.124048
NEO   0.127493
TRX   0.206256
IOTA  0.230281
ZRX   0.281235
LINK  0.331761
ATOM  0.375451
ICX   0.393778
ALGO  0.409564
g================================================================         ZRX   LINK    ATOM     ICX    ALGO
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  0.7889  19.79  12.946  0.9279  0.9062
721  0.8190  18.44  11.958  1.0350  0.8683
722  0.8384  18.66  13.182  0.9786  0.9059
723  0.7890  18.20  14.395  0.9198  0.8918
724  0.7950  18.38  14.064  0.9519  0.8952

[725 rows x 5 columns]
ZRX     0.136727
LINK    0.385394
ATOM    0.151061
ICX     0.204455
ALGO    0.496115
Name: 368, dtype: float64
報酬 0.2747504051097821 %
i= ZRX     0.136727
LINK    0.385394
ATOM    0.151061
ICX     0.204455
ALGO    0.496115
Name: 368, dtype: float64
牛式===============================
執行第 375
           375
LTC  -0.528714
VET  -0.108349
ZEC  -0.075318
ADA  -0.046238
ZIL  -0.012734
BCH   0.007602
XLM   0.018644
BNB   0.024499
BAT   0.026976
XRP   0.037437
ETH   0.107623
ZRX   0.136727
QTUM  0.139124
ATOM  0.151061
NEO   0.162015
ICX   0.204455
IOTA  0.204539
TRX   0.234719
LINK  0.385394
ALGO  0.496115
g================================================================         ICX    IOTA      TRX   LINK    ALGO
0       NaN     NaN      NaN    NaN     NaN
1       NaN     NaN      NaN    NaN     NaN
2       NaN     NaN      NaN    NaN     NaN
3       NaN     NaN      NaN    NaN     NaN
4       NaN     NaN      NaN    NaN     NaN
..      ...     ...      ...    ...     ...
720  0.9279  0.8896  0.06432  19.79  0.9062
721  1.0350  0.8165  0.06111  18.44  0.8683
722  0.9786  0.8180  0.06219  18.66  0.9059
723  0.9198  0.7913  0.06139  18.20  0.8918
724  0.9519  0.8404  0.06184  18.38  0.8952

[725 rows x 5 columns]
ICX     0.180559
IOTA    0.104096
TRX     0.313023
LINK    0.396437
ALGO    0.342723
Name: 369, dtype: float64
報酬 0.2673674809084778 %
i= ICX     0.180559
IOTA    0.104096
TRX     0.313023
LINK    0.396437
ALGO    0.342723
Name: 369, dtype: float64
牛式===============================
執行第 376
           376
LTC  -0.380456
VET  -0.074059
ZEC  -0.040926
ADA  -0.035302
BCH   0.019548
XRP   0.033811
BNB   0.038003
ZIL   0.052885
NEO   0.065777
XLM   0.082824
ETH   0.096786
IOTA  0.104096
BAT   0.131542
QTUM  0.138178
ATOM  0.138965
ICX   0.180559
ZRX   0.267028
TRX   0.313023
ALGO  0.342723
LINK  0.396437
g================================================================         ICX     ZRX      TRX    ALGO   LINK
0       NaN     NaN      NaN     NaN    NaN
1       NaN     NaN      NaN     NaN    NaN
2       NaN     NaN      NaN     NaN    NaN
3       NaN     NaN      NaN     NaN    NaN
4       NaN     NaN      NaN     NaN    NaN
..      ...     ...      ...     ...    ...
720  0.9279  0.7889  0.06432  0.9062  19.79
721  1.0350  0.8190  0.06111  0.8683  18.44
722  0.9786  0.8384  0.06219  0.9059  18.66
723  0.9198  0.7890  0.06139  0.8918  18.20
724  0.9519  0.7950  0.06184  0.8952  18.38

[725 rows x 5 columns]
ICX     0.200617
ZRX     0.268293
TRX     0.510702
ALGO    0.342268
LINK    0.280648
Name: 370, dtype: float64
報酬 0.32050535326937746 %
i= ICX     0.200617
ZRX     0.268293
TRX     0.510702
ALGO    0.342268
LINK    0.280648
Name: 370, dtype: float64
牛式===============================
執行第 377
           377
LTC  -0.324770
ZIL  -0.035714
VET   0.002454
ADA   0.026673
ZEC   0.072595
BNB   0.105882
XRP   0.114293
IOTA  0.118989
BCH   0.127561
ETH   0.134980
XLM   0.136350
ICX   0.200617
ATOM  0.202483
NEO   0.207752
BAT   0.209560
QTUM  0.254225
ZRX   0.268293
LINK  0.280648
ALGO  0.342268
TRX   0.510702
g================================================================       QTUM     ZRX   LINK    ALGO      TRX
0      NaN     NaN    NaN     NaN      NaN
1      NaN     NaN    NaN     NaN      NaN
2      NaN     NaN    NaN     NaN      NaN
3      NaN     NaN    NaN     NaN      NaN
4      NaN     NaN    NaN     NaN      NaN
..     ...     ...    ...     ...      ...
720  7.079  0.7889  19.79  0.9062  0.06432
721  6.504  0.8190  18.44  0.8683  0.06111
722  6.776  0.8384  18.66  0.9059  0.06219
723  6.639  0.7890  18.20  0.8918  0.06139
724  6.694  0.7950  18.38  0.8952  0.06184

[725 rows x 5 columns]
QTUM    0.177333
ZRX     0.224123
LINK   -0.018776
ALGO    0.063277
TRX     0.424963
Name: 371, dtype: float64
報酬 0.17418376551112313 %
i= QTUM    0.177333
ZRX     0.224123
LINK   -0.018776
ALGO    0.063277
TRX     0.424963
Name: 371, dtype: float64
牛式===============================
執行第 378
           378
LTC  -0.279010
ZIL  -0.094716
VET  -0.064327
LINK -0.018776
ATOM -0.015892
ZEC  -0.005025
ADA   0.002195
IOTA  0.025468
ALGO  0.063277
XLM   0.065996
BCH   0.066167
BNB   0.071196
XRP   0.071732
ETH   0.091254
ICX   0.094870
NEO   0.127998
QTUM  0.177333
ZRX   0.224123
BAT   0.289454
TRX   0.424963
g================================================================         NEO   QTUM     ZRX     BAT      TRX
0       NaN    NaN     NaN     NaN      NaN
1       NaN    NaN     NaN     NaN      NaN
2       NaN    NaN     NaN     NaN      NaN
3       NaN    NaN     NaN     NaN      NaN
4       NaN    NaN     NaN     NaN      NaN
..      ...    ...     ...     ...      ...
720  37.005  7.079  0.7889  0.6135  0.06432
721  34.083  6.504  0.8190  0.5691  0.06111
722  34.637  6.776  0.8384  0.5695  0.06219
723  34.057  6.639  0.7890  0.5575  0.06139
724  34.191  6.694  0.7950  0.5623  0.06184

[725 rows x 5 columns]
NEO     0.088446
QTUM    0.152098
ZRX     0.141174
BAT     0.182360
TRX     0.184258
Name: 372, dtype: float64
報酬 0.14966690717556577 %
i= NEO     0.088446
QTUM    0.152098
ZRX     0.141174
BAT     0.182360
TRX     0.184258
Name: 372, dtype: float64
牛式===============================
執行第 379
           379
LTC  -0.341104
ZIL  -0.137958
ZEC  -0.126046
ALGO -0.103412
VET  -0.089448
ADA  -0.070635
ATOM -0.070112
ICX  -0.067282
LINK -0.057110
ETH  -0.042114
XRP  -0.015560
IOTA -0.012994
BCH  -0.010041
XLM   0.010485
BNB   0.026171
NEO   0.088446
ZRX   0.141174
QTUM  0.152098
BAT   0.182360
TRX   0.184258
g================================================================         NEO     ZRX   QTUM     BAT      TRX
0       NaN     NaN    NaN     NaN      NaN
1       NaN     NaN    NaN     NaN      NaN
2       NaN     NaN    NaN     NaN      NaN
3       NaN     NaN    NaN     NaN      NaN
4       NaN     NaN    NaN     NaN      NaN
..      ...     ...    ...     ...      ...
720  37.005  0.7889  7.079  0.6135  0.06432
721  34.083  0.8190  6.504  0.5691  0.06111
722  34.637  0.8384  6.776  0.5695  0.06219
723  34.057  0.7890  6.639  0.5575  0.06139
724  34.191  0.7950  6.694  0.5623  0.06184

[725 rows x 5 columns]
NEO     0.204348
ZRX     0.132925
QTUM    0.315908
BAT     0.294941
TRX     0.112237
Name: 373, dtype: float64
報酬 0.2120717576519265 %
i= NEO     0.204348
ZRX     0.132925
QTUM    0.315908
BAT     0.294941
TRX     0.112237
Name: 373, dtype: float64
牛式===============================
執行第 380
           380
LTC  -0.294724
ZIL  -0.090328
ZEC  -0.072655
VET  -0.054567
LINK -0.053129
ETH  -0.050663
ADA  -0.030818
XRP  -0.026268
IOTA -0.020634
ICX  -0.016694
ALGO -0.016177
BNB  -0.002164
BCH   0.004911
XLM   0.021911
ATOM  0.032972
TRX   0.112237
ZRX   0.132925
NEO   0.204348
BAT   0.294941
QTUM  0.315908
g================================================================          TRX     ZRX     NEO     BAT   QTUM
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  0.06432  0.7889  37.005  0.6135  7.079
721  0.06111  0.8190  34.083  0.5691  6.504
722  0.06219  0.8384  34.637  0.5695  6.776
723  0.06139  0.7890  34.057  0.5575  6.639
724  0.06184  0.7950  34.191  0.5623  6.694

[725 rows x 5 columns]
TRX    -0.040396
ZRX     0.392169
NEO     0.093303
BAT     0.375046
QTUM    0.217124
Name: 374, dtype: float64
報酬 0.20744919363423472 %
i= TRX    -0.040396
ZRX     0.392169
NEO     0.093303
BAT     0.375046
QTUM    0.217124
Name: 374, dtype: float64
牛式===============================
執行第 381
           381
LINK -0.278706
ALGO -0.162890
ZIL  -0.147924
ZEC  -0.136460
IOTA -0.114477
ADA  -0.112058
ETH  -0.102464
VET  -0.081965
ATOM -0.077227
XLM  -0.072836
XRP  -0.066080
BCH  -0.063962
BNB  -0.040870
TRX  -0.040396
ICX   0.083901
NEO   0.093303
LTC   0.165156
QTUM  0.217124
BAT   0.375046
ZRX   0.392169
g================================================================         NEO     LTC   QTUM     BAT     ZRX
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  37.005  137.39  7.079  0.6135  0.7889
721  34.083  132.25  6.504  0.5691  0.8190
722  34.637  134.42  6.776  0.5695  0.8384
723  34.057  134.00  6.639  0.5575  0.7890
724  34.191  134.19  6.694  0.5623  0.7950

[725 rows x 5 columns]
NEO     0.224145
LTC     0.038965
QTUM    0.248501
BAT     0.227567
ZRX     0.193490
Name: 375, dtype: float64
報酬 0.18653348703661984 %
i= NEO     0.224145
LTC     0.038965
QTUM    0.248501
BAT     0.227567
ZRX     0.193490
Name: 375, dtype: float64
牛式===============================
執行第 382
           382
ZIL  -0.165145
LINK -0.156300
XLM  -0.110696
TRX  -0.110166
ALGO -0.101081
ZEC  -0.098359
ADA  -0.097320
ETH  -0.088753
VET  -0.083913
BCH  -0.069848
XRP  -0.059894
BNB  -0.054917
IOTA -0.046078
ATOM  0.033874
LTC   0.038965
ZRX   0.193490
ICX   0.202869
NEO   0.224145
BAT   0.227567
QTUM  0.248501
g================================================================         ZRX     ICX     NEO     BAT   QTUM
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  0.7889  0.9279  37.005  0.6135  7.079
721  0.8190  1.0350  34.083  0.5691  6.504
722  0.8384  0.9786  34.637  0.5695  6.776
723  0.7890  0.9198  34.057  0.5575  6.639
724  0.7950  0.9519  34.191  0.5623  6.694

[725 rows x 5 columns]
ZRX     0.285256
ICX     0.211337
NEO     0.097492
BAT     0.272526
QTUM    0.163445
Name: 376, dtype: float64
報酬 0.20601119480526536 %
i= ZRX     0.285256
ICX     0.211337
NEO     0.097492
BAT     0.272526
QTUM    0.163445
Name: 376, dtype: float64
牛式===============================
執行第 383
           383
TRX  -0.197694
ZIL  -0.146157
ADA  -0.135668
VET  -0.106394
BCH  -0.103430
XRP  -0.096542
XLM  -0.095464
ETH  -0.091603
LINK -0.087297
BNB  -0.071064
IOTA -0.065550
ZEC  -0.026634
ALGO  0.046936
NEO   0.097492
LTC   0.106012
QTUM  0.163445
ICX   0.211337
BAT   0.272526
ZRX   0.285256
ATOM  0.437976
g================================================================       QTUM     ICX     BAT     ZRX    ATOM
0      NaN     NaN     NaN     NaN     NaN
1      NaN     NaN     NaN     NaN     NaN
2      NaN     NaN     NaN     NaN     NaN
3      NaN     NaN     NaN     NaN     NaN
4      NaN     NaN     NaN     NaN     NaN
..     ...     ...     ...     ...     ...
720  7.079  0.9279  0.6135  0.7889  12.946
721  6.504  1.0350  0.5691  0.8190  11.958
722  6.776  0.9786  0.5695  0.8384  13.182
723  6.639  0.9198  0.5575  0.7890  14.395
724  6.694  0.9519  0.5623  0.7950  14.064

[725 rows x 5 columns]
QTUM    0.160036
ICX     0.235508
BAT     0.133829
ZRX     0.292057
ATOM    0.409895
Name: 377, dtype: float64
報酬 0.2462651874226669 %
i= QTUM    0.160036
ICX     0.235508
BAT     0.133829
ZRX     0.292057
ATOM    0.409895
Name: 377, dtype: float64
牛式===============================
執行第 384
           384
TRX  -0.127216
ADA  -0.097109
LINK -0.065432
VET  -0.049338
XLM  -0.047103
XRP  -0.046108
BCH  -0.041121
ZEC  -0.034873
ETH  -0.034212
BNB  -0.018245
IOTA -0.004308
ZIL   0.025508
LTC   0.052733
NEO   0.117058
ALGO  0.132147
BAT   0.133829
QTUM  0.160036
ICX   0.235508
ZRX   0.292057
ATOM  0.409895
g================================================================         BAT   QTUM     ICX     ZRX    ATOM
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  0.6135  7.079  0.9279  0.7889  12.946
721  0.5691  6.504  1.0350  0.8190  11.958
722  0.5695  6.776  0.9786  0.8384  13.182
723  0.5575  6.639  0.9198  0.7890  14.395
724  0.5623  6.694  0.9519  0.7950  14.064

[725 rows x 5 columns]
BAT     0.085930
QTUM    0.056753
ICX     0.270948
ZRX     0.263199
ATOM    0.482832
Name: 378, dtype: float64
報酬 0.23193228468894672 %
i= BAT     0.085930
QTUM    0.056753
ICX     0.270948
ZRX     0.263199
ATOM    0.482832
Name: 378, dtype: float64
牛式===============================
執行第 385
           385
ADA  -0.132793
TRX  -0.132553
LINK -0.127318
BCH  -0.059117
ALGO -0.058676
ETH  -0.057933
VET  -0.053909
XLM  -0.049139
XRP  -0.046694
ZEC  -0.043792
BNB  -0.042506
IOTA -0.029017
ZIL  -0.023777
QTUM  0.056753
LTC   0.071364
NEO   0.075509
BAT   0.085930
ZRX   0.263199
ICX   0.270948
ATOM  0.482832
g================================================================         NEO     BAT     ZRX     ICX    ATOM
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  37.005  0.6135  0.7889  0.9279  12.946
721  34.083  0.5691  0.8190  1.0350  11.958
722  34.637  0.5695  0.8384  0.9786  13.182
723  34.057  0.5575  0.7890  0.9198  14.395
724  34.191  0.5623  0.7950  0.9519  14.064

[725 rows x 5 columns]
NEO    -0.028868
BAT    -0.028817
ZRX     0.077565
ICX     0.181583
ATOM    0.223916
Name: 379, dtype: float64
報酬 0.08507599107279804 %
i= NEO    -0.028868
BAT    -0.028817
ZRX     0.077565
ICX     0.181583
ATOM    0.223916
Name: 379, dtype: float64
牛式===============================
執行第 386
           386
ADA  -0.145630
TRX  -0.137705
ALGO -0.123084
VET  -0.117547
IOTA -0.105844
XLM  -0.086045
QTUM -0.073811
ETH  -0.072463
BCH  -0.067635
XRP  -0.053678
LINK -0.053616
ZEC  -0.049949
BNB  -0.036860
NEO  -0.028868
BAT  -0.028817
ZIL  -0.016696
ZRX   0.077565
LTC   0.137639
ICX   0.181583
ATOM  0.223916
g================================================================          ZIL     ZRX     LTC     ICX    ATOM
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08133  0.7889  137.39  0.9279  12.946
721  0.07509  0.8190  132.25  1.0350  11.958
722  0.07496  0.8384  134.42  0.9786  13.182
723  0.07299  0.7890  134.00  0.9198  14.395
724  0.07377  0.7950  134.19  0.9519  14.064

[725 rows x 5 columns]
ZIL    -0.040681
ZRX    -0.122458
LTC     0.168539
ICX     0.044361
ATOM    0.299251
Name: 380, dtype: float64
報酬 0.06980230195106978 %
i= ZIL    -0.040681
ZRX    -0.122458
LTC     0.168539
ICX     0.044361
ATOM    0.299251
Name: 380, dtype: float64
牛式===============================
執行第 387
           387
BAT  -0.134253
ADA  -0.127583
ZRX  -0.122458
VET  -0.111910
QTUM -0.106716
IOTA -0.085914
BCH  -0.065045
XLM  -0.055796
XRP  -0.052117
TRX  -0.049525
ZIL  -0.040681
ALGO -0.020305
ZEC  -0.018375
ETH  -0.012811
ICX   0.044361
BNB   0.047597
LINK  0.050651
NEO   0.068878
LTC   0.168539
ATOM  0.299251
g================================================================         BNB   LINK     NEO     LTC    ATOM
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  327.67  19.79  37.005  137.39  12.946
721  310.59  18.44  34.083  132.25  11.958
722  316.72  18.66  34.637  134.42  13.182
723  316.09  18.20  34.057  134.00  14.395
724  321.87  18.38  34.191  134.19  14.064

[725 rows x 5 columns]
BNB     0.038739
LINK   -0.045369
NEO    -0.035967
LTC     0.006165
ATOM    0.175000
Name: 381, dtype: float64
報酬 0.027713671979572106 %
i= BNB     0.038739
LINK   -0.045369
NEO    -0.035967
LTC     0.006165
ATOM    0.175000
Name: 381, dtype: float64
牛式===============================
執行第 388
           388
QTUM -0.197599
IOTA -0.134506
ADA  -0.127843
BAT  -0.119819
ZRX  -0.119008
VET  -0.102327
XLM  -0.065118
BCH  -0.062956
ALGO -0.056577
XRP  -0.050856
ICX  -0.047700
TRX  -0.046975
ZIL  -0.046035
LINK -0.045369
NEO  -0.035967
ZEC  -0.007151
ETH  -0.000708
LTC   0.006165
BNB   0.038739
ATOM  0.175000
g================================================================         ZEC      ETH     LTC     BNB    ATOM
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  118.51  2316.15  137.39  327.67  12.946
721  109.38  2121.52  132.25  310.59  11.958
722  110.99  2146.27  134.42  316.72  13.182
723  108.15  2111.19  134.00  316.09  14.395
724  110.82  2138.86  134.19  321.87  14.064

[725 rows x 5 columns]
ZEC    -0.067875
ETH     0.020531
LTC     0.060662
BNB     0.050847
ATOM   -0.143933
Name: 382, dtype: float64
報酬 -0.015953475780050907 %
i= ZEC    -0.067875
ETH     0.020531
LTC     0.060662
BNB     0.050847
ATOM   -0.143933
Name: 382, dtype: float64
牛式===============================
執行第 389
           389
ATOM -0.143933
QTUM -0.135952
ALGO -0.130258
BAT  -0.126460
ZRX  -0.107648
ZEC  -0.067875
XLM  -0.064529
VET  -0.061207
BCH  -0.058524
IOTA -0.047805
ADA  -0.042823
XRP  -0.038312
ZIL  -0.023321
ETH   0.020531
TRX   0.022998
ICX   0.031143
BNB   0.050847
LTC   0.060662
LINK  0.082454
NEO   0.165547
g================================================================         ICX     BNB     LTC   LINK     NEO
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.9279  327.67  137.39  19.79  37.005
721  1.0350  310.59  132.25  18.44  34.083
722  0.9786  316.72  134.42  18.66  34.637
723  0.9198  316.09  134.00  18.20  34.057
724  0.9519  321.87  134.19  18.38  34.191

[725 rows x 5 columns]
ICX     0.004741
BNB     0.045575
LTC    -0.008088
LINK    0.087847
NEO     0.145070
Name: 383, dtype: float64
報酬 0.055029095543880205 %
i= ICX     0.004741
BNB     0.045575
LTC    -0.008088
LINK    0.087847
NEO     0.145070
Name: 383, dtype: float64
牛式===============================
執行第 390
           390
ALGO -0.177068
ZRX  -0.128286
BAT  -0.126356
QTUM -0.097382
IOTA -0.072538
ATOM -0.069818
VET  -0.057457
ADA  -0.050057
XLM  -0.045547
BCH  -0.038964
XRP  -0.019543
ZIL  -0.018128
LTC  -0.008088
ICX   0.004741
ZEC   0.011712
BNB   0.045575
ETH   0.052706
TRX   0.075269
LINK  0.087847
NEO   0.145070
g================================================================         BNB      ETH      TRX   LINK     NEO
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  327.67  2316.15  0.06432  19.79  37.005
721  310.59  2121.52  0.06111  18.44  34.083
722  316.72  2146.27  0.06219  18.66  34.637
723  316.09  2111.19  0.06139  18.20  34.057
724  321.87  2138.86  0.06184  18.38  34.191

[725 rows x 5 columns]
BNB     0.081308
ETH     0.132256
TRX     0.270788
LINK    0.104108
NEO     0.201046
Name: 384, dtype: float64
報酬 0.15790120468282268 %
i= BNB     0.081308
ETH     0.132256
TRX     0.270788
LINK    0.104108
NEO     0.201046
Name: 384, dtype: float64
牛式===============================
執行第 391
           391
ATOM -0.143113
ALGO -0.106322
ZRX  -0.055830
QTUM -0.035612
BCH  -0.006933
XLM  -0.004015
IOTA  0.000000
BAT   0.008116
XRP   0.017630
ICX   0.030109
VET   0.030563
ZIL   0.049180
ZEC   0.073906
BNB   0.081308
ADA   0.089688
LTC   0.095964
LINK  0.104108
ETH   0.132256
NEO   0.201046
TRX   0.270788
g================================================================         LTC   LINK      ETH     NEO      TRX
0       NaN    NaN      NaN     NaN      NaN
1       NaN    NaN      NaN     NaN      NaN
2       NaN    NaN      NaN     NaN      NaN
3       NaN    NaN      NaN     NaN      NaN
4       NaN    NaN      NaN     NaN      NaN
..      ...    ...      ...     ...      ...
720  137.39  19.79  2316.15  37.005  0.06432
721  132.25  18.44  2121.52  34.083  0.06111
722  134.42  18.66  2146.27  34.637  0.06219
723  134.00  18.20  2111.19  34.057  0.06139
724  134.19  18.38  2138.86  34.191  0.06184

[725 rows x 5 columns]
LTC    -0.046751
LINK    0.058630
ETH     0.234086
NEO     0.241962
TRX     0.465991
Name: 385, dtype: float64
報酬 0.19078370427462915 %
i= LTC    -0.046751
LINK    0.058630
ETH     0.234086
NEO     0.241962
TRX     0.465991
Name: 385, dtype: float64
牛式===============================
執行第 392
           392
ICX  -0.088240
ZRX  -0.087320
QTUM -0.067249
ATOM -0.062022
ALGO -0.058256
LTC  -0.046751
BAT  -0.043652
ZIL  -0.021448
VET  -0.006079
XLM   0.008058
IOTA  0.024965
LINK  0.058630
BCH   0.063005
XRP   0.069131
ADA   0.088153
ZEC   0.110088
BNB   0.113012
ETH   0.234086
NEO   0.241962
TRX   0.465991
g================================================================         ZEC     BNB      ETH     NEO      TRX
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  118.51  327.67  2316.15  37.005  0.06432
721  109.38  310.59  2121.52  34.083  0.06111
722  110.99  316.72  2146.27  34.637  0.06219
723  108.15  316.09  2111.19  34.057  0.06139
724  110.82  321.87  2138.86  34.191  0.06184

[725 rows x 5 columns]
ZEC    0.054908
BNB    0.068801
ETH    0.147497
NEO    0.151189
TRX    0.501520
Name: 386, dtype: float64
報酬 0.18478321580810006 %
i= ZEC    0.054908
BNB    0.068801
ETH    0.147497
NEO    0.151189
TRX    0.501520
Name: 386, dtype: float64
牛式===============================
執行第 393
           393
ALGO -0.107849
ATOM -0.086801
ZRX  -0.083498
ICX  -0.058298
LTC  -0.040927
QTUM -0.037444
BAT  -0.030034
XLM  -0.014187
IOTA -0.004125
BCH  -0.001777
VET   0.003326
ZIL   0.005424
LINK  0.019284
XRP   0.044734
ZEC   0.054908
BNB   0.068801
ADA   0.072188
ETH   0.147497
NEO   0.151189
TRX   0.501520
g================================================================         BNB     ADA      ETH     NEO      TRX
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  327.67  1.4039  2316.15  37.005  0.06432
721  310.59  1.3327  2121.52  34.083  0.06111
722  316.72  1.3497  2146.27  34.637  0.06219
723  316.09  1.3356  2111.19  34.057  0.06139
724  321.87  1.3478  2138.86  34.191  0.06184

[725 rows x 5 columns]
BNB   -0.118820
ADA   -0.132583
ETH   -0.034176
NEO   -0.029158
TRX    0.692565
Name: 387, dtype: float64
報酬 0.07556546833870777 %
i= BNB   -0.118820
ADA   -0.132583
ETH   -0.034176
NEO   -0.029158
TRX    0.692565
Name: 387, dtype: float64
牛式===============================
執行第 394
           394
ATOM -0.351130
ALGO -0.347264
ZRX  -0.305347
ICX  -0.288827
QTUM -0.282466
BAT  -0.279680
ZEC  -0.255631
ZIL  -0.243192
VET  -0.242937
IOTA -0.215512
LINK -0.215182
BCH  -0.203975
XLM  -0.184942
ADA  -0.132583
BNB  -0.118820
XRP  -0.100758
ETH  -0.034176
NEO  -0.029158
LTC  -0.002298
TRX   0.692565
g================================================================         XRP      ETH     NEO     LTC      TRX
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.6521  2316.15  37.005  137.39  0.06432
721  0.6236  2121.52  34.083  132.25  0.06111
722  0.6372  2146.27  34.637  134.42  0.06219
723  0.6251  2111.19  34.057  134.00  0.06139
724  0.6362  2138.86  34.191  134.19  0.06184

[725 rows x 5 columns]
XRP   -0.072519
ETH   -0.032561
NEO   -0.107021
LTC   -0.029215
TRX    0.427941
Name: 388, dtype: float64
報酬 0.037324913038502314 %
i= XRP   -0.072519
ETH   -0.032561
NEO   -0.107021
LTC   -0.029215
TRX    0.427941
Name: 388, dtype: float64
牛式===============================
執行第 395
           395
ALGO -0.298969
ICX  -0.270557
QTUM -0.249126
BAT  -0.247440
ATOM -0.247319
LINK -0.244973
ZEC  -0.242089
IOTA -0.211733
ZIL  -0.207736
ZRX  -0.201832
XLM  -0.161230
VET  -0.151593
BCH  -0.141226
ADA  -0.125613
NEO  -0.107021
BNB  -0.086748
XRP  -0.072519
ETH  -0.032561
LTC  -0.029215
TRX   0.427941
g================================================================         BNB     XRP      ETH     LTC      TRX
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  327.67  0.6521  2316.15  137.39  0.06432
721  310.59  0.6236  2121.52  132.25  0.06111
722  316.72  0.6372  2146.27  134.42  0.06219
723  316.09  0.6251  2111.19  134.00  0.06139
724  321.87  0.6362  2138.86  134.19  0.06184

[725 rows x 5 columns]
BNB   -0.176047
XRP   -0.160977
ETH   -0.220297
LTC    0.049448
TRX    0.107407
Name: 389, dtype: float64
報酬 -0.08009325846789246 %
i= BNB   -0.176047
XRP   -0.160977
ETH   -0.220297
LTC    0.049448
TRX    0.107407
Name: 389, dtype: float64
牛式===============================
執行第 396
           396
ZIL  -0.358094
LINK -0.357013
ATOM -0.355908
ALGO -0.341953
ZRX  -0.325742
ICX  -0.324439
QTUM -0.320186
BAT  -0.315820
ZEC  -0.314163
VET  -0.293939
IOTA -0.273875
ADA  -0.234528
XLM  -0.234330
ETH  -0.220297
BCH  -0.192306
NEO  -0.182451
BNB  -0.176047
XRP  -0.160977
LTC   0.049448
TRX   0.107407

g================================================================         NEO     BNB     XRP     LTC      TRX
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  37.005  327.67  0.6521  137.39  0.06432
721  34.083  310.59  0.6236  132.25  0.06111
722  34.637  316.72  0.6372  134.42  0.06219
723  34.057  316.09  0.6251  134.00  0.06139
724  34.191  321.87  0.6362  134.19  0.06184

[725 rows x 5 columns]
NEO   -0.161033
BNB    0.001729
XRP   -0.146781
LTC    0.042493
TRX    0.076396
Name: 390, dtype: float64
報酬 -0.03743921385499431 %
i= NEO   -0.161033
BNB    0.001729
XRP   -0.146781
LTC    0.042493
TRX    0.076396
Name: 390, dtype: float64
牛式===============================
執行第 397
           397
ZIL  -0.317857
VET  -0.289959
ATOM -0.279008
QTUM -0.278142
ICX  -0.259197
BAT  -0.258194
ALGO -0.251295
ZRX  -0.247795
ZEC  -0.246553
ADA  -0.243896
IOTA -0.207803
XLM  -0.199897
ETH  -0.187395
LINK -0.177678
BCH  -0.167842
NEO  -0.161033
XRP  -0.146781
BNB   0.001729
LTC   0.042493
TRX   0.076396
g================================================================         NEO     XRP     BNB     LTC      TRX
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  37.005  0.6521  327.67  137.39  0.06432
721  34.083  0.6236  310.59  132.25  0.06111
722  34.637  0.6372  316.72  134.42  0.06219
723  34.057  0.6251  316.09  134.00  0.06139
724  34.191  0.6362  321.87  134.19  0.06184

[725 rows x 5 columns]
NEO   -0.153646
XRP   -0.181160
BNB   -0.091828
LTC    0.097009
TRX   -0.065418
Name: 391, dtype: float64
報酬 -0.07900866379028137 %
i= NEO   -0.153646
XRP   -0.181160
BNB   -0.091828
LTC    0.097009
TRX   -0.065418
Name: 391, dtype: float64
牛式===============================
執行第 398
           398
QTUM -0.315924
ATOM -0.300595
ZIL  -0.300457
VET  -0.282564
ALGO -0.280495
ICX  -0.270127
ETH  -0.257674
ZEC  -0.256401
ADA  -0.248334
BAT  -0.245823
ZRX  -0.235441
LINK -0.224020
IOTA -0.221675
BCH  -0.216881
XLM  -0.204391
XRP  -0.181160
NEO  -0.153646
BNB  -0.091828
TRX  -0.065418
LTC   0.097009
g================================================================         XRP     NEO     BNB      TRX     LTC
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6521  37.005  327.67  0.06432  137.39
721  0.6236  34.083  310.59  0.06111  132.25
722  0.6372  34.637  316.72  0.06219  134.42
723  0.6251  34.057  316.09  0.06139  134.00
724  0.6362  34.191  321.87  0.06184  134.19

[725 rows x 5 columns]
XRP   -0.143622
NEO   -0.159518
BNB   -0.059514
TRX    0.016484
LTC    0.036761
Name: 392, dtype: float64
報酬 -0.061882018783152096 %
i= XRP   -0.143622
NEO   -0.159518
BNB   -0.059514
TRX    0.016484
LTC    0.036761
Name: 392, dtype: float64
牛式===============================
執行第 399
           399
QTUM -0.271689
ICX  -0.264427
ATOM -0.255226
ALGO -0.250161
VET  -0.242057
ZIL  -0.238352
ETH  -0.233298
ZEC  -0.228575
ZRX  -0.221485
ADA  -0.208333
BAT  -0.207267
LINK -0.206757
IOTA -0.181361
XLM  -0.161978
NEO  -0.159518
BCH  -0.157456
XRP  -0.143622
BNB  -0.059514
TRX   0.016484
LTC   0.036761
g================================================================         BCH     XRP     BNB      TRX     LTC
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  509.55  0.6521  327.67  0.06432  137.39
721  490.60  0.6236  310.59  0.06111  132.25
722  504.08  0.6372  316.72  0.06219  134.42
723  497.02  0.6251  316.09  0.06139  134.00
724  498.00  0.6362  321.87  0.06184  134.19

[725 rows x 5 columns]
BCH    0.047367
XRP   -0.022262
BNB    0.205709
TRX   -0.161895
LTC    0.152252
Name: 393, dtype: float64
報酬 0.04423405857891736 %
i= BCH    0.047367
XRP   -0.022262
BNB    0.205709
TRX   -0.161895
LTC    0.152252
Name: 393, dtype: float64
牛式===============================
執行第 400
           400
TRX  -0.161895
ETH  -0.079657
ICX  -0.047565
NEO  -0.026202
XRP  -0.022262
ADA  -0.015295
XLM   0.002562
BAT   0.017036
QTUM  0.017932
ZRX   0.034211
LINK  0.037847
VET   0.039019
ZIL   0.039773
IOTA  0.041955
BCH   0.047367
ZEC   0.052780
ATOM  0.084114
LTC   0.152252
ALGO  0.185759
BNB   0.205709
g================================================================         ZEC    ATOM     LTC    ALGO     BNB
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  118.51  12.946  137.39  0.9062  327.67
721  109.38  11.958  132.25  0.8683  310.59
722  110.99  13.182  134.42  0.9059  316.72
723  108.15  14.395  134.00  0.8918  316.09
724  110.82  14.064  134.19  0.8952  321.87

[725 rows x 5 columns]
ZEC     0.039738
ATOM   -0.027032
LTC     0.142311
ALGO    0.104545
BNB     0.171360
Name: 394, dtype: float64
報酬 0.08618458771245847 %
i= ZEC     0.039738
ATOM   -0.027032
LTC     0.142311
ALGO    0.104545
BNB     0.171360
Name: 394, dtype: float64
牛式===============================
執行第 401
           401
VET  -0.087655
ZRX  -0.084419
TRX  -0.072533
ADA  -0.045754
ETH  -0.045688
XRP  -0.042638
ATOM -0.027032
NEO  -0.022858
ICX  -0.013874
BCH  -0.011688
XLM   0.004830
BAT   0.004913
LINK  0.010492
QTUM  0.017462
IOTA  0.037037
ZEC   0.039738
ZIL   0.040989
ALGO  0.104545
LTC   0.142311
BNB   0.171360
g================================================================         ZEC      ZIL    ALGO     LTC     BNB
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  118.51  0.08133  0.9062  137.39  327.67
721  109.38  0.07509  0.8683  132.25  310.59
722  110.99  0.07496  0.9059  134.42  316.72
723  108.15  0.07299  0.8918  134.00  316.09
724  110.82  0.07377  0.8952  134.19  321.87

[725 rows x 5 columns]
ZEC     0.137008
ZIL     0.153177
ALGO    0.205279
LTC     0.166667
BNB     0.305085
Name: 395, dtype: float64
報酬 0.19344314038121085 %
i= ZEC     0.137008
ZIL     0.153177
ALGO    0.205279
LTC     0.166667
BNB     0.305085
Name: 395, dtype: float64
牛式===============================
執行第 402
           402
BCH  -0.002260
XRP   0.021271
ADA   0.077736
ICX   0.079721
ATOM  0.086435
VET   0.095187
IOTA  0.107710
XLM   0.112691
BAT   0.113502
ETH   0.116899
TRX   0.121405
ZEC   0.137008
ZIL   0.153177
LTC   0.166667
LINK  0.174693
NEO   0.201300
QTUM  0.201365
ALGO  0.205279
ZRX   0.233170
BNB   0.305085
g================================================================         NEO   QTUM    ALGO     ZRX     BNB
0       NaN    NaN     NaN     NaN     NaN
1       NaN    NaN     NaN     NaN     NaN
2       NaN    NaN     NaN     NaN     NaN
3       NaN    NaN     NaN     NaN     NaN
4       NaN    NaN     NaN     NaN     NaN
..      ...    ...     ...     ...     ...
720  37.005  7.079  0.9062  0.7889  327.67
721  34.083  6.504  0.8683  0.8190  310.59
722  34.637  6.776  0.9059  0.8384  316.72
723  34.057  6.639  0.8918  0.7890  316.09
724  34.191  6.694  0.8952  0.7950  321.87

[725 rows x 5 columns]
NEO     0.266690
QTUM    0.176980
ALGO    0.088635
ZRX     0.120955
BNB     0.229940
Name: 396, dtype: float64
報酬 0.176639964412097 %
i= NEO     0.266690
QTUM    0.176980
ALGO    0.088635
ZRX     0.120955
BNB     0.229940
Name: 396, dtype: float64
牛式===============================
執行第 403
           403
LINK -0.007800
BCH   0.010717
XRP   0.032021
TRX   0.041057
IOTA  0.046105
ADA   0.055076
BAT   0.061628
ATOM  0.082496
XLM   0.082677
VET   0.086693
ALGO  0.088635
ETH   0.100085
ZEC   0.112693
ICX   0.115646
ZRX   0.120955
LTC   0.143281
ZIL   0.163613
QTUM  0.176980
BNB   0.229940
NEO   0.266690
g================================================================         LTC      ZIL   QTUM     BNB     NEO
0       NaN      NaN    NaN     NaN     NaN
1       NaN      NaN    NaN     NaN     NaN
2       NaN      NaN    NaN     NaN     NaN
3       NaN      NaN    NaN     NaN     NaN
4       NaN      NaN    NaN     NaN     NaN
..      ...      ...    ...     ...     ...
720  137.39  0.08133  7.079  327.67  37.005
721  132.25  0.07509  6.504  310.59  34.083
722  134.42  0.07496  6.776  316.72  34.637
723  134.00  0.07299  6.639  316.09  34.057
724  134.19  0.07377  6.694  321.87  34.191

[725 rows x 5 columns]
LTC     0.038074
ZIL     0.088773
QTUM    0.098755
BNB     0.388419
NEO     0.114327
Name: 397, dtype: float64
報酬 0.14566948602416513 %
i= LTC     0.038074
ZIL     0.088773
QTUM    0.098755
BNB     0.388419
NEO     0.114327
Name: 397, dtype: float64
牛式===============================
執行第 404
           404
TRX  -0.055196
LINK -0.033681
BCH  -0.028726
IOTA -0.012307
XRP  -0.000083
ZEC   0.009538
ALGO  0.013971
ADA   0.014740
XLM   0.016915
BAT   0.020174
ETH   0.035097
LTC   0.038074
VET   0.049836
ATOM  0.051028
ZRX   0.062024
ZIL   0.088773
QTUM  0.098755
NEO   0.114327
ICX   0.124619
BNB   0.388419
g================================================================          ZIL   QTUM     NEO     ICX     BNB
0        NaN    NaN     NaN     NaN     NaN
1        NaN    NaN     NaN     NaN     NaN
2        NaN    NaN     NaN     NaN     NaN
3        NaN    NaN     NaN     NaN     NaN
4        NaN    NaN     NaN     NaN     NaN
..       ...    ...     ...     ...     ...
720  0.08133  7.079  37.005  0.9279  327.67
721  0.07509  6.504  34.083  1.0350  310.59
722  0.07496  6.776  34.637  0.9786  316.72
723  0.07299  6.639  34.057  0.9198  316.09
724  0.07377  6.694  34.191  0.9519  321.87

[725 rows x 5 columns]
ZIL     0.079202
QTUM    0.117847
NEO     0.288758
ICX     0.275571
BNB     0.339217
Name: 398, dtype: float64
報酬 0.22011863176763874 %
i= ZIL     0.079202
QTUM    0.117847
NEO     0.288758
ICX     0.275571
BNB     0.339217
Name: 398, dtype: float64
牛式===============================
執行第 405
           405
TRX  -0.135420
BCH   0.014970
BAT   0.021921
IOTA  0.027828
LINK  0.033220
XLM   0.034732
XRP   0.038842
LTC   0.054550
VET   0.059746
ADA   0.061861
ZEC   0.077356
ZIL   0.079202
ATOM  0.086632
ZRX   0.089380
ALGO  0.096099
QTUM  0.117847
ETH   0.119246
ICX   0.275571
NEO   0.288758
BNB   0.339217
g================================================================       QTUM      ETH     ICX     NEO     BNB
0      NaN      NaN     NaN     NaN     NaN
1      NaN      NaN     NaN     NaN     NaN
2      NaN      NaN     NaN     NaN     NaN
3      NaN      NaN     NaN     NaN     NaN
4      NaN      NaN     NaN     NaN     NaN
..     ...      ...     ...     ...     ...
720  7.079  2316.15  0.9279  37.005  327.67
721  6.504  2121.52  1.0350  34.083  310.59
722  6.776  2146.27  0.9786  34.637  316.72
723  6.639  2111.19  0.9198  34.057  316.09
724  6.694  2138.86  0.9519  34.191  321.87

[725 rows x 5 columns]
QTUM    0.009832
ETH     0.036882
ICX     0.222329
NEO     0.173128
BNB     0.106531
Name: 399, dtype: float64
報酬 0.1097403335424422 %
i= QTUM    0.009832
ETH     0.036882
ICX     0.222329
NEO     0.173128
BNB     0.106531
Name: 399, dtype: float64
牛式===============================
執行第 406
           406
TRX  -0.179034
ALGO -0.143099
LINK -0.112642
ATOM -0.086981
LTC  -0.066622
ZIL  -0.050395
IOTA -0.042017
BAT  -0.040904
ZRX  -0.023721
VET  -0.020725
ZEC  -0.007353
XLM  -0.005495
ADA  -0.003321
QTUM  0.009832
XRP   0.018542
ETH   0.036882
BCH   0.050092
BNB   0.106531
NEO   0.173128
ICX   0.222329
g================================================================          ETH     BCH     BNB     NEO     ICX
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  509.55  327.67  37.005  0.9279
721  2121.52  490.60  310.59  34.083  1.0350
722  2146.27  504.08  316.72  34.637  0.9786
723  2111.19  497.02  316.09  34.057  0.9198
724  2138.86  498.00  321.87  34.191  0.9519

[725 rows x 5 columns]
ETH   -0.008939
BCH    0.013540
BNB    0.133659
NEO    0.134889
ICX    0.088811
Name: 400, dtype: float64
報酬 0.07239206451877116 %
i= ETH   -0.008939
BCH    0.013540
BNB    0.133659
NEO    0.134889
ICX    0.088811
Name: 400, dtype: float64
牛式===============================
執行第 407
           407
TRX  -0.200364
LINK -0.142971
ALGO -0.130961
IOTA -0.096128
ZRX  -0.090079
LTC  -0.079705
QTUM -0.066362
ZEC  -0.059184
ADA  -0.057641
BAT  -0.056788
VET  -0.042769
ATOM -0.039610
ZIL  -0.023162
XLM  -0.014914
ETH  -0.008939
BCH   0.013540
XRP   0.014270
ICX   0.088811
BNB   0.133659
NEO   0.134889
g================================================================         BCH     XRP     ICX     BNB     NEO
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  509.55  0.6521  0.9279  327.67  37.005
721  490.60  0.6236  1.0350  310.59  34.083
722  504.08  0.6372  0.9786  316.72  34.637
723  497.02  0.6251  0.9198  316.09  34.057
724  498.00  0.6362  0.9519  321.87  34.191

[725 rows x 5 columns]
BCH    0.034236
XRP    0.039677
ICX    0.049297
BNB    0.064935
NEO    0.171898
Name: 401, dtype: float64
報酬 0.0720086708422647 %
i= BCH    0.034236
XRP    0.039677
ICX    0.049297
BNB    0.064935
NEO    0.171898
Name: 401, dtype: float64
牛式===============================
執行第 408
           408
ZRX  -0.167548
TRX  -0.160752
ALGO -0.132603
LINK -0.116559
LTC  -0.114715
QTUM -0.088778
ZEC  -0.058117
BAT  -0.053808
ATOM -0.051104
IOTA -0.042306
XLM  -0.039651
ZIL  -0.035383
ADA  -0.029306
VET   0.020086
BCH   0.034236
XRP   0.039677
ETH   0.041341
ICX   0.049297
BNB   0.064935
NEO   0.171898
g================================================================         XRP      ETH     ICX     BNB     NEO
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.6521  2316.15  0.9279  327.67  37.005
721  0.6236  2121.52  1.0350  310.59  34.083
722  0.6372  2146.27  0.9786  316.72  34.637
723  0.6251  2111.19  0.9198  316.09  34.057
724  0.6362  2138.86  0.9519  321.87  34.191

[725 rows x 5 columns]
XRP    0.012645
ETH   -0.008716
ICX   -0.033537
BNB   -0.029113
NEO    0.164235
Name: 402, dtype: float64
報酬 0.021102947102938606 %
i= XRP    0.012645
ETH   -0.008716
ICX   -0.033537
BNB   -0.029113
NEO    0.164235
Name: 402, dtype: float64
牛式===============================
執行第 409
           409
LINK -0.206761
ZRX  -0.192561
ALGO -0.176528
LTC  -0.152334
ZEC  -0.118185
ATOM -0.113689
TRX  -0.111892
BAT  -0.110989
IOTA -0.086811
ADA  -0.068577
XLM  -0.066818
ZIL  -0.040495
ICX  -0.033537
BNB  -0.029113
QTUM -0.017175
ETH  -0.008716
XRP   0.012645
BCH   0.016731
VET   0.074860
NEO   0.164235
g================================================================          ETH     XRP     BCH      VET     NEO
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  2316.15  0.6521  509.55  0.08348  37.005
721  2121.52  0.6236  490.60  0.07614  34.083
722  2146.27  0.6372  504.08  0.07704  34.637
723  2111.19  0.6251  497.02  0.07591  34.057
724  2138.86  0.6362  498.00  0.07768  34.191

[725 rows x 5 columns]
ETH    0.053294
XRP    0.037978
BCH    0.049788
VET    0.192224
NEO    0.208249
Name: 403, dtype: float64
報酬 0.10830662410298197 %
i= ETH    0.053294
XRP    0.037978
BCH    0.049788
VET    0.192224
NEO    0.208249
Name: 403, dtype: float64
牛式===============================
執行第 410
           410
LINK -0.159336
BNB  -0.127366
ZRX  -0.120902
TRX  -0.095953
ALGO -0.092210
ZEC  -0.071737
ATOM -0.069627
BAT  -0.059325
ADA  -0.037474
IOTA -0.032040
ICX  -0.025042
XLM  -0.017009
QTUM -0.006420
LTC   0.006862
ZIL   0.010791
XRP   0.037978
BCH   0.049788
ETH   0.053294
VET   0.192224
NEO   0.208249
g================================================================         XRP     BCH      ETH      VET     NEO
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  0.6521  509.55  2316.15  0.08348  37.005
721  0.6236  490.60  2121.52  0.07614  34.083
722  0.6372  504.08  2146.27  0.07704  34.637
723  0.6251  497.02  2111.19  0.07591  34.057
724  0.6362  498.00  2138.86  0.07768  34.191

[725 rows x 5 columns]
XRP    0.002929
BCH    0.002170
ETH   -0.016732
VET    0.126460
NEO    0.070751
Name: 404, dtype: float64
報酬 0.03711574986611965 %
i= XRP    0.002929
BCH    0.002170
ETH   -0.016732
VET    0.126460
NEO    0.070751
Name: 404, dtype: float64
牛式===============================
執行第 411
           411
LINK -0.197032
ZRX  -0.165363
BNB  -0.153970
ALGO -0.142109
ATOM -0.132689
TRX  -0.113195
ICX  -0.109381
ZEC  -0.089356
IOTA -0.076301
ADA  -0.075849
BAT  -0.073323
ZIL  -0.062053
QTUM -0.043989
XLM  -0.040055
ETH  -0.016732
LTC  -0.008229
BCH   0.002170
XRP   0.002929
NEO   0.070751
VET   0.126460
g================================================================         LTC     BCH     XRP     NEO      VET
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  137.39  509.55  0.6521  37.005  0.08348
721  132.25  490.60  0.6236  34.083  0.07614
722  134.42  504.08  0.6372  34.637  0.07704
723  134.00  497.02  0.6251  34.057  0.07591
724  134.19  498.00  0.6362  34.191  0.07768

[725 rows x 5 columns]
LTC    0.049488
BCH   -0.097147
XRP   -0.051407
NEO   -0.010851
VET    0.002546
Name: 405, dtype: float64
報酬 -0.021474319533902043 %
i= LTC    0.049488
BCH   -0.097147
XRP   -0.051407
NEO   -0.010851
VET    0.002546
Name: 405, dtype: float64
牛式===============================
執行第 412
           412
LINK -0.203653
ICX  -0.190139
ALGO -0.188189
ZRX  -0.181008
ATOM -0.160905
BNB  -0.151236
ADA  -0.143809
BAT  -0.134444
ZEC  -0.131987
IOTA -0.124635
ZIL  -0.120844
TRX  -0.107245
XLM  -0.101388
BCH  -0.097147
QTUM -0.082353
ETH  -0.065482
XRP  -0.051407
NEO  -0.010851
VET   0.002546
LTC   0.049488
g================================================================          ETH     XRP     NEO      VET     LTC
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  2316.15  0.6521  37.005  0.08348  137.39
721  2121.52  0.6236  34.083  0.07614  132.25
722  2146.27  0.6372  34.637  0.07704  134.42
723  2111.19  0.6251  34.057  0.07591  134.00
724  2138.86  0.6362  34.191  0.07768  134.19

[725 rows x 5 columns]
ETH   -0.056367
XRP   -0.055263
NEO   -0.035452
VET   -0.007795
LTC    0.024503
Name: 406, dtype: float64
報酬 -0.02607484295064886 %
i= ETH   -0.056367
XRP   -0.055263
NEO   -0.035452
VET   -0.007795
LTC    0.024503
Name: 406, dtype: float64
牛式===============================
執行第 413
           413
LINK -0.185461
ATOM -0.177091
ZIL  -0.161233
ICX  -0.154654
ALGO -0.149025
BNB  -0.135873
ZRX  -0.111837
ADA  -0.108655
XLM  -0.103228
IOTA -0.100443
BAT  -0.088118
ZEC  -0.086219
ETH  -0.056367
XRP  -0.055263
TRX  -0.053071
BCH  -0.045413
QTUM -0.043709
NEO  -0.035452
VET  -0.007795
LTC   0.024503
g================================================================         BCH   QTUM     NEO      VET     LTC
0       NaN    NaN     NaN      NaN     NaN
1       NaN    NaN     NaN      NaN     NaN
2       NaN    NaN     NaN      NaN     NaN
3       NaN    NaN     NaN      NaN     NaN
4       NaN    NaN     NaN      NaN     NaN
..      ...    ...     ...      ...     ...
720  509.55  7.079  37.005  0.08348  137.39
721  490.60  6.504  34.083  0.07614  132.25
722  504.08  6.776  34.637  0.07704  134.42
723  497.02  6.639  34.057  0.07591  134.00
724  498.00  6.694  34.191  0.07768  134.19

[725 rows x 5 columns]
BCH    -0.108626
QTUM   -0.154326
NEO    -0.175483
VET    -0.159153
LTC    -0.023053
Name: 407, dtype: float64
報酬 -0.12412801003025835 %
i= BCH    -0.108626
QTUM   -0.154326
NEO    -0.175483
VET    -0.159153
LTC    -0.023053
Name: 407, dtype: float64
牛式===============================
執行第 414
           414
LINK -0.307552
ALGO -0.247966
ATOM -0.242651
ZRX  -0.226912
ICX  -0.210459
ADA  -0.185819
ETH  -0.178316
NEO  -0.175483
IOTA -0.173139
ZIL  -0.167168
XLM  -0.163661
VET  -0.159153
BNB  -0.157058
QTUM -0.154326
BAT  -0.149379
ZEC  -0.133467
XRP  -0.122223
TRX  -0.117626
BCH  -0.108626
LTC  -0.023053
g================================================================         ZEC     XRP      TRX     BCH     LTC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  118.51  0.6521  0.06432  509.55  137.39
721  109.38  0.6236  0.06111  490.60  132.25
722  110.99  0.6372  0.06219  504.08  134.42
723  108.15  0.6251  0.06139  497.02  134.00
724  110.82  0.6362  0.06184  498.00  134.19

[725 rows x 5 columns]
ZEC   -0.048359
XRP   -0.071694
TRX   -0.096386
BCH   -0.076039
LTC    0.034922
Name: 408, dtype: float64
報酬 -0.05151095291851186 %
i= ZEC   -0.048359
XRP   -0.071694
TRX   -0.096386
BCH   -0.076039
LTC    0.034922
Name: 408, dtype: float64
牛式===============================
執行第 415
           415
QTUM -0.173680
ZIL  -0.144197
ICX  -0.142166
VET  -0.141719
NEO  -0.137587
ALGO -0.127375
BNB  -0.111994
XLM  -0.101010
IOTA -0.097623
ATOM -0.097261
TRX  -0.096386
ADA  -0.093077
ETH  -0.091753
ZRX  -0.082774
BCH  -0.076039
BAT  -0.072279
XRP  -0.071694
ZEC  -0.048359
LINK -0.021804
LTC   0.034922
g================================================================         BAT     XRP     ZEC   LINK     LTC
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.6135  0.6521  118.51  19.79  137.39
721  0.5691  0.6236  109.38  18.44  132.25
722  0.5695  0.6372  110.99  18.66  134.42
723  0.5575  0.6251  108.15  18.20  134.00
724  0.5623  0.6362  110.82  18.38  134.19

[725 rows x 5 columns]
BAT    -0.042869
XRP    -0.038380
ZEC    -0.054166
LINK    0.057256
LTC    -0.017391
Name: 409, dtype: float64
報酬 -0.019110175179608446 %
i= BAT    -0.042869
XRP    -0.038380
ZEC    -0.054166
LINK    0.057256
LTC    -0.017391
Name: 409, dtype: float64
牛式===============================
執行第 416
           416
VET  -0.154617
NEO  -0.130266
ICX  -0.115796
QTUM -0.103003
BNB  -0.092647
ETH  -0.086604
ALGO -0.074431
BCH  -0.071527
IOTA -0.059213
ZEC  -0.054166
ZIL  -0.053974
ZRX  -0.053613
XLM  -0.050000
BAT  -0.042869
XRP  -0.038380
ATOM -0.032160
TRX  -0.021300
LTC  -0.017391
LINK  0.057256
ADA   0.059821
g================================================================        ATOM      TRX     LTC   LINK     ADA
0       NaN      NaN     NaN    NaN     NaN
1       NaN      NaN     NaN    NaN     NaN
2       NaN      NaN     NaN    NaN     NaN
3       NaN      NaN     NaN    NaN     NaN
4       NaN      NaN     NaN    NaN     NaN
..      ...      ...     ...    ...     ...
720  12.946  0.06432  137.39  19.79  1.4039
721  11.958  0.06111  132.25  18.44  1.3327
722  13.182  0.06219  134.42  18.66  1.3497
723  14.395  0.06139  134.00  18.20  1.3356
724  14.064  0.06184  134.19  18.38  1.3478

[725 rows x 5 columns]
ATOM   -0.014785
TRX     0.009276
LTC     0.018729
LINK    0.056468
ADA     0.068973
Name: 410, dtype: float64
報酬 0.027732489388809078 %
i= ATOM   -0.014785
TRX     0.009276
LTC     0.018729
LINK    0.056468
ADA     0.068973
Name: 410, dtype: float64
牛式===============================
執行第 417
           417
VET  -0.112125
NEO  -0.109928
ICX  -0.068837
QTUM -0.049980
ETH  -0.045683
XLM  -0.040296
ZEC  -0.024140
BCH  -0.022054
XRP  -0.020445
BAT  -0.020202
ATOM -0.014785
ZRX  -0.008361
ALGO -0.007322
BNB  -0.004559
IOTA  0.001142
TRX   0.009276
LTC   0.018729
ZIL   0.038168
LINK  0.056468
ADA   0.068973
g================================================================          TRX     LTC      ZIL   LINK     ADA
0        NaN     NaN      NaN    NaN     NaN
1        NaN     NaN      NaN    NaN     NaN
2        NaN     NaN      NaN    NaN     NaN
3        NaN     NaN      NaN    NaN     NaN
4        NaN     NaN      NaN    NaN     NaN
..       ...     ...      ...    ...     ...
720  0.06432  137.39  0.08133  19.79  1.4039
721  0.06111  132.25  0.07509  18.44  1.3327
722  0.06219  134.42  0.07496  18.66  1.3497
723  0.06139  134.00  0.07299  18.20  1.3356
724  0.06184  134.19  0.07377  18.38  1.3478

[725 rows x 5 columns]
TRX     0.067899
LTC     0.008388
ZIL     0.127273
LINK    0.237385
ADA     0.271655
Name: 411, dtype: float64
報酬 0.1425198910522168 %
i= TRX     0.067899
LTC     0.008388
ZIL     0.127273
LINK    0.237385
ADA     0.271655
Name: 411, dtype: float64

牛式===============================
執行第 418
           418
ICX   0.007761
LTC   0.008388
VET   0.011110
QTUM  0.047745
XLM   0.048906
ETH   0.050642
XRP   0.054150
NEO   0.054603
TRX   0.067899
ZRX   0.075939
BAT   0.076490
ZEC   0.077386
BCH   0.079817
IOTA  0.084342
ALGO  0.116603
ZIL   0.127273
BNB   0.139939
ATOM  0.158901
LINK  0.237385
ADA   0.271655
g================================================================          ZIL     BNB    ATOM   LINK     ADA
0        NaN     NaN     NaN    NaN     NaN
1        NaN     NaN     NaN    NaN     NaN
2        NaN     NaN     NaN    NaN     NaN
3        NaN     NaN     NaN    NaN     NaN
4        NaN     NaN     NaN    NaN     NaN
..       ...     ...     ...    ...     ...
720  0.08133  327.67  12.946  19.79  1.4039
721  0.07509  310.59  11.958  18.44  1.3327
722  0.07496  316.72  13.182  18.66  1.3497
723  0.07299  316.09  14.395  18.20  1.3356
724  0.07377  321.87  14.064  18.38  1.3478

[725 rows x 5 columns]
ZIL     0.067845
BNB     0.122712
ATOM    0.147743
LINK    0.176201
ADA     0.232384
Name: 412, dtype: float64
報酬 0.14937710049308262 %
i= ZIL     0.067845
BNB     0.122712
ATOM    0.147743
LINK    0.176201
ADA     0.232384
Name: 412, dtype: float64
牛式===============================
執行第 419
           419
ICX  -0.042513
NEO  -0.005244
XLM   0.021766
BAT   0.024049
BCH   0.025672
ETH   0.028124
XRP   0.034977
VET   0.035798
QTUM  0.036309
LTC   0.050675
TRX   0.052042
ZEC   0.054399
ZIL   0.067845
ALGO  0.070376
ZRX   0.085962
IOTA  0.100985
BNB   0.122712
ATOM  0.147743
LINK  0.176201
ADA   0.232384
g================================================================        IOTA     BNB    ATOM   LINK     ADA
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.8896  327.67  12.946  19.79  1.4039
721  0.8165  310.59  11.958  18.44  1.3327
722  0.8180  316.72  13.182  18.66  1.3497
723  0.7913  316.09  14.395  18.20  1.3356
724  0.8404  321.87  14.064  18.38  1.3478

[725 rows x 5 columns]
IOTA    0.180956
BNB     0.262166
ATOM    0.380568
LINK    0.331143
ADA     0.320016
Name: 413, dtype: float64
報酬 0.2949697915415821 %
i= IOTA    0.180956
BNB     0.262166
ATOM    0.380568
LINK    0.331143
ADA     0.320016
Name: 413, dtype: float64
牛式===============================
執行第 420
           420
NEO   0.001884
TRX   0.059203
XRP   0.097392
XLM   0.101115
BCH   0.103078
LTC   0.105564
BAT   0.118644
QTUM  0.121198
ETH   0.124414
ICX   0.147281
VET   0.159345
IOTA  0.180956
ZEC   0.185759
ZRX   0.197534
ZIL   0.261372
BNB   0.262166
ALGO  0.266319
ADA   0.320016
LINK  0.331143
ATOM  0.380568
g================================================================         BNB    ALGO     ADA   LINK    ATOM
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  327.67  0.9062  1.4039  19.79  12.946
721  310.59  0.8683  1.3327  18.44  11.958
722  316.72  0.9059  1.3497  18.66  13.182
723  316.09  0.8918  1.3356  18.20  14.395
724  321.87  0.8952  1.3478  18.38  14.064

[725 rows x 5 columns]
BNB     0.190806
ALGO    0.178292
ADA     0.228281
LINK    0.000000
ATOM    0.198751
Name: 414, dtype: float64
報酬 0.15922578614137897 %
i= BNB     0.190806
ALGO    0.178292
ADA     0.228281
LINK    0.000000
ATOM    0.198751
Name: 414, dtype: float64
牛式===============================
執行第 421
           421
NEO  -0.125384
TRX  -0.001143
LINK  0.000000
ETH   0.030361
ICX   0.030645
XRP   0.038637
QTUM  0.050065
BCH   0.054633
BAT   0.059761
XLM   0.064429
ZRX   0.070102
VET   0.092531
LTC   0.095567
IOTA  0.147893
ZEC   0.164610
ALGO  0.178292
BNB   0.190806
ATOM  0.198751
ADA   0.228281
ZIL   0.336986
g================================================================        ALGO     BNB    ATOM     ADA      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.9062  327.67  12.946  1.4039  0.08133
721  0.8683  310.59  11.958  1.3327  0.07509
722  0.9059  316.72  13.182  1.3497  0.07496
723  0.8918  316.09  14.395  1.3356  0.07299
724  0.8952  321.87  14.064  1.3478  0.07377

[725 rows x 5 columns]
ALGO    0.056449
BNB     0.113857
ATOM    0.071891
ADA     0.011660
ZIL     0.219436
Name: 415, dtype: float64
報酬 0.09465876224028898 %
i= ALGO    0.056449
BNB     0.113857
ATOM    0.071891
ADA     0.011660
ZIL     0.219436
Name: 415, dtype: float64
牛式===============================
執行第 422
           422
NEO  -0.118077
LINK -0.098973
TRX  -0.047215
XLM  -0.020490
ZRX  -0.017488
XRP  -0.013704
VET  -0.013247
BAT  -0.008183
QTUM  0.002966
ETH   0.003439
ADA   0.011660
ICX   0.051077
BCH   0.052743
ALGO  0.056449
IOTA  0.063331
ATOM  0.071891
LTC   0.093279
BNB   0.113857
ZEC   0.179464
ZIL   0.219436
g================================================================        ATOM     LTC     BNB     ZEC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  12.946  137.39  327.67  118.51  0.08133
721  11.958  132.25  310.59  109.38  0.07509
722  13.182  134.42  316.72  110.99  0.07496
723  14.395  134.00  316.09  108.15  0.07299
724  14.064  134.19  321.87  110.82  0.07377

[725 rows x 5 columns]
ATOM    0.066986
LTC     0.134745
BNB     0.041985
ZEC     0.136323
ZIL     0.104167
Name: 416, dtype: float64
報酬 0.09684108113064949 %
i= ATOM    0.066986
LTC     0.134745
BNB     0.041985
ZEC     0.136323
ZIL     0.104167
Name: 416, dtype: float64
牛式===============================
執行第 423
           423
NEO  -0.138085
LINK -0.103984
VET  -0.076612
ICX  -0.074161
TRX  -0.047794
QTUM -0.044676
XLM  -0.038873
BAT  -0.038230
XRP  -0.031515
ALGO -0.029502
ADA  -0.027967
ETH  -0.023030
BCH  -0.007502
ZRX  -0.004343
IOTA  0.022053
BNB   0.041985
ATOM  0.066986
ZIL   0.104167
LTC   0.134745
ZEC   0.136323
g================================================================         BNB    ATOM      ZIL     LTC     ZEC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  327.67  12.946  0.08133  137.39  118.51
721  310.59  11.958  0.07509  132.25  109.38
722  316.72  13.182  0.07496  134.42  110.99
723  316.09  14.395  0.07299  134.00  108.15
724  321.87  14.064  0.07377  134.19  110.82

[725 rows x 5 columns]
BNB     0.074724
ATOM    0.060093
ZIL     0.198065
LTC     0.042266
ZEC     0.093429
Name: 417, dtype: float64
報酬 0.09371534940704054 %
i= BNB     0.074724
ATOM    0.060093
ZIL     0.198065
LTC     0.042266
ZEC     0.093429
Name: 417, dtype: float64
牛式===============================
執行第 424
           424
NEO  -0.158069
LINK -0.140871
VET  -0.079193
ADA  -0.079072
ICX  -0.062575
ZRX  -0.048318
BCH  -0.047011
XRP  -0.043478
BAT  -0.040105
ETH  -0.032339
XLM  -0.032311
QTUM -0.030380
ALGO -0.016833
IOTA  0.021948
TRX   0.023326
LTC   0.042266
ATOM  0.060093
BNB   0.074724
ZEC   0.093429
ZIL   0.198065
g================================================================         LTC    ATOM     BNB     ZEC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  137.39  12.946  327.67  118.51  0.08133
721  132.25  11.958  310.59  109.38  0.07509
722  134.42  13.182  316.72  110.99  0.07496
723  134.00  14.395  316.09  108.15  0.07299
724  134.19  14.064  321.87  110.82  0.07377

[725 rows x 5 columns]
LTC     0.060852
ATOM    0.101200
BNB     0.075213
ZEC     0.122754
ZIL     0.409001
Name: 418, dtype: float64
報酬 0.15380398403092782 %
i= LTC     0.060852
ATOM    0.101200
BNB     0.075213
ZEC     0.122754
ZIL     0.409001
Name: 418, dtype: float64
牛式===============================
執行第 425
           425
NEO  -0.098215
ZRX  -0.088840
VET  -0.088201
LINK -0.086576
QTUM -0.049464
ALGO -0.045872
BAT  -0.045687
ADA  -0.036059
BCH  -0.021486
ICX  -0.013470
XLM  -0.004643
ETH  -0.003956
TRX   0.006088
IOTA  0.025354
XRP   0.027907
LTC   0.060852
BNB   0.075213
ATOM  0.101200
ZEC   0.122754
ZIL   0.409001
g================================================================         LTC     BNB    ATOM     ZEC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  137.39  327.67  12.946  118.51  0.08133
721  132.25  310.59  11.958  109.38  0.07509
722  134.42  316.72  13.182  110.99  0.07496
723  134.00  316.09  14.395  108.15  0.07299
724  134.19  321.87  14.064  110.82  0.07377

[725 rows x 5 columns]
LTC     0.105370
BNB    -0.007642
ATOM    0.012453
ZEC     0.073433
ZIL     0.184888
Name: 419, dtype: float64
報酬 0.07370053366037814 %
i= LTC     0.105370
BNB    -0.007642
ATOM    0.012453
ZEC     0.073433
ZIL     0.184888
Name: 419, dtype: float64
牛式===============================
執行第 426
           426
VET  -0.135622
NEO  -0.102150
ZRX  -0.076961
ICX  -0.076273
BAT  -0.067761
ALGO -0.063034
QTUM -0.054665
LINK -0.050346
ADA  -0.036004
BCH  -0.031702
ETH  -0.017566
IOTA -0.010580
XLM  -0.010533
BNB  -0.007642
TRX   0.004563
ATOM  0.012453
XRP   0.030722
ZEC   0.073433
LTC   0.105370
ZIL   0.184888
g================================================================        ATOM     XRP     ZEC     LTC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  12.946  0.6521  118.51  137.39  0.08133
721  11.958  0.6236  109.38  132.25  0.07509
722  13.182  0.6372  110.99  134.42  0.07496
723  14.395  0.6251  108.15  134.00  0.07299
724  14.064  0.6362  110.82  134.19  0.07377

[725 rows x 5 columns]
ATOM   -0.118720
XRP     0.016138
ZEC    -0.041920
LTC     0.081610
ZIL    -0.068648
Name: 420, dtype: float64
報酬 -0.02630795647781259 %
i= ATOM   -0.118720
XRP     0.016138
ZEC    -0.041920
LTC     0.081610
ZIL    -0.068648
Name: 420, dtype: float64
牛式===============================
執行第 427
           427
VET  -0.252679
ALGO -0.174415
ICX  -0.147716
ZRX  -0.140064
NEO  -0.131670
BAT  -0.119883
ATOM -0.118720
LINK -0.111449
IOTA -0.107307
QTUM -0.107275
ADA  -0.083555
ZIL  -0.068648
BNB  -0.053980
ETH  -0.052428
ZEC  -0.041920
BCH  -0.036626
XLM  -0.033004
TRX  -0.024790
XRP   0.016138
LTC   0.081610
g================================================================         BCH      XLM      TRX     XRP     LTC
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  509.55  0.25677  0.06432  0.6521  137.39
721  490.60  0.24383  0.06111  0.6236  132.25
722  504.08  0.24550  0.06219  0.6372  134.42
723  497.02  0.24484  0.06139  0.6251  134.00
724  498.00  0.24587  0.06184  0.6362  134.19

[725 rows x 5 columns]
BCH   -0.020707
XLM   -0.011348
TRX   -0.012002
XRP    0.043825
LTC    0.027346
Name: 421, dtype: float64
報酬 0.005422899525215641 %
i= BCH   -0.020707
XLM   -0.011348
TRX   -0.012002
XRP    0.043825
LTC    0.027346
Name: 421, dtype: float64
牛式===============================
執行第 428
           428
ICX  -0.152004
VET  -0.116894
NEO  -0.107779
ZRX  -0.104036
ALGO -0.083284
QTUM -0.072666
LINK -0.068394
BAT  -0.067738
IOTA -0.050735
ZEC  -0.048400
ATOM -0.047183
ADA  -0.043860
ETH  -0.031978
ZIL  -0.028792
BCH  -0.020707
TRX  -0.012002
XLM  -0.011348
BNB   0.007639
LTC   0.027346
XRP   0.043825
g================================================================          TRX      XLM     BNB     LTC     XRP
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.06432  0.25677  327.67  137.39  0.6521
721  0.06111  0.24383  310.59  132.25  0.6236
722  0.06219  0.24550  316.72  134.42  0.6372
723  0.06139  0.24484  316.09  134.00  0.6251
724  0.06184  0.24587  321.87  134.19  0.6362

[725 rows x 5 columns]
TRX   -0.006950
XLM    0.030862
BNB    0.014286
LTC   -0.044299
XRP    0.074061
Name: 422, dtype: float64
報酬 0.013592232780650536 %
i= TRX   -0.006950
XLM    0.030862
BNB    0.014286
LTC   -0.044299
XRP    0.074061
Name: 422, dtype: float64
牛式===============================
執行第 429
           429
VET  -0.071754
NEO  -0.059207
ZRX  -0.055684
LTC  -0.044299
ICX  -0.040051
ZEC  -0.029131
BAT  -0.027244
ALGO -0.023116
IOTA -0.023065
QTUM -0.016608
TRX  -0.006950
BNB   0.014286
ETH   0.014636
ATOM  0.027110
XLM   0.030862
LINK  0.034707
ADA   0.036422
BCH   0.065115
ZIL   0.066593
XRP   0.074061
g================================================================       LINK     ADA     BCH      ZIL     XRP
0      NaN     NaN     NaN      NaN     NaN
1      NaN     NaN     NaN      NaN     NaN
2      NaN     NaN     NaN      NaN     NaN
3      NaN     NaN     NaN      NaN     NaN
4      NaN     NaN     NaN      NaN     NaN
..     ...     ...     ...      ...     ...
720  19.79  1.4039  509.55  0.08133  0.6521
721  18.44  1.3327  490.60  0.07509  0.6236
722  18.66  1.3497  504.08  0.07496  0.6372
723  18.20  1.3356  497.02  0.07299  0.6251
724  18.38  1.3478  498.00  0.07377  0.6362

[725 rows x 5 columns]
LINK    0.120820
ADA     0.086183
BCH     0.085114
ZIL     0.085622
XRP     0.086999
Name: 423, dtype: float64
報酬 0.09294766938585317 %
i= LINK    0.120820
ADA     0.086183
BCH     0.085114
ZIL     0.085622
XRP     0.086999
Name: 423, dtype: float64

牛式===============================
執行第 430
           430
TRX  -0.034191
LTC  -0.029120
NEO  -0.023251
VET  -0.022332
BNB   0.006740
BAT   0.008629
QTUM  0.013925
IOTA  0.016956
ICX   0.022336
ATOM  0.028942
ZRX   0.035619
ALGO  0.041852
ZEC   0.045769
ETH   0.055218
XLM   0.056777
BCH   0.085114
ZIL   0.085622
ADA   0.086183
XRP   0.086999
LINK  0.120820
g================================================================         BCH      ZIL     ADA     XRP   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  509.55  0.08133  1.4039  0.6521  19.79
721  490.60  0.07509  1.3327  0.6236  18.44
722  504.08  0.07496  1.3497  0.6372  18.66
723  497.02  0.07299  1.3356  0.6251  18.20
724  498.00  0.07377  1.3478  0.6362  18.38

[725 rows x 5 columns]
BCH     0.074158
ZIL    -0.073744
ADA     0.084117
XRP     0.024406
LINK    0.120341
Name: 424, dtype: float64
報酬 0.045855625046326655 %
i= BCH     0.074158
ZIL    -0.073744
ADA     0.084117
XRP     0.024406
LINK    0.120341
Name: 424, dtype: float64
牛式===============================
執行第 431
           431
ZIL  -0.073744
NEO  -0.033197
VET  -0.022382
BNB  -0.022054
BAT  -0.015660
IOTA -0.007636
ICX  -0.006068
QTUM -0.002602
TRX  -0.000378
LTC   0.006373
XRP   0.024406
ATOM  0.040030
ALGO  0.045513
ZRX   0.049681
ETH   0.051267
ZEC   0.058469
XLM   0.060914
BCH   0.074158
ADA   0.084117
LINK  0.120341
g================================================================         ZEC      XLM     BCH     ADA   LINK
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  118.51  0.25677  509.55  1.4039  19.79
721  109.38  0.24383  490.60  1.3327  18.44
722  110.99  0.24550  504.08  1.3497  18.66
723  108.15  0.24484  497.02  1.3356  18.20
724  110.82  0.24587  498.00  1.3478  18.38

[725 rows x 5 columns]
ZEC     0.101703
XLM     0.052136
BCH     0.078422
ADA     0.092346
LINK    0.127859
Name: 425, dtype: float64
報酬 0.0904928864581799 %
i= ZEC     0.101703
XLM     0.052136
BCH     0.078422
ADA     0.092346
LINK    0.127859
Name: 425, dtype: float64
牛式===============================
執行第 432
           432
LTC  -0.029878
ZIL  -0.006763
BNB  -0.001750
BAT   0.001354
VET   0.004568
NEO   0.005604
ICX   0.005843
TRX   0.006056
XRP   0.020217
QTUM  0.023478
ZRX   0.036909
IOTA  0.040929
ALGO  0.043383
XLM   0.052136
ETH   0.058534
BCH   0.078422
ADA   0.092346
ZEC   0.101703
LINK  0.127859
ATOM  0.132874
g================================================================         BCH     ADA     ZEC   LINK    ATOM
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  509.55  1.4039  118.51  19.79  12.946
721  490.60  1.3327  109.38  18.44  11.958
722  504.08  1.3497  110.99  18.66  13.182
723  497.02  1.3356  108.15  18.20  14.395
724  498.00  1.3478  110.82  18.38  14.064

[725 rows x 5 columns]
BCH     0.091518
ADA     0.178902
ZEC     0.187378
LINK    0.302166
ATOM    0.260557
Name: 426, dtype: float64
報酬 0.20410430312456143 %
i= BCH     0.091518
ADA     0.178902
ZEC     0.187378
LINK    0.302166
ATOM    0.260557
Name: 426, dtype: float64
牛式===============================
執行第 433
           433
LTC  -0.023696
XRP   0.042554
BAT   0.045562
TRX   0.059054
XLM   0.071991
QTUM  0.079650
NEO   0.086020
BCH   0.091518
BNB   0.107259
ZIL   0.114411
ZRX   0.123934
VET   0.125989
ETH   0.133893
ICX   0.138152
IOTA  0.139185
ADA   0.178902
ZEC   0.187378
ALGO  0.204967
ATOM  0.260557
LINK  0.302166
g================================================================         ADA     ZEC    ALGO    ATOM   LINK
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  1.4039  118.51  0.9062  12.946  19.79
721  1.3327  109.38  0.8683  11.958  18.44
722  1.3497  110.99  0.9059  13.182  18.66
723  1.3356  108.15  0.8918  14.395  18.20
724  1.3478  110.82  0.8952  14.064  18.38

[725 rows x 5 columns]
ADA     0.166098
ZEC     0.138609
ALGO    0.116249
ATOM    0.229793
LINK    0.223582
Name: 427, dtype: float64
報酬 0.1748661235025041 %
i= ADA     0.166098
ZEC     0.138609
ALGO    0.116249
ATOM    0.229793
LINK    0.223582
Name: 427, dtype: float64
牛式===============================
執行第 434
           434
LTC  -0.103492
BAT   0.011178
VET   0.020713
XRP   0.031529
NEO   0.048331
TRX   0.049765
XLM   0.056009
ZIL   0.058761
QTUM  0.061503
IOTA  0.100697
BNB   0.109386
ICX   0.114068
ETH   0.115051
ALGO  0.116249
BCH   0.134934
ZEC   0.138609
ADA   0.166098
ZRX   0.170118
LINK  0.223582
ATOM  0.229793
g================================================================         ZEC     ADA     ZRX   LINK    ATOM
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  118.51  1.4039  0.7889  19.79  12.946
721  109.38  1.3327  0.8190  18.44  11.958
722  110.99  1.3497  0.8384  18.66  13.182
723  108.15  1.3356  0.7890  18.20  14.395
724  110.82  1.3478  0.7950  18.38  14.064

[725 rows x 5 columns]
ZEC     0.109534
ADA     0.112497
ZRX     0.050815
LINK    0.141509
ATOM    0.136337
Name: 428, dtype: float64
報酬 0.11013848451025879 %
i= ZEC     0.109534
ADA     0.112497
ZRX     0.050815
LINK    0.141509
ATOM    0.136337
Name: 428, dtype: float64
牛式===============================
執行第 435
           435
LTC  -0.107940
BAT  -0.014233
ZIL  -0.011446
XRP  -0.008281
NEO  -0.003408
QTUM  0.001778
XLM   0.011210
VET   0.011264
ICX   0.030103
TRX   0.040047
IOTA  0.041508
ZRX   0.050815
ALGO  0.062237
ETH   0.079563
BCH   0.107263
ZEC   0.109534
ADA   0.112497
BNB   0.113759
ATOM  0.136337
LINK  0.141509
g================================================================         ZEC     ADA     BNB    ATOM   LINK
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  118.51  1.4039  327.67  12.946  19.79
721  109.38  1.3327  310.59  11.958  18.44
722  110.99  1.3497  316.72  13.182  18.66
723  108.15  1.3356  316.09  14.395  18.20
724  110.82  1.3478  321.87  14.064  18.38

[725 rows x 5 columns]
ZEC     0.074307
ADA     0.052798
BNB     0.102889
ATOM    0.119108
LINK    0.034649
Name: 429, dtype: float64
報酬 0.07675016320550507 %
i= ZEC     0.074307
ADA     0.052798
BNB     0.102889
ATOM    0.119108
LINK    0.034649
Name: 429, dtype: float64
牛式===============================
執行第 436
           436
ZIL  -0.074405
LTC  -0.062875
VET  -0.044202
ALGO -0.043822
ICX  -0.043697
QTUM -0.042918
BAT  -0.040072
XRP  -0.027865
XLM  -0.012265
NEO  -0.009545
TRX   0.009517
ZRX   0.021047
IOTA  0.025195
ETH   0.034274
LINK  0.034649
ADA   0.052798
ZEC   0.074307
BNB   0.102889
BCH   0.105933
ATOM  0.119108
g================================================================         ADA     ZEC     BNB     BCH    ATOM
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  1.4039  118.51  327.67  509.55  12.946
721  1.3327  109.38  310.59  490.60  11.958
722  1.3497  110.99  316.72  504.08  13.182
723  1.3356  108.15  316.09  497.02  14.395
724  1.3478  110.82  321.87  498.00  14.064

[725 rows x 5 columns]
ADA    -0.007340
ZEC    -0.063473
BNB     0.057435
BCH     0.054202
ATOM   -0.024395
Name: 430, dtype: float64
報酬 0.0032859249561469463 %
i= ADA    -0.007340
ZEC    -0.063473
BNB     0.057435
BCH     0.054202
ATOM   -0.024395
Name: 430, dtype: float64
牛式===============================
執行第 437
           437
LTC  -0.088453
ZIL  -0.085193
ALGO -0.080319
VET  -0.071754
ICX  -0.065632
ZEC  -0.063473
BAT  -0.059545
QTUM -0.057826
XRP  -0.054462
IOTA -0.034078
NEO  -0.029147
TRX  -0.027242
ATOM -0.024395
ZRX  -0.015439
ETH  -0.013872
ADA  -0.007340
LINK  0.006654
XLM   0.019915
BCH   0.054202
BNB   0.057435
g================================================================         ADA   LINK      XLM     BCH     BNB
0       NaN    NaN      NaN     NaN     NaN
1       NaN    NaN      NaN     NaN     NaN
2       NaN    NaN      NaN     NaN     NaN
3       NaN    NaN      NaN     NaN     NaN
4       NaN    NaN      NaN     NaN     NaN
..      ...    ...      ...     ...     ...
720  1.4039  19.79  0.25677  509.55  327.67
721  1.3327  18.44  0.24383  490.60  310.59
722  1.3497  18.66  0.24550  504.08  316.72
723  1.3356  18.20  0.24484  497.02  316.09
724  1.3478  18.38  0.24587  498.00  321.87

[725 rows x 5 columns]
ADA    -0.004509
LINK   -0.020276
XLM     0.061876
BCH     0.023501
BNB     0.059958
Name: 431, dtype: float64
報酬 0.024109859741153428 %
i= ADA    -0.004509
LINK   -0.020276
XLM     0.061876
BCH     0.023501
BNB     0.059958
Name: 431, dtype: float64
牛式===============================
執行第 438
           438
ZEC  -0.130399
ZIL  -0.119650
ATOM -0.100016
LTC  -0.078776
QTUM -0.074342
XRP  -0.057844
ALGO -0.055137
IOTA -0.045342
VET  -0.039091
ICX  -0.037636
BAT  -0.032913
NEO  -0.032253
TRX  -0.031226
LINK -0.020276
ETH  -0.015555
ZRX  -0.015365
ADA  -0.004509
BCH   0.023501
BNB   0.059958
XLM   0.061876
g================================================================         ZRX     ADA     BCH     BNB      XLM
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.7889  1.4039  509.55  327.67  0.25677
721  0.8190  1.3327  490.60  310.59  0.24383
722  0.8384  1.3497  504.08  316.72  0.24550
723  0.7890  1.3356  497.02  316.09  0.24484
724  0.7950  1.3478  498.00  321.87  0.24587

[725 rows x 5 columns]
ZRX   -0.016945
ADA   -0.019631
BCH    0.040254
BNB    0.000000
XLM    0.024104
Name: 432, dtype: float64
報酬 0.0055563571291945115 %
i= ZRX   -0.016945
ADA   -0.019631
BCH    0.040254
BNB    0.000000
XLM    0.024104
Name: 432, dtype: float64
牛式===============================
執行第 439
           439
ZEC  -0.117534
ZIL  -0.090326
LTC  -0.090270
ALGO -0.084180
ICX  -0.055910
QTUM -0.055864
IOTA -0.054495
XRP  -0.053941
TRX  -0.042467
LINK -0.041156
ATOM -0.034673
NEO  -0.031627
BAT  -0.028597
ETH  -0.021371
ADA  -0.019631
ZRX  -0.016945
BNB   0.000000
VET   0.021605
XLM   0.024104
BCH   0.040254
g================================================================         ZRX     BNB      VET      XLM     BCH
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  0.7889  327.67  0.08348  0.25677  509.55
721  0.8190  310.59  0.07614  0.24383  490.60
722  0.8384  316.72  0.07704  0.24550  504.08
723  0.7890  316.09  0.07591  0.24484  497.02
724  0.7950  321.87  0.07768  0.24587  498.00

[725 rows x 5 columns]
ZRX   -0.068627
BNB   -0.026359
VET   -0.007664
XLM    0.113541
BCH   -0.014013
Name: 433, dtype: float64

報酬 -0.0006243792682388616 %
i= ZRX   -0.068627
BNB   -0.026359
VET   -0.007664
XLM    0.113541
BCH   -0.014013
Name: 433, dtype: float64
牛式===============================
執行第 440
           440
ALGO -0.114936
ICX  -0.088737
ZEC  -0.085771
ATOM -0.084526
ZRX  -0.068627
QTUM -0.051073
XRP  -0.042612
TRX  -0.034341
BNB  -0.026359
IOTA -0.025686
BCH  -0.014013
BAT  -0.013819
ZIL  -0.011500
LINK -0.008182
VET  -0.007664
ETH  -0.005012
ADA  -0.004666
NEO  -0.001251
LTC   0.028029
XLM   0.113541
g================================================================          ETH     ADA     NEO     LTC      XLM
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  2316.15  1.4039  37.005  137.39  0.25677
721  2121.52  1.3327  34.083  132.25  0.24383
722  2146.27  1.3497  34.637  134.42  0.24550
723  2111.19  1.3356  34.057  134.00  0.24484
724  2138.86  1.3478  34.191  134.19  0.24587

[725 rows x 5 columns]
ETH   -0.026934
ADA   -0.044112
NEO   -0.000708
LTC    0.050758
XLM    0.091659
Name: 434, dtype: float64
報酬 0.014132518627410074 %
i= ETH   -0.026934
ADA   -0.044112
NEO   -0.000708
LTC    0.050758
XLM    0.091659
Name: 434, dtype: float64
牛式===============================
執行第 441
           441
ZEC  -0.158912
ALGO -0.125420
ATOM -0.122773
LINK -0.094582
ICX  -0.091515
BCH  -0.070579
BNB  -0.066796
ZRX  -0.058702
QTUM -0.047915
ADA  -0.044112
ZIL  -0.036842
IOTA -0.036563
VET  -0.031618
TRX  -0.030654
BAT  -0.029809
ETH  -0.026934
XRP  -0.023645
NEO  -0.000708
LTC   0.050758
XLM   0.091659
g================================================================          ETH     XRP     NEO     LTC      XLM
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  2316.15  0.6521  37.005  137.39  0.25677
721  2121.52  0.6236  34.083  132.25  0.24383
722  2146.27  0.6372  34.637  134.42  0.24550
723  2111.19  0.6251  34.057  134.00  0.24484
724  2138.86  0.6362  34.191  134.19  0.24587

[725 rows x 5 columns]
ETH    0.035257
XRP    0.021711
NEO    0.064554
LTC    0.074443
XLM    0.129707
Name: 435, dtype: float64
報酬 0.06513435003015533 %
i= ETH    0.035257
XRP    0.021711
NEO    0.064554
LTC    0.074443
XLM    0.129707
Name: 435, dtype: float64
牛式===============================
執行第 442
           442
ATOM -0.093084
ZEC  -0.078400
ZRX  -0.057818
BNB  -0.049840
ALGO -0.040420
ICX  -0.021008
BCH  -0.012622
ADA  -0.007405
ZIL  -0.005359
LINK  0.005581
TRX   0.007541
BAT   0.009381
IOTA  0.015179
XRP   0.021711
QTUM  0.025112
ETH   0.035257
VET   0.035665
NEO   0.064554
LTC   0.074443
XLM   0.129707
g================================================================          ETH      VET     NEO     LTC      XLM
0        NaN      NaN     NaN     NaN      NaN
1        NaN      NaN     NaN     NaN      NaN
2        NaN      NaN     NaN     NaN      NaN
3        NaN      NaN     NaN     NaN      NaN
4        NaN      NaN     NaN     NaN      NaN
..       ...      ...     ...     ...      ...
720  2316.15  0.08348  37.005  137.39  0.25677
721  2121.52  0.07614  34.083  132.25  0.24383
722  2146.27  0.07704  34.637  134.42  0.24550
723  2111.19  0.07591  34.057  134.00  0.24484
724  2138.86  0.07768  34.191  134.19  0.24587

[725 rows x 5 columns]
ETH    0.132458
VET    0.148649
NEO    0.095823
LTC    0.058360
XLM    0.084950
Name: 436, dtype: float64
報酬 0.10404786122068596 %
i= ETH    0.132458
VET    0.148649
NEO    0.095823
LTC    0.058360
XLM    0.084950
Name: 436, dtype: float64
牛式===============================
執行第 443
           443
ZRX  -0.020566
ATOM  0.009817
BNB   0.021326
ICX   0.039477
ZEC   0.047954
ALGO  0.053000
TRX   0.053676
LTC   0.058360
ADA   0.063952
XRP   0.070759
BCH   0.072605
IOTA  0.072838
BAT   0.079749
QTUM  0.079834
ZIL   0.080931
XLM   0.084950
NEO   0.095823
LINK  0.129367
ETH   0.132458
VET   0.148649
g================================================================          XLM     NEO   LINK      ETH      VET
0        NaN     NaN    NaN      NaN      NaN
1        NaN     NaN    NaN      NaN      NaN
2        NaN     NaN    NaN      NaN      NaN
3        NaN     NaN    NaN      NaN      NaN
4        NaN     NaN    NaN      NaN      NaN
..       ...     ...    ...      ...      ...
720  0.25677  37.005  19.79  2316.15  0.08348
721  0.24383  34.083  18.44  2121.52  0.07614
722  0.24550  34.637  18.66  2146.27  0.07704
723  0.24484  34.057  18.20  2111.19  0.07591
724  0.24587  34.191  18.38  2138.86  0.07768

[725 rows x 5 columns]
XLM     0.022233
NEO     0.054848
LINK    0.143932
ETH     0.111853
VET     0.111940
Name: 437, dtype: float64
報酬 0.08896134577800732 %
i= XLM     0.022233
NEO     0.054848
LINK    0.143932
ETH     0.111853
VET     0.111940
Name: 437, dtype: float64
牛式===============================
執行第 444
           444
ZRX  -0.022887
ATOM -0.019923
ICX  -0.016010
ALGO -0.014031
ZEC   0.003808
LTC   0.005913
BNB   0.013232
ADA   0.019815
XLM   0.022233
IOTA  0.024490
BAT   0.033100
TRX   0.036505
QTUM  0.051400
NEO   0.054848
XRP   0.058819
ZIL   0.090055
BCH   0.104837
ETH   0.111853
VET   0.111940
LINK  0.143932
g================================================================          ZIL     BCH      ETH      VET   LINK
0        NaN     NaN      NaN      NaN    NaN
1        NaN     NaN      NaN      NaN    NaN
2        NaN     NaN      NaN      NaN    NaN
3        NaN     NaN      NaN      NaN    NaN
4        NaN     NaN      NaN      NaN    NaN
..       ...     ...      ...      ...    ...
720  0.08133  509.55  2316.15  0.08348  19.79
721  0.07509  490.60  2121.52  0.07614  18.44
722  0.07496  504.08  2146.27  0.07704  18.66
723  0.07299  497.02  2111.19  0.07591  18.20
724  0.07377  498.00  2138.86  0.07768  18.38

[725 rows x 5 columns]
ZIL     0.055887
BCH     0.106023
ETH     0.089570
VET     0.055880
LINK    0.159817
Name: 438, dtype: float64
報酬 0.09343562981818346 %
i= ZIL     0.055887
BCH     0.106023
ETH     0.089570
VET     0.055880
LINK    0.159817
Name: 438, dtype: float64
牛式===============================
執行第 445
           445
ATOM -0.038175
ICX  -0.031169
ZRX  -0.025212
ALGO -0.024406
ZEC  -0.004346
LTC  -0.000702
BNB  -0.000652
ADA   0.005868
BAT   0.023364
TRX   0.043579
QTUM  0.044264
NEO   0.051085
VET   0.055880
ZIL   0.055887
IOTA  0.057269
XRP   0.057760
XLM   0.077155
ETH   0.089570
BCH   0.106023
LINK  0.159817
g================================================================         XRP      XLM      ETH     BCH   LINK
0       NaN      NaN      NaN     NaN    NaN
1       NaN      NaN      NaN     NaN    NaN
2       NaN      NaN      NaN     NaN    NaN
3       NaN      NaN      NaN     NaN    NaN
4       NaN      NaN      NaN     NaN    NaN
..      ...      ...      ...     ...    ...
720  0.6521  0.25677  2316.15  509.55  19.79
721  0.6236  0.24383  2121.52  490.60  18.44
722  0.6372  0.24550  2146.27  504.08  18.66
723  0.6251  0.24484  2111.19  497.02  18.20
724  0.6362  0.24587  2138.86  498.00  18.38

[725 rows x 5 columns]
XRP     0.030745
XLM    -0.023286
ETH     0.070127
BCH     0.085232
LINK    0.113657
Name: 439, dtype: float64
報酬 0.055294908904733764 %
i= XRP     0.030745
XLM    -0.023286
ETH     0.070127
BCH     0.085232
LINK    0.113657
Name: 439, dtype: float64
牛式===============================
執行第 446
           446
ZRX  -0.053915
ZIL  -0.041477
ATOM -0.038168
XLM  -0.023286
ADA  -0.022518
ZEC  -0.020450
ICX  -0.007223
ALGO -0.004285
BAT   0.004204
IOTA  0.005056
BNB   0.007687
QTUM  0.008141
NEO   0.015994
LTC   0.021950
XRP   0.030745
VET   0.033702
TRX   0.042907
ETH   0.070127
BCH   0.085232
LINK  0.113657
g================================================================          VET      TRX      ETH     BCH   LINK
0        NaN      NaN      NaN     NaN    NaN
1        NaN      NaN      NaN     NaN    NaN
2        NaN      NaN      NaN     NaN    NaN
3        NaN      NaN      NaN     NaN    NaN
4        NaN      NaN      NaN     NaN    NaN
..       ...      ...      ...     ...    ...
720  0.08348  0.06432  2316.15  509.55  19.79
721  0.07614  0.06111  2121.52  490.60  18.44
722  0.07704  0.06219  2146.27  504.08  18.66
723  0.07591  0.06139  2111.19  497.02  18.20
724  0.07768  0.06184  2138.86  498.00  18.38

[725 rows x 5 columns]
VET     0.054911
TRX     0.031624
ETH     0.066404
BCH     0.078514
LINK    0.188641
Name: 440, dtype: float64
報酬 0.08401895848577116 %
i= VET     0.054911
TRX     0.031624
ETH     0.066404
BCH     0.078514
LINK    0.188641
Name: 440, dtype: float64
牛式===============================
執行第 447
           447
ZRX  -0.019505
ZIL   0.002186
LTC   0.004350
XLM   0.004582
ADA   0.007626
NEO   0.008084
QTUM  0.012582
ALGO  0.013259
ICX   0.018905
XRP   0.020106
ATOM  0.024288
BAT   0.024484
TRX   0.031624
IOTA  0.039089
ZEC   0.041487
VET   0.054911
ETH   0.066404
BCH   0.078514
BNB   0.078527
LINK  0.188641
g================================================================          VET      ETH     BCH     BNB   LINK
0        NaN      NaN     NaN     NaN    NaN
1        NaN      NaN     NaN     NaN    NaN
2        NaN      NaN     NaN     NaN    NaN
3        NaN      NaN     NaN     NaN    NaN
4        NaN      NaN     NaN     NaN    NaN
..       ...      ...     ...     ...    ...
720  0.08348  2316.15  509.55  327.67  19.79
721  0.07614  2121.52  490.60  310.59  18.44
722  0.07704  2146.27  504.08  316.72  18.66
723  0.07591  2111.19  497.02  316.09  18.20
724  0.07768  2138.86  498.00  321.87  18.38

[725 rows x 5 columns]
VET     0.002026
ETH     0.032189
BCH     0.021742
BNB     0.058843
LINK    0.103608
Name: 441, dtype: float64
報酬 0.043681603411874416 %
i= VET     0.002026
ETH     0.032189
BCH     0.021742
BNB     0.058843
LINK    0.103608
Name: 441, dtype: float64
牛式===============================
執行第 448
           448
NEO  -0.072582
LTC  -0.069064
ALGO -0.043449
QTUM -0.040245
ICX  -0.038895
ZRX  -0.037086
ADA  -0.030881
ZEC  -0.027031
XLM  -0.021864
ATOM -0.017966
IOTA -0.011392
BAT  -0.007900
VET   0.002026
ZIL   0.002155
XRP   0.005173
TRX   0.010853
BCH   0.021742
ETH   0.032189
BNB   0.058843
LINK  0.103608
g================================================================          TRX     BCH      ETH     BNB   LINK
0        NaN     NaN      NaN     NaN    NaN
1        NaN     NaN      NaN     NaN    NaN
2        NaN     NaN      NaN     NaN    NaN
3        NaN     NaN      NaN     NaN    NaN
4        NaN     NaN      NaN     NaN    NaN
..       ...     ...      ...     ...    ...
720  0.06432  509.55  2316.15  327.67  19.79
721  0.06111  490.60  2121.52  310.59  18.44
722  0.06219  504.08  2146.27  316.72  18.66
723  0.06139  497.02  2111.19  316.09  18.20
724  0.06184  498.00  2138.86  321.87  18.38

[725 rows x 5 columns]
TRX    -0.007383
BCH    -0.000186
ETH    -0.061551
BNB    -0.010440
LINK   -0.042642
Name: 442, dtype: float64
報酬 -0.024440648381495754 %
i= TRX    -0.007383
BCH    -0.000186
ETH    -0.061551
BNB    -0.010440
LINK   -0.042642
Name: 442, dtype: float64
牛式===============================
執行第 449
           449
NEO  -0.149153
ZEC  -0.133618
BAT  -0.125783
ALGO -0.125040
VET  -0.124476
ATOM -0.118672
ZRX  -0.116535
QTUM -0.111538
ICX  -0.109743
ADA  -0.108032
ZIL  -0.090256
XLM  -0.084492
ETH  -0.061551
LTC  -0.059519
IOTA -0.048091
XRP  -0.044924
LINK -0.042642
BNB  -0.010440
TRX  -0.007383
BCH  -0.000186
g================================================================         XRP   LINK     BNB      TRX     BCH
0       NaN    NaN     NaN      NaN     NaN
1       NaN    NaN     NaN      NaN     NaN
2       NaN    NaN     NaN      NaN     NaN
3       NaN    NaN     NaN      NaN     NaN
4       NaN    NaN     NaN      NaN     NaN
..      ...    ...     ...      ...     ...
720  0.6521  19.79  327.67  0.06432  509.55
721  0.6236  18.44  310.59  0.06111  490.60
722  0.6372  18.66  316.72  0.06219  504.08
723  0.6251  18.20  316.09  0.06139  497.02
724  0.6362  18.38  321.87  0.06184  498.00

[725 rows x 5 columns]
XRP    -0.048288
LINK   -0.072368
BNB    -0.025139
TRX    -0.005245
BCH    -0.011020
Name: 443, dtype: float64
報酬 -0.03241215914728437 %
i= XRP    -0.048288
LINK   -0.072368
BNB    -0.025139
TRX    -0.005245
BCH    -0.011020
Name: 443, dtype: float64
牛式===============================
執行第 450
           450
ALGO -0.169146
VET  -0.165739
NEO  -0.156925
BAT  -0.146209
ATOM -0.135957
ADA  -0.117135
QTUM -0.112615
ZIL  -0.111505
ZRX  -0.104072
ZEC  -0.101012
ICX  -0.098426
XLM  -0.073494
LINK -0.072368
IOTA -0.060123
ETH  -0.054451
XRP  -0.048288
LTC  -0.044314
BNB  -0.025139
BCH  -0.011020
TRX  -0.005245
g================================================================         XRP     LTC     BNB     BCH      TRX
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.6521  137.39  327.67  509.55  0.06432
721  0.6236  132.25  310.59  490.60  0.06111
722  0.6372  134.42  316.72  504.08  0.06219
723  0.6251  134.00  316.09  497.02  0.06139
724  0.6362  134.19  321.87  498.00  0.06184

[725 rows x 5 columns]
XRP   -0.067369
LTC    0.026464
BNB   -0.070170
BCH   -0.050468
TRX   -0.053585
Name: 444, dtype: float64
報酬 -0.0430255156835337 %
i= XRP   -0.067369
LTC    0.026464
BNB   -0.070170
BCH   -0.050468
TRX   -0.053585
Name: 444, dtype: float64
牛式===============================
執行第 451
           451
NEO  -0.192442
VET  -0.179368
ALGO -0.175114
ATOM -0.166516
QTUM -0.158304
BAT  -0.146119
ICX  -0.142359
ZRX  -0.139615
ADA  -0.136111
LINK -0.127559
IOTA -0.107292
XLM  -0.103879
ZIL  -0.101233
ZEC  -0.091674
ETH  -0.071919
BNB  -0.070170
XRP  -0.067369
TRX  -0.053585
BCH  -0.050468
LTC   0.026464
g================================================================         BNB     XRP      TRX     BCH     LTC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  327.67  0.6521  0.06432  509.55  137.39
721  310.59  0.6236  0.06111  490.60  132.25
722  316.72  0.6372  0.06219  504.08  134.42
723  316.09  0.6251  0.06139  497.02  134.00
724  321.87  0.6362  0.06184  498.00  134.19

[725 rows x 5 columns]
BNB   -0.054395
XRP   -0.053097
TRX   -0.045219
BCH   -0.033385
LTC    0.011531
Name: 445, dtype: float64
報酬 -0.03491301242523779 %
i= BNB   -0.054395
XRP   -0.053097
TRX   -0.045219
BCH   -0.033385
LTC    0.011531
Name: 445, dtype: float64
牛式===============================
執行第 452
           452
ALGO -0.176432
NEO  -0.176190
VET  -0.161572
ICX  -0.142819
BAT  -0.138140
ATOM -0.127740
ZRX  -0.126459
ADA  -0.125529
QTUM -0.118887
IOTA -0.087675
LINK -0.075720
ZEC  -0.073147
ZIL  -0.064380
XLM  -0.063817
BNB  -0.054395
XRP  -0.053097
ETH  -0.047442
TRX  -0.045219
BCH  -0.033385
LTC   0.011531
g================================================================         XRP      ETH      TRX     BCH     LTC
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.6521  2316.15  0.06432  509.55  137.39
721  0.6236  2121.52  0.06111  490.60  132.25
722  0.6372  2146.27  0.06219  504.08  134.42
723  0.6251  2111.19  0.06139  497.02  134.00
724  0.6362  2138.86  0.06184  498.00  134.19

[725 rows x 5 columns]
XRP   -0.032688
ETH    0.009415
TRX   -0.038131
BCH    0.032393
LTC    0.014133
Name: 446, dtype: float64
報酬 -0.0029755266632229605 %
i= XRP   -0.032688
ETH    0.009415
TRX   -0.038131
BCH    0.032393
LTC    0.014133
Name: 446, dtype: float64
牛式===============================
執行第 453
           453
NEO  -0.125373
ALGO -0.108471
BAT  -0.106373
BNB  -0.081508
ATOM -0.078328
IOTA -0.077064
VET  -0.076937
QTUM -0.075472
ICX  -0.067017
ZRX  -0.052956
ADA  -0.046478
TRX  -0.038131
ZEC  -0.034689
XRP  -0.032688
XLM  -0.031065
ZIL  -0.023446
LINK -0.014505
ETH   0.009415
LTC   0.014133
BCH   0.032393
g================================================================          ZIL   LINK      ETH     LTC     BCH
0        NaN    NaN      NaN     NaN     NaN
1        NaN    NaN      NaN     NaN     NaN
2        NaN    NaN      NaN     NaN     NaN
3        NaN    NaN      NaN     NaN     NaN
4        NaN    NaN      NaN     NaN     NaN
..       ...    ...      ...     ...     ...
720  0.08133  19.79  2316.15  137.39  509.55
721  0.07509  18.44  2121.52  132.25  490.60
722  0.07496  18.66  2146.27  134.42  504.08
723  0.07299  18.20  2111.19  134.00  497.02
724  0.07377  18.38  2138.86  134.19  498.00

[725 rows x 5 columns]
ZIL    -0.076344
LINK   -0.096396
ETH    -0.050223
LTC     0.130600
BCH    -0.027403
Name: 447, dtype: float64
報酬 -0.023953223690600222 %
i= ZIL    -0.076344
LINK   -0.096396
ETH    -0.050223
LTC     0.130600
BCH    -0.027403
Name: 447, dtype: float64
牛式===============================
執行第 454
           454
ALGO -0.142857
BAT  -0.140984
QTUM -0.122607
BNB  -0.117180
VET  -0.116199
IOTA -0.112351
ICX  -0.105777
NEO  -0.105545
ZEC  -0.104265
ATOM -0.104126
ADA  -0.100858
LINK -0.096396
TRX  -0.094409
ZRX  -0.089221
XLM  -0.077073
ZIL  -0.076344
XRP  -0.068567
ETH  -0.050223
BCH  -0.027403
LTC   0.130600
g================================================================          ZIL     XRP      ETH     BCH     LTC
0        NaN     NaN      NaN     NaN     NaN
1        NaN     NaN      NaN     NaN     NaN
2        NaN     NaN      NaN     NaN     NaN
3        NaN     NaN      NaN     NaN     NaN
4        NaN     NaN      NaN     NaN     NaN
..       ...     ...      ...     ...     ...
720  0.08133  0.6521  2316.15  509.55  137.39
721  0.07509  0.6236  2121.52  490.60  132.25
722  0.07496  0.6372  2146.27  504.08  134.42
723  0.07299  0.6251  2111.19  497.02  134.00
724  0.07377  0.6362  2138.86  498.00  134.19

[725 rows x 5 columns]
ZIL   -0.016347
XRP   -0.024394
ETH   -0.001133
BCH   -0.089736
LTC    0.060959
Name: 448, dtype: float64
報酬 -0.014130469345630559 %
i= ZIL   -0.016347
XRP   -0.024394
ETH   -0.001133
BCH   -0.089736
LTC    0.060959
Name: 448, dtype: float64
牛式===============================
執行第 455
           455
ALGO -0.154848
VET  -0.131178
BNB  -0.114078
QTUM -0.101010
LINK -0.092576
TRX  -0.091856
IOTA -0.091382
BCH  -0.089736
NEO  -0.075236
BAT  -0.074757
ICX  -0.071197
ATOM -0.068262
ZEC  -0.063380
ADA  -0.052616
XLM  -0.037401
ZRX  -0.032680
XRP  -0.024394
ZIL  -0.016347
ETH  -0.001133
LTC   0.060959
g================================================================         ZRX     XRP      ZIL      ETH     LTC
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  0.7889  0.6521  0.08133  2316.15  137.39
721  0.8190  0.6236  0.07509  2121.52  132.25
722  0.8384  0.6372  0.07496  2146.27  134.42
723  0.7890  0.6251  0.07299  2111.19  134.00
724  0.7950  0.6362  0.07377  2138.86  134.19

[725 rows x 5 columns]
ZRX   -0.058526
XRP   -0.020048
ZIL    0.000000
ETH    0.038891
LTC    0.141471
Name: 449, dtype: float64
報酬 0.020357562308366717 %
i= ZRX   -0.058526
XRP   -0.020048
ZIL    0.000000
ETH    0.038891
LTC    0.141471
Name: 449, dtype: float64
牛式===============================
執行第 456
           456
BCH  -0.098415
QTUM -0.098377
BNB  -0.097790
IOTA -0.090944
TRX  -0.089266
NEO  -0.080314
VET  -0.078289
ICX  -0.077219
LINK -0.072695
ALGO -0.071234
ZRX  -0.058526
ATOM -0.053529
ZEC  -0.049411
XLM  -0.037921
BAT  -0.020613
XRP  -0.020048
ZIL   0.000000
ADA   0.000105
ETH   0.038891
LTC   0.141471
g================================================================         XRP      ZIL     ADA      ETH     LTC
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.6521  0.08133  1.4039  2316.15  137.39
721  0.6236  0.07509  1.3327  2121.52  132.25
722  0.6372  0.07496  1.3497  2146.27  134.42
723  0.6251  0.07299  1.3356  2111.19  134.00
724  0.6362  0.07377  1.3478  2138.86  134.19

[725 rows x 5 columns]
XRP    0.028041
ZIL    0.078330
ADA    0.045445
ETH    0.089074
LTC    0.050878
Name: 450, dtype: float64
報酬 0.05835368129824174 %
i= XRP    0.028041
ZIL    0.078330
ADA    0.045445
ETH    0.089074
LTC    0.050878
Name: 450, dtype: float64
牛式===============================
執行第 457
           457
BCH  -0.047117
VET  -0.036214
IOTA -0.030727
BNB  -0.028080
ZEC  -0.027291
TRX  -0.026552
NEO  -0.025561
ATOM -0.025108
ALGO -0.022844
ICX  -0.012191
LINK -0.009025
QTUM -0.007708
BAT   0.020856
XRP   0.028041
ADA   0.045445
XLM   0.048246
LTC   0.050878
ZRX   0.065644
ZIL   0.078330
ETH   0.089074
g================================================================          XLM     LTC     ZRX      ZIL      ETH
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  0.25677  137.39  0.7889  0.08133  2316.15
721  0.24383  132.25  0.8190  0.07509  2121.52
722  0.24550  134.42  0.8384  0.07496  2146.27
723  0.24484  134.00  0.7890  0.07299  2111.19
724  0.24587  134.19  0.7950  0.07377  2138.86

[725 rows x 5 columns]
XLM    0.078457
LTC    0.053867
ZRX    0.170861
ZIL    0.157924
ETH    0.178831
Name: 451, dtype: float64
報酬 0.12798787863899164 %
i= XLM    0.078457
LTC    0.053867
ZRX    0.170861
ZIL    0.157924
ETH    0.178831
Name: 451, dtype: float64
牛式===============================
執行第 458
           458
BCH  -0.017479
TRX   0.014752
BNB   0.019642
IOTA  0.053564
LTC   0.053867
QTUM  0.054481
ATOM  0.057192
ZEC   0.057944
NEO   0.068480
XLM   0.078457
XRP   0.078480
LINK  0.082814
BAT   0.102536
ALGO  0.112138
VET   0.132253
ICX   0.134549
ZIL   0.157924
ZRX   0.170861
ADA   0.172688
ETH   0.178831
g================================================================         ICX      ZIL     ZRX     ADA      ETH
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.9279  0.08133  0.7889  1.4039  2316.15
721  1.0350  0.07509  0.8190  1.3327  2121.52
722  0.9786  0.07496  0.8384  1.3497  2146.27
723  0.9198  0.07299  0.7890  1.3356  2111.19
724  0.9519  0.07377  0.7950  1.3478  2138.86

[725 rows x 5 columns]
ICX   -0.003562
ZIL    0.034618
ZRX    0.032840
ADA    0.030630
ETH    0.097461
Name: 452, dtype: float64
報酬 0.03839742881672807 %
i= ICX   -0.003562
ZIL    0.034618
ZRX    0.032840
ADA    0.030630
ETH    0.097461
Name: 452, dtype: float64
牛式===============================
執行第 459
           459
BCH  -0.053016
TRX  -0.033424
QTUM -0.029866
BNB  -0.026657
ATOM -0.025728
ZEC  -0.014271
VET  -0.010954
NEO  -0.008365
ALGO -0.003862
ICX  -0.003562
BAT   0.008915
XLM   0.011832
LINK  0.018182
IOTA  0.018599
ADA   0.030630
ZRX   0.032840
ZIL   0.034618
XRP   0.037960
LTC   0.066981
ETH   0.097461
g================================================================         ZRX      ZIL     XRP     LTC      ETH
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.7889  0.08133  0.6521  137.39  2316.15
721  0.8190  0.07509  0.6236  132.25  2121.52
722  0.8384  0.07496  0.6372  134.42  2146.27
723  0.7890  0.07299  0.6251  134.00  2111.19
724  0.7950  0.07377  0.6362  134.19  2138.86

[725 rows x 5 columns]
ZRX    0.115911
ZIL    0.121653
XRP    0.078460
LTC   -0.018658
ETH    0.186381
Name: 453, dtype: float64
報酬 0.09674932683823849 %
i= ZRX    0.115911
ZIL    0.121653
XRP    0.078460
LTC   -0.018658
ETH    0.186381
Name: 453, dtype: float64
牛式===============================
執行第 460
           460
LTC  -0.018658
NEO   0.014988
BNB   0.020863
TRX   0.036386
ATOM  0.044753
BCH   0.052386
QTUM  0.052987
XRP   0.078460
ALGO  0.078479
XLM   0.078613
IOTA  0.078702
BAT   0.081788
ICX   0.096130
ZEC   0.105273
VET   0.106415
ZRX   0.115911
ZIL   0.121653
ADA   0.154980
LINK  0.179963
ETH   0.186381
g================================================================         ZRX      ZIL     ADA   LINK      ETH
0       NaN      NaN     NaN    NaN      NaN
1       NaN      NaN     NaN    NaN      NaN
2       NaN      NaN     NaN    NaN      NaN
3       NaN      NaN     NaN    NaN      NaN
4       NaN      NaN     NaN    NaN      NaN
..      ...      ...     ...    ...      ...
720  0.7889  0.08133  1.4039  19.79  2316.15
721  0.8190  0.07509  1.3327  18.44  2121.52
722  0.8384  0.07496  1.3497  18.66  2146.27
723  0.7890  0.07299  1.3356  18.20  2111.19
724  0.7950  0.07377  1.3478  18.38  2138.86

[725 rows x 5 columns]
ZRX     0.087531
ZIL     0.110029
ADA     0.123999
LINK    0.202117
ETH     0.145376
Name: 454, dtype: float64
報酬 0.13381035424987334 %
i= ZRX     0.087531
ZIL     0.110029
ADA     0.123999
LINK    0.202117
ETH     0.145376
Name: 454, dtype: float64
牛式===============================
執行第 461
           461
TRX   0.014742
LTC   0.026096
IOTA  0.026983
XRP   0.044790
BNB   0.045404
NEO   0.047833
XLM   0.055430
QTUM  0.063135
BAT   0.073049
BCH   0.081176
ZRX   0.087531
ICX   0.088375
ZEC   0.096992
ZIL   0.110029
ALGO  0.114298
ADA   0.123999
ETH   0.145376
ATOM  0.148537
VET   0.192948
LINK  0.202117
g================================================================         ADA      ETH    ATOM      VET   LINK
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  1.4039  2316.15  12.946  0.08348  19.79
721  1.3327  2121.52  11.958  0.07614  18.44
722  1.3497  2146.27  13.182  0.07704  18.66
723  1.3356  2111.19  14.395  0.07591  18.20
724  1.3478  2138.86  14.064  0.07768  18.38

[725 rows x 5 columns]
ADA     0.110657
ETH     0.119438
ATOM    0.160091
VET     0.232996
LINK    0.244742
Name: 455, dtype: float64
報酬 0.17358492495129033 %
i= ADA     0.110657
ETH     0.119438
ATOM    0.160091
VET     0.232996
LINK    0.244742
Name: 455, dtype: float64
牛式===============================
執行第 462
           462
LTC  -0.033782
TRX   0.026882
BNB   0.047142
BCH   0.067186
XRP   0.068362
XLM   0.068374
IOTA  0.078423
BAT   0.088505
ZEC   0.093230
QTUM  0.094381
NEO   0.108306
ADA   0.110657
ETH   0.119438
ICX   0.149407
ZIL   0.154022
ATOM  0.160091
ALGO  0.210813
ZRX   0.225308
VET   0.232996
LINK  0.244742
g================================================================        ATOM    ALGO     ZRX      VET   LINK
0       NaN     NaN     NaN      NaN    NaN
1       NaN     NaN     NaN      NaN    NaN
2       NaN     NaN     NaN      NaN    NaN
3       NaN     NaN     NaN      NaN    NaN
4       NaN     NaN     NaN      NaN    NaN
..      ...     ...     ...      ...    ...
720  12.946  0.9062  0.7889  0.08348  19.79
721  11.958  0.8683  0.8190  0.07614  18.44
722  13.182  0.9059  0.8384  0.07704  18.66
723  14.395  0.8918  0.7890  0.07591  18.20
724  14.064  0.8952  0.7950  0.07768  18.38

[725 rows x 5 columns]
ATOM    0.117673
ALGO    0.121322
ZRX     0.050662
VET     0.167387
LINK    0.164845
Name: 456, dtype: float64
報酬 0.12437794742411294 %
i= ATOM    0.117673
ALGO    0.121322
ZRX     0.050662
VET     0.167387
LINK    0.164845
Name: 456, dtype: float64
牛式===============================
執行第 463
           463
XLM   0.000000
TRX   0.002006
LTC   0.007165
IOTA  0.008427
BNB   0.010834
BCH   0.029412
ZEC   0.039704
XRP   0.041402
BAT   0.044526
ZRX   0.050662
QTUM  0.065251
NEO   0.068078
ZIL   0.072641
ADA   0.086836
ETH   0.111941
ATOM  0.117673
ALGO  0.121322
ICX   0.143354
LINK  0.164845

VET   0.167387
g================================================================        ATOM    ALGO     ICX   LINK      VET
0       NaN     NaN     NaN    NaN      NaN
1       NaN     NaN     NaN    NaN      NaN
2       NaN     NaN     NaN    NaN      NaN
3       NaN     NaN     NaN    NaN      NaN
4       NaN     NaN     NaN    NaN      NaN
..      ...     ...     ...    ...      ...
720  12.946  0.9062  0.9279  19.79  0.08348
721  11.958  0.8683  1.0350  18.44  0.07614
722  13.182  0.9059  0.9786  18.66  0.07704
723  14.395  0.8918  0.9198  18.20  0.07591
724  14.064  0.8952  0.9519  18.38  0.07768

[725 rows x 5 columns]
ATOM    0.031352
ALGO   -0.038670
ICX     0.011360
LINK    0.020559
VET    -0.047491
Name: 457, dtype: float64
報酬 -0.004577832478313515 %
i= ATOM    0.031352
ALGO   -0.038670
ICX     0.011360
LINK    0.020559
VET    -0.047491
Name: 457, dtype: float64
牛式===============================
執行第 464
           464
IOTA -0.071402
ZIL  -0.063322
TRX  -0.048202
VET  -0.047491
BNB  -0.047128
ZRX  -0.044309
BAT  -0.041605
ADA  -0.040620
XLM  -0.038760
ALGO -0.038670
LTC  -0.026935
QTUM -0.019314
NEO  -0.017693
XRP  -0.014585
BCH   0.009866
ICX   0.011360
ETH   0.014880
LINK  0.020559
ZEC   0.022428
ATOM  0.031352
g================================================================         ICX      ETH   LINK     ZEC    ATOM
0       NaN      NaN    NaN     NaN     NaN
1       NaN      NaN    NaN     NaN     NaN
2       NaN      NaN    NaN     NaN     NaN
3       NaN      NaN    NaN     NaN     NaN
4       NaN      NaN    NaN     NaN     NaN
..      ...      ...    ...     ...     ...
720  0.9279  2316.15  19.79  118.51  12.946
721  1.0350  2121.52  18.44  109.38  11.958
722  0.9786  2146.27  18.66  110.99  13.182
723  0.9198  2111.19  18.20  108.15  14.395
724  0.9519  2138.86  18.38  110.82  14.064

[725 rows x 5 columns]
ICX     0.114090
ETH     0.094388
LINK    0.094388
ZEC     0.148788
ATOM    0.127922
Name: 458, dtype: float64
報酬 0.11591513596304917 %
i= ICX     0.114090
ETH     0.094388
LINK    0.094388
ZEC     0.148788
ATOM    0.127922
Name: 458, dtype: float64
牛式===============================
執行第 465
           465
LTC  -0.017695
IOTA -0.002720
BNB   0.016216
BCH   0.020645
TRX   0.021311
XLM   0.036464
ADA   0.049763
BAT   0.053015
XRP   0.066600
QTUM  0.074397
NEO   0.080240
ALGO  0.088406
ZIL   0.092822
LINK  0.094388
ETH   0.094388
ZRX   0.107133
ICX   0.114090
ATOM  0.127922
VET   0.137340
ZEC   0.148788
g================================================================         ZRX     ICX    ATOM      VET     ZEC
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.7889  0.9279  12.946  0.08348  118.51
721  0.8190  1.0350  11.958  0.07614  109.38
722  0.8384  0.9786  13.182  0.07704  110.99
723  0.7890  0.9198  14.395  0.07591  108.15
724  0.7950  0.9519  14.064  0.07768  110.82

[725 rows x 5 columns]
ZRX     0.020174
ICX     0.002847
ATOM    0.049075
VET     0.011506
ZEC     0.054638
Name: 459, dtype: float64
報酬 0.027648125328298124 %
i= ZRX     0.020174
ICX     0.002847
ATOM    0.049075
VET     0.011506
ZEC     0.054638
Name: 459, dtype: float64
牛式===============================
執行第 466
           466
LTC  -0.074984
BCH  -0.057866
IOTA -0.054156
ADA  -0.023928
BNB  -0.016209
LINK -0.014151
TRX  -0.009073
BAT  -0.009073
XLM  -0.006871
ALGO -0.001875
ICX   0.002847
QTUM  0.006413
VET   0.011506
ETH   0.013486
NEO   0.015674
ZRX   0.020174
ZIL   0.045148
ATOM  0.049075
ZEC   0.054638
XRP   0.056751
g================================================================         ZRX      ZIL    ATOM     ZEC     XRP
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.7889  0.08133  12.946  118.51  0.6521
721  0.8190  0.07509  11.958  109.38  0.6236
722  0.8384  0.07496  13.182  110.99  0.6372
723  0.7890  0.07299  14.395  108.15  0.6251
724  0.7950  0.07377  14.064  110.82  0.6362

[725 rows x 5 columns]
ZRX     0.014403
ZIL     0.029427
ATOM   -0.032867
ZEC     0.047635
XRP     0.077031
Name: 460, dtype: float64
報酬 0.02712581645092409 %
i= ZRX     0.014403
ZIL     0.029427
ATOM   -0.032867
ZEC     0.047635
XRP     0.077031
Name: 460, dtype: float64
牛式===============================
執行第 467
           467
BCH  -0.088757
LTC  -0.044454
ADA  -0.043995
ATOM -0.032867
LINK -0.029624
ALGO -0.015367
BNB  -0.015308
ICX  -0.007567
QTUM -0.004529
NEO  -0.004097
IOTA -0.003583
BAT  -0.001547
VET   0.000816
XLM   0.006031
ETH   0.008508
ZRX   0.014403
TRX   0.022195
ZIL   0.029427
ZEC   0.047635
XRP   0.077031
g================================================================         ZRX      TRX      ZIL     ZEC     XRP
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.7889  0.06432  0.08133  118.51  0.6521
721  0.8190  0.06111  0.07509  109.38  0.6236
722  0.8384  0.06219  0.07496  110.99  0.6372
723  0.7890  0.06139  0.07299  108.15  0.6251
724  0.7950  0.06184  0.07377  110.82  0.6362

[725 rows x 5 columns]
ZRX   -0.042750
TRX    0.026581
ZIL    0.083045
ZEC    0.091709
XRP    0.134476
Name: 461, dtype: float64
報酬 0.05861204285769335 %
i= ZRX   -0.042750
TRX    0.026581
ZIL    0.083045
ZEC    0.091709
XRP    0.134476
Name: 461, dtype: float64
牛式===============================
執行第 468
           468
ALGO -0.061959
ZRX  -0.042750
LTC  -0.032819
LINK -0.030722
BCH  -0.029846
VET  -0.021409
BAT  -0.020327
ADA  -0.020002
ICX  -0.015621
BNB  -0.008508
IOTA -0.004717
ATOM -0.000590
NEO   0.009368
ETH   0.022116
TRX   0.026581
QTUM  0.033400
XLM   0.034383
ZIL   0.083045
ZEC   0.091709
XRP   0.134476
g================================================================       QTUM      XLM      ZIL     ZEC     XRP
0      NaN      NaN      NaN     NaN     NaN
1      NaN      NaN      NaN     NaN     NaN
2      NaN      NaN      NaN     NaN     NaN
3      NaN      NaN      NaN     NaN     NaN
4      NaN      NaN      NaN     NaN     NaN
..     ...      ...      ...     ...     ...
720  7.079  0.25677  0.08133  118.51  0.6521
721  6.504  0.24383  0.07509  109.38  0.6236
722  6.776  0.24550  0.07496  110.99  0.6372
723  6.639  0.24484  0.07299  108.15  0.6251
724  6.694  0.24587  0.07377  110.82  0.6362

[725 rows x 5 columns]
QTUM    0.071463
XLM     0.075880
ZIL     0.130994
ZEC     0.134080
XRP     0.182127
Name: 462, dtype: float64
報酬 0.11890888466439628 %
i= QTUM    0.071463
XLM     0.075880
ZIL     0.130994
ZEC     0.134080
XRP     0.182127
Name: 462, dtype: float64
牛式===============================
執行第 469
           469
LTC  -0.050442
ALGO -0.013659
BCH  -0.006267
ICX   0.004982
BNB   0.020364
BAT   0.028084
ADA   0.032638
ETH   0.040653
LINK  0.045348
NEO   0.049574
ZRX   0.049863
ATOM  0.050258
IOTA  0.056506
TRX   0.059648
QTUM  0.071463
XLM   0.075880
VET   0.088624
ZIL   0.130994
ZEC   0.134080
XRP   0.182127
g================================================================          XLM      VET      ZIL     ZEC     XRP
0        NaN      NaN      NaN     NaN     NaN
1        NaN      NaN      NaN     NaN     NaN
2        NaN      NaN      NaN     NaN     NaN
3        NaN      NaN      NaN     NaN     NaN
4        NaN      NaN      NaN     NaN     NaN
..       ...      ...      ...     ...     ...
720  0.25677  0.08348  0.08133  118.51  0.6521
721  0.24383  0.07614  0.07509  109.38  0.6236
722  0.24550  0.07704  0.07496  110.99  0.6372
723  0.24484  0.07591  0.07299  108.15  0.6251
724  0.24587  0.07768  0.07377  110.82  0.6362

[725 rows x 5 columns]
XLM    0.037717
VET    0.105822
ZIL    0.131565
ZEC    0.004769
XRP    0.151617
Name: 463, dtype: float64
報酬 0.08629803199387043 %
i= XLM    0.037717
VET    0.105822
ZIL    0.131565
ZEC    0.004769
XRP    0.151617
Name: 463, dtype: float64
牛式===============================
執行第 470
           470
BCH  -0.053079
ICX  -0.048767
LTC  -0.046861
ZEC   0.004769
ALGO  0.004887
ZRX   0.012493
BNB   0.012996
ATOM  0.014107
ADA   0.018159
NEO   0.018401
BAT   0.021450
ETH   0.034861
IOTA  0.035427
XLM   0.037717
QTUM  0.058592
TRX   0.075965
LINK  0.092667
VET   0.105822
ZIL   0.131565
XRP   0.151617
g================================================================          TRX   LINK      VET      ZIL     XRP
0        NaN    NaN      NaN      NaN     NaN
1        NaN    NaN      NaN      NaN     NaN
2        NaN    NaN      NaN      NaN     NaN
3        NaN    NaN      NaN      NaN     NaN
4        NaN    NaN      NaN      NaN     NaN
..       ...    ...      ...      ...     ...
720  0.06432  19.79  0.08348  0.08133  0.6521
721  0.06111  18.44  0.07614  0.07509  0.6236
722  0.06219  18.66  0.07704  0.07496  0.6372
723  0.06139  18.20  0.07591  0.07299  0.6251
724  0.06184  18.38  0.07768  0.07377  0.6362

[725 rows x 5 columns]
TRX     0.014961
LINK    0.058275
VET    -0.025489
ZIL     0.041481
XRP     0.142271
Name: 464, dtype: float64
報酬 0.04629984073515518 %
i= TRX     0.014961
LINK    0.058275
VET    -0.025489
ZIL     0.041481
XRP     0.142271
Name: 464, dtype: float64
牛式===============================
執行第 471
           471
ICX  -0.075401
LTC  -0.058760
ZRX  -0.055886
ALGO -0.054863
ZEC  -0.053295
BCH  -0.050529
BAT  -0.030602
VET  -0.025489
ATOM -0.022069
IOTA -0.012076
ETH  -0.011356
BNB  -0.004255
ADA  -0.003950
NEO   0.004248
TRX   0.014961
XLM   0.019168
ZIL   0.041481
LINK  0.058275
QTUM  0.074499
XRP   0.142271
g================================================================          XLM      ZIL   LINK   QTUM     XRP
0        NaN      NaN    NaN    NaN     NaN
1        NaN      NaN    NaN    NaN     NaN
2        NaN      NaN    NaN    NaN     NaN
3        NaN      NaN    NaN    NaN     NaN
4        NaN      NaN    NaN    NaN     NaN
..       ...      ...    ...    ...     ...
720  0.25677  0.08133  19.79  7.079  0.6521
721  0.24383  0.07509  18.44  6.504  0.6236
722  0.24550  0.07496  18.66  6.776  0.6372
723  0.24484  0.07299  18.20  6.639  0.6251
724  0.24587  0.07377  18.38  6.694  0.6362

[725 rows x 5 columns]
XLM     0.094885
ZIL     0.116683
LINK    0.124402
QTUM    0.156863
XRP     0.230178
Name: 465, dtype: float64
報酬 0.14460224832216512 %
i= XLM     0.094885
ZIL     0.116683
LINK    0.124402
QTUM    0.156863
XRP     0.230178
Name: 465, dtype: float64
牛式===============================
執行第 472
           472
ZEC  -0.010330
ZRX   0.002138
LTC   0.017783
BCH   0.019715
ICX   0.027825
BAT   0.030010
BNB   0.036891
ATOM  0.044202
TRX   0.046576
NEO   0.048718
IOTA  0.057654
ALGO  0.069899
VET   0.070737
XLM   0.094885
ETH   0.107450
ZIL   0.116683
LINK  0.124402
ADA   0.137954
QTUM  0.156863
XRP   0.230178
g================================================================          ZIL   LINK     ADA   QTUM     XRP
0        NaN    NaN     NaN    NaN     NaN
1        NaN    NaN     NaN    NaN     NaN
2        NaN    NaN     NaN    NaN     NaN
3        NaN    NaN     NaN    NaN     NaN
4        NaN    NaN     NaN    NaN     NaN
..       ...    ...     ...    ...     ...
720  0.08133  19.79  1.4039  7.079  0.6521
721  0.07509  18.44  1.3327  6.504  0.6236
722  0.07496  18.66  1.3497  6.776  0.6372
723  0.07299  18.20  1.3356  6.639  0.6251
724  0.07377  18.38  1.3478  6.694  0.6362

[725 rows x 5 columns]
ZIL     0.189067
LINK    0.274752
ADA     0.327800
QTUM    0.361982
XRP     0.719999
Name: 466, dtype: float64
報酬 0.37472008205180135 %
i= ZIL     0.189067
LINK    0.274752
ADA     0.327800
QTUM    0.361982
XRP     0.719999
Name: 466, dtype: float64
牛式===============================
執行第 473
           473
LTC  -0.028182
BNB   0.102675
ZRX   0.159800
ZIL   0.189067
ZEC   0.189565
ICX   0.190029
ATOM  0.191635
NEO   0.196017
TRX   0.206475
BAT   0.208678
ETH   0.232045
ALGO  0.237612
BCH   0.267678
LINK  0.274752
IOTA  0.305234
VET   0.306912
ADA   0.327800
QTUM  0.361982
XLM   0.363682
XRP   0.719999
g================================================================          VET     ADA   QTUM      XLM     XRP
0        NaN     NaN    NaN      NaN     NaN
1        NaN     NaN    NaN      NaN     NaN
2        NaN     NaN    NaN      NaN     NaN
3        NaN     NaN    NaN      NaN     NaN
4        NaN     NaN    NaN      NaN     NaN
..       ...     ...    ...      ...     ...
720  0.08348  1.4039  7.079  0.25677  0.6521
721  0.07614  1.3327  6.504  0.24383  0.6236
722  0.07704  1.3497  6.776  0.24550  0.6372
723  0.07591  1.3356  6.639  0.24484  0.6251
724  0.07768  1.3478  6.694  0.24587  0.6362

[725 rows x 5 columns]
VET     0.227064
ADA     0.401945
QTUM    0.234443
XLM     0.264346
XRP     0.548814
Name: 467, dtype: float64
報酬 0.3353222496759394 %

i= VET     0.227064
ADA     0.401945
QTUM    0.234443
XLM     0.264346
XRP     0.548814
Name: 467, dtype: float64
牛式===============================
執行第 474
           474
LTC  -0.048791
ZIL   0.031492
ZEC   0.066026
ZRX   0.069142
BNB   0.074008
ATOM  0.078678
NEO   0.092429
ALGO  0.099262
ICX   0.101162
BAT   0.114372
TRX   0.127109
LINK  0.148970
BCH   0.157627
ETH   0.217158
VET   0.227064
QTUM  0.234443
IOTA  0.259874
XLM   0.264346
ADA   0.401945
XRP   0.548814
g================================================================       QTUM    IOTA      XLM     ADA     XRP
0      NaN     NaN      NaN     NaN     NaN
1      NaN     NaN      NaN     NaN     NaN
2      NaN     NaN      NaN     NaN     NaN
3      NaN     NaN      NaN     NaN     NaN
4      NaN     NaN      NaN     NaN     NaN
..     ...     ...      ...     ...     ...
720  7.079  0.8896  0.25677  1.4039  0.6521
721  6.504  0.8165  0.24383  1.3327  0.6236
722  6.776  0.8180  0.24550  1.3497  0.6372
723  6.639  0.7913  0.24484  1.3356  0.6251
724  6.694  0.8404  0.24587  1.3478  0.6362

[725 rows x 5 columns]
QTUM    0.267695
IOTA    0.361582
XLM     0.527229
ADA     0.410797
XRP     1.037765
Name: 468, dtype: float64
報酬 0.5210135262174408 %
i= QTUM    0.267695
IOTA    0.361582
XLM     0.527229
ADA     0.410797
XRP     1.037765
Name: 468, dtype: float64
牛式===============================
執行第 475
           475
LTC  -0.010897
ZIL   0.068182
BNB   0.084734
ATOM  0.099489
LINK  0.141361
ZRX   0.142745
NEO   0.182370
ZEC   0.189015
TRX   0.199093
ICX   0.203525
ALGO  0.224125
BAT   0.243902
ETH   0.262748
BCH   0.266090
QTUM  0.267695
VET   0.298177
IOTA  0.361582
ADA   0.410797
XLM   0.527229
XRP   1.037765
g================================================================          VET    IOTA     ADA      XLM     XRP
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.08348  0.8896  1.4039  0.25677  0.6521
721  0.07614  0.8165  1.3327  0.24383  0.6236
722  0.07704  0.8180  1.3497  0.24550  0.6372
723  0.07591  0.7913  1.3356  0.24484  0.6251
724  0.07768  0.8404  1.3478  0.24587  0.6362

[725 rows x 5 columns]
VET     0.370808
IOTA    0.493390
ADA     0.566976
XLM     1.341463
XRP     1.358355
Name: 469, dtype: float64
報酬 0.8261986417942095 %
i= VET     0.370808
IOTA    0.493390
ADA     0.566976
XLM     1.341463
XRP     1.358355
Name: 469, dtype: float64
牛式===============================
執行第 476
           476
LTC  -0.016693
LINK  0.153392
ZIL   0.163603
ATOM  0.166732
BNB   0.209195
ETH   0.264372
ZRX   0.274198
NEO   0.303792
BAT   0.306000
TRX   0.313037
ALGO  0.337074
ICX   0.340150
VET   0.370808
ZEC   0.371460
BCH   0.412364
QTUM  0.431628
IOTA  0.493390
ADA   0.566976
XLM   1.341463
XRP   1.358355
g================================================================       QTUM    IOTA     ADA      XLM     XRP
0      NaN     NaN     NaN      NaN     NaN
1      NaN     NaN     NaN      NaN     NaN
2      NaN     NaN     NaN      NaN     NaN
3      NaN     NaN     NaN      NaN     NaN
4      NaN     NaN     NaN      NaN     NaN
..     ...     ...     ...      ...     ...
720  7.079  0.8896  1.4039  0.25677  0.6521
721  6.504  0.8165  1.3327  0.24383  0.6236
722  6.776  0.8180  1.3497  0.24550  0.6372
723  6.639  0.7913  1.3356  0.24484  0.6251
724  6.694  0.8404  1.3478  0.24587  0.6362

[725 rows x 5 columns]
QTUM    0.300444
IOTA    0.403785
ADA     0.465345
XLM     1.307582
XRP     1.084517
Name: 470, dtype: float64
報酬 0.7123347633754198 %
i= QTUM    0.300444
IOTA    0.403785
ADA     0.465345
XLM     1.307582
XRP     1.084517
Name: 470, dtype: float64
牛式===============================
執行第 477
           477
LTC   0.009569
LINK  0.045521
BNB   0.114316
ATOM  0.161107
ETH   0.208849
ZRX   0.217320
NEO   0.226190
ZEC   0.255012
BCH   0.274546
TRX   0.283165
ALGO  0.294007
QTUM  0.300444
BAT   0.307026
ICX   0.364372
ZIL   0.368421
IOTA  0.403785
VET   0.443778
ADA   0.465345
XRP   1.084517
XLM   1.307582
g================================================================        IOTA      VET     ADA     XRP      XLM
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.8896  0.08348  1.4039  0.6521  0.25677
721  0.8165  0.07614  1.3327  0.6236  0.24383
722  0.8180  0.07704  1.3497  0.6372  0.24550
723  0.7913  0.07591  1.3356  0.6251  0.24484
724  0.8404  0.07768  1.3478  0.6362  0.24587

[725 rows x 5 columns]
IOTA    0.143233
VET     0.212715
ADA     0.169891
XRP     0.627721
XLM     0.892011
Name: 471, dtype: float64
報酬 0.40911410690840944 %
i= IOTA    0.143233
VET     0.212715
ADA     0.169891
XRP     0.627721
XLM     0.892011
Name: 471, dtype: float64
牛式===============================
執行第 478
           478
LINK -0.108511
BNB  -0.025216
LTC   0.002496
ATOM  0.011200
ETH   0.017994
BCH   0.041398
NEO   0.043780
ALGO  0.057604
QTUM  0.069068
ZRX   0.086400
BAT   0.109136
ZEC   0.109442
ICX   0.113536
TRX   0.117535
IOTA  0.143233
ZIL   0.146732
ADA   0.169891
VET   0.212715
XRP   0.627721
XLM   0.892011
g================================================================          ZIL     ADA      VET     XRP      XLM
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  0.08133  1.4039  0.08348  0.6521  0.25677
721  0.07509  1.3327  0.07614  0.6236  0.24383
722  0.07496  1.3497  0.07704  0.6372  0.24550
723  0.07299  1.3356  0.07591  0.6251  0.24484
724  0.07377  1.3478  0.07768  0.6362  0.24587

[725 rows x 5 columns]
ZIL    0.039224
ADA    0.059810
VET    0.005822
XRP    0.209356
XLM    0.890283
Name: 472, dtype: float64
報酬 0.24089904500228712 %
i= ZIL    0.039224
ADA    0.059810
VET    0.005822
XRP    0.209356
XLM    0.890283
Name: 472, dtype: float64
牛式===============================
執行第 479
           479
LINK -0.191586
BCH  -0.129042
ATOM -0.094668
NEO  -0.066932
BNB  -0.066885
ETH  -0.060504
ALGO -0.053594
ZEC  -0.043586
IOTA -0.043159
TRX  -0.038940
BAT  -0.038462
QTUM -0.034521
ZRX  -0.033365
ICX  -0.022671
LTC  -0.018182
VET   0.005822
ZIL   0.039224
ADA   0.059810
XRP   0.209356
XLM   0.890283
g================================================================          VET      ZIL     ADA     XRP      XLM
0        NaN      NaN     NaN     NaN      NaN
1        NaN      NaN     NaN     NaN      NaN
2        NaN      NaN     NaN     NaN      NaN
3        NaN      NaN     NaN     NaN      NaN
4        NaN      NaN     NaN     NaN      NaN
..       ...      ...     ...     ...      ...
720  0.08348  0.08133  1.4039  0.6521  0.25677
721  0.07614  0.07509  1.3327  0.6236  0.24383
722  0.07704  0.07496  1.3497  0.6372  0.24550
723  0.07591  0.07299  1.3356  0.6251  0.24484
724  0.07768  0.07377  1.3478  0.6362  0.24587

[725 rows x 5 columns]
VET    0.103523
ZIL    0.182301
ADA    0.132399
XRP    0.403453
XLM    0.918058
Name: 473, dtype: float64
報酬 0.34794683649778835 %
i= VET    0.103523
ZIL    0.182301
ADA    0.132399
XRP    0.403453
XLM    0.918058
Name: 473, dtype: float64
牛式===============================
執行第 480
           480
LINK -0.097241
BCH  -0.044777
ETH  -0.040248
BNB  -0.029627
LTC  -0.012357
ATOM -0.009847
NEO   0.020658
BAT   0.042234
ZRX   0.044540
ALGO  0.048674
ICX   0.049408
QTUM  0.050410
TRX   0.060564
IOTA  0.063323
ZEC   0.095086
VET   0.103523
ADA   0.132399
ZIL   0.182301
XRP   0.403453
XLM   0.918058
g================================================================          VET     ADA      ZIL     XRP      XLM
0        NaN     NaN      NaN     NaN      NaN
1        NaN     NaN      NaN     NaN      NaN
2        NaN     NaN      NaN     NaN      NaN
3        NaN     NaN      NaN     NaN      NaN
4        NaN     NaN      NaN     NaN      NaN
..       ...     ...      ...     ...      ...
720  0.08348  1.4039  0.08133  0.6521  0.25677
721  0.07614  1.3327  0.07509  0.6236  0.24383
722  0.07704  1.3497  0.07496  0.6372  0.24550
723  0.07591  1.3356  0.07299  0.6251  0.24484
724  0.07768  1.3478  0.07377  0.6362  0.24587

[725 rows x 5 columns]
VET   -0.055847
ADA    0.077441
ZIL    0.194763
XRP   -0.017510
XLM    0.469074
Name: 474, dtype: float64
報酬 0.13358422969274114 %
i= VET   -0.055847
ADA    0.077441
ZIL    0.194763
XRP   -0.017510
XLM    0.469074
Name: 474, dtype: float64
牛式===============================
執行第 481
           481
LINK -0.124509
BCH  -0.117784
BAT  -0.074902
NEO  -0.074136
ICX  -0.067735
ATOM -0.066403
ALGO -0.057160
VET  -0.055847
ZEC  -0.054877
ETH  -0.054381
ZRX  -0.052523
IOTA -0.051729
TRX  -0.032136
BNB  -0.028405
QTUM -0.021832
XRP  -0.017510
LTC  -0.011017
ADA   0.077441
ZIL   0.194763
XLM   0.469074
g================================================================         XRP     LTC     ADA      ZIL      XLM
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.6521  137.39  1.4039  0.08133  0.25677
721  0.6236  132.25  1.3327  0.07509  0.24383
722  0.6372  134.42  1.3497  0.07496  0.24550
723  0.6251  134.00  1.3356  0.07299  0.24484
724  0.6362  134.19  1.3478  0.07377  0.24587

[725 rows x 5 columns]
XRP   -0.040474
LTC   -0.045116
ADA    0.030731
ZIL    0.158373
XLM    0.036254
Name: 475, dtype: float64
報酬 0.027953590509969796 %
i= XRP   -0.040474
LTC   -0.045116
ADA    0.030731
ZIL    0.158373
XLM    0.036254
Name: 475, dtype: float64
牛式===============================
執行第 482
           482
NEO  -0.092861
ZEC  -0.089053
LINK -0.088235
BCH  -0.087084
IOTA -0.082791
ALGO -0.079743
TRX  -0.079374
ZRX  -0.076393
BNB  -0.071618
BAT  -0.066998
ATOM -0.064484
ICX  -0.055663
QTUM -0.047433
LTC  -0.045116
XRP  -0.040474
VET  -0.010035
ETH   0.018610
ADA   0.030731
XLM   0.036254
ZIL   0.158373
g================================================================          VET      ETH     ADA      XLM      ZIL
0        NaN      NaN     NaN      NaN      NaN
1        NaN      NaN     NaN      NaN      NaN
2        NaN      NaN     NaN      NaN      NaN
3        NaN      NaN     NaN      NaN      NaN
4        NaN      NaN     NaN      NaN      NaN
..       ...      ...     ...      ...      ...
720  0.08348  2316.15  1.4039  0.25677  0.08133
721  0.07614  2121.52  1.3327  0.24383  0.07509
722  0.07704  2146.27  1.3497  0.24550  0.07496
723  0.07591  2111.19  1.3356  0.24484  0.07299
724  0.07768  2138.86  1.3478  0.24587  0.07377

[725 rows x 5 columns]
VET   -0.114354
ETH    0.027679
ADA    0.003931
XLM   -0.052822
ZIL   -0.032918
Name: 476, dtype: float64
報酬 -0.03369670134879756 %
i= VET   -0.114354
ETH    0.027679
ADA    0.003931
XLM   -0.052822
ZIL   -0.032918
Name: 476, dtype: float64
牛式===============================
執行第 483
           483
VET  -0.114354
ICX  -0.113396
ATOM -0.111374
NEO  -0.110852
ALGO -0.103699
ZRX  -0.100405
TRX  -0.086759
BAT  -0.084924
IOTA -0.083708
BCH  -0.083604
QTUM -0.071770
LTC  -0.065899
LINK -0.063904
XLM  -0.052822
ZEC  -0.045879
BNB  -0.037073
XRP  -0.034523
ZIL  -0.032918
ADA   0.003931
ETH   0.027679
g================================================================         BNB     XRP      ZIL     ADA      ETH
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  327.67  0.6521  0.08133  1.4039  2316.15
721  310.59  0.6236  0.07509  1.3327  2121.52
722  316.72  0.6372  0.07496  1.3497  2146.27
723  316.09  0.6251  0.07299  1.3356  2111.19
724  321.87  0.6362  0.07377  1.3478  2138.86

[725 rows x 5 columns]
BNB    0.073707
XRP    0.174439
ZIL    0.207445
ADA    0.146231
ETH    0.151590
Name: 477, dtype: float64
報酬 0.15068233074815546 %
i= BNB    0.073707
XRP    0.174439
ZIL    0.207445
ADA    0.146231
ETH    0.151590
Name: 477, dtype: float64
牛式===============================
執行第 484
           484
LTC  -0.052286
ATOM  0.036418
ZRX   0.046883
NEO   0.050099
TRX   0.062628
BNB   0.073707
BAT   0.078807
BCH   0.086997
ICX   0.087571
ZEC   0.093086
QTUM  0.104637
XLM   0.104730
LINK  0.112967
VET   0.122502
ALGO  0.134175
IOTA  0.135153
ADA   0.146231
ETH   0.151590
XRP   0.174439
ZIL   0.207445
g================================================================        IOTA     ADA      ETH     XRP      ZIL
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  0.8896  1.4039  2316.15  0.6521  0.08133
721  0.8165  1.3327  2121.52  0.6236  0.07509
722  0.8180  1.3497  2146.27  0.6372  0.07496
723  0.7913  1.3356  2111.19  0.6251  0.07299
724  0.8404  1.3478  2138.86  0.6362  0.07377

[725 rows x 5 columns]
IOTA    0.116123
ADA     0.158991
ETH     0.187552
XRP     0.124320
ZIL     0.363636
Name: 478, dtype: float64
報酬 0.19012449785126453 %
i= IOTA    0.116123
ADA     0.158991
ETH     0.187552
XRP     0.124320
ZIL     0.363636
Name: 478, dtype: float64
牛式===============================
執行第 485
           485
XLM  -0.106831
LTC  -0.035162
ATOM  0.026468
ZRX   0.069282
TRX   0.077971
BNB   0.078707
BAT   0.080000
ZEC   0.088125
BCH   0.099928
NEO   0.103212
QTUM  0.106113
ICX   0.109934
IOTA  0.116123
LINK  0.118495
XRP   0.124320
ALGO  0.133578
ADA   0.158991
ETH   0.187552
VET   0.198884
ZIL   0.363636
g================================================================        ALGO     ADA      ETH      VET      ZIL
0       NaN     NaN      NaN      NaN      NaN
1       NaN     NaN      NaN      NaN      NaN
2       NaN     NaN      NaN      NaN      NaN
3       NaN     NaN      NaN      NaN      NaN
4       NaN     NaN      NaN      NaN      NaN
..      ...     ...      ...      ...      ...
720  0.9062  1.4039  2316.15  0.08348  0.08133
721  0.8683  1.3327  2121.52  0.07614  0.07509
722  0.9059  1.3497  2146.27  0.07704  0.07496
723  0.8918  1.3356  2111.19  0.07591  0.07299
724  0.8952  1.3478  2138.86  0.07768  0.07377

[725 rows x 5 columns]
ALGO    0.042574
ADA    -0.104245
ETH     0.055363
VET     0.021368
ZIL     0.105165
Name: 479, dtype: float64
報酬 0.024044952315036693 %
i= ALGO    0.042574
ADA    -0.104245
ETH     0.055363
VET     0.021368
ZIL     0.105165
Name: 479, dtype: float64
牛式===============================
執行第 486
           486
XLM  -0.191896
XRP  -0.115903
ADA  -0.104245
ZEC  -0.083776
ATOM -0.070166
ZRX  -0.053722
IOTA -0.051592
QTUM -0.035342
TRX  -0.032819
LINK -0.031322
ICX  -0.021334
NEO  -0.013797
LTC  -0.013692
BNB  -0.004460
BAT  -0.004357
BCH   0.013403
VET   0.021368
ALGO  0.042574
ETH   0.055363
ZIL   0.105165
g================================================================         BCH      VET    ALGO      ETH      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  509.55  0.08348  0.9062  2316.15  0.08133
721  490.60  0.07614  0.8683  2121.52  0.07509
722  504.08  0.07704  0.9059  2146.27  0.07496
723  497.02  0.07591  0.8918  2111.19  0.07299
724  498.00  0.07768  0.8952  2138.86  0.07377

[725 rows x 5 columns]
BCH     0.016483
VET     0.156302
ALGO    0.086833
ETH     0.036868
ZIL     0.166096
Name: 480, dtype: float64
報酬 0.09251616828592021 %
i= BCH     0.016483
VET     0.156302
ALGO    0.086833
ETH     0.036868
ZIL     0.166096
Name: 480, dtype: float64

牛式===============================
執行第 487
           487
XLM  -0.114507
LTC  -0.048039
ZEC  -0.043415
ADA  -0.038882
XRP  -0.033117
ATOM -0.031141
ZRX  -0.017113
LINK -0.014222
BNB  -0.012292
QTUM -0.006220
TRX  -0.005534
IOTA -0.003792
BAT  -0.000424
NEO   0.016456
BCH   0.016483
ETH   0.036868
ICX   0.039273
ALGO  0.086833
VET   0.156302
ZIL   0.166096
g================================================================          ETH     ICX    ALGO      VET      ZIL
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  2316.15  0.9279  0.9062  0.08348  0.08133
721  2121.52  1.0350  0.8683  0.07614  0.07509
722  2146.27  0.9786  0.9059  0.07704  0.07496
723  2111.19  0.9198  0.8918  0.07591  0.07299
724  2138.86  0.9519  0.8952  0.07768  0.07377

[725 rows x 5 columns]
ETH    -0.023998
ICX    -0.059172
ALGO    0.023715
VET     0.072081
ZIL     0.206273
Name: 481, dtype: float64
報酬 0.0437800591763192 %
i= ETH    -0.023998
ICX    -0.059172
ALGO    0.023715
VET     0.072081
ZIL     0.206273
Name: 481, dtype: float64
牛式===============================
執行第 488
           488
XLM  -0.132847
BCH  -0.097943
QTUM -0.095157
ADA  -0.077996
ZRX  -0.068267
ATOM -0.064261
BNB  -0.063492
XRP  -0.063197
ICX  -0.059172
ZEC  -0.054451
LINK -0.053296
TRX  -0.043881
IOTA -0.039739
NEO  -0.036955
BAT  -0.026262
ETH  -0.023998
LTC   0.002435
ALGO  0.023715
VET   0.072081
ZIL   0.206273
g================================================================          ETH     LTC    ALGO      VET      ZIL
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  2316.15  137.39  0.9062  0.08348  0.08133
721  2121.52  132.25  0.8683  0.07614  0.07509
722  2146.27  134.42  0.9059  0.07704  0.07496
723  2111.19  134.00  0.8918  0.07591  0.07299
724  2138.86  134.19  0.8952  0.07768  0.07377

[725 rows x 5 columns]
ETH     0.010425
LTC     0.017396
ALGO    0.075723
VET     0.231600
ZIL     0.273737
Name: 482, dtype: float64
報酬 0.12177617764885325 %
i= ETH     0.010425
LTC     0.017396
ALGO    0.075723
VET     0.231600
ZIL     0.273737
Name: 482, dtype: float64
牛式===============================
執行第 489
           489
XLM  -0.084686
QTUM -0.038292
ATOM -0.030240
BNB  -0.025556
IOTA -0.023299
LINK -0.019505
BCH  -0.012148
ADA  -0.011426
NEO  -0.004793
XRP  -0.004109
TRX   0.002648
BAT   0.003406
ICX   0.008606
ETH   0.010425
ZEC   0.011787
ZRX   0.012763
LTC   0.017396
ALGO  0.075723
VET   0.231600
ZIL   0.273737
g================================================================         ZRX     LTC    ALGO      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  0.7889  137.39  0.9062  0.08348  0.08133
721  0.8190  132.25  0.8683  0.07614  0.07509
722  0.8384  134.42  0.9059  0.07704  0.07496
723  0.7890  134.00  0.8918  0.07591  0.07299
724  0.7950  134.19  0.8952  0.07768  0.07377

[725 rows x 5 columns]
ZRX    -0.110199
LTC    -0.005254
ALGO   -0.118302
VET    -0.001097
ZIL     0.006423
Name: 483, dtype: float64
報酬 -0.04568601708714346 %
i= ZRX    -0.110199
LTC    -0.005254
ALGO   -0.118302
VET    -0.001097
ZIL     0.006423
Name: 483, dtype: float64
牛式===============================
執行第 490
           490
XLM  -0.175350
ATOM -0.142003
QTUM -0.135271
IOTA -0.133546
LINK -0.132237
ALGO -0.118302
ICX  -0.114051
XRP  -0.113546
ZRX  -0.110199
ADA  -0.110124
TRX  -0.106342
ZEC  -0.092201
BAT  -0.091622
BCH  -0.090764
NEO  -0.086764
BNB  -0.086469
ETH  -0.071812
LTC  -0.005254
VET  -0.001097
ZIL   0.006423
g================================================================         BNB      ETH     LTC      VET      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  327.67  2316.15  137.39  0.08348  0.08133
721  310.59  2121.52  132.25  0.07614  0.07509
722  316.72  2146.27  134.42  0.07704  0.07496
723  316.09  2111.19  134.00  0.07591  0.07299
724  321.87  2138.86  134.19  0.07768  0.07377

[725 rows x 5 columns]
BNB   -0.083062
ETH   -0.068729
LTC    0.069971
VET   -0.035523
ZIL   -0.075893
Name: 484, dtype: float64
報酬 -0.038647191346516466 %
i= BNB   -0.083062
ETH   -0.068729
LTC    0.069971
VET   -0.035523
ZIL   -0.075893
Name: 484, dtype: float64
牛式===============================
執行第 491
           491
QTUM -0.134168
ATOM -0.127656
ICX  -0.118128
IOTA -0.115506
ZRX  -0.114956
NEO  -0.103739
ALGO -0.101969
ADA  -0.098239
LINK -0.096636
BAT  -0.095885
TRX  -0.093493
ZEC  -0.083102
BNB  -0.083062
BCH  -0.079382
ZIL  -0.075893
XRP  -0.075566
ETH  -0.068729
XLM  -0.065853
VET  -0.035523
LTC   0.069971
g================================================================         XRP      ETH      XLM      VET     LTC
0       NaN      NaN      NaN      NaN     NaN
1       NaN      NaN      NaN      NaN     NaN
2       NaN      NaN      NaN      NaN     NaN
3       NaN      NaN      NaN      NaN     NaN
4       NaN      NaN      NaN      NaN     NaN
..      ...      ...      ...      ...     ...
720  0.6521  2316.15  0.25677  0.08348  137.39
721  0.6236  2121.52  0.24383  0.07614  132.25
722  0.6372  2146.27  0.24550  0.07704  134.42
723  0.6251  2111.19  0.24484  0.07591  134.00
724  0.6362  2138.86  0.24587  0.07768  134.19

[725 rows x 5 columns]
XRP    0.033560
ETH   -0.016353
XLM   -0.005014
VET    0.016520
LTC    0.038535
Name: 485, dtype: float64
報酬 0.013449728538887795 %
i= XRP    0.033560
ETH   -0.016353
XLM   -0.005014
VET    0.016520
LTC    0.038535
Name: 485, dtype: float64
牛式===============================
執行第 492
           492
IOTA -0.115014
ALGO -0.098557
BAT  -0.087527
ATOM -0.077837
QTUM -0.062862
LINK -0.062303
NEO  -0.061972
ZRX  -0.058045
BCH  -0.050116
ICX  -0.050113
BNB  -0.046864
TRX  -0.046149
ZEC  -0.044631
ADA  -0.041094
ETH  -0.016353
XLM  -0.005014
VET   0.016520
XRP   0.033560
LTC   0.038535
ZIL   0.103623
g================================================================          XLM      VET     XRP     LTC      ZIL
0        NaN      NaN     NaN     NaN      NaN
1        NaN      NaN     NaN     NaN      NaN
2        NaN      NaN     NaN     NaN      NaN
3        NaN      NaN     NaN     NaN      NaN
4        NaN      NaN     NaN     NaN      NaN
..       ...      ...     ...     ...      ...
720  0.25677  0.08348  0.6521  137.39  0.08133
721  0.24383  0.07614  0.6236  132.25  0.07509
722  0.24550  0.07704  0.6372  134.42  0.07496
723  0.24484  0.07591  0.6251  134.00  0.07299
724  0.24587  0.07768  0.6362  134.19  0.07377

[725 rows x 5 columns]
XLM   -0.125473
VET   -0.110540
XRP   -0.065872
LTC    0.104583
ZIL   -0.135683
Name: 486, dtype: float64
報酬 -0.06659676672141757 %
i= XLM   -0.125473
VET   -0.110540
XRP   -0.065872
LTC    0.104583
ZIL   -0.135683
Name: 486, dtype: float64
牛式===============================
執行第 493
           493
IOTA -0.197072
ALGO -0.162406
ICX  -0.149504
BAT  -0.139101
QTUM -0.138439
ZIL  -0.135683
ADA  -0.129244
ZRX  -0.127513
XLM  -0.125473
LINK -0.116173
NEO  -0.115271
ZEC  -0.113880
VET  -0.110540
BCH  -0.105779
ATOM -0.104793
TRX  -0.091326
ETH  -0.088607
BNB  -0.080727
XRP  -0.065872
LTC   0.104583
g================================================================          TRX      ETH     BNB     XRP     LTC
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.06432  2316.15  327.67  0.6521  137.39
721  0.06111  2121.52  310.59  0.6236  132.25
722  0.06219  2146.27  316.72  0.6372  134.42
723  0.06139  2111.19  316.09  0.6251  134.00
724  0.06184  2138.86  321.87  0.6362  134.19

[725 rows x 5 columns]
TRX   -0.077246
ETH   -0.055677
BNB   -0.046102
XRP   -0.186621
LTC    0.077017
Name: 487, dtype: float64
報酬 -0.05772571443333015 %
i= TRX   -0.077246
ETH   -0.055677
BNB   -0.046102
XRP   -0.186621
LTC    0.077017
Name: 487, dtype: float64
牛式===============================
執行第 494
           494
XRP  -0.186621
IOTA -0.140408
ZEC  -0.116781
BAT  -0.110830
XLM  -0.097568
LINK -0.094815
ADA  -0.090519
ALGO -0.081378
NEO  -0.080601
TRX  -0.077246
ZIL  -0.074336
ICX  -0.071601
QTUM -0.069732
BCH  -0.064993
ETH  -0.055677
BNB  -0.046102
VET  -0.038170
ATOM -0.029542
ZRX  -0.019755
LTC   0.077017
g================================================================         BNB      VET    ATOM     ZRX     LTC
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  327.67  0.08348  12.946  0.7889  137.39
721  310.59  0.07614  11.958  0.8190  132.25
722  316.72  0.07704  13.182  0.8384  134.42
723  316.09  0.07591  14.395  0.7890  134.00
724  321.87  0.07768  14.064  0.7950  134.19

[725 rows x 5 columns]
BNB    -0.007834
VET    -0.091707
ATOM    0.018827
ZRX    -0.021250
LTC     0.051532
Name: 488, dtype: float64
報酬 -0.010086368742095453 %
i= BNB    -0.007834
VET    -0.091707
ATOM    0.018827
ZRX    -0.021250
LTC     0.051532
Name: 488, dtype: float64
牛式===============================
執行第 495
           495
XRP  -0.154945
ZEC  -0.096373
BAT  -0.095885
VET  -0.091707
ICX  -0.082484
ZIL  -0.077637
ALGO -0.065861
IOTA -0.053986
TRX  -0.035655
BCH  -0.027308
ZRX  -0.021250
QTUM -0.021057
LINK -0.009946
NEO  -0.009804
BNB  -0.007834
ETH  -0.000507
ADA   0.000325
ATOM  0.018827
XLM   0.049206
LTC   0.051532
g================================================================          ETH     ADA    ATOM      XLM     LTC
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  2316.15  1.4039  12.946  0.25677  137.39
721  2121.52  1.3327  11.958  0.24383  132.25
722  2146.27  1.3497  13.182  0.24550  134.42
723  2111.19  1.3356  14.395  0.24484  134.00
724  2138.86  1.3478  14.064  0.24587  134.19

[725 rows x 5 columns]
ETH     0.056220
ADA     0.120566
ATOM    0.103441
XLM     0.112930
LTC     0.072989
Name: 489, dtype: float64
報酬 0.09322924798763683 %
i= ETH     0.056220
ADA     0.120566
ATOM    0.103441
XLM     0.112930
LTC     0.072989
Name: 489, dtype: float64
牛式===============================
執行第 496
           496
XRP  -0.110111
ZEC  -0.023273
BAT  -0.009087
VET  -0.000977
IOTA  0.011702
ZRX   0.019236
BCH   0.034171
ALGO  0.039190
TRX   0.043011
ICX   0.043769
QTUM  0.044398
ZIL   0.051691
ETH   0.056220
NEO   0.056615
LINK  0.056837
LTC   0.072989
BNB   0.084899
ATOM  0.103441
XLM   0.112930
ADA   0.120566
g================================================================         LTC     BNB    ATOM      XLM     ADA
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  137.39  327.67  12.946  0.25677  1.4039
721  132.25  310.59  11.958  0.24383  1.3327
722  134.42  316.72  13.182  0.24550  1.3497
723  134.00  316.09  14.395  0.24484  1.3356
724  134.19  321.87  14.064  0.24587  1.3478

[725 rows x 5 columns]
LTC     0.015895
BNB     0.048668
ATOM    0.100749
XLM    -0.035306
ADA     0.039603
Name: 490, dtype: float64
報酬 0.03392175166671687 %
i= LTC     0.015895
BNB     0.048668
ATOM    0.100749
XLM    -0.035306
ADA     0.039603
Name: 490, dtype: float64
牛式===============================
執行第 497
           497
XRP  -0.197340
XLM  -0.035306
ZEC  -0.024784
VET  -0.016449
IOTA -0.010369
BAT  -0.007283
LINK  0.004754
NEO   0.011717
LTC   0.015895
TRX   0.017073
ETH   0.026710
ZRX   0.027289
ICX   0.030654
QTUM  0.037736
ADA   0.039603
BNB   0.048668
ALGO  0.064136
BCH   0.072321
ATOM  0.100749
ZIL   0.127858
g================================================================         BNB    ALGO     BCH    ATOM      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  327.67  0.9062  509.55  12.946  0.08133
721  310.59  0.8683  490.60  11.958  0.07509
722  316.72  0.9059  504.08  13.182  0.07496
723  316.09  0.8918  497.02  14.395  0.07299
724  321.87  0.8952  498.00  14.064  0.07377

[725 rows x 5 columns]
BNB     0.105206
ALGO    0.158038
BCH     0.174651
ATOM    0.179124
ZIL     0.202209

Name: 491, dtype: float64
報酬 0.16384563207607386 %
i= BNB     0.105206
ALGO    0.158038
BCH     0.174651
ATOM    0.179124
ZIL     0.202209
Name: 491, dtype: float64
牛式===============================
執行第 498
           498
XRP  -0.001644
LTC   0.012215
VET   0.085273
BNB   0.105206
NEO   0.106989
ZEC   0.111179
TRX   0.117040
BAT   0.117506
ZRX   0.120000
ICX   0.121604
LINK  0.134567
QTUM  0.138272
ETH   0.141703
ALGO  0.158038
IOTA  0.159115
BCH   0.174651
ATOM  0.179124
ADA   0.187518
ZIL   0.202209
XLM   0.208237
g================================================================         BCH    ATOM     ADA      ZIL      XLM
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  509.55  12.946  1.4039  0.08133  0.25677
721  490.60  11.958  1.3327  0.07509  0.24383
722  504.08  13.182  1.3497  0.07496  0.24550
723  497.02  14.395  1.3356  0.07299  0.24484
724  498.00  14.064  1.3478  0.07377  0.24587

[725 rows x 5 columns]
BCH     0.199468
ATOM    0.139367
ADA     0.173201
ZIL     0.287802
XLM     0.241299
Name: 492, dtype: float64
報酬 0.2082272473924231 %
i= BCH     0.199468
ATOM    0.139367
ADA     0.173201
ZIL     0.287802
XLM     0.241299
Name: 492, dtype: float64
牛式===============================
執行第 499
           499
LTC  -0.032002
XRP   0.056929
VET   0.098188
BNB   0.105745
TRX   0.108429
BAT   0.116256
NEO   0.117588
ICX   0.136629
ATOM  0.139367
ZRX   0.144463
QTUM  0.148718
ALGO  0.152272
LINK  0.157216
ZEC   0.168107
IOTA  0.169220
ADA   0.173201
ETH   0.183008
BCH   0.199468
XLM   0.241299
ZIL   0.287802
g================================================================         ADA      ETH     BCH      XLM      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  1.4039  2316.15  509.55  0.25677  0.08133
721  1.3327  2121.52  490.60  0.24383  0.07509
722  1.3497  2146.27  504.08  0.24550  0.07496
723  1.3356  2111.19  497.02  0.24484  0.07299
724  1.3478  2138.86  498.00  0.24587  0.07377

[725 rows x 5 columns]
ADA    0.143679
ETH    0.150840
BCH    0.170545
XLM    0.165733
ZIL    0.337099
Name: 493, dtype: float64
報酬 0.19357910837496856 %
i= ADA    0.143679
ETH    0.150840
BCH    0.170545
XLM    0.165733
ZIL    0.337099
Name: 493, dtype: float64
牛式===============================
執行第 500
           500
LTC  -0.022784
ZRX   0.053061
ATOM  0.053370
VET   0.057282
NEO   0.088092
TRX   0.088967
BNB   0.100213
LINK  0.104746
QTUM  0.110211
IOTA  0.113824
ZEC   0.120394
ICX   0.129755
ALGO  0.141287
ADA   0.143679
ETH   0.150840
XRP   0.153144
XLM   0.165733
BCH   0.170545
BAT   0.183412
ZIL   0.337099
g================================================================         XRP      XLM     BCH     BAT      ZIL
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.6521  0.25677  509.55  0.6135  0.08133
721  0.6236  0.24383  490.60  0.5691  0.07509
722  0.6372  0.24550  504.08  0.5695  0.07496
723  0.6251  0.24484  497.02  0.5575  0.07299
724  0.6362  0.24587  498.00  0.5623  0.07377

[725 rows x 5 columns]
XRP    0.122016
XLM    0.029488
BCH    0.151675
BAT    0.147349
ZIL    0.524855
Name: 494, dtype: float64
報酬 0.1950767870725519 %
i= XRP    0.122016
XLM    0.029488
BCH    0.151675
BAT    0.147349
ZIL    0.524855
Name: 494, dtype: float64
牛式===============================
執行第 501
           501
LTC  -0.049458
ATOM  0.018094
XLM   0.029488
NEO   0.032656
LINK  0.040958
VET   0.055950
ADA   0.066143
TRX   0.068470
ZRX   0.069174
ZEC   0.076912
QTUM  0.099335
ETH   0.114462
XRP   0.122016
ICX   0.122449
IOTA  0.129728
BNB   0.143151
BAT   0.147349
ALGO  0.150065
BCH   0.151675
ZIL   0.524855
g================================================================         BNB     BAT    ALGO     BCH      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  327.67  0.6135  0.9062  509.55  0.08133
721  310.59  0.5691  0.8683  490.60  0.07509
722  316.72  0.5695  0.9059  504.08  0.07496
723  316.09  0.5575  0.8918  497.02  0.07299
724  321.87  0.5623  0.8952  498.00  0.07377

[725 rows x 5 columns]
BNB     0.141192
BAT     0.064649
ALGO    0.084052
BCH     0.262314
ZIL     0.403823
Name: 495, dtype: float64
報酬 0.19120612776305834 %
i= BNB     0.141192
BAT     0.064649
ALGO    0.084052
BCH     0.262314
ZIL     0.403823
Name: 495, dtype: float64
牛式===============================
執行第 502
           502
LTC  -0.062654
ATOM -0.037115
VET  -0.002077
NEO   0.008624
LINK  0.018706
ZRX   0.021975
ADA   0.023566
XLM   0.040353
ICX   0.054267
BAT   0.064649
IOTA  0.071712
TRX   0.072852
ZEC   0.083836
ALGO  0.084052
ETH   0.088718
QTUM  0.113230
XRP   0.118328
BNB   0.141192
BCH   0.262314
ZIL   0.403823
g================================================================       QTUM     XRP     BNB     BCH      ZIL
0      NaN     NaN     NaN     NaN      NaN
1      NaN     NaN     NaN     NaN      NaN
2      NaN     NaN     NaN     NaN      NaN
3      NaN     NaN     NaN     NaN      NaN
4      NaN     NaN     NaN     NaN      NaN
..     ...     ...     ...     ...      ...
720  7.079  0.6521  327.67  509.55  0.08133
721  6.504  0.6236  310.59  490.60  0.07509
722  6.776  0.6372  316.72  504.08  0.07496
723  6.639  0.6251  316.09  497.02  0.07299
724  6.694  0.6362  321.87  498.00  0.07377

[725 rows x 5 columns]
QTUM    0.006190
XRP     0.099404
BNB     0.089431
BCH     0.086064
ZIL     0.412621
Name: 496, dtype: float64
報酬 0.13874187954561545 %
i= QTUM    0.006190
XRP     0.099404
BNB     0.089431
BCH     0.086064
ZIL     0.412621
Name: 496, dtype: float64
牛式===============================
執行第 503
           503
VET  -0.059565
LTC  -0.051185
ATOM -0.048411
ZRX  -0.036526
NEO  -0.034100
LINK -0.029180
ADA  -0.007541
XLM  -0.005357
ICX  -0.003999
IOTA -0.003274
ALGO -0.001230
ZEC   0.002069
TRX   0.002398
QTUM  0.006190
BAT   0.026135
ETH   0.031941
BCH   0.086064
BNB   0.089431
XRP   0.099404
ZIL   0.412621
g================================================================          ETH     BCH     BNB     XRP      ZIL
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  2316.15  509.55  327.67  0.6521  0.08133
721  2121.52  490.60  310.59  0.6236  0.07509
722  2146.27  504.08  316.72  0.6372  0.07496
723  2111.19  497.02  316.09  0.6251  0.07299
724  2138.86  498.00  321.87  0.6362  0.07377

[725 rows x 5 columns]
ETH    0.000188
BCH    0.037387
BNB    0.096827
XRP   -0.216898
ZIL    0.311383
Name: 497, dtype: float64
報酬 0.04577756369237982 %
i= ETH    0.000188
BCH    0.037387
BNB    0.096827
XRP   -0.216898
ZIL    0.311383
Name: 497, dtype: float64
牛式===============================
執行第 504
           504
XRP  -0.216898
XLM  -0.165139
ATOM -0.098907
ZRX  -0.094353
VET  -0.081753
TRX  -0.079936
NEO  -0.078833
ZEC  -0.074939
ADA  -0.068252
QTUM -0.067968
IOTA -0.067879
ICX  -0.067027
BAT  -0.063090
LINK -0.051149
LTC  -0.028916
ALGO -0.009706
ETH   0.000188
BCH   0.037387
BNB   0.096827
ZIL   0.311383
g================================================================        ALGO      ETH     BCH     BNB      ZIL
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  0.9062  2316.15  509.55  327.67  0.08133
721  0.8683  2121.52  490.60  310.59  0.07509
722  0.9059  2146.27  504.08  316.72  0.07496
723  0.8918  2111.19  497.02  316.09  0.07299
724  0.8952  2138.86  498.00  321.87  0.07377

[725 rows x 5 columns]
ALGO   -0.128537
ETH    -0.089673
BCH    -0.113899
BNB     0.032098
ZIL     0.517942
Name: 498, dtype: float64
報酬 0.04358624221827954 %
i= ALGO   -0.128537
ETH    -0.089673
BCH    -0.113899
BNB     0.032098
ZIL     0.517942
Name: 498, dtype: float64
牛式===============================
執行第 505
           505
XRP  -0.549200
XLM  -0.319627
ZEC  -0.252993
NEO  -0.240871
VET  -0.223113
QTUM -0.220238
TRX  -0.194020
LINK -0.186340
ZRX  -0.183694
ATOM -0.180123
IOTA -0.173737
ADA  -0.164708
BAT  -0.146955
ICX  -0.136086
ALGO -0.128537
BCH  -0.113899
ETH  -0.089673
LTC  -0.043776
BNB   0.032098
ZIL   0.517942
g================================================================         BCH      ETH     LTC     BNB      ZIL
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  509.55  2316.15  137.39  327.67  0.08133
721  490.60  2121.52  132.25  310.59  0.07509
722  504.08  2146.27  134.42  316.72  0.07496
723  497.02  2111.19  134.00  316.09  0.07299
724  498.00  2138.86  134.19  321.87  0.07377

[725 rows x 5 columns]
BCH   -0.053224
ETH   -0.063317
LTC    0.010849
BNB    0.050388
ZIL    0.356017
Name: 499, dtype: float64
報酬 0.06014270434159574 %
i= BCH   -0.053224
ETH   -0.063317
LTC    0.010849
BNB    0.050388
ZIL    0.356017
Name: 499, dtype: float64
牛式===============================
執行第 506
           506
XRP  -0.422676
ZEC  -0.159832
QTUM -0.157664
NEO  -0.147013
XLM  -0.145357
VET  -0.145202
LINK -0.142222
ICX  -0.127537
BAT  -0.127353
ZRX  -0.117975
ALGO -0.109915
TRX  -0.109360
IOTA -0.091386
ADA  -0.072420
ATOM -0.069431
ETH  -0.063317
BCH  -0.053224
LTC   0.010849
BNB   0.050388
ZIL   0.356017
g================================================================          ETH     BCH     LTC     BNB      ZIL
0        NaN     NaN     NaN     NaN      NaN
1        NaN     NaN     NaN     NaN      NaN
2        NaN     NaN     NaN     NaN      NaN
3        NaN     NaN     NaN     NaN      NaN
4        NaN     NaN     NaN     NaN      NaN
..       ...     ...     ...     ...      ...
720  2316.15  509.55  137.39  327.67  0.08133
721  2121.52  490.60  132.25  310.59  0.07509
722  2146.27  504.08  134.42  316.72  0.07496
723  2111.19  497.02  134.00  316.09  0.07299
724  2138.86  498.00  134.19  321.87  0.07377

[725 rows x 5 columns]
ETH   -0.047921
BCH    0.003712
LTC    0.068900
BNB   -0.003604
ZIL    0.264000
Name: 500, dtype: float64
報酬 0.05701734260292346 %
i= ETH   -0.047921
BCH    0.003712
LTC    0.068900
BNB   -0.003604
ZIL    0.264000
Name: 500, dtype: float64
牛式===============================
執行第 507
           507
XRP  -0.448444
QTUM -0.186055
XLM  -0.160626
VET  -0.160166
ZRX  -0.153011
NEO  -0.149369
LINK -0.141797
IOTA -0.140675
ALGO -0.131609
ZEC  -0.125697
BAT  -0.124744
TRX  -0.085550
ATOM -0.071847
ICX  -0.071577
ETH  -0.047921
ADA  -0.040731
BNB  -0.003604
BCH   0.003712
LTC   0.068900
ZIL   0.264000
g================================================================         ADA     BNB     BCH     LTC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  1.4039  327.67  509.55  137.39  0.08133
721  1.3327  310.59  490.60  132.25  0.07509
722  1.3497  316.72  504.08  134.42  0.07496
723  1.3356  316.09  497.02  134.00  0.07299
724  1.3478  321.87  498.00  134.19  0.07377

[725 rows x 5 columns]
ADA   -0.022529
BNB   -0.020134
BCH   -0.074694
LTC    0.072571
ZIL    0.866004
Name: 501, dtype: float64
報酬 0.16424346139295848 %
i= ADA   -0.022529
BNB   -0.020134
BCH   -0.074694
LTC    0.072571
ZIL    0.866004
Name: 501, dtype: float64
牛式===============================
執行第 508
           508
XRP  -0.470636
QTUM -0.193433
XLM  -0.169795
LINK -0.159908
NEO  -0.146033
IOTA -0.117175
TRX  -0.110186
ZRX  -0.104731
ZEC  -0.096757
ALGO -0.089033
BAT  -0.079242
BCH  -0.074694
ATOM -0.044308
ICX  -0.025035
ADA  -0.022529
BNB  -0.020134
ETH  -0.002804
VET   0.007469
LTC   0.072571
ZIL   0.866004
g================================================================         BNB      ETH      VET     LTC      ZIL
0       NaN      NaN      NaN     NaN      NaN
1       NaN      NaN      NaN     NaN      NaN
2       NaN      NaN      NaN     NaN      NaN
3       NaN      NaN      NaN     NaN      NaN
4       NaN      NaN      NaN     NaN      NaN
..      ...      ...      ...     ...      ...
720  327.67  2316.15  0.08348  137.39  0.08133
721  310.59  2121.52  0.07614  132.25  0.07509
722  316.72  2146.27  0.07704  134.42  0.07496
723  316.09  2111.19  0.07591  134.00  0.07299
724  321.87  2138.86  0.07768  134.19  0.07377

[725 rows x 5 columns]
BNB    0.046020
ETH    0.125128
VET    0.066302
LTC    0.039105
ZIL    0.541540
Name: 502, dtype: float64
報酬 0.16361882672051226 %
i= BNB    0.046020
ETH    0.125128
VET    0.066302
LTC    0.039105
ZIL    0.541540
Name: 502, dtype: float64
牛式===============================
執行第 509
           509
XRP  -0.447802
QTUM -0.125336
XLM  -0.120612
NEO  -0.084898
BAT  -0.067471
ATOM -0.039547
IOTA -0.024310
ALGO -0.017857
ZEC  -0.013123
LINK -0.012998
TRX  -0.012645
ZRX  -0.009014
ICX   0.005772
ADA   0.012904
LTC   0.039105
BNB   0.046020
VET   0.066302
BCH   0.079180
ETH   0.125128

ZIL   0.541540
g================================================================         BNB      VET     BCH      ETH      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  327.67  0.08348  509.55  2316.15  0.08133
721  310.59  0.07614  490.60  2121.52  0.07509
722  316.72  0.07704  504.08  2146.27  0.07496
723  316.09  0.07591  497.02  2111.19  0.07299
724  321.87  0.07768  498.00  2138.86  0.07377

[725 rows x 5 columns]
BNB    0.071876
VET    0.267410
BCH    0.116365
ETH    0.145255
ZIL    0.740366
Name: 503, dtype: float64
報酬 0.26825423586028163 %
i= BNB    0.071876
VET    0.267410
BCH    0.116365
ETH    0.145255
ZIL    0.740366
Name: 503, dtype: float64
牛式===============================
執行第 510
           510
XRP  -0.442029
XLM  -0.107753
QTUM -0.076028
NEO  -0.055361
BAT  -0.034814
LINK -0.014063
IOTA -0.003901
ZRX   0.004796
ZEC   0.018445
TRX   0.024230
ALGO  0.061776
BNB   0.071876
ATOM  0.088539
BCH   0.116365
ADA   0.125702
ICX   0.131334
ETH   0.145255
LTC   0.152638
VET   0.267410
ZIL   0.740366
g================================================================         ICX      ETH     LTC      VET      ZIL
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  0.9279  2316.15  137.39  0.08348  0.08133
721  1.0350  2121.52  132.25  0.07614  0.07509
722  0.9786  2146.27  134.42  0.07704  0.07496
723  0.9198  2111.19  134.00  0.07591  0.07299
724  0.9519  2138.86  134.19  0.07768  0.07377

[725 rows x 5 columns]
ICX    0.319005
ETH    0.249509
LTC    0.146876
VET    0.591248
ZIL    0.464280
Name: 504, dtype: float64
報酬 0.35418354412440034 %
i= ICX    0.319005
ETH    0.249509
LTC    0.146876
VET    0.591248
ZIL    0.464280
Name: 504, dtype: float64
牛式===============================
執行第 511
           511
XRP  -0.149344
BAT   0.067253
LINK  0.072080
QTUM  0.083492
XLM   0.089197
ZRX   0.098676
TRX   0.115323
NEO   0.115772
IOTA  0.141940
LTC   0.146876
ZEC   0.175729
ALGO  0.195855
ETH   0.249509
BNB   0.253607
ATOM  0.278599
BCH   0.279621
ICX   0.319005
ADA   0.401114
ZIL   0.464280
VET   0.591248
g================================================================         BCH     ICX     ADA      ZIL      VET
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  509.55  0.9279  1.4039  0.08133  0.08348
721  490.60  1.0350  1.3327  0.07509  0.07614
722  504.08  0.9786  1.3497  0.07496  0.07704
723  497.02  0.9198  1.3356  0.07299  0.07591
724  498.00  0.9519  1.3478  0.07377  0.07768

[725 rows x 5 columns]
BCH    0.209632
ICX    0.249802
ADA    0.202078
ZIL    0.302459
VET    0.359876
Name: 505, dtype: float64
報酬 0.2647693725608208 %
i= BCH    0.209632
ICX    0.249802
ADA    0.202078
ZIL    0.302459
VET    0.359876
Name: 505, dtype: float64
牛式===============================
執行第 512
           512
XRP  -0.372643
XLM  -0.167299
BAT  -0.076182
QTUM -0.040295
NEO  -0.036329
LINK -0.028497
TRX  -0.026724
ZRX  -0.012634
IOTA  0.003738
ZEC   0.032378
ALGO  0.067791
ATOM  0.093769
BNB   0.171279
ADA   0.202078
BCH   0.209632
LTC   0.217630
ETH   0.227597
ICX   0.249802
ZIL   0.302459
VET   0.359876
g================================================================         LTC      ETH     ICX      ZIL      VET
0       NaN      NaN     NaN      NaN      NaN
1       NaN      NaN     NaN      NaN      NaN
2       NaN      NaN     NaN      NaN      NaN
3       NaN      NaN     NaN      NaN      NaN
4       NaN      NaN     NaN      NaN      NaN
..      ...      ...     ...      ...      ...
720  137.39  2316.15  0.9279  0.08133  0.08348
721  132.25  2121.52  1.0350  0.07509  0.07614
722  134.42  2146.27  0.9786  0.07496  0.07704
723  134.00  2111.19  0.9198  0.07299  0.07591
724  134.19  2138.86  0.9519  0.07377  0.07768

[725 rows x 5 columns]
LTC    0.239831
ETH    0.173742
ICX    0.156420
ZIL    0.306487
VET    0.284423
Name: 506, dtype: float64
報酬 0.2321807659416882 %
i= LTC    0.239831
ETH    0.173742
ICX    0.156420
ZIL    0.306487
VET    0.284423
Name: 506, dtype: float64
牛式===============================
執行第 513
           513
XRP  -0.310804
XLM  -0.162751
BAT  -0.067290
TRX  -0.062018
NEO  -0.059983
QTUM -0.029283
LINK -0.028547
ZRX  -0.010315
ZEC  -0.005757
IOTA  0.012987
BCH   0.071106
ALGO  0.085816
BNB   0.125075
ADA   0.151498
ICX   0.156420
ETH   0.173742
LTC   0.239831
VET   0.284423
ZIL   0.306487
ATOM  0.317376
g================================================================          ETH     LTC      VET      ZIL    ATOM
0        NaN     NaN      NaN      NaN     NaN
1        NaN     NaN      NaN      NaN     NaN
2        NaN     NaN      NaN      NaN     NaN
3        NaN     NaN      NaN      NaN     NaN
4        NaN     NaN      NaN      NaN     NaN
..       ...     ...      ...      ...     ...
720  2316.15  137.39  0.08348  0.08133  12.946
721  2121.52  132.25  0.07614  0.07509  11.958
722  2146.27  134.42  0.07704  0.07496  13.182
723  2111.19  134.00  0.07591  0.07299  14.395
724  2138.86  134.19  0.07768  0.07377  14.064

[725 rows x 5 columns]
ETH     0.145009
LTC     0.228578
VET     0.157572
ZIL    -0.086287
ATOM    0.218711
Name: 507, dtype: float64
報酬 0.13271660156088744 %
i= ETH     0.145009
LTC     0.228578
VET     0.157572
ZIL    -0.086287
ATOM    0.218711
Name: 507, dtype: float64
牛式===============================
執行第 514
           514
XRP  -0.194750
ZEC  -0.146635
XLM  -0.101001
ZIL  -0.086287
BAT  -0.044902
NEO  -0.034842
TRX  -0.032757
QTUM  0.003540
IOTA  0.015718
BCH   0.056021
ZRX   0.057926
LINK  0.078324
ICX   0.079194
ADA   0.105203
BNB   0.123585
ETH   0.145009
VET   0.157572
ATOM  0.218711
LTC   0.228578
ALGO  0.289320
g================================================================          ETH      VET    ATOM     LTC    ALGO
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  2316.15  0.08348  12.946  137.39  0.9062
721  2121.52  0.07614  11.958  132.25  0.8683
722  2146.27  0.07704  13.182  134.42  0.9059
723  2111.19  0.07591  14.395  134.00  0.8918
724  2138.86  0.07768  14.064  134.19  0.8952

[725 rows x 5 columns]
ETH     0.132609
VET     0.208109
ATOM    0.120008
LTC     0.285196
ALGO    0.277429
Name: 508, dtype: float64
報酬 0.2046703963816074 %
i= ETH     0.132609
VET     0.208109
ATOM    0.120008
LTC     0.285196
ALGO    0.277429
Name: 508, dtype: float64
牛式===============================
執行第 515
           515
XRP  -0.221980
ZEC  -0.141790
XLM  -0.122290
TRX  -0.058844
ZIL  -0.053632
NEO  -0.045394
IOTA -0.037374
ZRX  -0.035848
BAT  -0.023000
QTUM -0.011429
LINK  0.004938
BCH   0.047040
ICX   0.082834
ATOM  0.120008
ETH   0.132609
BNB   0.136742
ADA   0.146469
VET   0.208109
ALGO  0.277429
LTC   0.285196
g================================================================         BNB     ADA      VET    ALGO     LTC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  327.67  1.4039  0.08348  0.9062  137.39
721  310.59  1.3327  0.07614  0.8683  132.25
722  316.72  1.3497  0.07704  0.9059  134.42
723  316.09  1.3356  0.07591  0.8918  134.00
724  321.87  1.3478  0.07768  0.8952  134.19

[725 rows x 5 columns]
BNB     0.146912
ADA     0.166024
VET     0.298823
ALGO    0.189371
LTC     0.182669
Name: 509, dtype: float64
報酬 0.19675956791532437 %
i= BNB     0.146912
ADA     0.166024
VET     0.298823
ALGO    0.189371
LTC     0.182669
Name: 509, dtype: float64
牛式===============================
執行第 516
           516
ZIL  -0.243905
ZEC  -0.141553
XRP  -0.099527
XLM  -0.059450
TRX  -0.004393
IOTA  0.010444
NEO   0.026104
BAT   0.030375
QTUM  0.034005
ZRX   0.040308
ICX   0.082888
ATOM  0.083380
LINK  0.085578
BNB   0.146912
ADA   0.166024
BCH   0.170406
LTC   0.182669
ALGO  0.189371
VET   0.298823
ETH   0.334005
g================================================================         BCH     LTC    ALGO      VET      ETH
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  509.55  137.39  0.9062  0.08348  2316.15
721  490.60  132.25  0.8683  0.07614  2121.52
722  504.08  134.42  0.9059  0.07704  2146.27
723  497.02  134.00  0.8918  0.07591  2111.19
724  498.00  134.19  0.8952  0.07768  2138.86

[725 rows x 5 columns]
BCH     0.150379
LTC     0.281705
ALGO    0.286828
VET     0.166138
ETH     0.423951
Name: 510, dtype: float64
報酬 0.2618002787638086 %
i= BCH     0.150379
LTC     0.281705
ALGO    0.286828
VET     0.166138
ETH     0.423951
Name: 510, dtype: float64
牛式===============================
執行第 517
           517
ZIL  -0.169160
ZEC  -0.075651
BNB   0.051151
BAT   0.058168
XRP   0.063755
ATOM  0.075062
ZRX   0.083516
NEO   0.087020
QTUM  0.107442
TRX   0.118944
ICX   0.120712
IOTA  0.135868
BCH   0.150379
LINK  0.159149
VET   0.166138
ADA   0.181267
XLM   0.188237
LTC   0.281705
ALGO  0.286828
ETH   0.423951
g================================================================         ADA      XLM     LTC    ALGO      ETH
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  1.4039  0.25677  137.39  0.9062  2316.15
721  1.3327  0.24383  132.25  0.8683  2121.52
722  1.3497  0.24550  134.42  0.9059  2146.27
723  1.3356  0.24484  134.00  0.8918  2111.19
724  1.3478  0.24587  134.19  0.8952  2138.86

[725 rows x 5 columns]
ADA     0.405402
XLM     0.467628
LTC     0.064329
ALGO    0.426528
ETH     0.462597
Name: 511, dtype: float64
報酬 0.3652966644298175 %
i= ADA     0.405402
XLM     0.467628
LTC     0.064329
ALGO    0.426528
ETH     0.462597
Name: 511, dtype: float64
牛式===============================
執行第 518
           518
ZIL  -0.092966
ZEC  -0.068497
TRX   0.058256
LTC   0.064329
XRP   0.066698
BNB   0.097138
ATOM  0.142883
NEO   0.146583
BAT   0.148535
ICX   0.155034
BCH   0.165724
QTUM  0.179233
IOTA  0.190589
ZRX   0.236439
LINK  0.290667
VET   0.377506
ADA   0.405402
ALGO  0.426528
ETH   0.462597
XLM   0.467628
g================================================================          VET     ADA    ALGO      ETH      XLM
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  0.08348  1.4039  0.9062  2316.15  0.25677
721  0.07614  1.3327  0.8683  2121.52  0.24383
722  0.07704  1.3497  0.9059  2146.27  0.24550
723  0.07591  1.3356  0.8918  2111.19  0.24484
724  0.07768  1.3478  0.8952  2138.86  0.24587

[725 rows x 5 columns]
VET     0.642720
ADA     0.833765
ALGO    0.525500
ETH     0.642073
XLM     1.661781
Name: 512, dtype: float64
報酬 0.86116768464847 %
i= VET     0.642720
ADA     0.833765
ALGO    0.525500
ETH     0.642073
XLM     1.661781
Name: 512, dtype: float64
牛式===============================
執行第 519
           519
ZIL  -0.058132
ZEC   0.000469
ATOM  0.032782
LTC   0.048404
BNB   0.131530
XRP   0.134784
TRX   0.137841
BAT   0.253006
IOTA  0.285762
ZRX   0.298592
BCH   0.326604
ICX   0.343194
QTUM  0.356596
NEO   0.369119
ALGO  0.525500
LINK  0.536064
ETH   0.642073
VET   0.642720
ADA   0.833765
XLM   1.661781
g================================================================       LINK      ETH      VET     ADA      XLM
0      NaN      NaN      NaN     NaN      NaN
1      NaN      NaN      NaN     NaN      NaN
2      NaN      NaN      NaN     NaN      NaN
3      NaN      NaN      NaN     NaN      NaN
4      NaN      NaN      NaN     NaN      NaN
..     ...      ...      ...     ...      ...
720  19.79  2316.15  0.08348  1.4039  0.25677
721  18.44  2121.52  0.07614  1.3327  0.24383
722  18.66  2146.27  0.07704  1.3497  0.24550
723  18.20  2111.19  0.07591  1.3356  0.24484
724  18.38  2138.86  0.07768  1.3478  0.24587

[725 rows x 5 columns]
LINK    0.351351
ETH     0.680075
VET     0.501549
ADA     0.701234
XLM     1.364394
Name: 513, dtype: float64
報酬 0.7197206511900915 %
i= LINK    0.351351
ETH     0.680075
VET     0.501549
ADA     0.701234
XLM     1.364394
Name: 513, dtype: float64
牛式===============================
執行第 520
           520
ZIL  -0.039549
LTC   0.043659
ATOM  0.068407
TRX   0.151098
ALGO  0.156627
BNB   0.156904
ZRX   0.171207
ZEC   0.193838
BAT   0.255632
QTUM  0.273810
ICX   0.275072
BCH   0.312323
IOTA  0.316025
LINK  0.351351
XRP   0.363725
NEO   0.445228
VET   0.501549
ETH   0.680075
ADA   0.701234
XLM   1.364394
g================================================================         NEO      VET      ETH     ADA      XLM
0       NaN      NaN      NaN     NaN      NaN
1       NaN      NaN      NaN     NaN      NaN
2       NaN      NaN      NaN     NaN      NaN
3       NaN      NaN      NaN     NaN      NaN
4       NaN      NaN      NaN     NaN      NaN
..      ...      ...      ...     ...      ...
720  37.005  0.08348  2316.15  1.4039  0.25677
721  34.083  0.07614  2121.52  1.3327  0.24383
722  34.637  0.07704  2146.27  1.3497  0.24550
723  34.057  0.07591  2111.19  1.3356  0.24484
724  34.191  0.07768  2138.86  1.3478  0.24587

[725 rows x 5 columns]
NEO    0.370927
VET    0.363577
ETH    0.569944
ADA    0.715438
XLM    1.328289
Name: 514, dtype: float64
報酬 0.6696350922319227 %
i= NEO    0.370927
VET    0.363577
ETH    0.569944
ADA    0.715438
XLM    1.328289
Name: 514, dtype: float64
牛式===============================
執行第 521
           521
ZIL   0.016073
LTC   0.038278
ATOM  0.094587
BNB   0.106956
ALGO  0.116319
TRX   0.119529
ZEC   0.194116
ZRX   0.221143
BAT   0.231486
BCH   0.233817
LINK  0.248157
QTUM  0.271676
IOTA  0.291710
VET   0.363577
NEO   0.370927
ICX   0.452074
XRP   0.452274
ETH   0.569944
ADA   0.715438
XLM   1.328289
g================================================================         ICX     XRP      ETH     ADA      XLM
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  0.9279  0.6521  2316.15  1.4039  0.25677
721  1.0350  0.6236  2121.52  1.3327  0.24383
722  0.9786  0.6372  2146.27  1.3497  0.24550
723  0.9198  0.6251  2111.19  1.3356  0.24484
724  0.9519  0.6362  2138.86  1.3478  0.24587

[725 rows x 5 columns]
ICX    0.410288
XRP    0.443267
ETH    0.309709
ADA    0.603957
XLM    1.280318
Name: 515, dtype: float64
報酬 0.6095077583620384 %
i= ICX    0.410288
XRP    0.443267
ETH    0.309709
ADA    0.603957
XLM    1.280318
Name: 515, dtype: float64
牛式===============================
執行第 522
           522
LTC   0.015652
BNB   0.062834
VET   0.103924
ATOM  0.121358
ZIL   0.121580
ALGO  0.140169
TRX   0.147318
BAT   0.264394
LINK  0.281752
ETH   0.309709
QTUM  0.310191
ZEC   0.326245
NEO   0.330465
BCH   0.359143
ZRX   0.382106
IOTA  0.394703
ICX   0.410288
XRP   0.443267
ADA   0.603957
XLM   1.280318
g================================================================        IOTA     ICX     XRP     ADA      XLM
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.8896  0.9279  0.6521  1.4039  0.25677
721  0.8165  1.0350  0.6236  1.3327  0.24383
722  0.8180  0.9786  0.6372  1.3497  0.24550
723  0.7913  0.9198  0.6251  1.3356  0.24484
724  0.8404  0.9519  0.6362  1.3478  0.24587

[725 rows x 5 columns]
IOTA    0.245343
ICX     0.215229
XRP     0.337250
ADA     0.339045
XLM     0.735221
Name: 516, dtype: float64
報酬 0.3744174144063006 %
i= IOTA    0.245343
ICX     0.215229
XRP     0.337250
ADA     0.339045
XLM     0.735221
Name: 516, dtype: float64
牛式===============================
執行第 523
           523
LTC  -0.072668
ALGO  0.031874
BNB   0.032360
ZIL   0.043292
TRX   0.059774
ATOM  0.062376
VET   0.101555
BAT   0.178195
LINK  0.190162
ETH   0.204953
ICX   0.215229
IOTA  0.245343
ZRX   0.335608
XRP   0.337250
ADA   0.339045
QTUM  0.352286
BCH   0.483725
NEO   0.526338
ZEC   0.598078
XLM   0.735221
g================================================================       QTUM     BCH     NEO     ZEC      XLM
0      NaN     NaN     NaN     NaN      NaN
1      NaN     NaN     NaN     NaN      NaN
2      NaN     NaN     NaN     NaN      NaN
3      NaN     NaN     NaN     NaN      NaN
4      NaN     NaN     NaN     NaN      NaN
..     ...     ...     ...     ...      ...
720  7.079  509.55  37.005  118.51  0.25677
721  6.504  490.60  34.083  109.38  0.24383
722  6.776  504.08  34.637  110.99  0.24550
723  6.639  497.02  34.057  108.15  0.24484
724  6.694  498.00  34.191  110.82  0.24587

[725 rows x 5 columns]
QTUM    0.108346
BCH     0.141399
NEO     0.403081
ZEC     0.479062
XLM     0.401376
Name: 517, dtype: float64
報酬 0.3066526971115282 %
i= QTUM    0.108346
BCH     0.141399
NEO     0.403081
ZEC     0.479062
XLM     0.401376
Name: 517, dtype: float64
牛式===============================
執行第 524
           524
VET  -0.128208
ALGO -0.127873
BNB  -0.086624
ATOM -0.078077
ZIL  -0.072274
ZRX  -0.017098
ETH  -0.011361
BAT  -0.003028
LINK  0.008953
TRX   0.014727
LTC   0.030132
IOTA  0.046346
ADA   0.067252
QTUM  0.108346
ICX   0.112617
BCH   0.141399
XRP   0.276072
XLM   0.401376
NEO   0.403081
ZEC   0.479062
g================================================================         BCH     XRP      XLM     NEO     ZEC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  509.55  0.6521  0.25677  37.005  118.51
721  490.60  0.6236  0.24383  34.083  109.38
722  504.08  0.6372  0.24550  34.637  110.99
723  497.02  0.6251  0.24484  34.057  108.15
724  498.00  0.6362  0.24587  34.191  110.82

[725 rows x 5 columns]
BCH   -0.003463
XRP    0.175811
XLM   -0.173062
NEO    0.134648
ZEC    0.554356
Name: 518, dtype: float64
報酬 0.13765818659116708 %
i= BCH   -0.003463
XRP    0.175811
XLM   -0.173062
NEO    0.134648
ZEC    0.554356
Name: 518, dtype: float64
牛式===============================
執行第 525
           525
VET  -0.258498
ALGO -0.220332
ZIL  -0.201106
LINK -0.190145
XLM  -0.173062
ATOM -0.145680
ADA  -0.131710
ETH  -0.131154
BNB  -0.094223
ICX  -0.092084
QTUM -0.088616
BAT  -0.075170
ZRX  -0.072451
TRX  -0.060079
IOTA -0.057990
LTC  -0.026163
BCH  -0.003463
NEO   0.134648
XRP   0.175811
ZEC   0.554356
g================================================================         LTC     BCH     NEO     XRP     ZEC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  137.39  509.55  37.005  0.6521  118.51
721  132.25  490.60  34.083  0.6236  109.38
722  134.42  504.08  34.637  0.6372  110.99
723  134.00  497.02  34.057  0.6251  108.15
724  134.19  498.00  34.191  0.6362  110.82

[725 rows x 5 columns]
LTC    0.011456
BCH    0.106302
NEO    0.111446
XRP   -0.054580
ZEC    0.730866
Name: 519, dtype: float64
報酬 0.18109812102133416 %
i= LTC    0.011456
BCH    0.106302
NEO    0.111446
XRP   -0.054580
ZEC    0.730866
Name: 519, dtype: float64
牛式===============================
執行第 526
           526
VET  -0.087683
BNB  -0.080871
ETH  -0.075364
ZIL  -0.071532
XRP  -0.054580
XLM  -0.027748
BAT  -0.026521
ALGO -0.023220
TRX  -0.007113
LINK -0.003750
ATOM -0.003353
LTC   0.011456
QTUM  0.020422
ADA   0.050311
IOTA  0.085707
ICX   0.093652
BCH   0.106302
NEO   0.111446
ZRX   0.155074
ZEC   0.730866
g================================================================         ICX     BCH     NEO     ZRX     ZEC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.9279  509.55  37.005  0.7889  118.51
721  1.0350  490.60  34.083  0.8190  109.38
722  0.9786  504.08  34.637  0.8384  110.99
723  0.9198  497.02  34.057  0.7890  108.15
724  0.9519  498.00  34.191  0.7950  110.82

[725 rows x 5 columns]
ICX   -0.043796
BCH    0.209476
NEO    0.169035
ZRX    0.143831
ZEC    0.631433
Name: 520, dtype: float64
報酬 0.22199593969459594 %
i= ICX   -0.043796
BCH    0.209476
NEO    0.169035
ZRX    0.143831
ZEC    0.631433
Name: 520, dtype: float64
牛式===============================
執行第 527
           527
LTC  -0.079850
XRP  -0.075480
ZIL  -0.058775
VET  -0.054141
ICX  -0.043796
BAT  -0.017921
BNB  -0.010631
TRX  -0.009198
ALGO  0.002418
ETH   0.014871
XLM   0.023034
ADA   0.028606
QTUM  0.055944
ATOM  0.092996
ZRX   0.143831
IOTA  0.151909
NEO   0.169035
LINK  0.178478
BCH   0.209476
ZEC   0.631433
g================================================================        IOTA     NEO   LINK     BCH     ZEC
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  0.8896  37.005  19.79  509.55  118.51
721  0.8165  34.083  18.44  490.60  109.38
722  0.8180  34.637  18.66  504.08  110.99
723  0.7913  34.057  18.20  497.02  108.15
724  0.8404  34.191  18.38  498.00  110.82

[725 rows x 5 columns]
IOTA    0.001390
NEO     0.100994
LINK    0.185080
BCH    -0.145364
ZEC     0.315984
Name: 521, dtype: float64
報酬 0.0916165403191737 %
i= IOTA    0.001390
NEO     0.100994
LINK    0.185080
BCH    -0.145364
ZEC     0.315984
Name: 521, dtype: float64
牛式===============================
執行第 528
           528
BCH  -0.145364
XRP  -0.135182
ZIL  -0.125544
VET  -0.122033
TRX  -0.119527
ICX  -0.106215
BAT  -0.099089
QTUM -0.087388
XLM  -0.083607
ADA  -0.082952
ETH  -0.081022
LTC  -0.078408
BNB  -0.065967
ZRX  -0.047768
IOTA  0.001390
ALGO  0.005363
NEO   0.100994
LINK  0.185080
ATOM  0.208652
ZEC   0.315984
g================================================================        ALGO     NEO   LINK    ATOM     ZEC
0       NaN     NaN    NaN     NaN     NaN
1       NaN     NaN    NaN     NaN     NaN
2       NaN     NaN    NaN     NaN     NaN
3       NaN     NaN    NaN     NaN     NaN
4       NaN     NaN    NaN     NaN     NaN
..      ...     ...    ...     ...     ...
720  0.9062  37.005  19.79  12.946  118.51
721  0.8683  34.083  18.44  11.958  109.38
722  0.9059  34.637  18.66  13.182  110.99
723  0.8918  34.057  18.20  14.395  108.15
724  0.8952  34.191  18.38  14.064  110.82

[725 rows x 5 columns]
ALGO    0.124429
NEO    -0.054931
LINK    0.243060
ATOM    0.405700
ZEC     0.121812
Name: 522, dtype: float64
報酬 0.16801409515329174 %
i= ALGO    0.124429
NEO    -0.054931
LINK    0.243060
ATOM    0.405700
ZEC     0.121812
Name: 522, dtype: float64
牛式===============================
執行第 529
           529
BCH  -0.185481
XRP  -0.113205
QTUM -0.100559
TRX  -0.082012
NEO  -0.054931
ETH  -0.021986
VET  -0.009543
IOTA -0.006544
ZRX  -0.001892
LTC  -0.001399
ZIL   0.005752
BNB   0.015791
XLM   0.021192
BAT   0.036159
ICX   0.040302
ZEC   0.121812
ALGO  0.124429
ADA   0.158439
LINK  0.243060
ATOM  0.405700
g================================================================         ZEC    ALGO     ADA   LINK    ATOM
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  118.51  0.9062  1.4039  19.79  12.946
721  109.38  0.8683  1.3327  18.44  11.958
722  110.99  0.9059  1.3497  18.66  13.182
723  108.15  0.8918  1.3356  18.20  14.395
724  110.82  0.8952  1.3478  18.38  14.064

[725 rows x 5 columns]
ZEC     0.157758
ALGO    0.407523
ADA     0.381926
LINK    0.591809
ATOM    0.494663
Name: 523, dtype: float64
報酬 0.40673560335619285 %
i= ZEC     0.157758
ALGO    0.407523
ADA     0.381926
LINK    0.591809
ATOM    0.494663
Name: 523, dtype: float64
牛式===============================

執行第 530
           530
XRP  -0.035229
LTC  -0.028738
BCH   0.003958
NEO   0.006798
TRX   0.043884
ICX   0.087887
QTUM  0.098446
VET   0.117790
XLM   0.120862
ZIL   0.127996
ETH   0.135192
ZEC   0.157758
IOTA  0.183967
BAT   0.186985
BNB   0.202515
ZRX   0.361639
ADA   0.381926
ALGO  0.407523
ATOM  0.494663
LINK  0.591809
g================================================================         ZRX     ADA    ALGO    ATOM   LINK
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  0.7889  1.4039  0.9062  12.946  19.79
721  0.8190  1.3327  0.8683  11.958  18.44
722  0.8384  1.3497  0.9059  13.182  18.66
723  0.7890  1.3356  0.8918  14.395  18.20
724  0.7950  1.3478  0.8952  14.064  18.38

[725 rows x 5 columns]
ZRX     0.367399
ADA     0.284409
ALGO    0.421264
ATOM    0.671399
LINK    0.578382
Name: 524, dtype: float64
報酬 0.464570551335878 %
i= ZRX     0.367399
ADA     0.284409
ALGO    0.421264
ATOM    0.671399
LINK    0.578382
Name: 524, dtype: float64
牛式===============================
執行第 531
           531
XRP  -0.024339
ZEC   0.045889
LTC   0.051097
XLM   0.087031
TRX   0.104785
BCH   0.127476
BNB   0.185572
ETH   0.198286
QTUM  0.200655
NEO   0.221405
BAT   0.222222
ZIL   0.268147
ADA   0.284409
ICX   0.309896
IOTA  0.330084
VET   0.347213
ZRX   0.367399
ALGO  0.421264
LINK  0.578382
ATOM  0.671399
g================================================================          VET     ZRX    ALGO   LINK    ATOM
0        NaN     NaN     NaN    NaN     NaN
1        NaN     NaN     NaN    NaN     NaN
2        NaN     NaN     NaN    NaN     NaN
3        NaN     NaN     NaN    NaN     NaN
4        NaN     NaN     NaN    NaN     NaN
..       ...     ...     ...    ...     ...
720  0.08348  0.7889  0.9062  19.79  12.946
721  0.07614  0.8190  0.8683  18.44  11.958
722  0.07704  0.8384  0.9059  18.66  13.182
723  0.07591  0.7890  0.8918  18.20  14.395
724  0.07768  0.7950  0.8952  18.38  14.064

[725 rows x 5 columns]
VET     0.115999
ZRX     0.066535
ALGO    0.157965
LINK    0.289210
ATOM    0.425985
Name: 525, dtype: float64
報酬 0.21113879431502597 %
i= VET     0.115999
ZRX     0.066535
ALGO    0.157965
LINK    0.289210
ATOM    0.425985
Name: 525, dtype: float64
牛式===============================
執行第 532
           532
ZEC  -0.127631
XRP  -0.036470
XLM  -0.016873
TRX  -0.002605
BCH   0.021416
ZIL   0.046482
BNB   0.062313
ZRX   0.066535
QTUM  0.070896
BAT   0.075321
LTC   0.096448
ICX   0.109233
VET   0.115999
IOTA  0.132371
NEO   0.135489
ALGO  0.157965
ADA   0.176350
ETH   0.211693
LINK  0.289210
ATOM  0.425985
g================================================================        ALGO     ADA      ETH   LINK    ATOM
0       NaN     NaN      NaN    NaN     NaN
1       NaN     NaN      NaN    NaN     NaN
2       NaN     NaN      NaN    NaN     NaN
3       NaN     NaN      NaN    NaN     NaN
4       NaN     NaN      NaN    NaN     NaN
..      ...     ...      ...    ...     ...
720  0.9062  1.4039  2316.15  19.79  12.946
721  0.8683  1.3327  2121.52  18.44  11.958
722  0.9059  1.3497  2146.27  18.66  13.182
723  0.8918  1.3356  2111.19  18.20  14.395
724  0.8952  1.3478  2138.86  18.38  14.064

[725 rows x 5 columns]
ALGO    0.201096
ADA     0.200396
ETH     0.116423
LINK    0.218263
ATOM    0.375695
Name: 526, dtype: float64
報酬 0.22237476187192345 %
i= ALGO    0.201096
ADA     0.200396
ETH     0.116423
LINK    0.218263
ATOM    0.375695
Name: 526, dtype: float64
牛式===============================
執行第 533
           533
ZEC  -0.116175
BCH  -0.058754
XLM  -0.034333
XRP  -0.004011
TRX   0.010942
BNB   0.016476
QTUM  0.071854
ZIL   0.073602
IOTA  0.106958
ZRX   0.108860
ETH   0.116423
NEO   0.127682
BAT   0.129765
ADA   0.200396
ALGO  0.201096
LINK  0.218263
LTC   0.240768
ICX   0.331895
VET   0.342899
ATOM  0.375695
g================================================================       LINK     LTC     ICX      VET    ATOM
0      NaN     NaN     NaN      NaN     NaN
1      NaN     NaN     NaN      NaN     NaN
2      NaN     NaN     NaN      NaN     NaN
3      NaN     NaN     NaN      NaN     NaN
4      NaN     NaN     NaN      NaN     NaN
..     ...     ...     ...      ...     ...
720  19.79  137.39  0.9279  0.08348  12.946
721  18.44  132.25  1.0350  0.07614  11.958
722  18.66  134.42  0.9786  0.07704  13.182
723  18.20  134.00  0.9198  0.07591  14.395
724  18.38  134.19  0.9519  0.07768  14.064

[725 rows x 5 columns]
LINK   -0.114849
LTC     0.203418
ICX     0.140222
VET     0.104582
ATOM   -0.094600
Name: 527, dtype: float64
報酬 0.04775467665288482 %
i= LINK   -0.114849
LTC     0.203418
ICX     0.140222
VET     0.104582
ATOM   -0.094600
Name: 527, dtype: float64
牛式===============================
執行第 534
           534
ZEC  -0.198337
BCH  -0.149273
XLM  -0.117790
LINK -0.114849
ZRX  -0.101104
ATOM -0.094600
TRX  -0.072581
QTUM -0.070289
ZIL  -0.062283
NEO  -0.057804
BNB  -0.054497
ALGO -0.054165
ETH  -0.046164
XRP  -0.043402
IOTA -0.030296
BAT  -0.014153
ADA   0.016657
VET   0.104582
ICX   0.140222
LTC   0.203418
g================================================================         BAT     ADA      VET     ICX     LTC
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  0.6135  1.4039  0.08348  0.9279  137.39
721  0.5691  1.3327  0.07614  1.0350  132.25
722  0.5695  1.3497  0.07704  0.9786  134.42
723  0.5575  1.3356  0.07591  0.9198  134.00
724  0.5623  1.3478  0.07768  0.9519  134.19

[725 rows x 5 columns]
BAT    0.180488
ADA   -0.001056
VET    0.165402
ICX    0.069613
LTC    0.085829
Name: 528, dtype: float64
報酬 0.10005510941857065 %
i= BAT    0.180488
ADA   -0.001056
VET    0.165402
ICX    0.069613
LTC    0.085829
Name: 528, dtype: float64
牛式===============================
執行第 535
           535
ZEC  -0.195361
ATOM -0.112674
BCH  -0.100167
ZIL  -0.077614
XLM  -0.072496
BNB  -0.051740
TRX  -0.051478
QTUM -0.044132
ZRX  -0.032607
XRP  -0.025181
ALGO -0.014510
NEO  -0.005761
ADA  -0.001056
ETH   0.005048
ICX   0.069613
IOTA  0.071513
LINK  0.073945
LTC   0.085829
VET   0.165402
BAT   0.180488
g================================================================        IOTA   LINK     LTC      VET     BAT
0       NaN    NaN     NaN      NaN     NaN
1       NaN    NaN     NaN      NaN     NaN
2       NaN    NaN     NaN      NaN     NaN
3       NaN    NaN     NaN      NaN     NaN
4       NaN    NaN     NaN      NaN     NaN
..      ...    ...     ...      ...     ...
720  0.8896  19.79  137.39  0.08348  0.6135
721  0.8165  18.44  132.25  0.07614  0.5691
722  0.8180  18.66  134.42  0.07704  0.5695
723  0.7913  18.20  134.00  0.07591  0.5575
724  0.8404  18.38  134.19  0.07768  0.5623

[725 rows x 5 columns]
IOTA    0.034198
LINK    0.063036
LTC     0.105671
VET     0.105120
BAT     0.204678
Name: 529, dtype: float64
報酬 0.10254062849373091 %
i= IOTA    0.034198
LINK    0.063036
LTC     0.105671
VET     0.105120
BAT     0.204678
Name: 529, dtype: float64
牛式===============================
執行第 536
           536
ZEC  -0.159542
XLM  -0.111649
BNB  -0.108497
BCH  -0.100701
ADA  -0.093295
ZIL  -0.076148
ALGO -0.053106
ZRX  -0.052614
TRX  -0.032440
ATOM -0.024936
XRP  -0.020727
ETH  -0.000438
NEO   0.025246
IOTA  0.034198
LINK  0.063036
ICX   0.102118
VET   0.105120
LTC   0.105671
BAT   0.204678
QTUM  0.232390
g================================================================         ICX      VET     LTC     BAT   QTUM
0       NaN      NaN     NaN     NaN    NaN
1       NaN      NaN     NaN     NaN    NaN
2       NaN      NaN     NaN     NaN    NaN
3       NaN      NaN     NaN     NaN    NaN
4       NaN      NaN     NaN     NaN    NaN
..      ...      ...     ...     ...    ...
720  0.9279  0.08348  137.39  0.6135  7.079
721  1.0350  0.07614  132.25  0.5691  6.504
722  0.9786  0.07704  134.42  0.5695  6.776
723  0.9198  0.07591  134.00  0.5575  6.639
724  0.9519  0.07768  134.19  0.5623  6.694

[725 rows x 5 columns]
ICX     0.021605
VET    -0.004745
LTC    -0.013197
BAT     0.126282
QTUM    0.075220
Name: 530, dtype: float64
報酬 0.04103292337026119 %
i= ICX     0.021605
VET    -0.004745
LTC    -0.013197
BAT     0.126282
QTUM    0.075220
Name: 530, dtype: float64
牛式===============================
執行第 537
           537
BCH  -0.137776
ATOM -0.136940
ZEC  -0.134225
ZIL  -0.124001
XLM  -0.111675
NEO  -0.098415
BNB  -0.077822
ZRX  -0.062254
TRX  -0.052166
ADA  -0.048216
IOTA -0.045236
XRP  -0.042781
LTC  -0.013197
ALGO -0.008821
VET  -0.004745
ICX   0.021605
QTUM  0.075220
ETH   0.104626
LINK  0.122902
BAT   0.126282
g================================================================         ICX   QTUM      ETH   LINK     BAT
0       NaN    NaN      NaN    NaN     NaN
1       NaN    NaN      NaN    NaN     NaN
2       NaN    NaN      NaN    NaN     NaN
3       NaN    NaN      NaN    NaN     NaN
4       NaN    NaN      NaN    NaN     NaN
..      ...    ...      ...    ...     ...
720  0.9279  7.079  2316.15  19.79  0.6135
721  1.0350  6.504  2121.52  18.44  0.5691
722  0.9786  6.776  2146.27  18.66  0.5695
723  0.9198  6.639  2111.19  18.20  0.5575
724  0.9519  6.694  2138.86  18.38  0.5623

[725 rows x 5 columns]
ICX     0.163025
QTUM    0.040228
ETH    -0.039672
LINK    0.136253
BAT     0.122951
Name: 531, dtype: float64
報酬 0.08455692816913526 %
i= ICX     0.163025
QTUM    0.040228
ETH    -0.039672
LINK    0.136253
BAT     0.122951
Name: 531, dtype: float64
牛式===============================
執行第 538
           538
BCH  -0.146332
ZEC  -0.141713
ATOM -0.130322
XLM  -0.125972
NEO  -0.115834
ZIL  -0.092502
XRP  -0.091792
IOTA -0.081403
ADA  -0.067440
LTC  -0.057442
ETH  -0.039672
TRX  -0.037218
ZRX  -0.036098
BNB  -0.019709
VET   0.021839
QTUM  0.040228
ALGO  0.066961
BAT   0.122951
LINK  0.136253
ICX   0.163025
g================================================================       QTUM    ALGO     BAT   LINK     ICX
0      NaN     NaN     NaN    NaN     NaN
1      NaN     NaN     NaN    NaN     NaN
2      NaN     NaN     NaN    NaN     NaN
3      NaN     NaN     NaN    NaN     NaN
4      NaN     NaN     NaN    NaN     NaN
..     ...     ...     ...    ...     ...
720  7.079  0.9062  0.6135  19.79  0.9279
721  6.504  0.8683  0.5691  18.44  1.0350
722  6.776  0.9059  0.5695  18.66  0.9786
723  6.639  0.8918  0.5575  18.20  0.9198
724  6.694  0.8952  0.5623  18.38  0.9519

[725 rows x 5 columns]
QTUM    0.060550
ALGO    0.097316
BAT     0.074300
LINK    0.056216
ICX     0.112634
Name: 532, dtype: float64
報酬 0.08020313488224903 %
i= QTUM    0.060550
ALGO    0.097316
BAT     0.074300
LINK    0.056216
ICX     0.112634
Name: 532, dtype: float64
牛式===============================
執行第 539
           539
VET  -0.149359
BCH  -0.139690
ATOM -0.131440
NEO  -0.111269
XLM  -0.108058
LTC  -0.099554
ZEC  -0.097270
XRP  -0.091549
ADA  -0.085135
ZIL  -0.084345
IOTA -0.080484
TRX  -0.033126
ZRX  -0.027589
BNB  -0.019967
ETH  -0.008617
LINK  0.056216
QTUM  0.060550
BAT   0.074300
ALGO  0.097316
ICX   0.112634
g================================================================       LINK   QTUM     BAT    ALGO     ICX
0      NaN    NaN     NaN     NaN     NaN
1      NaN    NaN     NaN     NaN     NaN
2      NaN    NaN     NaN     NaN     NaN
3      NaN    NaN     NaN     NaN     NaN
4      NaN    NaN     NaN     NaN     NaN
..     ...    ...     ...     ...     ...
720  19.79  7.079  0.6135  0.9062  0.9279
721  18.44  6.504  0.5691  0.8683  1.0350
722  18.66  6.776  0.5695  0.9059  0.9786
723  18.20  6.639  0.5575  0.8918  0.9198
724  18.38  6.694  0.5623  0.8952  0.9519

[725 rows x 5 columns]
LINK    0.137894
QTUM    0.136596
BAT     0.242002
ALGO    0.173536
ICX     0.145455
Name: 533, dtype: float64
報酬 0.16709632546706238 %
i= LINK    0.137894
QTUM    0.136596
BAT     0.242002
ALGO    0.173536
ICX     0.145455
Name: 533, dtype: float64
牛式===============================
執行第 540
           540
BCH  -0.096845
XRP  -0.065466
IOTA -0.064870
VET  -0.055915
ZEC  -0.053438
LTC  -0.052680
XLM  -0.051469
NEO  -0.047888
ATOM -0.027378
ZIL  -0.001930
ADA   0.014336
TRX   0.023551
BNB   0.059188
ETH   0.117172
QTUM  0.136596
LINK  0.137894
ICX   0.145455
ALGO  0.173536
BAT   0.242002
ZRX   0.258780
g================================================================       LINK     ICX    ALGO     BAT     ZRX
0      NaN     NaN     NaN     NaN     NaN
1      NaN     NaN     NaN     NaN     NaN
2      NaN     NaN     NaN     NaN     NaN
3      NaN     NaN     NaN     NaN     NaN
4      NaN     NaN     NaN     NaN     NaN
..     ...     ...     ...     ...     ...
720  19.79  0.9279  0.9062  0.6135  0.7889
721  18.44  1.0350  0.8683  0.5691  0.8190
722  18.66  0.9786  0.9059  0.5695  0.8384
723  18.20  0.9198  0.8918  0.5575  0.7890
724  18.38  0.9519  0.8952  0.5623  0.7950

[725 rows x 5 columns]
LINK    0.061460
ICX     0.152660
ALGO    0.097369
BAT    -0.028608
ZRX     0.189300
Name: 534, dtype: float64
報酬 0.09443644883545814 %
i= LINK    0.061460
ICX     0.152660
ALGO    0.097369
BAT    -0.028608
ZRX     0.189300
Name: 534, dtype: float64
牛式===============================
執行第 541
           541
VET  -0.125327
IOTA -0.113502
BCH  -0.082859
LTC  -0.059526
NEO  -0.053006
ZIL  -0.034396
XRP  -0.030895
BAT  -0.028608
ADA  -0.017257
ZEC  -0.003905
ATOM  0.001498
TRX   0.035714
BNB   0.039393
LINK  0.061460
ETH   0.075171
XLM   0.085571
ALGO  0.097369
QTUM  0.120041
ICX   0.152660
ZRX   0.189300
g================================================================          XLM    ALGO   QTUM     ICX     ZRX
0        NaN     NaN    NaN     NaN     NaN
1        NaN     NaN    NaN     NaN     NaN
2        NaN     NaN    NaN     NaN     NaN
3        NaN     NaN    NaN     NaN     NaN
4        NaN     NaN    NaN     NaN     NaN
..       ...     ...    ...     ...     ...
720  0.25677  0.9062  7.079  0.9279  0.7889
721  0.24383  0.8683  6.504  1.0350  0.8190
722  0.24550  0.9059  6.776  0.9786  0.8384
723  0.24484  0.8918  6.639  0.9198  0.7890
724  0.24587  0.8952  6.694  0.9519  0.7950

[725 rows x 5 columns]
XLM     0.086320
ALGO    0.143987
QTUM   -0.156417
ICX     0.101579
ZRX     0.066182
Name: 535, dtype: float64
報酬 0.04832997643066848 %
i= XLM     0.086320
ALGO    0.143987
QTUM   -0.156417
ICX     0.101579
ZRX     0.066182
Name: 535, dtype: float64
牛式===============================
執行第 542
           542
QTUM -0.156417
IOTA -0.084554
LINK -0.083098
NEO  -0.076656
LTC  -0.074546
VET  -0.073121
BAT  -0.062500
BCH  -0.055849
ATOM -0.041902
ZIL  -0.008257
ZEC  -0.005121
ADA   0.004830
XRP   0.040969
BNB   0.047654
ZRX   0.066182
XLM   0.086320
ICX   0.101579
ETH   0.118617
TRX   0.141293
ALGO  0.143987

g================================================================          XLM     ICX      ETH      TRX    ALGO
0        NaN     NaN      NaN      NaN     NaN
1        NaN     NaN      NaN      NaN     NaN
2        NaN     NaN      NaN      NaN     NaN
3        NaN     NaN      NaN      NaN     NaN
4        NaN     NaN      NaN      NaN     NaN
..       ...     ...      ...      ...     ...
720  0.25677  0.9279  2316.15  0.06432  0.9062
721  0.24383  1.0350  2121.52  0.06111  0.8683
722  0.24550  0.9786  2146.27  0.06219  0.9059
723  0.24484  0.9198  2111.19  0.06139  0.8918
724  0.24587  0.9519  2138.86  0.06184  0.8952

[725 rows x 5 columns]
XLM     0.211159
ICX     0.005517
ETH    -0.009663
TRX     0.073049
ALGO    0.182449
Name: 536, dtype: float64
報酬 0.09250218341730218 %
i= XLM     0.211159
ICX     0.005517
ETH    -0.009663
TRX     0.073049
ALGO    0.182449
Name: 536, dtype: float64
牛式===============================
執行第 543
           543
VET  -0.122979
QTUM -0.069958
NEO  -0.063535
ZEC  -0.060791
IOTA -0.058346
BCH  -0.051086
LTC  -0.050279
LINK -0.045638
ATOM -0.021140
ETH  -0.009663
BAT  -0.007852
ICX   0.005517
ADA   0.030384
ZIL   0.060127
BNB   0.070045
TRX   0.073049
ALGO  0.182449
ZRX   0.190954
XLM   0.211159
XRP   0.622438
g================================================================          TRX    ALGO     ZRX      XLM     XRP
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.06432  0.9062  0.7889  0.25677  0.6521
721  0.06111  0.8683  0.8190  0.24383  0.6236
722  0.06219  0.9059  0.8384  0.24550  0.6372
723  0.06139  0.8918  0.7890  0.24484  0.6251
724  0.06184  0.8952  0.7950  0.24587  0.6362

[725 rows x 5 columns]
TRX     0.069854
ALGO    0.172451
ZRX     0.357788
XLM     0.175884
XRP     0.849817
Name: 537, dtype: float64
報酬 0.32515873034416765 %
i= TRX     0.069854
ALGO    0.172451
ZRX     0.357788
XLM     0.175884
XRP     0.849817
Name: 537, dtype: float64
牛式===============================
執行第 544
           544
VET  -0.146078
ICX  -0.109889
BCH  -0.075555
IOTA -0.056687
LTC  -0.047493
NEO  -0.044727
LINK -0.033405
ZEC  -0.025376
ETH  -0.003833
QTUM -0.001523
BAT   0.004645
ADA   0.005159
ZIL   0.033827
ATOM  0.052060
BNB   0.061034
TRX   0.069854
ALGO  0.172451
XLM   0.175884
ZRX   0.357788
XRP   0.849817
g================================================================          TRX    ALGO      XLM     ZRX     XRP
0        NaN     NaN      NaN     NaN     NaN
1        NaN     NaN      NaN     NaN     NaN
2        NaN     NaN      NaN     NaN     NaN
3        NaN     NaN      NaN     NaN     NaN
4        NaN     NaN      NaN     NaN     NaN
..       ...     ...      ...     ...     ...
720  0.06432  0.9062  0.25677  0.7889  0.6521
721  0.06111  0.8683  0.24383  0.8190  0.6236
722  0.06219  0.9059  0.24550  0.8384  0.6372
723  0.06139  0.8918  0.24484  0.7890  0.6251
724  0.06184  0.8952  0.24587  0.7950  0.6362

[725 rows x 5 columns]
TRX     0.118385
ALGO    0.071714
XLM     0.235802
ZRX     0.264738
XRP     0.384360
Name: 538, dtype: float64
報酬 0.21500001333926325 %
i= TRX     0.118385
ALGO    0.071714
XLM     0.235802
ZRX     0.264738
XRP     0.384360
Name: 538, dtype: float64
牛式===============================
執行第 545
           545
ICX  -0.140538
LTC  -0.058668
IOTA -0.038337
BCH  -0.031029
LINK -0.009520
ZEC  -0.007504
NEO  -0.003539
VET  -0.002478
ETH   0.005389
QTUM  0.009904
BAT   0.059806
ALGO  0.071714
ZIL   0.105969
TRX   0.118385
ADA   0.188124
ATOM  0.199793
BNB   0.232263
XLM   0.235802
ZRX   0.264738
XRP   0.384360
g================================================================        ATOM     BNB      XLM     ZRX     XRP
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  12.946  327.67  0.25677  0.7889  0.6521
721  11.958  310.59  0.24383  0.8190  0.6236
722  13.182  316.72  0.24550  0.8384  0.6372
723  14.395  316.09  0.24484  0.7890  0.6251
724  14.064  321.87  0.24587  0.7950  0.6362

[725 rows x 5 columns]
ATOM    0.278472
BNB     0.244265
XLM     0.423588
ZRX     0.169120
XRP     0.484302
Name: 539, dtype: float64
報酬 0.3199494827511099 %
i= ATOM    0.278472
BNB     0.244265
XLM     0.423588
ZRX     0.169120
XRP     0.484302
Name: 539, dtype: float64
牛式===============================
執行第 546
           546
ICX  -0.014373
LTC   0.013217
BAT   0.047226
VET   0.062822
IOTA  0.096149
NEO   0.126453
LINK  0.130248
QTUM  0.138496
BCH   0.139513
ZRX   0.169120
TRX   0.174513
ZEC   0.176628
ALGO  0.203697
ETH   0.209758
BNB   0.244265
ZIL   0.252175
ATOM  0.278472
ADA   0.364260
XLM   0.423588
XRP   0.484302
g================================================================          ZIL    ATOM     ADA      XLM     XRP
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  0.08133  12.946  1.4039  0.25677  0.6521
721  0.07509  11.958  1.3327  0.24383  0.6236
722  0.07496  13.182  1.3497  0.24550  0.6372
723  0.07299  14.395  1.3356  0.24484  0.6251
724  0.07377  14.064  1.3478  0.24587  0.6362

[725 rows x 5 columns]
ZIL     0.217398
ATOM    0.159581
ADA     0.284917
XLM     0.179935
XRP     0.503938
Name: 540, dtype: float64
報酬 0.26915373411214205 %
i= ZIL     0.217398
ATOM    0.159581
ADA     0.284917
XLM     0.179935
XRP     0.503938
Name: 540, dtype: float64
牛式===============================
執行第 547
           547
ICX  -0.009083
LTC   0.044940
BAT   0.053665
VET   0.064927
LINK  0.091424
ZEC   0.097429
BCH   0.103029
NEO   0.109606
IOTA  0.122338
QTUM  0.128550
ATOM  0.159581
TRX   0.167343
XLM   0.179935
ZIL   0.217398
BNB   0.226930
ETH   0.254210
ZRX   0.261822
ADA   0.284917
ALGO  0.330054
XRP   0.503938
g================================================================          ETH     ZRX     ADA    ALGO     XRP
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  0.7889  1.4039  0.9062  0.6521
721  2121.52  0.8190  1.3327  0.8683  0.6236
722  2146.27  0.8384  1.3497  0.9059  0.6372
723  2111.19  0.7890  1.3356  0.8918  0.6251
724  2138.86  0.7950  1.3478  0.8952  0.6362

[725 rows x 5 columns]
ETH     0.157895
ZRX     0.721751
ADA     0.264894
ALGO    0.109365
XRP     0.570050
Name: 541, dtype: float64
報酬 0.3647907857845819 %
i= ETH     0.157895
ZRX     0.721751
ADA     0.264894
ALGO    0.109365
XRP     0.570050
Name: 541, dtype: float64
牛式===============================
執行第 548
           548
ICX  -0.050093
TRX  -0.007194
VET  -0.005207
BAT   0.011650
BCH   0.034047
NEO   0.052452
ZEC   0.052878
QTUM  0.060496
IOTA  0.069091
LINK  0.077871
LTC   0.078830
ALGO  0.109365
XLM   0.111191
ZIL   0.134850
ATOM  0.146867
ETH   0.157895
ADA   0.264894
BNB   0.304409
XRP   0.570050
ZRX   0.721751
g================================================================          ETH     ADA     BNB     XRP     ZRX
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  2316.15  1.4039  327.67  0.6521  0.7889
721  2121.52  1.3327  310.59  0.6236  0.8190
722  2146.27  1.3497  316.72  0.6372  0.8384
723  2111.19  1.3356  316.09  0.6251  0.7890
724  2138.86  1.3478  321.87  0.6362  0.7950

[725 rows x 5 columns]
ETH    0.249141
ADA    0.480488
BNB    0.513852
XRP    0.018635
ZRX    1.432312
Name: 542, dtype: float64
報酬 0.538885618662125 %
i= ETH    0.249141
ADA    0.480488
BNB    0.513852
XRP    0.018635
ZRX    1.432312
Name: 542, dtype: float64
牛式===============================
執行第 549
           549
XRP   0.018635
LTC   0.034938
XLM   0.072588
BCH   0.072693
ICX   0.087133
LINK  0.113838
TRX   0.124961
ZIL   0.127921
NEO   0.141119
ZEC   0.141877
QTUM  0.168638
BAT   0.176955
VET   0.193208
IOTA  0.205684
ETH   0.249141
ALGO  0.254253
ADA   0.480488
ATOM  0.512474
BNB   0.513852
ZRX   1.432312
g================================================================        ALGO     ADA    ATOM     BNB     ZRX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.9062  1.4039  12.946  327.67  0.7889
721  0.8683  1.3327  11.958  310.59  0.8190
722  0.9059  1.3497  13.182  316.72  0.8384
723  0.8918  1.3356  14.395  316.09  0.7890
724  0.8952  1.3478  14.064  321.87  0.7950

[725 rows x 5 columns]
ALGO    0.240798
ADA     0.838012
ATOM    0.478389
BNB     0.637040
ZRX     1.044554
Name: 543, dtype: float64
報酬 0.6477586420086209 %
i= ALGO    0.240798
ADA     0.838012
ATOM    0.478389
BNB     0.637040
ZRX     1.044554
Name: 543, dtype: float64
牛式===============================
執行第 550
           550
LTC  -0.173640
XRP  -0.105314
ZEC   0.099591
LINK  0.107665
TRX   0.112203
NEO   0.115012
ZIL   0.140437
ICX   0.145952
BCH   0.146924
BAT   0.164795
VET   0.177167
XLM   0.230920
ALGO  0.240798
ETH   0.277230
QTUM  0.347972
IOTA  0.380427
ATOM  0.478389
BNB   0.637040
ADA   0.838012
ZRX   1.044554
g================================================================        IOTA    ATOM     BNB     ADA     ZRX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.8896  12.946  327.67  1.4039  0.7889
721  0.8165  11.958  310.59  1.3327  0.8190
722  0.8180  13.182  316.72  1.3497  0.8384
723  0.7913  14.395  316.09  1.3356  0.7890
724  0.8404  14.064  321.87  1.3478  0.7950

[725 rows x 5 columns]
IOTA    0.341739
ATOM    0.488798
BNB     0.330480
ADA     0.623156
ZRX     1.053751
Name: 544, dtype: float64
報酬 0.5675848913953633 %
i= IOTA    0.341739
ATOM    0.488798
BNB     0.330480
ADA     0.623156
ZRX     1.053751
Name: 544, dtype: float64
牛式===============================
執行第 551
           551
LTC  -0.115520
VET  -0.008406
ZIL   0.012527
ZEC   0.041530
NEO   0.062237
BCH   0.073120
ICX   0.074788
LINK  0.080821
TRX   0.090385
XRP   0.126187
ETH   0.175084
XLM   0.191458
QTUM  0.224690
BAT   0.282472
ALGO  0.310045
BNB   0.330480
IOTA  0.341739
ATOM  0.488798
ADA   0.623156
ZRX   1.053751
g================================================================         BNB    IOTA    ATOM     ADA     ZRX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  327.67  0.8896  12.946  1.4039  0.7889
721  310.59  0.8165  11.958  1.3327  0.8190
722  316.72  0.8180  13.182  1.3497  0.8384
723  316.09  0.7913  14.395  1.3356  0.7890
724  321.87  0.8404  14.064  1.3478  0.7950

[725 rows x 5 columns]
BNB     0.563640
IOTA    0.682178
ATOM    0.590429
ADA     0.598252
ZRX     1.160176
Name: 545, dtype: float64
報酬 0.7189349496594364 %
i= BNB     0.563640
IOTA    0.682178
ATOM    0.590429
ADA     0.598252
ZRX     1.160176
Name: 545, dtype: float64
牛式===============================
執行第 552
           552
LTC  -0.239580
ZIL   0.025222
ZEC   0.063143
ICX   0.071900
LINK  0.073449
VET   0.114514
BCH   0.125872
NEO   0.151559
ETH   0.157637
XLM   0.172690
XRP   0.211170
TRX   0.218505
BAT   0.318196
QTUM  0.336438
ALGO  0.551290
BNB   0.563640
ATOM  0.590429
ADA   0.598252
IOTA  0.682178
ZRX   1.160176
g================================================================         BNB    ATOM     ADA    IOTA     ZRX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  327.67  12.946  1.4039  0.8896  0.7889
721  310.59  11.958  1.3327  0.8165  0.8190
722  316.72  13.182  1.3497  0.8180  0.8384
723  316.09  14.395  1.3356  0.7913  0.7890
724  321.87  14.064  1.3478  0.8404  0.7950

[725 rows x 5 columns]
BNB     1.064658
ATOM    0.618213
ADA     0.597181
IOTA    0.658870
ZRX     0.974406
Name: 546, dtype: float64
報酬 0.7826656844366804 %
i= BNB     1.064658
ATOM    0.618213
ADA     0.597181
IOTA    0.658870
ZRX     0.974406
Name: 546, dtype: float64
牛式===============================
執行第 553
           553
LTC  -0.214051
ETH   0.063945
LINK  0.101715
ZEC   0.142572
BCH   0.153210
XLM   0.157210
ICX   0.165242
XRP   0.199537
VET   0.211522
NEO   0.257573
ZIL   0.317594
TRX   0.331306
BAT   0.346894
QTUM  0.356331
ALGO  0.383591
ADA   0.597181
ATOM  0.618213
IOTA  0.658870
ZRX   0.974406
BNB   1.064658
g================================================================         ADA    ATOM    IOTA     ZRX     BNB
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  1.4039  12.946  0.8896  0.7889  327.67
721  1.3327  11.958  0.8165  0.8190  310.59
722  1.3497  13.182  0.8180  0.8384  316.72
723  1.3356  14.395  0.7913  0.7890  316.09
724  1.3478  14.064  0.8404  0.7950  321.87

[725 rows x 5 columns]
ADA     1.139659
ATOM    0.638221
IOTA    1.009070
ZRX     0.456215
BNB     1.301681
Name: 547, dtype: float64
報酬 0.9089692173649982 %
i= ADA     1.139659
ATOM    0.638221
IOTA    1.009070
ZRX     0.456215
BNB     1.301681
Name: 547, dtype: float64
牛式===============================
執行第 554
           554
LTC  -0.220804
ETH   0.090721
LINK  0.095102
XRP   0.136303
BCH   0.176747
XLM   0.273420
VET   0.290066
ZEC   0.293667
ZIL   0.364470
TRX   0.398551
NEO   0.412889
BAT   0.422585
ZRX   0.456215
ALGO  0.465297
ICX   0.615112
ATOM  0.638221
IOTA  1.009070
ADA   1.139659
QTUM  1.143183
BNB   1.301681
g================================================================        ATOM    IOTA     ADA   QTUM     BNB
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  12.946  0.8896  1.4039  7.079  327.67
721  11.958  0.8165  1.3327  6.504  310.59
722  13.182  0.8180  1.3497  6.776  316.72
723  14.395  0.7913  1.3356  6.639  316.09
724  14.064  0.8404  1.3478  6.694  321.87

[725 rows x 5 columns]
ATOM    0.443214
IOTA    1.272991
ADA     0.724866
QTUM    0.925513
BNB     0.830579
Name: 548, dtype: float64
報酬 0.8394323400005084 %
i= ATOM    0.443214
IOTA    1.272991
ADA     0.724866
QTUM    0.925513
BNB     0.830579
Name: 548, dtype: float64
牛式===============================
執行第 555
           555
LTC  -0.182742
ETH   0.039236
LINK  0.057751
ZRX   0.113266
XRP   0.169963
BCH   0.184626
XLM   0.293298
VET   0.329807
NEO   0.393134
ZIL   0.400097
ATOM  0.443214
ZEC   0.472850
ALGO  0.486198
TRX   0.568113
BAT   0.593868
ICX   0.596251
ADA   0.724866
BNB   0.830579
QTUM  0.925513
IOTA  1.272991
g================================================================         ICX     ADA     BNB   QTUM    IOTA
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  0.9279  1.4039  327.67  7.079  0.8896
721  1.0350  1.3327  310.59  6.504  0.8165
722  0.9786  1.3497  316.72  6.776  0.8180
723  0.9198  1.3356  316.09  6.639  0.7913
724  0.9519  1.3478  321.87  6.694  0.8404

[725 rows x 5 columns]
ICX     0.729762
ADA     0.460099
BNB     0.883285
QTUM    0.660860
IOTA    1.195274
Name: 549, dtype: float64
報酬 0.7858560055931763 %
i= ICX     0.729762
ADA     0.460099
BNB     0.883285
QTUM    0.660860
IOTA    1.195274
Name: 549, dtype: float64
牛式===============================
執行第 556
           556
LTC   0.009283
ETH   0.098026
LINK  0.225600
ZRX   0.247112
BCH   0.255595
XRP   0.375265
XLM   0.404902
ADA   0.460099
ZIL   0.498921
NEO   0.511555
ZEC   0.515927
TRX   0.571673
QTUM  0.660860
ICX   0.729762
ATOM  0.753239
BAT   0.777998
VET   0.828937
BNB   0.883285
ALGO  1.124722
IOTA  1.195274
g================================================================         BAT      VET     BNB    ALGO    IOTA
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.6135  0.08348  327.67  0.9062  0.8896
721  0.5691  0.07614  310.59  0.8683  0.8165
722  0.5695  0.07704  316.72  0.9059  0.8180
723  0.5575  0.07591  316.09  0.8918  0.7913
724  0.5623  0.07768  321.87  0.8952  0.8404

[725 rows x 5 columns]
BAT     0.516716
VET     0.879256
BNB     0.945760
ALGO    0.979972
IOTA    1.345445
Name: 550, dtype: float64
報酬 0.9334296615829973 %
i= BAT     0.516716
VET     0.879256
BNB     0.945760
ALGO    0.979972
IOTA    1.345445
Name: 550, dtype: float64
牛式===============================
執行第 557
           557
LTC  -0.033744
ETH   0.125394
ZRX   0.339386
ADA   0.377547
LINK  0.381568
XLM   0.462014
ATOM  0.463030
BCH   0.499179
XRP   0.512689
BAT   0.516716
TRX   0.663421
NEO   0.731306
QTUM  0.817475
VET   0.879256
ZEC   0.905949
BNB   0.945760
ZIL   0.946170
ICX   0.962420
ALGO  0.979972
IOTA  1.345445
g================================================================         BNB      ZIL     ICX    ALGO    IOTA
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  327.67  0.08133  0.9279  0.9062  0.8896
721  310.59  0.07509  1.0350  0.8683  0.8165
722  316.72  0.07496  0.9786  0.9059  0.8180
723  316.09  0.07299  0.9198  0.8918  0.7913
724  321.87  0.07377  0.9519  0.8952  0.8404

[725 rows x 5 columns]
BNB     0.705632
ZIL     0.670767
ICX     0.733822
ALGO    0.454662
IOTA    0.645505
Name: 551, dtype: float64
報酬 0.642077603095718 %
i= BNB     0.705632
ZIL     0.670767
ICX     0.733822
ALGO    0.454662
IOTA    0.645505
Name: 551, dtype: float64
牛式===============================
執行第 558
           558
LTC   0.024059
ETH   0.029208
ZRX   0.217704
ADA   0.241387
XLM   0.297490
LINK  0.305151
XRP   0.314952
BAT   0.335646
ATOM  0.349626
TRX   0.367054
ALGO  0.454662
QTUM  0.477508
BCH   0.484848
ZEC   0.592604
NEO   0.604287
IOTA  0.645505
ZIL   0.670767
VET   0.673866
BNB   0.705632
ICX   0.733822
g================================================================        IOTA      ZIL      VET     BNB     ICX
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.8896  0.08133  0.08348  327.67  0.9279
721  0.8165  0.07509  0.07614  310.59  1.0350
722  0.8180  0.07496  0.07704  316.72  0.9786
723  0.7913  0.07299  0.07591  316.09  0.9198
724  0.8404  0.07377  0.07768  321.87  0.9519

[725 rows x 5 columns]
IOTA    0.698058
ZIL     0.258006
VET     0.445730
BNB     0.208066
ICX     0.873073
Name: 552, dtype: float64
報酬 0.49658669348461715 %
i= IOTA    0.698058
ZIL     0.258006
VET     0.445730
BNB     0.208066
ICX     0.873073
Name: 552, dtype: float64
牛式===============================
執行第 559
           559
ETH   0.004670
LTC   0.060986
ZRX   0.068452
TRX   0.107461
XRP   0.153648
LINK  0.179218
BNB   0.208066
ADA   0.218929
XLM   0.234468
BAT   0.241181
ZIL   0.258006
QTUM  0.279274
ALGO  0.313211
NEO   0.340728
BCH   0.387175
VET   0.445730
ZEC   0.457287
ATOM  0.490532
IOTA  0.698058
ICX   0.873073
g================================================================          VET     ZEC    ATOM    IOTA     ICX
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08348  118.51  12.946  0.8896  0.9279
721  0.07614  109.38  11.958  0.8165  1.0350
722  0.07704  110.99  13.182  0.8180  0.9786
723  0.07591  108.15  14.395  0.7913  0.9198
724  0.07768  110.82  14.064  0.8404  0.9519

[725 rows x 5 columns]
VET     0.382205
ZEC     0.337456
ATOM    0.679117
IOTA    0.414898
ICX     0.403428
Name: 553, dtype: float64
報酬 0.44342073722440106 %
i= VET     0.382205
ZEC     0.337456
ATOM    0.679117
IOTA    0.414898
ICX     0.403428
Name: 553, dtype: float64
牛式===============================
執行第 560
           560
QTUM -0.147591
ADA  -0.074406
LTC  -0.003276
BNB   0.010799
ETH   0.022234
XRP   0.030504
ZRX   0.050511
TRX   0.121762
XLM   0.170010
LINK  0.193067
NEO   0.221176
BAT   0.250056
ZIL   0.264810
ALGO  0.269696
ZEC   0.337456
VET   0.382205
ICX   0.403428
IOTA  0.414898
BCH   0.424052
ATOM  0.679117
g================================================================          VET     ICX    IOTA     BCH    ATOM
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08348  0.9279  0.8896  509.55  12.946
721  0.07614  1.0350  0.8165  490.60  11.958
722  0.07704  0.9786  0.8180  504.08  13.182
723  0.07591  0.9198  0.7913  497.02  14.395
724  0.07768  0.9519  0.8404  498.00  14.064

[725 rows x 5 columns]
VET     0.201197
ICX     0.480578
IOTA    0.107097
BCH     0.352333
ATOM    0.354751
Name: 554, dtype: float64
報酬 0.29919109518635567 %
i= VET     0.201197
ICX     0.480578
IOTA    0.107097
BCH     0.352333
ATOM    0.354751
Name: 554, dtype: float64
牛式===============================
執行第 561
           561
ZRX  -0.114976
QTUM -0.104057
TRX  -0.074009
ADA  -0.040356
BAT  -0.031556
XRP   0.010885
ETH   0.033949
XLM   0.090542
ALGO  0.104498
IOTA  0.107097
LINK  0.157687
NEO   0.170407
ZEC   0.184620
ZIL   0.188576
VET   0.201197
BNB   0.333280
BCH   0.352333
ATOM  0.354751
ICX   0.480578
LTC   3.997050
g================================================================         BNB     BCH    ATOM     ICX     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  327.67  509.55  12.946  0.9279  137.39
721  310.59  490.60  11.958  1.0350  132.25
722  316.72  504.08  13.182  0.9786  134.42
723  316.09  497.02  14.395  0.9198  134.00
724  321.87  498.00  14.064  0.9519  134.19

[725 rows x 5 columns]
BNB     0.432355
BCH     0.221840
ATOM    0.092946
ICX     0.566905
LTC     3.738503
Name: 555, dtype: float64
報酬 1.010509938101538 %
i= BNB     0.432355
BCH     0.221840
ATOM    0.092946
ICX     0.566905
LTC     3.738503
Name: 555, dtype: float64
牛式===============================
執行第 562
           562
ALGO -0.187620
XRP  -0.128666
ZRX  -0.108116
XLM  -0.064126
QTUM -0.028062
ADA  -0.012459
TRX  -0.006165
VET  -0.005502
BAT   0.009249
ETH   0.053262
LINK  0.056462
ATOM  0.092946
NEO   0.169135
ZIL   0.178199
ZEC   0.182812
IOTA  0.196034
BCH   0.221840
BNB   0.432355
ICX   0.566905
LTC   3.738503
g================================================================        IOTA     BCH     BNB     ICX     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.8896  509.55  327.67  0.9279  137.39
721  0.8165  490.60  310.59  1.0350  132.25
722  0.8180  504.08  316.72  0.9786  134.42
723  0.7913  497.02  316.09  0.9198  134.00
724  0.8404  498.00  321.87  0.9519  134.19

[725 rows x 5 columns]
IOTA    0.134844
BCH     0.078990
BNB     1.500038
ICX     0.404930
LTC     3.858874
Name: 556, dtype: float64
報酬 1.1955350708885224 %

i= IOTA    0.134844
BCH     0.078990
BNB     1.500038
ICX     0.404930
LTC     3.858874
Name: 556, dtype: float64
牛式===============================
執行第 563
           563
ALGO -0.179745
ZRX  -0.175440
XRP  -0.110453
XLM  -0.090028
QTUM -0.060127
VET  -0.022355
BAT  -0.006159
ZIL   0.005545
TRX   0.013880
ADA   0.014342
LINK  0.014628
ZEC   0.027572
ETH   0.077050
BCH   0.078990
NEO   0.126278
ATOM  0.132331
IOTA  0.134844
ICX   0.404930
BNB   1.500038
LTC   3.858874
g================================================================        ATOM    IOTA     ICX     BNB     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  12.946  0.8896  0.9279  327.67  137.39
721  11.958  0.8165  1.0350  310.59  132.25
722  13.182  0.8180  0.9786  316.72  134.42
723  14.395  0.7913  0.9198  316.09  134.00
724  14.064  0.8404  0.9519  321.87  134.19

[725 rows x 5 columns]
ATOM    0.133661
IOTA    0.161049
ICX     0.397926
BNB     0.870799
LTC     3.641062
Name: 557, dtype: float64
報酬 1.0408995387598792 %
i= ATOM    0.133661
IOTA    0.161049
ICX     0.397926
BNB     0.870799
LTC     3.641062
Name: 557, dtype: float64
牛式===============================
執行第 564
           564
ZRX  -0.146889
XRP  -0.135832
ALGO -0.108813
XLM  -0.056117
BCH  -0.055441
QTUM -0.043168
NEO  -0.000274
ZIL   0.015100
VET   0.021339
LINK  0.024104
BAT   0.036360
TRX   0.045232
ZEC   0.049767
ETH   0.062957
ATOM  0.133661
IOTA  0.161049
ADA   0.319942
ICX   0.397926
BNB   0.870799
LTC   3.641062
g================================================================        IOTA     ADA     ICX     BNB     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.8896  1.4039  0.9279  327.67  137.39
721  0.8165  1.3327  1.0350  310.59  132.25
722  0.8180  1.3497  0.9786  316.72  134.42
723  0.7913  1.3356  0.9198  316.09  134.00
724  0.8404  1.3478  0.9519  321.87  134.19

[725 rows x 5 columns]
IOTA    0.105201
ADA     0.278140
ICX     0.158683
BNB     1.260000
LTC     3.472835
Name: 558, dtype: float64
報酬 1.0549718551695801 %
i= IOTA    0.105201
ADA     0.278140
ICX     0.158683
BNB     1.260000
LTC     3.472835
Name: 558, dtype: float64
牛式===============================
執行第 565
           565
ATOM -0.038736
ALGO -0.033681
XRP  -0.010297
BCH  -0.010159
XLM   0.004251
ZEC   0.021328
ZIL   0.041064
LINK  0.046669
ZRX   0.066667
VET   0.072709
ETH   0.086665
IOTA  0.105201
QTUM  0.110089
BAT   0.125952
ICX   0.158683
TRX   0.165783
ADA   0.278140
NEO   0.319144
BNB   1.260000
LTC   3.472835
g================================================================          TRX     ADA     NEO     BNB     LTC
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.06432  1.4039  37.005  327.67  137.39
721  0.06111  1.3327  34.083  310.59  132.25
722  0.06219  1.3497  34.637  316.72  134.42
723  0.06139  1.3356  34.057  316.09  134.00
724  0.06184  1.3478  34.191  321.87  134.19

[725 rows x 5 columns]
TRX    0.043687
ADA    0.260395
NEO    0.145548
BNB    1.055803
LTC    3.273007
Name: 559, dtype: float64
報酬 0.955688059336625 %
i= TRX    0.043687
ADA    0.260395
NEO    0.145548
BNB    1.055803
LTC    3.273007
Name: 559, dtype: float64
牛式===============================
執行第 566
           566
ATOM -0.152572
ALGO -0.130491
BCH  -0.108833
ZEC  -0.074172
ZIL  -0.066120
XLM  -0.046553
BAT  -0.031840
LINK -0.017807
ZRX  -0.015543
QTUM -0.002498
ETH  -0.001988
VET   0.012955
TRX   0.043687
IOTA  0.046187
ICX   0.049887
XRP   0.088033
NEO   0.145548
ADA   0.260395
BNB   1.055803
LTC   3.273007
g================================================================         XRP     NEO     ADA     BNB     LTC
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6521  37.005  1.4039  327.67  137.39
721  0.6236  34.083  1.3327  310.59  132.25
722  0.6372  34.637  1.3497  316.72  134.42
723  0.6251  34.057  1.3356  316.09  134.00
724  0.6362  34.191  1.3478  321.87  134.19

[725 rows x 5 columns]
XRP   -0.108596
NEO   -0.088783
ADA    0.080855
BNB    0.401137
LTC   -0.250896
Name: 560, dtype: float64
報酬 0.006743350165621909 %
i= XRP   -0.108596
NEO   -0.088783
ADA    0.080855
BNB    0.401137
LTC   -0.250896
Name: 560, dtype: float64
牛式===============================
執行第 567
           567
BCH  -0.279189
ALGO -0.265117
ICX  -0.262660
LTC  -0.250896
ZEC  -0.244224
ZIL  -0.232562
QTUM -0.225515
XLM  -0.222043
LINK -0.195470
VET  -0.176796
BAT  -0.169716
IOTA -0.159309
ATOM -0.148116
ETH  -0.145796
TRX  -0.144624
XRP  -0.108596
NEO  -0.088783
ZRX   0.011886
ADA   0.080855
BNB   0.401137
g================================================================         XRP     NEO     ZRX     ADA     BNB
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6521  37.005  0.7889  1.4039  327.67
721  0.6236  34.083  0.8190  1.3327  310.59
722  0.6372  34.637  0.8384  1.3497  316.72
723  0.6251  34.057  0.7890  1.3356  316.09
724  0.6362  34.191  0.7950  1.3478  321.87

[725 rows x 5 columns]
XRP   -0.115551
NEO   -0.074065
ZRX   -0.052432
ADA    0.147629
BNB    0.298886
Name: 561, dtype: float64
報酬 0.04089370150526097 %
i= XRP   -0.115551
NEO   -0.074065
ZRX   -0.052432
ADA    0.147629
BNB    0.298886
Name: 561, dtype: float64
牛式===============================
執行第 568
           568
QTUM -0.255781
BCH  -0.251187
ICX  -0.250961
ALGO -0.240476
ZEC  -0.224018
VET  -0.213700
LTC  -0.199832
ZIL  -0.193300
IOTA -0.189551
BAT  -0.188339
XLM  -0.183713
ETH  -0.162485
ATOM -0.158337
LINK -0.131603
TRX  -0.124247
XRP  -0.115551
NEO  -0.074065
ZRX  -0.052432
ADA   0.147629
BNB   0.298886
g================================================================         XRP     NEO     ZRX     ADA     BNB
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.6521  37.005  0.7889  1.4039  327.67
721  0.6236  34.083  0.8190  1.3327  310.59
722  0.6372  34.637  0.8384  1.3497  316.72
723  0.6251  34.057  0.7890  1.3356  316.09
724  0.6362  34.191  0.7950  1.3478  321.87

[725 rows x 5 columns]
XRP   -0.225569
NEO   -0.196491
ZRX   -0.105709
ADA    0.160493
BNB   -0.297659
Name: 562, dtype: float64
報酬 -0.13298693694932628 %
i= XRP   -0.225569
NEO   -0.196491
ZRX   -0.105709
ADA    0.160493
BNB   -0.297659
Name: 562, dtype: float64
牛式===============================
執行第 569
           569
ZEC  -0.329350
ICX  -0.323308
BCH  -0.305993
BNB  -0.297659
QTUM -0.293120
LINK -0.287486
ALGO -0.282472
ZIL  -0.267267
VET  -0.265347
IOTA -0.261919
XLM  -0.258136
TRX  -0.254494
ETH  -0.246656
LTC  -0.240688
XRP  -0.225569
ATOM -0.224561
BAT  -0.215264
NEO  -0.196491
ZRX  -0.105709
ADA   0.160493
g================================================================        ATOM     BAT     NEO     ZRX     ADA
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  12.946  0.6135  37.005  0.7889  1.4039
721  11.958  0.5691  34.083  0.8190  1.3327
722  13.182  0.5695  34.637  0.8384  1.3497
723  14.395  0.5575  34.057  0.7890  1.3356
724  14.064  0.5623  34.191  0.7950  1.3478

[725 rows x 5 columns]
ATOM   -0.127966
BAT    -0.091255
NEO    -0.140629
ZRX    -0.139166
ADA     0.112710
Name: 563, dtype: float64
報酬 -0.07726114562679623 %
i= ATOM   -0.127966
BAT    -0.091255
NEO    -0.140629
ZRX    -0.139166
ADA     0.112710
Name: 563, dtype: float64
牛式===============================
執行第 570
           570
BCH  -0.287487
ZEC  -0.279386
ICX  -0.276747
VET  -0.260531
LINK -0.260076
ALGO -0.258018
LTC  -0.251607
ETH  -0.244625
QTUM -0.226770
TRX  -0.218106
ZIL  -0.191459
IOTA -0.190111
XLM  -0.177908
XRP  -0.164584
NEO  -0.140629
ZRX  -0.139166
ATOM -0.127966
BNB  -0.126960
BAT  -0.091255
ADA   0.112710
g================================================================         ZRX    ATOM     BNB     BAT     ADA
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  0.7889  12.946  327.67  0.6135  1.4039
721  0.8190  11.958  310.59  0.5691  1.3327
722  0.8384  13.182  316.72  0.5695  1.3497
723  0.7890  14.395  316.09  0.5575  1.3356
724  0.7950  14.064  321.87  0.5623  1.3478

[725 rows x 5 columns]
ZRX    -0.227136
ATOM   -0.113888
BNB    -0.232267
BAT    -0.151295
ADA     0.197045
Name: 564, dtype: float64
報酬 -0.10550820753836714 %
i= ZRX    -0.227136
ATOM   -0.113888
BNB    -0.232267
BAT    -0.151295
ADA     0.197045
Name: 564, dtype: float64
牛式===============================
執行第 571
           571
NEO  -0.320328
BCH  -0.316657
QTUM -0.260430
ZEC  -0.259360
VET  -0.256256
ICX  -0.253086
ETH  -0.245332
LTC  -0.244169
LINK -0.232620
BNB  -0.232267
ZRX  -0.227136
TRX  -0.216681
XRP  -0.198739
IOTA -0.186335
ALGO -0.158725
ZIL  -0.157849
BAT  -0.151295
XLM  -0.118050
ATOM -0.113888
ADA   0.197045
g================================================================          ZIL     BAT      XLM    ATOM     ADA
0        NaN     NaN      NaN     NaN     NaN
1        NaN     NaN      NaN     NaN     NaN
2        NaN     NaN      NaN     NaN     NaN
3        NaN     NaN      NaN     NaN     NaN
4        NaN     NaN      NaN     NaN     NaN
..       ...     ...      ...     ...     ...
720  0.08133  0.6135  0.25677  12.946  1.4039
721  0.07509  0.5691  0.24383  11.958  1.3327
722  0.07496  0.5695  0.24550  13.182  1.3497
723  0.07299  0.5575  0.24484  14.395  1.3356
724  0.07377  0.5623  0.24587  14.064  1.3478

[725 rows x 5 columns]
ZIL    -0.127296
BAT    -0.022111
XLM    -0.124778
ATOM   -0.174651
ADA     0.195842
Name: 565, dtype: float64
報酬 -0.05059894964410203 %
i= ZIL    -0.127296
BAT    -0.022111
XLM    -0.124778
ATOM   -0.174651
ADA     0.195842
Name: 565, dtype: float64
牛式===============================
執行第 572
           572
BCH  -0.268747
XRP  -0.266206
NEO  -0.249659
QTUM -0.242291
ICX  -0.233008
ZEC  -0.229382
ZRX  -0.224633
LINK -0.215967
BNB  -0.214649
VET  -0.207614
LTC  -0.206048
ETH  -0.202038
ATOM -0.174651
TRX  -0.159506
IOTA -0.144034
ZIL  -0.127296
XLM  -0.124778
ALGO -0.108309
BAT  -0.022111
ADA   0.195842
g================================================================          ZIL      XLM    ALGO     BAT     ADA
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.08133  0.25677  0.9062  0.6135  1.4039
721  0.07509  0.24383  0.8683  0.5691  1.3327
722  0.07496  0.24550  0.9059  0.5695  1.3497
723  0.07299  0.24484  0.8918  0.5575  1.3356
724  0.07377  0.24587  0.8952  0.5623  1.3478

[725 rows x 5 columns]
ZIL     0.098672
XLM     0.112776
ALGO    0.084569
BAT     0.228122
ADA     0.344753
Name: 566, dtype: float64
報酬 0.17377817049909497 %
i= ZIL     0.098672
XLM     0.112776
ALGO    0.084569
BAT     0.228122
ADA     0.344753
Name: 566, dtype: float64
牛式===============================
執行第 573
           573
ZRX  -0.142532
ATOM -0.078583
XRP  -0.064116
BCH  -0.029382
ZEC  -0.024126
NEO  -0.016136
LTC  -0.009289
ETH  -0.005133
QTUM  0.023699
TRX   0.064516
LINK  0.068261
ALGO  0.084569
VET   0.085693
ZIL   0.098672
BNB   0.099301
IOTA  0.107671
XLM   0.112776
ICX   0.151910
BAT   0.228122
ADA   0.344753
g================================================================        IOTA      XLM     ICX     BAT     ADA
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  0.25677  0.9279  0.6135  1.4039
721  0.8165  0.24383  1.0350  0.5691  1.3327
722  0.8180  0.24550  0.9786  0.5695  1.3497
723  0.7913  0.24484  0.9198  0.5575  1.3356
724  0.8404  0.24587  0.9519  0.5623  1.3478

[725 rows x 5 columns]
IOTA   -0.011356
XLM     0.033354
ICX    -0.008536
BAT     0.172669
ADA     0.167406
Name: 567, dtype: float64
報酬 0.07070730700390282 %
i= IOTA   -0.011356
XLM     0.033354
ICX    -0.008536
BAT     0.172669
ADA     0.167406
Name: 567, dtype: float64
牛式===============================
執行第 574
           574
ZRX  -0.106203
ETH  -0.082421
ZEC  -0.080052
XRP  -0.071215
NEO  -0.070713
BNB  -0.058245
ATOM -0.029045
TRX  -0.023958
QTUM -0.022411
BCH  -0.018437
LTC  -0.014609
IOTA -0.011356
ICX  -0.008536
LINK  0.013163
ZIL   0.016396
ALGO  0.020083
VET   0.023679
XLM   0.033354
ADA   0.167406
BAT   0.172669
g================================================================        ALGO      VET      XLM     ADA     BAT
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.9062  0.08348  0.25677  1.4039  0.6135
721  0.8683  0.07614  0.24383  1.3327  0.5691
722  0.9059  0.07704  0.24550  1.3497  0.5695
723  0.8918  0.07591  0.24484  1.3356  0.5575
724  0.8952  0.07768  0.24587  1.3478  0.5623

[725 rows x 5 columns]
ALGO    0.200142
VET     0.345522
XLM     0.107298
ADA     0.130451
BAT     0.586866
Name: 568, dtype: float64

報酬 0.2740558785666864 %
i= ALGO    0.200142
VET     0.345522
XLM     0.107298
ADA     0.130451
BAT     0.586866
Name: 568, dtype: float64
牛式===============================
執行第 575
           575
XRP   0.028297
BNB   0.030639
NEO   0.031072
BCH   0.045391
QTUM  0.045446
ZEC   0.046692
LTC   0.046882
ZRX   0.052496
ETH   0.066513
TRX   0.083186
XLM   0.107298
IOTA  0.108509
ADA   0.130451
ICX   0.155036
ZIL   0.160349
ALGO  0.200142
ATOM  0.208437
LINK  0.210846
VET   0.345522
BAT   0.586866
g================================================================        ALGO    ATOM   LINK      VET     BAT
0       NaN     NaN    NaN      NaN     NaN
1       NaN     NaN    NaN      NaN     NaN
2       NaN     NaN    NaN      NaN     NaN
3       NaN     NaN    NaN      NaN     NaN
4       NaN     NaN    NaN      NaN     NaN
..      ...     ...    ...      ...     ...
720  0.9062  12.946  19.79  0.08348  0.6135
721  0.8683  11.958  18.44  0.07614  0.5691
722  0.9059  13.182  18.66  0.07704  0.5695
723  0.8918  14.395  18.20  0.07591  0.5575
724  0.8952  14.064  18.38  0.07768  0.5623

[725 rows x 5 columns]
ALGO    0.120510
ATOM   -0.002065
LINK    0.100199
VET     0.269100
BAT     0.314949
Name: 569, dtype: float64
報酬 0.16053857312679662 %
i= ALGO    0.120510
ATOM   -0.002065
LINK    0.100199
VET     0.269100
BAT     0.314949
Name: 569, dtype: float64
牛式===============================
執行第 576
           576
ADA  -0.103204
ATOM -0.002065
NEO   0.004459
XLM   0.029533
ZEC   0.032048
BNB   0.034217
ZRX   0.040170
BCH   0.043916
LTC   0.061816
ETH   0.064358
ZIL   0.083661
QTUM  0.095827
LINK  0.100199
ALGO  0.120510
XRP   0.124100
IOTA  0.138017
TRX   0.138366
VET   0.269100
ICX   0.306249
BAT   0.314949
g================================================================        IOTA      TRX      VET     ICX     BAT
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.8896  0.06432  0.08348  0.9279  0.6135
721  0.8165  0.06111  0.07614  1.0350  0.5691
722  0.8180  0.06219  0.07704  0.9786  0.5695
723  0.7913  0.06139  0.07591  0.9198  0.5575
724  0.8404  0.06184  0.07768  0.9519  0.5623

[725 rows x 5 columns]
IOTA    0.158362
TRX     0.079372
VET     0.275169
ICX     0.219162
BAT     0.319596
Name: 570, dtype: float64
報酬 0.21033208863193212 %
i= IOTA    0.158362
TRX     0.079372
VET     0.275169
ICX     0.219162
BAT     0.319596
Name: 570, dtype: float64
牛式===============================
執行第 577
           577
ADA  -0.120476
XLM  -0.075246
ALGO -0.041978
ATOM -0.022764
BNB   0.000488
ZIL   0.000605
NEO   0.005150
ZRX   0.005331
ZEC   0.010010
BCH   0.030742
XRP   0.043931
ETH   0.049448
LTC   0.050716
LINK  0.064220
TRX   0.079372
IOTA  0.158362
ICX   0.219162
QTUM  0.248243
VET   0.275169
BAT   0.319596
g================================================================        IOTA     ICX   QTUM      VET     BAT
0       NaN     NaN    NaN      NaN     NaN
1       NaN     NaN    NaN      NaN     NaN
2       NaN     NaN    NaN      NaN     NaN
3       NaN     NaN    NaN      NaN     NaN
4       NaN     NaN    NaN      NaN     NaN
..      ...     ...    ...      ...     ...
720  0.8896  0.9279  7.079  0.08348  0.6135
721  0.8165  1.0350  6.504  0.07614  0.5691
722  0.8180  0.9786  6.776  0.07704  0.5695
723  0.7913  0.9198  6.639  0.07591  0.5575
724  0.8404  0.9519  6.694  0.07768  0.5623

[725 rows x 5 columns]
IOTA    0.141635
ICX     0.322050
QTUM    0.307581
VET     0.344380
BAT     0.262588
Name: 571, dtype: float64
報酬 0.27564677840918045 %
i= IOTA    0.141635
ICX     0.322050
QTUM    0.307581
VET     0.344380
BAT     0.262588
Name: 571, dtype: float64
牛式===============================
執行第 578
           578
ADA  -0.139164
XLM  -0.008075
ALGO  0.035742
ATOM  0.074171
BNB   0.077220
NEO   0.079812
ZIL   0.080011
BCH   0.089105
TRX   0.101360
LTC   0.105904
XRP   0.115563
ZEC   0.127003
ZRX   0.134260
IOTA  0.141635
LINK  0.142394
ETH   0.161752
BAT   0.262588
QTUM  0.307581
ICX   0.322050
VET   0.344380
g================================================================          ETH     BAT   QTUM     ICX      VET
0        NaN     NaN    NaN     NaN      NaN
1        NaN     NaN    NaN     NaN      NaN
2        NaN     NaN    NaN     NaN      NaN
3        NaN     NaN    NaN     NaN      NaN
4        NaN     NaN    NaN     NaN      NaN
..       ...     ...    ...     ...      ...
720  2316.15  0.6135  7.079  0.9279  0.08348
721  2121.52  0.5691  6.504  1.0350  0.07614
722  2146.27  0.5695  6.776  0.9786  0.07704
723  2111.19  0.5575  6.639  0.9198  0.07591
724  2138.86  0.5623  6.694  0.9519  0.07768

[725 rows x 5 columns]
ETH     0.100904
BAT     0.187970
QTUM    0.203605
ICX     0.170248
VET     0.236940
Name: 572, dtype: float64
報酬 0.1799336031656611 %
i= ETH     0.100904
BAT     0.187970
QTUM    0.203605
ICX     0.170248
VET     0.236940
Name: 572, dtype: float64
牛式===============================
執行第 579
           579
ADA  -0.126263
BNB  -0.057669
XLM  -0.040641
ALGO  0.014678
ZIL   0.018048
BCH   0.030431
NEO   0.030701
LINK  0.031769
ATOM  0.040958
ZRX   0.043600
XRP   0.044423
ZEC   0.047109
IOTA  0.081210
TRX   0.081923
LTC   0.083537
ETH   0.100904
ICX   0.170248
BAT   0.187970
QTUM  0.203605
VET   0.236940
g================================================================          ETH     ICX     BAT   QTUM      VET
0        NaN     NaN     NaN    NaN      NaN
1        NaN     NaN     NaN    NaN      NaN
2        NaN     NaN     NaN    NaN      NaN
3        NaN     NaN     NaN    NaN      NaN
4        NaN     NaN     NaN    NaN      NaN
..       ...     ...     ...    ...      ...
720  2316.15  0.9279  0.6135  7.079  0.08348
721  2121.52  1.0350  0.5691  6.504  0.07614
722  2146.27  0.9786  0.5695  6.776  0.07704
723  2111.19  0.9198  0.5575  6.639  0.07591
724  2138.86  0.9519  0.5623  6.694  0.07768

[725 rows x 5 columns]
ETH     0.228745
ICX     0.137327
BAT     0.231574
QTUM    0.214217
VET     0.492031
Name: 573, dtype: float64
報酬 0.2607787525669483 %
i= ETH     0.228745
ICX     0.137327
BAT     0.231574
QTUM    0.214217
VET     0.492031
Name: 573, dtype: float64
牛式===============================
執行第 580
           580
ADA  -0.086499
XLM  -0.000788
BNB   0.004802
BCH   0.022864
ATOM  0.028270
ZRX   0.042667
NEO   0.061135
ALGO  0.066642
LTC   0.072564
ZEC   0.074824
XRP   0.086289
IOTA  0.097973
ZIL   0.099158
LINK  0.117626
TRX   0.129776
ICX   0.137327
QTUM  0.214217
ETH   0.228745
BAT   0.231574
VET   0.492031
g================================================================         ICX   QTUM      ETH     BAT      VET
0       NaN    NaN      NaN     NaN      NaN
1       NaN    NaN      NaN     NaN      NaN
2       NaN    NaN      NaN     NaN      NaN
3       NaN    NaN      NaN     NaN      NaN
4       NaN    NaN      NaN     NaN      NaN
..      ...    ...      ...     ...      ...
720  0.9279  7.079  2316.15  0.6135  0.08348
721  1.0350  6.504  2121.52  0.5691  0.07614
722  0.9786  6.776  2146.27  0.5695  0.07704
723  0.9198  6.639  2111.19  0.5575  0.07591
724  0.9519  6.694  2138.86  0.5623  0.07768

[725 rows x 5 columns]
ICX     0.114030
QTUM    0.224254
ETH     0.189170
BAT    -0.021870
VET     0.217995
Name: 574, dtype: float64
報酬 0.14471586014826174 %
i= ICX     0.114030
QTUM    0.224254
ETH     0.189170
BAT    -0.021870
VET     0.217995
Name: 574, dtype: float64
牛式===============================
執行第 581
           581
BAT  -0.021870
ATOM -0.017151
ADA  -0.014327
ALGO  0.000508
ZRX   0.006687
XLM   0.024249
BCH   0.044531
LINK  0.052473
ZIL   0.064468
NEO   0.076020
XRP   0.081551
LTC   0.083502
ZEC   0.084805
TRX   0.085989
ICX   0.114030
IOTA  0.170297
ETH   0.189170
BNB   0.216525
VET   0.217995
QTUM  0.224254
g================================================================        IOTA      ETH     BNB      VET   QTUM
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  0.8896  2316.15  327.67  0.08348  7.079
721  0.8165  2121.52  310.59  0.07614  6.504
722  0.8180  2146.27  316.72  0.07704  6.776
723  0.7913  2111.19  316.09  0.07591  6.639
724  0.8404  2138.86  321.87  0.07768  6.694

[725 rows x 5 columns]
IOTA    0.028356
ETH     0.165853
BNB     0.210788
VET     0.222355
QTUM    0.098378
Name: 575, dtype: float64
報酬 0.1451459184519533 %
i= IOTA    0.028356
ETH     0.165853
BNB     0.210788
VET     0.222355
QTUM    0.098378
Name: 575, dtype: float64
牛式===============================
執行第 582
           582
XRP  -0.040051
ICX  -0.038489
XLM  -0.004664
TRX   0.002139
ZRX   0.016832
ALGO  0.018644
ADA   0.019381
IOTA  0.028356
ATOM  0.042014
ZIL   0.077034
NEO   0.079291
LINK  0.082038
BCH   0.083147
QTUM  0.098378
LTC   0.110397
ZEC   0.147399
ETH   0.165853
BAT   0.184698
BNB   0.210788
VET   0.222355
g================================================================         ZEC      ETH     BAT     BNB      VET
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  118.51  2316.15  0.6135  327.67  0.08348
721  109.38  2121.52  0.5691  310.59  0.07614
722  110.99  2146.27  0.5695  316.72  0.07704
723  108.15  2111.19  0.5575  316.09  0.07591
724  110.82  2138.86  0.5623  321.87  0.07768

[725 rows x 5 columns]
ZEC    0.252891
ETH    0.192474
BAT    0.180907
BNB    0.285372
VET    0.292220
Name: 576, dtype: float64
報酬 0.24077304153002071 %
i= ZEC    0.252891
ETH    0.192474
BAT    0.180907
BNB    0.285372
VET    0.292220
Name: 576, dtype: float64
牛式===============================
執行第 583
           583
QTUM -0.069081
ADA  -0.029019
XRP  -0.007010
XLM   0.000247
ICX   0.012533
TRX   0.025707
ZRX   0.025842
ALGO  0.028895
ATOM  0.034219
IOTA  0.044969
LINK  0.080101
BCH   0.102983
LTC   0.115932
NEO   0.119930
BAT   0.180907
ETH   0.192474
ZEC   0.252891
BNB   0.285372
VET   0.292220
ZIL   0.515675
g================================================================          ETH     ZEC     BNB      VET      ZIL
0        NaN     NaN     NaN      NaN      NaN
1        NaN     NaN     NaN      NaN      NaN
2        NaN     NaN     NaN      NaN      NaN
3        NaN     NaN     NaN      NaN      NaN
4        NaN     NaN     NaN      NaN      NaN
..       ...     ...     ...      ...      ...
720  2316.15  118.51  327.67  0.08348  0.08133
721  2121.52  109.38  310.59  0.07614  0.07509
722  2146.27  110.99  316.72  0.07704  0.07496
723  2111.19  108.15  316.09  0.07591  0.07299
724  2138.86  110.82  321.87  0.07768  0.07377

[725 rows x 5 columns]
ETH    0.072507
ZEC    0.160850
BNB    0.164229
VET    0.230837
ZIL    0.409142
Name: 577, dtype: float64
報酬 0.20751286277334585 %
i= ETH    0.072507
ZEC    0.160850
BNB    0.164229
VET    0.230837
ZIL    0.409142
Name: 577, dtype: float64
牛式===============================
執行第 584
           584
ADA  -0.086263
QTUM -0.077251
XRP  -0.051331
XLM  -0.037669
ICX  -0.023376
ZRX  -0.022404
ATOM -0.019139
TRX  -0.004980
ALGO -0.004361
LINK  0.007812
IOTA  0.032069
NEO   0.048311
ETH   0.072507
BCH   0.074664
BAT   0.136945
ZEC   0.160850
BNB   0.164229
LTC   0.207895
VET   0.230837
ZIL   0.409142
g================================================================         ZEC     BNB     LTC      VET      ZIL
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  118.51  327.67  137.39  0.08348  0.08133
721  109.38  310.59  132.25  0.07614  0.07509
722  110.99  316.72  134.42  0.07704  0.07496
723  108.15  316.09  134.00  0.07591  0.07299
724  110.82  321.87  134.19  0.07768  0.07377

[725 rows x 5 columns]
ZEC    0.200646
BNB    0.149350
LTC    0.186972
VET    0.192384
ZIL    0.546526
Name: 578, dtype: float64
報酬 0.25517572102888697 %
i= ZEC    0.200646
BNB    0.149350
LTC    0.186972
VET    0.192384
ZIL    0.546526
Name: 578, dtype: float64
牛式===============================
執行第 585
           585
ICX  -0.060259
QTUM -0.035157
ADA  -0.027507
ZRX  -0.016937
XRP  -0.016377
XLM  -0.013911
ATOM -0.005188
TRX   0.021441
ALGO  0.029925
LINK  0.040588
IOTA  0.050099
NEO   0.069783
ETH   0.111298
BNB   0.149350
BCH   0.149577
BAT   0.171605
LTC   0.186972
VET   0.192384
ZEC   0.200646
ZIL   0.546526
g================================================================         BAT     LTC      VET     ZEC      ZIL
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  0.6135  137.39  0.08348  118.51  0.08133
721  0.5691  132.25  0.07614  109.38  0.07509
722  0.5695  134.42  0.07704  110.99  0.07496
723  0.5575  134.00  0.07591  108.15  0.07299
724  0.5623  134.19  0.07768  110.82  0.07377

[725 rows x 5 columns]
BAT    0.033158
LTC    0.117521
VET    0.008984
ZEC    0.105348
ZIL    0.314429
Name: 579, dtype: float64
報酬 0.1158881230818786 %
i= BAT    0.033158
LTC    0.117521
VET    0.008984
ZEC    0.105348
ZIL    0.314429
Name: 579, dtype: float64
牛式===============================
執行第 586
           586
LINK -0.099592
ICX  -0.077974
QTUM -0.073933
XRP  -0.072740
XLM  -0.070464
ZRX  -0.066981
ADA  -0.056281
ATOM -0.048022
TRX  -0.035141
ALGO -0.027383
NEO  -0.010579
IOTA  0.008231
VET   0.008984
ETH   0.012651
BAT   0.033158
BCH   0.044272
BNB   0.098333
ZEC   0.105348
LTC   0.117521

ZIL   0.314429
g================================================================         BCH     BNB     ZEC     LTC      ZIL
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  509.55  327.67  118.51  137.39  0.08133
721  490.60  310.59  109.38  132.25  0.07509
722  504.08  316.72  110.99  134.42  0.07496
723  497.02  316.09  108.15  134.00  0.07299
724  498.00  321.87  110.82  134.19  0.07377

[725 rows x 5 columns]
BCH   -0.040101
BNB   -0.132355
ZEC   -0.019180
LTC   -0.015364
ZIL    0.195809
Name: 580, dtype: float64
報酬 -0.0022384068816054814 %
i= BCH   -0.040101
BNB   -0.132355
ZEC   -0.019180
LTC   -0.015364
ZIL    0.195809
Name: 580, dtype: float64
牛式===============================
執行第 587
           587
ADA  -0.139044
BNB  -0.132355
LINK -0.128295
XLM  -0.109192
XRP  -0.101711
ZRX  -0.101667
IOTA -0.100639
NEO  -0.093824
QTUM -0.093264
ATOM -0.056048
TRX  -0.046267
ETH  -0.040916
BCH  -0.040101
ZEC  -0.019180
ICX  -0.016816
LTC  -0.015364
ALGO  0.007369
BAT   0.017539
ZIL   0.195809
VET   0.221602
g================================================================         LTC    ALGO     BAT      ZIL      VET
0       NaN     NaN     NaN      NaN      NaN
1       NaN     NaN     NaN      NaN      NaN
2       NaN     NaN     NaN      NaN      NaN
3       NaN     NaN     NaN      NaN      NaN
4       NaN     NaN     NaN      NaN      NaN
..      ...     ...     ...      ...      ...
720  137.39  0.9062  0.6135  0.08133  0.08348
721  132.25  0.8683  0.5691  0.07509  0.07614
722  134.42  0.9059  0.5695  0.07496  0.07704
723  134.00  0.8918  0.5575  0.07299  0.07591
724  134.19  0.8952  0.5623  0.07377  0.07768

[725 rows x 5 columns]
LTC     0.005936
ALGO    0.083852
BAT     0.256135
ZIL     0.214493
VET     0.212404
Name: 581, dtype: float64
報酬 0.15456399339048604 %
i= LTC     0.005936
ALGO    0.083852
BAT     0.256135
ZIL     0.214493
VET     0.212404
Name: 581, dtype: float64
牛式===============================
執行第 588
           588
BNB  -0.071334
LINK -0.067802
XLM  -0.034994
BCH  -0.033815
ZEC  -0.004856
XRP  -0.002903
NEO  -0.001444
ETH   0.005776
LTC   0.005936
IOTA  0.015964
TRX   0.016107
QTUM  0.023274
ZRX   0.024651
ICX   0.032723
ATOM  0.068778
ALGO  0.083852
ADA   0.101623
VET   0.212404
ZIL   0.214493
BAT   0.256135
g================================================================        ALGO     ADA      VET      ZIL     BAT
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  0.9062  1.4039  0.08348  0.08133  0.6135
721  0.8683  1.3327  0.07614  0.07509  0.5691
722  0.9059  1.3497  0.07704  0.07496  0.5695
723  0.8918  1.3356  0.07591  0.07299  0.5575
724  0.8952  1.3478  0.07768  0.07377  0.5623

[725 rows x 5 columns]
ALGO    0.193349
ADA     0.224897
VET     0.141288
ZIL     0.117322
BAT     0.538548
Name: 582, dtype: float64
報酬 0.24308063549825762 %
i= ALGO    0.193349
ADA     0.224897
VET     0.141288
ZIL     0.117322
BAT     0.538548
Name: 582, dtype: float64
牛式===============================
執行第 589
           589
BNB  -0.069707
ZEC  -0.037376
IOTA -0.025187
BCH  -0.013047
XLM  -0.004448
ICX  -0.001541
ETH  -0.001440
QTUM  0.014384
LTC   0.022645
LINK  0.032258
XRP   0.040233
ZRX   0.053222
TRX   0.065475
ATOM  0.082224
NEO   0.105705
ZIL   0.117322
VET   0.141288
ALGO  0.193349
ADA   0.224897
BAT   0.538548
g================================================================          ZIL      VET    ALGO     ADA     BAT
0        NaN      NaN     NaN     NaN     NaN
1        NaN      NaN     NaN     NaN     NaN
2        NaN      NaN     NaN     NaN     NaN
3        NaN      NaN     NaN     NaN     NaN
4        NaN      NaN     NaN     NaN     NaN
..       ...      ...     ...     ...     ...
720  0.08133  0.08348  0.9062  1.4039  0.6135
721  0.07509  0.07614  0.8683  1.3327  0.5691
722  0.07496  0.07704  0.9059  1.3497  0.5695
723  0.07299  0.07591  0.8918  1.3356  0.5575
724  0.07377  0.07768  0.8952  1.3478  0.5623

[725 rows x 5 columns]
ZIL     0.095967
VET     0.181418
ALGO    0.196915
ADA     0.193203
BAT     0.592191
Name: 583, dtype: float64
報酬 0.25193857851572554 %
i= ZIL     0.095967
VET     0.181418
ALGO    0.196915
ADA     0.193203
BAT     0.592191
Name: 583, dtype: float64
牛式===============================
執行第 590
           590
LTC  -0.094601
BCH  -0.018382
ZEC  -0.017200
BNB  -0.008086
IOTA  0.000605
ETH   0.004860
XLM   0.021887
LINK  0.036998
ICX   0.039855
XRP   0.067107
TRX   0.067267
QTUM  0.090053
NEO   0.094326
ZIL   0.095967
ZRX   0.132502
VET   0.181418
ATOM  0.191192
ADA   0.193203
ALGO  0.196915
BAT   0.592191
g================================================================          VET    ATOM     ADA    ALGO     BAT
0        NaN     NaN     NaN     NaN     NaN
1        NaN     NaN     NaN     NaN     NaN
2        NaN     NaN     NaN     NaN     NaN
3        NaN     NaN     NaN     NaN     NaN
4        NaN     NaN     NaN     NaN     NaN
..       ...     ...     ...     ...     ...
720  0.08348  12.946  1.4039  0.9062  0.6135
721  0.07614  11.958  1.3327  0.8683  0.5691
722  0.07704  13.182  1.3497  0.9059  0.5695
723  0.07591  14.395  1.3356  0.8918  0.5575
724  0.07768  14.064  1.3478  0.8952  0.5623

[725 rows x 5 columns]
VET     0.198883
ATOM    0.146951
ADA     0.176246
ALGO    0.096822
BAT     0.453898
Name: 584, dtype: float64
報酬 0.21456005284293944 %
i= VET     0.198883
ATOM    0.146951
ADA     0.176246
ALGO    0.096822
BAT     0.453898
Name: 584, dtype: float64
牛式===============================
執行第 591
           591
LTC  -0.116030
BCH  -0.102235
ETH  -0.057804
BNB  -0.046178
ZEC  -0.037151
IOTA -0.031661
XLM  -0.028116
LINK  0.002017
ZIL   0.009599
XRP   0.019337
NEO   0.047787
ICX   0.071635
ALGO  0.096822
TRX   0.109871
ZRX   0.120101
QTUM  0.146732
ATOM  0.146951
ADA   0.176246
VET   0.198883
BAT   0.453898
g================================================================       QTUM    ATOM     ADA      VET     BAT
0      NaN     NaN     NaN      NaN     NaN
1      NaN     NaN     NaN      NaN     NaN
2      NaN     NaN     NaN      NaN     NaN
3      NaN     NaN     NaN      NaN     NaN
4      NaN     NaN     NaN      NaN     NaN
..     ...     ...     ...      ...     ...
720  7.079  12.946  1.4039  0.08348  0.6135
721  6.504  11.958  1.3327  0.07614  0.5691
722  6.776  13.182  1.3497  0.07704  0.5695
723  6.639  14.395  1.3356  0.07591  0.5575
724  6.694  14.064  1.3478  0.07768  0.5623

[725 rows x 5 columns]
QTUM    0.131917
ATOM    0.125379
ADA     0.136990
VET     0.355473
BAT     0.411481
Name: 585, dtype: float64
報酬 0.2322481249427794 %
i= QTUM    0.131917
ATOM    0.125379
ADA     0.136990
VET     0.355473
BAT     0.411481
Name: 585, dtype: float64
牛式===============================
執行第 592
           592
LTC  -0.067308
BCH  -0.030605
ETH  -0.026366
BNB   0.000530
LINK  0.033496
ZIL   0.036289
XLM   0.068114
IOTA  0.070649
ALGO  0.075641
ZEC   0.079249
NEO   0.086397
ICX   0.104260
ATOM  0.125379
ZRX   0.128180
QTUM  0.131917
ADA   0.136990
TRX   0.188173
XRP   0.194406
VET   0.355473
BAT   0.411481
g================================================================         ADA      TRX     XRP      VET     BAT
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  1.4039  0.06432  0.6521  0.08348  0.6135
721  1.3327  0.06111  0.6236  0.07614  0.5691
722  1.3497  0.06219  0.6372  0.07704  0.5695
723  1.3356  0.06139  0.6251  0.07591  0.5575
724  1.3478  0.06184  0.6362  0.07768  0.5623

[725 rows x 5 columns]
ADA    0.150585
TRX    0.246894
XRP    0.185852
VET    0.189354
BAT    0.479474
Name: 586, dtype: float64
報酬 0.25043153380732297 %
i= ADA    0.150585
TRX    0.246894
XRP    0.185852
VET    0.189354
BAT    0.479474
Name: 586, dtype: float64
牛式===============================
執行第 593
           593
LTC  -0.026123
ALGO -0.009080
ICX  -0.005804
ETH  -0.004554
BCH   0.000382
ATOM  0.029789
BNB   0.041421
XLM   0.050342
LINK  0.064117
ZIL   0.084576
ZEC   0.098000
NEO   0.099345
ZRX   0.100045
IOTA  0.101515
QTUM  0.106218
ADA   0.150585
XRP   0.185852
VET   0.189354
TRX   0.246894
BAT   0.479474
g================================================================         ADA     XRP      VET      TRX     BAT
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  1.4039  0.6521  0.08348  0.06432  0.6135
721  1.3327  0.6236  0.07614  0.06111  0.5691
722  1.3497  0.6372  0.07704  0.06219  0.5695
723  1.3356  0.6251  0.07591  0.06139  0.5575
724  1.3478  0.6362  0.07768  0.06184  0.5623

[725 rows x 5 columns]
ADA   -0.116583
XRP    0.182211
VET    0.186748
TRX    0.132735
BAT    0.055010
Name: 587, dtype: float64
報酬 0.08802436270672147 %
i= ADA   -0.116583
XRP    0.182211
VET    0.186748
TRX    0.132735
BAT    0.055010
Name: 587, dtype: float64
牛式===============================
執行第 594
           594
ADA  -0.116583
ATOM -0.084977
ALGO -0.082273
LTC  -0.078998
ETH  -0.066722
ICX  -0.043757
BCH  -0.037400
LINK -0.022931
BNB  -0.012583
ZRX  -0.008322
XLM  -0.007157
NEO  -0.001054
ZEC   0.001507
QTUM  0.026667
ZIL   0.043588
BAT   0.055010
IOTA  0.101646
TRX   0.132735
XRP   0.182211
VET   0.186748
g================================================================         BAT    IOTA      TRX     XRP      VET
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  0.6135  0.8896  0.06432  0.6521  0.08348
721  0.5691  0.8165  0.06111  0.6236  0.07614
722  0.5695  0.8180  0.06219  0.6372  0.07704
723  0.5575  0.7913  0.06139  0.6251  0.07591
724  0.5623  0.8404  0.06184  0.6362  0.07768

[725 rows x 5 columns]
BAT    -0.147085
IOTA    0.220508
TRX     0.070387
XRP     0.171599
VET     0.084674
Name: 588, dtype: float64
報酬 0.08001651147197267 %
i= BAT    -0.147085
IOTA    0.220508
TRX     0.070387
XRP     0.171599
VET     0.084674
Name: 588, dtype: float64
牛式===============================
執行第 595
           595
ADA  -0.189044
ZIL  -0.149472
BAT  -0.147085
ALGO -0.140734
LINK -0.136276
NEO  -0.113767
ATOM -0.103631
LTC  -0.095858
ETH  -0.085112
ZEC  -0.067520
BCH  -0.055997
BNB  -0.053437
XLM  -0.017425
ICX  -0.003086
ZRX   0.036569
TRX   0.070387
VET   0.084674
QTUM  0.131325
XRP   0.171599
IOTA  0.220508
g================================================================          TRX      VET   QTUM     XRP    IOTA
0        NaN      NaN    NaN     NaN     NaN
1        NaN      NaN    NaN     NaN     NaN
2        NaN      NaN    NaN     NaN     NaN
3        NaN      NaN    NaN     NaN     NaN
4        NaN      NaN    NaN     NaN     NaN
..       ...      ...    ...     ...     ...
720  0.06432  0.08348  7.079  0.6521  0.8896
721  0.06111  0.07614  6.504  0.6236  0.8165
722  0.06219  0.07704  6.776  0.6372  0.8180
723  0.06139  0.07591  6.639  0.6251  0.7913
724  0.06184  0.07768  6.694  0.6362  0.8404

[725 rows x 5 columns]
TRX     0.046145
VET     0.096563
QTUM    0.137270
XRP     0.029566
IOTA    0.066339
Name: 589, dtype: float64
報酬 0.075176809948587 %
i= TRX     0.046145
VET     0.096563
QTUM    0.137270
XRP     0.029566
IOTA    0.066339
Name: 589, dtype: float64
牛式===============================
執行第 596
           596
ATOM -0.206887
ALGO -0.181305
BAT  -0.176074
LINK -0.153585
ADA  -0.130522
ZIL  -0.123248
LTC  -0.118504
ETH  -0.109161
ZEC  -0.105355
BCH  -0.100809
ZRX  -0.095116
NEO  -0.093229
XLM  -0.082129
BNB  -0.048641
ICX   0.010064
XRP   0.029566
TRX   0.046145
IOTA  0.066339
VET   0.096563
QTUM  0.137270
g================================================================         XRP      TRX    IOTA      VET   QTUM
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  0.6521  0.06432  0.8896  0.08348  7.079
721  0.6236  0.06111  0.8165  0.07614  6.504
722  0.6372  0.06219  0.8180  0.07704  6.776
723  0.6251  0.06139  0.7913  0.07591  6.639
724  0.6362  0.06184  0.8404  0.07768  6.694

[725 rows x 5 columns]
XRP     0.095111
TRX    -0.057932
IOTA    0.001950
VET    -0.000865
QTUM    0.169421
Name: 590, dtype: float64
報酬 0.04153698858064956 %
i= XRP     0.095111
TRX    -0.057932
IOTA    0.001950
VET    -0.000865
QTUM    0.169421
Name: 590, dtype: float64

牛式===============================
執行第 597
           597
ATOM -0.229955
ZEC  -0.181480
BAT  -0.177926
ALGO -0.165346
ZIL  -0.162981
ZRX  -0.158880
ADA  -0.153590
LINK -0.143624
LTC  -0.142207
ETH  -0.123552
NEO  -0.121695
BCH  -0.112020
BNB  -0.111001
XLM  -0.086433
ICX  -0.083659
TRX  -0.057932
VET  -0.000865
IOTA  0.001950
XRP   0.095111
QTUM  0.169421
g================================================================          TRX      VET    IOTA     XRP   QTUM
0        NaN      NaN     NaN     NaN    NaN
1        NaN      NaN     NaN     NaN    NaN
2        NaN      NaN     NaN     NaN    NaN
3        NaN      NaN     NaN     NaN    NaN
4        NaN      NaN     NaN     NaN    NaN
..       ...      ...     ...     ...    ...
720  0.06432  0.08348  0.8896  0.6521  7.079
721  0.06111  0.07614  0.8165  0.6236  6.504
722  0.06219  0.07704  0.8180  0.6372  6.776
723  0.06139  0.07591  0.7913  0.6251  6.639
724  0.06184  0.07768  0.8404  0.6362  6.694

[725 rows x 5 columns]
TRX     0.066249
VET     0.005584
IOTA    0.031141
XRP     0.074736
QTUM    0.306644
Name: 591, dtype: float64
報酬 0.09687084926201046 %
i= TRX     0.066249
VET     0.005584
IOTA    0.031141
XRP     0.074736
QTUM    0.306644
Name: 591, dtype: float64
牛式===============================
執行第 598
           598
ZEC  -0.136314
ATOM -0.086952
LTC  -0.081924
ALGO -0.075043
LINK -0.074949
XLM  -0.073789
ZRX  -0.070860
ETH  -0.058892
BCH  -0.055297
BNB  -0.035626
NEO  -0.032962
ZIL  -0.019851
BAT  -0.007210
VET   0.005584
ADA   0.011907
IOTA  0.031141
ICX   0.056722
TRX   0.066249
XRP   0.074736
QTUM  0.306644
g================================================================        IOTA     ICX      TRX     XRP   QTUM
0       NaN     NaN      NaN     NaN    NaN
1       NaN     NaN      NaN     NaN    NaN
2       NaN     NaN      NaN     NaN    NaN
3       NaN     NaN      NaN     NaN    NaN
4       NaN     NaN      NaN     NaN    NaN
..      ...     ...      ...     ...    ...
720  0.8896  0.9279  0.06432  0.6521  7.079
721  0.8165  1.0350  0.06111  0.6236  6.504
722  0.8180  0.9786  0.06219  0.6372  6.776
723  0.7913  0.9198  0.06139  0.6251  6.639
724  0.8404  0.9519  0.06184  0.6362  6.694

[725 rows x 5 columns]
IOTA   -0.009145
ICX     0.126001
TRX     0.006326
XRP     0.060526
QTUM    0.301428
Name: 592, dtype: float64
報酬 0.09702716763086598 %
i= IOTA   -0.009145
ICX     0.126001
TRX     0.006326
XRP     0.060526
QTUM    0.301428
Name: 592, dtype: float64
牛式===============================
執行第 599
           599
ZEC  -0.098563
ATOM -0.087610
LINK -0.081137
LTC  -0.057845
VET  -0.054529
XLM  -0.053431
ZIL  -0.045780
BCH  -0.044340
ETH  -0.039908
BAT  -0.038065
NEO  -0.031998
ZRX  -0.028532
ALGO -0.016715
IOTA -0.009145
ADA  -0.007623
TRX   0.006326
BNB   0.017262
XRP   0.060526
ICX   0.126001
QTUM  0.301428
g================================================================          TRX     BNB     XRP     ICX   QTUM
0        NaN     NaN     NaN     NaN    NaN
1        NaN     NaN     NaN     NaN    NaN
2        NaN     NaN     NaN     NaN    NaN
3        NaN     NaN     NaN     NaN    NaN
4        NaN     NaN     NaN     NaN    NaN
..       ...     ...     ...     ...    ...
720  0.06432  327.67  0.6521  0.9279  7.079
721  0.06111  310.59  0.6236  1.0350  6.504
722  0.06219  316.72  0.6372  0.9786  6.776
723  0.06139  316.09  0.6251  0.9198  6.639
724  0.06184  321.87  0.6362  0.9519  6.694

[725 rows x 5 columns]
TRX     0.072332
BNB     0.054344
XRP     0.002536
ICX     0.271506
QTUM    0.253476
Name: 593, dtype: float64
報酬 0.13083874193979078 %
i= TRX     0.072332
BNB     0.054344
XRP     0.002536
ICX     0.271506
QTUM    0.253476
Name: 593, dtype: float64
牛式===============================
執行第 600
           600
IOTA -0.050365
BCH  -0.023650
LINK -0.022369
LTC  -0.007700
ETH   0.001883
XRP   0.002536
ATOM  0.006299
XLM   0.012481
ZRX   0.025529
VET   0.027333
BAT   0.032520
ZEC   0.038619
BNB   0.054344
ZIL   0.061320
TRX   0.072332
ADA   0.077918
NEO   0.099197
ALGO  0.119833
QTUM  0.253476
ICX   0.271506
g================================================================         ADA     NEO    ALGO   QTUM     ICX
0       NaN     NaN     NaN    NaN     NaN
1       NaN     NaN     NaN    NaN     NaN
2       NaN     NaN     NaN    NaN     NaN
3       NaN     NaN     NaN    NaN     NaN
4       NaN     NaN     NaN    NaN     NaN
..      ...     ...     ...    ...     ...
720  1.4039  37.005  0.9062  7.079  0.9279
721  1.3327  34.083  0.8683  6.504  1.0350
722  1.3497  34.637  0.9059  6.776  0.9786
723  1.3356  34.057  0.8918  6.639  0.9198
724  1.3478  34.191  0.8952  6.694  0.9519

[725 rows x 5 columns]
ADA     0.076883
NEO     0.106850
ALGO    0.260901
QTUM    0.246973
ICX     0.368202
Name: 594, dtype: float64
報酬 0.21196190544459076 %
i= ADA     0.076883
NEO     0.106850
ALGO    0.260901
QTUM    0.246973
ICX     0.368202
Name: 594, dtype: float64
牛式===============================
執行第 601
           601
IOTA -0.086131
BCH   0.013827
XLM   0.021725
XRP   0.026457
LTC   0.040872
LINK  0.045132
ZRX   0.063421
ZIL   0.065056
ADA   0.076883
BNB   0.077125
ATOM  0.082092
BAT   0.083278
ETH   0.088821
ZEC   0.095542
TRX   0.102896
VET   0.106041
NEO   0.106850
QTUM  0.246973
ALGO  0.260901
ICX   0.368202
g================================================================          VET     NEO   QTUM    ALGO     ICX
0        NaN     NaN    NaN     NaN     NaN
1        NaN     NaN    NaN     NaN     NaN
2        NaN     NaN    NaN     NaN     NaN
3        NaN     NaN    NaN     NaN     NaN
4        NaN     NaN    NaN     NaN     NaN
..       ...     ...    ...     ...     ...
720  0.08348  37.005  7.079  0.9062  0.9279
721  0.07614  34.083  6.504  0.8683  1.0350
722  0.07704  34.637  6.776  0.9059  0.9786
723  0.07591  34.057  6.639  0.8918  0.9198
724  0.07768  34.191  6.694  0.8952  0.9519

[725 rows x 5 columns]
VET     0.051306
NEO     0.136295
QTUM    0.209640
ALGO    0.287533
ICX     0.416026
Name: 595, dtype: float64
報酬 0.22015996894603934 %
i= VET     0.051306
NEO     0.136295
QTUM    0.209640
ALGO    0.287533
ICX     0.416026
Name: 595, dtype: float64
牛式===============================
執行第 602
           602
VET   0.051306
IOTA  0.082194
BCH   0.106088
XLM   0.106275
LTC   0.111603
LINK  0.117623
ADA   0.132713
NEO   0.136295
ATOM  0.139727
ETH   0.163143
XRP   0.164947
ZIL   0.167834
BAT   0.179901
TRX   0.182894
QTUM  0.209640
ZEC   0.211033
BNB   0.252705
ALGO  0.287533
ZRX   0.345425
ICX   0.416026
g================================================================         ZEC     BNB    ALGO     ZRX     ICX
0       NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
720  118.51  327.67  0.9062  0.7889  0.9279
721  109.38  310.59  0.8683  0.8190  1.0350
722  110.99  316.72  0.9059  0.8384  0.9786
723  108.15  316.09  0.8918  0.7890  0.9198
724  110.82  321.87  0.8952  0.7950  0.9519

[725 rows x 5 columns]
ZEC     0.285598
BNB     0.291699
ALGO    0.311919
ZRX     0.434166
ICX     0.688027
Name: 596, dtype: float64
報酬 0.40228172282277763 %
i= ZEC     0.285598
BNB     0.291699
ALGO    0.311919
ZRX     0.434166
ICX     0.688027
Name: 596, dtype: float64
牛式===============================
執行第 603
           603
VET   0.084823
ADA   0.086516
XRP   0.114782
ATOM  0.115463
XLM   0.122429
QTUM  0.142927
BCH   0.143035
ZIL   0.145324
LTC   0.146320
LINK  0.150078
IOTA  0.150737
BAT   0.171957
ETH   0.209109
ZEC   0.285598
BNB   0.291699
ALGO  0.311919
NEO   0.312077
ZRX   0.434166
TRX   0.676976
ICX   0.688027
g================================================================        ALGO     NEO     ZRX      TRX     ICX
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.9062  37.005  0.7889  0.06432  0.9279
721  0.8683  34.083  0.8190  0.06111  1.0350
722  0.9059  34.637  0.8384  0.06219  0.9786
723  0.8918  34.057  0.7890  0.06139  0.9198
724  0.8952  34.191  0.7950  0.06184  0.9519

[725 rows x 5 columns]
ALGO    0.183935
NEO     0.258401
ZRX     0.413438
TRX     0.319629
ICX     0.381648
Name: 597, dtype: float64
報酬 0.3114102841806838 %
i= ALGO    0.183935
NEO     0.258401
ZRX     0.413438
TRX     0.319629
ICX     0.381648
Name: 597, dtype: float64
牛式===============================
執行第 604
           604
ADA  -0.025979
VET  -0.021165
XRP   0.012101
ATOM  0.027262
ZIL   0.059266
BAT   0.074015
IOTA  0.089426
LINK  0.097080
BCH   0.099270
XLM   0.102496
LTC   0.102916
ETH   0.158574
QTUM  0.160431
ALGO  0.183935
ZEC   0.239326
NEO   0.258401
BNB   0.311149
TRX   0.319629
ICX   0.381648
ZRX   0.413438
g================================================================         NEO     BNB      TRX     ICX     ZRX
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  37.005  327.67  0.06432  0.9279  0.7889
721  34.083  310.59  0.06111  1.0350  0.8190
722  34.637  316.72  0.06219  0.9786  0.8384
723  34.057  316.09  0.06139  0.9198  0.7890
724  34.191  321.87  0.06184  0.9519  0.7950

[725 rows x 5 columns]
NEO    0.288091
BNB    0.256015
TRX    0.449788
ICX    0.257570
ZRX    0.385484
Name: 598, dtype: float64
報酬 0.32738971526404953 %
i= NEO    0.288091
BNB    0.256015
TRX    0.449788
ICX    0.257570
ZRX    0.385484
Name: 598, dtype: float64
牛式===============================
執行第 605
           605
ADA   0.011565
VET   0.062271
ATOM  0.085222
XRP   0.107280
BAT   0.108173
XLM   0.148789
LTC   0.150992
BCH   0.161299
IOTA  0.162267
ALGO  0.171283
QTUM  0.189353
LINK  0.209389
ZIL   0.213462
ETH   0.245834
BNB   0.256015
ICX   0.257570
ZEC   0.267999
NEO   0.288091
ZRX   0.385484
TRX   0.449788
g================================================================         ICX     ZEC     NEO     ZRX      TRX
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.9279  118.51  37.005  0.7889  0.06432
721  1.0350  109.38  34.083  0.8190  0.06111
722  0.9786  110.99  34.637  0.8384  0.06219
723  0.9198  108.15  34.057  0.7890  0.06139
724  0.9519  110.82  34.191  0.7950  0.06184

[725 rows x 5 columns]
ICX    0.055501
ZEC    0.180808
NEO    0.131037
ZRX    0.187044
TRX    0.596226
Name: 599, dtype: float64
報酬 0.2301233705463833 %
i= ICX    0.055501
ZEC    0.180808
NEO    0.131037
ZRX    0.187044
TRX    0.596226
Name: 599, dtype: float64
牛式===============================
執行第 606
           606
VET  -0.036514
ADA  -0.022058
BAT  -0.005086
ALGO  0.022665
XLM   0.027320
ATOM  0.037349
ICX   0.055501
ZIL   0.057661
LTC   0.059526
XRP   0.061260
IOTA  0.062882
BCH   0.068563
LINK  0.099400
NEO   0.131037
ZEC   0.180808
ZRX   0.187044
QTUM  0.187226
ETH   0.190893
BNB   0.197136
TRX   0.596226
g================================================================         ZRX   QTUM      ETH     BNB      TRX
0       NaN    NaN      NaN     NaN      NaN
1       NaN    NaN      NaN     NaN      NaN
2       NaN    NaN      NaN     NaN      NaN
3       NaN    NaN      NaN     NaN      NaN
4       NaN    NaN      NaN     NaN      NaN
..      ...    ...      ...     ...      ...
720  0.7889  7.079  2316.15  327.67  0.06432
721  0.8190  6.504  2121.52  310.59  0.06111
722  0.8384  6.776  2146.27  316.72  0.06219
723  0.7890  6.639  2111.19  316.09  0.06139
724  0.7950  6.694  2138.86  321.87  0.06184

[725 rows x 5 columns]
ZRX     0.150759
QTUM    0.230497
ETH     0.143089
BNB     0.269836
TRX     0.971270
Name: 600, dtype: float64
報酬 0.35309012078155616 %
i= ZRX     0.150759
QTUM    0.230497
ETH     0.143089
BNB     0.269836
TRX     0.971270
Name: 600, dtype: float64
牛式===============================
執行第 607
           607
ALGO -0.064447
ADA  -0.017296
VET   0.005196
ICX   0.018061
IOTA  0.027335
BAT   0.031242
LTC   0.043602
XLM   0.059536
ATOM  0.061757
BCH   0.081716
LINK  0.097074
XRP   0.123337
ETH   0.143089
ZRX   0.150759
NEO   0.198146
QTUM  0.230497
ZIL   0.248269
ZEC   0.254458
BNB   0.269836
TRX   0.971270
g================================================================       QTUM      ZIL     ZEC     BNB      TRX
0      NaN      NaN     NaN     NaN      NaN
1      NaN      NaN     NaN     NaN      NaN
2      NaN      NaN     NaN     NaN      NaN
3      NaN      NaN     NaN     NaN      NaN
4      NaN      NaN     NaN     NaN      NaN
..     ...      ...     ...     ...      ...
720  7.079  0.08133  118.51  327.67  0.06432
721  6.504  0.07509  109.38  310.59  0.06111
722  6.776  0.07496  110.99  316.72  0.06219
723  6.639  0.07299  108.15  316.09  0.06139
724  6.694  0.07377  110.82  321.87  0.06184

[725 rows x 5 columns]
QTUM    0.351296
ZIL     0.154677
ZEC     0.274666
BNB     0.179731
TRX     1.075489
Name: 601, dtype: float64
報酬 0.40717161008279634 %
i= QTUM    0.351296
ZIL     0.154677
ZEC     0.274666
BNB     0.179731
TRX     1.075489
Name: 601, dtype: float64
牛式===============================
執行第 608
           608
ICX  -0.051012
ZRX  -0.023931
ADA  -0.000841
ALGO  0.058566
ATOM  0.073789
BAT   0.092184
IOTA  0.125647
LTC   0.129573
ETH   0.143657
VET   0.145289
ZIL   0.154677
LINK  0.160920
BNB   0.179731
BCH   0.230148
ZEC   0.274666
NEO   0.309718
XLM   0.336392
QTUM  0.351296
XRP   0.622944
TRX   1.075489
g================================================================         NEO      XLM   QTUM     XRP      TRX
0       NaN      NaN    NaN     NaN      NaN
1       NaN      NaN    NaN     NaN      NaN
2       NaN      NaN    NaN     NaN      NaN
3       NaN      NaN    NaN     NaN      NaN
4       NaN      NaN    NaN     NaN      NaN
..      ...      ...    ...     ...      ...
720  37.005  0.25677  7.079  0.6521  0.06432
721  34.083  0.24383  6.504  0.6236  0.06111
722  34.637  0.24550  6.776  0.6372  0.06219
723  34.057  0.24484  6.639  0.6251  0.06139
724  34.191  0.24587  6.694  0.6362  0.06184

[725 rows x 5 columns]
NEO     0.239722
XLM     0.330358
QTUM    0.624414
XRP     0.913892
TRX     0.339517
Name: 602, dtype: float64
報酬 0.48958043246979477 %

i= NEO     0.239722
XLM     0.330358
QTUM    0.624414
XRP     0.913892
TRX     0.339517
Name: 602, dtype: float64
牛式===============================
執行第 609
           609
ICX  -0.185242
ALGO  0.021415
ZRX   0.021730
ADA   0.050583
ETH   0.101150
ATOM  0.134748
ZIL   0.162416
BAT   0.163117
IOTA  0.172098
LINK  0.182624
LTC   0.204097
ZEC   0.207991
BCH   0.223116
NEO   0.239722
VET   0.276085
XLM   0.330358
BNB   0.332583
TRX   0.339517
QTUM  0.624414
XRP   0.913892
g================================================================          XLM     BNB      TRX   QTUM     XRP
0        NaN     NaN      NaN    NaN     NaN
1        NaN     NaN      NaN    NaN     NaN
2        NaN     NaN      NaN    NaN     NaN
3        NaN     NaN      NaN    NaN     NaN
4        NaN     NaN      NaN    NaN     NaN
..       ...     ...      ...    ...     ...
720  0.25677  327.67  0.06432  7.079  0.6521
721  0.24383  310.59  0.06111  6.504  0.6236
722  0.24550  316.72  0.06219  6.776  0.6372
723  0.24484  316.09  0.06139  6.639  0.6251
724  0.24587  321.87  0.06184  6.694  0.6362

[725 rows x 5 columns]
XLM     0.115938
BNB     0.123082
TRX     0.289178
QTUM    0.556398
XRP     0.607952
Name: 603, dtype: float64
報酬 0.3385097284062432 %
i= XLM     0.115938
BNB     0.123082
TRX     0.289178
QTUM    0.556398
XRP     0.607952
Name: 603, dtype: float64
牛式===============================
執行第 610
           610
ICX  -0.176661
ZRX  -0.128089
ALGO -0.015430
ADA  -0.006586
ETH  -0.003394
ATOM  0.002515
BAT   0.028259
ZEC   0.034089
LINK  0.035263
IOTA  0.050368
ZIL   0.076650
LTC   0.083132
BCH   0.108133
XLM   0.115938
BNB   0.123082
NEO   0.141154
VET   0.203599
TRX   0.289178
QTUM  0.556398
XRP   0.607952
g================================================================         NEO      VET      TRX   QTUM     XRP
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  37.005  0.08348  0.06432  7.079  0.6521
721  34.083  0.07614  0.06111  6.504  0.6236
722  34.637  0.07704  0.06219  6.776  0.6372
723  34.057  0.07591  0.06139  6.639  0.6251
724  34.191  0.07768  0.06184  6.694  0.6362

[725 rows x 5 columns]
NEO     0.194558
VET     0.241393
TRX     0.339729
QTUM    0.658422
XRP     0.742719
Name: 604, dtype: float64
報酬 0.4353639225182887 %
i= NEO     0.194558
VET     0.241393
TRX     0.339729
QTUM    0.658422
XRP     0.742719
Name: 604, dtype: float64
牛式===============================
執行第 611
           611
ICX  -0.094309
ZRX  -0.055035
ETH  -0.025079
ALGO -0.004789
LINK  0.009858
ATOM  0.011331
ZIL   0.020931
ADA   0.023899
LTC   0.068920
BAT   0.077007
ZEC   0.090185
BCH   0.107154
XLM   0.149984
IOTA  0.166451
NEO   0.194558
BNB   0.234842
VET   0.241393
TRX   0.339729
QTUM  0.658422
XRP   0.742719
g================================================================         BNB      VET      TRX   QTUM     XRP
0       NaN      NaN      NaN    NaN     NaN
1       NaN      NaN      NaN    NaN     NaN
2       NaN      NaN      NaN    NaN     NaN
3       NaN      NaN      NaN    NaN     NaN
4       NaN      NaN      NaN    NaN     NaN
..      ...      ...      ...    ...     ...
720  327.67  0.08348  0.06432  7.079  0.6521
721  310.59  0.07614  0.06111  6.504  0.6236
722  316.72  0.07704  0.06219  6.776  0.6372
723  316.09  0.07591  0.06139  6.639  0.6251
724  321.87  0.07768  0.06184  6.694  0.6362

[725 rows x 5 columns]
BNB     0.408779
VET     0.441627
TRX     0.141351
QTUM    0.616632
XRP     0.760484
Name: 605, dtype: float64
報酬 0.4737747398743892 %
i= BNB     0.408779
VET     0.441627
TRX     0.141351
QTUM    0.616632
XRP     0.760484
Name: 605, dtype: float64
牛式===============================
執行第 612
           612
ETH   0.029091
ADA   0.033120
ATOM  0.067172
ICX   0.067705
LINK  0.077789
ALGO  0.102976
LTC   0.130954
ZEC   0.134486
TRX   0.141351
BCH   0.187314
XLM   0.188726
NEO   0.199396
ZIL   0.207706
ZRX   0.251477
IOTA  0.261934
BAT   0.380863
BNB   0.408779
VET   0.441627
QTUM  0.616632
XRP   0.760484
g================================================================         BAT     BNB      VET   QTUM     XRP
0       NaN     NaN      NaN    NaN     NaN
1       NaN     NaN      NaN    NaN     NaN
2       NaN     NaN      NaN    NaN     NaN
3       NaN     NaN      NaN    NaN     NaN
4       NaN     NaN      NaN    NaN     NaN
..      ...     ...      ...    ...     ...
720  0.6135  327.67  0.08348  7.079  0.6521
721  0.5691  310.59  0.07614  6.504  0.6236
722  0.5695  316.72  0.07704  6.776  0.6372
723  0.5575  316.09  0.07591  6.639  0.6251
724  0.5623  321.87  0.07768  6.694  0.6362

[725 rows x 5 columns]
BAT     0.246022
BNB     0.351747
VET     0.538395
QTUM    0.470992
XRP     1.164740
Name: 606, dtype: float64
報酬 0.5543792980552572 %
i= BAT     0.246022
BNB     0.351747
VET     0.538395
QTUM    0.470992
XRP     1.164740
Name: 606, dtype: float64
牛式===============================
執行第 613
           613
ZIL  -0.061291
ATOM -0.023089
ICX  -0.020499
TRX  -0.009560
ETH   0.027815
ADA   0.030698
LINK  0.038386
ALGO  0.062471
ZEC   0.102276
NEO   0.130996
ZRX   0.187629
BCH   0.198095
BAT   0.246022
LTC   0.267886
XLM   0.312246
IOTA  0.344479
BNB   0.351747
QTUM  0.470992
VET   0.538395
XRP   1.164740
g================================================================        IOTA     BNB   QTUM      VET     XRP
0       NaN     NaN    NaN      NaN     NaN
1       NaN     NaN    NaN      NaN     NaN
2       NaN     NaN    NaN      NaN     NaN
3       NaN     NaN    NaN      NaN     NaN
4       NaN     NaN    NaN      NaN     NaN
..      ...     ...    ...      ...     ...
720  0.8896  327.67  7.079  0.08348  0.6521
721  0.8165  310.59  6.504  0.07614  0.6236
722  0.8180  316.72  6.776  0.07704  0.6372
723  0.7913  316.09  6.639  0.07591  0.6251
724  0.8404  321.87  6.694  0.07768  0.6362

[725 rows x 5 columns]
IOTA    0.219172
BNB     0.430644
QTUM    0.264785
VET     0.362204
XRP     0.486827
Name: 607, dtype: float64
報酬 0.35272641913344654 %
i= IOTA    0.219172
BNB     0.430644
QTUM    0.264785
VET     0.362204
XRP     0.486827
Name: 607, dtype: float64
牛式===============================
執行第 614
           614
TRX  -0.108457
ZIL  -0.033395
ICX   0.015420
ETH   0.022110
ADA   0.042645
LINK  0.049196
BCH   0.069317
NEO   0.084536
ALGO  0.086197
ATOM  0.089604
XLM   0.094907
BAT   0.125039
ZEC   0.127889
LTC   0.141261
ZRX   0.180996
IOTA  0.219172
QTUM  0.264785
VET   0.362204
BNB   0.430644
XRP   0.486827
g================================================================        IOTA   QTUM      VET     BNB     XRP
0       NaN    NaN      NaN     NaN     NaN
1       NaN    NaN      NaN     NaN     NaN
2       NaN    NaN      NaN     NaN     NaN
3       NaN    NaN      NaN     NaN     NaN
4       NaN    NaN      NaN     NaN     NaN
..      ...    ...      ...     ...     ...
720  0.8896  7.079  0.08348  327.67  0.6521
721  0.8165  6.504  0.07614  310.59  0.6236
722  0.8180  6.776  0.07704  316.72  0.6372
723  0.7913  6.639  0.07591  316.09  0.6251
724  0.8404  6.694  0.07768  321.87  0.6362

[725 rows x 5 columns]
IOTA    0.109927
QTUM   -0.046663
VET     0.149815
BNB     0.486764
XRP     0.346697
Name: 608, dtype: float64
報酬 0.20930819091280597 %
i= IOTA    0.109927
QTUM   -0.046663
VET     0.149815
BNB     0.486764
XRP     0.346697
Name: 608, dtype: float64
牛式===============================
執行第 615
           615
QTUM -0.046663
LINK -0.046384
ZIL  -0.041829
ETH   0.012510
BCH   0.014192
ATOM  0.017228
NEO   0.028759
LTC   0.031747
TRX   0.037359
ADA   0.051144
ALGO  0.061753
BAT   0.067747
ICX   0.075209
XLM   0.094836
ZRX   0.108471
IOTA  0.109927
VET   0.149815
ZEC   0.158991
XRP   0.346697
BNB   0.486764
g================================================================        IOTA      VET     ZEC     XRP     BNB
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  0.08348  118.51  0.6521  327.67
721  0.8165  0.07614  109.38  0.6236  310.59
722  0.8180  0.07704  110.99  0.6372  316.72
723  0.7913  0.07591  108.15  0.6251  316.09
724  0.8404  0.07768  110.82  0.6362  321.87

[725 rows x 5 columns]
IOTA    0.310847
VET     0.447157
ZEC     0.321468
XRP     0.958230
BNB     0.465165
Name: 609, dtype: float64
報酬 0.5005733370812274 %
i= IOTA    0.310847
VET     0.447157
ZEC     0.321468
XRP     0.958230
BNB     0.465165
Name: 609, dtype: float64
牛式===============================
執行第 616
           616
QTUM -0.034184
ZIL   0.060820
NEO   0.113648
ICX   0.115263
LINK  0.141388
ALGO  0.164554
ETH   0.172541
ADA   0.203021
BCH   0.209805
LTC   0.220032
ATOM  0.220123
BAT   0.264542
IOTA  0.310847
ZEC   0.321468
TRX   0.331335
ZRX   0.345235
XLM   0.387273
VET   0.447157
BNB   0.465165
XRP   0.958230
g================================================================         ZRX      XLM      VET     BNB     XRP
0       NaN      NaN      NaN     NaN     NaN
1       NaN      NaN      NaN     NaN     NaN
2       NaN      NaN      NaN     NaN     NaN
3       NaN      NaN      NaN     NaN     NaN
4       NaN      NaN      NaN     NaN     NaN
..      ...      ...      ...     ...     ...
720  0.7889  0.25677  0.08348  327.67  0.6521
721  0.8190  0.24383  0.07614  310.59  0.6236
722  0.8384  0.24550  0.07704  316.72  0.6372
723  0.7890  0.24484  0.07591  316.09  0.6251
724  0.7950  0.24587  0.07768  321.87  0.6362

[725 rows x 5 columns]
ZRX    0.163988
XLM    0.258527
VET    0.439733
BNB    0.315817
XRP    0.735437
Name: 610, dtype: float64
報酬 0.3827005075494232 %
i= ZRX    0.163988
XLM    0.258527
VET    0.439733
BNB    0.315817
XRP    0.735437
Name: 610, dtype: float64
牛式===============================
執行第 617
           617
QTUM -0.059363
ZIL  -0.030729
ICX   0.012769
ALGO  0.082908
NEO   0.089821
IOTA  0.117368
BAT   0.133163
TRX   0.134477
ZRX   0.163988
ETH   0.168764
ADA   0.190857
LTC   0.231055
XLM   0.258527
LINK  0.261440
BCH   0.267324
ZEC   0.285637
BNB   0.315817
ATOM  0.316397
VET   0.439733
XRP   0.735437
g================================================================         ZEC     BNB    ATOM      VET     XRP
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  118.51  327.67  12.946  0.08348  0.6521
721  109.38  310.59  11.958  0.07614  0.6236
722  110.99  316.72  13.182  0.07704  0.6372
723  108.15  316.09  14.395  0.07591  0.6251
724  110.82  321.87  14.064  0.07768  0.6362

[725 rows x 5 columns]
ZEC     0.299552
BNB     0.195854
ATOM    0.302103
VET     0.395979
XRP     0.724552
Name: 611, dtype: float64
報酬 0.38360805212239235 %
i= ZEC     0.299552
BNB     0.195854
ATOM    0.302103
VET     0.395979
XRP     0.724552
Name: 611, dtype: float64
牛式===============================
執行第 618
           618
ICX  -0.025744
ZIL  -0.015656
BAT  -0.013248
ZRX   0.019025
QTUM  0.117808
ALGO  0.126659
IOTA  0.169578
BNB   0.195854
ETH   0.216683
ADA   0.230331
NEO   0.232624
LTC   0.294253
ZEC   0.299552
ATOM  0.302103
XLM   0.316929
LINK  0.348845
BCH   0.371993
VET   0.395979
TRX   0.413740
XRP   0.724552

g================================================================       LINK     BCH      VET      TRX     XRP
0      NaN     NaN      NaN      NaN     NaN
1      NaN     NaN      NaN      NaN     NaN
2      NaN     NaN      NaN      NaN     NaN
3      NaN     NaN      NaN      NaN     NaN
4      NaN     NaN      NaN      NaN     NaN
..     ...     ...      ...      ...     ...
720  19.79  509.55  0.08348  0.06432  0.6521
721  18.44  490.60  0.07614  0.06111  0.6236
722  18.66  504.08  0.07704  0.06219  0.6372
723  18.20  497.02  0.07591  0.06139  0.6251
724  18.38  498.00  0.07768  0.06184  0.6362

[725 rows x 5 columns]
LINK    0.315163
BCH     0.645575
VET     0.658372
TRX     0.275791
XRP     0.126028
Name: 612, dtype: float64
報酬 0.4041858444978271 %
i= LINK    0.315163
BCH     0.645575
VET     0.658372
TRX     0.275791
XRP     0.126028
Name: 612, dtype: float64
牛式===============================
執行第 619
           619
ZRX  -0.048548
ICX   0.018737
BAT   0.043573
BNB   0.076250
ALGO  0.082016
XLM   0.084734
XRP   0.126028
ETH   0.135473
ZIL   0.138320
ADA   0.158017
QTUM  0.158263
LTC   0.205163
IOTA  0.205616
ATOM  0.212098
TRX   0.275791
ZEC   0.312100
LINK  0.315163
NEO   0.407798
BCH   0.645575
VET   0.658372
g================================================================         ZEC   LINK     NEO     BCH      VET
0       NaN    NaN     NaN     NaN      NaN
1       NaN    NaN     NaN     NaN      NaN
2       NaN    NaN     NaN     NaN      NaN
3       NaN    NaN     NaN     NaN      NaN
4       NaN    NaN     NaN     NaN      NaN
..      ...    ...     ...     ...      ...
720  118.51  19.79  37.005  509.55  0.08348
721  109.38  18.44  34.083  490.60  0.07614
722  110.99  18.66  34.637  504.08  0.07704
723  108.15  18.20  34.057  497.02  0.07591
724  110.82  18.38  34.191  498.00  0.07768

[725 rows x 5 columns]
ZEC     0.258281
LINK    0.176349
NEO     0.463406
BCH     0.431435
VET     0.626302
Name: 613, dtype: float64
報酬 0.3911545594947875 %
i= ZEC     0.258281
LINK    0.176349
NEO     0.463406
BCH     0.431435
VET     0.626302
Name: 613, dtype: float64
牛式===============================
執行第 620
           620
ZRX  -0.043962
BNB  -0.019901
XLM   0.007855
BAT   0.025750
ICX   0.039461
ATOM  0.041460
ZIL   0.073299
ETH   0.078534
ADA   0.085355
ALGO  0.101608
IOTA  0.111116
XRP   0.134787
QTUM  0.153373
LINK  0.176349
LTC   0.196584
ZEC   0.258281
TRX   0.272139
BCH   0.431435
NEO   0.463406
VET   0.626302
g================================================================         ZEC      TRX     BCH     NEO      VET
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  118.51  0.06432  509.55  37.005  0.08348
721  109.38  0.06111  490.60  34.083  0.07614
722  110.99  0.06219  504.08  34.637  0.07704
723  108.15  0.06139  497.02  34.057  0.07591
724  110.82  0.06184  498.00  34.191  0.07768

[725 rows x 5 columns]
ZEC    0.174162
TRX    0.109671
BCH    0.449993
NEO    0.823520
VET    0.972119
Name: 614, dtype: float64
報酬 0.5058931837264122 %
i= ZEC    0.174162
TRX    0.109671
BCH    0.449993
NEO    0.823520
VET    0.972119
Name: 614, dtype: float64
牛式===============================
執行第 621
           621
BNB  -0.195811
ZRX  -0.174086
ICX  -0.118642
XLM  -0.077901
BAT  -0.048416
XRP  -0.041692
ADA  -0.029584
ATOM -0.027879
ALGO -0.018264
ZIL   0.026814
ETH   0.046239
TRX   0.109671
LTC   0.117149
ZEC   0.174162
LINK  0.180665
IOTA  0.182232
QTUM  0.258020
BCH   0.449993
NEO   0.823520
VET   0.972119
g================================================================        IOTA   QTUM     BCH     NEO      VET
0       NaN    NaN     NaN     NaN      NaN
1       NaN    NaN     NaN     NaN      NaN
2       NaN    NaN     NaN     NaN      NaN
3       NaN    NaN     NaN     NaN      NaN
4       NaN    NaN     NaN     NaN      NaN
..      ...    ...     ...     ...      ...
720  0.8896  7.079  509.55  37.005  0.08348
721  0.8165  6.504  490.60  34.083  0.07614
722  0.8180  6.776  504.08  34.637  0.07704
723  0.7913  6.639  497.02  34.057  0.07591
724  0.8404  6.694  498.00  34.191  0.07768

[725 rows x 5 columns]
IOTA   -0.041695
QTUM    0.212232
BCH     0.194823
NEO     0.639049
VET     0.490693
Name: 615, dtype: float64
報酬 0.2990202393301048 %
i= IOTA   -0.041695
QTUM    0.212232
BCH     0.194823
NEO     0.639049
VET     0.490693
Name: 615, dtype: float64
牛式===============================
執行第 622
           622
ZRX  -0.311976
XRP  -0.270906
XLM  -0.238853
ATOM -0.192119
ICX  -0.171101
ADA  -0.155305
ALGO -0.147437
BAT  -0.123600
TRX  -0.114099
ZIL  -0.104148
BNB  -0.083851
ETH  -0.060548
IOTA -0.041695
LTC  -0.022478
ZEC  -0.002477
LINK  0.007320
BCH   0.194823
QTUM  0.212232
VET   0.490693
NEO   0.639049
g================================================================       LINK     BCH   QTUM      VET     NEO
0      NaN     NaN    NaN      NaN     NaN
1      NaN     NaN    NaN      NaN     NaN
2      NaN     NaN    NaN      NaN     NaN
3      NaN     NaN    NaN      NaN     NaN
4      NaN     NaN    NaN      NaN     NaN
..     ...     ...    ...      ...     ...
720  19.79  509.55  7.079  0.08348  37.005
721  18.44  490.60  6.504  0.07614  34.083
722  18.66  504.08  6.776  0.07704  34.637
723  18.20  497.02  6.639  0.07591  34.057
724  18.38  498.00  6.694  0.07768  34.191

[725 rows x 5 columns]
LINK   -0.057557
BCH     0.154098
QTUM    0.101051
VET     0.494693
NEO     0.567195
Name: 616, dtype: float64
報酬 0.25189595810288096 %
i= LINK   -0.057557
BCH     0.154098
QTUM    0.101051
VET     0.494693
NEO     0.567195
Name: 616, dtype: float64
牛式===============================
執行第 623
           623
XRP  -0.244215
ATOM -0.214077
ZRX  -0.210609
XLM  -0.166635
BAT  -0.135288
ADA  -0.126655
ICX  -0.119800
ALGO -0.117575
LTC  -0.063711
LINK -0.057557
TRX  -0.052493
ETH  -0.040300
ZIL  -0.037204
IOTA  0.036981
ZEC   0.047669
BNB   0.068901
QTUM  0.101051
BCH   0.154098
VET   0.494693
NEO   0.567195
g================================================================         BNB   QTUM     BCH      VET     NEO
0       NaN    NaN     NaN      NaN     NaN
1       NaN    NaN     NaN      NaN     NaN
2       NaN    NaN     NaN      NaN     NaN
3       NaN    NaN     NaN      NaN     NaN
4       NaN    NaN     NaN      NaN     NaN
..      ...    ...     ...      ...     ...
720  327.67  7.079  509.55  0.08348  37.005
721  310.59  6.504  490.60  0.07614  34.083
722  316.72  6.776  504.08  0.07704  34.637
723  316.09  6.639  497.02  0.07591  34.057
724  321.87  6.694  498.00  0.07768  34.191

[725 rows x 5 columns]
BNB     0.001770
QTUM   -0.103630
BCH     0.051929
VET     0.284521
NEO     0.293232
Name: 617, dtype: float64
報酬 0.10556419986668375 %
i= BNB     0.001770
QTUM   -0.103630
BCH     0.051929
VET     0.284521
NEO     0.293232
Name: 617, dtype: float64
牛式===============================
執行第 624
           624
ATOM -0.297542
XRP  -0.265942
ZRX  -0.257518
TRX  -0.250656
XLM  -0.234010
ALGO -0.229618
BAT  -0.206990
ADA  -0.185811
ZIL  -0.184503
ICX  -0.164627
LINK -0.149026
QTUM -0.103630
LTC  -0.098002
ETH  -0.060705
ZEC  -0.060073
IOTA -0.056072
BNB   0.001770
BCH   0.051929
VET   0.284521
NEO   0.293232
g================================================================        IOTA     BNB     BCH      VET     NEO
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.8896  327.67  509.55  0.08348  37.005
721  0.8165  310.59  490.60  0.07614  34.083
722  0.8180  316.72  504.08  0.07704  34.637
723  0.7913  316.09  497.02  0.07591  34.057
724  0.8404  321.87  498.00  0.07768  34.191

[725 rows x 5 columns]
IOTA   -0.273172
BNB    -0.004978
BCH    -0.227963
VET    -0.192722
NEO     0.039467
Name: 618, dtype: float64
報酬 -0.13187359516845593 %
i= IOTA   -0.273172
BNB    -0.004978
BCH    -0.227963
VET    -0.192722
NEO     0.039467
Name: 618, dtype: float64
牛式===============================
執行第 625
           625
TRX  -0.317252
ZIL  -0.316169
BAT  -0.299084
ZRX  -0.279672
IOTA -0.273172
QTUM -0.269463
ATOM -0.262987
XLM  -0.262525
ICX  -0.261414
XRP  -0.251200
BCH  -0.227963
ALGO -0.227397
VET  -0.192722
ADA  -0.186902
LTC  -0.181886
ZEC  -0.170768
LINK -0.161505
ETH  -0.010156
BNB  -0.004978
NEO   0.039467
g================================================================         ZEC   LINK      ETH     BNB     NEO
0       NaN    NaN      NaN     NaN     NaN
1       NaN    NaN      NaN     NaN     NaN
2       NaN    NaN      NaN     NaN     NaN
3       NaN    NaN      NaN     NaN     NaN
4       NaN    NaN      NaN     NaN     NaN
..      ...    ...      ...     ...     ...
720  118.51  19.79  2316.15  327.67  37.005
721  109.38  18.44  2121.52  310.59  34.083
722  110.99  18.66  2146.27  316.72  34.637
723  108.15  18.20  2111.19  316.09  34.057
724  110.82  18.38  2138.86  321.87  34.191

[725 rows x 5 columns]
ZEC    -0.211944
LINK   -0.119830
ETH     0.020358
BNB     0.022150
NEO    -0.079345
Name: 619, dtype: float64
報酬 -0.07372205116729269 %
i= ZEC    -0.211944
LINK   -0.119830
ETH     0.020358
BNB     0.022150
NEO    -0.079345
Name: 619, dtype: float64
牛式===============================
執行第 626
           626
ICX  -0.313866
ALGO -0.305071
TRX  -0.297443
ZRX  -0.277180
ZIL  -0.275087
QTUM -0.243716
XRP  -0.240056
XLM  -0.238842
ZEC  -0.211944
BAT  -0.204899
LTC  -0.200457
IOTA -0.195886
ATOM -0.157635
ADA  -0.156724
BCH  -0.151206
LINK -0.119830
VET  -0.111730
NEO  -0.079345
ETH   0.020358
BNB   0.022150
g================================================================       LINK      VET     NEO      ETH     BNB
0      NaN      NaN     NaN      NaN     NaN
1      NaN      NaN     NaN      NaN     NaN
2      NaN      NaN     NaN      NaN     NaN
3      NaN      NaN     NaN      NaN     NaN
4      NaN      NaN     NaN      NaN     NaN
..     ...      ...     ...      ...     ...
720  19.79  0.08348  37.005  2316.15  327.67
721  18.44  0.07614  34.083  2121.52  310.59
722  18.66  0.07704  34.637  2146.27  316.72
723  18.20  0.07591  34.057  2111.19  316.09
724  18.38  0.07768  34.191  2138.86  321.87

[725 rows x 5 columns]
LINK   -0.201638
VET    -0.296554
NEO    -0.324712
ETH    -0.008860
BNB     0.033357
Name: 620, dtype: float64
報酬 -0.15968127040681554 %
i= LINK   -0.201638
VET    -0.296554
NEO    -0.324712
ETH    -0.008860
BNB     0.033357
Name: 620, dtype: float64
牛式===============================
執行第 627
           627
QTUM -0.362099
NEO  -0.324712
ICX  -0.299251
VET  -0.296554
IOTA -0.294921
ZIL  -0.289530
TRX  -0.281038
XRP  -0.253736
ALGO -0.252077
ZRX  -0.248552
ZEC  -0.237473
BAT  -0.233553
XLM  -0.219368
BCH  -0.208703
LINK -0.201638
LTC  -0.176141
ATOM -0.139281
ADA  -0.137312
ETH  -0.008860
BNB   0.033357
g================================================================         LTC    ATOM     ADA      ETH     BNB
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  137.39  12.946  1.4039  2316.15  327.67
721  132.25  11.958  1.3327  2121.52  310.59
722  134.42  13.182  1.3497  2146.27  316.72
723  134.00  14.395  1.3356  2111.19  316.09
724  134.19  14.064  1.3478  2138.86  321.87

[725 rows x 5 columns]
LTC    -0.144590
ATOM   -0.030388
ADA    -0.087278
ETH     0.071935
BNB     0.000496
Name: 621, dtype: float64
報酬 -0.03796489086391865 %
i= LTC    -0.144590
ATOM   -0.030388
ADA    -0.087278
ETH     0.071935
BNB     0.000496
Name: 621, dtype: float64
牛式===============================
執行第 628
           628
QTUM -0.346754
NEO  -0.272372
VET  -0.265036
ZIL  -0.222865
BAT  -0.220828
TRX  -0.217147
IOTA -0.213221
XRP  -0.210743
ICX  -0.194068
XLM  -0.166940
ZRX  -0.153419
ALGO -0.153126
BCH  -0.149770
LTC  -0.144590
LINK -0.116825
ZEC  -0.102470
ADA  -0.087278
ATOM -0.030388
BNB   0.000496
ETH   0.071935
g================================================================         ZEC     ADA    ATOM     BNB      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  118.51  1.4039  12.946  327.67  2316.15
721  109.38  1.3327  11.958  310.59  2121.52
722  110.99  1.3497  13.182  316.72  2146.27
723  108.15  1.3356  14.395  316.09  2111.19
724  110.82  1.3478  14.064  321.87  2138.86

[725 rows x 5 columns]
ZEC    -0.087584
ADA    -0.026632
ATOM    0.038139
BNB    -0.088919
ETH     0.085606
Name: 622, dtype: float64
報酬 -0.01587801392820267 %
i= ZEC    -0.087584
ADA    -0.026632
ATOM    0.038139
BNB    -0.088919
ETH     0.085606
Name: 622, dtype: float64
牛式===============================
執行第 629
           629
VET  -0.249275
QTUM -0.199097
NEO  -0.164850
ZIL  -0.145840
TRX  -0.116522
ICX  -0.106236
ZRX  -0.105053
LINK -0.099307
BCH  -0.097519
IOTA -0.093642
BNB  -0.088919
ZEC  -0.087584
XLM  -0.083425
BAT  -0.079769
LTC  -0.052031
ALGO -0.043148
ADA  -0.026632
XRP  -0.014105
ATOM  0.038139
ETH   0.085606
g================================================================        ALGO     ADA     XRP    ATOM      ETH
0       NaN     NaN     NaN     NaN      NaN
1       NaN     NaN     NaN     NaN      NaN
2       NaN     NaN     NaN     NaN      NaN
3       NaN     NaN     NaN     NaN      NaN
4       NaN     NaN     NaN     NaN      NaN
..      ...     ...     ...     ...      ...
720  0.9062  1.4039  0.6521  12.946  2316.15
721  0.8683  1.3327  0.6236  11.958  2121.52
722  0.9059  1.3497  0.6372  13.182  2146.27
723  0.8918  1.3356  0.6251  14.395  2111.19
724  0.8952  1.3478  0.6362  14.064  2138.86

[725 rows x 5 columns]

ALGO    0.082927
ADA     0.086424
XRP     0.085492
ATOM    0.177480
ETH     0.128026
Name: 623, dtype: float64
報酬 0.11206985201715418 %
i= ALGO    0.082927
ADA     0.086424
XRP     0.085492
ATOM    0.177480
ETH     0.128026
Name: 623, dtype: float64
牛式===============================
執行第 630
           630
VET  -0.076053
QTUM -0.053369
NEO  -0.027691
BCH  -0.023809
LTC   0.007836
LINK  0.014341
ZEC   0.018887
BAT   0.021330
TRX   0.025906
XLM   0.040311
BNB   0.047048
IOTA  0.071536
ICX   0.082439
ALGO  0.082927
XRP   0.085492
ADA   0.086424
ZRX   0.116549
ETH   0.128026
ATOM  0.177480
ZIL   0.208051
g================================================================         ADA     ZRX      ETH    ATOM      ZIL
0       NaN     NaN      NaN     NaN      NaN
1       NaN     NaN      NaN     NaN      NaN
2       NaN     NaN      NaN     NaN      NaN
3       NaN     NaN      NaN     NaN      NaN
4       NaN     NaN      NaN     NaN      NaN
..      ...     ...      ...     ...      ...
720  1.4039  0.7889  2316.15  12.946  0.08133
721  1.3327  0.8190  2121.52  11.958  0.07509
722  1.3497  0.8384  2146.27  13.182  0.07496
723  1.3356  0.7890  2111.19  14.395  0.07299
724  1.3478  0.7950  2138.86  14.064  0.07377

[725 rows x 5 columns]
ADA     0.165536
ZRX     0.143747
ETH     0.144816
ATOM    0.222145
ZIL     0.225528
Name: 624, dtype: float64
報酬 0.18035438588122346 %
i= ADA     0.165536
ZRX     0.143747
ETH     0.144816
ATOM    0.222145
ZIL     0.225528
Name: 624, dtype: float64
牛式===============================
執行第 631
           631
NEO   0.015511
LTC   0.022743
LINK  0.029830
VET   0.042724
BCH   0.066924
QTUM  0.071221
ZEC   0.072670
XLM   0.106233
ALGO  0.108856
BNB   0.112271
TRX   0.114896
BAT   0.121102
ZRX   0.143747
ETH   0.144816
ADA   0.165536
XRP   0.171842
IOTA  0.198174
ATOM  0.222145
ZIL   0.225528
ICX   0.244086
g================================================================         XRP    IOTA    ATOM      ZIL     ICX
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.6521  0.8896  12.946  0.08133  0.9279
721  0.6236  0.8165  11.958  0.07509  1.0350
722  0.6372  0.8180  13.182  0.07496  0.9786
723  0.6251  0.7913  14.395  0.07299  0.9198
724  0.6362  0.8404  14.064  0.07377  0.9519

[725 rows x 5 columns]
XRP     0.194947
IOTA    0.122497
ATOM    0.081740
ZIL     0.204937
ICX     0.286990
Name: 625, dtype: float64
報酬 0.178222167709229 %
i= XRP     0.194947
IOTA    0.122497
ATOM    0.081740
ZIL     0.204937
ICX     0.286990
Name: 625, dtype: float64
牛式===============================
執行第 632
           632
VET  -0.050220
BAT   0.013312
LINK  0.038451
NEO   0.039937
ZEC   0.040065
BCH   0.048970
LTC   0.058163
ATOM  0.081740
QTUM  0.087073
XLM   0.091357
TRX   0.111182
IOTA  0.122497
ADA   0.130551
ALGO  0.132727
ZRX   0.135798
BNB   0.139420
ETH   0.164697
XRP   0.194947
ZIL   0.204937
ICX   0.286990
g================================================================         BNB      ETH     XRP      ZIL     ICX
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  327.67  2316.15  0.6521  0.08133  0.9279
721  310.59  2121.52  0.6236  0.07509  1.0350
722  316.72  2146.27  0.6372  0.07496  0.9786
723  316.09  2111.19  0.6251  0.07299  0.9198
724  321.87  2138.86  0.6362  0.07377  0.9519

[725 rows x 5 columns]
BNB    0.252834
ETH    0.250422
XRP    0.521952
ZIL    0.431022
ICX    0.577992
Name: 626, dtype: float64
報酬 0.40684457151111786 %
i= BNB    0.252834
ETH    0.250422
XRP    0.521952
ZIL    0.431022
ICX    0.577992
Name: 626, dtype: float64
牛式===============================
執行第 633
           633
VET   0.126071
LTC   0.204864
NEO   0.216995
LINK  0.222436
BAT   0.222566
ADA   0.227584
ATOM  0.233775
ZEC   0.237139
XLM   0.246248
ETH   0.250422
BNB   0.252834
ALGO  0.286645
TRX   0.287966
QTUM  0.288839
IOTA  0.291249
BCH   0.291635
ZRX   0.361224
ZIL   0.431022
XRP   0.521952
ICX   0.577992
g================================================================         BCH     ZRX      ZIL     XRP     ICX
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  509.55  0.7889  0.08133  0.6521  0.9279
721  490.60  0.8190  0.07509  0.6236  1.0350
722  504.08  0.8384  0.07496  0.6372  0.9786
723  497.02  0.7890  0.07299  0.6251  0.9198
724  498.00  0.7950  0.07377  0.6362  0.9519

[725 rows x 5 columns]
BCH    0.327949
ZRX    0.445596
ZIL    0.490779
XRP    0.596613
ICX    0.510217
Name: 627, dtype: float64
報酬 0.4742308353521777 %
i= BCH    0.327949
ZRX    0.445596
ZIL    0.490779
XRP    0.596613
ICX    0.510217
Name: 627, dtype: float64
牛式===============================
執行第 634
           634
VET   0.215537
BNB   0.229346
LTC   0.238046
BAT   0.240066
ADA   0.240664
QTUM  0.270608
ETH   0.271362
ZEC   0.271613
ALGO  0.273001
ATOM  0.274403
NEO   0.286872
IOTA  0.289459
TRX   0.289973
XLM   0.296711
LINK  0.302532
BCH   0.327949
ZRX   0.445596
ZIL   0.490779
ICX   0.510217
XRP   0.596613
g================================================================         BCH     ZRX      ZIL     ICX     XRP
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  509.55  0.7889  0.08133  0.9279  0.6521
721  490.60  0.8190  0.07509  1.0350  0.6236
722  504.08  0.8384  0.07496  0.9786  0.6372
723  497.02  0.7890  0.07299  0.9198  0.6251
724  498.00  0.7950  0.07377  0.9519  0.6362

[725 rows x 5 columns]
BCH    0.145984
ZRX    0.224211
ZIL    0.242491
ICX    0.267051
XRP    0.141896
Name: 628, dtype: float64
報酬 0.20432645340706065 %
i= BCH    0.145984
ZRX    0.224211
ZIL    0.242491
ICX    0.267051
XRP    0.141896
Name: 628, dtype: float64
牛式===============================
執行第 635
           635
IOTA  0.026834
ATOM  0.047170
ZEC   0.071278
ADA   0.075209
BAT   0.078952
QTUM  0.086550
TRX   0.086990
LTC   0.087018
ALGO  0.123462
LINK  0.124217
VET   0.140767
XRP   0.141896
BCH   0.145984
XLM   0.146329
BNB   0.161977
ETH   0.164884
NEO   0.183891
ZRX   0.224211
ZIL   0.242491
ICX   0.267051
g================================================================          ETH     NEO     ZRX      ZIL     ICX
0        NaN     NaN     NaN      NaN     NaN
1        NaN     NaN     NaN      NaN     NaN
2        NaN     NaN     NaN      NaN     NaN
3        NaN     NaN     NaN      NaN     NaN
4        NaN     NaN     NaN      NaN     NaN
..       ...     ...     ...      ...     ...
720  2316.15  37.005  0.7889  0.08133  0.9279
721  2121.52  34.083  0.8190  0.07509  1.0350
722  2146.27  34.637  0.8384  0.07496  0.9786
723  2111.19  34.057  0.7890  0.07299  0.9198
724  2138.86  34.191  0.7950  0.07377  0.9519

[725 rows x 5 columns]
ETH    0.286742
NEO    0.137610
ZRX    0.042466
ZIL   -0.003577
ICX    0.056549
Name: 629, dtype: float64
報酬 0.10395804286238253 %
i= ETH    0.286742
NEO    0.137610
ZRX    0.042466
ZIL   -0.003577
ICX    0.056549
Name: 629, dtype: float64
牛式===============================
執行第 636
           636
IOTA -0.057340
ATOM -0.004773
ZIL  -0.003577
VET   0.009770
ZEC   0.036412
ADA   0.041514
ZRX   0.042466
TRX   0.044946
BAT   0.049732
QTUM  0.054838
ICX   0.056549
XLM   0.082916
ALGO  0.096045
XRP   0.109953
LTC   0.134131
NEO   0.137610
LINK  0.143013
BCH   0.143177
BNB   0.188594
ETH   0.286742
g================================================================         NEO   LINK     BCH     BNB      ETH
0       NaN    NaN     NaN     NaN      NaN
1       NaN    NaN     NaN     NaN      NaN
2       NaN    NaN     NaN     NaN      NaN
3       NaN    NaN     NaN     NaN      NaN
4       NaN    NaN     NaN     NaN      NaN
..      ...    ...     ...     ...      ...
720  37.005  19.79  509.55  327.67  2316.15
721  34.083  18.44  490.60  310.59  2121.52
722  34.637  18.66  504.08  316.72  2146.27
723  34.057  18.20  497.02  316.09  2111.19
724  34.191  18.38  498.00  321.87  2138.86

[725 rows x 5 columns]
NEO     0.074624
LINK    0.271724
BCH     0.055720
BNB     0.103872
ETH     0.204044
Name: 630, dtype: float64
報酬 0.1419966452279946 %
i= NEO     0.074624
LINK    0.271724
BCH     0.055720
BNB     0.103872
ETH     0.204044
Name: 630, dtype: float64
牛式===============================
執行第 637
           637
IOTA -0.135138
ICX  -0.106644
ATOM -0.084633
VET  -0.048945
ADA  -0.034186
BAT  -0.022487
QTUM -0.011974
ALGO -0.009150
TRX   0.002525
ZIL   0.013950
ZRX   0.025698
XLM   0.026726
XRP   0.027463
ZEC   0.034683
BCH   0.055720
NEO   0.074624
BNB   0.103872
ETH   0.204044
LTC   0.205198
LINK  0.271724
g================================================================         NEO     BNB      ETH     LTC   LINK
0       NaN     NaN      NaN     NaN    NaN
1       NaN     NaN      NaN     NaN    NaN
2       NaN     NaN      NaN     NaN    NaN
3       NaN     NaN      NaN     NaN    NaN
4       NaN     NaN      NaN     NaN    NaN
..      ...     ...      ...     ...    ...
720  37.005  327.67  2316.15  137.39  19.79
721  34.083  310.59  2121.52  132.25  18.44
722  34.637  316.72  2146.27  134.42  18.66
723  34.057  316.09  2111.19  134.00  18.20
724  34.191  321.87  2138.86  134.19  18.38

[725 rows x 5 columns]
NEO     0.288364
BNB     0.084840
ETH     0.277549
LTC     0.392749
LINK    0.359298
Name: 631, dtype: float64
報酬 0.28056020091838646 %
i= NEO     0.288364
BNB     0.084840
ETH     0.277549
LTC     0.392749
LINK    0.359298
Name: 631, dtype: float64
牛式===============================
執行第 638
           638
IOTA -0.035536
ICX   0.009901
VET   0.083699
BNB   0.084840
ALGO  0.091893
ZIL   0.103414
ATOM  0.120920
ZRX   0.125666
ADA   0.130661
BAT   0.147284
XRP   0.154781
TRX   0.209024
XLM   0.232141
QTUM  0.252483
ZEC   0.272573
ETH   0.277549
NEO   0.288364
LINK  0.359298
LTC   0.392749
BCH   0.650822
g================================================================          ETH     NEO   LINK     LTC     BCH
0        NaN     NaN    NaN     NaN     NaN
1        NaN     NaN    NaN     NaN     NaN
2        NaN     NaN    NaN     NaN     NaN
3        NaN     NaN    NaN     NaN     NaN
4        NaN     NaN    NaN     NaN     NaN
..       ...     ...    ...     ...     ...
720  2316.15  37.005  19.79  137.39  509.55
721  2121.52  34.083  18.44  132.25  490.60
722  2146.27  34.637  18.66  134.42  504.08
723  2111.19  34.057  18.20  134.00  497.02
724  2138.86  34.191  18.38  134.19  498.00

[725 rows x 5 columns]
ETH     0.258663
NEO     0.266522
LINK    0.237021
LTC     0.303937
BCH     0.517593
Name: 632, dtype: float64
報酬 0.3167474779660647 %
i= ETH     0.258663
NEO     0.266522
LINK    0.237021
LTC     0.303937
BCH     0.517593
Name: 632, dtype: float64
牛式===============================
執行第 639
           639
ICX  -0.046156
XRP   0.003380
BNB   0.017150
IOTA  0.031771
VET   0.071997
ALGO  0.101441
BAT   0.110891
ATOM  0.124120
ZIL   0.139536
ZRX   0.141096
TRX   0.149860
ADA   0.218565
XLM   0.230149
LINK  0.237021
ETH   0.258663
ZEC   0.259397
NEO   0.266522
LTC   0.303937
BCH   0.517593
QTUM  0.643970
g================================================================         ZEC     NEO     LTC     BCH   QTUM
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  118.51  37.005  137.39  509.55  7.079
721  109.38  34.083  132.25  490.60  6.504
722  110.99  34.637  134.42  504.08  6.776
723  108.15  34.057  134.00  497.02  6.639
724  110.82  34.191  134.19  498.00  6.694

[725 rows x 5 columns]
ZEC     0.241298
NEO     0.155842
LTC     0.248997
BCH     0.335813
QTUM    0.754158
Name: 633, dtype: float64
報酬 0.34722165761971197 %
i= ZEC     0.241298
NEO     0.155842
LTC     0.248997
BCH     0.335813
QTUM    0.754158
Name: 633, dtype: float64
牛式===============================
執行第 640
           640
XRP  -0.041694
BNB   0.006582
IOTA  0.035163
ZRX   0.037350
ICX   0.048357
ZIL   0.076034
BAT   0.106991
TRX   0.125248
VET   0.128063
ALGO  0.131702
NEO   0.155842
XLM   0.166824
ETH   0.182706
LINK  0.193635
ATOM  0.205818
ADA   0.222674
ZEC   0.241298
LTC   0.248997
BCH   0.335813

QTUM  0.754158
g================================================================         ADA     ZEC     LTC     BCH   QTUM
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  1.4039  118.51  137.39  509.55  7.079
721  1.3327  109.38  132.25  490.60  6.504
722  1.3497  110.99  134.42  504.08  6.776
723  1.3356  108.15  134.00  497.02  6.639
724  1.3478  110.82  134.19  498.00  6.694

[725 rows x 5 columns]
ADA     0.221527
ZEC     0.295090
LTC     0.290277
BCH     0.437519
QTUM    0.679800
Name: 634, dtype: float64
報酬 0.38484275928953837 %
i= ADA     0.221527
ZEC     0.295090
LTC     0.290277
BCH     0.437519
QTUM    0.679800
Name: 634, dtype: float64
牛式===============================
執行第 641
           641
XRP   0.000576
VET   0.036856
BNB   0.038925
ZRX   0.046175
IOTA  0.057600
ICX   0.066478
NEO   0.090353
ALGO  0.094185
XLM   0.106933
TRX   0.120160
BAT   0.129310
ZIL   0.147255
ADA   0.221527
LINK  0.231627
ATOM  0.279626
LTC   0.290277
ZEC   0.295090
ETH   0.323437
BCH   0.437519
QTUM  0.679800
g================================================================         LTC     ZEC      ETH     BCH   QTUM
0       NaN     NaN      NaN     NaN    NaN
1       NaN     NaN      NaN     NaN    NaN
2       NaN     NaN      NaN     NaN    NaN
3       NaN     NaN      NaN     NaN    NaN
4       NaN     NaN      NaN     NaN    NaN
..      ...     ...      ...     ...    ...
720  137.39  118.51  2316.15  509.55  7.079
721  132.25  109.38  2121.52  490.60  6.504
722  134.42  110.99  2146.27  504.08  6.776
723  134.00  108.15  2111.19  497.02  6.639
724  134.19  110.82  2138.86  498.00  6.694

[725 rows x 5 columns]
LTC     0.316591
ZEC     0.216424
ETH     0.143823
BCH     0.403824
QTUM    0.724832
Name: 635, dtype: float64
報酬 0.36109889799836276 %
i= LTC     0.316591
ZEC     0.216424
ETH     0.143823
BCH     0.403824
QTUM    0.724832
Name: 635, dtype: float64
牛式===============================
執行第 642
           642
BNB  -0.021416
XRP  -0.012994
ZRX   0.026176
ALGO  0.055587
ICX   0.079427
TRX   0.085721
IOTA  0.087686
BAT   0.094210
ZIL   0.108361
VET   0.108803
NEO   0.113123
XLM   0.138362
ETH   0.143823
ZEC   0.216424
LINK  0.243578
ATOM  0.255471
ADA   0.296557
LTC   0.316591
BCH   0.403824
QTUM  0.724832
g================================================================        ATOM     ADA     LTC     BCH   QTUM
0       NaN     NaN     NaN     NaN    NaN
1       NaN     NaN     NaN     NaN    NaN
2       NaN     NaN     NaN     NaN    NaN
3       NaN     NaN     NaN     NaN    NaN
4       NaN     NaN     NaN     NaN    NaN
..      ...     ...     ...     ...    ...
720  12.946  1.4039  137.39  509.55  7.079
721  11.958  1.3327  132.25  490.60  6.504
722  13.182  1.3497  134.42  504.08  6.776
723  14.395  1.3356  134.00  497.02  6.639
724  14.064  1.3478  134.19  498.00  6.694

[725 rows x 5 columns]
ATOM    0.205330
ADA     0.272481
LTC     0.152997
BCH     0.374403
QTUM    0.658258
Name: 636, dtype: float64
報酬 0.33269375475258994 %
i= ATOM    0.205330
ADA     0.272481
LTC     0.152997
BCH     0.374403
QTUM    0.658258
Name: 636, dtype: float64
牛式===============================
執行第 643
           643
ZRX  -0.009074
XRP  -0.003225
LINK  0.006941
BNB   0.017280
ZIL   0.031689
TRX   0.033317
IOTA  0.062797
NEO   0.065990
ALGO  0.072625
VET   0.073966
ICX   0.074376
BAT   0.119025
ZEC   0.138980
LTC   0.152997
ETH   0.194728
ATOM  0.205330
ADA   0.272481
XLM   0.286682
BCH   0.374403
QTUM  0.658258
g================================================================        ATOM     ADA      XLM     BCH   QTUM
0       NaN     NaN      NaN     NaN    NaN
1       NaN     NaN      NaN     NaN    NaN
2       NaN     NaN      NaN     NaN    NaN
3       NaN     NaN      NaN     NaN    NaN
4       NaN     NaN      NaN     NaN    NaN
..      ...     ...      ...     ...    ...
720  12.946  1.4039  0.25677  509.55  7.079
721  11.958  1.3327  0.24383  490.60  6.504
722  13.182  1.3497  0.24550  504.08  6.776
723  14.395  1.3356  0.24484  497.02  6.639
724  14.064  1.3478  0.24587  498.00  6.694

[725 rows x 5 columns]
ATOM    0.083018
ADA     0.193234
XLM     0.206938
BCH     0.062969
QTUM    0.490185
Name: 637, dtype: float64
報酬 0.20726880493601368 %
i= ATOM    0.083018
ADA     0.193234
XLM     0.206938
BCH     0.062969
QTUM    0.490185
Name: 637, dtype: float64
牛式===============================
執行第 644
           644
XRP  -0.084608
TRX  -0.052398
LINK -0.016142
ZRX  -0.008187
NEO   0.003443
ALGO  0.020243
BAT   0.023194
VET   0.025713
BNB   0.031912
ZEC   0.033969
ZIL   0.036468
IOTA  0.042764
ICX   0.049692
LTC   0.062178
BCH   0.062969
ATOM  0.083018
ETH   0.184872
ADA   0.193234
XLM   0.206938
QTUM  0.490185
g================================================================        ATOM      ETH     ADA      XLM   QTUM
0       NaN      NaN     NaN      NaN    NaN
1       NaN      NaN     NaN      NaN    NaN
2       NaN      NaN     NaN      NaN    NaN
3       NaN      NaN     NaN      NaN    NaN
4       NaN      NaN     NaN      NaN    NaN
..      ...      ...     ...      ...    ...
720  12.946  2316.15  1.4039  0.25677  7.079
721  11.958  2121.52  1.3327  0.24383  6.504
722  13.182  2146.27  1.3497  0.24550  6.776
723  14.395  2111.19  1.3356  0.24484  6.639
724  14.064  2138.86  1.3478  0.24587  6.694

[725 rows x 5 columns]
ATOM   -0.119845
ETH     0.087448
ADA    -0.048316
XLM    -0.089771
QTUM   -0.189360
Name: 638, dtype: float64
報酬 -0.07196864719297422 %
i= ATOM   -0.119845
ETH     0.087448
ADA    -0.048316
XLM    -0.089771
QTUM   -0.189360
Name: 638, dtype: float64
牛式===============================
執行第 645
           645
NEO  -0.242809
ZIL  -0.242034
TRX  -0.224726
VET  -0.224182
ZRX  -0.216253
XRP  -0.207348
ICX  -0.193516
ALGO -0.192746
QTUM -0.189360
IOTA -0.186152
BCH  -0.181912
BAT  -0.180620
LINK -0.131624
LTC  -0.125644
ATOM -0.119845
ZEC  -0.114719
XLM  -0.089771
BNB  -0.076688
ADA  -0.048316
ETH   0.087448
g================================================================         ZEC      XLM     BNB     ADA      ETH
0       NaN      NaN     NaN     NaN      NaN
1       NaN      NaN     NaN     NaN      NaN
2       NaN      NaN     NaN     NaN      NaN
3       NaN      NaN     NaN     NaN      NaN
4       NaN      NaN     NaN     NaN      NaN
..      ...      ...     ...     ...      ...
720  118.51  0.25677  327.67  1.4039  2316.15
721  109.38  0.24383  310.59  1.3327  2121.52
722  110.99  0.24550  316.72  1.3497  2146.27
723  108.15  0.24484  316.09  1.3356  2111.19
724  110.82  0.24587  321.87  1.3478  2138.86

[725 rows x 5 columns]
ZEC   -0.073675
XLM    0.033679
BNB   -0.083623
ADA    0.167181
ETH    0.068249
Name: 639, dtype: float64
報酬 0.022361963723866295 %
i= ZEC   -0.073675
XLM    0.033679
BNB   -0.083623
ADA    0.167181
ETH    0.068249
Name: 639, dtype: float64
牛式===============================
執行第 646
           646
ICX  -0.231328
QTUM -0.219120
VET  -0.208237
ZRX  -0.197235
NEO  -0.180064
ATOM -0.179996
ZIL  -0.179660
TRX  -0.176383
BAT  -0.151269
ALGO -0.144850
XRP  -0.139189
LINK -0.120090
IOTA -0.102408
BNB  -0.083623
LTC  -0.081427
ZEC  -0.073675
BCH  -0.066778
XLM   0.033679
ETH   0.068249
ADA   0.167181
g================================================================         ZEC     BCH      XLM      ETH     ADA
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  118.51  509.55  0.25677  2316.15  1.4039
721  109.38  490.60  0.24383  2121.52  1.3327
722  110.99  504.08  0.24550  2146.27  1.3497
723  108.15  497.02  0.24484  2111.19  1.3356
724  110.82  498.00  0.24587  2138.86  1.3478

[725 rows x 5 columns]
ZEC   -0.030895
BCH   -0.072143
XLM    0.084223
ETH    0.043414
ADA    0.237443
Name: 640, dtype: float64
報酬 0.05240840404042575 %
i= ZEC   -0.030895
BCH   -0.072143
XLM    0.084223
ETH    0.043414
ADA    0.237443
Name: 640, dtype: float64
牛式===============================
執行第 647
           647
ICX  -0.200546
VET  -0.162759
ZIL  -0.143582
QTUM -0.140813
BAT  -0.139815
NEO  -0.134841
TRX  -0.126373
ZRX  -0.126114
ATOM -0.125068
XRP  -0.101594
IOTA -0.094396
BCH  -0.072143
BNB  -0.067707
LTC  -0.059391
LINK -0.041564
ZEC  -0.030895
ALGO -0.027858
ETH   0.043414
XLM   0.084223
ADA   0.237443
g================================================================         ZEC    ALGO      ETH      XLM     ADA
0       NaN     NaN      NaN      NaN     NaN
1       NaN     NaN      NaN      NaN     NaN
2       NaN     NaN      NaN      NaN     NaN
3       NaN     NaN      NaN      NaN     NaN
4       NaN     NaN      NaN      NaN     NaN
..      ...     ...      ...      ...     ...
720  118.51  0.9062  2316.15  0.25677  1.4039
721  109.38  0.8683  2121.52  0.24383  1.3327
722  110.99  0.9059  2146.27  0.24550  1.3497
723  108.15  0.8918  2111.19  0.24484  1.3356
724  110.82  0.8952  2138.86  0.24587  1.3478

[725 rows x 5 columns]
ZEC    -0.111884
ALGO   -0.083542
ETH    -0.072007
XLM     0.082930
ADA     0.230595
Name: 641, dtype: float64
報酬 0.009218377768942233 %
i= ZEC    -0.111884
ALGO   -0.083542
ETH    -0.072007
XLM     0.082930
ADA     0.230595
Name: 641, dtype: float64
牛式===============================
執行第 648
           648
QTUM -0.266772
VET  -0.263111
ICX  -0.239947
LTC  -0.227601
NEO  -0.223690
ZIL  -0.208873
ZRX  -0.207243
LINK -0.207154
BAT  -0.196958
IOTA -0.181730
BCH  -0.181394
TRX  -0.157486
BNB  -0.149326
ATOM -0.149177
ZEC  -0.111884
ALGO -0.083542
ETH  -0.072007
XRP  -0.032847
XLM   0.082930
ADA   0.230595
g================================================================        ALGO      ETH     XRP      XLM     ADA
0       NaN      NaN     NaN      NaN     NaN
1       NaN      NaN     NaN      NaN     NaN
2       NaN      NaN     NaN      NaN     NaN
3       NaN      NaN     NaN      NaN     NaN
4       NaN      NaN     NaN      NaN     NaN
..      ...      ...     ...      ...     ...
720  0.9062  2316.15  0.6521  0.25677  1.4039
721  0.8683  2121.52  0.6236  0.24383  1.3327
722  0.9059  2146.27  0.6372  0.24550  1.3497
723  0.8918  2111.19  0.6251  0.24484  1.3356
724  0.8952  2138.86  0.6362  0.24587  1.3478

[725 rows x 5 columns]
ALGO    0.020356
ETH    -0.093003
XRP     0.041265
XLM     0.086017
ADA     0.399963
Name: 642, dtype: float64
報酬 0.09091979534682426 %
i= ALGO    0.020356
ETH    -0.093003
XRP     0.041265
XLM     0.086017
ADA     0.399963
Name: 642, dtype: float64
牛式===============================
執行第 649
           649
QTUM -0.179273
LTC  -0.175359
ICX  -0.131836
BAT  -0.131262
VET  -0.129708
LINK -0.123654
ZIL  -0.120793
BCH  -0.117399
NEO  -0.115962
BNB  -0.108140
ETH  -0.093003
ZRX  -0.092265
ZEC  -0.073770
TRX  -0.059925
ATOM -0.040584
IOTA -0.007349
ALGO  0.020356
XRP   0.041265
XLM   0.086017
ADA   0.399963
g================================================================        IOTA    ALGO     XRP      XLM     ADA
0       NaN     NaN     NaN      NaN     NaN
1       NaN     NaN     NaN      NaN     NaN
2       NaN     NaN     NaN      NaN     NaN
3       NaN     NaN     NaN      NaN     NaN
4       NaN     NaN     NaN      NaN     NaN
..      ...     ...     ...      ...     ...
720  0.8896  0.9062  0.6521  0.25677  1.4039
721  0.8165  0.8683  0.6236  0.24383  1.3327
722  0.8180  0.9059  0.6372  0.24550  1.3497
723  0.7913  0.8918  0.6251  0.24484  1.3356
724  0.8404  0.8952  0.6362  0.24587  1.3478

[725 rows x 5 columns]
IOTA   -0.123220
ALGO   -0.125297
XRP     0.012112
XLM    -0.120874
ADA     0.152132
Name: 643, dtype: float64
報酬 -0.04102949637127269 %
i= IOTA   -0.123220
ALGO   -0.125297
XRP     0.012112
XLM    -0.120874
ADA     0.152132
Name: 643, dtype: float64
牛式===============================
執行第 650
           650
QTUM -0.343549
BCH  -0.308237
NEO  -0.259267
ICX  -0.259250
VET  -0.256890
LTC  -0.255194
BAT  -0.240244
BNB  -0.237992
LINK -0.237490
ZIL  -0.228932
ZEC  -0.220070
ATOM -0.215517
ETH  -0.214079
ZRX  -0.212414
TRX  -0.187343
ALGO -0.125297
IOTA -0.123220
XLM  -0.120874
XRP   0.012112
ADA   0.152132
g================================================================        ALGO    IOTA      XLM     XRP     ADA
0       NaN     NaN      NaN     NaN     NaN
1       NaN     NaN      NaN     NaN     NaN
2       NaN     NaN      NaN     NaN     NaN
3       NaN     NaN      NaN     NaN     NaN
4       NaN     NaN      NaN     NaN     NaN
..      ...     ...      ...     ...     ...
720  0.9062  0.8896  0.25677  0.6521  1.4039
721  0.8683  0.8165  0.24383  0.6236  1.3327
722  0.9059  0.8180  0.24550  0.6372  1.3497
723  0.8918  0.7913  0.24484  0.6251  1.3356
724  0.8952  0.8404  0.24587  0.6362  1.3478

[725 rows x 5 columns]
ALGO    0.094352
IOTA    0.045857
XLM     0.088848
XRP     0.251751
ADA     0.279355
Name: 644, dtype: float64
報酬 0.15203243789829993 %
i= ALGO    0.094352
IOTA    0.045857
XLM     0.088848
XRP     0.251751
ADA     0.279355
Name: 644, dtype: float64
牛式===============================
執行第 651
           651
BNB  -0.131658
BCH  -0.115810
ETH  -0.110130
QTUM -0.096744
ZEC  -0.067937
NEO  -0.059807
LTC  -0.047414
ICX  -0.043800
BAT  -0.036609
VET  -0.029853
TRX  -0.013726
ZIL  -0.011398
ZRX  -0.006209
ATOM  0.016315
LINK  0.038809
IOTA  0.045857
XLM   0.088848
ALGO  0.094352
XRP   0.251751
ADA   0.279355
g================================================================        IOTA      XLM    ALGO     XRP     ADA
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.8896  0.25677  0.9062  0.6521  1.4039
721  0.8165  0.24383  0.8683  0.6236  1.3327
722  0.8180  0.24550  0.9059  0.6372  1.3497
723  0.7913  0.24484  0.8918  0.6251  1.3356
724  0.8404  0.24587  0.8952  0.6362  1.3478

[725 rows x 5 columns]
IOTA   -0.422706
XLM    -0.316369
ALGO   -0.308810
XRP    -0.220173
ADA    -0.237239
Name: 645, dtype: float64
報酬 -0.3010596220700744 %
i= IOTA   -0.422706
XLM    -0.316369
ALGO   -0.308810
XRP    -0.220173
ADA    -0.237239
Name: 645, dtype: float64
熊式-----------------------------------
執行第 652
           652
ZEC  -0.502551
QTUM -0.473862
BCH  -0.441577
ICX  -0.432265
NEO  -0.431288
IOTA -0.422706
VET  -0.417362
LTC  -0.414315
BNB  -0.414176
ATOM -0.413758
ZIL  -0.401466
LINK -0.387925
ZRX  -0.385144
BAT  -0.376571
TRX  -0.351934
ETH  -0.345459
XLM  -0.316369
ALGO -0.308810
ADA  -0.237239
XRP  -0.220173
g================================================================        ZEC   QTUM     BCH     ICX     NEO
0    55.45  2.642  334.09  0.2002  10.494
1    50.56  2.347  315.09  0.1862   9.427
2    50.57  2.376  316.10  0.2011   9.897
3    48.85  2.291  339.01  0.1925   9.818
4    50.01  2.455  330.12  0.1975   9.663
..     ...    ...     ...     ...     ...
720    NaN    NaN     NaN     NaN     NaN
721    NaN    NaN     NaN     NaN     NaN
722    NaN    NaN     NaN     NaN     NaN
723    NaN    NaN     NaN     NaN     NaN
724    NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
ZEC     0.302528
QTUM    0.769103
BCH     0.350482
ICX     0.049002
NEO     0.218726
Name: 646, dtype: float64
報酬 0.33796816651746 %
i= ZEC     0.302528
QTUM    0.769103
BCH     0.350482
ICX     0.049002
NEO     0.218726
Name: 646, dtype: float64
牛式===============================
執行第 653
           653
ZEC  -0.403296
QTUM -0.380153
BCH  -0.371128
ICX  -0.351617
LTC  -0.351215
BNB  -0.348096
ATOM -0.347131
LINK -0.341563
IOTA -0.322927
ZRX  -0.322669
ETH  -0.317222
VET  -0.297409
NEO  -0.288225
TRX  -0.285382
ZIL  -0.285102
BAT  -0.283361
XLM  -0.258620
ALGO -0.249712
XRP  -0.159114
ADA  -0.100628
g================================================================         BAT      XLM    ALGO     XRP     ADA
0       NaN      NaN     NaN     NaN     NaN
1       NaN      NaN     NaN     NaN     NaN
2       NaN      NaN     NaN     NaN     NaN
3       NaN      NaN     NaN     NaN     NaN
4       NaN      NaN     NaN     NaN     NaN
..      ...      ...     ...     ...     ...
720  0.6135  0.25677  0.9062  0.6521  1.4039
721  0.5691  0.24383  0.8683  0.6236  1.3327
722  0.5695  0.24550  0.9059  0.6372  1.3497
723  0.5575  0.24484  0.8918  0.6251  1.3356
724  0.5623  0.24587  0.8952  0.6362  1.3478

[725 rows x 5 columns]
BAT    -0.333098
XLM    -0.383881
ALGO   -0.294571
XRP    -0.322574
ADA    -0.288324
Name: 647, dtype: float64
報酬 -0.32448964172373873 %
i= BAT    -0.333098
XLM    -0.383881
ALGO   -0.294571
XRP    -0.322574
ADA    -0.288324
Name: 647, dtype: float64
熊式-----------------------------------
執行第 654
           654
ATOM -0.446045
QTUM -0.442883
ZEC  -0.421064
BNB  -0.419959
BCH  -0.411031
IOTA -0.403531
LTC  -0.399586
ZIL  -0.385983
XLM  -0.383881
LINK -0.383595
NEO  -0.373740
VET  -0.372961
ICX  -0.367759
TRX  -0.353410
BAT  -0.333098
ETH  -0.331535
ZRX  -0.328940
XRP  -0.322574
ALGO -0.294571
ADA  -0.288324
g================================================================       ATOM   QTUM    ZEC    BNB     BCH
0    3.258  2.642  55.45  29.42  334.09
1    2.857  2.347  50.56  27.01  315.09
2    2.898  2.376  50.57  28.11  316.10
3    2.884  2.291  48.85  27.53  339.01
4    2.910  2.455  50.01  27.50  330.12
..     ...    ...    ...    ...     ...
720    NaN    NaN    NaN    NaN     NaN
721    NaN    NaN    NaN    NaN     NaN
722    NaN    NaN    NaN    NaN     NaN
723    NaN    NaN    NaN    NaN     NaN
724    NaN    NaN    NaN    NaN     NaN

[725 rows x 5 columns]
ATOM    0.247315
QTUM    0.784410
ZEC     0.252940
BNB     0.063798
BCH     0.465507
Name: 648, dtype: float64
報酬 0.3627940103748563 %
i= ATOM    0.247315
QTUM    0.784410
ZEC     0.252940
BNB     0.063798
BCH     0.465507
Name: 648, dtype: float64
熊式-----------------------------------
執行第 655
           655
QTUM -0.498369
ATOM -0.496338
IOTA -0.487595
BNB  -0.468857
BCH  -0.459282
ZEC  -0.458122
XLM  -0.455867
NEO  -0.447277
VET  -0.436413
ICX  -0.429438
LTC  -0.428403
LINK -0.427729
ZIL  -0.427281
BAT  -0.403681
ZRX  -0.392234
XRP  -0.375242
TRX  -0.369834
ADA  -0.363783
ETH  -0.360805
ALGO -0.304612
g================================================================       QTUM   ATOM    IOTA    BNB     BCH
0    2.642  3.258  0.2564  29.42  334.09
1    2.347  2.857  0.2322  27.01  315.09
2    2.376  2.898  0.2428  28.11  316.10
3    2.291  2.884  0.2413  27.53  339.01
4    2.455  2.910  0.2422  27.50  330.12
..     ...    ...     ...    ...     ...
720    NaN    NaN     NaN    NaN     NaN
721    NaN    NaN     NaN    NaN     NaN
722    NaN    NaN     NaN    NaN     NaN
723    NaN    NaN     NaN    NaN     NaN
724    NaN    NaN     NaN    NaN     NaN

[725 rows x 5 columns]
QTUM    0.493843
ATOM    0.104281
IOTA   -0.032336
BNB    -0.065728
BCH     0.300899
Name: 649, dtype: float64
報酬 0.16019185973672587 %
i= QTUM    0.493843
ATOM    0.104281
IOTA   -0.032336
BNB    -0.065728
BCH     0.300899
Name: 649, dtype: float64
熊式-----------------------------------
執行第 656
           656
QTUM -0.531451
ZEC  -0.514650
IOTA -0.510844
NEO  -0.494359
LTC  -0.493675
BNB  -0.488823
ZIL  -0.486109
BCH  -0.483386
ICX  -0.473704
BAT  -0.472571
XRP  -0.470785
LINK -0.465573
ZRX  -0.457670
VET  -0.453797
ATOM -0.446906
TRX  -0.442988
XLM  -0.431331
ALGO -0.363241
ETH  -0.359180
ADA  -0.352822
g================================================================       QTUM    ZEC    IOTA     NEO    LTC
0    2.642  55.45  0.2564  10.494  56.59
1    2.347  50.56  0.2322   9.427  54.82
2    2.376  50.57  0.2428   9.897  56.60
3    2.291  48.85  0.2413   9.818  55.28
4    2.455  50.01  0.2422   9.663  55.88
..     ...    ...     ...     ...    ...
720    NaN    NaN     NaN     NaN    NaN
721    NaN    NaN     NaN     NaN    NaN
722    NaN    NaN     NaN     NaN    NaN
723    NaN    NaN     NaN     NaN    NaN
724    NaN    NaN     NaN     NaN    NaN

[725 rows x 5 columns]
QTUM    0.866826
ZEC     0.212164
IOTA    0.115620
NEO     0.174650
LTC     0.212521
Name: 650, dtype: float64
報酬 0.31635616541307426 %
i= QTUM    0.866826
ZEC     0.212164
IOTA    0.115620
NEO     0.174650
LTC     0.212521
Name: 650, dtype: float64
熊式-----------------------------------
執行第 657
           657
IOTA -0.432327
ZEC  -0.415637
ICX  -0.386007
ZRX  -0.385855
NEO  -0.382092
LINK -0.380639
QTUM -0.378435
ZIL  -0.377797
XRP  -0.376336
LTC  -0.374444
ATOM -0.367203
BAT  -0.345519
TRX  -0.340550
BNB  -0.320375
XLM  -0.320340
BCH  -0.312762
VET  -0.309262
ALGO -0.283284
ADA  -0.228626
ETH  -0.216055
g================================================================        IOTA    ZEC     ICX     ZRX     NEO
0    0.2564  55.45  0.2002  0.1814  10.494
1    0.2322  50.56  0.1862  0.1624   9.427
2    0.2428  50.57  0.2011  0.1736   9.897
3    0.2413  48.85  0.1925  0.1751   9.818
4    0.2422  50.01  0.1975  0.1711   9.663
..      ...    ...     ...     ...     ...
720     NaN    NaN     NaN     NaN     NaN
721     NaN    NaN     NaN     NaN     NaN
722     NaN    NaN     NaN     NaN     NaN
723     NaN    NaN     NaN     NaN     NaN
724     NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
IOTA   -0.108316
ZEC    -0.063487
ICX    -0.162023
ZRX    -0.143799
NEO    -0.193459
Name: 651, dtype: float64
報酬 -0.13421671186096268 %
i= IOTA   -0.108316
ZEC    -0.063487
ICX    -0.162023
ZRX    -0.143799
NEO    -0.193459
Name: 651, dtype: float64
熊式-----------------------------------
執行第 658
           658
XRP  -0.082054
IOTA -0.043467
ICX  -0.041674
XLM  -0.037413
ZIL  -0.030710
TRX  -0.020193
ZEC  -0.013448
ZRX  -0.012997
LTC  -0.012366
BAT  -0.008871
ATOM  0.009500
NEO   0.025022
BNB   0.026270
BCH   0.027691
LINK  0.040816
ALGO  0.047961
ADA   0.054216
VET   0.059522
QTUM  0.063553
ETH   0.110988
g================================================================          XRP    IOTA     ICX      XLM      ZIL
0    0.29787  0.2564  0.2002  0.07442  0.00879
1    0.26338  0.2322  0.1862  0.06922  0.00762
2    0.26408  0.2428  0.2011  0.07019  0.00749
3    0.26055  0.2413  0.1925  0.06851  0.00732
4    0.26543  0.2422  0.1975  0.06770  0.00773
..       ...     ...     ...      ...      ...
720      NaN     NaN     NaN      NaN      NaN
721      NaN     NaN     NaN      NaN      NaN
722      NaN     NaN     NaN      NaN      NaN
723      NaN     NaN     NaN      NaN      NaN
724      NaN     NaN     NaN      NaN      NaN

[725 rows x 5 columns]
XRP    -0.150895
IOTA   -0.117319
ICX    -0.154643
XLM    -0.001212
ZIL    -0.206535
Name: 652, dtype: float64
報酬 -0.1261208930471679 %
i= XRP    -0.150895
IOTA   -0.117319
ICX    -0.154643
XLM    -0.001212
ZIL    -0.206535
Name: 652, dtype: float64
熊式-----------------------------------
執行第 659
           659
NEO  -0.129756
ZEC  -0.129420
XRP  -0.125837
XLM  -0.103788
ATOM -0.097416
ALGO -0.076569
QTUM -0.074727
ZIL  -0.069811
TRX  -0.068370
BCH  -0.064085
LTC  -0.061387
ICX  -0.034647
BNB  -0.034427
IOTA -0.027319
ADA  -0.014138
ZRX  -0.006315
VET   0.013488
BAT   0.013840
ETH   0.037045
LINK  0.105641
g================================================================         NEO    ZEC      XRP      XLM   ATOM
0    10.494  55.45  0.29787  0.07442  3.258
1     9.427  50.56  0.26338  0.06922  2.857
2     9.897  50.57  0.26408  0.07019  2.898
3     9.818  48.85  0.26055  0.06851  2.884
4     9.663  50.01  0.26543  0.06770  2.910
..      ...    ...      ...      ...    ...
720     NaN    NaN      NaN      NaN    NaN
721     NaN    NaN      NaN      NaN    NaN
722     NaN    NaN      NaN      NaN    NaN
723     NaN    NaN      NaN      NaN    NaN
724     NaN    NaN      NaN      NaN    NaN

[725 rows x 5 columns]
NEO    -0.147344
ZEC    -0.044756
XRP    -0.112502
XLM     0.059673
ATOM   -0.098836
Name: 653, dtype: float64
報酬 -0.06875308602110682 %
i= NEO    -0.147344
ZEC    -0.044756
XRP    -0.112502
XLM     0.059673
ATOM   -0.098836
Name: 653, dtype: float64
熊式-----------------------------------
執行第 660
           660
ZEC  -0.048832
ICX  -0.035470
XRP  -0.035313
ALGO -0.010105
XLM  -0.000716
TRX   0.016318
IOTA  0.054575
ZRX   0.056807
ZIL   0.061853
ADA   0.063353
ATOM  0.064245
LTC   0.072310
NEO   0.075273
BCH   0.087177
BAT   0.110568
BNB   0.125341
ETH   0.127355
VET   0.140067
LINK  0.234834
QTUM  0.296847
g================================================================        ZEC     ICX      XRP   ALGO      XLM
0    55.45  0.2002  0.29787  0.809  0.07442
1    50.56  0.1862  0.26338  0.717  0.06922
2    50.57  0.2011  0.26408  0.710  0.07019
3    48.85  0.1925  0.26055  0.677  0.06851
4    50.01  0.1975  0.26543  0.683  0.06770
..     ...     ...      ...    ...      ...
720    NaN     NaN      NaN    NaN      NaN
721    NaN     NaN      NaN    NaN      NaN
722    NaN     NaN      NaN    NaN      NaN
723    NaN     NaN      NaN    NaN      NaN
724    NaN     NaN      NaN    NaN      NaN

[725 rows x 5 columns]
ZEC    -0.140789
ICX    -0.247540
XRP    -0.049997
ALGO   -0.085353
XLM     0.104905
Name: 654, dtype: float64
報酬 -0.08375471785104838 %
i= ZEC    -0.140789
ICX    -0.247540
XRP    -0.049997
ALGO   -0.085353
XLM     0.104905
Name: 654, dtype: float64
熊式-----------------------------------
執行第 661
           661
ALGO -0.075990
ICX  -0.051595
TRX  -0.043542
XRP  -0.006299
ZRX   0.007725
IOTA  0.019036
XLM   0.026821
ADA   0.033349
ATOM  0.037663
LTC   0.045876
ETH   0.055932
ZIL   0.059853
NEO   0.061123
VET   0.086943
BCH   0.092645
BAT   0.099353
BNB   0.100592
ZEC   0.157865
LINK  0.199313
QTUM  0.251626
g================================================================       ALGO     ICX      TRX      XRP     ZRX
0    0.809  0.2002  0.02049  0.29787  0.1814
1    0.717  0.1862  0.01778  0.26338  0.1624
2    0.710  0.2011  0.01752  0.26408  0.1736
3    0.677  0.1925  0.01688  0.26055  0.1751
4    0.683  0.1975  0.01692  0.26543  0.1711
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
ALGO   -0.077141
ICX    -0.246410
TRX    -0.163295
XRP    -0.056048
ZRX    -0.192696
Name: 655, dtype: float64
報酬 -0.14711801771163607 %

i= ALGO   -0.077141
ICX    -0.246410
TRX    -0.163295
XRP    -0.056048
ZRX    -0.192696
Name: 655, dtype: float64
熊式-----------------------------------
執行第 662
           662
XLM   0.003559
ALGO  0.010614
ATOM  0.032098
ICX   0.038395
XRP   0.049015
ADA   0.065703
IOTA  0.076100
ETH   0.082359
TRX   0.092731
ZRX   0.129000
ZIL   0.144007
VET   0.146002
LTC   0.147719
NEO   0.154191
BNB   0.164978
BCH   0.179016
BAT   0.218045
LINK  0.275793
ZEC   0.302712
QTUM  0.380415
g================================================================          XLM   ALGO   ATOM     ICX      XRP
0    0.07442  0.809  3.258  0.2002  0.29787
1    0.06922  0.717  2.857  0.1862  0.26338
2    0.07019  0.710  2.898  0.2011  0.26408
3    0.06851  0.677  2.884  0.1925  0.26055
4    0.06770  0.683  2.910  0.1975  0.26543
..       ...    ...    ...     ...      ...
720      NaN    NaN    NaN     NaN      NaN
721      NaN    NaN    NaN     NaN      NaN
722      NaN    NaN    NaN     NaN      NaN
723      NaN    NaN    NaN     NaN      NaN
724      NaN    NaN    NaN     NaN      NaN

[725 rows x 5 columns]
XLM    -0.022923
ALGO   -0.060776
ATOM   -0.166088
ICX    -0.192006
XRP     0.075341
Name: 656, dtype: float64
報酬 -0.0732902653246292 %
i= XLM    -0.022923
ALGO   -0.060776
ATOM   -0.166088
ICX    -0.192006
XRP     0.075341
Name: 656, dtype: float64
熊式-----------------------------------
執行第 663
           663
XLM  -0.146957
ALGO -0.131137
ATOM -0.129398
BCH  -0.117860
ICX  -0.101346
ETH  -0.098370
XRP  -0.086593
LTC  -0.074408
TRX  -0.062402
BNB  -0.057546
ZRX  -0.046796
NEO  -0.045458
VET  -0.039639
IOTA -0.038386
ZIL  -0.034309
BAT  -0.028962
ZEC   0.006847
QTUM  0.015212
ADA   0.018355
LINK  0.018968
g================================================================          XLM   ALGO   ATOM     BCH     ICX
0    0.07442  0.809  3.258  334.09  0.2002
1    0.06922  0.717  2.857  315.09  0.1862
2    0.07019  0.710  2.898  316.10  0.2011
3    0.06851  0.677  2.884  339.01  0.1925
4    0.06770  0.683  2.910  330.12  0.1975
..       ...    ...    ...     ...     ...
720      NaN    NaN    NaN     NaN     NaN
721      NaN    NaN    NaN     NaN     NaN
722      NaN    NaN    NaN     NaN     NaN
723      NaN    NaN    NaN     NaN     NaN
724      NaN    NaN    NaN     NaN     NaN

[725 rows x 5 columns]
XLM    -0.115933
ALGO   -0.073181
ATOM   -0.150932
BCH    -0.293567
ICX    -0.236658
Name: 657, dtype: float64
報酬 -0.174054213560102 %
i= XLM    -0.115933
ALGO   -0.073181
ATOM   -0.150932
BCH    -0.293567
ICX    -0.236658
Name: 657, dtype: float64
熊式-----------------------------------
執行第 664
           664
XLM  -0.059293
ALGO -0.040238
BCH  -0.022023
NEO  -0.009276
ICX  -0.003156
TRX  -0.003111
ETH   0.001800
ATOM  0.005101
LTC   0.024389
BNB   0.028943
IOTA  0.029279
BAT   0.040819
ZRX   0.041956
XRP   0.068247
QTUM  0.068710
ZIL   0.075537
ZEC   0.117177
ADA   0.119482
VET   0.121067
LINK  0.164851
g================================================================          XLM   ALGO     BCH     NEO     ICX
0    0.07442  0.809  334.09  10.494  0.2002
1    0.06922  0.717  315.09   9.427  0.1862
2    0.07019  0.710  316.10   9.897  0.2011
3    0.06851  0.677  339.01   9.818  0.1925
4    0.06770  0.683  330.12   9.663  0.1975
..       ...    ...     ...     ...     ...
720      NaN    NaN     NaN     NaN     NaN
721      NaN    NaN     NaN     NaN     NaN
722      NaN    NaN     NaN     NaN     NaN
723      NaN    NaN     NaN     NaN     NaN
724      NaN    NaN     NaN     NaN     NaN

[725 rows x 5 columns]
XLM    -0.249857
ALGO   -0.252246
BCH    -0.433133
NEO    -0.407402
ICX    -0.404900
Name: 658, dtype: float64
報酬 -0.3495076308006549 %
i= XLM    -0.249857
ALGO   -0.252246
BCH    -0.433133
NEO    -0.407402
ICX    -0.404900
Name: 658, dtype: float64
熊式-----------------------------------
執行第 665
           665
BAT  -0.156927
ICX  -0.144310
NEO  -0.135678
IOTA -0.131197
ALGO -0.124866
ZIL  -0.115722
ZRX  -0.106207
ATOM -0.097558
BCH  -0.095182
LINK -0.094367
VET  -0.091955
ETH  -0.087163
TRX  -0.083855
LTC  -0.079690
QTUM -0.061801
XLM  -0.056652
BNB  -0.044383
ZEC  -0.027562
ADA  -0.024296
XRP  -0.020260
g================================================================         BAT     ICX     NEO    IOTA   ALGO
0    0.1972  0.2002  10.494  0.2564  0.809
1    0.1682  0.1862   9.427  0.2322  0.717
2    0.1870  0.2011   9.897  0.2428  0.710
3    0.1788  0.1925   9.818  0.2413  0.677
4    0.1764  0.1975   9.663  0.2422  0.683
..      ...     ...     ...     ...    ...
720     NaN     NaN     NaN     NaN    NaN
721     NaN     NaN     NaN     NaN    NaN
722     NaN     NaN     NaN     NaN    NaN
723     NaN     NaN     NaN     NaN    NaN
724     NaN     NaN     NaN     NaN    NaN

[725 rows x 5 columns]
BAT    -0.267387
ICX    -0.339153
NEO    -0.259821
IOTA   -0.324170
ALGO   -0.178656
Name: 659, dtype: float64
報酬 -0.27383754585671494 %
i= BAT    -0.267387
ICX    -0.339153
NEO    -0.259821
IOTA   -0.324170
ALGO   -0.178656
Name: 659, dtype: float64
熊式-----------------------------------
執行第 666
           666
QTUM -0.159917
NEO  -0.074398
BCH  -0.066833
BAT  -0.052932
LTC  -0.029700
LINK -0.028209
ETH  -0.013981
TRX  -0.013527
ICX  -0.010274
XLM   0.000024
ZIL   0.019582
VET   0.020463
ATOM  0.027830
ZRX   0.044370
ALGO  0.049804
XRP   0.056300
ADA   0.065779
BNB   0.091755
IOTA  0.098610
ZEC   0.102946
g================================================================       QTUM     NEO     BCH     BAT    LTC
0    2.642  10.494  334.09  0.1972  56.59
1    2.347   9.427  315.09  0.1682  54.82
2    2.376   9.897  316.10  0.1870  56.60
3    2.291   9.818  339.01  0.1788  55.28
4    2.455   9.663  330.12  0.1764  55.88
..     ...     ...     ...     ...    ...
720    NaN     NaN     NaN     NaN    NaN
721    NaN     NaN     NaN     NaN    NaN
722    NaN     NaN     NaN     NaN    NaN
723    NaN     NaN     NaN     NaN    NaN
724    NaN     NaN     NaN     NaN    NaN

[725 rows x 5 columns]
QTUM   -0.494949
NEO    -0.424681
BCH    -0.470263
BAT    -0.379508
LTC    -0.448791
Name: 660, dtype: float64
報酬 -0.4436387558051866 %
i= QTUM   -0.494949
NEO    -0.424681
BCH    -0.470263
BAT    -0.379508
LTC    -0.448791
Name: 660, dtype: float64
熊式-----------------------------------
執行第 667
           667
QTUM  0.022677
BCH   0.042758
ZEC   0.047428
XLM   0.065577
LTC   0.089251
BAT   0.108021
NEO   0.125381
TRX   0.139625
LINK  0.152221
XRP   0.161254
ICX   0.164504
ETH   0.180040
ADA   0.219694
ZRX   0.233192
ALGO  0.235255
ZIL   0.257555
BNB   0.298242
ATOM  0.308873
VET   0.321158
IOTA  0.322062
g================================================================       QTUM     BCH    ZEC      XLM    LTC
0    2.642  334.09  55.45  0.07442  56.59
1    2.347  315.09  50.56  0.06922  54.82
2    2.376  316.10  50.57  0.07019  56.60
3    2.291  339.01  48.85  0.06851  55.28
4    2.455  330.12  50.01  0.06770  55.88
..     ...     ...    ...      ...    ...
720    NaN     NaN    NaN      NaN    NaN
721    NaN     NaN    NaN      NaN    NaN
722    NaN     NaN    NaN      NaN    NaN
723    NaN     NaN    NaN      NaN    NaN
724    NaN     NaN    NaN      NaN    NaN

[725 rows x 5 columns]
QTUM   -0.513702
BCH    -0.459754
ZEC    -0.473762
XLM    -0.428744
LTC    -0.434793
Name: 661, dtype: float64
報酬 -0.4621509955526856 %
i= QTUM   -0.513702
BCH    -0.459754
ZEC    -0.473762
XLM    -0.428744
LTC    -0.434793
Name: 661, dtype: float64
熊式-----------------------------------
執行第 668
           668
QTUM  0.004267
BCH   0.030057
ZEC   0.044594
XLM   0.049510
LTC   0.092571
BAT   0.116696
TRX   0.122999
NEO   0.124415
ICX   0.131138
LINK  0.138067
XRP   0.167028
ETH   0.181490
ZRX   0.189508
ADA   0.219638
ALGO  0.242033
ATOM  0.250456
ZIL   0.271768
BNB   0.281688
IOTA  0.285744
VET   0.306269
g================================================================       QTUM     BCH    ZEC      XLM    LTC
0    2.642  334.09  55.45  0.07442  56.59
1    2.347  315.09  50.56  0.06922  54.82
2    2.376  316.10  50.57  0.07019  56.60
3    2.291  339.01  48.85  0.06851  55.28
4    2.455  330.12  50.01  0.06770  55.88
..     ...     ...    ...      ...    ...
720    NaN     NaN    NaN      NaN    NaN
721    NaN     NaN    NaN      NaN    NaN
722    NaN     NaN    NaN      NaN    NaN
723    NaN     NaN    NaN      NaN    NaN
724    NaN     NaN    NaN      NaN    NaN

[725 rows x 5 columns]
QTUM   -0.578100
BCH    -0.526458
ZEC    -0.565052
XLM    -0.488375
LTC    -0.519085
Name: 662, dtype: float64
報酬 -0.5354139169235618 %
i= QTUM   -0.578100
BCH    -0.526458
ZEC    -0.565052
XLM    -0.488375
LTC    -0.519085
Name: 662, dtype: float64
熊式-----------------------------------
執行第 669
           669
QTUM -0.042499
BCH  -0.018677
XLM   0.000961
LINK  0.009680
LTC   0.015139
XRP   0.018431
ZEC   0.025737
ICX   0.049090
TRX   0.050021
ADA   0.052612
BAT   0.066042
NEO   0.078783
ETH   0.101415
ZRX   0.111313
ZIL   0.143916
ALGO  0.149753
VET   0.163986
IOTA  0.177308
ATOM  0.180230
BNB   0.198169
g================================================================       QTUM     BCH      XLM  LINK    LTC
0    2.642  334.09  0.07442  2.42  56.59
1    2.347  315.09  0.06922  2.28  54.82
2    2.376  316.10  0.07019  2.42  56.60
3    2.291  339.01  0.06851  2.30  55.28
4    2.455  330.12  0.06770  2.40  55.88
..     ...     ...      ...   ...    ...
720    NaN     NaN      NaN   NaN    NaN
721    NaN     NaN      NaN   NaN    NaN
722    NaN     NaN      NaN   NaN    NaN
723    NaN     NaN      NaN   NaN    NaN
724    NaN     NaN      NaN   NaN    NaN

[725 rows x 5 columns]
QTUM   -0.353668
BCH    -0.298187
XLM    -0.316520
LINK   -0.291017
LTC    -0.345793
Name: 663, dtype: float64
報酬 -0.32103708946362997 %
i= QTUM   -0.353668
BCH    -0.298187
XLM    -0.316520
LINK   -0.291017
LTC    -0.345793
Name: 663, dtype: float64
熊式-----------------------------------
執行第 670
           670
LINK -0.141833
QTUM -0.109652
XRP  -0.092228
ZEC  -0.079066
BCH  -0.067586
LTC  -0.063188
XLM  -0.055710
ADA  -0.035634
BAT  -0.006515
ETH   0.001417
TRX   0.007021
NEO   0.012865
VET   0.014272
ICX   0.014336
ZRX   0.040952
ZIL   0.067208
ATOM  0.079694
ALGO  0.092490
BNB   0.111582
IOTA  0.123564
g================================================================      LINK   QTUM      XRP    ZEC     BCH
0    2.42  2.642  0.29787  55.45  334.09
1    2.28  2.347  0.26338  50.56  315.09
2    2.42  2.376  0.26408  50.57  316.10
3    2.30  2.291  0.26055  48.85  339.01
4    2.40  2.455  0.26543  50.01  330.12
..    ...    ...      ...    ...     ...
720   NaN    NaN      NaN    NaN     NaN
721   NaN    NaN      NaN    NaN     NaN
722   NaN    NaN      NaN    NaN     NaN
723   NaN    NaN      NaN    NaN     NaN
724   NaN    NaN      NaN    NaN     NaN

[725 rows x 5 columns]
LINK   -0.352914
QTUM   -0.357810
XRP    -0.387401
ZEC    -0.430191
BCH    -0.341132
Name: 664, dtype: float64
報酬 -0.3738895942072429 %
i= LINK   -0.352914
QTUM   -0.357810
XRP    -0.387401
ZEC    -0.430191
BCH    -0.341132
Name: 664, dtype: float64
熊式-----------------------------------
執行第 671
           671
LINK -0.199609
QTUM -0.180027
XLM  -0.171364
XRP  -0.145543
BCH  -0.136420
ZEC  -0.118368
LTC  -0.114907
ADA  -0.097873
ICX  -0.092800
ZRX  -0.071783
BAT  -0.071323
ZIL  -0.058784
TRX  -0.058175
NEO  -0.054679
VET  -0.051337
ATOM -0.021024
IOTA -0.020450
ETH  -0.015876
BNB  -0.011756
ALGO  0.076313
g================================================================      LINK   QTUM      XLM      XRP     BCH
0    2.42  2.642  0.07442  0.29787  334.09
1    2.28  2.347  0.06922  0.26338  315.09
2    2.42  2.376  0.07019  0.26408  316.10
3    2.30  2.291  0.06851  0.26055  339.01
4    2.40  2.455  0.06770  0.26543  330.12
..    ...    ...      ...      ...     ...
720   NaN    NaN      NaN      NaN     NaN
721   NaN    NaN      NaN      NaN     NaN
722   NaN    NaN      NaN      NaN     NaN
723   NaN    NaN      NaN      NaN     NaN
724   NaN    NaN      NaN      NaN     NaN

[725 rows x 5 columns]
LINK    0.281557
QTUM    0.154304
XLM    -0.003640
XRP    -0.028168
BCH     0.091361
Name: 665, dtype: float64
報酬 0.09908286693557589 %
i= LINK    0.281557
QTUM    0.154304
XLM    -0.003640
XRP    -0.028168
BCH     0.091361
Name: 665, dtype: float64
熊式-----------------------------------
執行第 672
           672
QTUM -0.222443
LINK -0.213633
ZEC  -0.201643
ICX  -0.170044
ZRX  -0.166972
XLM  -0.164549
BAT  -0.157373
NEO  -0.154795
XRP  -0.146915
BCH  -0.145362
LTC  -0.142308
ZIL  -0.121880
BNB  -0.120992
IOTA -0.100305
VET  -0.099069
ADA  -0.097484
ATOM -0.083182
ALGO -0.074158
ETH  -0.072654
TRX  -0.070358
g================================================================       QTUM  LINK    ZEC     ICX     ZRX
0    2.642  2.42  55.45  0.2002  0.1814
1    2.347  2.28  50.56  0.1862  0.1624
2    2.376  2.42  50.57  0.2011  0.1736
3    2.291  2.30  48.85  0.1925  0.1751
4    2.455  2.40  50.01  0.1975  0.1711
..     ...   ...    ...     ...     ...
720    NaN   NaN    NaN     NaN     NaN
721    NaN   NaN    NaN     NaN     NaN
722    NaN   NaN    NaN     NaN     NaN
723    NaN   NaN    NaN     NaN     NaN
724    NaN   NaN    NaN     NaN     NaN

[725 rows x 5 columns]
QTUM    0.056669
LINK    0.028693
ZEC    -0.181803
ICX    -0.114768
ZRX    -0.050519
Name: 666, dtype: float64
報酬 -0.052345826707641964 %
i= QTUM    0.056669
LINK    0.028693
ZEC    -0.181803
ICX    -0.114768
ZRX    -0.050519
Name: 666, dtype: float64
熊式-----------------------------------
執行第 673
           673
LINK -0.205160
QTUM -0.198920
ZRX  -0.188760
ZIL  -0.174821
ICX  -0.168723
NEO  -0.163103
ATOM -0.161634
ZEC  -0.161089
VET  -0.160636
BAT  -0.151303
IOTA -0.144192
XLM  -0.141338
BNB  -0.122278
XRP  -0.119613
ADA  -0.119395
BCH  -0.118851
LTC  -0.107074
ETH  -0.085527
TRX  -0.082450
ALGO -0.060991
g================================================================      LINK   QTUM     ZRX      ZIL     ICX
0    2.42  2.642  0.1814  0.00879  0.2002
1    2.28  2.347  0.1624  0.00762  0.1862
2    2.42  2.376  0.1736  0.00749  0.2011
3    2.30  2.291  0.1751  0.00732  0.1925
4    2.40  2.455  0.1711  0.00773  0.1975
..    ...    ...     ...      ...     ...
720   NaN    NaN     NaN      NaN     NaN
721   NaN    NaN     NaN      NaN     NaN
722   NaN    NaN     NaN      NaN     NaN
723   NaN    NaN     NaN      NaN     NaN
724   NaN    NaN     NaN      NaN     NaN

[725 rows x 5 columns]
LINK    0.092759
QTUM    0.092523
ZRX    -0.070576
ZIL    -0.027461
ICX    -0.151396
Name: 667, dtype: float64
報酬 -0.012830180822499492 %
i= LINK    0.092759
QTUM    0.092523
ZRX    -0.070576
ZIL    -0.027461
ICX    -0.151396
Name: 667, dtype: float64
熊式-----------------------------------
執行第 674
           674
LINK -0.198960
ATOM -0.149158
ZIL  -0.145071
QTUM -0.139949
ICX  -0.139296
ZEC  -0.138485
VET  -0.133447
ZRX  -0.129415
BAT  -0.125691
XLM  -0.119691
IOTA -0.112635
ADA  -0.103967
XRP  -0.103808
BCH  -0.103643
NEO  -0.102079
BNB  -0.100404
ETH  -0.081242
LTC  -0.060664
TRX  -0.059624
ALGO  0.017494

g================================================================      LINK   ATOM      ZIL   QTUM     ICX
0    2.42  3.258  0.00879  2.642  0.2002
1    2.28  2.857  0.00762  2.347  0.1862
2    2.42  2.898  0.00749  2.376  0.2011
3    2.30  2.884  0.00732  2.291  0.1925
4    2.40  2.910  0.00773  2.455  0.1975
..    ...    ...      ...    ...     ...
720   NaN    NaN      NaN    NaN     NaN
721   NaN    NaN      NaN    NaN     NaN
722   NaN    NaN      NaN    NaN     NaN
723   NaN    NaN      NaN    NaN     NaN
724   NaN    NaN      NaN    NaN     NaN

[725 rows x 5 columns]
LINK    0.088918
ATOM   -0.014869
ZIL    -0.049049
QTUM    0.161007
ICX    -0.108552
Name: 668, dtype: float64
報酬 0.015490912791859147 %
i= LINK    0.088918
ATOM   -0.014869
ZIL    -0.049049
QTUM    0.161007
ICX    -0.108552
Name: 668, dtype: float64
熊式-----------------------------------
執行第 675
           675
LINK -0.207965
ATOM -0.196905
ZEC  -0.189678
ICX  -0.183198
QTUM -0.171502
ZRX  -0.169212
VET  -0.164044
ZIL  -0.151553
XLM  -0.151168
NEO  -0.147731
IOTA -0.145420
BAT  -0.139488
ADA  -0.134210
BNB  -0.114535
BCH  -0.111621
ETH  -0.105572
TRX  -0.084822
XRP  -0.081708
LTC  -0.059827
ALGO -0.005325
g================================================================      LINK   ATOM    ZEC     ICX   QTUM
0    2.42  3.258  55.45  0.2002  2.642
1    2.28  2.857  50.56  0.1862  2.347
2    2.42  2.898  50.57  0.2011  2.376
3    2.30  2.884  48.85  0.1925  2.291
4    2.40  2.910  50.01  0.1975  2.455
..    ...    ...    ...     ...    ...
720   NaN    NaN    NaN     NaN    NaN
721   NaN    NaN    NaN     NaN    NaN
722   NaN    NaN    NaN     NaN    NaN
723   NaN    NaN    NaN     NaN    NaN
724   NaN    NaN    NaN     NaN    NaN

[725 rows x 5 columns]
LINK    0.351787
ATOM    0.078062
ZEC     0.312161
ICX     0.080373
QTUM    0.400417
Name: 669, dtype: float64
報酬 0.24455992941383312 %
i= LINK    0.351787
ATOM    0.078062
ZEC     0.312161
ICX     0.080373
QTUM    0.400417
Name: 669, dtype: float64
熊式-----------------------------------
執行第 676
           676
ATOM -0.231034
QTUM -0.223962
ICX  -0.222058
LINK -0.212859
ZIL  -0.200178
ZRX  -0.197835
BAT  -0.191213
IOTA -0.187605
NEO  -0.184225
VET  -0.171279
ZEC  -0.158191
XLM  -0.138438
ETH  -0.128077
BNB  -0.127060
TRX  -0.122014
XRP  -0.120119
ADA  -0.118195
BCH  -0.116656
LTC  -0.083163
ALGO -0.035055
g================================================================       ATOM   QTUM     ICX  LINK      ZIL
0    3.258  2.642  0.2002  2.42  0.00879
1    2.857  2.347  0.1862  2.28  0.00762
2    2.898  2.376  0.2011  2.42  0.00749
3    2.884  2.291  0.1925  2.30  0.00732
4    2.910  2.455  0.1975  2.40  0.00773
..     ...    ...     ...   ...      ...
720    NaN    NaN     NaN   NaN      NaN
721    NaN    NaN     NaN   NaN      NaN
722    NaN    NaN     NaN   NaN      NaN
723    NaN    NaN     NaN   NaN      NaN
724    NaN    NaN     NaN   NaN      NaN

[725 rows x 5 columns]
ATOM   -0.032902
QTUM    0.104172
ICX    -0.031681
LINK    0.216995
ZIL     0.061921
Name: 670, dtype: float64
報酬 0.0637009973419627 %
i= ATOM   -0.032902
QTUM    0.104172
ICX    -0.031681
LINK    0.216995
ZIL     0.061921
Name: 670, dtype: float64
熊式-----------------------------------
執行第 677
           677
ICX  -0.087844
ATOM -0.070967
BAT  -0.065418
ZRX  -0.058552
LINK -0.051261
QTUM -0.046303
NEO  -0.035293
ETH  -0.032144
ZIL  -0.029428
ZEC  -0.022879
VET  -0.018329
XLM  -0.005597
IOTA -0.004376
ADA  -0.004025
TRX  -0.001813
BNB   0.021558
XRP   0.022811
BCH   0.029020
LTC   0.055586
ALGO  0.079622
g================================================================         ICX   ATOM     BAT     ZRX  LINK
0    0.2002  3.258  0.1972  0.1814  2.42
1    0.1862  2.857  0.1682  0.1624  2.28
2    0.2011  2.898  0.1870  0.1736  2.42
3    0.1925  2.884  0.1788  0.1751  2.30
4    0.1975  2.910  0.1764  0.1711  2.40
..      ...    ...     ...     ...   ...
720     NaN    NaN     NaN     NaN   NaN
721     NaN    NaN     NaN     NaN   NaN
722     NaN    NaN     NaN     NaN   NaN
723     NaN    NaN     NaN     NaN   NaN
724     NaN    NaN     NaN     NaN   NaN

[725 rows x 5 columns]
ICX     0.003332
ATOM   -0.012500
BAT     0.013426
ZRX     0.048081
LINK    0.115105
Name: 671, dtype: float64
報酬 0.03348865596066486 %
i= ICX     0.003332
ATOM   -0.012500
BAT     0.013426
ZRX     0.048081
LINK    0.115105
Name: 671, dtype: float64
熊式-----------------------------------
執行第 678
           678
ZRX  -0.047544
ATOM -0.027476
ICX  -0.021739
XLM  -0.020010
IOTA -0.019710
TRX  -0.007168
ADA  -0.004108
BAT   0.000596
VET   0.001325
QTUM  0.003722
XRP   0.018766
ZIL   0.020026
ETH   0.029678
LINK  0.035255
NEO   0.041480
BNB   0.049692
ZEC   0.058913
BCH   0.074423
ALGO  0.119457
LTC   0.121014
g================================================================         ZRX   ATOM     ICX      XLM    IOTA
0    0.1814  3.258  0.2002  0.07442  0.2564
1    0.1624  2.857  0.1862  0.06922  0.2322
2    0.1736  2.898  0.2011  0.07019  0.2428
3    0.1751  2.884  0.1925  0.06851  0.2413
4    0.1711  2.910  0.1975  0.06770  0.2422
..      ...    ...     ...      ...     ...
720     NaN    NaN     NaN      NaN     NaN
721     NaN    NaN     NaN      NaN     NaN
722     NaN    NaN     NaN      NaN     NaN
723     NaN    NaN     NaN      NaN     NaN
724     NaN    NaN     NaN      NaN     NaN

[725 rows x 5 columns]
ZRX    -0.002089
ATOM   -0.025276
ICX    -0.092418
XLM    -0.055682
IOTA   -0.006828
Name: 672, dtype: float64
報酬 -0.036458561162092964 %
i= ZRX    -0.002089
ATOM   -0.025276
ICX    -0.092418
XLM    -0.055682
IOTA   -0.006828
Name: 672, dtype: float64
熊式-----------------------------------
執行第 679
           679
XLM  -0.085726
ZRX  -0.073004
VET  -0.071131
ATOM -0.070029
QTUM -0.067740
ZIL  -0.066678
XRP  -0.057217
ZEC  -0.056668
IOTA -0.052747
TRX  -0.047252
LINK -0.041846
ADA  -0.041438
ETH  -0.024842
BNB  -0.022624
NEO  -0.021804
BAT  -0.017629
ALGO -0.009594
BCH  -0.008956
LTC   0.017354
ICX   0.059646
g================================================================          XLM     ZRX       VET   ATOM   QTUM
0    0.07442  0.1814  0.004916  3.258  2.642
1    0.06922  0.1624  0.004628  2.857  2.347
2    0.07019  0.1736  0.004580  2.898  2.376
3    0.06851  0.1751  0.004493  2.884  2.291
4    0.06770  0.1711  0.004454  2.910  2.455
..       ...     ...       ...    ...    ...
720      NaN     NaN       NaN    NaN    NaN
721      NaN     NaN       NaN    NaN    NaN
722      NaN     NaN       NaN    NaN    NaN
723      NaN     NaN       NaN    NaN    NaN
724      NaN     NaN       NaN    NaN    NaN

[725 rows x 5 columns]
XLM     0.015213
ZRX     0.084548
VET     0.160130
ATOM    0.150848
QTUM   -0.138451
Name: 673, dtype: float64
報酬 0.05445772292976379 %
i= XLM     0.015213
ZRX     0.084548
VET     0.160130
ATOM    0.150848
QTUM   -0.138451
Name: 673, dtype: float64
熊式-----------------------------------
執行第 680
           680
QTUM -0.105290
ZRX  -0.068692
XLM  -0.062092
TRX  -0.049897
IOTA -0.042670
XRP  -0.041911
ETH  -0.041510
VET  -0.039661
ZIL  -0.038284
NEO  -0.036634
ADA  -0.031277
ALGO -0.028656
BCH  -0.012858
BAT  -0.012645
BNB  -0.012094
LTC  -0.007685
LINK -0.002596
ZEC   0.021119
ICX   0.023192
ATOM  0.045834
g================================================================       QTUM     ZRX      XLM      TRX    IOTA
0    2.642  0.1814  0.07442  0.02049  0.2564
1    2.347  0.1624  0.06922  0.01778  0.2322
2    2.376  0.1736  0.07019  0.01752  0.2428
3    2.291  0.1751  0.06851  0.01688  0.2413
4    2.455  0.1711  0.06770  0.01692  0.2422
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
QTUM   -0.068442
ZRX     0.108671
XLM    -0.035546
TRX     0.070784
IOTA    0.201743
Name: 674, dtype: float64
報酬 0.05544204525364671 %
i= QTUM   -0.068442
ZRX     0.108671
XLM    -0.035546
TRX     0.070784
IOTA    0.201743
Name: 674, dtype: float64
熊式-----------------------------------
執行第 681
           681
QTUM -0.047498
XRP  -0.007316
XLM  -0.002514
ETH   0.008203
ZRX   0.010635
ZIL   0.012332
BAT   0.018424
BNB   0.020960
VET   0.023885
NEO   0.026236
LTC   0.026622
ADA   0.031267
BCH   0.037543
IOTA  0.057396
TRX   0.067235
LINK  0.087058
ALGO  0.095635
ATOM  0.139052
ZEC   0.141024
ICX   0.186131
g================================================================       QTUM      XRP      XLM     ETH     ZRX
0    2.642  0.29787  0.07442  209.22  0.1814
1    2.347  0.26338  0.06922  187.11  0.1624
2    2.376  0.26408  0.07019  188.16  0.1736
3    2.291  0.26055  0.06851  185.03  0.1751
4    2.455  0.26543  0.06770  185.61  0.1711
..     ...      ...      ...     ...     ...
720    NaN      NaN      NaN     NaN     NaN
721    NaN      NaN      NaN     NaN     NaN
722    NaN      NaN      NaN     NaN     NaN
723    NaN      NaN      NaN     NaN     NaN
724    NaN      NaN      NaN     NaN     NaN

[725 rows x 5 columns]
QTUM   -0.028625
XRP     0.111272
XLM     0.022614
ETH     0.155604
ZRX     0.157386
Name: 675, dtype: float64
報酬 0.08365018395545076 %
i= QTUM   -0.028625
XRP     0.111272
XLM     0.022614
ETH     0.155604
ZRX     0.157386
Name: 675, dtype: float64
熊式-----------------------------------
執行第 682
           682
XLM  -0.095318
QTUM -0.065299
VET  -0.063768
ETH  -0.057807
ZRX  -0.048574
ADA  -0.043799
XRP  -0.043180
LTC  -0.033288
BCH  -0.030293
ZIL  -0.027932
LINK -0.023073
NEO  -0.019225
BNB  -0.019025
BAT  -0.013297
IOTA -0.010519
ALGO -0.000101
TRX   0.020735
ZEC   0.050954
ATOM  0.067493
ICX   0.094182
g================================================================          XLM   QTUM       VET     ETH     ZRX
0    0.07442  2.642  0.004916  209.22  0.1814
1    0.06922  2.347  0.004628  187.11  0.1624
2    0.07019  2.376  0.004580  188.16  0.1736
3    0.06851  2.291  0.004493  185.03  0.1751
4    0.06770  2.455  0.004454  185.61  0.1711
..       ...    ...       ...     ...     ...
720      NaN    NaN       NaN     NaN     NaN
721      NaN    NaN       NaN     NaN     NaN
722      NaN    NaN       NaN     NaN     NaN
723      NaN    NaN       NaN     NaN     NaN
724      NaN    NaN       NaN     NaN     NaN

[725 rows x 5 columns]
XLM     0.016047
QTUM   -0.031633
VET     0.189179
ETH     0.136988
ZRX     0.133938
Name: 676, dtype: float64
報酬 0.08890375138534468 %
i= XLM     0.016047
QTUM   -0.031633
VET     0.189179
ETH     0.136988
ZRX     0.133938
Name: 676, dtype: float64
熊式-----------------------------------
執行第 683
           683
QTUM -0.168361
XLM  -0.160211
VET  -0.139593
XRP  -0.139364
ETH  -0.136199
ZIL  -0.135930
LINK -0.129074
ZRX  -0.119037
IOTA -0.115740
ADA  -0.110085
LTC  -0.106021
BCH  -0.099831
ALGO -0.098750
NEO  -0.096380
BNB  -0.086734
BAT  -0.080173
ATOM -0.049832
TRX  -0.044280
ZEC  -0.034257
ICX   0.008976
g================================================================       QTUM      XLM       VET      XRP     ETH
0    2.642  0.07442  0.004916  0.29787  209.22
1    2.347  0.06922  0.004628  0.26338  187.11
2    2.376  0.07019  0.004580  0.26408  188.16
3    2.291  0.06851  0.004493  0.26055  185.03
4    2.455  0.06770  0.004454  0.26543  185.61
..     ...      ...       ...      ...     ...
720    NaN      NaN       NaN      NaN     NaN
721    NaN      NaN       NaN      NaN     NaN
722    NaN      NaN       NaN      NaN     NaN
723    NaN      NaN       NaN      NaN     NaN
724    NaN      NaN       NaN      NaN     NaN

[725 rows x 5 columns]
QTUM   -0.218740
XLM    -0.139883
VET    -0.091579
XRP    -0.170333
ETH    -0.043648

Name: 677, dtype: float64
報酬 -0.13283678684972858 %
i= QTUM   -0.218740
XLM    -0.139883
VET    -0.091579
XRP    -0.170333
ETH    -0.043648
Name: 677, dtype: float64
熊式-----------------------------------
執行第 684
           684
QTUM -0.199195
IOTA -0.149424
LTC  -0.139786
ZIL  -0.135438
XLM  -0.133277
LINK -0.132612
VET  -0.131869
BCH  -0.131697
ETH  -0.131155
ZRX  -0.130621
XRP  -0.129956
NEO  -0.120528
ALGO -0.115428
BAT  -0.105467
ATOM -0.095029
ADA  -0.094180
BNB  -0.083736
TRX  -0.060539
ZEC  -0.051461
ICX  -0.025266
g================================================================       QTUM    IOTA    LTC      ZIL      XLM
0    2.642  0.2564  56.59  0.00879  0.07442
1    2.347  0.2322  54.82  0.00762  0.06922
2    2.376  0.2428  56.60  0.00749  0.07019
3    2.291  0.2413  55.28  0.00732  0.06851
4    2.455  0.2422  55.88  0.00773  0.06770
..     ...     ...    ...      ...      ...
720    NaN     NaN    NaN      NaN      NaN
721    NaN     NaN    NaN      NaN      NaN
722    NaN     NaN    NaN      NaN      NaN
723    NaN     NaN    NaN      NaN      NaN
724    NaN     NaN    NaN      NaN      NaN

[725 rows x 5 columns]
QTUM   -0.204888
IOTA    0.028487
LTC    -0.122287
ZIL    -0.082162
XLM    -0.163690
Name: 678, dtype: float64
報酬 -0.10890787904784979 %
i= QTUM   -0.204888
IOTA    0.028487
LTC    -0.122287
ZIL    -0.082162
XLM    -0.163690
Name: 678, dtype: float64
熊式-----------------------------------
執行第 685
           685
QTUM -0.408551
NEO  -0.360209
VET  -0.340874
IOTA -0.329728
ZRX  -0.325961
ICX  -0.324991
ZIL  -0.323864
XRP  -0.300335
XLM  -0.293368
LTC  -0.288567
LINK -0.286531
BCH  -0.274386
ALGO -0.267074
ATOM -0.263328
BAT  -0.260926
BNB  -0.258820
ZEC  -0.257408
ETH  -0.256518
TRX  -0.252856
ADA  -0.244925
g================================================================       QTUM     NEO       VET    IOTA     ZRX
0    2.642  10.494  0.004916  0.2564  0.1814
1    2.347   9.427  0.004628  0.2322  0.1624
2    2.376   9.897  0.004580  0.2428  0.1736
3    2.291   9.818  0.004493  0.2413  0.1751
4    2.455   9.663  0.004454  0.2422  0.1711
..     ...     ...       ...     ...     ...
720    NaN     NaN       NaN     NaN     NaN
721    NaN     NaN       NaN     NaN     NaN
722    NaN     NaN       NaN     NaN     NaN
723    NaN     NaN       NaN     NaN     NaN
724    NaN     NaN       NaN     NaN     NaN

[725 rows x 5 columns]
QTUM   -0.178450
NEO    -0.111383
VET    -0.045755
IOTA   -0.077338
ZRX    -0.157550
Name: 679, dtype: float64
報酬 -0.1140951612431806 %
i= QTUM   -0.178450
NEO    -0.111383
VET    -0.045755
IOTA   -0.077338
ZRX    -0.157550
Name: 679, dtype: float64
熊式-----------------------------------
執行第 686
           686
QTUM -0.426665
NEO  -0.382467
XRP  -0.342867
ZIL  -0.341250
ZRX  -0.336983
VET  -0.335597
ATOM -0.331594
IOTA -0.329455
ICX  -0.298723
LTC  -0.282841
LINK -0.271150
ALGO -0.270528
BAT  -0.263455
XLM  -0.262797
TRX  -0.261860
BCH  -0.253206
BNB  -0.246867
ZEC  -0.225608
ADA  -0.221151
ETH  -0.207608
g================================================================       QTUM     NEO      XRP      ZIL     ZRX
0    2.642  10.494  0.29787  0.00879  0.1814
1    2.347   9.427  0.26338  0.00762  0.1624
2    2.376   9.897  0.26408  0.00749  0.1736
3    2.291   9.818  0.26055  0.00732  0.1751
4    2.455   9.663  0.26543  0.00773  0.1711
..     ...     ...      ...      ...     ...
720    NaN     NaN      NaN      NaN     NaN
721    NaN     NaN      NaN      NaN     NaN
722    NaN     NaN      NaN      NaN     NaN
723    NaN     NaN      NaN      NaN     NaN
724    NaN     NaN      NaN      NaN     NaN

[725 rows x 5 columns]
QTUM   -0.216578
NEO    -0.175752
XRP    -0.168263
ZIL    -0.224247
ZRX    -0.217322
Name: 680, dtype: float64
報酬 -0.2004323737244123 %
i= QTUM   -0.216578
NEO    -0.175752
XRP    -0.168263
ZIL    -0.224247
ZRX    -0.217322
Name: 680, dtype: float64
熊式-----------------------------------
執行第 687
           687
QTUM -0.317755
NEO  -0.311139
ATOM -0.294896
VET  -0.289447
ZIL  -0.288118
IOTA -0.275046
ICX  -0.266946
ZRX  -0.264898
XRP  -0.241203
LTC  -0.227572
ALGO -0.218266
ZEC  -0.215692
TRX  -0.215282
LINK -0.213704
BCH  -0.210207
XLM  -0.195142
ETH  -0.169491
BAT  -0.163576
BNB  -0.160211
ADA  -0.155581
g================================================================       QTUM     NEO   ATOM       VET      ZIL
0    2.642  10.494  3.258  0.004916  0.00879
1    2.347   9.427  2.857  0.004628  0.00762
2    2.376   9.897  2.898  0.004580  0.00749
3    2.291   9.818  2.884  0.004493  0.00732
4    2.455   9.663  2.910  0.004454  0.00773
..     ...     ...    ...       ...      ...
720    NaN     NaN    NaN       NaN      NaN
721    NaN     NaN    NaN       NaN      NaN
722    NaN     NaN    NaN       NaN      NaN
723    NaN     NaN    NaN       NaN      NaN
724    NaN     NaN    NaN       NaN      NaN

[725 rows x 5 columns]
QTUM   -0.198637
NEO    -0.156914
ATOM   -0.208250
VET    -0.189798
ZIL    -0.192268
Name: 681, dtype: float64
報酬 -0.1891734735843899 %
i= QTUM   -0.198637
NEO    -0.156914
ATOM   -0.208250
VET    -0.189798
ZIL    -0.192268
Name: 681, dtype: float64
熊式-----------------------------------
執行第 688
           688
QTUM -0.230539
NEO  -0.228690
VET  -0.187506
ZRX  -0.183253
ZIL  -0.178240
ICX  -0.172252
IOTA -0.167909
ATOM -0.163468
XRP  -0.154997
ZEC  -0.146963
LTC  -0.139401
BCH  -0.135012
ALGO -0.116385
ETH  -0.108023
LINK -0.100142
XLM  -0.095550
BNB  -0.084494
BAT  -0.058012
TRX  -0.048552
ADA  -0.039292
g================================================================       QTUM     NEO       VET     ZRX      ZIL
0    2.642  10.494  0.004916  0.1814  0.00879
1    2.347   9.427  0.004628  0.1624  0.00762
2    2.376   9.897  0.004580  0.1736  0.00749
3    2.291   9.818  0.004493  0.1751  0.00732
4    2.455   9.663  0.004454  0.1711  0.00773
..     ...     ...       ...     ...      ...
720    NaN     NaN       NaN     NaN      NaN
721    NaN     NaN       NaN     NaN      NaN
722    NaN     NaN       NaN     NaN      NaN
723    NaN     NaN       NaN     NaN      NaN
724    NaN     NaN       NaN     NaN      NaN

[725 rows x 5 columns]
QTUM   -0.215155
NEO    -0.168815
VET    -0.153342
ZRX    -0.181504
ZIL    -0.179455
Name: 682, dtype: float64
報酬 -0.1796542459258057 %
i= QTUM   -0.215155
NEO    -0.168815
VET    -0.153342
ZRX    -0.181504
ZIL    -0.179455
Name: 682, dtype: float64
熊式-----------------------------------
執行第 689
           689
NEO  -0.294474
QTUM -0.281108
ZIL  -0.253997
VET  -0.253694
ICX  -0.241444
ATOM -0.234195
ZRX  -0.233932
ZEC  -0.217822
IOTA -0.199751
XRP  -0.195212
BCH  -0.185916
LTC  -0.179004
LINK -0.168390
XLM  -0.165417
ETH  -0.164375
BNB  -0.158485
ALGO -0.153419
BAT  -0.131411
TRX  -0.102017
ADA  -0.095444
g================================================================         NEO   QTUM      ZIL       VET     ICX
0    10.494  2.642  0.00879  0.004916  0.2002
1     9.427  2.347  0.00762  0.004628  0.1862
2     9.897  2.376  0.00749  0.004580  0.2011
3     9.818  2.291  0.00732  0.004493  0.1925
4     9.663  2.455  0.00773  0.004454  0.1975
..      ...    ...      ...       ...     ...
720     NaN    NaN      NaN       NaN     NaN
721     NaN    NaN      NaN       NaN     NaN
722     NaN    NaN      NaN       NaN     NaN
723     NaN    NaN      NaN       NaN     NaN
724     NaN    NaN      NaN       NaN     NaN

[725 rows x 5 columns]
NEO    -0.132043
QTUM   -0.163153
ZIL    -0.127003
VET    -0.120779
ICX    -0.178878
Name: 683, dtype: float64
報酬 -0.14437117094594354 %
i= NEO    -0.132043
QTUM   -0.163153
ZIL    -0.127003
VET    -0.120779
ICX    -0.178878
Name: 683, dtype: float64
熊式-----------------------------------
執行第 690
           690
NEO  -0.303888
ZIL  -0.266953
VET  -0.249238
ICX  -0.244431
ZRX  -0.240293
QTUM -0.229426
LINK -0.217090
ZEC  -0.214584
XRP  -0.203718
ATOM -0.199499
ETH  -0.184248
LTC  -0.181037
IOTA -0.179944
BNB  -0.175877
BCH  -0.173683
XLM  -0.162387
BAT  -0.148876
ALGO -0.132955
ADA  -0.123100
TRX  -0.073308
g================================================================         NEO      ZIL       VET     ICX     ZRX
0    10.494  0.00879  0.004916  0.2002  0.1814
1     9.427  0.00762  0.004628  0.1862  0.1624
2     9.897  0.00749  0.004580  0.2011  0.1736
3     9.818  0.00732  0.004493  0.1925  0.1751
4     9.663  0.00773  0.004454  0.1975  0.1711
..      ...      ...       ...     ...     ...
720     NaN      NaN       NaN     NaN     NaN
721     NaN      NaN       NaN     NaN     NaN
722     NaN      NaN       NaN     NaN     NaN
723     NaN      NaN       NaN     NaN     NaN
724     NaN      NaN       NaN     NaN     NaN

[725 rows x 5 columns]
NEO   -0.004078
ZIL   -0.005310
VET   -0.010474
ICX   -0.050761
ZRX   -0.045645
Name: 684, dtype: float64
報酬 -0.023253627123231223 %
i= NEO   -0.004078
ZIL   -0.005310
VET   -0.010474
ICX   -0.050761
ZRX   -0.045645
Name: 684, dtype: float64
熊式-----------------------------------
執行第 691
           691
ICX  -0.011110
ZIL  -0.007164
NEO  -0.003241
ETH   0.046485
BCH   0.048545
LINK  0.050915
ATOM  0.055090
ZRX   0.056513
BAT   0.059330
ZEC   0.059809
VET   0.060338
LTC   0.062550
IOTA  0.062808
XRP   0.067612
BNB   0.070039
XLM   0.098427
ALGO  0.101507
QTUM  0.122307
ADA   0.135602
TRX   0.207160
g================================================================         ICX      ZIL     NEO     ETH     BCH
0    0.2002  0.00879  10.494  209.22  334.09
1    0.1862  0.00762   9.427  187.11  315.09
2    0.2011  0.00749   9.897  188.16  316.10
3    0.1925  0.00732   9.818  185.03  339.01
4    0.1975  0.00773   9.663  185.61  330.12
..      ...      ...     ...     ...     ...
720     NaN      NaN     NaN     NaN     NaN
721     NaN      NaN     NaN     NaN     NaN
722     NaN      NaN     NaN     NaN     NaN
723     NaN      NaN     NaN     NaN     NaN
724     NaN      NaN     NaN     NaN     NaN

[725 rows x 5 columns]
ICX    0.098670
ZIL   -0.009228
NEO    0.028440
ETH    0.014464
BCH    0.052596
Name: 685, dtype: float64
報酬 0.03698833193970634 %
i= ICX    0.098670
ZIL   -0.009228
NEO    0.028440
ETH    0.014464
BCH    0.052596
Name: 685, dtype: float64
熊式-----------------------------------
執行第 692
           692
ICX   0.075512
NEO   0.103818
BNB   0.108548
ETH   0.110551
VET   0.110738
ZEC   0.110797
LINK  0.118452
XLM   0.125246
BCH   0.130853
ALGO  0.132920
IOTA  0.146516
ADA   0.146603
BAT   0.151521
LTC   0.152449
ZIL   0.165961
XRP   0.177579
ATOM  0.213537
ZRX   0.217452
QTUM  0.265249
TRX   0.282822
g================================================================         ICX     NEO    BNB     ETH       VET
0    0.2002  10.494  29.42  209.22  0.004916
1    0.1862   9.427  27.01  187.11  0.004628
2    0.2011   9.897  28.11  188.16  0.004580
3    0.1925   9.818  27.53  185.03  0.004493
4    0.1975   9.663  27.50  185.61  0.004454
..      ...     ...    ...     ...       ...
720     NaN     NaN    NaN     NaN       NaN
721     NaN     NaN    NaN     NaN       NaN
722     NaN     NaN    NaN     NaN       NaN
723     NaN     NaN    NaN     NaN       NaN
724     NaN     NaN    NaN     NaN       NaN

[725 rows x 5 columns]
ICX   -0.032743
NEO   -0.051195
BNB   -0.074933
ETH   -0.092863
VET   -0.103486
Name: 686, dtype: float64
報酬 -0.07104382507878945 %
i= ICX   -0.032743
NEO   -0.051195
BNB   -0.074933
ETH   -0.092863
VET   -0.103486
Name: 686, dtype: float64
熊式-----------------------------------
執行第 693
           693
BNB   0.012257
ICX   0.034851
NEO   0.043347
IOTA  0.058543
LINK  0.059368
BAT   0.061250
ALGO  0.063101
ETH   0.096195
ADA   0.097401
XLM   0.099111
BCH   0.103581
XRP   0.106220
LTC   0.113816
ZRX   0.123386
ZEC   0.127196
ZIL   0.163113
TRX   0.168163
VET   0.182534
ATOM  0.206821
QTUM  0.286079
g================================================================        BNB     ICX     NEO    IOTA  LINK
0    29.42  0.2002  10.494  0.2564  2.42
1    27.01  0.1862   9.427  0.2322  2.28
2    28.11  0.2011   9.897  0.2428  2.42
3    27.53  0.1925   9.818  0.2413  2.30
4    27.50  0.1975   9.663  0.2422  2.40
..     ...     ...     ...     ...   ...
720    NaN     NaN     NaN     NaN   NaN
721    NaN     NaN     NaN     NaN   NaN
722    NaN     NaN     NaN     NaN   NaN
723    NaN     NaN     NaN     NaN   NaN
724    NaN     NaN     NaN     NaN   NaN

[725 rows x 5 columns]
BNB     0.003586
ICX     0.086186
NEO    -0.036436
IOTA   -0.013654
LINK    0.010385
Name: 687, dtype: float64
報酬 0.010013348299112868 %
i= BNB     0.003586
ICX     0.086186
NEO    -0.036436
IOTA   -0.013654
LINK    0.010385
Name: 687, dtype: float64
熊式-----------------------------------
執行第 694
           694
BNB  -0.016317
ALGO  0.010766
ADA   0.019823
LINK  0.023622
ICX   0.030150
TRX   0.032405
IOTA  0.034985
NEO   0.045166
XRP   0.048944
XLM   0.056102
LTC   0.072215
BAT   0.072575
BCH   0.083568
ZIL   0.113265
ZRX   0.118979
VET   0.129836
ETH   0.143386
ATOM  0.159549
ZEC   0.160135
QTUM  0.243029
g================================================================        BNB   ALGO      ADA  LINK     ICX
0    29.42  0.809  0.05262  2.42  0.2002
1    27.01  0.717  0.04715  2.28  0.1862
2    28.11  0.710  0.04733  2.42  0.2011
3    27.53  0.677  0.04668  2.30  0.1925
4    27.50  0.683  0.04740  2.40  0.1975
..     ...    ...      ...   ...     ...
720    NaN    NaN      NaN   NaN     NaN
721    NaN    NaN      NaN   NaN     NaN
722    NaN    NaN      NaN   NaN     NaN
723    NaN    NaN      NaN   NaN     NaN
724    NaN    NaN      NaN   NaN     NaN

[725 rows x 5 columns]
BNB    -0.025216
ALGO    0.017192
ADA    -0.016365
LINK   -0.014432
ICX     0.085711
Name: 688, dtype: float64
報酬 0.00937803924012066 %
i= BNB    -0.025216
ALGO    0.017192
ADA    -0.016365
LINK   -0.014432
ICX     0.085711
Name: 688, dtype: float64
熊式-----------------------------------
執行第 695
           695
BNB   0.023084
IOTA  0.039208
ALGO  0.051040
TRX   0.054362
ADA   0.062560
LINK  0.078153
XRP   0.078784
NEO   0.089298
LTC   0.093511
BCH   0.103166
ICX   0.112859
XLM   0.113507
BAT   0.121768
ZRX   0.138893
ETH   0.164228
VET   0.170728
ZIL   0.180236
ZEC   0.199143
ATOM  0.213587
QTUM  0.282149
g================================================================        BNB    IOTA   ALGO      TRX      ADA
0    29.42  0.2564  0.809  0.02049  0.05262
1    27.01  0.2322  0.717  0.01778  0.04715
2    28.11  0.2428  0.710  0.01752  0.04733
3    27.53  0.2413  0.677  0.01688  0.04668
4    27.50  0.2422  0.683  0.01692  0.04740
..     ...     ...    ...      ...      ...
720    NaN     NaN    NaN      NaN      NaN
721    NaN     NaN    NaN      NaN      NaN
722    NaN     NaN    NaN      NaN      NaN
723    NaN     NaN    NaN      NaN      NaN
724    NaN     NaN    NaN      NaN      NaN

[725 rows x 5 columns]
BNB    -0.026629
IOTA   -0.050629
ALGO   -0.051508
TRX     0.006176
ADA    -0.060926
Name: 689, dtype: float64
報酬 -0.03670303478379015 %
i= BNB    -0.026629
IOTA   -0.050629
ALGO   -0.051508
TRX     0.006176
ADA    -0.060926
Name: 689, dtype: float64
熊式-----------------------------------
執行第 696
           696
BNB   0.028340
ALGO  0.044359
IOTA  0.052571
XLM   0.057056
TRX   0.061404
XRP   0.063878
LINK  0.078466
LTC   0.079180
BCH   0.079305
ADA   0.115213
ICX   0.125930
BAT   0.137351
NEO   0.141626
ZEC   0.146942
ZRX   0.151989
ZIL   0.163740
VET   0.173095
ETH   0.177433
QTUM  0.214286

ATOM  0.229927
g================================================================        BNB   ALGO    IOTA      XLM      TRX
0    29.42  0.809  0.2564  0.07442  0.02049
1    27.01  0.717  0.2322  0.06922  0.01778
2    28.11  0.710  0.2428  0.07019  0.01752
3    27.53  0.677  0.2413  0.06851  0.01688
4    27.50  0.683  0.2422  0.06770  0.01692
..     ...    ...     ...      ...      ...
720    NaN    NaN     NaN      NaN      NaN
721    NaN    NaN     NaN      NaN      NaN
722    NaN    NaN     NaN      NaN      NaN
723    NaN    NaN     NaN      NaN      NaN
724    NaN    NaN     NaN      NaN      NaN

[725 rows x 5 columns]
BNB    -0.073067
ALGO   -0.102500
IOTA   -0.120685
XLM    -0.137929
TRX    -0.054896
Name: 690, dtype: float64
報酬 -0.09781532253996658 %
i= BNB    -0.073067
ALGO   -0.102500
IOTA   -0.120685
XLM    -0.137929
TRX    -0.054896
Name: 690, dtype: float64
熊式-----------------------------------
執行第 697
           697
LINK  0.019053
XLM   0.022894
BNB   0.028774
TRX   0.030429
XRP   0.044486
ALGO  0.048596
IOTA  0.052823
LTC   0.056755
BCH   0.062428
ADA   0.064274
BAT   0.092052
ZEC   0.097341
ZRX   0.113255
ICX   0.123579
ETH   0.124179
VET   0.139499
ZIL   0.139864
NEO   0.155412
QTUM  0.181848
ATOM  0.185726
g================================================================      LINK      XLM    BNB      TRX      XRP
0    2.42  0.07442  29.42  0.02049  0.29787
1    2.28  0.06922  27.01  0.01778  0.26338
2    2.42  0.07019  28.11  0.01752  0.26408
3    2.30  0.06851  27.53  0.01688  0.26055
4    2.40  0.06770  27.50  0.01692  0.26543
..    ...      ...    ...      ...      ...
720   NaN      NaN    NaN      NaN      NaN
721   NaN      NaN    NaN      NaN      NaN
722   NaN      NaN    NaN      NaN      NaN
723   NaN      NaN    NaN      NaN      NaN
724   NaN      NaN    NaN      NaN      NaN

[725 rows x 5 columns]
LINK   -0.299679
XLM    -0.312146
BNB    -0.265449
TRX    -0.255346
XRP    -0.318881
Name: 691, dtype: float64
報酬 -0.290300352230242 %
i= LINK   -0.299679
XLM    -0.312146
BNB    -0.265449
TRX    -0.255346
XRP    -0.318881
Name: 691, dtype: float64
熊式-----------------------------------
執行第 698
           698
XLM   0.017305
ZEC   0.023280
LINK  0.025013
IOTA  0.031979
TRX   0.032021
ZRX   0.033838
ZIL   0.038307
ALGO  0.047715
BCH   0.051959
LTC   0.052593
BNB   0.062278
XRP   0.080603
BAT   0.086824
ADA   0.103102
VET   0.107638
ICX   0.114829
ETH   0.115327
ATOM  0.130846
NEO   0.132169
QTUM  0.173644
g================================================================          XLM    ZEC  LINK    IOTA      TRX
0    0.07442  55.45  2.42  0.2564  0.02049
1    0.06922  50.56  2.28  0.2322  0.01778
2    0.07019  50.57  2.42  0.2428  0.01752
3    0.06851  48.85  2.30  0.2413  0.01688
4    0.06770  50.01  2.40  0.2422  0.01692
..       ...    ...   ...     ...      ...
720      NaN    NaN   NaN     NaN      NaN
721      NaN    NaN   NaN     NaN      NaN
722      NaN    NaN   NaN     NaN      NaN
723      NaN    NaN   NaN     NaN      NaN
724      NaN    NaN   NaN     NaN      NaN

[725 rows x 5 columns]
XLM    -0.298253
ZEC    -0.224702
LINK   -0.314286
IOTA   -0.361280
TRX    -0.291167
Name: 692, dtype: float64
報酬 -0.2979375847754543 %
i= XLM    -0.298253
ZEC    -0.224702
LINK   -0.314286
IOTA   -0.361280
TRX    -0.291167
Name: 692, dtype: float64
熊式-----------------------------------
執行第 699
           699
ZEC  -0.115070
XLM  -0.096193
QTUM -0.080756
XRP  -0.074777
VET  -0.074292
ZIL  -0.070061
LINK -0.056041
TRX  -0.045965
LTC  -0.040373
ZRX  -0.037258
BCH  -0.032813
BAT  -0.029457
IOTA -0.025398
ALGO -0.012549
BNB   0.007372
ETH   0.018459
ADA   0.023173
NEO   0.027821
ICX   0.105826
ATOM  0.174142
g================================================================        ZEC      XLM   QTUM      XRP       VET
0    55.45  0.07442  2.642  0.29787  0.004916
1    50.56  0.06922  2.347  0.26338  0.004628
2    50.57  0.07019  2.376  0.26408  0.004580
3    48.85  0.06851  2.291  0.26055  0.004493
4    50.01  0.06770  2.455  0.26543  0.004454
..     ...      ...    ...      ...       ...
720    NaN      NaN    NaN      NaN       NaN
721    NaN      NaN    NaN      NaN       NaN
722    NaN      NaN    NaN      NaN       NaN
723    NaN      NaN    NaN      NaN       NaN
724    NaN      NaN    NaN      NaN       NaN

[725 rows x 5 columns]
ZEC    -0.184682
XLM    -0.195775
QTUM   -0.323249
XRP    -0.232905
VET    -0.291694
Name: 693, dtype: float64
報酬 -0.24566083296909919 %
i= ZEC    -0.184682
XLM    -0.195775
QTUM   -0.323249
XRP    -0.232905
VET    -0.291694
Name: 693, dtype: float64
熊式-----------------------------------
執行第 700
           700
ZEC  -0.118312
ZIL  -0.086378
XLM  -0.083513
VET  -0.073977
QTUM -0.070171
XRP  -0.057580
TRX  -0.047961
LTC  -0.040230
BCH  -0.032627
BAT  -0.030579
ZRX  -0.022264
IOTA -0.007383
LINK  0.004103
NEO   0.015727
ETH   0.016193
ADA   0.021606
ALGO  0.032748
ICX   0.044200
BNB   0.044653
ATOM  0.095028
g================================================================        ZEC      ZIL      XLM       VET   QTUM
0    55.45  0.00879  0.07442  0.004916  2.642
1    50.56  0.00762  0.06922  0.004628  2.347
2    50.57  0.00749  0.07019  0.004580  2.376
3    48.85  0.00732  0.06851  0.004493  2.291
4    50.01  0.00773  0.06770  0.004454  2.455
..     ...      ...      ...       ...    ...
720    NaN      NaN      NaN       NaN    NaN
721    NaN      NaN      NaN       NaN    NaN
722    NaN      NaN      NaN       NaN    NaN
723    NaN      NaN      NaN       NaN    NaN
724    NaN      NaN      NaN       NaN    NaN

[725 rows x 5 columns]
ZEC    -0.207115
ZIL    -0.236875
XLM    -0.154847
VET    -0.247551
QTUM   -0.284704
Name: 694, dtype: float64
報酬 -0.22621825602289097 %
i= ZEC    -0.207115
ZIL    -0.236875
XLM    -0.154847
VET    -0.247551
QTUM   -0.284704
Name: 694, dtype: float64
熊式-----------------------------------
執行第 701
           701
XLM  -0.045429
ZEC  -0.014961
VET  -0.012655
XRP  -0.011970
ZIL  -0.008775
TRX  -0.007101
QTUM -0.001411
LTC   0.001604
BCH   0.026325
ADA   0.052951
BAT   0.055393
NEO   0.083031
ALGO  0.086571
LINK  0.086766
ETH   0.098738
IOTA  0.107708
BNB   0.139167
ZRX   0.143997
ICX   0.150384
ATOM  0.172645
g================================================================          XLM    ZEC       VET      XRP      ZIL
0    0.07442  55.45  0.004916  0.29787  0.00879
1    0.06922  50.56  0.004628  0.26338  0.00762
2    0.07019  50.57  0.004580  0.26408  0.00749
3    0.06851  48.85  0.004493  0.26055  0.00732
4    0.06770  50.01  0.004454  0.26543  0.00773
..       ...    ...       ...      ...      ...
720      NaN    NaN       NaN      NaN      NaN
721      NaN    NaN       NaN      NaN      NaN
722      NaN    NaN       NaN      NaN      NaN
723      NaN    NaN       NaN      NaN      NaN
724      NaN    NaN       NaN      NaN      NaN

[725 rows x 5 columns]
XLM   -0.185536
ZEC   -0.241132
VET   -0.272343
XRP   -0.230924
ZIL   -0.276210
Name: 695, dtype: float64
報酬 -0.24122888645875226 %
i= XLM   -0.185536
ZEC   -0.241132
VET   -0.272343
XRP   -0.230924
ZIL   -0.276210
Name: 695, dtype: float64
熊式-----------------------------------
執行第 702
           702
VET  -0.121597
TRX  -0.081743
QTUM -0.080317
ZIL  -0.078876
ZEC  -0.078673
XLM  -0.073172
XRP  -0.049680
ADA  -0.045207
NEO  -0.039915
LTC  -0.033543
BAT  -0.020987
ETH  -0.015664
IOTA -0.014960
BCH  -0.010747
LINK  0.008753
ATOM  0.013819
ALGO  0.027331
BNB   0.080764
ZRX   0.183526
ICX   0.266520
g================================================================           VET      TRX   QTUM      ZIL    ZEC
0    0.004916  0.02049  2.642  0.00879  55.45
1    0.004628  0.01778  2.347  0.00762  50.56
2    0.004580  0.01752  2.376  0.00749  50.57
3    0.004493  0.01688  2.291  0.00732  48.85
4    0.004454  0.01692  2.455  0.00773  50.01
..        ...      ...    ...      ...    ...
720       NaN      NaN    NaN      NaN    NaN
721       NaN      NaN    NaN      NaN    NaN
722       NaN      NaN    NaN      NaN    NaN
723       NaN      NaN    NaN      NaN    NaN
724       NaN      NaN    NaN      NaN    NaN

[725 rows x 5 columns]
VET    -0.236437
TRX    -0.083601
QTUM   -0.242751
ZIL    -0.248310
ZEC    -0.193030
Name: 696, dtype: float64
報酬 -0.20082593946124927 %
i= VET    -0.236437
TRX    -0.083601
QTUM   -0.242751
ZIL    -0.248310
ZEC    -0.193030
Name: 696, dtype: float64
熊式-----------------------------------
執行第 703
           703
VET  -0.131552
ZIL  -0.087523
XLM  -0.073410
TRX  -0.067756
QTUM -0.067437
NEO  -0.062776
ZEC  -0.059646
XRP  -0.057675
ADA  -0.049975
LTC  -0.039994
BAT  -0.036053
ETH  -0.035631
IOTA -0.025146
BCH  -0.006053
LINK -0.003205
ALGO  0.036617
BNB   0.058344
ATOM  0.103558
ICX   0.178894
ZRX   0.181344
g================================================================           VET      ZIL      XLM      TRX   QTUM
0    0.004916  0.00879  0.07442  0.02049  2.642
1    0.004628  0.00762  0.06922  0.01778  2.347
2    0.004580  0.00749  0.07019  0.01752  2.376
3    0.004493  0.00732  0.06851  0.01688  2.291
4    0.004454  0.00773  0.06770  0.01692  2.455
..        ...      ...      ...      ...    ...
720       NaN      NaN      NaN      NaN    NaN
721       NaN      NaN      NaN      NaN    NaN
722       NaN      NaN      NaN      NaN    NaN
723       NaN      NaN      NaN      NaN    NaN
724       NaN      NaN      NaN      NaN    NaN

[725 rows x 5 columns]
VET    -0.209002
ZIL    -0.245814
XLM    -0.128260
TRX    -0.043157
QTUM   -0.186557
Name: 697, dtype: float64
報酬 -0.16255819849638 %
i= VET    -0.209002
ZIL    -0.245814
XLM    -0.128260
TRX    -0.043157
QTUM   -0.186557
Name: 697, dtype: float64
熊式-----------------------------------
執行第 704
           704
VET  -0.136208
ZIL  -0.119966
QTUM -0.102959
ZEC  -0.102043
XRP  -0.101610
NEO  -0.092902
ETH  -0.091246
TRX  -0.088628
XLM  -0.086656
ADA  -0.086144
BAT  -0.077903
LTC  -0.075224
IOTA -0.064104
BCH  -0.057246
LINK -0.055036
ALGO  0.012834
BNB   0.026666
ICX   0.082755
ZRX   0.089629
ATOM  0.169660
g================================================================           VET      ZIL   QTUM    ZEC      XRP
0    0.004916  0.00879  2.642  55.45  0.29787
1    0.004628  0.00762  2.347  50.56  0.26338
2    0.004580  0.00749  2.376  50.57  0.26408
3    0.004493  0.00732  2.291  48.85  0.26055
4    0.004454  0.00773  2.455  50.01  0.26543
..        ...      ...    ...    ...      ...
720       NaN      NaN    NaN    NaN      NaN
721       NaN      NaN    NaN    NaN      NaN
722       NaN      NaN    NaN    NaN      NaN
723       NaN      NaN    NaN    NaN      NaN
724       NaN      NaN    NaN    NaN      NaN

[725 rows x 5 columns]
VET     0.080632
ZIL     0.100427
QTUM    0.151150
ZEC     0.159720
XRP     0.061840
Name: 698, dtype: float64
報酬 0.1107539260175244 %
i= VET     0.080632
ZIL     0.100427
QTUM    0.151150
ZEC     0.159720
XRP     0.061840
Name: 698, dtype: float64
熊式-----------------------------------
執行第 705
           705
ZIL  -0.073707
VET  -0.068138
NEO  -0.048823
TRX  -0.041983
ADA  -0.040097
QTUM -0.037527
XLM  -0.031169
ETH  -0.026977
LTC  -0.026621
XRP  -0.026175
BCH  -0.013119
BAT  -0.007764
ZEC  -0.004134
LINK  0.001089
IOTA  0.023380
ALGO  0.024960
ATOM  0.035183
ICX   0.058019
BNB   0.065795
ZRX   0.143720
g================================================================          ZIL       VET     NEO      TRX      ADA
0    0.00879  0.004916  10.494  0.02049  0.05262
1    0.00762  0.004628   9.427  0.01778  0.04715
2    0.00749  0.004580   9.897  0.01752  0.04733
3    0.00732  0.004493   9.818  0.01688  0.04668
4    0.00773  0.004454   9.663  0.01692  0.04740
..       ...       ...     ...      ...      ...
720      NaN       NaN     NaN      NaN      NaN
721      NaN       NaN     NaN      NaN      NaN
722      NaN       NaN     NaN      NaN      NaN
723      NaN       NaN     NaN      NaN      NaN
724      NaN       NaN     NaN      NaN      NaN

[725 rows x 5 columns]
ZIL    0.250036
VET    0.260675
NEO    0.164098
TRX    0.329796
ADA    0.187624
Name: 699, dtype: float64
報酬 0.23844588121011984 %
i= ZIL    0.250036
VET    0.260675
NEO    0.164098
TRX    0.329796
ADA    0.187624
Name: 699, dtype: float64
熊式-----------------------------------
執行第 706
           706
ETH  -0.119260
VET  -0.110821
ZIL  -0.104634
LINK -0.103677
NEO  -0.090584
XLM  -0.081148
BAT  -0.079866
QTUM -0.079815
IOTA -0.077638
TRX  -0.074257
ADA  -0.071014
ZEC  -0.066314
BCH  -0.057992
XRP  -0.053574
ALGO -0.045754
LTC  -0.036063
ATOM -0.013666
BNB  -0.002084
ICX   0.039698
ZRX   0.040160
g================================================================         ETH       VET      ZIL  LINK     NEO
0    209.22  0.004916  0.00879  2.42  10.494
1    187.11  0.004628  0.00762  2.28   9.427
2    188.16  0.004580  0.00749  2.42   9.897
3    185.03  0.004493  0.00732  2.30   9.818
4    185.61  0.004454  0.00773  2.40   9.663
..      ...       ...      ...   ...     ...
720     NaN       NaN      NaN   NaN     NaN
721     NaN       NaN      NaN   NaN     NaN
722     NaN       NaN      NaN   NaN     NaN
723     NaN       NaN      NaN   NaN     NaN
724     NaN       NaN      NaN   NaN     NaN

[725 rows x 5 columns]
ETH     0.154867
VET     0.196454
ZIL     0.193399
LINK    0.062092
NEO     0.090752
Name: 700, dtype: float64
報酬 0.13951274331924335 %
i= ETH     0.154867
VET     0.196454
ZIL     0.193399
LINK    0.062092
NEO     0.090752
Name: 700, dtype: float64
熊式-----------------------------------
執行第 707
           707
ETH  -0.162092
ZIL  -0.149760
IOTA -0.149393
LINK -0.148055
BAT  -0.127791
VET  -0.126737
QTUM -0.123464
ZEC  -0.121509
ADA  -0.098939
NEO  -0.095501
XLM  -0.095377
ZRX  -0.094435
BCH  -0.087626
TRX  -0.077270
ICX  -0.072853
ATOM -0.063417
BNB  -0.057070
XRP  -0.050146
LTC  -0.043526
ALGO -0.034761
g================================================================         ETH      ZIL    IOTA  LINK     BAT
0    209.22  0.00879  0.2564  2.42  0.1972
1    187.11  0.00762  0.2322  2.28  0.1682
2    188.16  0.00749  0.2428  2.42  0.1870
3    185.03  0.00732  0.2413  2.30  0.1788
4    185.61  0.00773  0.2422  2.40  0.1764
..      ...      ...     ...   ...     ...
720     NaN      NaN     NaN   NaN     NaN
721     NaN      NaN     NaN   NaN     NaN
722     NaN      NaN     NaN   NaN     NaN
723     NaN      NaN     NaN   NaN     NaN
724     NaN      NaN     NaN   NaN     NaN

[725 rows x 5 columns]

ETH     0.059999
ZIL     0.039529
IOTA   -0.041075
LINK   -0.044094
BAT     0.014131
Name: 701, dtype: float64
報酬 0.005698014115659178 %
i= ETH     0.059999
ZIL     0.039529
IOTA   -0.041075
LINK   -0.044094
BAT     0.014131
Name: 701, dtype: float64
熊式-----------------------------------
執行第 708
           708
ICX  -0.195459
ZRX  -0.125275
IOTA -0.094672
LINK -0.081345
BAT  -0.066948
ETH  -0.059773
ADA  -0.052225
ZIL  -0.051139
BCH  -0.047513
QTUM -0.047509
VET  -0.047019
ZEC  -0.044249
NEO  -0.036499
TRX  -0.020291
ATOM -0.016725
XLM  -0.016446
ALGO -0.010941
LTC  -0.008922
XRP  -0.006094
BNB  -0.003574
g================================================================         ICX     ZRX    IOTA  LINK     BAT
0    0.2002  0.1814  0.2564  2.42  0.1972
1    0.1862  0.1624  0.2322  2.28  0.1682
2    0.2011  0.1736  0.2428  2.42  0.1870
3    0.1925  0.1751  0.2413  2.30  0.1788
4    0.1975  0.1711  0.2422  2.40  0.1764
..      ...     ...     ...   ...     ...
720     NaN     NaN     NaN   NaN     NaN
721     NaN     NaN     NaN   NaN     NaN
722     NaN     NaN     NaN   NaN     NaN
723     NaN     NaN     NaN   NaN     NaN
724     NaN     NaN     NaN   NaN     NaN

[725 rows x 5 columns]
ICX     0.127483
ZRX     0.142857
IOTA    0.072593
LINK    0.082297
BAT     0.121768
Name: 702, dtype: float64
報酬 0.109399725766227 %
i= ICX     0.127483
ZRX     0.142857
IOTA    0.072593
LINK    0.082297
BAT     0.121768
Name: 702, dtype: float64
熊式-----------------------------------
執行第 709
           709
ZRX  -0.199070
ICX  -0.194972
LINK -0.156484
IOTA -0.153912
ATOM -0.130102
QTUM -0.125295
BAT  -0.109921
ETH  -0.106725
VET  -0.103193
ZIL  -0.100987
ZEC  -0.098928
BCH  -0.095560
NEO  -0.094668
ADA  -0.092243
ALGO -0.079258
TRX  -0.070108
LTC  -0.065094
XRP  -0.062147
XLM  -0.017026
BNB  -0.003663
g================================================================         ZRX     ICX  LINK    IOTA   ATOM
0    0.1814  0.2002  2.42  0.2564  3.258
1    0.1624  0.1862  2.28  0.2322  2.857
2    0.1736  0.2011  2.42  0.2428  2.898
3    0.1751  0.1925  2.30  0.2413  2.884
4    0.1711  0.1975  2.40  0.2422  2.910
..      ...     ...   ...     ...    ...
720     NaN     NaN   NaN     NaN    NaN
721     NaN     NaN   NaN     NaN    NaN
722     NaN     NaN   NaN     NaN    NaN
723     NaN     NaN   NaN     NaN    NaN
724     NaN     NaN   NaN     NaN    NaN

[725 rows x 5 columns]
ZRX     0.181455
ICX     0.143703
LINK    0.104425
IOTA    0.065524
ATOM    0.245568
Name: 703, dtype: float64
報酬 0.1481350714773914 %
i= ZRX     0.181455
ICX     0.143703
LINK    0.104425
IOTA    0.065524
ATOM    0.245568
Name: 703, dtype: float64
熊式-----------------------------------
執行第 710
           710
ATOM -0.225148
ZRX  -0.216984
ICX  -0.198630
IOTA -0.170100
QTUM -0.166139
LINK -0.162088
ZIL  -0.154131
VET  -0.140166
ZEC  -0.138511
NEO  -0.128109
ADA  -0.122716
ALGO -0.120767
BCH  -0.118667
ETH  -0.110360
LTC  -0.099328
TRX  -0.094315
XRP  -0.057271
BNB  -0.041855
XLM  -0.039904
BAT  -0.014350
g================================================================       ATOM     ZRX     ICX    IOTA   QTUM
0    3.258  0.1814  0.2002  0.2564  2.642
1    2.857  0.1624  0.1862  0.2322  2.347
2    2.898  0.1736  0.2011  0.2428  2.376
3    2.884  0.1751  0.1925  0.2413  2.291
4    2.910  0.1711  0.1975  0.2422  2.455
..     ...     ...     ...     ...    ...
720    NaN     NaN     NaN     NaN    NaN
721    NaN     NaN     NaN     NaN    NaN
722    NaN     NaN     NaN     NaN    NaN
723    NaN     NaN     NaN     NaN    NaN
724    NaN     NaN     NaN     NaN    NaN

[725 rows x 5 columns]
ATOM    0.221660
ZRX     0.135843
ICX     0.149838
IOTA    0.060853
QTUM    0.203806
Name: 704, dtype: float64
報酬 0.15439994901884954 %
i= ATOM    0.221660
ZRX     0.135843
ICX     0.149838
IOTA    0.060853
QTUM    0.203806
Name: 704, dtype: float64
熊式-----------------------------------
執行第 711
           711
ATOM -0.216652
ZRX  -0.211572
IOTA -0.182294
QTUM -0.169555
ICX  -0.168190
LINK -0.164309
ZEC  -0.159538
VET  -0.157698
ZIL  -0.157381
NEO  -0.135650
ADA  -0.130732
BCH  -0.124900
ALGO -0.123883
ETH  -0.112752
LTC  -0.106714
TRX  -0.095246
XRP  -0.085822
BNB  -0.066859
XLM  -0.054541
BAT  -0.050151
g================================================================       ATOM     ZRX    IOTA   QTUM     ICX
0    3.258  0.1814  0.2564  2.642  0.2002
1    2.857  0.1624  0.2322  2.347  0.1862
2    2.898  0.1736  0.2428  2.376  0.2011
3    2.884  0.1751  0.2413  2.291  0.1925
4    2.910  0.1711  0.2422  2.455  0.1975
..     ...     ...     ...    ...     ...
720    NaN     NaN     NaN    NaN     NaN
721    NaN     NaN     NaN    NaN     NaN
722    NaN     NaN     NaN    NaN     NaN
723    NaN     NaN     NaN    NaN     NaN
724    NaN     NaN     NaN    NaN     NaN

[725 rows x 5 columns]
ATOM    0.248369
ZRX    -0.007567
IOTA    0.002319
QTUM    0.102918
ICX     0.180709
Name: 705, dtype: float64
報酬 0.10534949633242212 %
i= ATOM    0.248369
ZRX    -0.007567
IOTA    0.002319
QTUM    0.102918
ICX     0.180709
Name: 705, dtype: float64
熊式-----------------------------------
執行第 712
           712
ZRX  -0.173677
ICX  -0.156800
ATOM -0.154953
IOTA -0.139113
QTUM -0.135366
ZEC  -0.127472
ZIL  -0.120479
NEO  -0.120362
LINK -0.117949
LTC  -0.106013
VET  -0.100507
ADA  -0.100122
BCH  -0.086925
ALGO -0.081982
ETH  -0.069899
TRX  -0.068897
XRP  -0.066942
BAT  -0.053063
BNB  -0.044035
XLM  -0.036801
g================================================================         ZRX     ICX   ATOM    IOTA   QTUM
0    0.1814  0.2002  3.258  0.2564  2.642
1    0.1624  0.1862  2.857  0.2322  2.347
2    0.1736  0.2011  2.898  0.2428  2.376
3    0.1751  0.1925  2.884  0.2413  2.291
4    0.1711  0.1975  2.910  0.2422  2.455
..      ...     ...    ...     ...    ...
720     NaN     NaN    NaN     NaN    NaN
721     NaN     NaN    NaN     NaN    NaN
722     NaN     NaN    NaN     NaN    NaN
723     NaN     NaN    NaN     NaN    NaN
724     NaN     NaN    NaN     NaN    NaN

[725 rows x 5 columns]
ZRX     0.003601
ICX     0.074361
ATOM    0.138277
IOTA    0.021125
QTUM   -0.057758
Name: 706, dtype: float64
報酬 0.03592107916441645 %
i= ZRX     0.003601
ICX     0.074361
ATOM    0.138277
IOTA    0.021125
QTUM   -0.057758
Name: 706, dtype: float64
熊式-----------------------------------
執行第 713
           713
ZRX  -0.184490
ATOM -0.179959
IOTA -0.176424
NEO  -0.172358
ZIL  -0.161099
VET  -0.154321
ICX  -0.153435
QTUM -0.145689
ZEC  -0.145039
ALGO -0.144621
LTC  -0.140020
LINK -0.139383
ADA  -0.113834
BCH  -0.108755
XRP  -0.100581
TRX  -0.099747
XLM  -0.092302
BNB  -0.092177
BAT  -0.076808
ETH  -0.063270
g================================================================         ZRX   ATOM    IOTA     NEO      ZIL
0    0.1814  3.258  0.2564  10.494  0.00879
1    0.1624  2.857  0.2322   9.427  0.00762
2    0.1736  2.898  0.2428   9.897  0.00749
3    0.1751  2.884  0.2413   9.818  0.00732
4    0.1711  2.910  0.2422   9.663  0.00773
..      ...    ...     ...     ...      ...
720     NaN    NaN     NaN     NaN      NaN
721     NaN    NaN     NaN     NaN      NaN
722     NaN    NaN     NaN     NaN      NaN
723     NaN    NaN     NaN     NaN      NaN
724     NaN    NaN     NaN     NaN      NaN

[725 rows x 5 columns]
ZRX     0.064499
ATOM    0.076322
IOTA    0.026304
NEO     0.012116
ZIL    -0.074428
Name: 707, dtype: float64
報酬 0.020962510357474696 %
i= ZRX     0.064499
ATOM    0.076322
IOTA    0.026304
NEO     0.012116
ZIL    -0.074428
Name: 707, dtype: float64
熊式-----------------------------------
執行第 714
           714
ZIL  -0.250246
ZRX  -0.235623
NEO  -0.213253
VET  -0.203556
IOTA -0.201975
QTUM -0.195157
ATOM -0.193740
ALGO -0.189334
LINK -0.188312
ICX  -0.182539
LTC  -0.181582
ZEC  -0.180792
ADA  -0.164674
TRX  -0.156172
XRP  -0.147144
BCH  -0.146676
BNB  -0.144985
BAT  -0.121469
XLM  -0.116004
ETH  -0.104617
g================================================================          ZIL     ZRX     NEO       VET    IOTA
0    0.00879  0.1814  10.494  0.004916  0.2564
1    0.00762  0.1624   9.427  0.004628  0.2322
2    0.00749  0.1736   9.897  0.004580  0.2428
3    0.00732  0.1751   9.818  0.004493  0.2413
4    0.00773  0.1711   9.663  0.004454  0.2422
..       ...     ...     ...       ...     ...
720      NaN     NaN     NaN       NaN     NaN
721      NaN     NaN     NaN       NaN     NaN
722      NaN     NaN     NaN       NaN     NaN
723      NaN     NaN     NaN       NaN     NaN
724      NaN     NaN     NaN       NaN     NaN

[725 rows x 5 columns]
ZIL    -0.084826
ZRX     0.187645
NEO    -0.002488
VET    -0.099468
IOTA    0.016685
Name: 708, dtype: float64
報酬 0.003509710426745394 %
i= ZIL    -0.084826
ZRX     0.187645
NEO    -0.002488
VET    -0.099468
IOTA    0.016685
Name: 708, dtype: float64
熊式-----------------------------------
執行第 715
           715
ZIL  -0.131325
NEO  -0.110434
QTUM -0.092121
ATOM -0.087992
ALGO -0.076849
BNB  -0.071207
TRX  -0.068995
IOTA -0.065308
LTC  -0.063898
BCH  -0.055735
XLM  -0.055031
ZRX  -0.053611
ICX  -0.053567
ZEC  -0.049095
VET  -0.045303
ADA  -0.045217
XRP  -0.044009
LINK -0.028590
BAT  -0.007102
ETH   0.040277
g================================================================          ZIL     NEO   QTUM   ATOM   ALGO
0    0.00879  10.494  2.642  3.258  0.809
1    0.00762   9.427  2.347  2.857  0.717
2    0.00749   9.897  2.376  2.898  0.710
3    0.00732   9.818  2.291  2.884  0.677
4    0.00773   9.663  2.455  2.910  0.683
..       ...     ...    ...    ...    ...
720      NaN     NaN    NaN    NaN    NaN
721      NaN     NaN    NaN    NaN    NaN
722      NaN     NaN    NaN    NaN    NaN
723      NaN     NaN    NaN    NaN    NaN
724      NaN     NaN    NaN    NaN    NaN

[725 rows x 5 columns]
ZIL    -0.080471
NEO    -0.024310
QTUM   -0.041855
ATOM    0.117592
ALGO    0.071817
Name: 709, dtype: float64
報酬 0.008554681720987145 %
i= ZIL    -0.080471
NEO    -0.024310
QTUM   -0.041855
ATOM    0.117592
ALGO    0.071817
Name: 709, dtype: float64
熊式-----------------------------------
執行第 716
           716
BAT  -0.066242
BNB  -0.030773
NEO  -0.025897
IOTA -0.008223
TRX  -0.006115
LTC   0.000000
XRP   0.004412
ZIL   0.005669
BCH   0.009132
QTUM  0.011199
ADA   0.012119
ALGO  0.015304
ATOM  0.020441
VET   0.037077
ZRX   0.038848
ICX   0.045720
ZEC   0.046152
LINK  0.054426
ETH   0.077931
XLM   0.120602
g================================================================         BAT    BNB     NEO    IOTA      TRX
0    0.1972  29.42  10.494  0.2564  0.02049
1    0.1682  27.01   9.427  0.2322  0.01778
2    0.1870  28.11   9.897  0.2428  0.01752
3    0.1788  27.53   9.818  0.2413  0.01688
4    0.1764  27.50   9.663  0.2422  0.01692
..      ...    ...     ...     ...      ...
720     NaN    NaN     NaN     NaN      NaN
721     NaN    NaN     NaN     NaN      NaN
722     NaN    NaN     NaN     NaN      NaN
723     NaN    NaN     NaN     NaN      NaN
724     NaN    NaN     NaN     NaN      NaN

[725 rows x 5 columns]
BAT    -0.056364
BNB     0.056239
NEO    -0.078470
IOTA   -0.056966
TRX    -0.079748
Name: 710, dtype: float64
報酬 -0.04306181256154655 %
i= BAT    -0.056364
BNB     0.056239
NEO    -0.078470
IOTA   -0.056966
TRX    -0.079748
Name: 710, dtype: float64
熊式-----------------------------------
執行第 717
           717
BAT  -0.017412
BNB  -0.004794
IOTA -0.002037
NEO   0.000000
TRX   0.000357
ICX   0.006315
ZIL   0.014318
ALGO  0.030091
ADA   0.030642
LTC   0.035956
ZRX   0.036216
ATOM  0.039031
BCH   0.043047
XRP   0.047283
ZEC   0.048529
QTUM  0.056305
LINK  0.073568
VET   0.084671
ETH   0.119213
XLM   0.158522
g================================================================         BAT    BNB    IOTA     NEO      TRX
0    0.1972  29.42  0.2564  10.494  0.02049
1    0.1682  27.01  0.2322   9.427  0.01778
2    0.1870  28.11  0.2428   9.897  0.01752
3    0.1788  27.53  0.2413   9.818  0.01688
4    0.1764  27.50  0.2422   9.663  0.01692
..      ...    ...     ...     ...      ...
720     NaN    NaN     NaN     NaN      NaN
721     NaN    NaN     NaN     NaN      NaN
722     NaN    NaN     NaN     NaN      NaN
723     NaN    NaN     NaN     NaN      NaN
724     NaN    NaN     NaN     NaN      NaN

[725 rows x 5 columns]
BAT    -0.069964
BNB     0.045440
IOTA   -0.006032
NEO    -0.089333
TRX    -0.081948
Name: 711, dtype: float64
報酬 -0.040367261689336374 %
i= BAT    -0.069964
BNB     0.045440
IOTA   -0.006032
NEO    -0.089333
TRX    -0.081948
Name: 711, dtype: float64
熊式-----------------------------------
執行第 718
           718
BNB   0.003144
TRX   0.012332
IOTA  0.012881
ZIL   0.014394
NEO   0.023226
ADA   0.028175
XRP   0.033913
ICX   0.038627
BCH   0.039326
ZEC   0.046925
BAT   0.051608
LTC   0.053002
ALGO  0.057365
ATOM  0.062762
VET   0.065501
ZRX   0.067759
LINK  0.082041
QTUM  0.100317
ETH   0.136705
XLM   0.141427
g================================================================        BNB      TRX    IOTA      ZIL     NEO
0    29.42  0.02049  0.2564  0.00879  10.494
1    27.01  0.01778  0.2322  0.00762   9.427
2    28.11  0.01752  0.2428  0.00749   9.897
3    27.53  0.01688  0.2413  0.00732   9.818
4    27.50  0.01692  0.2422  0.00773   9.663
..     ...      ...     ...      ...     ...
720    NaN      NaN     NaN      NaN     NaN
721    NaN      NaN     NaN      NaN     NaN
722    NaN      NaN     NaN      NaN     NaN
723    NaN      NaN     NaN      NaN     NaN
724    NaN      NaN     NaN      NaN     NaN

[725 rows x 5 columns]
BNB     0.046722
TRX    -0.069094
IOTA   -0.033609
ZIL    -0.097438
NEO    -0.060452
Name: 712, dtype: float64
報酬 -0.042774297116053114 %
i= BNB     0.046722
TRX    -0.069094
IOTA   -0.033609
ZIL    -0.097438
NEO    -0.060452
Name: 712, dtype: float64