In [1]:
import csv
import pandas as pd
import talib
import numpy as np

In [2]:
# data = pd.read_csv("cryptoday.csv")

In [3]:
# data = data.astype('float64')

In [4]:
data = pd.read_csv("全幣種-週價格(程式).csv")

In [5]:
#data

In [6]:
data = data.dropna()

In [7]:
#data.head(10)

In [8]:
data['BTC']

0     10815.7
1     11314.5
2     10218.1
3     10131.0
4      9594.4
       ...
85    58093.4
86    55862.9
87    57059.9
88    59748.4
89    64509.0
Name: BTC, Length: 90, dtype: float64

In [9]:
type(data['BTC'])

pandas.core.series.Series

In [10]:
type(data['BTC'])

pandas.core.series.Series

In [11]:
data['BTC']

0     10815.7
1     11314.5
2     10218.1
3     10131.0
4      9594.4
       ...
85    58093.4
86    55862.9
87    57059.9
88    59748.4
89    64509.0
Name: BTC, Length: 90, dtype: float64

In [12]:
SMA = talib.SMA(data['BTC'],20)

In [13]:
SMA

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
        ...
85    34346.890
86    36398.615
87    38448.060
88    40501.120
89    42840.035
Length: 90, dtype: float64

In [14]:
BBI = np.where((data["BTC"]- SMA> 0),1, 0)
seven = data.shift(6)

In [15]:
#reward = data["BTC"].rolling(window = 9)

In [16]:
today = data.drop(['Date'], axis=1)

In [17]:
sevenago = seven.drop(['Date'], axis=1)

In [18]:
today

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,REP,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX
0,10815.7,0.057739,0.06634,3.6882,0.7438,0.23479,335.39,27.74,0.48535,0.04450,...,11.10,0.020345,0.1276,0.021828,0.005480,0.08237,87.967,0.31601,65.06,0.21572
1,11314.5,0.051980,0.05567,3.3458,0.8104,0.20275,316.13,29.60,0.43925,0.04280,...,10.93,0.019749,0.1154,0.020467,0.004909,0.07390,90.653,0.29925,56.67,0.19208
2,10218.1,0.047360,0.05311,2.9089,0.6841,0.17675,306.59,27.45,0.38663,0.03783,...,9.58,0.017929,0.1154,0.016901,0.004457,0.06839,81.809,0.26544,50.09,0.17177
3,10131.0,0.050097,0.06279,2.6917,0.5782,0.20312,305.52,26.44,0.38957,0.04010,...,9.75,0.018997,0.1298,0.017729,0.004902,0.07035,80.560,0.27137,50.20,0.18548
4,9594.4,0.044777,0.05375,2.0140,0.4083,0.17708,279.25,21.22,0.35833,0.03389,...,7.78,0.015490,0.1125,0.015482,0.004090,0.06196,67.283,0.25759,44.71,0.16204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,58093.4,1.200409,0.28091,20.8997,1.2120,1.08189,536.21,264.10,8.16719,0.07634,...,31.16,0.104714,8.3075,0.060797,0.089385,0.41538,231.894,0.52446,154.61,1.49642
86,55862.9,1.176785,0.28380,18.7088,1.1594,1.08166,500.34,269.32,7.20804,0.07813,...,32.80,0.116051,11.7987,0.063617,0.088533,0.38190,221.039,0.54789,133.59,1.41517
87,57059.9,1.163307,0.35063,20.0322,1.2608,1.11515,530.76,321.53,7.34998,0.10162,...,37.06,0.148812,11.3903,0.101466,0.087419,0.40850,257.027,0.57886,171.16,1.72563
88,59748.4,1.217928,0.65042,21.0379,1.3880,1.46425,672.51,472.25,7.13694,0.12606,...,52.30,0.198945,12.3759,0.126386,0.142241,0.56226,292.212,1.37431,206.28,2.17897
89,64509.0,1.527384,0.46099,24.1419,1.4777,1.51468,812.50,579.42,7.33396,0.12839,...,50.27,0.212417,12.6048,0.150806,0.165572,0.67024,324.176,1.92118,231.87,2.20148

In [19]:
# type(today)
today = today.astype('float64')

In [20]:
type(sevenago)

pandas.core.frame.DataFrame

In [21]:
today

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,REP,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX
0,10815.7,0.057739,0.06634,3.6882,0.7438,0.23479,335.39,27.74,0.48535,0.04450,...,11.10,0.020345,0.1276,0.021828,0.005480,0.08237,87.967,0.31601,65.06,0.21572
1,11314.5,0.051980,0.05567,3.3458,0.8104,0.20275,316.13,29.60,0.43925,0.04280,...,10.93,0.019749,0.1154,0.020467,0.004909,0.07390,90.653,0.29925,56.67,0.19208
2,10218.1,0.047360,0.05311,2.9089,0.6841,0.17675,306.59,27.45,0.38663,0.03783,...,9.58,0.017929,0.1154,0.016901,0.004457,0.06839,81.809,0.26544,50.09,0.17177
3,10131.0,0.050097,0.06279,2.6917,0.5782,0.20312,305.52,26.44,0.38957,0.04010,...,9.75,0.018997,0.1298,0.017729,0.004902,0.07035,80.560,0.27137,50.20,0.18548
4,9594.4,0.044777,0.05375,2.0140,0.4083,0.17708,279.25,21.22,0.35833,0.03389,...,7.78,0.015490,0.1125,0.015482,0.004090,0.06196,67.283,0.25759,44.71,0.16204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,58093.4,1.200409,0.28091,20.8997,1.2120,1.08189,536.21,264.10,8.16719,0.07634,...,31.16,0.104714,8.3075,0.060797,0.089385,0.41538,231.894,0.52446,154.61,1.49642
86,55862.9,1.176785,0.28380,18.7088,1.1594,1.08166,500.34,269.32,7.20804,0.07813,...,32.80,0.116051,11.7987,0.063617,0.088533,0.38190,221.039,0.54789,133.59,1.41517
87,57059.9,1.163307,0.35063,20.0322,1.2608,1.11515,530.76,321.53,7.34998,0.10162,...,37.06,0.148812,11.3903,0.101466,0.087419,0.40850,257.027,0.57886,171.16,1.72563
88,59748.4,1.217928,0.65042,21.0379,1.3880,1.46425,672.51,472.25,7.13694,0.12606,...,52.30,0.198945,12.3759,0.126386,0.142241,0.56226,292.212,1.37431,206.28,2.17897
89,64509.0,1.527384,0.46099,24.1419,1.4777,1.51468,812.50,579.42,7.33396,0.12839,...,50.27,0.212417,12.6048,0.150806,0.165572,0.67024,324.176,1.92118,231.87,2.20148

In [22]:
# today.astype(float)
today = today.astype(float, errors = 'raise')

In [23]:
# sevenago.astype(int)

In [24]:
sevenago

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,REP,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,39256.6,0.633867,0.10692,12.0672,0.8077,0.35271,458.06,72.58,2.46207,0.04289,...,22.95,0.065418,2.2777,0.035078,0.029929,0.37760,152.218,0.44274,94.21,1.44309
86,47168.7,0.911147,0.12347,20.2464,1.6600,0.61702,667.88,133.07,3.63700,0.07578,...,32.80,0.115424,3.3432,0.059812,0.054758,0.56441,241.513,0.63303,176.04,1.88730
87,55923.7,1.116149,0.18792,21.7111,1.2199,0.57861,678.85,254.36,5.51401,0.05787,...,37.15,0.107362,3.6816,0.057754,0.053508,0.48631,255.685,0.51200,164.09,1.53128
88,46136.7,1.316575,0.16420,19.1252,1.0976,0.51439,483.28,225.07,4.98695,0.04473,...,30.91,0.084853,3.1500,0.046520,0.040782,0.43815,209.165,0.43574,119.72,1.33222
89,48855.6,1.129016,0.20616,18.9052,1.0538,0.66461,500.31,226.26,8.47001,0.05201,...,31.05,0.086786,4.1544,0.050190,0.053299,0.40161,204.691,0.46296,125.20,1.37067

In [25]:
reward = today/sevenago-1
# reward.head(10)

In [26]:
reward["BBI"]= BBI
reward.head(10)

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX,BBI
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,-0.044232,-0.196055,-0.148779,-0.157773,-0.569105,-0.258614,-0.093354,-0.239366,-0.235397,-0.231461,...,-0.290587,-0.175549,-0.277442,-0.331752,-0.287119,-0.136540,-0.173191,-0.290194,-0.231272,0
7,-0.116797,-0.003790,0.111371,-0.082282,-0.610686,0.014895,-0.012653,-0.285811,-0.059738,-0.203738,...,-0.221176,-0.075390,-0.114282,-0.157466,-0.057240,-0.199850,-0.031980,-0.158814,0.281393,0
8,-0.196671,-0.184248,0.016381,-0.239438,-0.702090,-0.070382,-0.259173,-0.426230,-0.146729,-0.247158,...,-0.309443,-0.266031,-0.197858,-0.229527,-0.153385,-0.294870,-0.088834,-0.194650,0.227572,0
9,-0.197779,-0.208535,-0.113712,0.027306,-0.611553,-0.031164,-0.270784,-0.405825,-0.115897,-0.284289,...,-0.326157,-0.338983,-0.150826,-0.303958,-0.167448,-0.300857,-0.067030,-0.265538,0.191287,0

In [27]:
reward = reward.dropna(axis=0,how='any')

In [28]:
reward

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX,BBI
6,-0.044232,-0.196055,-0.148779,-0.157773,-0.569105,-0.258614,-0.093354,-0.239366,-0.235397,-0.231461,...,-0.290587,-0.175549,-0.277442,-0.331752,-0.287119,-0.136540,-0.173191,-0.290194,-0.231272,0
7,-0.116797,-0.003790,0.111371,-0.082282,-0.610686,0.014895,-0.012653,-0.285811,-0.059738,-0.203738,...,-0.221176,-0.075390,-0.114282,-0.157466,-0.057240,-0.199850,-0.031980,-0.158814,0.281393,0
8,-0.196671,-0.184248,0.016381,-0.239438,-0.702090,-0.070382,-0.259173,-0.426230,-0.146729,-0.247158,...,-0.309443,-0.266031,-0.197858,-0.229527,-0.153385,-0.294870,-0.088834,-0.194650,0.227572,0
9,-0.197779,-0.208535,-0.113712,0.027306,-0.611553,-0.031164,-0.270784,-0.405825,-0.115897,-0.284289,...,-0.326157,-0.338983,-0.150826,-0.303958,-0.167448,-0.300857,-0.067030,-0.265538,0.191287,0
10,-0.134453,-0.097550,0.031628,0.402830,-0.369091,0.110684,-0.197207,-0.189444,-0.063489,-0.143995,...,-0.193415,-0.229333,0.012079,-0.100489,-0.007747,-0.203766,0.057339,-0.181839,0.590533,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,0.479838,0.893787,1.627291,0.731943,0.500557,2.067364,0.170611,2.638743,2.317205,0.779902,...,0.600691,2.647320,0.733195,1.986568,0.100053,0.523433,0.184578,0.641121,0.036955,1
86,0.184321,0.291542,1.298534,-0.075944,-0.301566,0.753039,-0.250853,1.023897,0.981864,0.031011,...,0.005432,2.529164,0.063616,0.616805,-0.323364,-0.084774,-0.134496,-0.241138,-0.250162,1
87,0.020317,0.042251,0.865847,-0.077329,0.033527,0.927291,-0.218148,0.264075,0.332965,0.756005,...,0.386077,2.093845,0.756865,0.633756,-0.160001,0.005249,0.130586,0.043086,0.126920,1
88,0.295030,-0.074927,2.961145,0.100009,0.264577,1.846576,0.391554,1.098236,0.431123,1.818243,...,1.344584,2.928857,1.716810,2.487838,0.283259,0.397041,2.153968,0.723020,0.635593,1
89,0.320401,0.352845,1.236079,0.276998,0.402258,1.279051,0.623993,1.560859,-0.134126,1.468564,...,1.447595,2.034084,2.004702,2.106475,0.668883,0.583734,3.149775,0.851997,0.606134,1

In [29]:
reward.reset_index(drop=True, inplace=True)
reward

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX,BBI
0,-0.044232,-0.196055,-0.148779,-0.157773,-0.569105,-0.258614,-0.093354,-0.239366,-0.235397,-0.231461,...,-0.290587,-0.175549,-0.277442,-0.331752,-0.287119,-0.136540,-0.173191,-0.290194,-0.231272,0
1,-0.116797,-0.003790,0.111371,-0.082282,-0.610686,0.014895,-0.012653,-0.285811,-0.059738,-0.203738,...,-0.221176,-0.075390,-0.114282,-0.157466,-0.057240,-0.199850,-0.031980,-0.158814,0.281393,0
2,-0.196671,-0.184248,0.016381,-0.239438,-0.702090,-0.070382,-0.259173,-0.426230,-0.146729,-0.247158,...,-0.309443,-0.266031,-0.197858,-0.229527,-0.153385,-0.294870,-0.088834,-0.194650,0.227572,0
3,-0.197779,-0.208535,-0.113712,0.027306,-0.611553,-0.031164,-0.270784,-0.405825,-0.115897,-0.284289,...,-0.326157,-0.338983,-0.150826,-0.303958,-0.167448,-0.300857,-0.067030,-0.265538,0.191287,0
4,-0.134453,-0.097550,0.031628,0.402830,-0.369091,0.110684,-0.197207,-0.189444,-0.063489,-0.143995,...,-0.193415,-0.229333,0.012079,-0.100489,-0.007747,-0.203766,0.057339,-0.181839,0.590533,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,0.479838,0.893787,1.627291,0.731943,0.500557,2.067364,0.170611,2.638743,2.317205,0.779902,...,0.600691,2.647320,0.733195,1.986568,0.100053,0.523433,0.184578,0.641121,0.036955,1
80,0.184321,0.291542,1.298534,-0.075944,-0.301566,0.753039,-0.250853,1.023897,0.981864,0.031011,...,0.005432,2.529164,0.063616,0.616805,-0.323364,-0.084774,-0.134496,-0.241138,-0.250162,1
81,0.020317,0.042251,0.865847,-0.077329,0.033527,0.927291,-0.218148,0.264075,0.332965,0.756005,...,0.386077,2.093845,0.756865,0.633756,-0.160001,0.005249,0.130586,0.043086,0.126920,1
82,0.295030,-0.074927,2.961145,0.100009,0.264577,1.846576,0.391554,1.098236,0.431123,1.818243,...,1.344584,2.928857,1.716810,2.487838,0.283259,0.397041,2.153968,0.723020,0.635593,1
83,0.320401,0.352845,1.236079,0.276998,0.402258,1.279051,0.623993,1.560859,-0.134126,1.468564,...,1.447595,2.034084,2.004702,2.106475,0.668883,0.583734,3.149775,0.851997,0.606134,1

In [30]:
reward.iloc[0,35]

0

In [31]:
A = ['A','A']

In [32]:
# df = pd.DataFrame(columns=['lib', 'qty1', 'qty2', 'qty3','WWWW'])
df = pd.DataFrame

In [33]:
reward

,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,BTS,...,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX,BBI
0,-0.044232,-0.196055,-0.148779,-0.157773,-0.569105,-0.258614,-0.093354,-0.239366,-0.235397,-0.231461,...,-0.290587,-0.175549,-0.277442,-0.331752,-0.287119,-0.136540,-0.173191,-0.290194,-0.231272,0
1,-0.116797,-0.003790,0.111371,-0.082282,-0.610686,0.014895,-0.012653,-0.285811,-0.059738,-0.203738,...,-0.221176,-0.075390,-0.114282,-0.157466,-0.057240,-0.199850,-0.031980,-0.158814,0.281393,0
2,-0.196671,-0.184248,0.016381,-0.239438,-0.702090,-0.070382,-0.259173,-0.426230,-0.146729,-0.247158,...,-0.309443,-0.266031,-0.197858,-0.229527,-0.153385,-0.294870,-0.088834,-0.194650,0.227572,0
3,-0.197779,-0.208535,-0.113712,0.027306,-0.611553,-0.031164,-0.270784,-0.405825,-0.115897,-0.284289,...,-0.326157,-0.338983,-0.150826,-0.303958,-0.167448,-0.300857,-0.067030,-0.265538,0.191287,0
4,-0.134453,-0.097550,0.031628,0.402830,-0.369091,0.110684,-0.197207,-0.189444,-0.063489,-0.143995,...,-0.193415,-0.229333,0.012079,-0.100489,-0.007747,-0.203766,0.057339,-0.181839,0.590533,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,0.479838,0.893787,1.627291,0.731943,0.500557,2.067364,0.170611,2.638743,2.317205,0.779902,...,0.600691,2.647320,0.733195,1.986568,0.100053,0.523433,0.184578,0.641121,0.036955,1
80,0.184321,0.291542,1.298534,-0.075944,-0.301566,0.753039,-0.250853,1.023897,0.981864,0.031011,...,0.005432,2.529164,0.063616,0.616805,-0.323364,-0.084774,-0.134496,-0.241138,-0.250162,1
81,0.020317,0.042251,0.865847,-0.077329,0.033527,0.927291,-0.218148,0.264075,0.332965,0.756005,...,0.386077,2.093845,0.756865,0.633756,-0.160001,0.005249,0.130586,0.043086,0.126920,1
82,0.295030,-0.074927,2.961145,0.100009,0.264577,1.846576,0.391554,1.098236,0.431123,1.818243,...,1.344584,2.928857,1.716810,2.487838,0.283259,0.397041,2.153968,0.723020,0.635593,1
83,0.320401,0.352845,1.236079,0.276998,0.402258,1.279051,0.623993,1.560859,-0.134126,1.468564,...,1.447595,2.034084,2.004702,2.106475,0.668883,0.583734,3.149775,0.851997,0.606134,1

In [34]:
data

,Date,BTC,ADA,ARDR,ATOM,ALGO,BAT,BCH,BNB,BNT,...,REP,SNT,THETA,TRX,VET,XLM,XMR,XRP,ZEC,ZRX
0,28-Jul-19,10815.7,0.057739,0.06634,3.6882,0.7438,0.23479,335.39,27.74,0.48535,...,11.10,0.020345,0.1276,0.021828,0.005480,0.08237,87.967,0.31601,65.06,0.21572
1,4-Aug-19,11314.5,0.051980,0.05567,3.3458,0.8104,0.20275,316.13,29.60,0.43925,...,10.93,0.019749,0.1154,0.020467,0.004909,0.07390,90.653,0.29925,56.67,0.19208
2,11-Aug-19,10218.1,0.047360,0.05311,2.9089,0.6841,0.17675,306.59,27.45,0.38663,...,9.58,0.017929,0.1154,0.016901,0.004457,0.06839,81.809,0.26544,50.09,0.17177
3,18-Aug-19,10131.0,0.050097,0.06279,2.6917,0.5782,0.20312,305.52,26.44,0.38957,...,9.75,0.018997,0.1298,0.017729,0.004902,0.07035,80.560,0.27137,50.20,0.18548
4,25-Aug-19,9594.4,0.044777,0.05375,2.0140,0.4083,0.17708,279.25,21.22,0.35833,...,7.78,0.015490,0.1125,0.015482,0.004090,0.06196,67.283,0.25759,44.71,0.16204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,14-Mar-21,58093.4,1.200409,0.28091,20.8997,1.2120,1.08189,536.21,264.10,8.16719,...,31.16,0.104714,8.3075,0.060797,0.089385,0.41538,231.894,0.52446,154.61,1.49642
86,21-Mar-21,55862.9,1.176785,0.28380,18.7088,1.1594,1.08166,500.34,269.32,7.20804,...,32.80,0.116051,11.7987,0.063617,0.088533,0.38190,221.039,0.54789,133.59,1.41517
87,28-Mar-21,57059.9,1.163307,0.35063,20.0322,1.2608,1.11515,530.76,321.53,7.34998,...,37.06,0.148812,11.3903,0.101466,0.087419,0.40850,257.027,0.57886,171.16,1.72563
88,4-Apr-21,59748.4,1.217928,0.65042,21.0379,1.3880,1.46425,672.51,472.25,7.13694,...,52.30,0.198945,12.3759,0.126386,0.142241,0.56226,292.212,1.37431,206.28,2.17897
89,11-Apr-21,64509.0,1.527384,0.46099,24.1419,1.4777,1.51468,812.50,579.42,7.33396,...,50.27,0.212417,12.6048,0.150806,0.165572,0.67024,324.176,1.92118,231.87,2.20148

In [61]:
for i in range(6,len(reward),1):
    rd = reward.iloc[i,35]
    if reward.iloc[i,35] == 0:
        print("熊式-----------------------------------")
        print("執行第",i) 
        q = reward.iloc[i:i+1,:35]
#         print(q)
        a = q.T
#         print(a)
#         print("執行第",i)    
        c = a.sort_values(by=[i])
#         print(c)
        d = c.T
#         print(d)
        e = d.iloc[:,0:5]
#         print(e)
        f= list(e.columns)
#         print(f)
        g = data.reindex(columns=f)
        h = g.shift(-7) / g.shift(-13) - 1 
        i = h.iloc[i-6,:]
        p = i.sum()
#         print(type(i))
#         print(i)

        result = pd.DataFrame(np.array([i]),
                   columns=f)
        print(type(i))
        print(result)
#         df.swapaxes("index", "columns") 
        result.to_csv('result.csv', mode='a', header=True)
#         j= i.sum()
        print(type(i))
        print(i)

#         print("報酬",j,"%")
        
    else :
        print("牛式===============================")
        print("執行第",i)     
        q = reward.iloc[i:i+1,:35] 
        a = q.T 
        c = a.sort_values(by=[i]) 
        d = c.T 
        e = d.iloc[:,30:36] 
        f= list(e.columns)
#         print(f)
        g = data.reindex(columns=f)
#         print(g)
        h = g.shift(-13)  / g.shift(-7) - 1 
#         print(h.head(25))
        i = h.iloc[i-6,:]
        result = pd.DataFrame(np.array([i]),
               columns=f)
        print(i)
        result.to_csv('result.csv', mode='a', header=True)
        j= i.sum()         
        print("報酬",j,"%")

熊式-----------------------------------
執行第 6
<class 'pandas.core.series.Series'>
       ALGO       ETC       ICX       XMR      DASH
0  0.221448  0.249954  0.256804  0.168277  0.290864
<class 'pandas.core.series.Series'>
ALGO    0.221448
ETC     0.249954
ICX     0.256804
XMR     0.168277
DASH    0.290864
Name: 0, dtype: float64
熊式-----------------------------------
執行第 7
<class 'pandas.core.series.Series'>
       DASH       BNT      ZEC       ICX      LTC
0 -0.004478  0.052682  0.09709  0.007994 -0.10684
<class 'pandas.core.series.Series'>
DASH   -0.004478
BNT     0.052682
ZEC     0.097090
ICX     0.007994
LTC    -0.106840
Name: 1, dtype: float64
熊式-----------------------------------
執行第 8
<class 'pandas.core.series.Series'>
        ZEC       KNC       BNT      ARDR       BTS
0  0.028739  0.155429  0.090592  0.072461  0.087533
<class 'pandas.core.series.Series'>
ZEC     0.028739
KNC     0.155429
BNT     0.090592
ARDR    0.072461
BTS     0.087533
Name: 2, dtype: float64
熊式-----------------------------------
執行第 9
<class 'pandas.core.series.Series'>
        KNC       BNT       BTS      IOTA      ARDR
0  0.240481  0.318948  0.353078  0.249663  0.229217
<class 'pandas.core.series.Series'>
KNC     0.240481
BNT     0.318948
BTS     0.353078
IOTA    0.249663
ARDR    0.229217
Name: 3, dtype: float64
熊式-----------------------------------
執行第 10
<class 'pandas.core.series.Series'>
       MANA       BTS       BNT     DASH      IOTA
0  0.153543  0.220952  0.207838  0.20673  0.280135
<class 'pandas.core.series.Series'>
MANA    0.153543
BTS     0.220952
BNT     0.207838
DASH    0.206730
IOTA    0.280135
Name: 4, dtype: float64
熊式-----------------------------------
執行第 11
<class 'pandas.core.series.Series'>
        XRP     IOTA       ZEC       ZRX    BTS
0  0.293597  0.31301  0.219025  0.240356  0.388
<class 'pandas.core.series.Series'>
XRP     0.293597
IOTA    0.313010
ZEC     0.219025
ZRX     0.240356
BTS     0.388000
Name: 5, dtype: float64
熊式-----------------------------------
執行第 12
<class 'pandas.core.series.Series'>
       BTS      DASH      LINK  IOTA      MANA
0  0.57663  0.455701  0.356784  0.44  0.246032
<class 'pandas.core.series.Series'>
BTS     0.576630
DASH    0.455701
LINK    0.356784
IOTA    0.440000
MANA    0.246032
Name: 6, dtype: float64
熊式-----------------------------------
執行第 13
<class 'pandas.core.series.Series'>
        BTS      DASH        HT      IOTA       TRX
0  0.783853  0.678647  0.376678  0.644358  0.403375
<class 'pandas.core.series.Series'>
BTS     0.783853
DASH    0.678647
HT      0.376678
IOTA    0.644358
TRX     0.403375
Name: 7, dtype: float64
熊式-----------------------------------
執行第 14
<class 'pandas.core.series.Series'>
        BTS      DASH     IOTA       XLM       ZRX
0  0.792799  0.625329  0.56445  0.554151  0.528249
<class 'pandas.core.series.Series'>
BTS     0.792799
DASH    0.625329
IOTA    0.564450
XLM     0.554151
ZRX     0.528249
Name: 8, dtype: float64
熊式-----------------------------------
執行第 15
<class 'pandas.core.series.Series'>
        BTS       OMG      DASH     LINK      IOTA
0  0.399478  0.280453  0.198311  0.32967  0.240395
<class 'pandas.core.series.Series'>
BTS     0.399478
OMG     0.280453
DASH    0.198311
LINK    0.329670
IOTA    0.240395
Name: 9, dtype: float64
熊式-----------------------------------
執行第 16
<class 'pandas.core.series.Series'>
        BTS       XLM       ZRX      LINK      DOGE
0  0.315789  0.186711  0.244409 -0.017544  0.098669
<class 'pandas.core.series.Series'>
BTS     0.315789
XLM     0.186711
ZRX     0.244409
LINK   -0.017544
DOGE    0.098669
Name: 10, dtype: float64
熊式-----------------------------------
執行第 17
<class 'pandas.core.series.Series'>
       ARDR       BTS       BNT       ZRX       SNT
0  0.094546  0.014199  0.152873 -0.034033  0.190432
<class 'pandas.core.series.Series'>
ARDR    0.094546
BTS     0.014199
BNT     0.152873
ZRX    -0.034033
SNT     0.190432
Name: 11, dtype: float64
牛式===============================
執行第 18
MANA    0.333333
BCH     0.499782
ZEC     0.523854
DASH    1.052270
ETC     1.209951
Name: 12, dtype: float64
報酬 3.6191915420009075 %
牛式===============================
執行第 19
REP     0.449335
BCH     1.041351
ZEC     1.348960
DASH    1.740428
ETC     1.822622
Name: 13, dtype: float64
報酬 6.402695669008244 %
牛式===============================
執行第 20
BTS     1.118886
ICX     2.437267
ZEC     1.513523
DASH    2.018638
ETC     1.648513
Name: 14, dtype: float64
報酬 8.73682725836615 %
牛式===============================
執行第 21
BCH     0.956204
ZEC     1.137086
ETC     1.252991
DASH    1.613553
ICX     2.188210
Name: 15, dtype: float64
報酬 7.1480440492596315 %
牛式===============================
執行第 22
BTS     0.977444
SNT     0.911150
LINK    0.802632
DASH    0.634047
ICX     2.377297
Name: 16, dtype: float64
報酬 5.702569264366105 %
牛式===============================
執行第 23
SNT     0.358805
BTS     0.224645
ALGO    0.280478
KNC     1.254343
ICX     0.925466
Name: 17, dtype: float64
報酬 3.043737472321955 %
牛式===============================
執行第 24
SNT     0.493988
LINK    0.782787
HT      0.510318
ICX     1.273757
KNC     1.987558
Name: 18, dtype: float64
報酬 5.048407791491176 %
牛式===============================
執行第 25
SNT    -0.362998
HT     -0.189370
LINK   -0.246479
ICX    -0.338427
KNC     0.574012
Name: 19, dtype: float64
報酬 -0.5632621580208637 %
熊式-----------------------------------
執行第 26
<class 'pandas.core.series.Series'>
        ZEC      DASH       ETC      IOTA      ATOM
0  1.128692  0.769823  1.334271  1.220584  1.134028
<class 'pandas.core.series.Series'>
ZEC     1.128692
DASH    0.769823
ETC     1.334271
IOTA    1.220584
ATOM    1.134028
Name: 20, dtype: float64
熊式-----------------------------------
執行第 27
<class 'pandas.core.series.Series'>
        ETC       VET      MANA      IOTA       OMG
0  1.226819  1.514315  1.377593  1.069265  1.551697
<class 'pandas.core.series.Series'>
ETC     1.226819
VET     1.514315
MANA    1.377593
IOTA    1.069265
OMG     1.551697
Name: 21, dtype: float64
熊式-----------------------------------
執行第 28
<class 'pandas.core.series.Series'>
        OMG       VET      MANA      ATOM       NEO
0  1.001268  1.033909  0.935361  1.482655  0.907588
<class 'pandas.core.series.Series'>
OMG     1.001268
VET     1.033909
MANA    0.935361
ATOM    1.482655
NEO     0.907588
Name: 22, dtype: float64
熊式-----------------------------------
執行第 29
<class 'pandas.core.series.Series'>
       ALGO      ATOM       VET       OMG      MANA
0  0.846967  0.498307  0.526359  0.466097  0.388679
<class 'pandas.core.series.Series'>
ALGO    0.846967
ATOM    0.498307
VET     0.526359
OMG     0.466097
MANA    0.388679
Name: 23, dtype: float64
熊式-----------------------------------
執行第 30
<class 'pandas.core.series.Series'>
       ALGO      ARDR      VET       NEO      QTUM
0  0.725441  0.626451  0.45931  0.471143  0.539523
<class 'pandas.core.series.Series'>
ALGO    0.725441
ARDR    0.626451
VET     0.459310
NEO     0.471143
QTUM    0.539523
Name: 24, dtype: float64
熊式-----------------------------------
執行第 31
<class 'pandas.core.series.Series'>
       ALGO     THETA       KNC      ARDR      QTUM
0 -0.299336 -0.426429 -0.151973 -0.093478 -0.207799
<class 'pandas.core.series.Series'>
ALGO    -0.299336
THETA   -0.426429
KNC     -0.151973
ARDR    -0.093478
QTUM    -0.207799
Name: 25, dtype: float64
熊式-----------------------------------
執行第 32
<class 'pandas.core.series.Series'>
       ARDR       ZRX       KNC      BTS       ETC
0 -0.038249 -0.276625 -0.309679 -0.19483 -0.329363
<class 'pandas.core.series.Series'>
ARDR   -0.038249
ZRX    -0.276625
KNC    -0.309679
BTS    -0.194830
ETC    -0.329363
Name: 26, dtype: float64
牛式===============================
執行第 33
ETH      0.604365
LINK     0.878505
ADA      0.731233
XLM      0.788182
THETA    1.249643
Name: 27, dtype: float64
報酬 4.251929127114946 %
牛式===============================
執行第 34
SNT      0.749287
XLM      0.623715
LINK     0.620690
THETA    1.327411
ZRX      1.452696
Name: 28, dtype: float64
報酬 4.7737991370996085 %
牛式===============================
執行第 35
XLM      0.349688
OMG      2.330842
SNT      0.669744
THETA    2.844784
ZRX      0.907004
Name: 29, dtype: float64
報酬 7.102062069462998 %
牛式===============================
執行第 36
SNT      0.681094
ZRX      0.882701
BNT      2.026381
OMG      1.649429
THETA    2.547590
Name: 30, dtype: float64
報酬 7.787194606757329 %
牛式===============================
執行第 37
ZRX      0.760017
ADA      1.040318
OMG      1.707475
BNT      1.754058
THETA    1.531396
Name: 31, dtype: float64
報酬 6.79326517827506 %
牛式===============================
執行第 38
ZRX      0.683445
ADA      0.552450
THETA    0.804878
OMG      1.158758
BNT      2.872756
Name: 32, dtype: float64
報酬 6.0722867071581135 %
牛式===============================
執行第 39
KNC      0.925725
THETA    0.400761
VET      0.822613
OMG      0.983270
BNT      3.254288
Name: 33, dtype: float64
報酬 6.3866572583809695 %
牛式===============================
執行第 40
ADA    0.516470
VET    0.937065
KNC    0.697088
OMG    0.489599
BNT    3.617911
Name: 34, dtype: float64
報酬 6.258133219994657 %
牛式===============================
執行第 41
OMG   -0.190158
ADA    0.821298
KNC    1.354416
VET    1.712708
BNT    2.889652
Name: 35, dtype: float64
報酬 6.587915512550456 %
牛式===============================
執行第 42
REP    0.440957
ADA    0.628515
KNC    1.335221
VET    1.976072
BNT    1.606753
Name: 36, dtype: float64
報酬 5.987517842274061 %
牛式===============================
執行第 43
LINK    0.832184
ADA     0.423434
KNC     1.401302
BNT     1.790364
VET     1.485984
Name: 37, dtype: float64
報酬 5.93326830832045 %
牛式===============================
執行第 44
ALGO    0.362628
LINK    0.866180
KNC     0.276261
VET     0.898593
BNT     0.684979
Name: 38, dtype: float64
報酬 3.088641558671662 %
牛式===============================
執行第 45
REP     0.173099
BNT     1.083519
ADA     0.812584
LINK    0.990431
VET     1.086606
Name: 39, dtype: float64
報酬 4.14623762220833 %
牛式===============================
執行第 46
ZEC     0.857033
ADA     0.896688
LINK    1.884354
BNT     1.616783
VET     1.415526
Name: 40, dtype: float64
報酬 6.670384404414285 %
牛式===============================
執行第 47
ALGO    1.920000
VET     0.560176
BNT     0.415160
MANA    1.512755
LINK    2.977178
Name: 41, dtype: float64
報酬 7.385269019483021 %
牛式===============================
執行第 48
ETH     0.653679
ATOM    0.634802
MANA    1.389163
ALGO    1.021475
LINK    1.601639
Name: 42, dtype: float64

報酬 5.300757534153777 %
牛式===============================
執行第 49
QTUM    0.450894
ALGO    0.499719
MANA    1.767089
LINK    1.060226
OMG     2.220293
Name: 43, dtype: float64
報酬 5.998220700256457 %
牛式===============================
執行第 50
NEO      0.457306
THETA    0.519876
LINK     0.382008
MANA     0.691810
OMG      1.288963
Name: 44, dtype: float64
報酬 3.339964128406666 %
牛式===============================
執行第 51
THETA    0.735443
TRX      0.598046
MANA     0.825806
BTS      0.166236
OMG      1.459616
Name: 45, dtype: float64
報酬 3.785147176837843 %
牛式===============================
執行第 52
TRX      0.354301
NEO      0.869061
THETA    0.756667
MANA    -0.214216
OMG      0.895062
Name: 46, dtype: float64
報酬 2.660874067609411 %
牛式===============================
執行第 53
BNB      0.138635
TRX      0.076649
THETA    0.814226
NEO      0.389993
OMG      0.594407
Name: 47, dtype: float64
報酬 2.0139107706373682 %
牛式===============================
執行第 54
TRX      0.082530
BNB      0.269369
NEO     -0.060042
OMG     -0.391437
THETA    0.672602
Name: 48, dtype: float64
報酬 0.5730229312502343 %
牛式===============================
執行第 55
HT      -0.022447
TRX      0.062314
XMR      0.241506
BNB      0.237140
THETA    0.516838
Name: 49, dtype: float64
報酬 1.035351422194354 %
牛式===============================
執行第 56
BTC      0.125830
TRX     -0.138127
BNB      0.552645
XMR      0.511070
THETA    0.585830
Name: 50, dtype: float64
報酬 1.6372478349848967 %
牛式===============================
執行第 57
ZEC     -0.023011
ADA      0.105774
XMR      0.464926
BNB      0.075088
THETA    0.316193
Name: 51, dtype: float64
報酬 0.9389685867693859 %
牛式===============================
執行第 58
LTC      0.149262
BCH      0.122384
BTC      0.245041
THETA    0.052268
XMR      0.322399
Name: 52, dtype: float64
報酬 0.8913543161294579 %
牛式===============================
執行第 59
LINK    0.140777
BCH     0.146834
LTC     0.278172
BTC     0.382228
XMR     0.123902
Name: 53, dtype: float64
報酬 1.0719124354963059 %
牛式===============================
執行第 60
LINK    0.352751
BCH     0.167849
ETH     0.333044
LTC     0.401358
BTC     0.524155
Name: 54, dtype: float64
報酬 1.7791570876649798 %
牛式===============================
執行第 61
ARDR    0.068529
ETH     0.491004
LINK    0.468631
LTC     0.783611
BTC     0.653969
Name: 55, dtype: float64
報酬 2.465743779310638 %
牛式===============================
執行第 62
LINK    0.232580
ETH     0.458753
BTC     0.560513
LTC     0.547500
XRP     1.601812
Name: 56, dtype: float64
報酬 3.40115793527184 %
牛式===============================
執行第 63
BTC     0.459648
DASH    0.405210
SNT     0.513155
XLM     1.008533
XRP     1.285424
Name: 57, dtype: float64
報酬 3.6719708780641676 %
牛式===============================
執行第 64
BTC    0.363230
ADA    0.551572
SNT    0.636039
XLM    1.046790
XRP    1.110337
Name: 58, dtype: float64
報酬 3.7079692739790353 %
牛式===============================
執行第 65
SNT    0.722007
VET    0.672895
BNT    1.124544
XLM    1.283092
XRP    1.315902
Name: 59, dtype: float64
報酬 5.11844009595262 %
牛式===============================
執行第 66
SNT    0.212211
LTC    1.032076
BNT    0.894209
XLM    0.815946
XRP    0.098963
Name: 60, dtype: float64
報酬 3.0534046659602874 %
牛式===============================
執行第 67
BTC      0.722746
XLM      0.167231
BNT      0.102078
LTC      0.569507
THETA    2.418223
Name: 61, dtype: float64
報酬 3.9797860222267385 %
牛式===============================
執行第 68
LTC      1.437695
ARDR     0.239817
BTC      1.264541
DOGE     1.994693
THETA    2.264009
Name: 62, dtype: float64
報酬 7.200755786439275 %
牛式===============================
執行第 69
BTC      0.881258
ETH      1.058507
LTC      0.726087
DOGE     1.723385
THETA    1.770616
Name: 63, dtype: float64
報酬 6.159852827582778 %
牛式===============================
執行第 70
BTC      0.706049
ETH      1.172320
ADA      1.395407
DOGE     1.708913
THETA    1.788295
Name: 64, dtype: float64
報酬 6.770983435837087 %
牛式===============================
執行第 71
ETH      1.092104
MANA     0.712269
ADA      1.213151
DOGE     6.183949
THETA    1.224789
Name: 65, dtype: float64
報酬 10.426262635527099 %
牛式===============================
執行第 72
ALGO      1.613070
ETH       1.633809
ADA       3.003657
THETA     0.366675
DOGE     11.747338
Name: 66, dtype: float64
報酬 18.36454883106761 %
牛式===============================
執行第 73
ETH     1.344080
MANA    3.331658
ADA     4.137999
ZRX     4.235374
DOGE    5.316045
Name: 67, dtype: float64
報酬 18.365156501175235 %
牛式===============================
執行第 74
XLM     0.565913
IOTA    2.184695
ADA     2.380600
ZRX     1.815629
DOGE    4.329297
Name: 68, dtype: float64
報酬 11.276134594895154 %
牛式===============================
執行第 75
ADA     2.748459
BNT     1.881198
HT      2.111444
DOGE    4.422415
BNB     4.222042
Name: 69, dtype: float64
報酬 15.385557651612693 %
牛式===============================
執行第 76
BNT     3.809746
HT      1.640355
ADA     2.267216
BNB     4.529326
DOGE    4.942714
Name: 70, dtype: float64
報酬 17.18935599544355 %
牛式===============================
執行第 77
IOTA    2.223339
ADA     2.028711
BNT     3.281849
BNB     5.163762
DOGE    1.223428
Name: 71, dtype: float64
報酬 13.921090003845492 %
牛式===============================
執行第 78
IOTA     1.501184
THETA    2.647320
BNT      2.317205
MANA     2.782111
BNB      2.638743
Name: 72, dtype: float64
報酬 11.886563245871102 %
牛式===============================
執行第 79
BAT      0.753039
BNT      0.981864
BNB      1.023897
THETA    2.529164
MANA     1.684165
Name: 73, dtype: float64
報酬 6.9721285788233285 %
牛式===============================
執行第 80
BNT      0.332965
BNB      0.264075
ARDR     0.865847
MANA     2.124545
THETA    2.093845
Name: 74, dtype: float64
報酬 5.681275903257931 %
牛式===============================
執行第 81
TRX      1.716810
ARDR     2.961145
BAT      1.846576
THETA    2.928857
MANA     3.011067
Name: 75, dtype: float64
報酬 12.464454811438824 %
牛式===============================
執行第 82
XRP      3.149775
VET      2.106475
THETA    2.034084
ARDR     1.236079
MANA     2.046252
Name: 76, dtype: float64
報酬 10.572665707792993 %
牛式===============================
執行第 83
TRX     NaN
THETA   NaN
MANA    NaN
VET     NaN
XRP     NaN
Name: 77, dtype: float64
報酬 0.0 %